Sp/issue 1006 single choice
google/android-fhir pull request #1008
Opened 2022-01-07 16:57 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1006

**Description**
Design single choice questionnaire json.
Write api to fetch single choice questionnaire json file name.
Apply custom style at application side.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-10 07:03 UTC, santosh-pingle commented
<img width="443" alt="Screen Shot 2022-01-10 at 12 27 19 PM" src="https://user-images.githubusercontent.com/86107848/148728332-65f566c2-e9a8-4034-893c-cd7e3923c944.png">

**Custom style radio button overlay bug #1007**  
<img width="442" alt="Screen Shot 2022-01-10 at 12 28 49 PM" src="https://user-images.githubusercontent.com/86107848/148728365-a53e57bb-10b3-43cd-b5fe-bbe532c00b78.png">

2022-01-25 17:37 UTC, jingtang10 requested changes

2022-01-25 17:37 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      Component.SINGLE_CHOICE -> "single_choice_questionnaire.json"
in this PR, can you make the file name another field of the enum class?

2022-01-26 17:44 UTC, jingtang10 commented
@juanchazo please leave a review if you have time thanks!

2022-01-27 10:06 UTC, jingtang10 approved these changes

2022-01-27 10:50 UTC, merged