Localized date rendering
google/android-fhir pull request #1013
Opened 2022-01-10 10:50 UTC by vvikramraj

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #898 

**Description**
Change to display dates in a locale-specific `DateFormat.DEFAULT` format.

**Alternative(s) considered**
NA

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-17 22:25 UTC, jingtang10 requested changes
Thanks @vvikramraj! Great job writing your first PR in the repo :)

Left a few comments - also, can you please think about handing this for the date time picker? Either same PR or create a follow up PR/issue.

2022-01-17 22:25 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/PatientDetailsViewModel.kt
> +  }
Hm I'm not sure I like the fact that the data model already has string as the date of birth... can we possibly change `PatientListViewModel.PatientItem` to `LocalDate` type to avoid having to have this function?

If that's the case then we can reuse the other utility function you've written.

2022-01-21 08:59 UTC, vvikramraj commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt
> +
Done.

2022-01-21 09:00 UTC, vvikramraj commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> -                    // DatePickerDialog.
Oops! Done.

2022-01-21 09:00 UTC, vvikramraj commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +internal fun getLocalizedDate(localDate: LocalDate?): String {
Done.

2022-01-21 09:00 UTC, vvikramraj commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +internal fun getLocalizedDate(localDate: LocalDate?): String {
Thanks. Done. I did not know about extension properties until now. This is neat!

2022-01-21 09:00 UTC, vvikramraj commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +import java.text.DateFormat
I chose `java.text.DateFormat` over `android.icu.text.DateFormat` because the latter is only available from API level 24 onwards and isn't available through desugaring either. The min SDK for the android-fhir projects is set to 21.****

2022-01-21 09:00 UTC, vvikramraj commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  return SimpleDateFormat.getDateInstance(DateFormat.DEFAULT, Locale.getDefault()).format(instant)
Please refer to previous reply.

2022-01-21 09:00 UTC, vvikramraj commented on demo/src/main/java/com/google/android/fhir/demo/PatientDetailsViewModel.kt
> +  }
Done.

2022-01-25 07:22 UTC, jingtang10 requested changes

2022-01-25 07:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +import java.text.DateFormat
can you do a version check like here: https://github.com/google/android-fhir/blob/cdabfe2a09ddd483e8209d1859b7abab5edca007/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseEncryptionKeyProvider.kt#L85

use a if/when statement so that you use the android class when api level is >=24.

may need to modify the tests too with the annotation https://github.com/google/android-fhir/blob/fadd2adcdb0245e4c1691c8b485107c323c1edc2/datacapture/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt#L34 but you add that annotation on the particular test cases rather than the whole class.

2022-01-31 11:39 UTC, vvikramraj commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +import java.text.DateFormat
Done.

2022-02-01 10:00 UTC, jingtang10 requested changes
Looks good @vvikramraj - just one comment to update the import.

2022-02-02 04:40 UTC, vvikramraj commented on demo/src/main/java/com/google/android/fhir/demo/PatientDetailsViewModel.kt
> +        DateFormat.getDateInstance(DateFormat.DEFAULT).format(date)
:-|  Done.

2022-02-02 10:05 UTC, jingtang10 approved these changes
👍

2022-02-03 09:54 UTC, merged