Sp/1011 multichoice
google/android-fhir pull request #1016
Opened 2022-01-10 13:58 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1011 

**Description**
Design multiple choice questionnaire json.
Write api to fetch multi choice questionnaire json file name.
Apply custom style at application side.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-13 16:00 UTC, santosh-pingle commented
<img width="434" alt="Screen Shot 2022-01-13 at 9 29 06 PM" src="https://user-images.githubusercontent.com/86107848/149364574-ac1c6abc-ab56-4438-8fb9-43d21602e831.png">

2022-01-27 11:59 UTC, jingtang10 requested changes

2022-01-27 11:59 UTC, jingtang10 commented on catalog/src/main/res/values/styles.xml
> +
can we make this the default in the data capture lib?

2022-01-27 11:59 UTC, jingtang10 commented on catalog/src/main/res/values/styles.xml
> +
same thing with the radio button.

sorry i didn't catch this in the previous pr.

i don't see any reason we shouldn't make this the default?

2022-01-28 10:58 UTC, jingtang10 approved these changes
Thanks @santosh-pingle!

2022-01-28 10:58 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
> -            android:textColor="?attr/questionnaireTextColor"
can you also remove this from the `attr.xml` file?

2022-01-28 12:49 UTC, merged