Set questionnaireResponse.questionnaire to questionnaire.url and not questionnaire.id
google/android-fhir pull request #1031
Opened 2022-01-13 04:02 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1028 

**Description**
Set questionnaireResponse.questionnaire to questionnaire.url and not questionnaire.id

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug fix

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-13 08:38 UTC, jingtang10 requested changes
can you add a test case please?

2022-01-17 10:42 UTC, joiskash commented
I have modified an existing test case. Set the url to "http://www.sample-org/FHIR/Resources/Questionnaire/questionnaire-1"

2022-01-17 17:31 UTC, jingtang10 requested changes
Please add test for questionnaire view model

2022-01-18 08:20 UTC, joiskash commented
> Please add test for questionnaire view model

Oops my bad. I have fixed the breaking UTs and also added two new tests.

2022-01-25 11:05 UTC, jingtang10 requested changes
just a few small comments!

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertResourceEquals(viewModel.getQuestionnaireResponse(), QuestionnaireResponse())
rename this test case to `stateHasNoQuestionnaireResponse_shouldCopyQuestionnaireUrl`

and instead of changing the assertion, you should change line 84 to set the url rather than the id.

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun stateHasQuestionnaireResponse_correctQuestionnaireReferenceInQuestionnaireResponse_shouldNotThrowError() {
```suggestion
  fun stateHasQuestionnaireResponse_questionnaireUrlMatches_shouldNotThrowError() {
```

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
in the spirit of having minimum tests, remove the item

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
remove

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
remove

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
remove

2022-01-25 11:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun stateHasQuestionnaireResponse_wrongQuestionnaireReferenceInQuestionnaireResponse_shouldThrowError() {
```suggestion
  fun stateHasQuestionnaireResponse_questionnaireUrlDoesNotMatch_shouldThrowError() {
```

2022-01-25 11:18 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
done

2022-01-25 11:18 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
done

2022-01-25 11:18 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
done

2022-01-25 11:18 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
done

2022-01-25 11:18 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertResourceEquals(viewModel.getQuestionnaireResponse(), QuestionnaireResponse())
done

2022-01-25 14:04 UTC, jingtang10 approved these changes
Thanks @joiskash!

2022-01-25 16:14 UTC, merged