Add ability to validate the min/max for Date on a FHIR Questionnaire
google/android-fhir pull request #1050
Opened 2022-01-18 14:48 UTC by RaaziaTarique

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1040 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-25 14:00 UTC, jingtang10 commented
Hi @RaaziaTarique! Thanks for the PR. If this is ready for review can you mark it so?

2022-02-09 09:15 UTC, jingtang10 requested changes
@RaaziaTarique thanks for this PR!

Can you please point me to any documentation (on hl7.org or other sites) on the expression `today()`? I've seen this expression in questionnaires but couldn't find any actual documentation in the specifications.

2022-02-09 09:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidator.kt
> +        }
what you have done here, is to add the capability to parse an expression and convert it into a value of a different type. This shouldn't be done inside this class. There should be another class that handles the parsing and interpreting of expressions.

likewise for the min value constraint validator. you should not have the code duplication in these 2 classes.

2022-02-09 09:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +            value = DateType(2026, 0, 1)
so this test will start failing in year 2026?

is there a way for you to mock/fake the system date to make this test more stable.

2022-02-09 09:41 UTC, RaaziaTarique commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidator.kt
> +        }
I'll create another class and will do the parsing there and use it on both max and min validator classes.

2022-02-09 09:46 UTC, RaaziaTarique commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +            value = DateType(2026, 0, 1)
Instead of using hardcoded date I can pass 5 years future date from current date. This will stable this test case as well.

2022-02-09 11:16 UTC, RaaziaTarique commented
> today()



> 

I just found this sample "Library" where they using something similar to it http://hl7.org/fhir/uv/cpg/Library-CKDRiskLogic.html. Maybe @f-odhiambo can comment better on it.

2022-02-09 12:01 UTC, f-odhiambo commented
> > today()
> 
> > 
> 
> I just found this sample "Library" where they using something similar to it http://hl7.org/fhir/uv/cpg/Library-CKDRiskLogic.html. Maybe @f-odhiambo can comment better on it.

Looking into this :)

2022-02-09 12:03 UTC, RaaziaTarique commented
> > today()
> 
> > 
> 
> I just found this sample "Library" where they using something similar to it http://hl7.org/fhir/uv/cpg/Library-CKDRiskLogic.html. Maybe @f-odhiambo can comment better on it.

Found the link for this particular filter.  http://hl7.org/fhirpath/#datetime-arithmetic CC: @jingtang10 @f-odhiambo

2022-02-23 20:19 UTC, jingtang10 commented
@RaaziaTarique have you used `FHIRPathEngine` before? See our usage https://github.com/google/android-fhir/search?q=fhirpathengine.

Can you try to use that instead of manually handling expressions?

2022-02-25 07:18 UTC, RaaziaTarique commented
> @RaaziaTarique have you used `FHIRPathEngine` before? See our usage https://github.com/google/android-fhir/search?q=fhirpathengine.
> 
> Can you try to use that instead of manually handling expressions?

@jingtang10, I have not used it previously, checking it now.

2022-03-02 13:02 UTC, RaaziaTarique commented
> > @RaaziaTarique have you used `FHIRPathEngine` before? See our usage https://github.com/google/android-fhir/search?q=fhirpathengine.
> > Can you try to use that instead of manually handling expressions?
> 
> @jingtang10, I have not used it previously, checking it now.

@jingtang10 , I checked that `ResourceMapper` is using `FHIRPathEngine` but currently it's only using (http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression)
 
In `ResourceMapper` I added the functionality to detect "today()" field if passed as an expression and in `ResourceMapper` we are not using http://hl7.org/fhir/StructureDefinition/maxValue and http://hl7.org/fhir/StructureDefinition/minValue expressions as these expressions are being validated separately.

2022-05-30 20:35 UTC, jingtang10 requested changes
@maimoonak @RaaziaTarique @ekigamba please take a look i think this PR's logic is still incorrect.

2022-05-30 20:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidator.kt
> +      answer.value > extension.value.detectTodayDate()
so this is assuming if there's a max value constraint for a date it will be today's date? this is incorrect logic!

2022-05-30 20:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TypeConversionUtil.kt
> +  }
this function signature is not great - it's very confusing. please refactor!

you shouldn't have vastly different behaviors due to date time.

2022-06-04 16:19 UTC, jingtang10 commented
@maimoonak @shoaibmushtaq25 @f-odhiambo can someone take over this PR please?

My main issue with this PR is that the logic is very specific - we can't have this type of hard-coded logic just for `today`. We need to make a change that handles expressions in general. I'm ok with not having a full implementation of that, but the structure needs to be there. At the moment the code logic seems strange.

2022-06-15 11:58 UTC, Tarun-Bhardwaj commented
> @maimoonak @shoaibmushtaq25 @f-odhiambo can someone take over this PR please?
> 
> My main issue with this PR is that the logic is very specific - we can't have this type of hard-coded logic just for `today`. We need to make a change that handles expressions in general. I'm ok with not having a full implementation of that, but the structure needs to be there. At the moment the code logic seems strange.

@maimoonak @shoaibmushtaq25 @f-odhiambo is someone working on the changes suggested by @jingtang10 above?

2022-06-15 19:06 UTC, closed without merging