Upload local changed resources using Bundle transaction
google/android-fhir pull request #1084
Opened 2022-01-27 15:26 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1021 

**Description**
Instead of making individual CRUD request for each local change, we would Bundle multiple resources inside a Bundle Transaction.
This PR also mandates for now that all the resources are created on server using Http PUT instead of POST.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-14 13:46 UTC, jingtang10 requested changes

2022-02-15 07:16 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/api/HapiFhirService.kt
> +  @retrofit2.http.POST(".") suspend fun postData(@Body body: RequestBody): Resource
Done

2022-02-15 07:17 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +      flow {
Yes it does :)

2022-02-15 07:17 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/BundlePayloadGenerator.kt
> +  private val bundleType: Bundle.BundleType = Bundle.BundleType.TRANSACTION,
Removed it.

2022-02-15 07:17 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/BundlePayloadGenerator.kt
> +internal class BundlePayloadGenerator(
Done

2022-02-15 07:18 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/BundlePayloadGenerator.kt
> +internal class BundlePayloadGenerator(
I am not sure if this class has to be a singleton. It can be a simple object that does the generation and dies down.

2022-02-15 07:28 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/DataSource.kt
> +  suspend fun postBundle(payload: String): Resource
Yes definitely we should take another look at the  `DataSource` interface.

2022-02-18 13:24 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/BundlePayloadGenerator.kt
> +internal class BundlePayloadGenerator(
As per our discussion, I have updated the code .

2022-02-18 16:58 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
>          database.deleteUpdates(it.first)
Sorry, I am very new to flow. I may not talk any sense below

What happen if the update fail? Should we not call deleteUpdates if the update fails?

2022-02-18 16:58 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +            it.response.location.split("/").let { location ->
1. super nit: rename location to paths or segments.
1. There is an assumption that the location array has at least a size two. Would there be any chance that the server returns an unexpected location? How would you handle it?

2022-02-18 16:58 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        // Leave it for now.
nit: for the ease of debugging, could you please add a log?

2022-02-18 16:58 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentGenerator.kt
> +  /** Should return [Resource] for the [LocalChangeEntity]. */
nit: Remove should. Just `Returns [IBaseResource]...` Please also specific when would IBaseResource be null.

2022-02-18 16:58 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/sync/bundle/TransactionBundleGenerator.kt
> +internal abstract class TransactionBundleGenerator(
Is abstract needed? There is no abstract method in this class. Can this be just an internal object?

2022-02-18 16:58 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/sync/bundle/TransactionBundleGenerator.kt
> +      return when (httpVerbToUseForCreate) {
`when` is a bit overkill for now. This can just be 
```
return if (httpVerbToUseForCreate == Bundle.HTTPVerb.PUT && httpVerbToUseForUpdate == Bundle.HTTPVerb.PATCH) {
 PutForCreateAndPatchForUpdateBasedTransactionGenerator
} else {
  throw IllegalArgumentException(...)
}

```

2022-02-18 17:17 UTC, jingtang10 approved these changes
like the abstraction of the generator much better - thanks @aditya-07 🙏

2022-02-21 08:41 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/data/HapiFhirResourceDataSource.kt
> +    return service.postData(payload.toRequestBody("application/fhir+json".toMediaType()))
Done

2022-02-21 08:45 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        // Leave it for now.
Done.

2022-02-21 08:47 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
>          database.deleteUpdates(it.first)
In our current path, `upload` only emits for the successful updates so the checks are not required as such.
But, I agree with you that we should have some checks to make sure a `failed` update doesn't cause any trouble. Will do the change in a follow-up PR.

2022-02-21 13:50 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        // Leave it for now.
Done

2022-02-21 13:51 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentGenerator.kt
> +  /** Should return [Resource] for the [LocalChangeEntity]. */
Done

2022-02-21 13:51 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentGenerator.kt
> +  fun getEntry(squashedLocalChange: SquashedLocalChange): Bundle.BundleEntryComponent {
Done

2022-02-21 13:52 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/TransactionBundleGenerator.kt
> +internal abstract class TransactionBundleGenerator(
Made it a regular open class.

2022-02-21 13:52 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/TransactionBundleGenerator.kt
> +      return when (httpVerbToUseForCreate) {
done

2022-02-21 13:58 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +            it.response.location.split("/").let { location ->
1. `response` is part of the `hapi-fhir-structures` library that we use, so can't rename `location`.
2. The server is supposed to return the location of the resource , either relative or absolute. So have updated the code to handle the cases and added some comments.

2022-02-21 14:15 UTC, jingtang10 requested changes

2022-02-21 14:15 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +      if (hasEtag() && hasLastModified() && hasLocation()) {
i don't like how this depends on the etag and last modified, but the function name doesn't mention this at all.

Either make this function return a new data class that includes resource id, type, etag, timestamp. or make a separate function that does the check.

2022-02-21 15:10 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +      if (hasEtag() && hasLastModified() && hasLocation()) {
I have removed the check from this function and moved it up. This didn't required the `etag` and `last modified` checks.

2022-02-21 15:39 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentGenerator.kt
> + * Creates [Bundle.BundleEntryComponent] for each [LocalChangeEntity] to be added to the [Bundle].
This looks like the documentation for getEntry though. You also have getEntryResource, which has nothing to do with `Bundle.BundleEntryComponent` to `LocalChangeEntry` convention.

2022-02-21 15:50 UTC, stevenckngaa commented on engine/src/test/java/com/google/android/fhir/sync/bundle/TransactionBundleGeneratorTest.kt
> +            resourceId = "Patient-002",
Should this be Patient-003?

2022-02-24 14:15 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentGenerator.kt
> +  fun getEntry(squashedLocalChange: SquashedLocalChange): Bundle.BundleEntryComponent {
My bad. Updated it now.

2022-02-24 14:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentImplementations.kt
> +      contentType = "application/json-patch+json"
Created `ContentTypes` in engine. The val's declared in the previous commits now also reference it

2022-02-24 14:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/bundle/HttpVerbBasedBundleEntryComponentGenerator.kt
> + * Creates [Bundle.BundleEntryComponent] for each [LocalChangeEntity] to be added to the [Bundle].
Update kdocs for the class and various apis.

2022-02-24 14:20 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/bundle/TransactionBundleGeneratorTest.kt
> +            resourceId = "Patient-002",
Updated.

2022-02-25 11:10 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +            it.response.location.split("/").let { location ->
My bad. The code has been refactored and the lambda param is not there anymore.

2022-02-25 11:43 UTC, jingtang10 approved these changes

2022-02-25 12:18 UTC, merged