Ns/questionnaire questionnaire response read only review mode
google/android-fhir pull request #1094
Opened 2022-02-01 08:42 UTC by nsabale7

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #227 

**Description**
Feature to review question/answers in list view from questionnaire and questionnaireResponse

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
 Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-04 10:17 UTC, joiskash requested changes
Thanks Nitin! I have added a few comments, please have a look

2022-02-04 10:17 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +      Questionnaire.QuestionnaireItemType.CHOICE -> {
Not sure why this is there.. why are we handling choice differently? I think this should be the else branch and all nested answers should be fetched

2022-02-04 10:17 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireResponseItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +internal object QuestionnaireResponseItemSimpleQuestionAnswerDisplayViewHolderFactory :
Can you please add a comment describing what this view does. You can refer to other view holder factories for that

2022-02-04 10:28 UTC, joiskash commented
Should we pass callbacks to the Fragment constructor for the three buttons in the view? i.e. submit, edit and back (personally I feel we do not need a back button)

So the Fragment constructor declaration will look like this
```
QuestionnaireResponseDisplayFragment(onSubmit()->Unit,onEdit()->Unit,onBack()->Unit){
 .
 .
 .
}
```
And the usage will look something like this

```
val questionnaireResponseDisplay = QuestionnaireResponseDisplayFragment( this::onSubmit, this::onEdit, this::onBack )

fun onSubmit(){
//Not implemented
}


fun onEdit(){
//Not implemented
}


fun onBack (){
//Not implemented
}
```
cc: @jingtang10

2022-02-09 10:28 UTC, jingtang10 commented
Thanks so much @nsabale7 for this PR and @joiskash for helping with this.

@shelaghm @fredhersch can you please take a look at the screenshot attached?

2022-02-09 17:45 UTC, shelaghm commented
@nsabale7 @joiskash @jingtang10 

Screenshot looks good to me. Nice work! 

- Is "Lab checkin" intended to be there? It looks a bit out of place?
- A small nit, but the padding between the lines and the text is not consistent at the top and the bottom. 16px is a good starting point for the padding.

2022-02-15 10:14 UTC, jingtang10 commented
@santosh-pingle please take a look

2022-02-15 10:15 UTC, jingtang10 commented
@juanchazo fyi

2022-02-15 10:50 UTC, nsabale7 commented
@shelaghm Thanks

- "Lab CheckIn" is the name/title of the questionnaire and it is placed according to the design shared in #227.
- Yeah, padding looks inconsistent. I will note it down and do the changes.

2022-02-18 01:35 UTC, shelaghm commented
> * "Lab CheckIn" is the name/title of the questionnaire and it is placed according to the design shared in [SDC feature for read-only mode for questionnaire #227](https://github.com/google/android-fhir/issues/227).

Ah, I see. Looks like there's two names of the survey in this example? Lab results and sample questionnaire review. I would suggest that the name of survey goes in the purple top header if possible?

2022-02-25 09:31 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayFragment.kt
> +    val questionnaireNameText = view.findViewById<TextView>(R.id.questionnaire_name_text)
Renamed questionnaireNameText to questionnaireTitleText

2022-02-25 09:34 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireResponseItemViewItem.kt
> + * the CheckBox and initial yes/no answer for the CheckBox).
I have updated the comment.

2022-02-25 09:42 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +      null
If question type is of Coding and it is not answered, we wont get display or code. It will be better if we return null so that it can be safely handled.

2022-02-25 09:44 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +val QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent.displayString: String?
Adding ? so it can be handled in QuestionnaireResponseItemViewItem.

2022-02-25 10:07 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +          FhirContext.forR4()
Replaced at all required places

2022-02-25 10:07 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayFragment.kt
> +    const val EXTRA_QUESTIONNAIRE_RESPONSE_JSON_STRING = "questionnaire-response"
Done

2022-02-25 10:08 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +      state[QuestionnaireResponseDisplayFragment.EXTRA_QUESTIONNAIRE_RESPONSE_JSON_STRING]
Done

2022-02-25 10:08 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +      Questionnaire.QuestionnaireItemType.CHOICE -> {
Handled in else condition

2022-02-25 10:08 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireResponseItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +internal object QuestionnaireResponseItemSimpleQuestionAnswerDisplayViewHolderFactory :
Done

2022-03-15 11:54 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayFragment.kt
> +    inflater.context.obtainStyledAttributes(R.styleable.QuestionnaireTheme).use {
Have you addressed this?

2022-03-15 11:58 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayFragment.kt
> +     * If this and [EXTRA_QUESTIONNAIRE_JSON_STRING] are provided, this extra-uri takes precedence.
replace  [**EXTRA_QUESTIONNAIRE_RESPONSE_JSON_STRING**]  instead of [EXTRA_QUESTIONNAIRE_JSON_STRING]

2022-03-15 11:59 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/QuestionnaireResponseDisplayFragmentCallbackType.kt
> +  SUBMIT("submit");
extract "back" etc to string constants

2022-03-15 12:02 UTC, joiskash reviewed
@Tarun-Bhardwaj It would be good to get a review from the google team! I have gone through and looks like its ready for feedback

2022-04-12 15:38 UTC, juanchazo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +          val questionnaireJson: String =
Can we extract this logic into a helper method and reuse it for the questionnaire and questionnaireResponse init blocks e.g. `fun parseResourceFromJson(json: String)` and cast that as `Questionnaire` or `QuestionnaireResponse`. Same goes for the URI logic - I think it'd make this easier to read, but optional.

2022-04-12 15:38 UTC, juanchazo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +          val questionnaireJson: String =
Also can we import the state keys directly instead of keeping the `QuestionnaireResponseDisplayFragment` part for easier readability.

2022-04-12 15:38 UTC, juanchazo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +        state.get<String?>(
How come we check this is not null but we don't check if the JSON string for the `Questionnaire` is null?

2022-04-12 15:38 UTC, juanchazo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +      } while (questionnaireItem!!.linkId != questionnaireResponseItem.linkId)
If `questionnaireItem` is nullable, why are we assuming it is non-null here?

2022-04-12 15:38 UTC, juanchazo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +      null
How come we chose to handle it differently than `Questionnaire.QuestionnaireItemAnswerOptionComponent.displayString` where we throw an exception if coding is null?

2022-04-13 07:48 UTC, nsabale7 commented
Based on the feedback from @jingtang10 we will make the following changes to this PR:

2022-04-13 11:39 UTC, joiskash commented
As per the feedback from the @jingtang10 we have tried to reuse as much of the existing code as possible:

1. We will be introducing a new `const val QUESTIONNAIRE_REVIEW_MODE = "review-mode"` that can be passed as an argument to the fragment . That will decide whether the fragment should open in review mode or in data collection mode
2. Introduce a new mutableStateFlow i.e. reviewMode in the QuestionnaireViewModel that will be set to false by default. We can keep this internal so that the QuestionnaireFragment can modify based on user input / developer code.
3. Introduce a flag in the QuestionnaireAdapter called reviewMode, if set then an early return will be triggered of the simple questionnaire-answer view.
```
internal class QuestionnaireItemAdapter {
...
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): QuestionnaireItemViewHolder {
    ...
         if(reviewMode){
             return QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.create(parent)  
         }
    ...
    }
...
}
```
5. Change the questionnaireStateFlow to pass null to pagination if reviewMode is set.
```
/** [QuestionnaireState] to be displayed in the UI. */
internal val questionnaireStateFlow: Flow<QuestionnaireState> =
  combine(modificationCount,pageFlow,reviewMode){ _, pagination,reviewMode ->
    if(reviewMode){
      getQuestionnaireState(
        questionnaireItemList = questionnaire.item,
        questionnaireResponseItemList = questionnaireResponse.item,
        pagination = null,
      )
    }else{
      getQuestionnaireState(
        questionnaireItemList = questionnaire.item,
        questionnaireResponseItemList = questionnaireResponse.item,
        pagination = pagination,
      )
    }

  }
    .stateIn(
      viewModelScope,
      SharingStarted.Lazily,
      initialValue =
      getQuestionnaireState(
        questionnaireItemList = questionnaire.item,
        questionnaireResponseItemList = questionnaireResponse.item,
        pagination = questionnaire.getInitialPagination(),
      )
    )
```
6. By default perform all validations on the last page before changing the Next page button to Review button cc: @dubdabasoduba . We got on call with the Ona team and thought that this should be the default with a way for devs to override. So we will add an open function in the QuestionnaireFragment `open fun lastPageBehaviour` with this default implementation.
7. Add an answerString property to the QuestionnaireItemViewItem to convert answers to display strings for the view. This is going to be the same as what is in 'QuestionnaireResponseItemViewItem' in the current PR.

2022-04-13 23:09 UTC, dubdabasoduba commented
> As per the feedback from the @jingtang10 we have tried to reuse as much of the existing code as possible:
> 
> 1. We will be introducing a new `const val QUESTIONNAIRE_REVIEW_MODE = "review-mode"` that can be passed as an argument to the fragment . That will decide whether the fragment should open in review mode or in data collection mode
> 2. Introduce a new mutableStateFlow i.e. reviewMode in the QuestionnaireViewModel that will be set to false by default. We can keep this internal so that the QuestionnaireFragment can modify based on user input / developer code.
> 3. Introduce a flag in the QuestionnaireAdapter called reviewMode, if set then an early return will be triggered of the simple questionnaire-answer view.
> 
> ```
> internal class QuestionnaireItemAdapter {
> ...
>     override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): QuestionnaireItemViewHolder {
>     ...
>          if(reviewMode){
>              return QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.create(parent)  
>          }
>     ...
>     }
> ...
> }
> ```
> 
> 5. Change the questionnaireStateFlow to pass null to pagination if reviewMode is set.
> 
> ```
> /** [QuestionnaireState] to be displayed in the UI. */
> internal val questionnaireStateFlow: Flow<QuestionnaireState> =
>   combine(modificationCount,pageFlow,reviewMode){ _, pagination,reviewMode ->
>     if(reviewMode){
>       getQuestionnaireState(
>         questionnaireItemList = questionnaire.item,
>         questionnaireResponseItemList = questionnaireResponse.item,
>         pagination = null,
>       )
>     }else{
>       getQuestionnaireState(
>         questionnaireItemList = questionnaire.item,
>         questionnaireResponseItemList = questionnaireResponse.item,
>         pagination = pagination,
>       )
>     }
> 
>   }
>     .stateIn(
>       viewModelScope,
>       SharingStarted.Lazily,
>       initialValue =
>       getQuestionnaireState(
>         questionnaireItemList = questionnaire.item,
>         questionnaireResponseItemList = questionnaireResponse.item,
>         pagination = questionnaire.getInitialPagination(),
>       )
>     )
> ```
> 
> 6. By default perform all validations on the last page before changing the Next page button to Review button cc: @dubdabasoduba . We got on call with the Ona team and thought that this should be the default with a way for devs to override. So we will add an open function in the QuestionnaireFragment `open fun lastPageBehaviour` with this default implementation.
> 7. Add an answerString property to the QuestionnaireItemViewItem to convert answers to display strings for the view. This is going to be the same as what is in 'QuestionnaireResponseItemViewItem' in the current PR.


@joiskash This looks good to me. 

> Change the questionnaireStateFlow to pass null to pagination if review mode is set.
This seems to suggest that the pagination will not work when the review mode is activated is that true? My context on pagination is the ability of a form to show multiple steps.  I might be very wrong on this. If so please correct me. 

@ellykits @maimoonak @ndegwamartin Do you guys mind reviewing this too.

2022-04-18 06:31 UTC, joiskash commented
Write access has been removed, so we will be moving to a fork that @nsabale7 will create soon. 

FYI @dubdabasoduba there will be a small delay.

2022-04-19 12:58 UTC, nsabale7 commented
FYI, This feature is continued in new [PR#1310](https://github.com/google/android-fhir/pull/1310) due to git write access.

2022-04-19 13:02 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +          val questionnaireJson: String =
This file has been removed as this feature was refactored to use single fragment.

2022-04-24 10:32 UTC, jingtang10 commented
> As per the feedback from the @jingtang10 we have tried to reuse as much of the existing code as possible:
> 
> 1. We will be introducing a new `const val QUESTIONNAIRE_REVIEW_MODE = "review-mode"` that can be passed as an argument to the fragment . That will decide whether the fragment should open in review mode or in data collection mode
> 2. Introduce a new mutableStateFlow i.e. reviewMode in the QuestionnaireViewModel that will be set to false by default. We can keep this internal so that the QuestionnaireFragment can modify based on user input / developer code.
> 3. Introduce a flag in the QuestionnaireAdapter called reviewMode, if set then an early return will be triggered of the simple questionnaire-answer view.
> 
> ```
> internal class QuestionnaireItemAdapter {
> ...
>     override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): QuestionnaireItemViewHolder {
>     ...
>          if(reviewMode){
>              return QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.create(parent)  
>          }
>     ...
>     }
> ...
> }
> ```
> 
> 5. Change the questionnaireStateFlow to pass null to pagination if reviewMode is set.
> 
> ```
> /** [QuestionnaireState] to be displayed in the UI. */
> internal val questionnaireStateFlow: Flow<QuestionnaireState> =
>   combine(modificationCount,pageFlow,reviewMode){ _, pagination,reviewMode ->
>     if(reviewMode){
>       getQuestionnaireState(
>         questionnaireItemList = questionnaire.item,
>         questionnaireResponseItemList = questionnaireResponse.item,
>         pagination = null,
>       )
>     }else{
>       getQuestionnaireState(
>         questionnaireItemList = questionnaire.item,
>         questionnaireResponseItemList = questionnaireResponse.item,
>         pagination = pagination,
>       )
>     }
> 
>   }
>     .stateIn(
>       viewModelScope,
>       SharingStarted.Lazily,
>       initialValue =
>       getQuestionnaireState(
>         questionnaireItemList = questionnaire.item,
>         questionnaireResponseItemList = questionnaireResponse.item,
>         pagination = questionnaire.getInitialPagination(),
>       )
>     )
> ```
> 
> 6. By default perform all validations on the last page before changing the Next page button to Review button cc: @dubdabasoduba . We got on call with the Ona team and thought that this should be the default with a way for devs to override. So we will add an open function in the QuestionnaireFragment `open fun lastPageBehaviour` with this default implementation.
> 7. Add an answerString property to the QuestionnaireItemViewItem to convert answers to display strings for the view. This is going to be the same as what is in 'QuestionnaireResponseItemViewItem' in the current PR.

thanks @joiskash. I'm yet to go over this PR (and #1310) in detail. But just want to highlight that this excellent write-up and a great example for all PR authors. This outlines the main changes in the PR, which means the reviewer can understand the PR more quickly, which means the review is going to be better quality.

thanks again for this.

2022-04-24 11:00 UTC, jingtang10 commented
@nsabale7 can you please address all the comments and leave a comment if they're addressed in the new PR? thanks.

2022-04-24 11:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayFragment.kt
> +     * If this and [EXTRA_QUESTIONNAIRE_JSON_STRING] are provided, this extra-uri takes precedence.
Sorry late to the party. If it's not too much work, can you separate this into a separate PR, and link the PR to this issue: #916?

@nsabale7 @joiskash

2022-04-24 11:06 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireResponseItemViewItem.kt
> +                true -> "Yes"
sadly this is something we'll have to deal with. i was hoping that android would have default strings defined for things like Yes/No. But the `android.R.string.yes` and `android.R.string.no` default to `OK` and `Cancel`...

but as long as we use resources, rather than hardcoded values, developers can provide their own translation if needed.

@nsabale7 please change these to use resources.

2022-04-25 18:05 UTC, jingtang10 commented
closing to continue discussion in #1310

2022-04-25 18:05 UTC, closed without merging

2022-04-27 06:43 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +        state.get<String?>(
This file has been removed as this feature was refactored to use single fragment.

2022-04-27 06:43 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayViewModel.kt
> +      } while (questionnaireItem!!.linkId != questionnaireResponseItem.linkId)
This file has been removed as this feature was refactored to use single fragment.

2022-04-27 06:46 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireResponseItemViewItem.kt
> +              when (it.valueBooleanType?.value) {
Handling answerString in QuestionnaireItemViewItem data class without safecalls. #1310

2022-04-27 06:48 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireResponseItemViewItem.kt
> +                true -> "Yes"
Need some help on this. To use resources we require context and as we are in data class i dont find any way.

2022-04-27 06:50 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireResponseDisplayFragment.kt
> +     * If this and [EXTRA_QUESTIONNAIRE_JSON_STRING] are provided, this extra-uri takes precedence.
Sure I can work on this.