Catalog, show questionnaire response when submit questionnaire button get clicked.
google/android-fhir pull request #1097
Opened 2022-02-01 10:48 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1081 

**Description**
Collect questionnaire response json string.
Design and implement fragment to show questionnaire json output string
Navigate back to landing page on close button click.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-10 09:59 UTC, jingtang10 requested changes
Thanks @santosh-pingle for this! Good work!

1. can you add some screenshots please?
2. does the submit button always show up? i think we probably shouldn't have it in the components?

2022-02-15 14:24 UTC, jingtang10 commented
can you put the submit button as a menu item in the app bar?

2022-02-16 10:47 UTC, santosh-pingle commented
> can you put the submit button as a menu item in the app bar?

done.

2022-02-18 09:59 UTC, santosh-pingle commented
Submit menu added to overflow menu until #1088 get fixed.

<img width="415" alt="Screen Shot 2022-02-18 at 3 26 38 PM" src="https://user-images.githubusercontent.com/86107848/154660213-a77268d3-71da-48f0-9899-d515ade6bbe3.png">
<img width="414" alt="Screen Shot 2022-02-18 at 3 26 54 PM" src="https://user-images.githubusercontent.com/86107848/154660232-89395ea4-4206-4367-a29d-675d0cf0b4bd.png">

2022-02-18 17:24 UTC, jingtang10 approved these changes

2022-02-18 17:24 UTC, jingtang10 commented on catalog/src/main/res/menu/submit_questionnaire_menu.xml
> +<?xml version="1.0" encoding="utf-8" ?>
rename this file to just menu.xml

this menu is not exclusively for the submit button, there might be other buttons added to it

2022-02-18 17:59 UTC, jingtang10 requested changes

2022-02-21 05:28 UTC, santosh-pingle commented
looking into the review comments.

2022-02-21 07:24 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +      childFragmentManager.commit { replace(R.id.container, fragment, QUESTIONNAIRE_FRAGMENT_TAG) }
Reverted change but added some checks when Questionnaire fragment get added.

- Reason to make this change : 
QuestionnaireFragment is added as child fragment to DemoQuestionnaire fragment, and on submit click it was navigating to QuestionnaireResponseFragment where response was shown. But when it navigate back to DemoQuestionnaire fragment every time new Questionnaire Fragment gets added. That was reason replace() was used instead of add().
But with this approach filled form state was not saved when it came back from response display fragment screen.

- As per new change: 
add() is kept as it is, only check is added if Questionnaire fragment is already added as child fragment then do not add new Questionnaire Fragment.

2022-02-22 11:36 UTC, jingtang10 requested changes

2022-02-22 11:36 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +      ) {
```suggestion
      if (childFragmentManager.findFragmentByTag(QUESTIONNAIRE_FRAGMENT_TAG) == null) {
```

should be enough

2022-02-23 20:00 UTC, jingtang10 approved these changes

2022-02-24 02:11 UTC, merged