1001 fix form validation
google/android-fhir pull request #1102
Opened 2022-02-02 09:45 UTC by aurangzaibumer

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-04 08:01 UTC, joiskash commented
Can you please update the PR template. You can refer to other PRs to know how to do this. eg: https://github.com/google/android-fhir/pull/1106

2022-02-04 12:08 UTC, aurangzaibumer commented
> Can you please update the PR template. You can refer to other PRs to know how to do this. eg: #1106

thanks, just updated the template.

2022-02-09 15:55 UTC, jingtang10 commented
Please take a look at this section of the wiki: https://github.com/google/android-fhir/wiki/Structured-Data-Capture-Library#provide-configuration

2022-02-09 16:04 UTC, jingtang10 commented
discussed offline with @aurangzaibumer: @ellykits and @aurangzaibumer please consider using the `DataCaptureConfg` class. Application developers should be able to set the config using the link I posted above.

If that is indeed a problem, then please let us know so we can make sure the APIs are easy to use.

Just a final note, this way of providing library config is consistent with other android libraries such as work manager.

2022-02-09 17:45 UTC, ellykits commented
@jingtang10 This is well noted. There was no problem using the `DataCaptureConfg` class. However, one of the potential issues we may  encounter in FHIRCore (currently using Hilt for Dependency Injection) is in the tests requiring the application to be cast into `DataCaptureConfig.Provider` instance. Hilt provides `HiltTestApplication` that is recommended to be used in the instrumentation tests instead of a custom test application class. 

**Note** that it is possible to provide a custom application for Hilt tests however for best practices it is not recommended to avoid accidental leaks of state used in the application class, that is documented here [Hilt custom test application](https://dagger.dev/hilt/testing.html#custom-test-application).

As an alternative approach to implementing the `DataCaptureConfig.Provider` interface via the `Application` class we can consider providing the `DataCaptureConfig` as a singleton initialized in the `onCreate` method of the `Application`. Implementing a custom Hilt test application for our tests would also still address our concern.

2022-02-10 10:12 UTC, jingtang10 commented
> @jingtang10 This is well noted. There was no problem using the `DataCaptureConfg` class. However, one potential issue we may encounter in FHIRCore (currently using Hilt for Dependency Injection) is in the tests that would require the application to be cast into `DataCaptureConfig.Provider` instance. Hilt provides `HiltTestApplication` that is recommended to be used in the instrumentation tests instead of a custom test application class.
> 
> **Note** that it is possible to provide a custom application for Hilt tests however for best practices it is not recommended to avoid accidental leaks of state used in the application class, that is documented here [Hilt custom test application](https://dagger.dev/hilt/testing.html#custom-test-application).
> 
> As an alternative approach to implementing the `DataCaptureConfig.Provider` interface via the `Application` class we can consider providing the `DataCaptureConfig` through a singleton initialized in the `onCreate` method of the `Application`. Implementing a custom Hilt test application for our tests would also still address our concern.

thanks @ellykits - i don't really understand the reasoning behind Hilt's recommendation besides "it's easy to get it wrong" it seems a bit weak to me. @yigit @stevenckngaa @kevinmost fyi. let me do some research and get back to you on this one.

2022-02-10 13:17 UTC, kevinmost commented
> As a best practice, avoid using @CustomTestApplication and instead use HiltTestApplication in your tests. In general, having your Activity, Fragment, etc. be independent of the parent they are contained in makes it easier to compose and reuse it in the future.

Sounds like the main concern is that it introduces a stronger coupling between your Hilt Application and the component (Fragment, Activity, etc)?

2022-02-16 09:30 UTC, jingtang10 commented
i chatted with someone working on hilt and they said: `It is just a 'recommendation', we know it might not be possible for all situations to only use the HiltTestApplication which is why there is also an API for custom applications.`

2022-02-16 10:05 UTC, ellykits commented
Cool thanks.

On Wed, Feb 16, 2022, 12:30 Jing Tang ***@***.***> wrote:

> i chatted with someone working on hilt and they said: It is just a
> 'recommendation', we know it might not be possible for all situations to
> only use the HiltTestApplication which is why there is also an API for
> custom applications.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/android-fhir/pull/1102#issuecomment-1041288391>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGM667BL4B4OUKECQOB4CDLU3NVD5ANCNFSM5NLRF7UA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-22 14:54 UTC, jingtang10 requested changes

2022-02-22 14:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    }
if you scroll pass the item so that the item disappears, and scroll back so the item reappears, the error message would disappear in this case. this is incorrect.

there needs to be some kind of state attached to the questionnaire item so you can avoid displaying validation result the first time...

2022-02-28 15:05 UTC, jingtang10 commented
as discussed on friday please see #1209 for a suggested fix.

there're a few issues related to this:

1. we need to unset the on click listener when setting the answer programatically to the UI
2. the `getValue` function in `QuestionnaireItemEditTextStringViewHolderDelegate.kt` should always return a non-null value. This is because there will always be a `QuestionnaireResponseItem` even if it doesn't have an answer.
3. Empty string should be considered by the required validator as an invalid answer.

2022-03-02 06:49 UTC, aurangzaibumer commented
> as discussed on friday please see #1209 for a suggested fix.
> 
> there're a few issues related to this:
> 
> 1. we need to unset the on click listener when setting the answer programatically to the UI
> 2. the `getValue` function in `QuestionnaireItemEditTextStringViewHolderDelegate.kt` should always return a non-null value. This is because there will always be a `QuestionnaireResponseItem` even if it doesn't have an answer.
> 3. Empty string should be considered by the required validator as an invalid answer.

Thanks Jing
As discussed on Friday, added other types check on Validator. Please share feedback.

fun QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent.isNotValid(): Boolean =
  when {
    hasValueStringType() && valueStringType.value.isNullOrEmpty() -> true
    hasValueBooleanType() && valueBooleanType.isEmpty -> true
    hasValueDecimalType() && valueDecimalType.isEmpty -> true
    hasValueDateType() && valueDateType.isEmpty -> true
    hasValueDateTimeType() && valueDateTimeType.isEmpty -> true
    hasValueQuantity() && valueQuantity.isEmpty -> true
    hasValueCoding() && valueCoding.isEmpty -> true
    hasValue() && value.isEmpty -> true
    hasValueUriType() && valueUriType.isEmpty -> true
    hasValueAttachment() && valueAttachment.isEmpty -> true
    else -> false
  }

2022-03-03 13:40 UTC, aurangzaibumer commented
Hello @jingtang10 

I locally compared the Jacoco report of the master branch with that of my branch and verified that the lines of code that dropped in coverage were not part of the changes I made. Thanks 

cc @f-odhiambo @maimoonak

2022-03-07 11:12 UTC, Tarun-Bhardwaj commented
@f-odhiambo , has this PR been internally reviewed and ready for review by Google?

2022-03-07 13:58 UTC, maimoonak approved these changes

2022-03-07 14:00 UTC, maimoonak commented
@Tarun-Bhardwaj yes. this has been reviewed.

2022-03-14 12:32 UTC, f-odhiambo commented
@Tarun-Bhardwaj any feedback on this?

2022-03-15 11:37 UTC, jingtang10 requested changes

2022-03-15 11:37 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    "com.google.android.fhir.datacapture.DataCaptureTestRunner"
do you still need this and the changes in the configuration? seems to me they can all be reverted?

2022-03-15 11:37 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/DataCaptureInstrumentationTestApplication.kt
> +/*
do you still need this class?

2022-03-15 11:37 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/DataCaptureTestRunner.kt
> +/*
and this

2022-03-15 11:37 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noError_shouldShowNoErrorMessageAtStart() {
you need to add a new test cases. there'll be two different scenarios. 1) questionnaire response without an answer 2) questionnaire response with an answer which has no value

the behavior should be different.

2022-03-15 11:37 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noError_shouldShowNoErrorMessageAtStart() {
same here

2022-03-21 07:14 UTC, aurangzaibumer commented
As per discussion with @jingtang10  on 18 March 2022

We've decided to keep a flag on Validation API to work differently whenever submit button is pressed. We will incorporate this change on separate PR. Thanks

cc @f-odhiambo

2022-03-22 08:13 UTC, jingtang10 requested changes

2022-03-22 08:13 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noError_shouldShowNoErrorMessageAtStart() {
is this addressed?

2022-03-22 08:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    if (delegate.questionnaireItemViewItem.questionnaireResponseItem.hasAnswer()) {
Add some comment here to explain why:

```suggestion
    // Only validate questionnaire items with answer(s). This is so that we do not show all the validation errors at once when the user opens a new questionnaire for the first time. Instead, the validation errors are shown when the user goes through each question.
    // Notice the difference between a questionnnaire response item without answer, and a questionnaire with an answer without value. 
    if (delegate.questionnaireItemViewItem.questionnaireResponseItem.hasAnswer()) {
```

2022-03-29 13:20 UTC, Tarun-Bhardwaj commented
@aurangzaibumer , have the last few comments from @jingtang10 addressed?
CC: @f-odhiambo

2022-03-29 16:11 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noError_shouldShowNoErrorMessageAtStart() {
```
@Test
  @UiThreadTest
  fun displayValidationResult_questionnaireResponseAnswerWithNoValue_shouldShowErrorMessage() {
    viewHolder.bind(
      QuestionnaireItemViewItem(
        Questionnaire.QuestionnaireItemComponent().apply { required = true
          addAnswerOption(
            Questionnaire.QuestionnaireItemAnswerOptionComponent().apply {
              value =  StringType("hello")
            }
          )},
        QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
          addAnswer()
        }
      ) {}
    )

    assertThat(viewHolder.itemView.findViewById<TextInputLayout>(R.id.text_input_layout).error)
      .isEqualTo(viewHolder.itemView.context.getString(R.string.required_constraint_validation_error_msg))
  }


  @Test
  @UiThreadTest
  fun displayValidationResult_noQuestionnaireResponseAnswer_shouldShowNoErrorMessage() {
    viewHolder.bind(
      QuestionnaireItemViewItem(
        Questionnaire.QuestionnaireItemComponent().apply { required = true
          addAnswerOption(
            Questionnaire.QuestionnaireItemAnswerOptionComponent().apply {
              value = StringType("hello")
            }
          )},
        QuestionnaireResponse.QuestionnaireResponseItemComponent()
      ) {}
    )

    assertThat(viewHolder.itemView.findViewById<TextInputLayout>(R.id.text_input_layout).error)
      .isEqualTo(null)
  }
```

I've added two cases just like you mentioned for class QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest, can you please review.

2022-03-30 09:34 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noError_shouldShowNoErrorMessageAtStart() {
as per investigation, Pickerview/Radio button can have only two states
1 -> no QR answer
2 -> QR answer with a value
have added following test cases, can you please review

```
@Test
  @UiThreadTest
  fun displayValidationResult_questionnaireResponseAnswerWithValue_shouldShowNoErrorMessage() {
    viewHolder.bind(
      QuestionnaireItemViewItem(
        Questionnaire.QuestionnaireItemComponent().apply { required = true
          addAnswerOption(
            Questionnaire.QuestionnaireItemAnswerOptionComponent().apply {
              text = "Question?"
            }
          )},
        QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
          addAnswer(
            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
              value = BooleanType(false)
            }
          )
        }
      ) {}
    )

    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.error_text_view).error)
      .isEqualTo(null)
  }

  @Test
  @UiThreadTest
  fun displayValidationResult_noQuestionnaireResponseAnswer_shouldShowNoErrorMessage() {
    viewHolder.bind(
      QuestionnaireItemViewItem(
        Questionnaire.QuestionnaireItemComponent().apply { required = true
          addAnswerOption(
            Questionnaire.QuestionnaireItemAnswerOptionComponent().apply {
              text = "Question?"
            }
          )},
        QuestionnaireResponse.QuestionnaireResponseItemComponent()
      ) {}
    )

    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.error_text_view).error)
      .isEqualTo(null)
  }
```

2022-03-31 06:29 UTC, aurangzaibumer commented
> @aurangzaibumer , have the last few comments from @jingtang10 addressed? CC: @f-odhiambo

I've addressed the comments. Waiting for a feedback. thanks.
cc @f-odhiambo

2022-03-31 12:07 UTC, aurangzaibumer commented
@jingtang10 can you please review and let me know any feedback. thanks

cc @f-odhiambo

2022-04-05 06:17 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noQuestionnaireResponseAnswer_shouldShowNoErrorMessage() {
resolved

2022-04-05 06:18 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RequiredConstraintValidator.kt
> +    }
resolved as per the feedback, please review. thanks

2022-04-05 06:22 UTC, aurangzaibumer commented
> Can you add a test case for `RequiredConstraintValidator.kt`?
> 
> Actually if you do this, you can probably remove the new test cases you added in the boolean and single line widgets' tests.

I've added few test cases for the `RequiredConstraintValidator.kt` class as per the business. Can you please review. thanks

2022-04-06 10:28 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noQuestionnaireResponseAnswer_shouldShowNoErrorMessage() {
added new test case for QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest 
can you please review
cc @f-odhiambo

2022-04-06 15:16 UTC, jingtang10 requested changes

2022-04-06 15:16 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RequiredConstraintValidatorTest.kt
> +  fun shouldReturnValidResultOnMultipleAnswersWithNoValue() {
```suggestion
  fun shouldReturnInvalidResult_noAnswerHasValue() {
```

2022-04-06 15:16 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RequiredConstraintValidatorTest.kt
> +  }
remove this test case.

2022-04-06 15:16 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.error_text_view).error)
i think you need to assert on `.text` rather than `.error`

```suggestion
    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.error_text_view).text)
```

2022-04-06 15:16 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +  }
this is the same as `displayValidationResult_error_shouldShowErrorMessage` for the widget itself. so this can be removed.

2022-04-06 15:16 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.error_text_view).error)
```suggestion
    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.error_text_view).text)
```

2022-04-06 15:16 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +    )
this is covered by `displayValidationResult_noError_shouldShowNoErrorMessage`

remove this test case

2022-04-06 16:25 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RequiredConstraintValidatorTest.kt
> +  fun shouldReturnValidResultOnMultipleAnswersWithValue() {
resolved

2022-04-06 17:10 UTC, aurangzaibumer commented
Comments are resolved. Can you please review @jingtang10 . Thanks
cc @f-odhiambo

2022-04-06 17:47 UTC, 1371523503 commented
什么


---Original---
From: ***@***.***&gt;
Date: Thu, Apr 7, 2022 01:10 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [google/android-fhir] Fixed Showing no validation errors whenform opens (PR #1102)




 
Comments are resolved. Can you please review @jingtang10 . Thanks
 cc @f-odhiambo
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2022-04-08 09:18 UTC, aurangzaibumer commented
Unable to update with master branch @jingtang10 
@f-odhiambo

2022-04-08 12:00 UTC, aurangzaibumer commented
> Unable to update with master branch @jingtang10 @f-odhiambo

fixed, can update now.

2022-04-08 14:18 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun displayValidationResult_noQuestionnaireResponseAnswer_shouldShowNoErrorMessage() {
so you effectively removed the test case where there is an error.

2022-04-14 08:20 UTC, jingtang10 commented
Two possible solutions (pending investigation):

1. instead of always creating a QuestionnaireResponseItem in the QuestionnaireItemViewItem, we can leave it as `null` if the question hasn't been touched by the user at all. If this field is null (meaning there's no answer at all), we don't validate. But if it's not null, we will validate. And if the non-null QuestionnaireResponseItem has no answer, that means the user has tried to answer it but left it empty/blank. In this case if the question is required, we should show validation error.
2. Add a dirty field to indicate if the question has been touched by the user

2022-04-14 08:21 UTC, jingtang10 commented
@aurangzaibumer @ellykits

2022-04-21 07:50 UTC, aurangzaibumer commented
New PR Link https://github.com/google/android-fhir/pull/1309

2022-04-21 07:50 UTC, closed without merging