imported Truth.assertThat
google/android-fhir pull request #1110
Opened 2022-02-03 11:21 UTC by Harsh9149

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #766 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-03 11:25 UTC, epicadk reviewed
a few comments

2022-02-03 11:25 UTC, epicadk commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/barcode/QuestionnaireItemBarCodeReaderViewHolderFactoryInstrumentedTest.kt
>  import com.google.common.truth.Truth
Do we still require this import?

2022-02-03 11:25 UTC, epicadk commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt
>  import com.google.common.truth.Truth
ditto

2022-02-03 11:25 UTC, epicadk commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
>  import com.google.common.truth.Truth
same

2022-02-03 11:25 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
>  import com.google.common.truth.Truth
ditto

2022-02-03 11:43 UTC, jingtang10 requested changes
thanks for this - please address @epicadk's comments!

thansk @epicadk for the review.

2022-02-03 12:24 UTC, Harsh9149 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/barcode/QuestionnaireItemBarCodeReaderViewHolderFactoryInstrumentedTest.kt
>  import com.google.common.truth.Truth
@epicadk I have run the spotless and the imports are gone. PTAL.

2022-02-03 12:45 UTC, jingtang10 approved these changes
@Harsh9149 thanks for the PR 👍

2022-02-03 12:46 UTC, jingtang10 commented
please tick the remaining items in the description:

 I have run ./gradlew check and ./gradlew connectedCheck to test my changes locally
 I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-03 12:54 UTC, Harsh9149 commented
Hi @jingtang10 is android fhir is participating in upcoming Gsoc'22.

2022-02-03 13:07 UTC, Harsh9149 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt
>  import com.google.common.truth.Truth
Done

2022-02-03 13:07 UTC, Harsh9149 commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
>  import com.google.common.truth.Truth
Done

2022-02-03 13:07 UTC, Harsh9149 commented on engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
>  import com.google.common.truth.Truth
Done

2022-02-03 16:11 UTC, Harsh9149 commented
> Hi @jingtang10 is android fhir is participating in upcoming Gsoc'22.

@f-odhiambo

2022-02-03 16:13 UTC, Harsh9149 commented
@epicadk I am not getting what is going wrong in my PR. My build test is failing can you please help me in resolving the error.

2022-02-04 10:39 UTC, jingtang10 commented
> @epicadk I am not getting what is going wrong in my PR. My build test is failing can you please help me in resolving the error.

The instrumentation tests have been timing out across different PRs. Not sure if this is a transient issue of github.

2022-02-05 08:12 UTC, Harsh9149 commented
> > @epicadk I am not getting what is going wrong in my PR. My build test is failing can you please help me in resolving the error.
> 
> The instrumentation tests have been timing out across different PRs. Not sure if this is a transient issue of github.

@jingtang10 is there a way to resolve this issue please let me know and also can you rerun the CI check again it might resolve the issue.

2022-02-06 11:52 UTC, epicadk commented
> > > @epicadk I am not getting what is going wrong in my PR. My build test is failing can you please help me in resolving the error.
> > 
> > The instrumentation tests have been timing out across different PRs. Not sure if this is a transient issue of github.
> 
> @jingtang10 is there a way to resolve this issue please let me know and also can you rerun the CI check again it might resolve the issue.

Already tried this.

2022-02-08 06:07 UTC, Harsh9149 commented
@jingtang10 please approve the CI check

2022-02-08 08:02 UTC, jingtang10 commented
@Harsh9149 as you can see in #1120 we are experiencing some issues with some of our tests. so while this pr is approved it probably won't be merged until that issue is resolved - hopefully soon.

2022-02-08 19:52 UTC, merged