Store remote version id for the resources and provide the version id for local change entity
google/android-fhir pull request #1127
Opened 2022-02-08 08:15 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1096 

**Description**
Store and update remote version id for the resources in `ResourceEntity` and add remote version id to `LocalChangeEntity`.
After a resource is created or updated, the server returns the Resource as response and it has the new meta data. So it needs to be propagated back to the `FhirEngine` as well.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-15 07:40 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val remoteLastUpdateTime: String
Done.

2022-02-15 07:41 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    }
Changed this particular test and added a few new ones to check different local/remote add/update cases.

2022-02-15 07:50 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +        resource.lastUpdatedTimestamp
Yes, `DatabaseImplTest.insert_localResourceWithNoMeta_shouldSaveNullRemoteVersionAndLastUpdated` and `DatabaseImplTest.insert_remoteResourceWithNoMeta_shouldSaveNullRemoteVersionAndLastUpdated` test this scenario.

2022-02-15 07:51 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    remoteLastUpdateTime: Long
Updated the function name instead of creating two functions.

2022-02-15 07:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val remoteLastUpdateTime: String
Done

2022-02-15 14:12 UTC, jingtang10 requested changes

2022-02-15 14:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val remoteLastUpdated: Instant?
```suggestion
  val versionId: String?,
  val lastUpdatedRemote: Instant?
```

2022-02-15 14:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val remoteLastUpdated: Instant?
```suggestion
  val versionId: String?,
  val lastUpdatedRemote: Instant?
```

2022-02-15 14:13 UTC, jingtang10 commented
as we discussed earlier today, can you create anothe issue for if we always save the resource

2022-02-15 19:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  override suspend fun updateRemoteVersionIdAndLastUpdate(
done

2022-02-15 19:53 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun update_remoteResourceWithLocalChange_shouldSaveRemoteVersionAndLastUpdated() = runBlocking {
done

2022-02-15 19:53 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun insert_remoteResource_shouldSaveRemoteVersionAndLastUpdated() = runBlocking {
done

2022-02-15 19:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val remoteLastUpdated: Instant?
done

2022-02-15 19:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val remoteLastUpdated: Instant?
done

2022-02-16 14:11 UTC, jingtang10 approved these changes

2022-02-17 09:27 UTC, merged