Convert Java classes to Kotlin
google/android-fhir pull request #113
Opened 2020-11-26 17:54 UTC by jingtang10

2020-11-30 01:43 UTC, yigit requested changes

2020-11-30 01:43 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/ResourceAlreadyExistsException.kt
> +  type: String,
these need to be `val`'s. (except for cause)

2020-11-30 01:43 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/ResourceNotFoundException.kt
> +  type: String,
ditto

2020-11-30 01:43 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/resource/Resources.kt
> +val R4_RESOURCE_PACKAGE_PREFIX = "org.hl7.fhir.r4.model."
i see the previous java class was public but i think these are all internal functionality right?
if so, we should mark these `internal` (everything in this file)

2020-11-30 01:43 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/resource/Resources.kt
> +fun <R : Resource> getResourceClass(resourceType: String): Class<R> {
we may want to move this to KClass instead but does not need to be in this PR

2020-11-30 09:39 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/ResourceAlreadyExistsException.kt
> +  type: String,
why? we don't need them after the constructor right?

2020-11-30 09:39 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/ResourceNotFoundException.kt
> +  type: String,
ditto

2020-11-30 09:39 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/resource/Resources.kt
> +val R4_RESOURCE_PACKAGE_PREFIX = "org.hl7.fhir.r4.model."
yeah thanks for the catch!

2020-11-30 09:39 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/resource/Resources.kt
> +fun <R : Resource> getResourceClass(resourceType: String): Class<R> {
ack. i'll do that in a following pr.

2020-12-02 17:50 UTC, jingtang10 commented
rebased. PTAL! thx! @yigit

2020-12-03 03:15 UTC, deepankarb requested changes
Empty file named 'Task' can be removed. Left a couple of comments. Thanks!

Also please take a look at spotless failure in CI: https://github.com/google/android-fhir/pull/113/checks?check_run_id=1487953151#step:10:27

2020-12-03 03:15 UTC, deepankarb commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +    private companion object {
Duplicate code? There's another `companion` right above.

2020-12-03 03:15 UTC, deepankarb commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.java
> +/*
This should be removed.

2020-12-07 16:49 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/ResourceAlreadyExistsException.kt
> +  type: String,
there are public getters/setters for it in the java version. i thought you wanted to keep them as properties ? with his, they cannot be read back anymore.

2020-12-07 16:55 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/ResourceAlreadyExistsException.kt
> +  type: String,
yeah you're right. if we don't expose these the class is a bit pointless.

2020-12-07 16:58 UTC, yigit approved these changes

2020-12-07 17:55 UTC, merged