Use Parametrized test for Number Search
google/android-fhir pull request #1153
Opened 2022-02-09 11:47 UTC by Anshul-9923

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #545 

**Description**
I have created one file NumberSearch.kt in which I have created a parameterized test for function search_filter_number_lessThanEquals. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-09 12:05 UTC, Anshul-9923 commented
@jingtang10 Please review my code if any changes are required let me know. For now, I have created a parameterized test for only 1 function after reviewing this I will create for other functions as well.

2022-02-09 14:46 UTC, epicadk requested changes

2022-02-09 14:46 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> -    MoreSearch.KT) */
change not required

2022-02-09 14:46 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +        FROM ResourceEntity a
Can this string not be a part of the test? You're repeating the same string in all the cases.

2022-02-09 14:46 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +  fun search_filter_number_lessThanEquals() {
please add the other cases as well.

2022-02-09 15:41 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +  fun search_filter_number_lessThanEquals() {
@epicadk other cases mean other functions search_filter_number_notEquals, search_filter_number_greaterThanEquals,etc.

2022-02-09 15:41 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> -    MoreSearch.KT) */
I will undo the change in the next commit.

2022-02-10 05:04 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +        FROM ResourceEntity a
Yes, I did that by creating a variable.

2022-02-10 05:40 UTC, epicadk requested changes

2022-02-10 05:40 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +    fun data() : Collection<Array<Any>> {
The only parametrised quantities need to be the number itself and its upper and lower bounds. The rest of these don't change and can be constants in the test.

2022-02-12 02:57 UTC, Anshul-9923 commented
@epicadk I have committed the changes if now the parameterized test for search_filter_number_lessThanEquals is all right then I would create a parameterized test for other functions as well.

2022-02-13 03:40 UTC, epicadk requested changes
Thanks for this, better now. Please add the remaining tests as well after making these changes.
refer https://www.hl7.org/fhir/search.html#number

2022-02-13 03:40 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +        arrayOf(BigDecimal("100.00")),
```suggestion
        arrayOf(BigDecimal("100.00"),BigDecimal("99.995"),BigDecimal("100.005"))),
```

2022-02-13 03:40 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +      BigDecimal("100.00").toDouble()
Use the parameter here as well.

2022-02-13 03:52 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +        arrayOf(BigDecimal("100.00")),
@epicadk Like this should I change other list elements also?

2022-02-13 15:05 UTC, Anshul-9923 commented
@epicadk I have added the remaining tests and done changes as told by you. PTAL!

2022-02-13 15:05 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +      BigDecimal("100.00").toDouble()
Done

2022-02-14 06:20 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +          num.toDouble()
Have you tried running the tests locally. This doesn't look like it's going to work. The number of expected args and the args do not match.

2022-02-14 07:48 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +          num.toDouble()
Yes Sir I tried but it shows tests events were not received. Can you please tell me which tests will not be going to work?

2022-02-14 12:10 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +  private val num: BigDecimal
the test events are received probably because the class is expecting 1 argument but you are passing 3. Please have 3 args here something like , number, higherBound, lowerBound

2022-02-14 12:10 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +          num.toDouble()
> Yes Sir I tried but it shows tests events were not received. Can you please tell me which tests will not be going to work?

No need for the formalities. 😅

2022-02-15 17:01 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +  private val num: BigDecimal
@epicadk Resolved the problem and did the required changes. PTAL

2022-02-15 17:39 UTC, epicadk commented
Looks good, but I still think a few of the tests will fail. Please look into those.

2022-02-15 17:56 UTC, epicadk submitted a review, later dismissed

2022-02-15 17:56 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +
Please run spotless using `gradlew sA`

2022-02-18 04:22 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +
@epicadk Should I have to set up anything else before running this command because I tried to run this command it shows the build failed in the 
![Screenshot (478)](https://user-images.githubusercontent.com/78676313/154617138-1bea5976-3d1e-49b7-975f-32b736750037.png)
android studio terminal.

2022-02-18 07:22 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008464899-What-s-the-smart-commands-execution

2022-02-18 18:12 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +package com.google.android.fhir.search
Test file name should end with "Test".

2022-02-19 12:38 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +package com.google.android.fhir.search
Done

2022-02-19 12:39 UTC, Anshul-9923 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +
@epicadk I tried to understand but didn't able to get what you want to say to resolve this issue.

2022-02-24 12:40 UTC, jingtang10 reviewed
are you going to remove the tests in the `SearchTest.kt` file? @epicadk what do you think? should we have parameterized tests for all types?

2022-02-24 16:36 UTC, epicadk commented
> are you going to remove the tests in the `SearchTest.kt` file? @epicadk what do you think? should we have parameterized tests for all types?

Yup I think we would cover a lot of edge cases that way.

2022-03-03 08:46 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/NumberSearch.kt
> +
press ctrl+enter after you type `gradlew sA`

2022-06-17 16:44 UTC, jingtang10 commented
@epicadk @omarismail94 can you two please take another look at this PR. any more changes required or do we want to merge this?

@Anshul-9923 

thanks

2022-06-17 17:16 UTC, omarismail94 commented
Hey @Anshul-9923 -  are you still interested on working on this PR?

I pulled your change on my machine and ran :

```
./gradlew :engine:testDebugUnitTest \
--tests "com.google.android.fhir.search.NumberSearchTest"
```

to test the changes you made and they failed. Could you take a look and fix them?

You also need to format the code before uploading your new commit as it is failing right now. See the CI/ build logs here:
https://github.com/google/android-fhir/runs/6939769862?check_suite_focus=true

To format the code, run:

```
./gradlew spotlessApply
```

and you will see that it will format the files you are changing for you

2022-06-21 20:42 UTC, omarismail94 commented
@epicadk @jingtang10 

can you review the changes I made? All errors now resolved when I run `./gradlew check` locally. I also removed the non-parameterised version of the tests in [SearchTest.kt](https://github.com/google/android-fhir/pull/1153/files#diff-f1c6d500d35226a0690a062de7822f3136aae2bf6de227b120ada65a818ffe89)

2022-06-23 05:31 UTC, jingtang10 approved these changes
thanks omar! some nits but overall looking good.

2022-06-23 05:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearchTest.kt
> +    assertThat(query.query)
`query.query` looks strange - so maybe the variable should be renamed to search. so you get `search.query`.

same for the rest of the test

2022-06-23 05:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearchTest.kt
> +class NumberSearchTest(
```suggestion
class NumberSearchParameterizedTest(
```

2022-06-23 05:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearchTest.kt
> +  fun search_filter_number_equals() {
kinda feel like now that these are in the same file, we don't need to say "search" and "filter" and "number" in the test name any more. what about using this more readable style:

`should search equal values`

https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

2022-06-23 05:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearchTest.kt
> +  fun search_filter_number_greater() {
`should search values greater than a number`

etc

2022-06-23 05:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/NumberSearchTest.kt
> +    /* x contains pairs of values and their corresponding range (see BigDecimal.getRange() in
does this comment still name sense? can you rewrite?

2022-06-23 05:31 UTC, jingtang10 commented
disabled auto merge - please address the comments before merging.

2022-06-23 12:44 UTC, omarismail94 commented
@jingtang10 thanks for the review! Addressed comments and will wait for tests to pass before merging

2022-06-24 09:48 UTC, omarismail94 approved these changes

2022-06-24 10:01 UTC, merged