Demo App: Screenshot testing
google/android-fhir pull request #1158
Opened 2022-02-09 15:12 UTC by anita-vadverao

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-16 10:48 UTC, jingtang10 requested changes
as discussed please sync and remove reference directory.

also should the html files be checked in?

2022-02-17 09:47 UTC, ktarasenko reviewed
Great stuff! 
I added my 5 cents, but let's not block this PR. Feel free to add TODOs instead of doing actual changes.

2022-02-17 09:47 UTC, ktarasenko commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    //    const val facebookScreenshotPlugin = "0.14.0"
duplicates l:209

2022-02-17 09:47 UTC, ktarasenko commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  //  const val screenshotPlugin =
Duplicated above

2022-02-17 09:47 UTC, ktarasenko commented on demo/src/androidTest/java/com/google/android/fhir/demo/screenshots/ScreenshotTest.kt
> +  @get:Rule var activityTestRule = ActivityTestRule(MainActivity::class.java, false, false)
`ActivityTestRule` is deprecated. Please use `ActivityScenario` instead.
https://developer.android.com/reference/androidx/test/core/app/ActivityScenario

This would change the way we would do `snapActivity`:
```
  activityScenario.onActivity { activity ->
            Screenshot.snapActivity(activity).record()
        }
```

2022-02-17 09:47 UTC, ktarasenko commented on demo/src/main/res/values/styles.xml
> +        parent="Theme.MaterialComponents.Light.DarkActionBar"
Did you switch to Light theme from DayNight one on purpose?

2022-02-17 09:47 UTC, ktarasenko commented on demo/src/androidTest/java/com/google/android/fhir/demo/screenshots/ScreenshotTest.kt
> +    Thread.sleep(5000)
I bet most of those timeouts are not necessary.
Espresso tools (IdlingResources) could be used instead.

2022-02-18 16:53 UTC, jingtang10 commented
Can you please remove all the HTML files that are included???

2022-02-24 12:38 UTC, jingtang10 commented
@epicadk FYI this is the PR I mentioned earlier

2022-03-03 08:30 UTC, epicadk commented on demo/src/androidTest/java/com/google/android/fhir/demo/screenshots/ScreenShotTestRunner.kt
> +class ScreenShotTestRunner : AndroidJUnitRunner() {
This is only required when we are using a custom test runner right?

2022-03-09 07:43 UTC, vvikramraj commented
> as discussed please sync and remove reference directory.
> 
> also should the html files be checked in?

The html files seem to contain the test output. I reckon we can safely leave them out.

2022-03-09 08:26 UTC, aditya-07 commented on demo/src/androidTest/java/com/google/android/fhir/demo/screenshots/ScreenShotTestRunner.kt
> +class ScreenShotTestRunner : AndroidJUnitRunner() {
Yes.

2022-03-17 17:08 UTC, jingtang10 commented
@vvikramraj + @kevinmost will you be able to investigate further and see if we can get this PR to be merged in some shape or form?

2022-03-17 20:33 UTC, epicadk commented
alternative: https://github.com/cashapp/paparazzi

2022-04-25 10:59 UTC, jingtang10 commented
thanks @epicadk - we'll close this PR for now.

also worth noting that you can also take screenshots in espresso tests. https://github.com/android/testing-samples

2022-04-25 10:59 UTC, closed without merging