Wz/db localid
google/android-fhir pull request #1159
Opened 2022-02-10 03:14 UTC by wantingzhang77

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #98 Change Resource - Index foreign key to SQLite ID

**Description**
Add a resourceLocalId for resourceEntity, use it as foreign key for index tables.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Code health

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-10 16:54 UTC, jingtang10 commented
cc @aditya-07 because he's working also on #1127 and #1084.

2022-02-15 13:11 UTC, jingtang10 requested changes
Thanks @wantingzhang77!

Please update the PR name to something more meaningful.

2022-02-15 13:11 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/DateIndexEntity.kt
> +  val resourceLocalId: String,
```suggestion
  val resourceUuid: String,
```

and all the other tables?

2022-02-15 13:22 UTC, jingtang10 requested changes

2022-02-15 13:22 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val resourceLocalId: String,
Given that room has added a built-in converter. See https://developer.android.com/jetpack/androidx/releases/room#2.4.0-alpha05. Can you just change the type of this field to UUID and see if this works?

and you'll need to update room version to the latest as well (think it's 2.4.1 at the moment).

2022-02-16 18:21 UTC, wantingzhang77 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val resourceLocalId: String,
Move this line after primary key on in all xxEntity files.

2022-02-16 18:23 UTC, wantingzhang77 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/ResourceEntity.kt
> +  val resourceLocalId: String,
Change the name from resourceLocalId to resourceUuid.
The room version forward issue will be addressed in separate bug, for the reason that it will also requires forwarding targetSDK version from 30 to 31.

2022-02-17 19:05 UTC, jingtang10 approved these changes

2022-02-17 23:11 UTC, merged