Add city and country validation at app side.
google/android-fhir pull request #1160
Opened 2022-02-10 09:31 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1131 

**Description**
City and Country validation is added.
If values are blank then it will create patient.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-11 06:53 UTC, santosh-pingle commented
> i'm not sure this is the right place to fix this issue. i would much rather that the sdc lib return some kind of result.
> 
> can you try to use this api:
> 
> https://github.com/google/android-fhir/blob/efcdabb7ae179ce4c90246c465b271a78479dd87/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt#L100

I see mentioned api throws exception if one of the check fails. I am thinking to add `required` check, if fails then throw exception.

2022-03-09 12:16 UTC, jingtang10 commented
just to reiterate what we discussed before, the check should be in the `validateQuestionnaireResponse` api rather than `checkQuestionnaireResponse`.

2022-04-17 22:08 UTC, jingtang10 requested changes

2022-04-17 22:08 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/AddPatientViewModel.kt
> +        }
```suggestion
        .any { !it.isValid }
```
and wrap this in an `if` statement to return

2022-04-19 07:45 UTC, jingtang10 approved these changes
Thanks @santosh-pingle

2022-04-19 09:50 UTC, merged