[1135] Sync time is not updating in hamburger menu after manual sync …
google/android-fhir pull request #1162
Opened 2022-02-10 13:15 UTC by PallaviGanorkar

…with server and toast message shows older time - Bug Fixed

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1135

**Description**
Sync time is not updating in hamburger menu after manual sync with server and toast message also shows older time

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-17 12:44 UTC, jingtang10 approved these changes
@PallaviGanorkar Great fix! 👍

2022-02-17 12:44 UTC, jingtang10 reviewed
Is there anyway to add a test case to catch this?

2022-02-21 18:20 UTC, jingtang10 commented
any progress on the tests?

2022-03-07 10:31 UTC, PallaviGanorkar commented
> any progress on the tests?

Test added

2022-03-10 11:55 UTC, jingtang10 requested changes
thanks!

2022-03-10 11:55 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    Thread.sleep(5000)
do you have to sleep?
and if you do, does this have to be 5 seconds?

2022-03-10 11:55 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    assert(firstSyncResult.timestamp.compareTo(curentTimeStamp) > 0)
use `com.google.common.truth.Truth.assertThat` to do assertion in tests. it's a nice library that has a fluent api: https://truth.dev/

2022-03-10 11:55 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +  fun `sync time should update on every sync call`() = runBlockingTest {
```suggestion
  fun `Sync time should update on every sync call`() = runBlockingTest {
```

and if you can fix the rest of the test cases in this file it'd be great.

2022-03-10 11:55 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    // get flows return by work manager wrapper
```suggestion
    // Get flows return by work manager wrapper
```

and for other comments too.

2022-03-10 11:55 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    datastoreUtil.readLastSyncTimestamp()?.let { assert((it).compareTo(curentTimeStamp) > 0) }
because this is testing a scenario, we don't really need to do `?.`. if anything we can just be more aggressive and use `!!`

```suggestion
    val timestamp = datastoreUtil.readLastSyncTimestamp()!!
    assertThat(timestamp).isEqualTo(...)
```

2022-03-15 08:15 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    assert(firstSyncResult.timestamp.compareTo(curentTimeStamp) > 0)
Done

2022-03-15 08:19 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +  fun `sync time should update on every sync call`() = runBlockingTest {
Done

2022-03-16 07:15 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    // get flows return by work manager wrapper
Done

2022-03-16 07:16 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    datastoreUtil.readLastSyncTimestamp()?.let { assert((it).compareTo(curentTimeStamp) > 0) }
Done

2022-03-16 10:08 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    Thread.sleep(5000)
Done

2022-03-23 18:17 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    Thread.sleep(5000)
@PallaviGanorkar Can you please elaborate on the change?

2022-03-31 11:52 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    println("After enqueue")
Please remove the logs.

2022-03-31 11:59 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    println("After stateList1 size :"+stateList1)
Please remove log statements.

2022-04-06 13:31 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    println("After stateList1 size :"+stateList1)
Those logs are added for testing purpose as test cases are passing locally on my machine but same are failing in CI. So, for debugging logs are added.  I will update once its fixd

2022-04-13 12:59 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    Thread.sleep(5000)
Sleep time is reduced to 300 milliseconds

2022-04-14 09:53 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +  }
```suggestion
  fun `Sync time should update on every sync call`() = runBlockingTest {
    val worker1 = PeriodicWorkRequestBuilder<TestSyncWorker>(15, TimeUnit.MINUTES).build()
    val stateFlow1 = syncJob.stateFlow()
    val stateList1 = mutableListOf<State>()
    val job1 = launch { stateFlow1.toList(stateList1) }
    val currentTimeStamp: OffsetDateTime = OffsetDateTime.now()
    workManager
      .enqueueUniquePeriodicWork(
        SyncWorkType.DOWNLOAD_UPLOAD.workerName,
        ExistingPeriodicWorkPolicy.REPLACE,
        worker1
      )
      .result
      .get()
    Thread.sleep(300)
    
    val firstSyncResult = (stateList1[stateList1.size - 1] as State.Finished).result
    assertThat(firstSyncResult.timestamp).isGreaterThan(currentTimeStamp)
    assertThat(datastoreUtil.readLastSyncTimestamp()!!).isGreaterThan(currentTimeStamp)
    job1.cancel()

    // Run sync for second time
    val worker2 = PeriodicWorkRequestBuilder<TestSyncWorker>(15, TimeUnit.MINUTES).build()
    val stateFlow2 = syncJob.stateFlow()
    val stateList2 = mutableListOf<State>()
    val job2 = launch { stateFlow2.toList(stateList2) }
    workManager
      .enqueueUniquePeriodicWork(
        SyncWorkType.DOWNLOAD_UPLOAD.workerName,
        ExistingPeriodicWorkPolicy.REPLACE,
        worker2
      )
      .result
      .get()
    Thread.sleep(300)
    
    val secondSyncResult = (stateList2[stateList2.size - 1] as State.Finished).result
    assertThat(secondSyncResult.timestamp).isGreaterThan(firstSyncResult.timestamp)
    assertThat(datastoreUtil.readLastSyncTimestamp()!!).isGreaterThan(firstSyncResult.timestamp)
    job2.cancel()
  }
```

2022-04-14 09:54 UTC, aditya-07 approved these changes
Just one small suggestion for better formatting. Otherwise, LGTM.!

2022-04-18 11:38 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +  fun `sync time should update on every sync call`() = runBlockingTest {
@jingtang10 As discussed reverted this change

2022-04-22 17:29 UTC, jingtang10 approved these changes

2022-04-26 17:50 UTC, jingtang10 commented
@PallaviGanorkar this seems to be a legitimate test failure:

```
com.google.android.fhir.sync.SyncJobTest > sync time should update on every sync call FAILED
    java.lang.IndexOutOfBoundsException at SyncJobTest.kt:215
```

2022-04-30 10:17 UTC, merged