[1164] Sync.poll doesn't retry if the request fails for some reason :…
google/android-fhir pull request #1166
Opened 2022-02-11 15:28 UTC by PallaviGanorkar

… bug fixed

Fixes #1164

**Description**
Sync.poll doesn't retry if the request fails for some reason.

**Type**
Choose one: Bug fix 

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-15 07:58 UTC, aditya-07 commented
@PallaviGanorkar Please use **Description** section above to describe your solution.

2022-02-15 08:22 UTC, aditya-07 requested changes
Please add appropriate tests to check that the retry mechanism is working.

2022-02-15 08:22 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +    }
`RetryConfiguration.backoffCriteria` is `non-null` type.
```suggestion
    periodicSyncConfiguration.retryConfiguration?.let {
      periodicWorkRequest
        .setBackoffCriteria(
       it.backoffCriteria.backoffPolicy,
        it.backoffCriteria.backoffDelay,
        it.backoffCriteria.timeUnit
        )
        .setInputData(
          Data.Builder()
            .putInt(MAX_RETRIES_ALLOWED, it.maxRetries)
            .build()
        )
    }
```

2022-02-16 09:34 UTC, PallaviGanorkar commented
> @PallaviGanorkar Please use **Description** section above to describe your solution.



> @PallaviGanorkar Please use **Description** section above to describe your solution.

Updated Description

2022-03-04 03:13 UTC, Tarun-Bhardwaj commented
@PallaviGanorkar , are the changes ready so that @aditya-07  can review?

2022-03-09 13:20 UTC, PallaviGanorkar commented
@aditya-07  Please review the code changes, As discussed, reusing existing method for periodic sync with retry mechanism

2022-03-22 18:31 UTC, PallaviGanorkar commented
> @PallaviGanorkar Please use **Description** section above to describe your solution.

done

2022-03-22 18:44 UTC, PallaviGanorkar commented
> Please add appropriate tests to check that the retry mechanism is working.

@aditya-07  As discussed, Code changes are tested Manually, those are working fine.
Test case will be pushed as separate PR under issue https://github.com/google/android-fhir/issues/1252

2022-03-23 15:19 UTC, aditya-07 requested changes
Left some comments. We shouldn't change our public `oneTimeSync` and `periodicSync` apis. They should still take `reified` type.

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  inline fun <W : FhirSyncWorker> oneTimeSync(
This function signature shouldn't change. Instead you should internally call `createOneTimeWorkRequest(retryConfiguration, W::class.java)`

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    clazz: Class<W>,
remove it.

2022-03-23 15:19 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +    Sync.oneTimeSync(this, FhirPeriodicSyncWorker::class.java)
```suggestion
    Sync.oneTimeSync<FhirPeriodicSyncWorker>(this)
```
Revert this change as the  Sync.oneTimeSync signature shouldn't change.

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    clazz: Class<W>
```suggestion
  inline fun < reified W : FhirSyncWorker> periodicSync(
    context: Context,
    periodicSyncConfiguration: PeriodicSyncConfiguration)
```
Just like oneTimeSync, this api shouldn't change as well.

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        createPeriodicWorkRequest(periodicSyncConfiguration, clazz)
```suggestion
        createPeriodicWorkRequest(periodicSyncConfiguration, W::class.java)
```

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        createOneTimeWorkRequest(retryConfiguration, clazz)
```suggestion
        createOneTimeWorkRequest(retryConfiguration, W::class.java)
```

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    val oneTimeWorkRequest = OneTimeWorkRequest.Builder(clazz)
While you are at it, please rename the variable.
```suggestion
    val oneTimeWorkRequestBuilder = OneTimeWorkRequest.Builder(clazz)
```

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +        PassingPeriodicSyncWorker::class.java
Should be reverted.

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +    val workRequest = Sync.createOneTimeWorkRequest(null, PassingPeriodicSyncWorker::class.java)
Should be reverted.

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +      Sync.createPeriodicWorkRequest(
Should be reverted.

2022-03-23 15:19 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +        PassingPeriodicSyncWorker::class.java
Should be reverted.

2022-03-30 10:49 UTC, PallaviGanorkar commented
> As discussed, Code changes are tested Manually, those are working fine.
> Test case will be pushed as separate PR under issue #1252

As discussed, Code changes are tested Manually, those are working fine.
Test case will be added as separate PR under issue https://github.com/google/android-fhir/issues/1252

2022-03-30 13:34 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        createPeriodicWorkRequest(periodicSyncConfiguration, clazz)
This changes request not valid for internal method

2022-03-30 13:41 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        createOneTimeWorkRequest(retryConfiguration, clazz)
This changes request not valid for internal method

2022-03-30 13:41 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +        PassingPeriodicSyncWorker::class.java
This changes request not valid for internal method

2022-03-30 13:42 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +    val workRequest = Sync.createOneTimeWorkRequest(null, PassingPeriodicSyncWorker::class.java)
This changes request not valid for internal method

2022-03-30 13:42 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +      Sync.createPeriodicWorkRequest(
This changes request not valid for internal method

2022-03-30 13:42 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +        PassingPeriodicSyncWorker::class.java
This changes request not valid for internal method

2022-03-31 20:14 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        createOneTimeWorkRequest<W>(retryConfiguration, W::class.java)
```suggestion
        createOneTimeWorkRequest(retryConfiguration, W::class.java)
```

2022-03-31 20:17 UTC, aditya-07 approved these changes
Just one small cleanup, otherwise LGTM!

2022-04-11 13:35 UTC, PallaviGanorkar commented
> Just one small cleanup, otherwise LGTM!

Done

2022-04-12 07:07 UTC, merged