Refactoring code to apply material theme.
google/android-fhir pull request #1169
Opened 2022-02-15 02:47 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1007 

**Description**
Use .xml layout file with RadioButton to create radio button options. So that it will be inflated by MaterialLayoutInflater at run time as material theme is declared as datacapture ttheme.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-15 06:05 UTC, santosh-pingle commented
<img width="435" alt="Screen Shot 2022-02-15 at 11 24 57 AM" src="https://user-images.githubusercontent.com/86107848/154002228-51e41b42-41f8-429a-8063-8a6a3018dbf6.png">

2022-03-09 12:24 UTC, jingtang10 requested changes

2022-03-09 12:24 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          radioButton.id = index++
i don't know if this id is used to clear the radio button selection. but it would be better to use android api to generate the id rather than using the index value.

```suggestion
          radioButton.id = View.generateViewId()
```

2022-03-31 10:35 UTC, jingtang10 approved these changes
thanks @santosh-pingle!

2022-04-01 18:11 UTC, merged