Change questionnaireResponseItem to var from val in questionnaireItemViewItem
google/android-fhir pull request #1185
Opened 2022-02-21 12:55 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #765 

**Description**
If you have a questionnaire with multiple levels of nesting, questionnaire response items are nested within answers. When the parent answer is changed, we clear the questionnaireResponseItem.answer list and add the new answer to it. The nested questionnaireResponseItems also get cleared and new instances of them are created in the questionnaireResponseItemChangedCallback. Since questionnaireItemViewItem.questionnaireResponseItem was a value , the ViewHolderFactory would always hold the reference to the old nested questionnaireResponseItem. On making it a variable, the viewHolderFactory now gets the reference of the correct questionnaireResponseitem while setting the answer.  This allows enable when to work properly and thus displays the third nested answer too.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-21 18:06 UTC, jingtang10 commented
Thanks Kashyap for fixing this. First thought is that we should write some tests to cover this case. Upon second thought I'm not entirely sure why this would be the fix anyway - it seems like if `val` vs `var` can fix this issue there's probably an underlying problem which is the items are not being replaced/deleted/cached correctly.

2022-02-22 07:49 UTC, joiskash commented
> Thanks Kashyap for fixing this. First thought is that we should write some tests to cover this case. Upon second thought I'm not entirely sure why this would be the fix anyway - it seems like if `val` vs `var` can fix this issue there's probably an underlying problem which is the items are not being replaced/deleted/cached correctly.

Sure , ill write a UT first.

2022-02-22 14:20 UTC, jingtang10 requested changes

2022-02-22 14:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +   */
```suggestion
  /**
   * [QuestionnaireItemViewItem] is a transient object for the UI only. Whenever the user makes any change
   * via the UI, a new list of [QuestionnaireItemViewItem]s will be created, each holding references to the
   * underlying [QuestionnaireItem] and [QuestionnaireResponseItem]. To avoid refreshing the UI 
   * unnecessarily with the same [QuestionnaireItem]s and [QuestionnaireResponseItem]s,  we consider two
   * [QuestionnaireItemViewItem]s to be the same if they have the same underlying [QuestionnaireItem] and
   * [QuestionnaireResponseItem]. See [QuestionnaireItemAdapter.DiffCallback].
   * 
   * On the other hand, under certain circumstances, the underlying [QuestionnaireResponseItem] might be 
   * recreated for the same question. For example, if a [QuestionnaireItem] is nested under another 
   * [QuestionnaireItem], the [QuestionnaireResponseItem](s) will be nested under the parent 
   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent]. and if the 
   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent] is changed, the nested 
   * [QuestionnaireResponseItem] will be recreated, too. In such cases, it would be incorrect
   * to simply check that the `linkId` of the underlying [QuestionnaireItem] and 
   * [QuestionnaireResponseItem] match.
   */
```

2022-02-22 14:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  }
add another function `equalsDeep` to handle the `areContentsTheSame` functino of the `DiffCallback`.

2022-02-23 13:38 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  override fun equals(other: Any?): Boolean {
done

2022-02-23 13:38 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  }
done

2022-02-23 19:59 UTC, jingtang10 approved these changes
Thanks @joiskash again for debugging fixing this very thorning issue!

Just a few nits! Please feel free to merge once these are addressed.

2022-02-23 19:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    return if (other is QuestionnaireItemViewItem) {
turn this if condition around and return early.

2022-02-23 19:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent]. and if the
```suggestion
   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent], and if the
```

2022-02-23 19:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +   * [QuestionnaireResponse.QuestionnaireResponseItemComponent.equalsDeep] functions
```suggestion
   * Comparing the contents of two [QuestionnaireItemViewItem]s by traversing the underlying
   * [Questionnaire.QuestionnaireItemComponent] and
   * [QuestionnaireResponse.QuestionnaireResponseItemComponent] and comparing values of all the
   * properties. This is done by using [Questionnaire.QuestionnaireItemComponent.equalsDeep] and
   * [QuestionnaireResponse.QuestionnaireResponseItemComponent.equalsDeep].
```

2022-02-24 08:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    return if (other is QuestionnaireItemViewItem) {
done

2022-02-24 08:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +   * [QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent]. and if the
done

2022-02-24 08:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +   * [QuestionnaireResponse.QuestionnaireResponseItemComponent.equalsDeep] functions
done

2022-02-24 09:07 UTC, jingtang10 requested changes

2022-02-24 09:07 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    }
```suggestion
    if (other !is QuestionnaireItemViewItem) return false
    return this.questionnaireItem === other.questionnaireItem &&
        this.questionnaireResponseItem === other.questionnaireResponseItem
```

2022-02-24 12:30 UTC, jingtang10 approved these changes

2022-02-24 12:30 UTC, merged