[1194] Catalog application crashes when time is set using time picker…
google/android-fhir pull request #1200
Opened 2022-02-24 08:39 UTC by PallaviGanorkar

… widget - Bug Fixed

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1194

**Description**
Clear and concise code change description. 

**Type**
Choose one: Bug fix
 

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-04-05 16:56 UTC, jingtang10 requested changes

2022-04-05 16:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            }
is there anyway you can create a single private function that sets the answer from local date and local time?

so that this part of code and the listener for the time input can share the same code path.

2022-04-06 07:45 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            }
I have already thought it but could not find way because need to private function for one line of code i.e.
 localDateTime = LocalDateTime.of(year, month + 1, dayOfMonth, it.hour, it.minute, it.second)

and LocalDateTime constructor has input from different local variables

2022-04-06 11:12 UTC, jingtang10 approved these changes

2022-04-06 11:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            }
got it. thanks for the explanation. i think i actually came across a similar problem before.

2022-04-06 11:12 UTC, jingtang10 approved these changes

2022-04-06 11:12 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(
```
import Truth.assertThat
```

2022-04-08 11:51 UTC, jingtang10 commented
Looks good. Thanks for updating the test cases pallavi. Just one request: have you checked (locally is fine) that without the code change your new test cases would fail? I.e. the new test case does test that the fix works.

2022-04-08 11:55 UTC, PallaviGanorkar commented
> Looks good. Thanks for updating the test cases pallavi. Just one request: have you checked (locally is fine) that without the code change your new test cases would fail? I.e. the new test case does test that the fix works.

Yes Jing, I have tested locally on emulator with API level 24, 27 & 30 before code changes test cases were failing on API level 24 and 27 . Now after fix its working on all 3 API level

2022-04-08 15:34 UTC, merged