Add submit questionnaire button to sdc module
google/android-fhir pull request #1201
Opened 2022-02-24 13:22 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1088 

**Description**
Clear and concise code change description. 

- Show submit questionnaire button when layout is default.
- Show Submit questionnaire button instead of Next button on last page when layout is paginated
- Add onSubmit callback onSubmit button click
- Make visible, invisible,  and Gone submit button through custom style.  

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-02-25 12:59 UTC, santosh-pingle commented
- when Submit questionnaire button visibility declared as gone in custom style in catalog app

https://user-images.githubusercontent.com/86107848/155719129-dc376bbf-f201-4c08-8dd8-19da0360ef7e.mov




-  by default submit questionnaire button visibility is visible and only visible when scroll reach at the bottom of the page in default layout and  on last page when layout is paginated.


https://user-images.githubusercontent.com/86107848/155718699-0e1fb165-ca3a-4f51-991a-880dba4bfee3.mov

2022-05-19 10:57 UTC, jingtang10 requested changes
can you make the submit button always visible in this case - i think showing and hiding it depending on scroll seems a bit strange.

alternatively, i think we could make the submit button an additional item in the recycler view so it will be just at the bottom of the questionnnaire. but we should check with @shelaghm on that one. for now the simplest implmentation that is consistent with the paginated layout is just to always show this button.

2022-05-19 10:57 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="submit_questionnaire">Submit questionnaire</string>
```suggestion
    <string name="submit_questionnaire">Submit</string>
```

2022-05-19 10:57 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +      "paginated_layout_questionnaire.json" -> R.style.Theme_Androidfhir
please update

2022-05-19 10:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    INVISIBLE,
do you need this - i don't think we want this to ever be invisible but taking up space.

2022-05-19 10:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  private enum class CustomStyleVisibility {
please check if it's possible just to rely on the android values which will save us the effort to define this.

2022-05-24 22:08 UTC, shelaghm commented
> can you make the submit button always visible in this case - i think showing and hiding it depending on scroll seems a bit strange.
> 
> alternatively, i think we could make the submit button an additional item in the recycler view so it will be just at the bottom of the questionnnaire. but we should check with @shelaghm on that one. for now the simplest implmentation that is consistent with the paginated layout is just to always show this button.

@santosh-pingle @jingtang10 
My perspective is that for default layout the submit button is only visible at the bottom of the whole questionnaire. The behavior I'm hoping to encourage is that users go through the whole survey. I want to avoid people accidentally clicking submit too early because it's visible to them, but they didn't know the survey was longer.

2022-05-26 09:54 UTC, santosh-pingle commented
> can you make the submit button always visible in this case - i think showing and hiding it depending on scroll seems a bit strange.
> 
> alternatively, i think we could make the submit button an additional item in the recycler view so it will be just at the bottom of the questionnnaire. but we should check with @shelaghm on that one. for now the simplest implmentation that is consistent with the paginated layout is just to always show this button.

https://user-images.githubusercontent.com/86107848/170464391-f414837f-9209-4025-909e-37544c89b3e9.mov

2022-05-26 10:11 UTC, jingtang10 commented
> > can you make the submit button always visible in this case - i think showing and hiding it depending on scroll seems a bit strange.
> > alternatively, i think we could make the submit button an additional item in the recycler view so it will be just at the bottom of the questionnnaire. but we should check with @shelaghm on that one. for now the simplest implmentation that is consistent with the paginated layout is just to always show this button.
> 
> @santosh-pingle @jingtang10 My perspective is that for default layout the submit button is only visible at the bottom of the whole questionnaire. The behavior I'm hoping to encourage is that users go through the whole survey. I want to avoid people accidentally clicking submit too early because it's visible to them, but they didn't know the survey was longer.

@shelaghm in the paginated layout at the moment, we have the prev/next buttons always always visible. this is inconsistent with what you suggested here. should we change that too? if that's the case - we can probably add a follow-up pr to change both (single/multiple page layouts)

2022-05-26 11:02 UTC, jingtang10 requested changes

2022-05-26 11:02 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +    />
i prefer to have 1 single submit button so that the logic in your follow up PR can be simpler. if we need to tweak the style, we can still do it in code.

2022-05-26 14:32 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun Questionnaire.usesPagination() =
This change is not required anymore, therefore reverted it back.

2022-05-27 06:30 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/170643589-97b059ff-772b-4736-b683-6a5c1a0f8960.mov

2022-05-27 11:45 UTC, jingtang10 approved these changes

2022-05-30 11:47 UTC, merged