[1205] FhirEngine Sync Download API Re-design
google/android-fhir pull request #1206
Opened 2022-02-24 23:55 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1205 

**Description**
FhirEngine Sync Download API Redesign

See for details: https://docs.google.com/document/d/1UZ7Ndb8JRmB2UdXpfIkPT-VAra6X2aLSzdGI_a8KJkg/edit#

TESTED=all unit tests passed. Added one more unit test as well

tl;dr: give more functionality to developers to control what resources they can download.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
No, open to suggestions though!

**Type**
Choose one: (Bug fix | **Feature** | Documentation | Testing | Code health | Builds | Releases | Other)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-03-04 12:46 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +  abstract fun getExtractNextUrlsFromResource(): (Resource) -> Collection<String>
Should we encapsulate this in something like a `SyncDownloadContext`? Engine can provide a default implementation for it based on what we have implemented in `FhirPeriodicSyncWorker` and Developer  applications  may use it or provide their custom implementation based on the use case?

2022-03-08 13:12 UTC, Tarun-Bhardwaj commented
@omarismail94 , did you get a chance to work on the review comments? This issue is lined up for FHIR Engine Beta release next week.
CC: @jingtang10

2022-03-08 20:18 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +  abstract fun getExtractNextUrlsFromResource(): (Resource) -> Collection<String>
Great idea! I created an interface named `SyncDownloadExtractor` that users can implement. Provided a sample implementation in the `demo` code, This interface is need to instantiate a `FhirSyncWorker`

2022-03-08 20:20 UTC, omarismail94 commented
@aditya-07 lmk if there are other comments that need addressing. I created a new interface named `SyncDownloadExtractor` that users can implement. An implementation of this interface is needed to instantiate a `FhirSyncWorker`. 

Note that I refactored the functions to take in parameters now as opposed to creating lambdas to make things cleaner


> @omarismail94 , did you get a chance to work on the review comments? This issue is lined up for FHIR Engine Beta release next week. CC: @jingtang10

@Tarun-Bhardwaj  yes :)

2022-03-09 11:52 UTC, jingtang10 requested changes
are there no tests to collect the flow of the resources? do you think we should add a test class for fhirsynchronizer?

2022-03-09 11:52 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/data/SyncDownloadExtractorImpl.kt
> +      downloadUrl = preProcessUrl
some documentation / comments would be great for this

2022-03-09 11:52 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/data/SyncDownloadExtractorImpl.kt
> +    }
add a brief comment to explain the 2 cases

2022-03-09 11:52 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    syncJob.run(fhirEngine, dataSource, TestingUtils.TestSyncDownloadExtractorImpl, flow)
the `resourceSyncParam` in this class can be deleted?

2022-03-09 11:55 UTC, jingtang10 requested changes

2022-03-09 11:55 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncDownloadExtractor.kt
> +interface SyncDownloadExtractor {
just brainstorming, this is optional :)
```suggestion
interface DownloadProcessor {
```


```suggestion
interface DownloadHandler {
```

2022-03-10 12:30 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +            val preprocessedUrl = listOfUrls.removeAt(0)
Better make `listOfUrls` a `Queue<String>` and use appropriate apis.

2022-03-14 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +            val preprocessedUrl = listOfUrls.removeAt(0)
Changed to a queue. Good idea!

2022-03-14 13:06 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/SyncDownloadExtractor.kt
> +interface SyncDownloadExtractor {
I saw the `FhirSynchronizer` contains a reference to `Uploader`, so I changed the name to `Downloader`. Lmk if that works!

2022-03-14 13:08 UTC, omarismail94 commented
> are there no tests to collect the flow of the resources? do you think we should add a test class for fhirsynchronizer?

 @jingtang10  Added a test to count the number of times resources get loaded that should be equal to the length of the queue

Also addressed all comments you made. Lmk if there's anything else you want!

2022-03-15 10:27 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncDownloadExtractor.kt
> +interface SyncDownloadExtractor {
i think the uploader does something different, it actually does the uploading!

i think here maybe download processor is better. @aditya-07 even suggested DownloadPrePostProcessor, or DownloadManager?

2022-03-15 10:27 UTC, jingtang10 approved these changes
thanks @omarismail94!

2022-03-15 12:53 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/SyncDownloadExtractor.kt
> +interface SyncDownloadExtractor {
Renamed to `DownloadManager`!

2022-03-15 14:07 UTC, merged