Added support for hidden items in validateQuestionnaireResponseAnswers
google/android-fhir pull request #1214
Opened 2022-03-02 04:38 UTC by shoaibmushtaq25

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1051 

**Description**
Hidden questionnaire items are not handled in the QuestionnaireResponseValidator in validateQuestionnaireResponseAnswers method.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-03 08:48 UTC, jingtang10 commented
@joiskash can you take a look as well please? thanks!

2022-03-04 06:46 UTC, ndegwamartin approved these changes

2022-03-04 07:08 UTC, f-odhiambo commented
@Tarun-Bhardwaj This PR is ready for review from Google SDK team side

2022-03-04 07:30 UTC, ndegwamartin commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
> +  fun validateQuestionnaireAnswers_questionnaireHasHiddenItems_shouldReturnValidResult() {
@shoaibmushtaq25 could we rename this test case to something like 
`validateQuestionnaireResponseAnswers_questionnaireResponseHasFewerItemsThanQuestionnaire_shouldReturnValidResult`
or 
`validateQuestionnaireResponseAnswers_questionnaireResponseHasFewerItems_shouldReturnValidResult`

2022-03-04 07:31 UTC, shoaibmushtaq25 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
> +  fun validateQuestionnaireAnswers_questionnaireHasHiddenItems_shouldReturnValidResult() {
Done

2022-03-04 08:40 UTC, joiskash requested changes
Just a general comment, the recursive logic was written by me a long time ago. I would rather have it follow the same pattern as  
1. checkQuestionnaireResponse => validateQuestionnaireResponse
2. checkQuestionnaireResponseItems => validateQuestionnaireResponseItems
3. checkQuestionnaireResponseItem => validateQuestionnaireResponseItem (handle all answers not just answer[0] )
4. checkQuestionnaireReponseAnswerItem => validateQuestionnaireResponseAnswerItem ( you probably do not need this one)

Make these functions return the output of as maps and use linkIdToValidationResultMap.putAll( )
I know this will be a breaking change for OpenSRP since the public api will now be changed from validateQuestionnaireResponseAnswers to validateQuestionnaireResponse . But it just seems like better, simpler code that's easy to understand considering the complicated tree structure of questionnaireItems and questionnaireResponseItems. 

@jingtang10 not sure how you feel about this.

2022-03-04 11:32 UTC, shoaibmushtaq25 commented
> Just a general comment, the recursive logic was written by me a long time ago. I would rather have it follow the same pattern as
> 
> 1. checkQuestionnaireResponse => validateQuestionnaireResponse
> 2. checkQuestionnaireResponseItems => validateQuestionnaireResponseItems
> 3. checkQuestionnaireResponseItem => validateQuestionnaireResponseItem (handle all answers not just answer[0] )
> 4. checkQuestionnaireReponseAnswerItem => validateQuestionnaireResponseAnswerItem ( you probably do not need this one)
> 
> Make these functions return the output as maps and use linkIdToValidationResultMap.putAll( ) I know this will be a breaking change for OpenSRP since the public api will now be changed from validateQuestionnaireResponseAnswers to validateQuestionnaireResponse . But it just seems like better, simpler code that's easy to understand considering the complicated tree structure of questionnaireItems and questionnaireResponseItems.
> 
> @jingtang10 not sure how you feel about this.

Thanks @joiskash for the detailed comment. I am open to this suggestion. Just want to get a go ahead before this change as this change would have a breaking api change for OpenSRP as you mentioned. On the other point, to check all the answer items, I thought about it to cover in this issue but i see that there is a [github issue#487](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt#L56) which is already created to check all the answer items. 

so what do you think that should we cater this in this PR or under the other [issue#487](https://github.com/google/android-fhir/issues/487) ?

2022-03-04 11:38 UTC, joiskash commented
We could cover in this and close that issue, since its just a matter of using for each. Initially we did not have any support for answer.repeats = true, but now we do have partial support. But as you said, lets just get another opinion from jing and maybe martin before doing the changes suggested by me.

2022-03-04 12:01 UTC, shoaibmushtaq25 commented
> We could cover in this and close that issue, since its just a matter of using for each. Initially we did not have any support for answer.repeats = true, but now we do have partial support. But as you said, lets just get another opinion from jing and maybe martin before doing the changes suggested by me.

Okay, great. Let's wait for the opinion from @jingtang10 / @ndegwamartin

2022-03-04 14:28 UTC, ndegwamartin commented
> > We could cover in this and close that issue, since its just a matter of using for each. Initially we did not have any support for answer.repeats = true, but now we do have partial support. But as you said, lets just get another opinion from jing and maybe martin before doing the changes suggested by me.
> 
> Okay, great. Let's wait for the opinion from @jingtang10 / @ndegwamartin

@shoaibmushtaq25 I'm okay with refactoring for cleaner more concise code. We can create a new ticket on FHIR Core to track migration of the breaking API cc @f-odhiambo

2022-03-04 14:34 UTC, shoaibmushtaq25 commented
> > > We could cover in this and close that issue, since its just a matter of using for each. Initially we did not have any support for answer.repeats = true, but now we do have partial support. But as you said, lets just get another opinion from jing and maybe martin before doing the changes suggested by me.
> > 
> > 
> > Okay, great. Let's wait for the opinion from @jingtang10 / @ndegwamartin
> 
> @shoaibmushtaq25 I'm okay with refactoring for cleaner more concise code. We can create a new ticket on FHIR Core to track migration of the breaking API cc @f-odhiambo

It's okay, I will do that. Thanks @ndegwamartin for your input on this.

2022-03-07 11:09 UTC, Tarun-Bhardwaj commented
@shoaibmushtaq25 , @ndegwamartin please let me know once this PR has been reviewed internally and ready for review by Google.

2022-03-07 11:27 UTC, shoaibmushtaq25 commented
> @shoaibmushtaq25 , @ndegwamartin please let me know once this PR has been reviewed internally and ready for review by Google.

sure @Tarun-Bhardwaj , will let you know after completing the mentioned feedback

2022-03-08 06:08 UTC, shoaibmushtaq25 commented
@ndegwamartin ,the PR is updated with the feedback, Please review it again. Thanks

2022-03-08 07:00 UTC, ellykits approved these changes
LGTM :+1:

2022-03-08 08:43 UTC, shoaibmushtaq25 commented
Hey @Tarun-Bhardwaj , This PR is ready for review by Google. You can follow up on that now. Thanks

2022-03-08 09:01 UTC, joiskash approved these changes
Looks good to me, just left some small comments.

2022-03-08 09:45 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +   * Validates that the [QuestionnaireResponse] is structurally consistent with the [Questionnaire].
Done.

2022-03-08 09:45 UTC, shoaibmushtaq25 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
> +  private fun assertValidateQuestionnaireResponseThrowsIllegalArgumentException(
Done.

2022-03-08 09:48 UTC, shoaibmushtaq25 commented
> Looks good to me, just left some small comments.

Thanks @joiskash , Its' done. You can have a look again.

2022-03-08 11:51 UTC, merged

2022-04-17 21:16 UTC, jingtang10 reviewed
@joiskash @shoaibmushtaq25 @ellykits left a few comments. if we need to do any work we can raise a follow-up PR. thanks!

2022-04-17 21:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
>    private val linkIdToValidationResultMap = mutableMapOf<String, MutableList<ValidationResult>>()
this should not be a private variable. you shouldn't keep any state between two calls of `validateQuestionnaireResponse`

2022-04-17 21:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +
remove new line

2022-04-17 21:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +
remove new line

2022-04-17 21:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +  fun validateQuestionnaireResponse(
what's the relationship between this API and the `checkQuestionnaireResponse` API? if this API does everything the other one do, why do we need the other one? or, why shouldn't this API call the other one instead of repeating the same code?

a lot of the code in this function is basically duplicated code from the other function. this is an issue. this means either we're not reusing code correctly, or we need to reconsider the boundaries of these APIs.

one thing i think can work is that, we make it clear the `check` api is checking the questionnaire response structurally, and this `validate` api is using the validators to check the answers are as expected.

that means we should remove the checks that are exactly the same.... and maybe explicitly document we expect the user calls the other api first to check the structural validity of the questionnaire response before calling this api. that way, in the implementation of this api we can just assume that the questionnaire response has a valid structure.

2022-04-18 06:37 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +  fun validateQuestionnaireResponse(
Yes this makes perfect sense. Check questionnaire -> structural validation , Validate Questionnaire -> validate against constraints defined in the Questionnaire. We should remove the same checks  and add explicit documentation.