Use sdc submit button to submit questionnaire in catalog app.
google/android-fhir pull request #1215
Opened 2022-03-02 09:42 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1211 

**Description**
Remove Submit questionnaire menu from catalog app, and related files and resources.
Use datacapture Submit questionnaire button.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-17 22:26 UTC, jingtang10 requested changes

2022-04-17 22:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +open class QuestionnaireFragment(val onSubmitClick: (() -> Unit)?) : Fragment() {
should this be optional?

2022-04-17 22:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +open class QuestionnaireFragment(val onSubmitClick: (() -> Unit)?) : Fragment() {
what other ways of setting this callback have you considered?

@stevenckngaa @yigit @kevinmost @juanchazo fyi

2022-04-22 08:58 UTC, santosh-pingle commented
@jingtang10 
current pr is follow up pr of below pr.
can you please review pr https://github.com/google/android-fhir/pull/1201?

2022-05-27 11:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +open class QuestionnaireFragment(val onSubmitClick: (() -> Unit)?) : Fragment() {
We can also think about below approach.
Fragment result api can also be used to notify that submit button is clicked by sending boolean value.
Then QuestionnaireFragment will be used to fetch questionnaire response.

2022-05-27 11:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +open class QuestionnaireFragment(val onSubmitClick: (() -> Unit)?) : Fragment() {
I would be happier with the results API instead of the call back. Can you prototype?

2022-05-27 13:31 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +open class QuestionnaireFragment(val onSubmitClick: (() -> Unit)?) : Fragment() {
Using the result API detailed above sounds like a better approach; we should try to avoid adding constructor arguments to Fragments.

2022-05-30 12:38 UTC, jingtang10 commented
#1201 is merged.

2022-05-30 12:39 UTC, santosh-pingle commented
Working on review comments.

2022-05-31 06:44 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/171109278-95d102f8-381c-468c-a10d-335d95058c51.mov

2022-05-31 10:29 UTC, jingtang10 requested changes
love how the results api makes everything simpler! 👍

can you add some tests to the datacapture lib?

2022-05-31 10:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      setFragmentResult(SUBMIT_REQUEST_KEY, bundleOf(SUBMIT_CLICK_KEY to true))
don't you have to include the actual questionnaire response?

2022-05-31 10:52 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      setFragmentResult(SUBMIT_REQUEST_KEY, bundleOf(SUBMIT_CLICK_KEY to true))
Actually, without passing questionnaire response in bundle, host/parent fragment can access questionnaire response by `questionnaireFragment.getQuestionnaireResponse()` once it receive submit click event through result api.
this was only reason, thought not to include response in bundle.

2022-05-31 12:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      setFragmentResult(SUBMIT_REQUEST_KEY, bundleOf(SUBMIT_CLICK_KEY to true))
ok interesting. i think this is probably ok for now.

@williamito something to bear in mind for the documentation.

2022-05-31 12:18 UTC, santosh-pingle commented
> love how the results api makes everything simpler! 👍
> 
> can you add some tests to the datacapture lib?

Actually, there is separate issue https://github.com/google/android-fhir/pull/358 for Questionnaire Fragment tests, there is no QuestionnaireFragment test suite yet #358, thinking to have separate pr for code coverage once above pr in.
is that okay?

2022-05-31 12:28 UTC, jingtang10 commented
> > love how the results api makes everything simpler! 👍
> > can you add some tests to the datacapture lib?
> 
> Actually, there is separate issue #358 for Questionnaire Fragment tests, there is no QuestionnaireFragment test suite yet #358, thinking to have separate pr for code coverage once above pr in. is that okay?

i really don't want to set this precedent - but given how long this pr has been around this is ok. Please do a follow-up PR immediately!

2022-05-31 12:30 UTC, santosh-pingle commented
> > > love how the results api makes everything simpler! 👍
> > > can you add some tests to the datacapture lib?
> > 
> > 
> > Actually, there is separate issue #358 for Questionnaire Fragment tests, there is no QuestionnaireFragment test suite yet #358, thinking to have separate pr for code coverage once above pr in. is that okay?
> 
> i really don't want to set this precedent - but given how long this pr has been around this is ok. Please do a follow-up PR immediately!

Sure, Thanks!

2022-05-31 12:32 UTC, jingtang10 approved these changes

2022-05-31 12:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      setFragmentResult(SUBMIT_REQUEST_KEY, bundleOf(SUBMIT_CLICK_KEY to true))
can you try if an empty bundle would work?

2022-05-31 12:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val SUBMIT_CLICK_KEY = "submit-click-key"
can you see if an empty bundle would work and see if we can just get rid of this?

2022-05-31 13:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      setFragmentResult(SUBMIT_REQUEST_KEY, bundleOf(SUBMIT_CLICK_KEY to true))
Works!
Updated change.

2022-06-01 05:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      setFragmentResult("", Bundle.EMPTY)
done. thanks!
I am also of the same opinion.
I misunderstood one of the earlier comment.

2022-06-01 09:22 UTC, jingtang10 approved these changes

2022-06-01 13:01 UTC, merged