1083 973 date picker pop
google/android-fhir pull request #1216
Opened 2022-03-02 16:48 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1083 #973

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-03 14:57 UTC, jingtang10 commented
@santosh-pingle can you take a look at this first? thanks

2022-03-04 05:46 UTC, santosh-pingle commented
looking into it.

2022-03-04 09:56 UTC, santosh-pingle reviewed
Can you please add some screenshots?

I put some comments, please see whether those can be addressed.

2022-03-04 09:56 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
Can we please write tests for it?

2022-03-04 09:56 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDate.kt
> +  } else {
do we need else part?
Can you please refer this Java 8+ API desugaring support [Java 8+ API desugaring support ](https://developer.android.com/studio/write/java8-support#library-desugaring)?
I think it is possible to use java.time.* package without android sdk api constraint.

2022-03-04 09:56 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
Will ```Questionnaire.QuestionnaireItemComponent.dateEntryFormat``` be used to format the selected or entered input from picker, like format the input and show it in input text field

2022-03-04 09:56 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
Can we please add this extension to the ```date_picker_questionnaire.json``` and ```date_time_picker_questionnaire.json``` to show this use case?

2022-03-16 13:21 UTC, PallaviGanorkar commented
> Can you please add some screenshots?
> 
> I put some comments, please see whether those can be addressed.
![DateEntryFormatFromJson](https://user-images.githubusercontent.com/13957417/158599158-ac6244a7-2b99-4c06-9df5-fd83686af0eb.png)
![DateEntryFormatFromDeviceLocale](https://user-images.githubusercontent.com/13957417/158599215-1003fcf6-7d8c-4235-a165-adcd77450118.png)

2022-03-16 13:25 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
Added date entry format in date_picker_questionnaire.json only to demonstrate use case 1. If date entry format is available in questionnaire json file.
And not added date entry format in date_time_picker_questionnaire.json to demonstrate use case 2. If date entry format is NOT available in questionnaire json file then read date format from device locale

2022-03-16 13:27 UTC, PallaviGanorkar commented
> Can you please add some screenshots?
> 
> I put some comments, please see whether those can be addressed.

Added screen shot

2022-03-16 13:45 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
As per requirement, It only shows date format as helper text under the date picker

2022-03-22 14:55 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
Done

2022-03-22 14:55 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDate.kt
> +  } else {
Done

2022-03-30 09:28 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
This is part of validation, We will consider this under input validation ticket.

2022-03-30 12:05 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.dateEntryFormat: String?
Ok , can we please create separate issue and link here.

2022-03-30 12:06 UTC, santosh-pingle commented
looks ok to me. thanks!

2022-04-01 12:47 UTC, jingtang10 requested changes
for the 3 changes in the PR description, 1 and 2 can probably be grouped in this PR. But please raise a different PR for 3. thanks!

2022-04-04 06:57 UTC, PallaviGanorkar commented
As per comment crate two separate PR for this change

2022-04-04 06:57 UTC, closed without merging