Add test cases for FhirOperator.kt
google/android-fhir pull request #1220
Opened 2022-03-08 16:53 UTC by RaaziaTarique

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1075

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Testing

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-17 07:40 UTC, ekigamba requested changes

2022-03-17 07:40 UTC, ekigamba commented on .github/ci-gradle.properties
> + org.gradle.workers.max=4
Revert this change here

2022-03-17 07:40 UTC, ekigamba commented on workflow/build.gradle.kts
> +  tasks.withType<Test>().configureEach {
You can also revert the changes here

2022-03-17 07:43 UTC, RaaziaTarique commented on workflow/build.gradle.kts
> +  tasks.withType<Test>().configureEach {
if I revert these changes them, it'll throw Java Heap Exception locally.

2022-03-29 13:49 UTC, Tarun-Bhardwaj commented
@RaaziaTarique  , CI issue is fixed. Could you please check if you're still facing it?
CC: @f-odhiambo

2022-03-30 11:37 UTC, ekigamba requested changes

2022-03-30 11:37 UTC, ekigamba commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorPopulationTest.kt
> +    assertThat(measureReportJSON).isNotNull()
Can we assert the output of the report to make sure that this works as expected

2022-03-30 11:37 UTC, ekigamba commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +    assertThat("Patient/charity-otala-1").isEqualTo(measureReport.subject.reference)
Are there other values that we can assert that possibly provide 'documentation' on how this function is supposed to work

2022-04-21 08:06 UTC, closed without merging