Initial expression support extension
google/android-fhir pull request #1228
Opened 2022-03-10 08:06 UTC by RaaziaTarique

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1033 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-22 14:42 UTC, ekigamba requested changes

2022-03-24 08:19 UTC, RaaziaTarique commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fill QuestionnaireResponse with values when given a single Resource should use definition based extraction`() =
As per the discussion, I have removed the definition based initial expression evaluation code and test case as definition based initial expressions evaluation will be done in parallel with other expressions such as http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemPopulationContext.

2022-03-24 08:50 UTC, jingtang10 requested changes

2022-03-25 09:00 UTC, ekigamba requested changes

2022-03-25 10:36 UTC, RaaziaTarique commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return answersFound
I can remove the return value but keeping the method because it can be utilised if we are going to add the support of other expressions as well.

2022-03-29 13:46 UTC, Tarun-Bhardwaj commented
@RaaziaTarique , are these changes approved post internal review? Any ETA by when Google can review these?

2022-03-29 14:09 UTC, ekigamba requested changes

2022-03-29 14:09 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    var answerExtracted = mutableListOf<Base>()
Kindly rename this to extracted answer

2022-03-29 14:11 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fill QuestionnaireResponse with values when given a single Resource should use definition based extraction`() =
Cool

2022-03-30 09:57 UTC, ekigamba approved these changes

2022-03-30 10:27 UTC, RaaziaTarique commented
> @RaaziaTarique , are these changes approved post internal review? Any ETA by when Google can review these?

@Tarun-Bhardwaj, this PR has been reviewed and it's ready to be reviewed by Google.
CC: @ekigamba  @f-odhiambo @jingtang10

2022-04-04 15:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        evaluateInitialExpressionAndSetInitialValue(exp, resources, questionnaireItem)
```suggestion
      questionnaireItem.initialExpression?.let {
        evaluateInitialExpressionAndSetInitialValue(it, resources, questionnaireItem)
```

2022-04-04 15:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      questionnaireItem.initialExpression?.let { exp ->
I think this is much better as a extension function on questionnaireItem.

`fun QuestionnaireItem.setInitialValueFromInitialExpression()` seems appropriate.

you're passing the questionnaire item to the `evaluateInitialExpressionAndSetInitialValue` function which seems odd to me. All this happens within the context of the questionnaire item, so should probably be an extension function.

2022-04-04 15:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
this code seems duplicated to me. you're just saying if the context resource is empty just take the first resource as the context resource right?

i feel this code is actually harder to read and doesn't add any more functionality.

2022-04-04 15:34 UTC, RaaziaTarique commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
@jingtang10, this code added functionality to use `FhirPath functions` such as `today()`, `now()` and etc. 
Previously these functions were not supported in SDK because it was only using the extracted resource from the `FhirPath expression` and in case of `FhirPath functions`, the `FhirPath Expressions` doesn't have any resource name in it.

2022-04-04 17:14 UTC, RaaziaTarique commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    resources: Array<out Resource>,
Actually `vararg resources: Resource` converts to `Array<out Resource>`, when being passed to another method.

2022-04-05 09:17 UTC, RaaziaTarique commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      questionnaireItem.initialExpression?.let { exp ->
@jingtang10  I have created an extension function with slight modifications. Please re-review the PR.

2022-04-20 20:16 UTC, jingtang10 approved these changes

2022-04-21 12:01 UTC, aditya-07 approved these changes
LGTM

2022-04-21 13:13 UTC, stevenckngaa approved these changes

2022-04-22 10:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    if (initialExpression != null) {
done.

2022-04-22 12:38 UTC, jingtang10 commented
Struggling to make the tests pass on GitHub even though they're passing locally...

2022-04-22 17:28 UTC, jingtang10 commented
tests should hopefully pass after #1324

2022-04-23 05:23 UTC, merged