Reorganize Data Source and refactor code
google/android-fhir pull request #1230
Opened 2022-03-14 10:00 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1199 

**Description**
1. DataSource interface is changed to support apis for just  Bundle based upload and download of the resources.
2. DataSource is implemented by Engine and is now longer exposed to the outer application.
3. Downloader interface is introduced similar to the Uploader interface to abstract away the details from FhirSynchronizer.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-16 13:46 UTC, jingtang10 requested changes

2022-03-16 13:46 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/remote/DataSourceImpl.kt
> +internal class DataSourceImpl(private val fhirService: RemoteFhirService) : DataSource {
does it make any sense to merge this class with the remote fhir service class? i feel these two are the same thing in the sense that that is just an implementation of the data source api using retrofit.

2022-03-16 20:21 UTC, aditya-07 commented on engine/build.gradle.kts
> +  // testImplementation(Dependencies.Retrofit.retrofitMock)
Done

2022-03-16 20:21 UTC, aditya-07 commented on engine/build.gradle.kts
> +  implementation(Dependencies.httpInterceptor)
Done

2022-03-16 20:21 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/data/DownloadManagerImpl.kt
> +    if (resourceResponse is OperationOutcome) {
Done

2022-03-16 20:24 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/remote/DataSourceImpl.kt
> +internal class DataSourceImpl(private val fhirService: RemoteFhirService) : DataSource {
Removed `DataSourceImpl` as well.

2022-03-17 07:00 UTC, vvikramraj reviewed
Partly reviewed. This is going to take some time to finish.

2022-03-17 10:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Authenticator.kt
> +  suspend fun refreshToken(): Boolean
Yes. We can take that in a subsequent PR.

2022-03-17 12:40 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Downloader.kt
> +/** Module for downloading the changed resources from the server. */
done

2022-03-17 12:41 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/DataSource.kt
> +  suspend fun download(path: String): Resource
As per our offline discussion, keeping it same.

2022-03-17 12:41 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/DataSource.kt
> + * operations are [Bundle] based for quick sync.
done

2022-03-17 13:48 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> + * A configuration to provide the remote Fhir server url and an [Authenticator] for supplying any
done

2022-03-17 13:48 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> + * auth token that may be necessary to talk to the server.
Done

2022-03-17 13:49 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  @Synchronized
done

2022-03-17 13:55 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
>     * Initializes the [FhirEngine] singleton with a custom Configuration.
Do you mean the kdocs? `check` throws `IllegalStateException` with the message provided in the lambda in case it fails.

2022-03-17 19:15 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +            is DownloadResult.Failure -> exceptions.add(it.syncError)
ok the horrible github code review tool doesn't let me comment on unchanged lines but can we rename the `FhirSynchronizer.emit` to something like `setState` and also rename the `FhirSynchronizer.flow` syncState (or something like that). 
Re-using emit makes the code very hard to read right now so I spent 10 minutes trying to understand where these are emitting. (same for `emitResult`). Those methods are changing a sharedflow's value so likely better to call it setState or update state (or something like that).

2022-03-17 19:15 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/remote/RemoteFhirService.kt
> +                  val accessToken = runBlocking { it.getAccessToken() }
this is usually a risky thing to do. given that retrofit does not have a suspending APIs for these, we should ither:

a) change `getAccessToken` to not be a suspend function
b) use the authentication API from retrofit (though I don't fully remember how it was working so may or may not solve the suspending problem)

2022-03-21 10:55 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/remote/RemoteFhirService.kt
> +                  val accessToken = runBlocking { it.getAccessToken() }
Both okhttp3 Authenticator and Interceptor are similar and have non suspending functions. So making getAccessToken non suspending.

Another way could be to ditch the Interceptors altogether and add authToken as @Header in the api argument. Since the api callers are suspending functions themselves, they should be able to call suspending getAccessToken() without any issue.

Keeping it simple for now by marking `getAccessToken` non suspending.

2022-03-21 18:50 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  private fun checkOrInitializeFhirService(context: Context) {
done.

2022-03-21 18:50 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirServices.kt
> +  val dataSource: DataSource? = null
Done

2022-03-21 18:51 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Downloader.kt
> +internal sealed class DownloadResult {
Done

2022-03-21 18:51 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +            is DownloadResult.Failure -> exceptions.add(it.syncError)
Done.

2022-03-22 08:25 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/remote/RemoteFhirService.kt
> +                  val accessToken = runBlocking { it.getAccessToken() }
@aditya-07 probably ok, but can you write down if we need to switch to `@Header` and if so create a new issue? thanks!

2022-03-22 08:25 UTC, jingtang10 approved these changes

2022-03-22 15:43 UTC, yigit approved these changes

2022-03-23 08:58 UTC, merged