Add subtitle text to single choice view in sdc.
google/android-fhir pull request #1232
Opened 2022-03-14 13:07 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1233

**Description**
Subtitle text to single choice view.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-31 10:43 UTC, jingtang10 requested changes
please fix the failing tests. pr looks ok otherwise.

2022-04-01 18:27 UTC, jingtang10 requested changes
have you tested your fix on lower API levels?

is this not going to break lower API levels (<26)?

can you use margin top and bottom instead?

2022-04-04 07:00 UTC, santosh-pingle commented
> 



> have you tested your fix on lower API levels?
> 
> is this not going to break lower API levels (<26)?
> 
> can you use margin top and bottom instead?

Interestingly, it worked when item was added to the layout file, but if it presents in style then it does not apply the margin.

Now, top and bottom margin are added.

2022-04-06 11:10 UTC, jingtang10 approved these changes

2022-04-06 11:10 UTC, merged