test e2e
google/android-fhir pull request #1245
Opened 2022-03-21 02:16 UTC by omarismail94

DRAFT: 

Just want to see if I can interact with emulator outside of testing

2022-03-28 12:02 UTC, jingtang10 commented
@omarismail94 thanks so much for this I'm seeing:

```
/data/data/com.google.android.fhir.demo/databases/resources.db: 1 file pulled, 0 skipped. 93.6 MB/s (954368 bytes in 0.010s)
Number of patients in App's DB is: 224
Number of patients in HAPI server is: 224.
```

does this mean this is successful?

2022-03-28 14:12 UTC, omarismail94 commented
> @omarismail94 thanks so much for this I'm seeing:
> 
> ```
> /data/data/com.google.android.fhir.demo/databases/resources.db: 1 file pulled, 0 skipped. 93.6 MB/s (954368 bytes in 0.010s)
> Number of patients in App's DB is: 224
> Number of patients in HAPI server is: 224.
> ```
> 
> does this mean this is successful?

Yes, I added an extra line at the end to show the test was a success

2022-03-29 13:39 UTC, jingtang10 commented
> > @omarismail94 thanks so much for this I'm seeing:
> > ```
> > /data/data/com.google.android.fhir.demo/databases/resources.db: 1 file pulled, 0 skipped. 93.6 MB/s (954368 bytes in 0.010s)
> > Number of patients in App's DB is: 224
> > Number of patients in HAPI server is: 224.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does this mean this is successful?
> 
> Yes, I added an extra line at the end to show the test was a success to make it clear

this is fantastic - thanks so much for adding this.

2022-03-29 13:41 UTC, jingtang10 requested changes

2022-03-29 20:28 UTC, omarismail94 commented on e2e/e2e.sh
> +echo "Number of patients in HAPI server is: ${patient_count_in_hapi}"
I can add a Docker image with a local HAPI FHIR Server!

2022-05-30 19:41 UTC, jingtang10 commented
closing this for now @omarismail94

2022-05-30 19:41 UTC, closed without merging