Datacapture, material date picker.
google/android-fhir pull request #1257
Opened 2022-03-24 07:19 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1109 

**Description**
Add material date picker.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**
<img width="433" alt="Screen Shot 2022-03-24 at 12 46 49 PM" src="https://user-images.githubusercontent.com/86107848/159862799-363d76c0-0e42-43ab-adb7-03af27374444.png">

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-01 18:48 UTC, jingtang10 requested changes

2022-04-01 18:48 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt
> +
why this test case? is this just testing system apis?

2022-04-01 18:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  get() = DateType(localDate.year, localDate.monthValue - 1, localDate.dayOfMonth)
i don't think this makes sense to be an extension function.

having date as a property of a long number is strange, it's not a universal feature. this should be a function.

2022-04-01 18:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  get() = Instant.ofEpochMilli(this).atZone(ZoneId.of("UTC")).toLocalDate()
i don't think this makes sense to be an extension function. this should be a function.

2022-04-01 18:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  get() = Instant.ofEpochMilli(this).atZone(ZoneId.of("UTC")).toLocalDate()
actually this function isn't doing the right thing. you shouldn't be able to convert a long to a local date. you're assuming the timezone here and it's not correct. i don't think this function should exist.

2022-04-01 18:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  get() = DateType(localDate.year, localDate.monthValue - 1, localDate.dayOfMonth)
same here. i don't think this function should exist.

2022-04-04 10:23 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  get() = DateType(localDate.year, localDate.monthValue - 1, localDate.dayOfMonth)
yes, every long can not be converted to DateType.

Done.

2022-04-04 10:41 UTC, jingtang10 requested changes

2022-04-04 10:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +                .atZone(ZoneId.of("UTC"))
extract a constant to be used for date conversion.

2022-04-05 11:45 UTC, kevinmost approved these changes

2022-04-05 17:48 UTC, jingtang10 approved these changes

2022-04-05 17:48 UTC, merged