Provide ResourceSyncParams based DownloadManager for syncing data.
google/android-fhir pull request #1259
Opened 2022-03-24 17:32 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[1258](https://github.com/google/android-fhir/issues/1258)

**Description**
Implemented  ResourceParamsBasedDownloadManager which takes ResourceSyncParams to generate the search urls for the resources and parses Bundle SearchSet to get extract resources and next urls. 

**Alternative(s) considered**
No

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ x I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-03-24 17:49 UTC, omarismail94 reviewed
Nice change! Just one minor comment

2022-03-24 17:49 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +typealias ResourceSyncParams = LinkedHashMap<ResourceType, ParamMap>
Do we need the insertion order character of `LinkedHashMap` vs a `HashMap`?

2022-03-24 18:01 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
One more question: 

Looking at the `LinkedList` documentation, it seems the implementation is unsynchronized: 

https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html


Do you see us having a case of two threads accessing the list content? I don't think so as the whole download happens in one coroutine

2022-03-28 05:52 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
This shouldn't be a problem as the whole download process happens in a single thread.

2022-03-28 06:56 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +typealias ResourceSyncParams = LinkedHashMap<ResourceType, ParamMap>
The order is required incase the developer application wants to download the resources in the given order. Reverting the change and the code will now depend on the order provided by the developer app. App developers can use `mapOf()` function as it makes sure that Entries of the map are iterated in the order they were specified.

2022-03-28 09:46 UTC, jingtang10 requested changes

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +class ResourceParamsBasedDownloadManager(syncParams: ResourceSyncParams) : DownloadManager {
do the following

1. remove `SyncConfiguration` in `Config.kt` and clean up `ParamMap.concatParams`
2. move `ResourceSyncParams` to this file
3. rename `ResourceSyncParams` to `ResourceSearchParams` as they are actually search parameters and have nothing to do with uploading.

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun setup() {
can this not be initialized on line 35 and remove `lateinit` keyword? and you can remove this method altogether.

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
feelsl ike `Map.Entry<ResourceType, ParamMap>` could have a typealias

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun getInitialUrl_shouldReturnPatientUrl() {
don't mention patient in the test name. it's not relevant.

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun createDownloadUrl_shouldBeSameAsInitialUrlIfNoLastUpdate() {
split into 2:

- `shouldReturnInitialUrlWithNullLastUpdatedTimestamp`
- `shouldReturnInitialUrlWithEmptyLastUpdatedTimestamp`

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun extractResourcesFromResponse_withBundleTypeSearchSet_shouldReturnPatient() {
this can jus be

- `extractResourcesFromResponse`

as this is the canonical case.

but in any case don't mention patient as it's not relevant to waht this test case is doing.

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun extractResourcesFromResponse_withResourceOtherThanBundleTypeSearchSet_shouldReturnEmptyList() {
```suggestion
  fun extractResourcesFromResponse_withTransactionResponseBundle_shouldReturnEmptyList() {
```

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +    assertThat(initialUrl).isEqualTo("Patient?address-city=NAIROBI&_sort=_lastUpdated")
don't assert on this - this is not what this test case is testing

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
hang on - why is this `queue` here?

i imagined this class to be more or less stateless, the queue should really be managed by the caller of this download manager.

@omarismail94

2022-03-28 09:46 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +    assertThat(resources).hasSize(2)
superfuluous assertion - line 104 subsumes this line.

2022-03-28 11:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
The idea here is that the calling application doesn't have to know the working of the `DownloadManager`. All it does is provide `ResourceSyncParams` like before and expect the download sync to work. For this reason, the  `ResourceParamsBasedDownloadManager` needs to sort of have a state to figure out the remaining params that need to be synced.

2022-03-30 06:58 UTC, jingtang10 approved these changes

2022-03-30 08:56 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun setup() {
I have made ResourceParamsBasedDownloadManager local to each test.

2022-03-30 08:56 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
Not required anymore with the changes.

2022-03-30 08:56 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun getInitialUrl_shouldReturnPatientUrl() {
Not required anymore with the changes.

2022-03-30 08:57 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun createDownloadUrl_shouldBeSameAsInitialUrlIfNoLastUpdate() {
Done for `getNextRequestUrl` api tests.

2022-03-30 08:58 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun extractResourcesFromResponse_withResourceOtherThanBundleTypeSearchSet_shouldReturnEmptyList() {
Done with `processResponse_withTransactionResponseBundle_shouldReturnEmptyList` .

2022-03-30 08:59 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +  fun extractResourcesFromResponse_withBundleTypeSearchSet_shouldReturnPatient() {
Done with `getNextRequestUrl_shouldReturnNextResourceUrls` & `getNextRequestUrl_shouldReturnResourceAndPageUrlsAsNextUrls` apis.

2022-03-30 08:59 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManagerTest.kt
> +    assertThat(initialUrl).isEqualTo("Patient?address-city=NAIROBI&_sort=_lastUpdated")
Done

2022-03-30 09:02 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadManager.kt
> +  private val queue: Queue<Map.Entry<ResourceType, ParamMap>> = LinkedList(syncParams.entries)
After the `DownloadWorkManager` interface change, `ResourceParamsBasedDownloadWorkManager` now keeps the state of the Resources being downloaded and the next Resources to be downloaded.

2022-03-30 09:06 UTC, merged