Implement FhirEngineDal
google/android-fhir pull request #1273
Opened 2022-04-01 06:59 UTC by epicadk

- impl test
- remove nulls

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1168

**Description**
Clear and concise code change description. 

Implemented the Fhir Engine Dal

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
nil

**Type**
Choose one: Feature
**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-04 09:37 UTC, ktarasenko requested changes
Thanks! I left a few minor comments.

2022-04-04 09:37 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineDal.kt
> +  override fun search(resourceType: String): MutableIterable<IBaseResource> {
is there a good reason to keep it Mutable?  Same for other ones

2022-04-04 09:37 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirEngineDalTest.kt
> +class FhirEngineDalTest2 {
class name doesn't match the test name. What is the difference between this and the other test in this PR? 
I

2022-04-11 08:35 UTC, epicadk commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirEngineDalTest.kt
> +class FhirEngineDalTest2 {
Sorry was facing some issues so was trying to run them on a device. Will refractor this.

2022-04-11 08:37 UTC, epicadk commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineDal.kt
> +  override fun search(resourceType: String): MutableIterable<IBaseResource> {
By mutable do you mean the return type? I'm not sure we can change that since we aren't defining the function signature.

2022-04-11 09:29 UTC, epicadk commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineDal.kt
> +  override fun search(resourceType: String): MutableIterable<IBaseResource> {
I don't think so. But I don't think that is within the scope of this pr either : /.

2022-04-25 12:45 UTC, vitorpamplona commented
What's the state of this PR? I will need to get to the DAL very soon. It would be nice if we can fix the last issues and merge it.

2022-04-26 10:34 UTC, epicadk commented
It depends on how we want to initialize the test fhir engine. 
@jingtang10 @ktarasenko ?

2022-04-27 15:26 UTC, epicadk commented
> @epicadk I'm not sure I understood the question

rephrased it

2022-05-02 10:52 UTC, epicadk commented
@jingtang10 ready for review

2022-05-02 12:39 UTC, vitorpamplona commented
@epicadk, an aesthetic suggestion: You can do this: 

```kotlin 
  override fun create(resource: IBaseResource): Unit = runBlocking {
     fhirEngine.create(resource as Resource)
  }
```

Instead of this:
```kotlin 
  override fun create(resource: IBaseResource) {
    runBlocking { fhirEngine.create(resource as Resource) }
  }
```

2022-05-02 12:40 UTC, epicadk commented
btw something we can have in this pr or future prs would be to create a custom scope and using that here instead of runblocking.

2022-05-02 12:47 UTC, vitorpamplona approved these changes
This DAL works great on my Generate CarePlan branch.

2022-05-06 12:14 UTC, vitorpamplona commented
@jingtang10 any chance we can merge this soon?

2022-05-20 15:52 UTC, jingtang10 approved these changes

2022-05-23 13:12 UTC, merged