Add testcase that references an Observation.
google/android-fhir pull request #1280
Opened 2022-04-06 09:07 UTC by ktarasenko

WIP. 
Fixes #1107

**Description**
Add more complex test case for evaluateMeasure that refrerences an observation and an episode of care without the context value

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug fix| Testing 

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-07 16:55 UTC, jingtang10 requested changes
fantastic progress! thanks so much @ktarasenko

@f-odhiambo can you please also leave a review?

2022-04-07 16:55 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +                // filter(Patient.ACTIVE, { value = of(true) })
do you need to uncommen this?

2022-04-07 16:55 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +                // filter(Patient.ACTIVE, { value = of(true) })
ditto

2022-04-07 16:55 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +class FhirOperator(fhirContext: FhirContext, fhirEngine: FhirEngine, debugLogsOn: Boolean = false) {
have you looked into using Timber? wouldn't really want this to be in the public api i think.

2022-04-07 16:55 UTC, jingtang10 commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +    assertThat(measureReportJSON).isNotNull()
this is just testing the serialization? i feel we don't need this.

2022-04-07 16:55 UTC, jingtang10 commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +    assertThat(measureReport).isNotNull()
this is subsumed by later lines. so i'd vote removing this line.

2022-04-07 16:55 UTC, jingtang10 commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +        measureReport.evaluatedResource.any { it.reference == "Observation/anc-b6-de17-example" }
use of `any` seems very lenient in test cases. can we harden it?

same with below

2022-04-12 15:24 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +class FhirOperator(fhirContext: FhirContext, fhirEngine: FhirEngine, debugLogsOn: Boolean = false) {
The logging of cql evaluator is a bit tricky. It's also doesn't really log anything, but rather dumps some debug information in memory. I will revert this part to avoid the confusion.

2022-04-12 15:25 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +    assertThat(measureReportJSON).isNotNull()
right, there should be a special test case for it. Removing

2022-04-12 15:25 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +    assertThat(measureReport).isNotNull()
done

2022-04-12 16:44 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
> +        measureReport.evaluatedResource.any { it.reference == "Observation/anc-b6-de17-example" }
done

2022-04-12 22:39 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +                // filter(Patient.ACTIVE, { value = of(true) })
I cleaned up filtering for now

2022-04-12 22:39 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +                // filter(Patient.ACTIVE, { value = of(true) })
removed

2022-04-12 22:39 UTC, ktarasenko commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +/** The builder for [FhirEngine] instance. */
Having FhirEngineProvider as a singleton creates some problems in tests. @epicadk , @jingtang10  do you think it makes sense to convert it to a normal class and move the burden of keeping a single instance of it to clients?

2022-04-17 22:01 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +/** The builder for [FhirEngine] instance. */
can you elaborate?

@yigit @aditya-07 @stevenckngaa @kevinmost fyi

2022-04-19 09:34 UTC, ktarasenko commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +/** The builder for [FhirEngine] instance. */
Workflow library E2E tests require a real instance of the `FhirEngine`. Currently the only way to create the `FhirEngine` is through `FhirEngineProvider`, which maintains a single instance of the `FhirServices`. 
To improve testability, we either need a way to clean up the `FhirEngine` instance or to have a fresh instance of it for every test (add a way to reset the `FhirServices` singleton). 
I'd prefer the second option. 
As a next step, given that singletons in android are generally frowned upon, I would suggest to get rid of memoisation part of the `FhirEngineProvider` and let it create a fresh instance of the `FhirEngine` every time. This way clients can chose their way of maintaining the single instance of the FhirEngine.

2022-04-19 15:53 UTC, ktarasenko commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +/** The builder for [FhirEngine] instance. */
@jingtang10  actually, the second Robolectric test doesn't work if the DB instance wasn't closed after every test case (in the @After method), so to be able to have all testcases in a single test file, this change is needed to be in this PR.

2022-05-03 13:44 UTC, ktarasenko commented
@jingtang10  @vitorpamplona  @f-odhiambo  Updated the CL, PTAL

2022-05-05 05:03 UTC, f-odhiambo approved these changes
I run the test based on the newly added resources and the $evaluate_measure works for Individual measure reporting. There is a bug in Population measure reporting after adding multiple patients but I think it is more of a CQL than an API error. Can be sorted in a separate PR. I think we can merge this in now

2022-05-05 07:51 UTC, f-odhiambo commented
I think this ticket can be merged in as the remaining issue is CQL related  - Evaluation fails if we have more than 1 patient being evaluated for ANC Indicator 1 measure reporting. This occurs when you are trying to do a measure reporting evaluation for a population for more than 1 patient  

```
The following errors were encountered during evaluation:
[pool-1-thread-1] WARN ca.uhn.fhir.parser.LenientErrorHandler - Found incorrect type for element type - Expected ARRAY and found OBJECT
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b9-de33 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b6-de99 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de220 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b9-de79 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b6-de26 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b9-de34 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de241 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de217 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b9-de35 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-c-de5 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de221 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de218 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de222 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-end-38 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-persona is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/core/ValueSet/who-identifier-types is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-care-codes is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-activity-codes is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b6-de25 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-end-39 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de219 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b6-de22 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-end-24 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de224 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-b10-de225 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.engine.terminology.BundleTerminologyProvider - ValueSet http://fhir.org/guides/who/anc-cds/ValueSet/anc-c-de1 is not expanded. Falling back to compose definition. This will potentially produce incorrect results.
[pool-1-thread-1] WARN ca.uhn.fhir.parser.LenientErrorHandler - Unknown element 'role' found while parsing
[pool-1-thread-1] WARN ca.uhn.fhir.parser.LenientErrorHandler - Unknown attribute 'value' found while parsing
[pool-1-thread-1] WARN ca.uhn.fhir.parser.LenientErrorHandler - Found incorrect type for element type - Expected ARRAY and found OBJECT
[pool-1-thread-1] WARN org.opencds.cqf.cql.evaluator.fhir.DirectoryBundler - Error parsing resource /Users/fodhiambo/Sites/smart-anc/input/tests/library/ANCIND01/validated-resources/Popul [...]

2022-05-25 10:31 UTC, Tarun-Bhardwaj commented
@f-odhiambo is there an ETA by when this PR can be merged?

2022-05-25 11:12 UTC, f-odhiambo commented
I need access to push an update to Kostia's PR to be reviewed and merged. 
cc @jingtang10 . This work is less than 1 day to review and merge

2022-05-27 13:03 UTC, jingtang10 approved these changes

2022-05-29 12:22 UTC, merged