Test cases added for dialog in Single choice and Multi choice widget
google/android-fhir pull request #1288
Opened 2022-04-13 10:30 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #782 

**Description**
1. Test cases added for dialog having single choice widget
2. Test cases added for dialog having multiple choice widget

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-21 11:30 UTC, jingtang10 requested changes
thanks @PallaviGanorkar!

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +
nit: remove leading blank line.

same below.

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(
import `assertThat`. and below.

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  private fun answerOptions(multiSelect: Boolean, vararg options: String) =
static? so put in companion obj?

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  private fun responseOptions(vararg responses: String) =
same. static.

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +      }
```suggestion
      repeats = multiSelect
```

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    onView(ViewMatchers.withId(R.id.multi_select_summary_holder)).perform(clickIcon(true))
```suggestion
    onView(ViewMatchers.withId(R.id.multi_select_summary_holder)).perform(clickIcon(isEndIcon = true))
```

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +      .isEqualTo("Coding 1, Coding 3, Coding 5")
but also check the questionnaire response item

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +
remove blank line

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldCancelMultipleChoiceDropDown() {
change this test case or add a new one so that you click code 1 and/or 3 and/or 5 and click cancel.

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    onView(ViewMatchers.withText("Coding 3")).perform(ViewActions.click())
i think 2 clicks is enough and keeps the test case simple but covers everything.

2022-04-21 11:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldCancelSingleOptionDropDown() {
same. select something and then cancel.

2022-04-22 06:08 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +
Done

2022-04-22 06:14 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(
Done

2022-04-22 06:16 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +      }
Done

2022-04-22 06:17 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +
Done

2022-04-22 06:35 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  private fun answerOptions(multiSelect: Boolean, vararg options: String) =
Done

2022-04-22 06:36 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  private fun responseOptions(vararg responses: String) =
Done

2022-04-22 06:36 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldCancelMultipleChoiceDropDown() {
Added new test case

2022-04-22 06:36 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldCancelSingleOptionDropDown() {
Added new test case

2022-04-22 06:53 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    onView(ViewMatchers.withText("Coding 3")).perform(ViewActions.click())
> i think 2 clicks is enough and keeps the test case simple but covers everything.

Done

2022-04-22 06:57 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    onView(ViewMatchers.withId(R.id.multi_select_summary_holder)).perform(clickIcon(true))
Done

2022-04-22 07:44 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +      .isEqualTo("Coding 1, Coding 3, Coding 5")
Done

2022-04-22 12:57 UTC, jingtang10 requested changes

2022-04-22 12:57 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    onView(ViewMatchers.withText("Coding 3")).perform(ViewActions.click())
is it possible to create functions to make these tests more readable? for example, I feel this test case should really be like:

```
clickOption("Coding 1")
clickOption("Coding 3")
clickOption("Coding 5")
clickOK()

assertTextSummary().isEqualTo("1, 3, 5")
assertAnwers().isEqualTo("1", "3","5")
```

would this be better? I think this way the tests woudl be much more readable.

2022-05-02 07:00 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +    onView(ViewMatchers.withText("Coding 3")).perform(ViewActions.click())
Done

2022-05-02 13:01 UTC, jingtang10 requested changes

2022-05-02 13:01 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldCancelMultipleChoiceDropDown() {
i kinda feel like `shouldSelectThenCancelMultipleChoiceDropDown` is enough? so you can remove this test case

2022-05-02 13:01 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldCancelSingleOptionDropDown() {
likewise, this is subsumed by the next test case?

2022-05-06 06:53 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/EspressoUtilities.kt
> +  Espresso.onView(ViewMatchers.withText(text)).perform(ViewActions.click())
Its already handled.

2022-05-06 07:14 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/EspressoUtilities.kt
> +  Truth.assertThat(
Its already handled.

2022-05-06 08:38 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/EspressoUtilities.kt
> +    .perform(ViewActions.click())
Its handled in Custom ViewAction class

2022-05-12 11:34 UTC, jingtang10 approved these changes
just a few small nits. thanks for the change!

2022-05-12 11:34 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/utilities/EspressoUtilities.kt
> +  onView(ViewMatchers.withId(id)).perform(clickIcon(isEndIcon = true))
```suggestion
  onView(withId(id)).perform(clickIcon(isEndIcon = true))
```

2022-05-12 11:34 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldSelectMultipleOptionsFromDropDown() {
```suggestion
  fun multipleChoice_selectMultiple_clickOK_shouldSaveMultipleOptions() {
```

2022-05-12 11:34 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldSelectMultipleOptionsFromDropDown() {
similarly others below

2022-05-12 11:34 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldSelectThenCancelSingleOptionDropDown() {
another example:
```suggestion
  fun singleOption_select_clickCancel_shouldSaveNothing() {
```

2022-05-12 11:34 UTC, merged

2022-05-12 13:27 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldSelectMultipleOptionsFromDropDown() {
Addressed in https://github.com/google/android-fhir/pull/1390

2022-05-12 13:28 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shouldSelectThenCancelSingleOptionDropDown() {
Addressed in https://github.com/google/android-fhir/pull/1390