Initial expression support extension
google/android-fhir pull request #1295
Opened 2022-04-14 11:41 UTC by RaaziaTarique

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #https://github.com/google/android-fhir/issues/1033

**Description**
Added functionality to use `FhirPath functions` such as `today()`, `now()` and etc. 
Previously these functions were not supported in SDK because it was only using the extracted resource from the `FhirPath expression` and in case of `FhirPath functions`, the `FhirPath Expressions` doesn't have any resource name in it.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-14 15:01 UTC, jingtang10 requested changes
can you please create an issue in the codebase, so that in the validator API, we will throw an exception if inital value and intial value expression are both present.

reference this url: http://build.fhir.org/ig/HL7/sdc/expressions.html

and this sentence: `Since both initial.value and initialExpression generate values before the user has access to the form, it is not allowed to have both present on a Questionnaire.item.`

2022-04-15 12:26 UTC, RaaziaTarique commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    assertThat((questionnaireResponse.item[0].answer[0].value as DateType).localDate)
I tried to use equalsDeep but it was returning false because of the minor time difference in `currentDate` and date returned from `FHIRPath Function`.
I added another assertions to make sure that `FHIRPath Function` returns `currentDate`
`assertThat(fhirFunctionDateType.isToday).isTrue()`

2022-04-15 12:26 UTC, RaaziaTarique commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +import com.google.android.fhir.datacapture.views.localDate
Reason mentioned here https://github.com/google/android-fhir/pull/1295#discussion_r851242921

2022-04-19 13:26 UTC, RaaziaTarique commented
@jingtang10, I have incorporated all the requested changes. Kindly re-review this PR.

2022-04-20 21:44 UTC, jingtang10 reviewed
What's the relationship between this PR and #1228?

I worked on #1228 and added some refactoring.

2022-04-21 06:56 UTC, RaaziaTarique commented
> What's the relationship between this PR and #1228?
> 
> I worked on #1228 and added some refactoring.

I created this PR as I don't have write access of https://github.com/google/android-fhir repo.

2022-04-21 08:05 UTC, closed without merging

2022-04-21 10:33 UTC, jingtang10 commented
Thanks @RaaziaTarique