Empty Option added to DropDown and test cases added
google/android-fhir pull request #1298
Opened 2022-04-15 12:02 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #940

**Description**
1. Empty Option added for drop down widget 
2. New Test cases added for DropDown
3. Updated existing test cases

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-16 13:22 UTC, jingtang10 commented
can you rebase your pr once #995 is merged? thanks

2022-04-17 11:16 UTC, jingtang10 commented
> can you rebase your pr once #995 is merged? thanks

It's merged. @PallaviGanorkar plz rebase / merge. Also please remove the `@Ignore` that I added for the broken test. Thanks!

2022-04-18 09:06 UTC, PallaviGanorkar commented
> can you rebase your pr once #995 is merged? thanks

done

2022-04-18 09:07 UTC, PallaviGanorkar commented
> > can you rebase your pr once #995 is merged? thanks
> 
> It's merged. @PallaviGanorkar plz rebase / merge. Also please remove the `@Ignore` that I added for the broken test. Thanks!

Done

2022-04-19 14:20 UTC, jingtang10 approved these changes

2022-04-19 14:20 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.auto_complete).text.toString())
import `Truth.assertThat`

```suggestion
   assertThat(viewHolder.itemView.findViewById<TextView>(R.id.auto_complete).text.toString())
```

2022-04-19 14:20 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.auto_complete).text.toString())
ditto

2022-04-19 17:53 UTC, jingtang10 requested changes

2022-04-19 17:53 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +      .isEqualTo("-")
can you please also test that the answer in the questionnaire response item is actually cleared?

2022-04-19 17:53 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +      .isEqualTo("Coding 3")
likewise, can you check coding 3 is actually set as answer?

2022-04-20 10:14 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.auto_complete).text.toString())
Done

2022-04-20 10:14 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +    Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.auto_complete).text.toString())
Done

2022-04-20 11:06 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +      .isEqualTo("Coding 3")
Done

2022-04-20 11:06 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +      .isEqualTo("-")
Done

2022-04-20 11:13 UTC, jingtang10 approved these changes

2022-04-20 22:31 UTC, merged