1272 extend validation api support
google/android-fhir pull request #1301
Opened 2022-04-18 11:41 UTC by aurangzaibumer

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

[Improvement#](https://github.com/google/android-fhir/issues/1272)

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-19 08:35 UTC, aurangzaibumer commented
@dubdabasoduba as per discussion on standup, there is a PR for submit button https://github.com/google/android-fhir/pull/1215 this needs to be merged first in order to work on the submit button so probably we can create a separate ticket for submit button implementation so this can be merged if reviewed.

2022-04-19 09:33 UTC, joiskash requested changes
Thinking about this a little more, I figured that this more than just validation.. This is triggering some logic on page change events within the QuestionnaireFragment. So we could refactor as such. This will allow more complex use cases such as :

1. Not allowing to switch page until a minimum amount of time has passed
2. Not allowing page change if the answers are exactly the same as the previous questionnaire answered . (this can happen in cases were there is a monetary incentive to complete forms)
 
Validation of all the items on the page can be the default implementation provided by the library. Developers can choose to add this in their Strategies too.

By having a context, the main point is that the strategy can be changed during run time.  So a developer can do something like 

`dataConfig.questionnairePageChangeStrategy.setStrategy(newStrategy)`

at any point in the code during run time. 

Create a context class that will be stored in the DataCapture Config
```
class QuestionnairePageChangeEventContext{
  private var pageChangeStrategy : PageChangeStrategy 

  fun setStrategy(pageChangeStrategy : PageChangeStrategy ){
      this.pageChangeStrategy = pageChangeStrategy
  }
  
  //This function will be called in the QuestionnaireViewModel goToNextPage and if returns true  then pageFlow.value will be changed.

  fun pageNextEvent( list: List<QuestionnaireItemViewItem> ):Boolean{
  return pageChangeStrategy.shouldGoToNextPage(list)
  }

//This function will be called in the QuestionnaireViewModel goToPreviousPage and if returns true  then pageFlow.value will be changed.

  fun pagePreviousEvent( list: List<QuestionnaireItemViewItem> ):Boolean{
  return pageChangeStrategy.shouldGoToPreviousPage(list)
  }
}
```
The strategy interface will be like this. 

```
interface PageChangeStrategy {

  fun shouldGoToPreviousPage(list: List<QuestionnaireItemViewItem>): Boolean

  fun shouldGoToNextPage(list: List<QuestionnaireItemViewItem>): Boolean

}
```

The default implementation can be like :

```
class DefaultPageChangeStrategy: PageChangeStrategy{

  override fun shouldGoToPreviousPage(list: List<QuestionnaireItemViewItem>): Boolean{
    return list.any { it.isErrorTriggered }
  }

  override fun shouldGoToNextPage(list: List<QuestionnaireItemViewItem>): Boolean
    return list.any { it.isErrorTriggered }
  }
```

and finally the change in the viewmodel can be as such:

'''
internal class QuestionnaireViewModel(application: Application, state: SavedStateHandle) :{
  private val questionnairePageEventContext by lazy {
    DataCapture.getConfiguration(getApplication()).questionnairePageEventContext ?: this
  }
.
.
.
  internal fun goToPreviousPage() {
    if (questionnairePageEventContext.pagePreviousEvent()){
              pageFlow.value = pageFlow.value!!.previousPage()
     }
  }
  
  internal fun goToNextPage() {
    if (questionnairePageEventContext.pageNextEvent()){
              pageFlow.value = pageFlow.value!!.nextPage()
     }
  }
}

'''

2022-04-21 06:14 UTC, aurangzaibumer commented
> Thinking about this a little more, I figured that this more than just validation.. This is triggering some logic on page change events within the QuestionnaireFragment. So we could refactor as such. This will allow more complex use cases such as :
> 
> 1. Not allowing to switch page until a minimum amount of time has passed
> 2. Not allowing page change if the answers are exactly the same as the previous questionnaire answered . (this can happen in cases were there is a monetary incentive to complete forms)
> 
> Validation of all the items on the page can be the default implementation provided by the library. Developers can choose to add this in their Strategies too.
> 
> By having a context, the main point is that the strategy can be changed during run time. So a developer can do something like
> 
> `dataConfig.questionnairePageEventContext.setStrategy(newStrategy)`
> 
> at any point in the code during run time.
> 
> Create a context class that will be stored in the DataCapture Config
> 
> ```
> class QuestionnairePageChangeEventContext{
>   private var pageChangeStrategy : PageChangeStrategy 
> 
>   fun setStrategy(pageChangeStrategy : PageChangeStrategy ){
>       this.pageChangeStrategy = pageChangeStrategy
>   }
>   
>   //This function will be called in the QuestionnaireViewModel goToNextPage and if returns true  then pageFlow.value will be changed.
> 
>   fun pageNextEvent( list: List<QuestionnaireItemViewItem> ):Boolean{
>   return pageChangeStrategy.shouldGoToNextPage(list)
>   }
> 
>   //This function will be called in the QuestionnaireViewModel goToPreviousPage and if returns true  then pageFlow.value will be changed.
> 
>   fun pagePreviousEvent( list: List<QuestionnaireItemViewItem> ):Boolean{
>   return pageChangeStrategy.shouldGoToPreviousPage(list)
>   }
> }
> ```
> 
> The strategy interface will be like this.
> 
> ```
> interface PageChangeStrategy {
> 
>   fun shouldGoToPreviousPage(list: List<QuestionnaireItemViewItem>): Boolean
> 
>   fun shouldGoToNextPage(list: List<QuestionnaireItemViewItem>): Boolean
> 
> }
> ```
> 
> The default implementation can be like :
> 
> ```
> class DefaultPageChangeStrategy: PageChangeStrategy{
> 
>   override fun shouldGoToPreviousPage(list: List<QuestionnaireItemViewItem>): Boolean{
>     return list.any { it.isErrorTriggered }
>   }
> 
>   override fun shouldGoToNextPage(list: List<QuestionnaireItemViewItem>): Boolean
>     return list.any { it.isErrorTriggered }
>   }
> ```
> 
> and finally the change in the viewmodel can be as such:
> 
> ```
> internal class QuestionnaireViewModel(application: Application, state: SavedStateHandle) :{
>   private val questionnairePageEventContext by lazy {
>     DataCapture.getConfiguration(getApplication()).questionnairePageEventContext // declare and initialize this in the DataConfig. It should never be null
>   }
> .
> .
> .
>   internal fun goToPreviousPage() {
>     if (questionnairePageEventContext.pagePreviousEvent()){
>               pageFlow.value = pageFlow.value!!.previousPage()
>      }
>   }
>   
>   internal fun goToNextPage() {
>     if (questionnairePageEventContext.pageNextEvent()){
>               pageFlow.value = pageFlow.value!!.nextPage()
>      }
>   }
> }
> ```
> 
> Some one from google can comment on this, @jingtang @kevinmost

feedback implemented, please review @joiskash . Thanks

2022-04-21 07:03 UTC, joiskash requested changes
Great work, left a few comments. I request someone from google and Ona to review this before you write the UTs. @jingtang10 @f-odhiambo

2022-04-21 07:03 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  AndroidViewModel(application), QuestionnaireValidation {
QuestionnaireValidation is not needed anymore right? I think it can be removed

2022-04-21 07:03 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun holdCurrentItemState(items: List<QuestionnaireItemViewItem>) {
Can this be made internal?

2022-04-21 07:03 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  override val shouldCheckValidationOnSwitchingPages = true
Remove this?

2022-04-21 08:13 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  override val shouldCheckValidationOnSwitchingPages = true
resolved. thanks

2022-04-21 08:14 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +
done. thanks

2022-04-21 10:08 UTC, jingtang10 commented
@santosh-pingle can you leave some comments please

2022-04-21 10:31 UTC, aurangzaibumer commented
> Great work, left a few comments. I request someone from google and Ona to review this before you write the UTs. @jingtang10 @f-odhiambo

@dubdabasoduba

2022-04-22 05:37 UTC, santosh-pingle commented
> @santosh-pingle can you leave some comments please

sure.

2022-04-22 07:27 UTC, santosh-pingle reviewed
left few minor comments.
Also please check whether we need `demo/src/main/assets/new-patient-registration-paginated.json` file change?

2022-04-22 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +    return !list.any { it.isErrorTriggered }
I see duplication of the code in `inshouldGoToPreviousPage()` and  `shouldGoToNextPage()`.  
Avoid duplication of code : 
Approach 1 : Introduce one more api `isErrorOnCurrentPage(list: List<QuestionnaireItemViewItem>): Boolean` in 'PageChangeStrategy'  and move error validation logic here, and call this api from above two api.

Approach 2 : or just create private api `isErrorOnCurrentPage(list: List<QuestionnaireItemViewItem>): Boolean` here instead of introducing new api in interface.

2022-04-22 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +    return !list.any { it.isErrorTriggered }
please refer earlier comment.

2022-04-22 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnairePageChangeEventContext.kt
> +class QuestionnairePageChangeEventContext {
can we please add api doc?

2022-04-22 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnairePageChangeEventContext.kt
> +  // This function will be called in the QuestionnaireViewModel goToNextPage and if returns true
Can we please use api doc comment format
/* **/

2022-04-22 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnairePageChangeEventContext.kt
> +  // This function will be called in the QuestionnaireViewModel goToPreviousPage and if returns true
ditto

2022-04-22 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  lateinit var currentPageItems: List<QuestionnaireItemViewItem>
can we declare it as private if it is only used here?

2022-04-25 06:48 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +    return !list.any { it.isErrorTriggered }
Used approached 2. Thanks for highlighting. Can you please review.

2022-04-25 06:54 UTC, aurangzaibumer commented
> left few minor comments. Also please check whether we need `demo/src/main/assets/new-patient-registration-paginated.json` file change?

was checking the questionnaire for pagination. I'll revert it back. Thanks.

2022-04-25 07:06 UTC, aurangzaibumer commented
Can you please review it again @santosh-pingle I had resolved the changes asked. Thanks

2022-04-26 06:33 UTC, aurangzaibumer commented
> Can you please review it again @santosh-pingle I had resolved the changes asked. Thanks

cc @dubdabasoduba

2022-05-06 20:15 UTC, jingtang10 commented
can you rename the PR: `Allow/disallow pagination based on validation result (e.g. can't go to next page with validation error)`

2022-05-06 20:21 UTC, jingtang10 requested changes

2022-05-06 20:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> + * implements PageChangeStrategy to give support for switching pages of the Questionnaire
```suggestion
 * Only allows pagination when there are no validation errors on the current page.
```

2022-05-06 20:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +    return !list.any { it.isErrorTriggered }
```suggestion
    return list.none { it.isErrorTriggered }
```

2022-05-06 20:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  internal fun holdCurrentItemState(items: List<QuestionnaireItemViewItem>) {
so the consumer of this view model will use this function to set the items after getting the items from this view model. that's a roundabout way of caching the items.

we could just cache these items when they are being returned in the `getQuestionnaireState` function?

2022-05-10 10:43 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  internal fun holdCurrentItemState(items: List<QuestionnaireItemViewItem>) {
I used the hard coded integer for pagination since I did know my exact page for now to check the current page items but it wasn't updated as per current page (isErrorTriggered were all false in those items that I received from below snippet although I had few errors showing on my page).

```
getQuestionnaireState(
      questionnaireItemList = questionnaire.item,
      questionnaireResponseItemList = questionnaireResponse.item,
      pagination = QuestionnairePagination(1, 0),
    ).items 
```

Can you please correct me if I'm wrong. Thanks

2022-05-10 10:51 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> +  var questionnairePageEventContext: QuestionnairePageChangeEventContext =
`DateCaptureConfig is global. Is this better as a per-questionnaire setting?`

Since We have to give developers the right to update the PageChangeStrategy that is why I added QuestionnairePageChangeEventContext in DataCaptureConfig. If I understood your question correctly.

2022-05-20 14:49 UTC, aurangzaibumer commented
> * the getQuestionnaireState method should probably incorporate questionnaire validation - at the moment it doesn't do any of that, it's probably incorrect. this also address @kevinmost 's todo he left in that function. 

This is done, please review and share feedback


> * it's possible as a result of the previous item, we might not need to directly call validation code in the answer changed callback. all that needs to be done is to get a new questionnaire state. i'm not sure if this is true so please do test it out.

I have tried to remove the validation from onBind and onAnswerChanged but the sequence of the method calling is different as I expected. whenever you give any input, **onAnswerChanged** gets called first, after that **getQuestionnaireState** gets called hence we cannot use **validationResult** from the **questionnaireViewItem** model in the Method **onAnswerChanged**

2022-05-23 13:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> +  var questionnairePageEventContext: QuestionnairePageChangeEventContext =
my question is why is this not a setting for individual questionnaires.

2022-05-30 20:04 UTC, jingtang10 requested changes

2022-05-30 20:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal data class QuestionnairePagination(val currentPageIndex: Int, val lastPageIndex: Int)
we discussed this, and we agreed to add more params here: can go to next page and can go to previous page. no?

@joiskash

2022-05-30 20:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +class DefaultPageChangeStrategy : PageChangeStrategy {
we discussed this and decided to remove page change startegy.

2022-05-30 20:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
the approach we agreed to take is that we add more states in the questionnarie state, so that it includes whether it's ok to go to previous/next page, so the UI will use that information to enable/disable the paging buttons

2022-06-01 09:19 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
Well I see that @shelaghm has described why it might not be such a good idea to enable / disable the buttons .

https://github.com/google/android-fhir/issues/1272

@jingtang10

2022-06-01 10:09 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +class DefaultPageChangeStrategy : PageChangeStrategy {
Sorry, can you please re-explain this because I don't really remember removing this strategy. thanks

2022-06-03 10:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
@aurangzaibumer i replied in the issue - i think i am persuaded that we shouldn't have disabld buttons. what this means is that we need to do validation in `getQuestionnarieState` and include the validation errors in the questionnarie item view items.

2022-06-08 10:51 UTC, joiskash requested changes
Sorry about the delay, left a few comments !

2022-06-08 10:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +class DefaultPageChangeStrategy : PageChangeStrategy {
Can this be made private?

2022-06-08 10:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnairePageChangeEventContext.kt
> +class QuestionnairePageChangeEventContext {
Same as above

2022-06-08 10:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnairePageChangeEventContext.kt
> +interface PageChangeStrategy {
Same as above

2022-06-08 10:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        currentPageItems.forEach { it.modified = true }
Not sure why we are doing this.. seems hacky..can you please remind me?  Why do we mark all items as modified? Is this because of the change that we made to avoid validation messages being displayed as soon as the page is open?

2022-06-08 10:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        _refresh.emit(currentPageItems)
Looks like we have created a new flow for page change.. is this a workaround to https://github.com/google/android-fhir/issues/1427 ?

2022-06-08 10:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun QuestionnairePagination.refresh() : QuestionnairePagination {
Is this being used anywhere?

2022-06-08 11:06 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun QuestionnairePagination.refresh() : QuestionnairePagination {
No, this is currently WIP. let me remove it.

2022-06-08 11:07 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        currentPageItems.forEach { it.modified = true }
This is WIP, actually I was trying to refresh the current page items because I do have the latest validationResult for each items, whenever next button is pressed, I need to show the validation where applicable I was trying to call the items because they were not being modified by the user. Currently this is WIP I'm working things around. thanks

2022-06-15 11:57 UTC, Tarun-Bhardwaj commented
@aurangzaibumer , is there an ETA you could provide so that @joiskash can continue with the code review?
CC: @f-odhiambo

2022-06-16 06:29 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnairePageChangeEventContext.kt
> +interface PageChangeStrategy {
made it internal

2022-06-16 06:31 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        _refresh.emit(currentPageItems)
this will be emited when next page is pressed. I'm trying to refresh the list when next button is pressed (in case if current page is not validated, the errors will be thrown to the required field where applicable that is why I added modified true). Yes its a bit hacky, please suggest any alternative. thanks

2022-06-16 08:18 UTC, aurangzaibumer commented
> @aurangzaibumer , is there an ETA you could provide so that @joiskash can continue with the code review? CC: @f-odhiambo

Discussed the issues/blockers with JING & Kashyap today in the SDK team, Requested a discussion meeting by tomorrow or next week (on Jing's availability).

2022-06-22 06:09 UTC, aurangzaibumer commented
As per discussion with Jing

1. He suggested to separate the Validation Changes from the Pagination changes so I'm removing the validation changes from this PR. This PR will only reflect changes that is related to **_pagination_**
2. The second thing He suggested is to use the ENUM approach instead of Page Change Strategy

2022-06-27 09:14 UTC, Tarun-Bhardwaj commented
@aurangzaibumer @joiskash , is this PR blocked? Any support you need here to move forward?

2022-06-29 07:55 UTC, aurangzaibumer commented
Made changes related to enum approach
For now keeping
- the validationResult code base
- Paging change strategy
will remove once discussion is done with @jingtang10 today

As per discussion below PR needs to be merged first in order to consume the validationResult code base from the QuestionnaireViewModel
https://github.com/google/android-fhir/pull/1468

2022-06-30 12:16 UTC, joiskash requested changes
Good work! Left a few comments

2022-06-30 12:16 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          //show toast that validation is failing
Same comment as above

2022-06-30 12:16 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +enum class EntryMode(val value: Int) {
Can you please add documentation that is borrowed from http://build.fhir.org/ig/HL7/sdc/ValueSet-entryMode.html and http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-entryMode.html

2022-07-04 08:52 UTC, Tarun-Bhardwaj commented
@aurangzaibumer , could you please provide an ETA for addressing review comments from @joiskash ?

2022-07-07 06:45 UTC, aurangzaibumer commented
> @aurangzaibumer , could you please provide an ETA for addressing review comments from @joiskash ?

This current PR is dependent on https://github.com/google/android-fhir/pull/1468 because we will be using the validation logic from 1468 PR and remove it from here. Me and Jing are currently working on #1468 so we can close that ASAP

2022-07-20 13:55 UTC, Tarun-Bhardwaj commented
@aurangzaibumer , considering that #1468 was merged last week, can the pending bits be closed on this PR as well?
CC: @f-odhiambo @jingtang10

2022-07-20 16:27 UTC, aurangzaibumer commented
> Reference

I'm facing an issue, for suppose when first try to open the questionnaire there are no errors shown and when user taps on next page (on restrict mode), the application should be showing errors on required fields (if not entered) in this case we have to re-validate the questionnaire (even if they are not being modified by the user) and also have to reflect the errors (where applicable) on the UI. Now what I did was that I iterate over currentPageItems so each element could  have latest validationResult (because there might be a case where fields are not being modified by the user yet) and then I have to update the UI in-order to reflect the errors

`//Revalidating it because there's a chance if they the fields are not being modified yet by the User
       currentPageItems.forEach {
         it.validationResult?.isValid = QuestionnaireResponseItemValidator.validate(
           it.questionnaireItem,
           it.answers,
           this@QuestionnaireViewModel.getApplication()
         ).isValid

       }`
       
can you please share your opinion if that's the right strategy. @jingtang10 

cc @maimoonak @joiskash

2022-07-20 23:35 UTC, jingtang10 commented
> > @aurangzaibumer , considering that #1468 was merged last week, can the pending bits be closed on this PR as well? CC: @f-odhiambo @jingtang10
> 
> I'm facing an issue, for suppose when we open the questionnaire there are no errors shown and when user taps on next page (on restrict mode), the application should be showing errors on required fields (if not entered) in this case we have to re-validate the questionnaire (even if they are not being modified by the user) and also have to reflect the errors (where applicable) on the UI. Now what I did was that I iterate over **currentPageItems** so each element could have latest validationResult (because there might be a case where fields are not being modified by the user yet) and then I have to update the UI in-order to reflect the errors
> 
> ```
>  currentPageItems.forEach {
>          it.validationResult?.isValid = QuestionnaireResponseItemValidator.validate(
>            it.questionnaireItem,
>            it.answers,
>            this@QuestionnaireViewModel.getApplication()
>          ).isValid
> 
>        }
> ```
> 
> can you please share your opinion if that's the right strategy. @jingtang10
> 
> cc @maimoonak @joiskash

can you add all the items to the modified set when the user tries to go to the next page?

2022-07-21 15:50 UTC, aurangzaibumer commented
> > > @aurangzaibumer , considering that #1468 was merged last week, can the pending bits be closed on this PR as well? CC: @f-odhiambo @jingtang10
> > 
> > 
> > I'm facing an issue, for suppose when we open the questionnaire there are no errors shown and when user taps on next page (on restrict mode), the application should be showing errors on required fields (if not entered) in this case we have to re-validate the questionnaire (even if they are not being modified by the user) and also have to reflect the errors (where applicable) on the UI. Now what I did was that I iterate over **currentPageItems** so each element could have latest validationResult (because there might be a case where fields are not being modified by the user yet) and then I have to update the UI in-order to reflect the errors
> > ```
> >  currentPageItems.forEach {
> >          it.validationResult?.isValid = QuestionnaireResponseItemValidator.validate(
> >            it.questionnaireItem,
> >            it.answers,
> >            this@QuestionnaireViewModel.getApplication()
> >          ).isValid
> > 
> >        }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can you please share your opinion if that's the right strategy. @jingtang10
> > cc @maimoonak @joiskash
> 
> can you add all the items to the modified set when the user tries to go to the next page?

  I have used a boolean that will be set as true whenever next page is pressed as 

`isPaginationButtonPressed = true
        modificationCount.update { it + 1 }`
        
 and updated a check on questionnareState as 
  
  `modifiedQuestionnaireResponseItemSet.contains(questionnaireResponseItem) || isPaginationButtonPressed`
  
   and it will be reset to false before pageFlow value changes as 
   
   `if (currentPageItems.none { !it.validationResult!!.isValid }) {
          isPaginationButtonPressed = false
          pageFlow.value = pageFlow.value!!.nextPage()
        }`
        
        
        

https://user-images.githubusercontent.com/35099184/180257590-020eeeb3-ec79-4333-9c56-9ce2a968aef0.mp4



can you please review if it's a better strategy @jingtang10 

cc @maimoonak @f-odhiambo

2022-07-21 15:51 UTC, jingtang10 commented
Thanks umer - this is much better

2022-07-21 15:55 UTC, aurangzaibumer commented
> Thanks umer - this is much better

thanks @jingtang10 , I'll be update the documentation and the test cases based on this implementation.

cc @f-odhiambo @maimoonak

2022-07-21 15:59 UTC, jingtang10 requested changes

2022-07-21 15:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +internal class DefaultPageChangeStrategy : PageChangeStrategy {
we have discussed this - can you remove this interface?

2022-07-21 15:59 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    >Please fill the required fields first</string>
delete this

2022-07-21 15:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DefaultPageChangeStrategy.kt
> +internal class DefaultPageChangeStrategy : PageChangeStrategy {
we have said that we'll be using entry mode http://build.fhir.org/ig/HL7/sdc/ValueSet-entryMode.html which is generalised to the page level

2022-07-21 15:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_QUESTIONNAIRE_PAGING_STRATEGY = "questionnaire-paging-strategy"
remove this

2022-07-22 15:32 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      EntryMode.PRIOR_EDIT, EntryMode.RANDOM -> {
according to doc
prior-edit`: display new top level page or question only when previous page or question answered. can go back.

so that is why I gave **prior-edit** and **random** the same functionality when tapping on **previous page**

2022-07-22 15:57 UTC, jingtang10 commented
please revert the license header changes - makes it very difficult to review the code.

thanks!

2022-07-22 15:58 UTC, jingtang10 requested changes

2022-07-22 15:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
you need to create a new class called `MoreQuestionnaires.kt` and put the logic to load entry mode there. also add tests.

2022-07-22 16:15 UTC, jingtang10 requested changes

2022-07-22 16:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      EntryMode.RANDOM, EntryMode.SEQUENTIAL -> {
i think sequential should be together with prior-edit?

2022-07-22 16:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
remove random blank line

2022-07-22 16:27 UTC, jingtang10 requested changes

2022-07-22 16:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        ?: EntryMode.RANDOM.value.uppercase(Locale.getDefault())
by the way i think this field should be nullable. don't assume here that random is the default.

2022-07-22 16:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  SEQUENTIAL("sequential")
move this to `MoreQuestionnaires.kt`

2022-07-22 16:27 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertTrue(viewModel.questionnairePageEventContext.pageNextEvent(state.items))
do these tests even pass - there's no page event context any more?

2022-07-22 16:31 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertTrue(viewModel.questionnairePageEventContext.pageNextEvent(state.items))
I haven't updated the unit test cases yet. I did only develop new implementation so that you can review and if you agree to that then i will be updating the unit test cases.

2022-07-22 16:33 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        ?: EntryMode.RANDOM.value.uppercase(Locale.getDefault())
Okay but for suppose if there is no value (null) for entryMode and user taps on the pagination button (next or previous), in that case what should happen? thanks

2022-07-23 10:42 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertTrue(viewModel.questionnairePageEventContext.pageNextEvent(state.items))
Sure that's fine. I think you can probably start writing tests.

2022-07-23 10:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        ?: EntryMode.RANDOM.value.uppercase(Locale.getDefault())
I think probably prior edit? But keep that logic in the view model instead of here.

2022-07-23 10:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        ?: EntryMode.RANDOM.value.uppercase(Locale.getDefault())
I know this is the view model file. But you need to move this to a separate file just as utility. And the view model will check things and decide the default behaviour

2022-07-26 11:16 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaires.kt
> +      "prior-edit" -> EntryMode.PRIOR_EDIT
can we add these values to enum as code? just as we do have for other enums for FHIR?

2022-07-26 11:16 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        // Previous questions and submitted answers cannot be viewed or edited.
is it possible to show a toast here? OR use else and log it as warning.

2022-07-28 10:25 UTC, aurangzaibumer commented
All comments are resolved. Can you please review and share you feedback @jingtang10 
Thanks

2022-07-28 13:55 UTC, jingtang10 requested changes

2022-07-28 13:55 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun shouldAllowUserToSwitchBetweenPages_entryMode_prior_edit() = runBlocking {
can you use the new kotlin back quote format: https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

i think you should probably also have separate test cases in each entry mode for going prev/next.

2022-07-29 11:37 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun shouldAllowUserToSwitchBetweenPages_entryMode_prior_edit() = runBlocking {
I have added three unit test cases for each entry mode

2022-07-29 11:37 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaires.kt
> +val Questionnaire.entryMode: EntryMode
I have added three unit test case for each entry mode

2022-08-04 09:20 UTC, joiskash requested changes
Wow this PR looks so clean! Great work, just a small comment, we should probably add a test that checks the default entry mode if there is no extension for entry mode in the questionnaire.

2022-08-04 09:20 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `should Allow user to move forward And Back Using Prior Entry Mode`() = runBlocking {
The case in this looks statement looks weird.

2022-08-04 11:32 UTC, aurangzaibumer commented
> Wow this PR looks so clean! Great work, just a small comment, we should probably add a test that checks the default entry mode if there is no extension for entry mode in the questionnaire.

added a case when no entryMode is defined in the questionnaire. Thanks

2022-08-05 15:22 UTC, jingtang10 approved these changes
thanksk @aurangzaibumer

2022-08-05 15:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (currentPageItems.none { !it.validationResult!!.isValid }) {
```suggestion
        if (currentPageItems.all { it.validationResult!!.isValid }) {
```

2022-08-05 15:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var isPaginationButtonPressed = false
add a comment

2022-08-05 15:22 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `should allow user to move forward and back using prior entry-mode`() = runBlocking {
separate all forward and backward cases?

2022-08-05 15:22 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertThat(state.items).hasSize(2)
don't have to do theses

2022-08-05 15:22 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `should allow user to move forward and back using prior entry-mode`() = runBlocking {
missing a test cases which is you can't go forward without answering the questions in prior edit mode.

2022-08-12 15:16 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `should allow user to move forward and back using prior entry-mode`() = runBlocking {
added the unit tests for prior-mode and sequential

2022-08-12 16:41 UTC, jingtang10 approved these changes

2022-08-12 16:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (currentPageItems.all { it.validationResult!!.isValid }) {
```suggestion
        if (currentPageItems.all { it.validationResult.isValid }) {
```

2022-08-12 16:45 UTC, jingtang10 approved these changes

2022-08-12 16:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    // holding updated items state
remove this comment.

2022-08-12 16:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (currentPageItems.all { it.validationResult!!.isValid }) {
this needs to be changed with the validation result code change

2022-08-15 05:47 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (currentPageItems.all { it.validationResult!!.isValid }) {
thanks for the suggestion. resolved

2022-08-15 06:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (currentPageItems.all { it.validationResult!!.isValid }) {
actually i've realised we have an issue here - if the user hasn't touched any question, does that not make the this check pass? which means that the user can always go to the next page without editing anything in the current page?

can you test this? thanks

i think this logic probably should be changed to checking if everything is valid.

2022-08-15 13:13 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (currentPageItems.all { it.validationResult!!.isValid }) {
yes you are right although it was working fine having both valid and not validated check because when we click on paginated buttons, it validates the items and receive validation either (invalid or valid). I have updated the logic though.

2022-08-15 15:24 UTC, aurangzaibumer commented
@jingtang10 can you please review on your availability. thanks

2022-08-16 10:04 UTC, jingtang10 approved these changes

2022-08-16 10:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        modificationCount.update { it + 1 }
can you add some comments to explain the necessity of having these lines here?

2022-08-16 10:06 UTC, jingtang10 approved these changes

2022-08-16 10:06 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        modificationCount.update { it + 1 }
```suggestion
        // Force update validation results for all questions on the current page
        isPaginationButtonPressed = true
        modificationCount.update { it + 1 }
```

2022-08-16 10:40 UTC, jingtang10 approved these changes

2022-08-16 10:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        modificationCount.update { it + 1 }
do you think this makes sense? i think we can save some additional validation if the user has already pressed the button.

```suggestion
        if (!isPaginationButtonPressed) {
          // Force update validation results for all questions on the current page
          isPaginationButtonPressed = true
          modificationCount.update { it + 1 }
        }
```

2022-08-16 10:43 UTC, jingtang10 approved these changes

2022-08-16 10:43 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt
> +  @Test
as @joiskash suggested, add a test case here for null case.

2022-08-16 12:51 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        modificationCount.update { it + 1 }
If i could map a case 
1. User opened the questionnaire and taps on the next button without touching any items
2. isPaginated is FALSE, it will trigger the validation for the current page items 
3. now errors are shown the required fields, now user tried to tap again on the next button 
4. since isPaginated is already TRUE, this will save the additional validation in this _case_. 
You are right @jingtang10 . This makes sense to me.

cc @maimoonak

2022-08-16 13:10 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt
> +  @Test
case added in MoreQuestionnaireTest class. thanks
also there was a test added `should allow user to move forward when no entry-mode is defined` in QuestionnaireViewModelTest as well.

2022-08-21 07:38 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt
> +  @Test
that's great - thanks!

2022-08-21 08:26 UTC, jingtang10 approved these changes

2022-08-21 08:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          // Force update validation results for all questions on the current page
```suggestion
          // Force update validation results for all questions on the current page. This is needed when the user has not answered any questions so no validation has been done.
```

2022-08-21 08:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          //show toast that validation is failing
Let's keep this in a follow-up pr.

2022-08-21 09:38 UTC, merged

2022-09-06 07:40 UTC, santosh-pingle commented
@aurangzaibumer can you please add some questionnaire examples?

2022-09-06 07:49 UTC, aurangzaibumer commented
> @aurangzaibumer can you please add some questionnaire examples?

```
"extension": [ 
    {
      "url" : "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-entryMode",
      "valueCode" : "prior-edit"
    } 
 ]
```
for more entry-mode codes : http://build.fhir.org/ig/HL7/sdc/ValueSet-entryMode.html