1001 fix form validation
google/android-fhir pull request #1309
Opened 2022-04-19 11:44 UTC by aurangzaibumer

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-21 10:08 UTC, jingtang10 commented
@santosh-pingle can you please leave some comments

2022-04-21 10:52 UTC, santosh-pingle commented
> @santosh-pingle can you please leave some comments
sure.

2022-04-21 15:20 UTC, santosh-pingle reviewed
do we need `demo/src/main/assets/new-patient-registration-paginated.json` change ?

2022-04-21 15:26 UTC, santosh-pingle commented
Also, can you please update the description for updated solution?

2022-04-22 07:21 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  var isDirty: Boolean = false,
I've added in the java docs. Can you please confirm if there is any other doc I have to update? thanks

2022-04-22 07:21 UTC, aurangzaibumer commented
> do we need `demo/src/main/assets/new-patient-registration-paginated.json` change ?

restored changes with the master

2022-04-22 07:31 UTC, aurangzaibumer commented
> Also, can you please update the description for updated solution?

done.

2022-04-22 07:36 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  var isDirty: Boolean = false,
is it okay to update api doc for isDirty variable in class doc something like 
line +27 @param questionnaireItem

e.g @param isDirty (its usage)

2022-04-22 07:41 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  var isDirty: Boolean = false,
I can see now, thanks!

2022-04-22 07:44 UTC, santosh-pingle commented
looks good to me, thanks!
Please code owner review once, thanks!

2022-04-26 06:32 UTC, aurangzaibumer commented
> looks good to me, thanks! Please code owner review once, thanks!

cc @f-odhiambo

2022-05-02 14:11 UTC, jingtang10 requested changes

2022-05-06 19:33 UTC, jingtang10 commented
is this ready for another review? please reply to individual comments. thanks!

2022-05-09 06:56 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    }
we have to keep this because (removing the text change listener) because this helps us not getting call the text watcher automatically after setting the text view that triggers the validation.

2022-05-09 06:57 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    }
Removing all of this chunk will let the validation get called after setting the text

2022-05-09 14:47 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/QuestionnaireItemPhoneNumberViewHolderFactoryInstrumentedTest.kt
> +          )
I have removed it, it is working.

2022-05-10 06:21 UTC, aurangzaibumer commented
> is this ready for another review? please reply to individual comments. thanks!

PR made ready for review. thanks

2022-05-16 08:22 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    }
Resolved.

2022-05-16 13:51 UTC, Tarun-Bhardwaj commented
@jingtang10 , would you be able to review this PR?

2022-05-17 17:15 UTC, jingtang10 requested changes

2022-05-17 17:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    ) {
```suggestion
    if (delegate.questionnaireItemViewItem.modified) {
```

2022-05-17 17:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    ) {
what if someone is deleting a field? this logic is wrong here.

2022-05-19 06:56 UTC, aurangzaibumer commented on demo/src/main/assets/new-patient-registration-paginated.json
> +        },
Yes, I was checking this to test with the other type of widgets. removed the changes. thanks

2022-05-19 06:56 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    // Only validate questionnaire items with answer(s). This is so that we do not show all the
thanks updated.

2022-05-19 06:57 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextStringViewHolderDelegate.kt
> +    return QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent()
Yes, I have checked the behavior without this snippet. working ok for me.

2022-05-19 06:59 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    ) {
the purpose of adding this condition 
1. modified - to check if user has made any interaction with the field 
2. when we are opening a questionnaire with answers, in that case validation should be triggered from here, it was originally calling before.
That is why both checks were added, please correct me If I'm wrong. thanks

2022-05-19 07:02 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    }
Moreover when we removed this snippet 
```
val answer = questionnaireItemViewItem.singleAnswerOrNull
    if (answer == null) {
      // Clear the text input and any error message if the question has not been answered.
      textInputEditText.setText("")
      displayValidationResult(ValidationResult(true, listOf()))
    } else {
      textInputEditText.setText(getText(answer))
      onAnswerChanged(textInputEditText.context)
    }
```
checking it with a longer questionnaire (has a lot of questions) , the validations are getting duplicate like we had this problem at earlier. I couldn't check this at that time of removing, my bad. Regrets. We can discuss this point on today's call. thanks

2022-05-20 15:45 UTC, jingtang10 requested changes
looks pretty good - almost ready to merge

last thing - just add some test cases where you have changed the existing test cases by adding modified = true. just make sure that if modify is false, we're not showing validation errors. that's the whole point of this PR now.

2022-05-20 15:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    // Instead, the validation errors are shown when the user goes through each question.
Say something like this:

Only validate questionnaire items if the user has made any change, or if there is an existing answer. In other words, do not validate questionnaire items before the user provides an answer to avoid UI cluttering upon opening questionnaire.

2022-05-20 15:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +    ) {
discussed offline - thanks for the explanation umer. yeah this is correct and my comment was wrong. but you do need to update the comment to match the logic, which i commented on earlier. thanks

2022-05-23 02:57 UTC, aurangzaibumer commented
> looks pretty good - almost ready to merge
> 
> last thing - just add some test cases where you have changed the existing test cases by adding modified = true. just make sure that if modify is false, we're not showing validation errors. that's the whole point of this PR now.

added the unit test cases for modify = false. Please review. Thanks

2022-05-23 07:15 UTC, aurangzaibumer commented
> > looks pretty good - almost ready to merge
> > last thing - just add some test cases where you have changed the existing test cases by adding modified = true. just make sure that if modify is false, we're not showing validation errors. that's the whole point of this PR now.
> 
> added the unit test cases for modify = false. Please review. Thanks

PR gateways passed. 
cc @jingtang10

2022-05-23 13:27 UTC, jingtang10 approved these changes
just a few small nits

thanks for this!

2022-05-23 14:40 UTC, aurangzaibumer commented
A 503 status code has been received, will attempt to retry the upload
##### Begin Diagnostic HTTP information #####
Status Code: 503
Status Message: Service Unavailable

2022-05-23 17:07 UTC, merged