Feature to review question/answers in list view in Questionnaire Fragment
google/android-fhir pull request #1310
Opened 2022-04-19 12:53 UTC by nsabale7

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #227 

**Description**
Feature to review question/answers in list view from questionnaire and questionnaireResponse

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
 Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-19 13:40 UTC, joiskash approved these changes
Looks good to me, just a few comments. We will need to improve the comments. But the implementation can get reviewed in the mean time.

@dubdabasoduba please get this reviewed by your team .

2022-04-19 13:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> + * Question which are not answered are shown as Not Answered.
This has to be removed, because we are now using the questionnaireStateFlow which does not create QuestionnaireItemViewItems for unanswered questions

2022-04-19 13:40 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    reviewFeature: Boolean = false
Please change reviewFeature to reviewMode to keep it consist

2022-04-19 13:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    viewLifecycleOwner.lifecycleScope.launchWhenCreated {
Can we have all the collect statements in one viewLifecycleOwner.lifecycleScope.launchWhenCreated { ?

2022-04-24 11:14 UTC, jingtang10 requested changes
This is fantastic work. Thanks both @nsabale7 and @joiskash!

One thought - shouldn't review mode simply add a new review page to the questionnaire, instead of changing the behavior of the entire questionnaire fragment?

So what I was imagining:

- if QuestionnaireFragment is launched with the flag turned off, everything is the same as before, i.e., showing either single page questionnaire, or paginated questionnaire
- if QuestionnaireFragment is launched with the flag turned on, there will be a new reivew page after the single-page or multi-page questionnaire, which allows the user to either submit the questionnaire or go back to the questionnaire to edit (intially could just go back to the first page in our v1)

is this better/worse than the current design? i feel it's probably closer to what developers want? I don't really want developers to have to create another questionnaire fragment when using review mode.

2022-04-26 12:28 UTC, joiskash commented
> This is fantastic work. Thanks both @nsabale7 and @joiskash!
> 
> One thought - shouldn't review mode simply add a new review page to the questionnaire, instead of changing the behavior of the entire questionnaire fragment?
> 
> So what I was imagining:
> 
>     * if QuestionnaireFragment is launched with the flag turned off, everything is the same as before, i.e., showing either single page questionnaire, or paginated questionnaire
> 
>     * if QuestionnaireFragment is launched with the flag turned on, there will be a new reivew page after the single-page or multi-page questionnaire, which allows the user to either submit the questionnaire or go back to the questionnaire to edit (intially could just go back to the first page in our v1)
> 
> 
> is this better/worse than the current design? i feel it's probably closer to what developers want? I don't really want developers to have to create another questionnaire fragment when using review mode.

Thanks @jingtang10 !

The current implementation is as per our discussion with @dubdabasoduba : 

1. Review mode will always be enabled. If the flag is passed as false when the questionnaire fragment is launched, then on the last page, the next page button will turn into a review button. On pressing the review button all the view holders in the recyclerview are replaced by a simple question-answer view holder and enables the edit button. If the edit button is pressed, the view navigates back to the last page.
2. If the flag is true, then the questionnaire fragment will launch directly into the review mode with the edit button enabled. The edit button behavior is the same as described above.

Based on the discussion with @dubdabasoduba and our team, it seems like review mode at the end of the questionnaire is a requirement i.e. accurate data capture cannot be done without review.
Developers do not have to create a new fragment to get into review mode. The current fragment can switch between the two modes based on button press. 

1. Review button on the last page 
2. Edit button to get back to data capture mode. 

@nsabale7 please add a video of this behavior so that it is clear.

2022-04-27 07:15 UTC, nsabale7 commented
https://user-images.githubusercontent.com/82660329/165462203-4f3caf51-95c4-4a9c-a19d-7a83f646a91b.mp4

This video shows directly the review feature and then go into edit feature.

@jingtang10

2022-04-27 23:29 UTC, dubdabasoduba requested changes

2022-04-27 23:29 UTC, dubdabasoduba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            pagination = null,
@joiskash how does this affect questionnaires with different steps/pages. Does convert it to a single page Questionnaire?

2022-04-27 23:29 UTC, dubdabasoduba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +                false -> "No"
I no it's rare for this boolean to change naming be could we have the literal strings in a Constants file

2022-04-27 23:31 UTC, dubdabasoduba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            pagination = null,
Never mind I think I understood how this will work.

2022-05-06 19:32 UTC, jingtang10 requested changes
reviewed together with @joiskash.

Thanks @nsabale7! please see comments below.

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +        android:id="@+id/buttons_layout"
```suggestion
        android:id="@+id/bottom_buttons"
```

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      } else false
```suggestion
    initialReviewMode = state[QuestionnaireFragment.QUESTIONNAIRE_REVIEW_MODE] ?: false
```

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      } else false
discussed with @joiskash, we should have 2 params here:

1. `QUESTIONNAIRE_HAS_REVIEW_PAGE`: true if we have a review page at the end of the questionnaire
2. `QUESTIONNAIRE_ENTRY_BY_REVIEW_PAGE`: true if the review page is the entry point of the questionnaire

and rename the variable on line 104

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  internal val initialReviewMode: Boolean
can this be private?

```suggestion
  private val initialReviewMode: Boolean
```

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val reviewMode = MutableStateFlow(initialReviewMode)
end with flow to contrast with `pageFlow`

```suggestion
  private val reviewFlow = MutableStateFlow(initialReviewMode)
```

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (reviewMode) {
```suggestion
    // Every questionnaire item is rendered as.a simple display item in review mode
    if (reviewMode) {
```

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +  var reviewMode = false
Alternatively, you could have 2 adapters.

1. the old adapter as is
2. a new review mode adapter that maps every single questionnaire item to the same display item view holder

And then when you listen to your reiview mode state flow, you can switch between these two adapters. 

Have you considered doing this instead of introducing a variable in this class. What are the pros/cons of these 2 different approaches?

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +                false -> "No"
i think we should use context, the reaon being that we/developers might need to provide translation.

but i guess i can be persuaded if we do this in an (immediate) follow-up.

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    const val NOT_ANSWERED = "Not Answered"
this needs to be a string resource

2022-05-06 19:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  open fun lastPageBehaviour(): Boolean {
is there a way to make this a param to the questionnaire fragment? open functions are easy to abuse.

2022-06-22 15:28 UTC, joiskash reviewed
@jingtang10 we have two things that we need your help with

1. Passing the context to QuestionnaireItemViewItem to fetch string resources for the NOT_ANSWERED string
2. Fetching the current questionnaire state to pass to the QuestionnaireReviewPageItemAdapater

2022-06-22 15:28 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    viewLifecycleOwner.lifecycleScope.launchWhenCreated {
resolved

2022-06-22 15:28 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          reviewPageItemAdapter.submitList(viewModel.questionnaireStateFlow.first().items)
Please put brackets around this

2022-06-22 15:28 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          reviewPageItemAdapter.submitList(viewModel.questionnaireStateFlow.first().items)
Looks like we are fetching the first set of items emitted. I know there is a PR where we are adding the currentState as a variable.. We can take the same approach. https://github.com/google/android-fhir/pull/1301

2022-06-22 15:28 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    const val NOT_ANSWERED = "Not Answered"
Adding context to questionnaireItemViewItem seems to be a big change. Should we go ahead and do that?

2022-06-22 15:33 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  internal val initialReviewMode: Boolean
Done

2022-06-22 15:34 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +  var reviewMode = false
Done.

2022-06-22 15:35 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    const val NOT_ANSWERED = "Not Answered"
Need help on this for context.

2022-07-01 17:29 UTC, jingtang10 commented
> @jingtang10 we have two things that we need your help with
> 
> 1. Passing the context to QuestionnaireItemViewItem to fetch string resources for the NOT_ANSWERED string

yeah as we discussed this is fine.

> 2. Fetching the current questionnaire state to pass to the QuestionnaireReviewPageItemAdapater

i don't really undrestand this. why does the adapter need to fetch the state? it shouldn't do that. the items should include all the info for the ui...

2022-07-01 17:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
revert this

2022-07-06 11:52 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
Done

2022-07-22 18:10 UTC, jingtang10 commented
@nsabale7 can you sync please - we made some changes in the view model. thanks!

2022-07-25 11:50 UTC, nsabale7 commented
> @nsabale7 can you sync please - we made some changes in the view model. thanks!

Sure @jingtang10, thanks.

2022-07-27 17:04 UTC, jingtang10 requested changes

2022-08-03 10:16 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    /** A boolean flag to open review page as the entry point of the questionnaire. */
Done

2022-08-03 10:16 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val QUESTIONNAIRE_HAS_REVIEW_PAGE = "questionnaire-has-review-page"
Done

2022-08-03 10:16 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    /** A boolean flag to have a review page at the end of the questionnaire. */
Done

2022-08-03 10:16 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val QUESTIONNAIRE_ENTRY_BY_REVIEW_PAGE = "questionnaire-entry-review-page"
Done

2022-08-03 10:17 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +      }
Moved this switch logic to MoreQuestionnaireResponseItemAnswerComponent.kt

2022-08-03 10:18 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> + * Copyright 2022 Google LLC
Done

2022-08-03 10:20 UTC, nsabale7 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +        android:id="@+id/buttons_layout"
I had reverted it one of the conflicts. Done now.

2022-08-08 13:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    const val NOT_ANSWERED = "Not Answered"
```
internal fun answerString(context: Context): String
```

2022-08-11 03:25 UTC, joiskash approved these changes
Looks good to me, left a comment about displaying validation results in review mode. I have not really thought about this. Also it could be taken up in a following PR.

2022-08-11 03:25 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +      override fun displayValidationResult(validationResult: ValidationResult) {}
Can we put some comment as to why this and the function below are empty? Also it maybe important to display validations during review.. @jingtang10 what do you think?

2022-08-11 06:12 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireReviewPageItemAdapter.kt
> +internal class QuestionnaireReviewPageItemAdapter :
Done

2022-08-11 06:48 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          recyclerView.swapAdapter(reviewPageItemAdapter, false)
I found a crash when using setAdapter() to switch adapters for single-page questionnaire.
`java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.recyclerview.widget.RecyclerView{76ea2cb VFED.V... ......ID 0,0-1080,1830 #7f08019f app:id/recycler_view aid=1073741827}, adapter:com.google.android.fhir.datacapture.QuestionnaireItemAdapter@b76a86d, layout:androidx.recyclerview.widget.LinearLayoutManager@a251ca2, context:androidx.appcompat.view.ContextThemeWrapper@a8eea82`

I replaced it with swapAdapter() and it works fine. Please add your views on this.
@jingtang10 @joiskash

2022-08-11 06:49 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireReviewPageItemAdapter.kt
> +internal class QuestionnaireReviewPageItemAdapter :
Done

2022-08-15 06:41 UTC, jingtang10 requested changes

2022-08-15 06:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          recyclerView.swapAdapter(reviewPageItemAdapter, false)
I can see @yigit created the `swapAdapter` API in 2014.

@yigit: why would this happen in the first place? is it right to use swap here then?

2022-08-15 18:51 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          recyclerView.swapAdapter(reviewPageItemAdapter, false)
this usually happens when the backing data is changed w/o notifying RV (or changing it from another thread)
do we not use immutable lists in these adapters?

2022-08-17 15:19 UTC, jingtang10 requested changes

2022-08-18 07:51 UTC, jingtang10 requested changes

2022-08-18 07:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .stateIn(viewModelScope, SharingStarted.Lazily, initialValue = showSubmitButtonFlag)
as discussed yesterday - i don't feel these 2 should be state flows. they will never need to be emitted without the questionnaire state change. so it's more appropriate if they are simply additional fields in the `QuestionnairePagination` object. @joiskash what's your view?

2022-08-18 12:26 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .stateIn(viewModelScope, SharingStarted.Lazily, initialValue = showSubmitButtonFlag)
There is conflict with this:
If pagination == null , in the case of a single page questionnaire, then we cannot use these new additional fields to show review / submit .
So our options are :
1. Make QuestionnairePagination not nullable and add 3 Booleans -> showSubmit, showReview, pagniationEnabled
2. Add showSubmit and showReview to the QuestionnaireState.

Please let us know what is better. @jingtang10

2022-08-18 15:50 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          recyclerView.swapAdapter(reviewPageItemAdapter, false)
Sorry for the late reply, we use immutable lists for both adapters.

2022-08-19 05:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .stateIn(viewModelScope, SharingStarted.Lazily, initialValue = showSubmitButtonFlag)
can we make `QuestionnairePagination` non-nullable so that it has to be provided to the UI?

and then you can add a boolean field called isPaginated or something...

and then you can have your review mode stuff also in the questionnaire pagination object?

@kevinmost @nsabale7 @joiskash

2022-08-19 05:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .stateIn(viewModelScope, SharingStarted.Lazily, initialValue = showSubmitButtonFlag)
again, it's about making things more explicit. i think making null have meaning (in this case the questionnaire is not paginated) is probably not the best practice, upon reflection.

2022-08-19 05:54 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .stateIn(viewModelScope, SharingStarted.Lazily, initialValue = showSubmitButtonFlag)
> can we make `QuestionnairePagination` non-nullable so that it has to be provided to the UI?
> 
> and then you can add a boolean field called isPaginated or something...
> 
> and then you can have your review mode stuff also in the questionnaire pagination object?
> 
> @kevinmost @nsabale7 @joiskash 

I completely agree. That was my first reaction too. @nsabale7 let's do this instead. I think we had discussed using pages as the null check, but initial idea is more readable and explicit.

2022-08-22 12:03 UTC, nsabale7 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireResponseItemAnswerComponentTest.kt
> +  fun displayString_attachmentType_shouldReturnUrlValue() {
Done

2022-08-22 12:03 UTC, nsabale7 commented on datacapture/src/main/res/values/strings.xml
> +    >"Please answer all required fields!"</string>
Removed non-required strings.

2022-08-22 12:03 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireReviewPageItemAdapter.kt
> +internal class QuestionnaireReviewPageItemAdapter :
Done

2022-08-23 11:05 UTC, nsabale7 commented
https://user-images.githubusercontent.com/82660329/186142611-728a3c71-3215-456a-be43-b1f4f0a72419.mp4

2022-08-23 22:10 UTC, shelaghm commented
Looks good @nsabale7 

In your recording I noticed that the "subtitle/instructional" text field is showing up on the review screen. Example: "select one" or "check all that apply". Is this intentional?

2022-08-24 06:51 UTC, jingtang10 approved these changes

2022-08-24 07:22 UTC, nsabale7 commented
> Looks good @nsabale7
> 
> In your recording I noticed that the "subtitle/instructional" text field is showing up on the review screen. Example: "select one" or "check all that apply". Is this intentional?

2022-08-24 07:25 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +                false -> "No"
Resolved this by passing context to the answerString function

2022-08-24 07:26 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    const val NOT_ANSWERED = "Not Answered"
Done. Thanks for this.

2022-08-24 07:28 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          reviewPageItemAdapter.submitList(viewModel.questionnaireStateFlow.first().items)
Refactored this by moving to single questionnaire state flow

2022-08-24 07:37 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .stateIn(viewModelScope, SharingStarted.Lazily, initialValue = showSubmitButtonFlag)
Moved all the logic to QuestionnairePagination state.

2022-08-24 08:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +      override fun displayValidationResult(validationResult: ValidationResult) {}
let's keep talking about this in a separate ticket - yes i agree validation is important.

2022-08-24 08:28 UTC, merged