Workflow Library: Implementing Library.evaluate and first androidTest suite
google/android-fhir pull request #1326
Opened 2022-04-23 16:17 UTC by vitorpamplona

**Description**

Implemented FhirOperator.evaluateLibrary function
Connected the LibraryProcessor to the FhirEngine's local DB, matching evaluateMeasure
Generalized FhirEngineRetrieveProvider to work with any FHIR Model
Added the first androidTests with a simple COVID Immunization check

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-23 20:36 UTC, ktarasenko requested changes
Amazing, thanks for adding this!

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +class FhirOperatorLibraryEvaluateTest {
Please move this test to /test root, since it's a robolectric test, not the one that runs on the instrumented device

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +    println("Composition " + fhirEngine.get(ResourceType.Composition, ids.first()))
could it be a part of the test, instead of logs?

2022-04-23 20:36 UTC, ktarasenko commented on workflow/testdata/COVIDCheck.cql
> +library DDCCPass version '0.0.1'
Is cql file is here for the reference?  Some other files aren't seems to be used too

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +    assertEquals(true, results.getParameterBool("CompletedImmunization"))
please use [Truth library](https://truth.dev/) for assertions

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          // TODO: I am not sure why the default search is only for active entities
This assumption (filter on active patients) didn't work. I removed it in the other PR that isn't merged yet.

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +    return javaClass.classLoader?.getResourceAsStream(assetName)
could be just `javaClass..getResourceAsStream(assetName)`

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          contextPath != "id" &&
contextPath != "id" is redundant

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +    } catch (e: NoSuchFieldException) {
If we still need this method, would it be possible to check if the field exists 
`Class.forName("").declaredFields.contains(field)` instead of catching an exception

2022-04-23 20:36 UTC, ktarasenko commented on workflow/testdata/COVIDCheck.cql
> +library DDCCPass version '0.0.1'
Could you please move the test data to a subfolder? It's slowly getting crowded

2022-04-23 20:36 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +      if (contextPath == "id" && contextValue is String) {
is there a constant for "id" somewhere?

2022-04-23 23:35 UTC, vitorpamplona commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +class FhirOperatorLibraryEvaluateTest {
My idea was to keep CQL tests running on the instrumented device to catch runtime exceptions of the environment (e.g. when XML-based or CQL/text libs are loaded and crash on Android only). Does it make sense?

2022-04-24 15:12 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +      if (contextPath == "id" && contextValue is String) {
We could use `fhirEngine.search` for everything instead of singling out the "id" request to the `fhirEngine.get`. I assume there is some performance benefit of using `get` instead of `search`, but if not, using search could remove the need to specify `id`

2022-04-24 15:13 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          // TODO: I am not sure why the default search is only for active entities
Can you point me out to the PR? I can incorporate those changes here.

2022-04-25 11:54 UTC, ktarasenko commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +class FhirOperatorLibraryEvaluateTest {
Got it. Yeah, makes sense.

2022-04-25 11:54 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          // TODO: I am not sure why the default search is only for active entities
keep if for now, I'll merge the change afterward

2022-04-25 12:51 UTC, ktarasenko commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +      if (contextPath == "id" && contextValue is String) {
I think keeping `get` is fine, i meant, do you know, is there a constant for the "id" string somewhere in `org.hl7.fhir.r4.model`?

2022-04-25 12:51 UTC, ktarasenko approved these changes

2022-04-25 15:11 UTC, f-odhiambo commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          // TODO: I am not sure why the default search is only for active entities
@vitorpamplona We had this check to basically filter records that are matched to active patients thus we do not run/evaluate this for inactive patients but this may not be true for all use cases cc @ktarasenko

2022-04-25 16:42 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          // TODO: I am not sure why the default search is only for active entities
I believe CQL rules should filter only active records themselves as opposed to the engine forcing all libraries to run only on active records.

2022-04-25 17:45 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +      if (contextPath == "id" && contextValue is String) {
There's no constant definition. The String comes from [here]( https://github.com/DBCG/cql_engine/blob/27d1321b92c83beb618b85181324b1c16a714b7a/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/FhirModelResolver.java#L98)

2022-05-16 16:11 UTC, jingtang10 commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +class FhirOperatorLibraryEvaluateTest {
are we sure these things can be caught?

2022-05-16 16:42 UTC, jingtang10 requested changes

2022-05-16 16:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +   */
no need to include @param or @return if there's nothing interesting to say about the param or the return value

2022-05-16 16:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +  fun hasField(dataType: String?, field: String): Boolean {
add empty line before new function

2022-05-16 16:42 UTC, jingtang10 commented on workflow/testdata/covid-check/COVIDCheck.cql
> +library DDCCPass version '0.0.1'
is this file used anywhere? i couldn't quite work out.

2022-05-16 16:42 UTC, jingtang10 commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +  fun evaluateCOVIDCheck() = runBlocking {
I would really love to see our test cases to be minimal. If for some reason, this test starts to fail, I will have no idea how to debug the cql libs. is there a way to simplify the test case so that it's basically testing the code path, and checking that the library is getting evaluated, without having complex logic such as covid?

from the point of view of the codebase, if the library does a complex calculation or if the library returns a simple true or false value doesn't make any diff right?

2022-05-16 16:50 UTC, vitorpamplona commented on workflow/testdata/covid-check/COVIDCheck.cql
> +library DDCCPass version '0.0.1'
This is kept just for reference since it has to be compiled into a Base64 representation and put into a library JSON file. The long-term goal is to compile the CQL before running these tests directly, removing the need to keep intermediary ELM representations.

2022-05-16 20:01 UTC, vitorpamplona commented on workflow/testdata/covid-check/COVIDCheck.cql
> +library DDCCPass version '0.0.1'
I deleted this file for now. It might come back when we are ready to compile CQL into Libraries directly on the SDK.

2022-05-18 12:50 UTC, jingtang10 approved these changes
thanks @vitorpamplona - around tests what i'm really concerned about is just that if the tests start failing, will someone be able to step in and debug the test. if the tests are super complex with a lot of artifacts, it'll be super hard. that's why i'm always pushing for minimum tests. thanks for making that change. 

additionally, can you add a little more comment on where the cql lib came from and how that's generated etc in the code comment? i know you can't add comment in json, so adding explanatino in the test file is good enough.

otherwise looking good. just have another small nit.

happy to merge if these are addressed.

2022-05-18 12:50 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +   * @param expressions ...... if omitted all expressions are evaluated
please update the `...` to actual words, or delete otherwise

2022-05-18 12:50 UTC, jingtang10 commented on workflow/src/androidTest/java/com/google/android/fhir/workflow/FhirOperatorLibraryEvaluateTest.kt
> +class FhirOperatorLibraryEvaluateTest {
good to know. thanks

2022-05-18 13:06 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +   * @param expressions ...... if omitted all expressions are evaluated
Fixed.

2022-05-18 13:16 UTC, vitorpamplona commented
> around tests what i'm really concerned about is just that if the tests start failing, will someone be able to step in and debug the test. if the tests are super complex with a lot of artifacts, it'll be super hard. that's why i'm always pushing for minimum tests. thanks for making that change.

I completely agree. Test structures for most of these CQL evaluation tasks are quite complex. I added PR #1395 to help understand this Test Case. It goes through the steps of Compiling CQL, generating the FHIR Library and making the bundle, which are necessary to call evaluate functions. As you can probably see, these are not really Unit tests. It's more of an integration test than anything else. 

I think moving forward, when the CQL compilation becomes available in the SDK, we can redesign these tests to go from reading CQL directly and running on it - masking all the intermediary processes and hopefully facilitating the understanding of what's happening. 

Once CQL compilation is available, we can also start breaking tests down to individual evaluation features. Right now it would be too much complexity and duplicated test resources to handle.

2022-05-24 12:06 UTC, merged