Changes to handle conflicts during download
google/android-fhir pull request #1335
Opened 2022-04-25 18:02 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1329 

**Description**

1. Added `ConflictResolver` in the engine library. Developer Application needs to provide its implementation via `FhirSyncWorker` for the engine to resolve conflicts that may arise during the downloading of resources.
2. Updated `FhirEngine.syncDownload` to return a flow of `DownloadedResource` that may represent a NonConflicting or Conflicting resource. 
3. `ResourceConflictProcessor` to process the incoming resources and handle conflicts.
4. Basic implementation of `ConflictResolver` provided with `AcceptOursStrategyBasedConflictResolver` and `AcceptTheirsStrategyBasedConflictResolver` that Developer Applications can use as-is. For advanced heuristics based conflict resolution, the Developer Applications may provide custom implementations.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-16 11:10 UTC, jingtang10 requested changes

2022-05-16 11:10 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +            database.update(*resolved.toTypedArray())
i'm slightly surprised we still have to do this - isn't the point of the conflict resolver to remove this gymnastics we have to do in the engine? can we simplify this?

2022-05-16 11:10 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +          ignorePaths.any { jsonObject.optString("path").startsWith(it) }
can you explain this change? i don't get it.

2022-05-16 11:10 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/ResourceConflictProcessor.kt
> +        val localResource = engine.get(remote.resourceType, remote.logicalId)
what if a new local change is added after this line? in that case it will simply be ignored right? this doesn't seem right. loading local change and resolving it should be atomic. @yigit

2022-05-16 16:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        is DownloadedResource.NonConflictingWithLocalChange -> this.remote.resourceType
since both have "remote" you can move it to the DownloadedResource definition, hence avoid the type checks here.

2022-05-16 16:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/ResourceConflictProcessor.kt
> +        val localResource = engine.get(remote.resourceType, remote.logicalId)
yep, we need to be locking the database for inserts while this logic is running.
we can do all of this in `db.withTransaction` to prevent concurrent changes.

2022-05-16 16:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/ResourceConflictProcessor.kt
> +          is ConflictResolutionResult.Resolved ->
not sure why we have this when/is here. `resolve` always returns `ConflcitResolutionResult.Resolved`

2022-05-17 17:03 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/ResourceConflictProcessor.kt
> +internal class ResourceConflictProcessor(
notes from offline discussion: lets move this to syncDownload in fhir engine impl since it owns the local data.

2022-05-23 13:27 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> +}
Done

2022-05-23 13:27 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> + * discarded.
Done

2022-05-23 13:28 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> +object AcceptOursStrategyBasedConflictResolver : ConflictResolver {
Renamed to `AcceptLocalConflictResolver` .

2022-05-23 13:29 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> +object AcceptTheirsStrategyBasedConflictResolver : ConflictResolver {
Renamed to `AcceptRemoteConflictResolver`

2022-05-23 13:29 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> +object AcceptOursStrategyBasedConflictResolver : ConflictResolver {
Rename to `AcceptLocalConflictResolver`

2022-05-23 13:31 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> +  override suspend fun resolve(local: Resource, remote: Resource): ConflictResolutionResult {
Done. Marked `ConflictResolver` as a functional interface and updated its implementors.

2022-05-23 13:31 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
> +object AcceptOursStrategyBasedConflictResolver : ConflictResolver {
Done

2022-05-23 13:32 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  data class NonConflictingWithLocalChange(
Not required anymore with the change to move resolution into the FhirEngine implementation .

2022-05-23 13:37 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ResourceConflictProcessor.kt
> +          is ConflictResolutionResult.Resolved ->
Code is refactored. So the comment is not relevant anymore.

2022-05-23 13:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        is DownloadedResource.NonConflictingWithLocalChange -> this.remote.resourceType
No relevant anymore because of the refactoring.

2022-05-23 13:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/ResourceConflictProcessor.kt
> +        val localResource = engine.get(remote.resourceType, remote.logicalId)
Code re-structured as per the offline discussion.

2022-05-23 13:55 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +          ignorePaths.any { jsonObject.optString("path").startsWith(it) }
The change is to not just check if path to ignore is just `/meta` and `/text`, but any path that starts with `/meta` or `/text`. I had encountered this while testing some resolution scenarios.

2022-06-20 21:21 UTC, jingtang10 approved these changes
looks good thanks - please wait for yigit's approval

2022-06-20 21:26 UTC, jingtang10 approved these changes

2022-06-20 21:26 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    conflictResolver: ConflictResolver,
move this to the second argument - seems more appropriate.

2022-06-20 21:26 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +          ignorePaths.any { jsonObject.optString("path").startsWith(it) }
can you add a little comment here?

2022-06-20 21:26 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +          ignorePaths.any { jsonObject.optString("path").startsWith(it) }
doesn't feel very readable. probably better to have an extension util function or something

2022-06-21 03:58 UTC, yigit requested changes

2022-06-21 03:58 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    conflictResolver: ConflictResolver,
if you mean second argument as `(download,conflictResolver)`; that is actually not what the kotlin style guide suggests.  function blocks are kept as the last argument so that you can pass them as a block. `syncDownload(resolver) { ... }`

2022-06-21 03:58 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +    db.withTransaction { block() }
```suggestion
    db.withTransaction(block)
```

2022-06-21 03:58 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +    db.withTransaction { localChangeDao.discardLocalChanges(resources) }
you don't need db.withTransaction here since you are executing 1 query. if it needs a transaction,it is better be done by annotating the method (see the comment on that file)

2022-06-21 03:58 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +  suspend fun discardLocalChanges(resources: List<Resource>) {
just annotate this method with `@Transaction`

2022-07-04 14:43 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +    db.withTransaction { block() }
done.

2022-07-04 14:44 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +    db.withTransaction { localChangeDao.discardLocalChanges(resources) }
Done. Removed `db.withTransaction` from here and added `@Transaction` to` LocalChangeDao. discardLocalChanges`.

2022-07-04 14:46 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    conflictResolver: ConflictResolver,
@jingtang10 Keeping the current function signature as per @yigit's comment.

2022-07-29 08:58 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    conflictResolver: ConflictResolver,
I mean, the conflict resolver is a single function interface so it can technically be a lambda too.

I sort of felt that download is the main operation so should be the first arg, and then conflict resolution is the second arg. But this is not a hill i'm gonna die on.

2022-07-29 08:59 UTC, jingtang10 approved these changes
thanks aditya - i think this is good to go.

you've addressed Yigit's comments. if he has additional comments when he's back from ooo we can do a follow-up.

2022-07-29 12:50 UTC, merged