Upgrading JUnit
google/android-fhir pull request #1342
Opened 2022-04-27 23:47 UTC by vitorpamplona

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1341

**Description**
Upgrade of JUnit and testing dependencies to 4.13

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**

Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-04-28 08:05 UTC, ktarasenko approved these changes

2022-04-28 08:05 UTC, ktarasenko commented on engine/build.gradle.kts
> +  // implementation(Dependencies.androidFhirCommon)
remove the commented out line

2022-04-28 09:04 UTC, jingtang10 requested changes

2022-04-28 16:12 UTC, vitorpamplona commented on datacapture/build.gradle.kts
> +  implementation(project(":common"))
Hum.. but every time anyone is trying to update dependencies they will get into a chicken and egg problem. In this case, android fhir common library forces 4.12, breaking the dependency resolution of gradle check. We can commit a broken check to update android fhir common library itself and then release the version to fix gradle check procedures, but it sounds hacky. 

This is a simple update. I assume when we get to the actual dependencies it could be necessarily hard to upgrade.

2022-04-28 16:12 UTC, vitorpamplona commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
4.13 is not available for non-alpha versions yet. Should we wait?

2022-04-29 10:25 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  implementation(project(":common"))
I see what you mean. Question: why should test dependencies have this effect? The fact that the `com.google.android.fhir:common` depends on junit 4.12 shouldn't be a problem for the other modules that depend on it? I thought that's the point of the separate `testImplementation` keywords in the gradle dependency block... ?!

If this is indeed an issue - we could publish a new version of common that depends on 4.13 (i can do that) and then immediately update the dependency of the other modules on common. Sorry this is more complex. But interdependencies between modules isn't something that I've discovered to be working well while publishing binaries.

2022-04-29 14:12 UTC, vitorpamplona commented on datacapture/build.gradle.kts
> +  implementation(project(":common"))
Do we know why `:common` [requires](https://github.com/Path-Check/android-fhir/blob/7251ddf22b906fae6528fc382693ad9a7fceedfb/common/build.gradle.kts#L58)
```groovy
implementation(Dependencies.Kotlin.kotlinTestJunit)
```
and not 
```groovy
testImplementation(Dependencies.Kotlin.kotlinTestJunit)
```
like everything else? 

That seems to be creating a runtime dependency on JUnit 4.12

It could be a simple oversight. It was added [here](https://github.com/Path-Check/android-fhir/commit/6e722c69eb3df766470ad16fe8951b395272c2d8).

2022-04-29 23:06 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  implementation(project(":common"))
#1351 to prepare common lib release

2022-05-02 07:01 UTC, santosh-pingle commented on datacapture/build.gradle.kts
> +  implementation(project(":common"))
Does it require to update the same change in `datacapture` module?
https://github.com/google/android-fhir/commit/e11c65f034e99ea9b7b88b8ad753583dec780c73#diff-c1be0bbfb8d6b1b28d7bc21ed7632dd09d1a81f5da9c612db062b87b7a56149f

2022-05-02 08:43 UTC, santosh-pingle commented on datacapture/build.gradle.kts
> +  implementation(project(":common"))
https://github.com/google/android-fhir/pull/1354

2022-05-03 19:35 UTC, jingtang10 commented
Hi @vitorpamplona - can you please update this PR now that #1353 is merged? Thanks!

2022-05-03 20:46 UTC, vitorpamplona commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
All up-to-date. Should we ship with alpha testing libs? I don't see a big issue with it.

2022-05-13 16:57 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
i don't feel this ticket is a priority any more given that we resolved the dependency issue of the common lib. based on that i don't feel there's a rush to upgrade junit to 4.13. we should wait a little bit.

2022-05-13 16:58 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
when will we be able to use 4.13 with non-alpha versions of other libs

2022-05-13 17:26 UTC, vitorpamplona commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
Agree, it's not urgent. The major goal for the upgrade is to get the method `assertThrows` on unit tests. It's useful because the engine throws an exception on `read(id)` if it can't find the object (as opposed to returning null). 

Today, we have to use this verbose version: 

```
assertThat(runCatching { provider.cleanup() }.exceptionOrNull())
      .isInstanceOf(IllegalStateException::class.java)
```

2022-05-16 13:03 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
i'm very surprised using public version 4.13 of junit requires using alpha versions of other libs... this seems totally wrong. is there any documentation on this? any one raised any issues?

2022-05-16 13:33 UTC, vitorpamplona commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val runner = "1.5.0-alpha02"
I am not sure why it surprises you. 4.13 is a somewhat new version. The majority of AndroidX test libs are still on 4.12.

2022-09-21 10:32 UTC, jingtang10 commented
closing this due to it being very old. vitor please feel free to update and reopen.

i'll also try to handle this update in my hapi upadte pr #1616

2022-09-21 13:56 UTC, closed without merging