Fix added for crashe on click of submit button after editing patient details
google/android-fhir pull request #1361
Opened 2022-05-04 13:31 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1229

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Progressbar can be added till data gets loaded on screen

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-13 17:53 UTC, jingtang10 requested changes

2022-05-13 17:53 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +  private var isBindingDone: Boolean = false
i'm not sure these things should be stored as private vars... that just introduces state into the ui classes. in android these should be coming from view model. @stevenckngaa @yigit do you agree?

2022-05-13 17:53 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +      }
can you just simply set the visibility to visible here?

2022-05-13 17:53 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +    menuItemEdit.setVisible(isBindingDone)
should the default visibility be invisible?

2022-05-16 08:02 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +  private var isBindingDone: Boolean = false
@kevinmost

2022-05-16 09:43 UTC, stevenckngaa commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +      }
+1. I don't know if that's needed to store a variable.

From my understanding, `invalidateOptionsMenu` recreates the entire menu. This seems a bit an overkill for updating the visibility of a button.

On top of that, should we disable the button from the menu rather than making it invisible?

2022-05-16 09:43 UTC, stevenckngaa commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +    menuItemEdit.setVisible(isBindingDone)
+1. Probably put the default in action_add_patient_submit.xml and fix the issue across the board. Look like ScreenFragment is missing from the fix.

2022-05-18 04:14 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +  private var isBindingDone: Boolean = false
Removed private variable. Now button is enabled and disabled on the basis of live data availability

2022-05-18 04:17 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +    menuItemEdit.setVisible(isBindingDone)
This issue is not present in ScreenerFragment. It works fine with max count of resources(in demo app patients) as well.

2022-05-18 05:17 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +      }
On Android 3.0 and higher, on call to [invalidateOptionsMenu()](https://developer.android.com/reference/android/app/Activity#invalidateOptionsMenu()) intternally system calls [onPrepareOptionsMenu()](https://developer.android.com/reference/android/app/Activity#onPrepareOptionsMenu(android.view.Menu)).

2022-05-20 06:27 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +    menuItemEdit.setVisible(isBindingDone)
@jingtang10  As discussed removed onPrepareOptionsMenu() method and updated code

2022-05-20 06:33 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/EditPatientFragment.kt
> +    menuItemEdit.setVisible(isBindingDone)
For disable state of edit button i have added "reticle_ripple" i.e. #9AFFFFFF. If required we can change it

2022-05-23 11:29 UTC, PallaviGanorkar commented on datacapture/src/main/res/color/edit_menu_color.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Yes. I missed it. Done

2022-05-23 11:44 UTC, PallaviGanorkar commented on demo/src/main/res/menu/details_options_menu.xml
> +        android:enabled="false"
Done

2022-05-23 11:45 UTC, PallaviGanorkar commented on demo/src/main/res/menu/add_patient_fragment_menu.xml
> +    />
Done but there are no changes to this file.

2022-05-30 13:38 UTC, jingtang10 requested changes

2022-05-30 13:38 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/AddPatientFragment.kt
> +    menu.findItem(R.id.action_add_patient_submit).setEnabled(true)
please create separate menus for add patient and edit patient so you don't need to set this.

2022-05-30 13:38 UTC, jingtang10 commented on demo/src/main/res/color/edit_menu_color.xml
> +    <item android:color="@color/reticle_ripple" android:state_enabled="false" />
instead of using a specific color - can you use material colors: https://m3.material.io/libraries/mdc-android/color-theming

2022-05-31 16:22 UTC, PallaviGanorkar commented on demo/src/main/res/color/edit_menu_color.xml
> +    <item android:color="@color/reticle_ripple" android:state_enabled="false" />
Done

2022-06-06 18:57 UTC, merged