Indexing for SearchParams defined in Resource class
google/android-fhir pull request #1368
Opened 2022-05-06 08:47 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1305 

**Description**
The search parameters defined in Resource class like id has path defined as `Resource.id`. With this, when a derived class like `Patient` is passed into the `FHIRPathEngine.evaluate` function, it doesn't return anything. So, we are adding the index values manually.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-16 11:21 UTC, jingtang10 requested changes

2022-05-16 11:21 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        enableEncryptionIfSupported = false,
did you need this change for testing? reverse please if so.

2022-05-16 11:21 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * Adds indexes for [SearchParameter] defined in [Resource] class. The reason they are added here
```suggestion
   * Adds indexes for [SearchParameter]s defined in [Resource] class. The reason they are added here
```

2022-05-16 11:21 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * manually is because the path for these [SearchParameter]s is defined for [Resource] class and
"The reason they are added here manually is because" -> "This is because"

2022-05-16 11:21 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * [FHIRPathEngine.evaluate] doesn't return anything when run against a derived resource like
The actual reason is the code generator doesn't generate search parameters for the base resource class right?

2022-05-16 11:41 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        enableEncryptionIfSupported = false,
Yes, oversight on my end. Will revert it.

2022-05-18 09:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * [FHIRPathEngine.evaluate] doesn't return anything when run against a derived resource like
Right and also because the expression path is defined for the resource class and hence when a derived class like `Patient` is evaluated for id using expression path `Resource.id`, `FHIRPathEngine` doesn't return anything. it expects the path to be "Patient.id".

2022-05-18 10:37 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        enableEncryptionIfSupported = false,
Done

2022-05-18 10:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * [FHIRPathEngine.evaluate] doesn't return anything when run against a derived resource like
Updated the comments to explain the reason.

2022-05-18 10:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * manually is because the path for these [SearchParameter]s is defined for [Resource] class and
Done

2022-05-18 10:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +   * Adds indexes for [SearchParameter] defined in [Resource] class. The reason they are added here
Done

2022-05-23 12:52 UTC, jingtang10 approved these changes

2022-05-24 07:35 UTC, merged