showing downloaded patient list from DB if sync Api fails in between
google/android-fhir pull request #1372
Opened 2022-05-09 06:48 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1134

**Description**
1. Added progress bar for sync operation at first app launch, So the screen won't be Idle while downloading resources
2. If the some resources are downloaded and the API fails in between, Here shown list from DB wherever patients are downloaded.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-13 18:04 UTC, jingtang10 commented
great pr - thanks @PallaviGanorkar!

can you attach a video?

2022-05-30 13:59 UTC, jingtang10 requested changes
@aditya-07 suggested having a top banner that shows the status fo the sync. I think that makes this implementation easier. bcause you don't need to use shared preferences any more. just always listen to the state and update the top banner.

2022-06-01 10:53 UTC, jingtang10 commented
@shelaghm just so you are aware.

2022-06-03 13:00 UTC, PallaviGanorkar commented
video attached with suggested UI change by @shelaghm 

https://user-images.githubusercontent.com/13957417/171858835-a5c18a1e-115d-4ebb-9fca-a730f29f8c37.mp4

2022-06-03 13:15 UTC, PallaviGanorkar commented
sync status background color updated as per UI

![sync_status_background_color](https://user-images.githubusercontent.com/13957417/171861376-1bf162b7-dd6e-4637-9b15-852373b9c0a2.png)

2022-06-04 11:01 UTC, jingtang10 requested changes
@PallaviGanorkar can you also remove the toast in the same PR?

2022-06-06 13:03 UTC, PallaviGanorkar commented on demo/src/main/res/values/strings.xml
> +  <string name="is_first_launch">isFirstLaunch</string>
Done

2022-06-06 13:04 UTC, PallaviGanorkar commented on demo/src/main/res/values/strings.xml
> +  <string name="syncing">SYNCING</string>
Done

2022-06-06 13:09 UTC, PallaviGanorkar commented on demo/src/main/res/layout/sync_status_layout.xml
> +<LinearLayout
i am using  android:drawableLeft in TextView, this is case  drawable will be displayed on extreme left of TextView with match parent width and 'Syncing' text will appear at center. So, to display drawable and text at center have to use layout

2022-06-06 13:11 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +  private lateinit var tvSyncingStatus: LinearLayout
Done

2022-06-06 15:07 UTC, PallaviGanorkar commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +        if (it is State.Finished || it is State.Failed) {
Done these in this PR itself. Please review

2022-07-05 22:18 UTC, merged