tests to prevent no row insertion in DB when there is empty/no local …
google/android-fhir pull request #1373
Opened 2022-05-09 15:55 UTC by PallaviGanorkar

…changes

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #346

**Description**
Test case added for no row should be inserted in database if there is update with empty/ no local changes

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-01 11:07 UTC, jingtang10 requested changes

2022-06-03 12:29 UTC, PallaviGanorkar commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(thirdlocalChangeCount).isEqualTo(3)
done

2022-06-03 12:29 UTC, PallaviGanorkar commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(fourthLocalChangeCount).isEqualTo(3)
done

2022-06-04 11:07 UTC, jingtang10 approved these changes
Approved - but please address the comments first

2022-06-04 11:07 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val squashed3localChanges =
```suggestion
    val squashedLocalChange =
```

2022-06-04 11:07 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +        .isEqualTo(com.google.android.fhir.db.impl.entities.LocalChangeEntity.Type.INSERT)
Question: Is your AndroidStudio configured to show these suggestions?

```suggestion
        .isEqualTo(LocalChangeEntity.Type.INSERT)
```

2022-06-04 11:07 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val squashedlocalChangeWithNoUpdate =
```suggestion
    val squashedLocalChangeWithNoFurtherUpdate =
```

2022-06-08 11:13 UTC, PallaviGanorkar commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val squashed3localChanges =
Done

2022-06-08 11:16 UTC, PallaviGanorkar commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +        .isEqualTo(com.google.android.fhir.db.impl.entities.LocalChangeEntity.Type.INSERT)
Done

2022-06-08 11:18 UTC, PallaviGanorkar commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val squashedlocalChangeWithNoUpdate =
Done

2022-06-09 19:29 UTC, merged