Add itemImage extension support
google/android-fhir pull request #1377
Opened 2022-05-10 08:12 UTC by ekigamba

Fixes #802

**Description**
Add support for `cpg-itemImage` extension on question types. Render the referenced image and provide an AttachmentResolver interface(WIP)

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
Yes, other alternatives were considered but this is a simpler solution

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

Duplicate of https://github.com/google/android-fhir/pull/807

2022-06-02 05:21 UTC, FikriMilano commented
@aditya-07 Kindly do another review, I already addressed all of the review feedback.

But I'm not sure why, sometimes the checks is failing on it's own e.g build fails or out of memory error.
cc @ekigamba @ndegwamartin

2022-06-06 06:52 UTC, FikriMilano commented
Tried to trigger the CI checks and got this error, it works locally though.
```
com.google.android.fhir.sync.SyncJobTest > sync time should update on every sync call FAILED
    java.lang.IndexOutOfBoundsException at SyncJobTest.kt:215
```

2022-06-15 11:53 UTC, Tarun-Bhardwaj commented
@FikriMilano, are you still blocked on this PR? Is there any help you need?
CC: @aditya-07

2022-06-17 03:56 UTC, FikriMilano commented
@Tarun-Bhardwaj thanks.

I'm no longer blocked, it's just sometimes the CI works sometimes it doesn't.

Also, I was trying to increase the code coverage, but it's quite difficult because some parts of the code keeps showing partial coverage, no matter how I wrote the test.

To sum up, this PR just need a review.

2022-07-01 12:06 UTC, FikriMilano commented on demo/src/main/java/com/google/android/fhir/demo/ReferenceAttachmentResolver.kt
> +    }*/
Done

2022-07-01 12:06 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +    android:orientation="vertical"
Nope, it should be horizontal

https://github.com/google/android-fhir/blob/be98cd52dbec0f45dce6692e8aeb2602d849a289/datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml#L21

2022-07-01 12:07 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +    android:orientation="vertical"
Done

2022-07-04 14:15 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt
> +          activity.lifecycleScope.launch {
Can we make sure the `fetchBitmap` happens on the IO dispatcher and not the `default` dispatcher?

Make this change for all the other classes. You can alternatively see if you have this code at a central class/util and call it from the classes

2022-07-04 14:15 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      activity.lifecycleScope.launch {
Can we make sure the `fetchBitmap` happens on the IO dispatcher and not the `default` dispatcher?

2022-07-04 14:15 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
> +          activity.lifecycleScope.launch {
Can we make sure the `fetchBitmap` happens on the IO dispatcher and not the `default` dispatcher?

2022-07-04 14:15 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
> +                // throw RuntimeException("At last! This has run")
I added these comments during testing. You can remove them now

2022-07-06 07:18 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
> +          activity.lifecycleScope.launch {
Done

2022-08-18 09:04 UTC, FikriMilano commented
Sorry, I'm currently occupied on other stuff, this is pending.

2022-08-19 09:45 UTC, ekigamba commented
@FikriMilano Kindly change this to `itemMedia` and log an error or show a toast for not supporting videos. We can have this implemented on another PR/issue. 

I forgot about this as we were waiting for the change request to be approved https://github.com/google/android-fhir/issues/802#issuecomment-963983792

2022-08-19 10:38 UTC, FikriMilano commented
Sure, make sense

2022-08-23 08:29 UTC, ekigamba commented on common/build.gradle.kts
> +  implementation(Dependencies.Androidx.appCompat)
Is this supposed to be here?

2022-08-23 08:29 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
> +        contentType = "video/mp4"
Let's revert this to `document/pdf` or something else since `video/mp4` is supposed to be handled by the `itemMedia`

2022-08-23 08:29 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactoryInstrumentedTest.kt
> +        contentType = "video/mp4"
We should also use some other content types since support for `video/mp4` should be added in another PR and other scoping on this

2022-08-23 08:42 UTC, ekigamba commented on common/build.gradle.kts
> +  implementation(Dependencies.Androidx.appCompat)
Is this supposed to be here

2022-08-23 08:42 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +        contentType = "video/mp4"
Let's revert this to `document/pdf` or something else since `video/mp4` is supposed to be handled by the `itemMedia`

2022-08-23 09:58 UTC, jingtang10 requested changes

2022-08-23 09:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
> +        }
this code is duplicated in multiple files please make sure this happens only in one place.

2022-08-23 12:32 UTC, FikriMilano commented on common/build.gradle.kts
> +  implementation(Dependencies.Androidx.appCompat)
Nope, good catch, will remove

2022-08-23 12:32 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
> +        contentType = "video/mp4"
Sure

2022-08-23 12:32 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +        contentType = "video/mp4"
Sure

2022-08-23 12:32 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
> +        }
Agreed, will do that

2022-08-23 12:33 UTC, FikriMilano commented on common/build.gradle.kts
> +  implementation(Dependencies.Androidx.appCompat)
Nope, good catch, will remove

2022-09-06 23:49 UTC, FikriMilano commented
@jingtang10 this is ready for review

2022-09-19 08:32 UTC, FikriMilano commented
We found a few bugs when rendering the image, @ekigamba is here to check on it.

Image is able to render in edit text type questionnaire.
But not for display and group type questionnaire.

I tried comparing each associated ViewHolderFactory but wasn't able to found a difference that cause the bug.

cc @jingtang10 @f-odhiambo

2022-09-19 10:34 UTC, ekigamba commented
@FikriMilano It seems that the issue is the orientation for the display items. I changed the linear layout orientation to `vertical` and I can see the images.

2022-09-21 02:40 UTC, FikriMilano commented
@jingtang10 @f-odhiambo @ekigamba 
This bug is fixed

2022-09-22 08:38 UTC, ekigamba commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +    android:orientation="vertical"
@FikriMilano It seems you'll have to use a different layout for this widget or embed the header + error view inside a separate linear layout whose orientation is horizontal while the outer layout containing the `QuestionnaireItemMediaView` retains the vertical orientation. Does this make sense?

2022-09-22 08:38 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextMultiLineViewHolderFactoryInstrumentedTest.kt
> +class QuestionnaireItemEditTextMultiLineViewHolderFactoryInstrumentedTest {
Since we moved the code to another class, see if we can remove this duplicate tests without reducing the coverage. I believe these tests cover the same code inside the `QuestionnaireItemMediaView`

2022-09-22 08:38 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +class QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest {
Since we moved the code to another class, see if we can remove this duplicate tests without reducing the coverage. I believe these tests cover the same code inside the `QuestionnaireItemMediaView`

2022-09-22 08:38 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
> +class QuestionnaireItemGroupViewHolderFactoryInstrumentedTest {
Since we moved the code to another class, see if we can remove this duplicate tests without reducing the coverage. I believe these tests cover the same code inside the `QuestionnaireItemMediaView`

2022-09-22 08:42 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
> +class QuestionnaireItemGroupViewHolderFactoryInstrumentedTest {
Yeah, true

2022-09-22 08:42 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest.kt
> +class QuestionnaireItemEditTextSingleLineViewHolderFactoryInstrumentedTest {
Yeah, true

2022-09-22 08:42 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextMultiLineViewHolderFactoryInstrumentedTest.kt
> +class QuestionnaireItemEditTextMultiLineViewHolderFactoryInstrumentedTest {
Yeah, true

2022-09-22 09:30 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaViewTest.kt
> +class QuestionnaireItemMediaViewTest {
Let's rename this to `QuestionnaireItemMediaViewInstrumentedTest` so that we can optionally have another test class in the unit tests folder

2022-09-28 08:11 UTC, FikriMilano commented
> @FikriMilano It seems you'll have to use a different layout for this widget or embed the header + error view inside a separate linear layout whose orientation is horizontal while the outer layout containing the QuestionnaireItemMediaView retains the vertical orientation. Does this make sense?

@ekigamba I think this does not matter, because originally using the `horizontal` orientation, the group type won't be able to show the error message.
But, changing it to `vertical` does enable the group type to show the error message. 
So I suggest to keep this change

2022-11-01 09:58 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> -          } catch (exception: NumberFormatException) {
Let's take a look at this

2022-11-04 13:45 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> -          } catch (exception: NumberFormatException) {
This change is from master branch, it's ok

2022-11-22 19:28 UTC, jingtang10 requested changes

2022-11-22 19:28 UTC, jingtang10 commented on contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/Utils.kt
> +  internal fun Context.tryUnwrapContext(): AppCompatActivity? {
remove this and use the one from utilities?

2022-11-22 19:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> +  var attachmentResolver: AttachmentResolver? = null
have you considered using a content provider?

@yigit @stevenckngaa do you think content resolver/provider here is a good solution? the usecase is that in the structured data capture library we might need to retrieve attachment data from a certain url - and we want the applicaton to be able to resolve the url to binary data which is to be rendered in the screen.

2022-11-22 19:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> -          } catch (exception: NumberFormatException) {
??? can you sync and make sure this is up to date?

2022-11-22 19:28 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_media.xml
> +<?xml version="1.0" encoding="utf-8" ?>
is this media view or image view?

2022-11-22 19:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    itemMedia.bind(questionnaireItemViewItem.questionnaireItem)
have you considered putting this functionality in `QuestionnaireItemViewHolderFactory.kt` since any questionnaire item can have a media extension?

2023-01-16 09:26 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_media.xml
> +<LinearLayout
yeah, should be

2023-01-16 09:26 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreContext.kt
> +/*
sure

2023-01-16 09:26 UTC, FikriMilano commented on contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/Utils.kt
> +  internal fun Context.tryUnwrapContext(): AppCompatActivity? {
sure

2023-01-16 09:27 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> +  var attachmentResolver: AttachmentResolver? = null
let me try

2023-01-16 09:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    itemMedia.bind(questionnaireItemViewItem.questionnaireItem)
sure

2023-01-16 09:31 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> -          } catch (exception: NumberFormatException) {
okay

2023-01-17 01:28 UTC, FikriMilano commented
I think a refactor is needed for this PR. 
Given that the Attachment widget PR is merged, it will be nice if we can re-use some of those code.

cc @f-odhiambo @jingtang10

2023-01-24 06:33 UTC, FikriMilano commented
@jingtang10 @omarismail94 this is ready for review

2023-01-30 13:51 UTC, delcroip commented
Is it a duplicate of https://github.com/google/android-fhir/pull/1749 ?

2023-01-30 13:54 UTC, FikriMilano commented
@delcroip no, that's item media for answers. This one is for questions.

2023-01-30 13:59 UTC, delcroip commented
Thanks @FikriMilano Do you know why this url is not used in that case ? 
http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemMedia

2023-02-02 10:11 UTC, FikriMilano commented
@delcroip not really sure about that.

implementation between the 2 is a bit different though.

2023-02-03 13:40 UTC, jingtang10 commented
> Thanks @FikriMilano Do you know why this url is not used in that case ? http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemMedia (not sure why the above url is not used for answer too, I don't see the conceptual difference with http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia)

hi @delcroip. Please see this link http://hl7.org/fhir/uv/sdc/STU3/rendering.html#itemMedia.

I think itemMedia is about additional image/video/audio clips to help the health worker answer a specific question. and itemAnswerMedia is a something that accompanies specific answer options.

For example, if there is a question asking the health worker to carry out a test, there might be an itemMedia extension with an image to explain to the health worker how to do the test.

And if there're answer options (apple, pear, orange) to a question, each of the answer options might have an accompanying itemAnswerMedia (a picture of apple, a picture of pear, a picture of orange) to help the health worker pick the right option

2023-02-03 14:40 UTC, delcroip commented
> > Thanks @FikriMilano Do you know why this url is not used in that case ? http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemMedia (not sure why the above url is not used for answer too, I don't see the conceptual difference with http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia)
> 
> hi @delcroip. Please see this link http://hl7.org/fhir/uv/sdc/STU3/rendering.html#itemMedia.
> 
> I think itemMedia is about additional image/video/audio clips to help the health worker answer a specific question. and itemAnswerMedia is a something that accompanies specific answer options.
> 
> For example, if there is a question asking the health worker to carry out a test, there might be an itemMedia extension with an image to explain to the health worker how to do the test.
> 
> And if there're answer options (apple, pear, orange) to a question, each of the answer options might have an accompanying itemAnswerMedia (a picture of apple, a picture of pear, a picture of orange) to help the health worker pick the right option


This remark is a detail, more for fhir guys (poke @brynrhodes )
I understand the different context, my point is that ItemMedia on a answer say that the media is on the answer, when on a item then the media is on the item. I simply fail to understand why two extensions are required for adding a media to an item or answer (a single ext could be applicable on item and answer)

2023-02-06 10:13 UTC, jingtang10 commented
> > > Thanks @FikriMilano Do you know why this url is not used in that case ? http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemMedia (not sure why the above url is not used for answer too, I don't see the conceptual difference with http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia)
> > 
> > 
> > hi @delcroip. Please see this link http://hl7.org/fhir/uv/sdc/STU3/rendering.html#itemMedia.
> > I think itemMedia is about additional image/video/audio clips to help the health worker answer a specific question. and itemAnswerMedia is a something that accompanies specific answer options.
> > For example, if there is a question asking the health worker to carry out a test, there might be an itemMedia extension with an image to explain to the health worker how to do the test.
> > And if there're answer options (apple, pear, orange) to a question, each of the answer options might have an accompanying itemAnswerMedia (a picture of apple, a picture of pear, a picture of orange) to help the health worker pick the right option
> 
> This remark is a detail, more for fhir guys (poke @brynrhodes ) I understand the different context, my point is that ItemMedia on a answer say that the media is on the answer, when on a item then the media is on the item. I simply fail to understand why two extensions are required for adding a media to an item or answer (a single ext could be applicable on item and answer)

thanks @delcroip for explaining further your concern. i think there're probably pros/cons to the current approach and what you are proposing. let's move this discussion to the questionnaire stream on chat.fhir.org to get the actual decision makers involved. in the mean time let's stick to what's currently in the standard until things change.

2023-02-06 11:49 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
> - * Copyright 2021 Google LLC
definitely

2023-02-06 11:49 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> -private val String.type: String
sure

2023-02-06 11:49 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Decode the Bitmap representation of [Binary.data]. */
sure

2023-02-06 11:49 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Decode the Bitmap representation of [Attachment.data]. */
sure

2023-02-06 11:49 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Fetch the Bitmap representation of [Attachment.url]. */
sure

2023-02-06 11:52 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val String.type: String
double checked, not a duplicate

2023-02-06 13:39 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val String.type: String
@PallaviGanorkar was using the full mime type, that's why

2023-02-06 13:40 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val String.type: String
https://github.com/google/android-fhir/pull/1749/files#diff-20095a92fea5035a44af013ca62d4126bedfdde8895405cb6cadfbc5733691e7R53-R55

2023-02-06 14:03 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    }
I agree with the logic being fragile.

for the second half, @ekigamba can help to answer this

2023-02-07 06:35 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    }
I also agree. Nice catch! on the first one
For the second one, we probably don't need to have both. The logic was supposed to assist in decoding of the Binary resource to bitmap

2023-02-07 06:53 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    }
thanks all, I will add the changes as discussed.

since we're going to have 1 url thing only, I will remove the condition as well.

2023-02-14 10:50 UTC, jingtang10 requested changes
Thanks @FikriMilano for taking thsi on.

Please add a screenshot to the PR.

Either document the following in the existing github issue (and make sure the issue doesn't get automatically closed) or create a new issue to track the following:

- add a new style to allow customization of item media
- discuss with @shelaghm the default look and feel (especially where it is positioned in relation to other components in a question, and the size and alignment etc) of the item media in different components

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/testing/DataCaptureTestApplication.kt
> -internal class DataCaptureTestApplication : Application(), DataCaptureConfig.Provider {
can you try to revert this change?

2023-02-14 10:50 UTC, jingtang10 commented on demo/src/main/assets/screener-questionnaire.json
> +          ]
is this even taking any effect inthe demo app? because the reference url resolver below is not really resolving this url.

can you just revert this change?

2023-02-14 10:50 UTC, jingtang10 commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
can you revert this?

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> +  /** A [UrlResolver] may be set by client to resolve url to it's media representation. */
```suggestion
  /** Resolves a URL to the media binary content. */
```

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> + * Resolves media based on the provided url. This allows the library to retrieve media from a url.
```suggestion
 * Resolves media content based on the provided URL, allowing the library to render media content in its UI.
```

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaView.kt
> +  /** Only usable for a String known as mime type. */
Add an example here.

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaView.kt
> +  /** Only usable for a String known as mime type. */
```suggestion
  /** Returns the main MIME type of a MIME type string (e.g. removing the subtype). */
```

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +    val urlResolver: UrlResolver = mock()
there's no need to mock. just implement this.

i did a quick search and found this article: https://torvo.com.au/articles/why-mocks-are-considered-harmful#:~:text=Automated%20testing%20during%20software%20development,provide%20false%20confidence%20at%20worst. but there are plenty of discussisons online.

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +import org.mockito.kotlin.mock
remove these once the comment below is addressed.

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="cd_item_media_image_attachment">Image attachment</string>
can this be removed?

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_media.xml
> +        android:contentDescription="@string/cd_item_media_image_attachment"
remove this

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsInstrumentedTest.kt
> +class MoreQuestionnaireItemComponentsInstrumentedTest {
can this class not be in test instead of androidTest?

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsInstrumentedTest.kt
> +class MoreQuestionnaireItemComponentsInstrumentedTest {
can this class just be removed? isn't this a duplicate of the test calss in test?

2023-02-14 10:50 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaViewInstrumentedTest.kt
> +    delay(1000)
this is bad for performance - going to slow the tests a lot. why is this needed?

@omarismail94 can you help impove this with your latest change?

2023-02-15 03:35 UTC, FikriMilano commented on datacapture/src/main/res/values/strings.xml
> +    <string name="cd_item_media_image_attachment">Image attachment</string>
@jingtang10 I have a good idea, let me know if you're ok w this.
perhaps we add the content description dynamically, we can append this into the ImageView based on [Attachment.title](https://build.fhir.org/datatypes-definitions.html#Attachment.title), it's nullable though.

putting the code in QuestionnaireItemMediaView should work

2023-02-15 03:35 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +import org.mockito.kotlin.mock
sure

2023-02-15 03:36 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +    val urlResolver: UrlResolver = mock()
I agree, good to know, thanks

2023-02-15 03:37 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaView.kt
> +  /** Only usable for a String known as mime type. */
added the comment w `(e.g. image/png returns image)`

2023-02-15 03:37 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaView.kt
> +  /** Only usable for a String known as mime type. */
sure

2023-02-15 03:37 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> + * Resolves media based on the provided url. This allows the library to retrieve media from a url.
sure

2023-02-15 03:37 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> +  /** A [UrlResolver] may be set by client to resolve url to it's media representation. */
sure

2023-02-15 03:37 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/testing/DataCaptureTestApplication.kt
> -internal class DataCaptureTestApplication : Application(), DataCaptureConfig.Provider {
sure

2023-02-15 03:38 UTC, FikriMilano commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
sure.

@shelaghm should we have a new catalog view for this?

2023-02-15 06:08 UTC, shelaghm commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
@FikriMilano Do you mean a new widget/component in the SDC catalog app? Currently we have an`image` component that doesn't have any content in it. We could use that same icon and update the name to be Media Extension? cc @santosh-pingle what do you think?

2023-02-15 06:46 UTC, FikriMilano commented on demo/src/main/assets/screener-questionnaire.json
> +          ]
sure

2023-02-15 07:05 UTC, FikriMilano commented on demo/src/main/assets/screener-questionnaire.json
> +          ]
@jingtang10 
I updated the reference url resolver, now it can actually show image.
and yes, this questionnaire is actually used by the demo app for patient survey.

sorry for the back and forth

<img src="https://user-images.githubusercontent.com/62053304/218955760-a358a0b7-0583-4214-8e1e-45daba8f2a99.png" width="300">

2023-02-15 07:28 UTC, FikriMilano commented on demo/src/main/assets/screener-questionnaire.json
> +          ]
I think we need to enable customization for this

2023-02-15 07:29 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsInstrumentedTest.kt
> +class MoreQuestionnaireItemComponentsInstrumentedTest {
agree, removed

2023-02-15 07:30 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_media.xml
> +        android:contentDescription="@string/cd_item_media_image_attachment"
see this
https://github.com/google/android-fhir/pull/1377#discussion_r1106611848

2023-02-15 07:33 UTC, FikriMilano commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
@shelaghm yeah, good idea; that was previously removed since it's not used. We can bring that back, though.

Should we use the thermometer image for the Questionnaire JSON?

2023-02-15 07:37 UTC, FikriMilano commented
@jingtang10 @shelaghm 
here's a screenshot of the thermometer image using itemMedia in the demo app.
this is using ReferenceUrlResolver, it no longer returns null

<img src="https://user-images.githubusercontent.com/62053304/218955760-a358a0b7-0583-4214-8e1e-45daba8f2a99.png" width="300">

2023-02-15 12:55 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
> + * Resolves media based on the provided url. This allows the library to retrieve media from a url.
sure

2023-02-15 13:05 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMediaViewInstrumentedTest.kt
> +    delay(1000)
Removed

2023-02-15 18:35 UTC, shelaghm commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
Hi @FikriMilano 

Some more specific guidance. 
(1) Add this to the `misc widgets` section
(2) Call this component `itemMedia`, and then will also add `itemAnswer Media` for the other component that is for itemAnswer Media Extension. 
(3) Can you use this image instead? 
<img width="364" alt="BloodSugar" src="https://user-images.githubusercontent.com/86378921/219119322-c4539caa-4866-4352-a485-b5fba4ef1b2a.png">
(4) Based on updating the image, I also think we need to update the text field boxes, so that the image makes a bit more sense. I recommend making this example about blood glucose. One text box with `Blood glucose (mg/dL)`
<img width="917" alt="Screenshot 2023-02-15 at 10 31 50" src="https://user-images.githubusercontent.com/86378921/219121352-fa8c06f5-8089-4502-af77-66fab6d2cce6.png">

2023-02-16 02:52 UTC, FikriMilano commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
Thanks I'll do that

2023-02-16 02:56 UTC, FikriMilano commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
@shelaghm itemMedia and itemAnswer Media have the same icon. Are you ok w this?

<img src="https://user-images.githubusercontent.com/62053304/219256008-0e867a89-a9e7-42fa-bcd3-5e8857ab00a3.png" width="300">

2023-02-16 03:53 UTC, FikriMilano commented
@jingtang10 @shelaghm 
Created this ticket to track styling item media and see supported possibilities of customization https://github.com/google/android-fhir/issues/1874

2023-02-16 07:39 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_media.xml
> +        android:contentDescription="@string/cd_item_media_image_attachment"
but yes, we can remove this string

2023-02-16 07:39 UTC, FikriMilano commented on datacapture/src/main/res/values/strings.xml
> +    <string name="cd_item_media_image_attachment">Image attachment</string>
but yes, we can remove this string

2023-02-16 10:43 UTC, FikriMilano commented
hi @omarismail94 
do you have an idea why this error happens in kokoro?

```
> Task :workflow:runFlank

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5m 42s
10 actionable tasks: 3 executed, 7 up-to-date

Publishing build scan...
https://gradle.com/s/a5om7b7jgjqfw

                                                         5m  8s Test executions status: FINISHED:6, RUNNING:6                                                         5m 13s Test executions status: FINISHED:6, RUNNING:6                                                         5m 18s Test executions status: FINISHED:6, RUNNING:6                                                         5m 23s Test executions status: FINISHED:6, RUNNING:6                                                         5m 28s Test executions status: FINISHED:6, RUNNING:6                                                         5m 33s Test executions status: FINISHED:6, RUNNING:6                                                         5m 38s Test executions status: FINISHED:6, RUNNING:6                                                         5m 43s Test executions status: FINISHED:6, RUNNING:6                                                         5m 48s Test executions status: FINISHED:6, RUNNING:6                                                         5m 53s Test executions status: FINISHED:6, RUNNING:6                                                         5m 58s Test executions status: FINISHED:6, RUNNING:6                                                         6m  3s Test executions status: FINISHED:6, RUNNING:6                                                         6m  8s Test executions status: FINISHED:6, RUNNING:6                                                         6m 13s Test executions status: FINISHED:6, RUNNING:6                                                         6m 18s Test executions status: FINISHED:6, RUNNING:6                                                         6m 24s Test executions status: FINISHED:7, RUNNING:5                                                         6m 29s Test executions status: FINISHED:7, RUNNING:5                                                         6m 34s Test executions status: FINISHED:8, RUNNING:4                                                         6m 39s Test executions status: FINISHED:10, RUNNING:2                                                          6m 44s Test executions status: FINISHED:10, RUNNING:2                                                          6m 49s Test executions status: FINISHED:10, RUNNING:2                                                          6m 54s Test executions status: FINISHED:10, RUNNING:2                                                          6m 59s Test executions status: FINISHED:11, RUNNING:1                                                          7m  4s Test executions status: FINISHED:12
  7m  4s matrix-2b70wos590qss FINISHED


FetchArtifacts
    Updating matrix file
  Uploading [performanceMetrics.json] to https://console.developers.google.com/storage/browser/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/matrix_0/...
CostReport
  Physical devices
    $0.33 for 4m

  Uploading [CostReport.txt] to https://console.developers.google.com/storage/browser/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/...
  Uploading [MatrixResultsReport.txt] to https://console.developers.google.com/storage/browser/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/...
  Uploading [JUnitReport.xml] to https://console.developers.google.com/storage/browser/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/...

MatrixResultsReport
  0 / 1 (0.00%)
  1 matrices failed

┌─────────┬──────────────────────┬────────────────────────────┬───────────────────────────────────┬───────────────────────────┬─────────────────────┐
│ OUTCOME │      MATRIX ID       │          APP NAME          │          TEST FILE NAME           │      TEST AXIS VALUE      │    TEST DETAILS     │
├─────────┼──────────────────────┼────────────────────────────┼───────────────────────────────────┼───────────────────────────┼─────────────────────┤
│ failure │ matrix-2b70wos590qss │ demo-debug-androidTest.apk │ datacapture-debug-androidTest.apk │ Nexus6P-27-en_US-portrait │ 0 test cases failed │
│ failure │ matrix-2b70wos590qss │ demo-debug-androidTest.apk │ datacapture-debug-androidTest.apk │ Nexus6P-24-en_US-portrait │ 0 test cases failed │
│ failure │ matrix-2b70wos590qss │ demo-debug-androidTest.apk │ datacapture-debug-androidTest.apk │ oriole-31-en_US-portrait  │ 0 test cases failed │
└─────────┴──────────────────────┴────────────────────────────┴───────────────────────────────────┴───────────────────────────┴─────────────────────┘
More details are available at:
https://console.firebase.google.com/project/android-fhir-instrumeted-tests/testlab/histories/bh.96901a7d2453dacf/matrices/8192783254353970039


  Uploading [matrix_ids.json] to https://console.developers.google.com/storage/browser/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/...

Matrices webLink
  matrix-2b70wos590qss https://console.firebase.google.com/project/android-fhir-instrumeted-tests/testlab/histories/bh.96901a7d2453dacf/matrices/8192783254353970039
Actual shard times:
  Shard 0: Expected: 0s, Actual: 0s, Diff: 0s



Total run duration: 7m 19s
	- Preparation: 0m 2s
	- Scheduling tests: 0m 10s
	- Executing matrices: 7m 4s

> Task :datacapture:execFlank FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':datacapture:execFlank'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 10
```

2023-02-16 10:55 UTC, omarismail94 commented
@FikriMilano  I looked at the logs, and the error I see is:

```
java.lang.RuntimeException: Unable to instantiate application com.google.android.fhir.datacapture.DataCaptureTestApplication package com.google.android.fhir.datacapture.test: java.lang.ClassNotFoundException: Didn't find class "com.google.android.fhir.datacapture.DataCaptureTestApplication"
```

where any changes made to that class by any chance?

2023-02-16 11:14 UTC, FikriMilano commented
@omarismail94 thank you so much, yes I delete that by mistake.

how did you get that error log? I can't found it on my end

2023-02-16 12:54 UTC, omarismail94 commented
@FikriMilano  I got the logs in a way that can be made easier (not a priority rn). In the Kokoro [logs](https://source.cloud.google.com/results/invocations/5b373f79-d072-468c-b89b-5034b1668cdb/targets/openhealthstack%2Fandroid-fhir%2Fgcp_ubuntu%2Fpresubmit/log), there are links to the videos at the bottom. For example:

https://storage.googleapis.com/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/matrix_0/oriole-31-en_US-portrait-rerun_1/video.mp4

I just replaced the last part `video.mp4` with `logcat`:

https://storage.googleapis.com/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/matrix_0/oriole-31-en_US-portrait-rerun_1/logcat

Reading the logs, you will find towards the end a line like this:

```
FATAL EXCEPTION: main
```

with the stack trace saying that the DataCaptureTestApplication class is missing!

I think if you ran `./gradlew connectedCheck`, you would have seen the same thing. `./gradlew connectedCheck` runs the unit tests, as well as the instrumentation tests. `./gradlew check` just runs the unit tests.

2023-02-16 23:05 UTC, shelaghm commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
@FikriMilano Created a new icon for itemAnswerMedia. Attached below. Thanks!
![itemAnswerMedia](https://user-images.githubusercontent.com/86378921/219507976-4b9964c0-422a-4f6d-814a-544ad431272e.png)

2023-02-17 03:31 UTC, FikriMilano commented
@omarismail94 thanks, that's very useful actually.

because, when I ran `./gradlew connectedCheck` it gave me this, and I can't find the error of a missing class:
```
> Task :benchmark:connectedReleaseAndroidTest
Starting 14 tests on Pixel_4_API_33(AVD) - 13
Feb 17, 2023 10:23:55 AM com.google.testing.platform.RunnerImpl run
SEVERE: Test execution failed with fatal error!
com.google.testing.platform.core.driver.TestDriverException: ErrorName: TEST_EXECUTION_FAILED
NameSpace: com.google.testing.platform
ErrorCode: 4002
Message: Test execution failed on test driver <com.google.testing.platform.runtime.android.driver.AndroidInstrumentationDriver>!Test failures could be due to various issues like incorrectly configuring the driver,timeouts, incorrect test environment etc. Check logs for more info.
        at com.google.testing.platform.driver.TestDriverProxy.run(TestDriverProxy.kt:113)
        at com.google.testing.platform.executor.SingleDeviceExecutor$execute$5.invoke(SingleDeviceExecutor.kt:87)
        at com.google.testing.platform.executor.SingleDeviceExecutor$execute$5.invoke(SingleDeviceExecutor.kt:87)
        at com.google.testing.platform.executor.SingleDeviceExecutor.runUnlessCancelled(SingleDeviceExecutor.kt:105)
        at com.google.testing.platform.executor.SingleDeviceExecutor.execute(SingleDeviceExecutor.kt:87)
        at com.google.testing.platform.RunnerImpl.run(RunnerImpl.kt:108)
        at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:80)
        at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:79)
        at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
        at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
        at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy.run(NonInteractiveServerStrategy.kt:79)
        at com.google.testing.platform.main.MainKt$main$4.invokeSuspend(Main.kt:67)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.google.testing.platform.main.MainKt.main(Main.kt:66)
        at com.google.testing.platform.main.MainKt.main$default(Main.kt:34)
        at com.google.testing.platform.main.MainKt.main(Main.kt)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.google.testing.platform.launcher.Launcher.main(Launcher.java:149)
Caused by: com.google.testing.platform.api.plugin.PluginException: Exception thrown during onAfterEach invocation of plugin com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin for test case A_JacksonMapperBenchmark#loadJsonMapper.
        at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow(PluginLifecycle.kt:216)
        at com.google.testing.platform.plugin.PluginLifecycleKt.access$invokeOrThrow(PluginLifecycle.kt:1)
        at com.google.testing.platform.plugin.PluginLifecycle$onAfterEach$1.invoke(PluginLifecycle.kt:134)
        at com.google.testing.platform.plugin.PluginLifecycle$onAfterEach$1.invoke(PluginLifecycle.kt:128)
        at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
        at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
        at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
        at com.google.testing.platform.plugin.PluginLifecycle.onAfterEach(PluginLifecycle.kt:128)
        at com.google.testing.platform.executor.SingleDeviceExecutor$execute$2.invoke(SingleDeviceExecutor.kt:79)
        at com.google.testing.platform.executor.SingleDeviceExecutor$execute$2.invoke(SingleDeviceExecutor.kt:78)
        at com.google.testing.platform.result.TestResultListenerManager.afterTest(TestResultListenerManager.kt:111)
        at com.google.testing.platform.runtime.android.driver.AndroidInstrumentationDriver$InstrumentationListener.testEnded(AndroidInstrumentationDriver.kt:340)
        at com.google.testing.platform.lib.adb.command.instrument.AmInstrumentationParser.reportTestEnded(AmInstrumentationParser.kt:311)
        at com.google.testing.platform.lib.adb.command.instrument.AmInstrumentationParser.handleStatusCode(AmInstrumentationParser.kt:221)
        at com.google.testing.platform.lib.adb.command.instrument.AmInstrumentationParser.parse(AmInstrumentationParser.kt:113)
        at com.google.testing.platform.runtime.android.driver.AndroidInstrumentationDriver$runTestSuite$1.invoke(AndroidInstrumentationDriver.kt:248)
        at com.google.testing.platform.runtime.android.driver.AndroidInstrumentationDriver$runTestSuite$1.invoke(AndroidInstrumentationDriver.kt:246)
        at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController$executeAsync$deferred$1$receiver$receiver$1.processNewLines(DdmlibAndroidDeviceController.kt:134)
        at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:104)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:704)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:468)
        at com.android.ddmlib.internal.DeviceImpl.executeShellCommand(DeviceImpl.java:724)
        at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDevice.executeShellCommand(DdmlibAndroidDevice.kt)
        at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController$executeAsync$deferred$1.invokeSuspend(DdmlibAndroidDeviceController.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: com.android.ddmlib.SyncException: Remote object doesn't exist!
        at com.android.ddmlib.SyncService.pullFile(SyncService.java:341)
        at com.android.ddmlib.internal.DeviceImpl.pullFile(DeviceImpl.java:1083)
        at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDevice.pullFile(DdmlibAndroidDevice.kt)
        at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController.pull(DdmlibAndroidDeviceController.kt:254)
        at com.google.testing.platform.executor.DeviceControllerProxy$pull$2.invoke(DeviceControllerProxy.kt:82)
        at com.google.testing.platform.executor.DeviceControllerProxy$pull$2.invoke(DeviceControllerProxy.kt:82)
        at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
        at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
        at com.google.testing.platform.executor.DeviceControllerProxy.pull(DeviceControllerProxy.kt:79)
  [...]

2023-02-17 07:48 UTC, omarismail94 commented
@FikriMilano the stacktrace you posted seems to be coming from the `benchmark` module:

```
:benchmark:connectedReleaseAndroidTest FAILED
```

Could you try running:

```
./gradlew :datacapture:connectedCheck
```

this will run the instrumentation tests for the datacapture library only!

2023-02-17 12:55 UTC, FikriMilano commented
@omarismail94 woah, yep that works, thanks a lot!

2023-02-17 13:14 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="cd_item_media_image_attachment">Image attachment</string>
agreed - attachment.title is the right thing to use here.

on a separate note, we should also use attachment.width and attachment.height - but i'm happy for that to be added in a follow up pr.

2023-02-17 13:15 UTC, jingtang10 commented
> @FikriMilano I got the logs in a way that can be made easier (not a priority rn). In the Kokoro [logs](https://source.cloud.google.com/results/invocations/5b373f79-d072-468c-b89b-5034b1668cdb/targets/openhealthstack%2Fandroid-fhir%2Fgcp_ubuntu%2Fpresubmit/log), there are links to the videos at the bottom. For example:
> 
> https://storage.googleapis.com/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/matrix_0/oriole-31-en_US-portrait-rerun_1/video.mp4
> 
> I just replaced the last part `video.mp4` with `logcat`:
> 
> https://storage.googleapis.com/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/2228/20230215-233801/firebase/datacapture/matrix_0/oriole-31-en_US-portrait-rerun_1/logcat
> 
> Reading the logs, you will find towards the end a line like this:
> 
> ```
> FATAL EXCEPTION: main
> ```
> 
> with the stack trace saying that the DataCaptureTestApplication class is missing!
> 
> I think if you ran `./gradlew connectedCheck`, you would have seen the same thing. `./gradlew connectedCheck` runs the unit tests, as well as the instrumentation tests. `./gradlew check` just runs the unit tests.

@omarismail94 can you please talk about this in the next developers call thanks!

2023-02-17 13:19 UTC, jingtang10 commented on catalog/src/main/res/values/strings.xml
> +    <string name="component_name_item_media">itemMedia</string>
Happy for this to be `Item Media` - see http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-itemMedia.html.

`itemMedia` in camel case is a programming thing. in the catalog app, the normal case is a bit more readable.

same with `Item Answer Media`

2023-02-17 13:24 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal suspend fun Attachment.fetchBitmapFromUrl(context: Context): Bitmap? {
so this should be reused by item answer media as well? can you add a todo to unify the two code paths?

2023-02-17 13:31 UTC, jingtang10 approved these changes
Thanks @FikriMilano for this! Great job! 🎉🎉🎉

2023-02-17 17:27 UTC, shelaghm commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
Here is SVG @FikriMilano ![itemAnswerMedia](https://user-images.githubusercontent.com/86378921/219723292-b5797a65-c41f-4fdd-b0d0-e20e4a49974d.svg)

2023-02-20 08:37 UTC, FikriMilano commented on catalog/src/main/assets/component_text_fields.json
> +      "extension": [
Thanks!

2023-02-20 08:51 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal suspend fun Attachment.fetchBitmapFromUrl(context: Context): Bitmap? {
yeah, should be

2023-02-20 08:51 UTC, FikriMilano commented on catalog/src/main/res/values/strings.xml
> +    <string name="component_name_item_media">itemMedia</string>
updated

2023-02-20 17:22 UTC, omarismail94 commented
@FikriMilano can you merge master into this so it can be merged?

2023-02-20 20:31 UTC, merged