Implement calculated-expression extension
google/android-fhir pull request #1380
Opened 2022-05-11 06:22 UTC by maimoonak

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-12 11:01 UTC, f-odhiambo commented
@RaaziaTarique kindly take a 1st pass review

2022-05-13 13:33 UTC, RaaziaTarique approved these changes
LGTM

2022-05-16 10:10 UTC, Tarun-Bhardwaj commented
Assigning to @aditya-07 for review.

2022-05-24 09:42 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
```suggestion
  private fun runCalculatedExpressions() {
    linkIdToQuestionnaireItemMap.filter { it.value.calculatedExpression != null }
      .forEach { questionnaireItem ->
        linkIdToQuestionnaireResponseItemMap[questionnaireItem.key]?.let { questionnaireResponseItem
          ->
          questionnaireItem.value.calculatedExpression?.expression?.let { expression ->
            fhirPathEngine.evaluate(null, questionnaireResponse, null, null, expression).firstOrNull()?.let {
              val evaluatedAnswer = it.castToType(it)
              val currentAnswer = if (questionnaireResponseItem.hasAnswer()) questionnaireResponseItem.answerFirstRep.value else null
              if (!evaluatedAnswer.equalsDeep(currentAnswer)) {
                questionnaireResponseItem.answerFirstRep.value = evaluatedAnswer
              }
              // notify UI to update it value i.e. notify item changed to adapter
              viewModelScope.launch {
                if (modificationCount.value > 0) {
                  questionnaireStateFlow.collectLatest {
                    it.items
                      .indexOfFirst { it.questionnaireItem.linkId == questionnaireItem.key }
                      .let { if (it > -1) _questionnaireItemValueStateFlow.emit(it) }
                  }
                }
              }
            }
          }
        }
      }
  }
```

2022-05-24 09:42 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    detectCalculatedExpressionCyclicDependency()
Should `detectCalculatedExpressionCyclicDependency` be called  right after the `linkIdToQuestionnaireItemMap` is generated to fail early.

2022-05-24 09:42 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    runCalculatedExpressions()
This may cause expressions to be calculated again and again. Should we restrict the scope to calculate items that depend on the item being answered in this callback? cc: @jingtang10 

On another note, If a user is entering text in the answer, this callback gets called after each character is added/removed. Maybe we should add some sort of wait to let user complete typing before the callback is called (like Rx debounce). cc: @jingtang10 @stevenckngaa @yigit

2022-05-24 09:42 UTC, aditya-07 commented on catalog/src/main/assets/calculated_expression_questionnaire.json
> +      }]
Do we use this information to let user know what to input?

2022-05-24 09:42 UTC, aditya-07 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +    ),
Should the option to see Calculated expressions in the Catalog app be part of Layouts tab or maybe a new tab altogether ? cc: @santosh-pingle  @jingtang10

2022-05-30 20:58 UTC, jingtang10 requested changes
please complete the description of the PR

2022-05-31 11:00 UTC, maimoonak commented on catalog/src/main/assets/calculated_expression_questionnaire.json
> +      }]
That is a different extension which allows to give user an option to choose unit of quantity http://hl7.org/fhir/R4/extension-questionnaire-unitoption.html. This is initial https://build.fhir.org/ig/HL7/sdc/behavior.html#initial where we can make type quantity as initial without value for unit reference purpose. This makes it default to the unit type specified in initial

2022-05-31 13:09 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
Made the suggested changes, however, two important points
- We can not skip null evaluations, so even if answer is null or empty we do set the value to erase the  previous calculated value 
- To prevent loop back we do verify that the new answer is not same as previous one. A dependents value change may not necessarily update the value. For e.g. if we calculate age in years from birthdate changing dates may not update age unless age changes its digit, similarly if we are ignoring decimals for any calculated value we may have same value as previous one.

2022-05-31 13:16 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    runCalculatedExpressions()
Moved the calculation after state has been updated and ready to be rendered. This would prevent some of the extra calls.
For debounce the delay may not work each case. For e.g. automation script can change value in millis and can submit form, and then we would end up missing the calculations, a QA user submit forms very quickly and the actual user may take 1 sec pause for each character. I also checked the isFocused, isActivated, but nothing seems to be relevant. The code for calculations prevents the unnecessary updates to some extent. The dependency graph generation is a bit tricky as calculation-expression could be anything, sum of multiple widgets, referring other items by linkId or by their value types etc, or other variables. User should be aware that using too much calculations can impact performance.
Any suggestions!

2022-05-31 21:22 UTC, maimoonak commented
@jingtang10 @aditya-07 Please review the changes

2022-06-15 11:51 UTC, Tarun-Bhardwaj commented
@aditya-07 @jingtang10 could you please review the changes?

2022-07-01 11:23 UTC, aditya-07 approved these changes
Small nit otherwise LGTM!

2022-07-01 11:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        )
Can we use `kotlin.check` here see https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html.

2022-07-01 16:37 UTC, jingtang10 requested changes
Can you attach a screenshot please?

@shelaghm not sure if we want to show case this in the layout screen of the catalog app... i kind feel like this is better off in the components page... that is if we want to showcase this at all.

2022-07-01 16:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
nit: please revert this change. this makes the history look weird.

2022-07-01 16:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
nit: same here. please revert.

2022-07-01 16:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    runCalculatedExpressions()
can you move this before line 153?

2022-07-01 16:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  internal val questionnaireItemValueStateFlow = _questionnaireItemValueStateFlow.asSharedFlow()
i kinda don't understand why these new stateflows are needed? can the modificationCount not be used in order to refresh the UI?

2022-07-01 16:38 UTC, jingtang10 commented
@joiskash can you please leave a review? thanks!

2022-07-01 16:58 UTC, shelaghm commented
> Can you attach a screenshot please?
> 
> @shelaghm not sure if we want to show case this in the layout screen of the catalog app... i kind feel like this is better off in the components page... that is if we want to showcase this at all.

I agree that it's likely more useful to show in components page, not layout page. Having a screenshot that I can look at of this components will he helpful for me to provide more specific guidance.

2022-07-04 11:00 UTC, joiskash requested changes
Nice work! Left a few comments

2022-07-04 11:00 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun detectCalculatedExpressionCyclicDependency(
This seems like it could be moved to a function similar to checkQuestionnaireResponse in the QuestionnaireResponseValidator. Just a suggestion, does not have to be done.

2022-07-04 21:47 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  internal val questionnaireItemValueStateFlow = _questionnaireItemValueStateFlow.asSharedFlow()
yes. it is needed because 1- _questionnaireItemValueStateFlow does not update and notify list unless item count is changed (a question is hidden/shown)  2- item value update notification is not triggered in every case, rather it is updated only if value is changed from previous one. For ex: calculation of age from birthdate can lead to same value for all/most birthdates of a year, which means age input should on;y be notified iff age value is updated. (see L#235-240). So in short this calculation and its value event is notified only in specific case and not with every modificationCount++

2022-07-04 21:49 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    }
yes, we need to do so. The list does not update the value unless a question is shown / hidden. This leads to notify item change which leads to item update in UI. Without this item value is not updated

2022-07-04 21:52 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun detectCalculatedExpressionCyclicDependency(
This method runs only on questionnaire items and does not have any link with questionnaireResponse. It runs only once for each questionnaireItem having the extension 'calculated-expression'

2022-07-04 23:24 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +            ?.localizedString
yes. If not fixed it throws following exception on initialization of dateType value. 
```
java.lang.NullPointerException: year must not be null
        at com.google.android.fhir.datacapture.views.QuestionnaireItemDatePickerViewHolderFactoryKt.getLocalDate(QuestionnaireItemDatePickerViewHolderFactory.kt:148)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemDatePickerViewHolderFactory$getQuestionnaireItemViewHolderDelegate$1.bind(QuestionnaireItemDatePickerViewHolderFactory.kt:85)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemViewHolder.bind(QuestionnaireItemViewHolderFactory.kt:65)
        at com.google.android.fhir.datacapture.QuestionnaireItemAdapter.onBindViewHolder(QuestionnaireItemAdapter.kt:99)
```

2022-07-05 00:07 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        ->
there is a variables PR for #1059 where @shoaibmushtaq25 is working for performance optimization of expressions. The calculated expression depends on variables as well, and any random valid expression as well. So building a tree is not straight forward. We are detecting cyclic dependency tree which would not allow endless loop, and we are also breaking the circuit by stopping the update notification if value is not updated. https://build.fhir.org/ig/HL7/sdc/expressions.html#calculatedExpression and https://build.fhir.org/ig/HL7/sdc/expressions.html#dependencies does not give any clear direction on this as well. We can work on this as separate ticket once variables PR is also merged and we are done evaluating different use cases.
Also we can have uses cases when we depend on multiple items for calculation without inclusion of linkId. For e.g. To calculate risk score based on 10 questions for covid health survey we may use expression like following

`%resource.descendants().where(linkId='group-id').select(answer.value).where(code='yes').count()`

The group for covid danger signs can have 10 danger signs and based on yes for each we may calculate risk score. Simialry I have seen a similar example in a metal health survey. 
This performance optimization would need a thorough analysis.

There is one more condition that needs to be implemented " If a user has edited a calculated value, it should no longer be changed when other answers in the questionnaire response change". Do we have a way to know if an input was updated by user or program?

2022-07-20 14:03 UTC, Tarun-Bhardwaj commented
@maimoonak could you please advise an ETA by when these changes can be ready for review?

2022-07-20 14:40 UTC, maimoonak commented
@Tarun-Bhardwaj I have resolved all conflicts with main, synced the code with new changes as well just now. 
The issue https://github.com/google/android-fhir/issues/1498 needs to be resolved to run the catalog (without extra needless edit-text). But this PR and functionality does not depend on this issue and is working as expected. (Below is a working example)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4829880/180010510-5d26a9ba-25d9-46d1-a3a0-7dddf413a5cd.gif)

2022-08-23 05:39 UTC, Tarun-Bhardwaj commented
@maimoonak , could you please advise the status of these changes? Is there an ETA by when we can merge this PR?

2022-09-05 06:04 UTC, maimoonak commented
@Tarun-Bhardwaj @jingtang10 kindly review the PR.

2022-09-09 13:43 UTC, jingtang10 requested changes

2022-09-09 13:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +   * expression extension, which is dependent on value of updated response
can you please rephrase this? not quite clear to me.

2022-09-09 13:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  return this + this.flatMap { if (it.hasItem()) it.item.flattened() else it.item }
i don't think you need the if else here. if the condition in the`if` clause is false, `it.item` will always evaluate to empty list.

2022-09-09 13:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +          modifiedResponses.none { it.linkId == item.linkId } &&
add a comment to say why this condition is needed.

2022-09-09 13:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                .isEmpty())
can you extract this into a small private helper function in this class.

also feels like you should be able to use `zip` instead of `filterIndexed`.

2022-09-14 10:16 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                .isEmpty())
simplified the logic using zip

2022-09-15 12:08 UTC, jingtang10 commented
can you please make sure to reply to the review comments and mark the conversations as resolved if the comment is addressed in the code. once that's done please reassign back to me. thanks

2022-09-16 10:43 UTC, jingtang10 requested changes

2022-09-22 10:08 UTC, jingtang10 commented
@maimoonak please reassign to me once all comments are addressed

2022-09-30 10:39 UTC, jingtang10 requested changes
i quite strong feel at this point we should create a dependency graph for expressions. the logic in your evaluator is getting very complex with part of it handling finding dependency and part of it handling the actual evaluation of variables.

i think we could possibly merge this without this change. but it will need to be an immediate refactoring i think.

2022-09-30 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> + * Check if given [item] has calculable expression based extension and is referencing current item
```suggestion
 * Whether [item] has any expression directly referencing the current questionnaire item by link ID (e.g. if [item] has an expression `%resource.item.where(linkId='this-question')` where `this-question` is the link ID of the current questionnaire item).
```

2022-09-30 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +        // 3- item answer depends on the updated item answer OR has a variable dependency
why do you also recalculate everything that has a variable dependency?

2022-09-30 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +      .map { calculable ->
i would prefer it if we refrain from introducing new terminology without defining them properly.

can we just use `questionnaireItem`?

2022-09-30 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun runCalculations(updatedQuestionnaireItem: Questionnaire.QuestionnaireItemComponent) {
I think a much better name for this function is `updateDependentQuestionnaireResponseItems`. and please add documentation to explain.

2022-09-30 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +          modifiedResponses.none { it.linkId == item.linkId } &&
actually this won't work. please remove `modifiedResponses` from the function signature of this function, and do this check in the `QuestionnareViewModel` (around line 387).

this is because the modified responses actually include response items... it's not a set of questionnaire items.

2022-09-30 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          questionnaireResponseItemPreOrderList.find { it.linkId == updatedCalculable.first.linkId }
you probably should use `findAll` instead of `find`, because you want to update all questionnaire response items with the same link id (meaning they originate from the same questionnaire item with the link id).

2022-10-07 07:47 UTC, jingtang10 requested changes

2022-10-07 07:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun runCalculations(updatedQuestionnaireItem: Questionnaire.QuestionnaireItemComponent) {
please still do this

2022-10-07 07:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +          modifiedResponses.none { it.linkId == item.linkId } &&
discussed with @maimoonak, what should happen here is:

drop a questionnaire item, if all the questionnaire response items with the same link id have been modified (i.e. present in the modified set).

2022-10-10 14:43 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +        // 3- item answer depends on the updated item answer OR has a variable dependency
as discussed in call, the variable dependency is not predictable. We want to evaluate all variables to ensure nothing is missed out

2022-10-10 17:40 UTC, maimoonak commented
@jingtang10 I have found few libraries for graph generation. I am still exploring these and if its possible to use any for our expression dependency graph
https://github.com/systek/dataflow
https://github.com/jgrapht/jgrapht/
https://github.com/google/guava/wiki/GraphsExplained
https://github.com/nidi3/graphviz-java#user-content-api

2022-10-11 17:47 UTC, jingtang10 approved these changes

2022-10-12 17:30 UTC, merged