Fix FHIR Engine search sort for DateTime properties
google/android-fhir pull request #1384
Opened 2022-05-11 08:31 UTC by ekigamba

Fixes #1363

**Description**
Implements a double-join to the tables `DateTimeIndexEntity` and `DateIndexEntity` whenever a DateClientParam sort is requested

**Alternative(s) considered**
Yes, a number of alternatives were considered and discussed [here](https://docs.google.com/document/d/1ALYulBGNwSg-Agqbx4qcgOaAVtUg70GXL_mOTnN5v1s/edit#) namely:
- Merging the two tables into 1
- Generating code to hint/guide on the right table depending the the sort property
- Add a DateTimeClientParam

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-16 07:52 UTC, Rkareko approved these changes

2022-05-16 09:36 UTC, Tarun-Bhardwaj commented
@ekigamba , when can we expect this PR to get completed?

2022-05-16 11:58 UTC, ekigamba commented
@Tarun-Bhardwaj This PR is complete

2022-05-18 12:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/DateTimeClientParam.kt
> +class DateTimeClientParam(theParamName: String) : DateClientParam(theParamName)
This might not be intuitive to the app developers that they need to pass DateTimeClientParam for date & time in the search sort function . Also they will have to re-define the `DateClientParam` define in hapi lib as a `DateTimeClientParam` now.

 ```
fun sort(parameter: DateClientParam, order: Order) {
    sort = parameter
    this.order = order
  }
```
One way to handle date-time could be to pass a boolean param in the `sort` indicating the type of search i.e Date or DateTime.
Any thoughts @jingtang10 ?

2022-05-18 14:12 UTC, ekigamba commented on engine/src/main/java/com/google/android/fhir/search/DateTimeClientParam.kt
> +class DateTimeClientParam(theParamName: String) : DateClientParam(theParamName)
Thanks for bringing it up:

1. We can have below function to make it more intuitive
```
  fun sort(parameter: DateTimeClientParam, order: Order) {
    sort = parameter
    this.order = order
  }
```

2. Do we really need to define `DateTimeClientParam` in the hapi lib since this is only used for sorting on this lib? Having extended `DateClientParam` means it can be reused for other places where `DateClientParam` is supposed to be used without changing the code to accomodate the new class. It's only role will be better readability when passed as a param in other `DateClientParam` functions

Alternatively, we can use a boolean as you stated. This will require us to track the boolean and have it as a class property of `Search` that will only be used whenever the sort param is a `DateClientParam`

2022-05-23 14:10 UTC, jingtang10 commented
discussed this on thursday (@f-odhiambo @ekigamba @aditya-07 @maimoonak). the root problem is the fact that there is only 1 type of search param for both date and datetime indices, but at run time we don't know which index table to join.

we talked about 2 options:

1. merge date index table with datetime index table.
2. update the generated code so that there's a hint as to which params are for date index and which are for datetime index.

@ekigamba can you investigate these 2 options a little bit and discuss the pros and cons so we can make a decision? thanks

2022-06-15 11:52 UTC, Tarun-Bhardwaj commented
> discussed this on thursday (@f-odhiambo @ekigamba @aditya-07 @maimoonak). the root problem is the fact that there is only 1 type of search param for both date and datetime indices, but at run time we don't know which index table to join.
> 
> we talked about 2 options:
> 
> 1. merge date index table with datetime index table.
> 2. update the generated code so that there's a hint as to which params are for date index and which are for datetime index.
> 
> @ekigamba can you investigate these 2 options a little bit and discuss the pros and cons so we can make a decision? thanks

@ekigamba , did you get a chance to work on the comments provided by @jingtang10 ?

2022-06-15 12:57 UTC, ekigamba commented
> > discussed this on thursday (@f-odhiambo @ekigamba @aditya-07 @maimoonak). the root problem is the fact that there is only 1 type of search param for both date and datetime indices, but at run time we don't know which index table to join.
> > we talked about 2 options:
> > 
> > 1. merge date index table with datetime index table.
> > 2. update the generated code so that there's a hint as to which params are for date index and which are for datetime index.
> > 
> > @ekigamba can you investigate these 2 options a little bit and discuss the pros and cons so we can make a decision? thanks
> 
> @ekigamba , did you get a chance to work on the comments provided by @jingtang10 ?

Yea, in progress. Investigating both and how Hapi FHIR server handles this currently

2022-07-05 17:04 UTC, jingtang10 commented
https://github.com/google/android-fhir/issues/1363#issuecomment-1175075572

2022-07-18 08:31 UTC, Rkareko approved these changes

2022-07-20 15:09 UTC, jingtang10 requested changes

2022-07-20 15:09 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    }
this code is very procedural and difficult to read - i think what should happen is for the `when` clause on line 65, you sould return a list of `SortTableInfo`s. And for each of them, you add the join statement and the sort order statement. that way it's much clearer.

so in this case or the `DateClientParam`, you just need to add both date and datetime tables.

2022-07-22 17:35 UTC, jingtang10 requested changes
just one comment on test - otherwise good to go

2022-07-22 17:35 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +
is this test case superfulous because you already had the two test cases before?
```suggestion

```

2022-07-22 17:41 UTC, jingtang10 requested changes

2022-07-22 17:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        is DateClientParam ->
actually add a comment here:
```suggestion
        // The DateClientParam maps to two index tables (Date without timezone info and DateTime with timezone info). Any data field in any resource will only have index records in one of the two tables. So we simply sort by both in the SQL query.
        is DateClientParam ->
```

2022-07-25 07:18 UTC, ekigamba commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    }
I have made the changes as requested. However, I think that the `forEachIndexed` can be confusing since it makes it seem as if the engine allows multiple sort params. It is also not clear that the are implemented for an exception. The for loops feel like generic solutions while they help fix the issue for 1 exception.

2022-07-25 14:20 UTC, ekigamba commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +
yes

2022-07-25 14:21 UTC, ekigamba commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        is DateClientParam ->
Yes

2022-07-25 18:26 UTC, jingtang10 approved these changes
thanks @ekigamba

2022-07-25 18:26 UTC, merged

2022-07-26 09:57 UTC, ekigamba commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    }
@jingtang10