throw exception if both initial value and expression present in QuestionnaireItem
google/android-fhir pull request #1385
Opened 2022-05-11 08:37 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1297

**Description**
IllegalArgumentException is thrown if inital value and intial value expression are present in QuestionnaireItem

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-13 09:16 UTC, aditya-07 reviewed
Nits

2022-05-13 09:16 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    ) {
```suggestion
    if (questionnaireItem.initialExpression?.isEmpty == false
     && questionnaireItem.initial.isNotEmpty()) {
```

2022-05-13 09:16 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        "Questionnaire item have both initial value and initial expression. See rule at http://build.fhir.org/ig/HL7/sdc/expressions.html#initialExpression."
```suggestion
        "Questionnaire.item is not allowed to have both initial.value and initialExpression. See rule at http://build.fhir.org/ig/HL7/sdc/expressions.html#initialExpression."
```

2022-05-13 09:16 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalArgumentException when QuestionnaireItem have both initial value and expression`():
```suggestion
  fun `populate() should fail with IllegalArgumentException when QuestionnaireItem has both initial value and initialExpression`():
```

2022-05-18 10:06 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    ) {
done

2022-05-18 10:20 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalArgumentException when QuestionnaireItem have both initial value and expression`():
done

2022-05-23 17:15 UTC, jingtang10 requested changes

2022-05-23 17:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
use Kotlin's `check`: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html

2022-05-23 17:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
i think for initial expression we should be checking `initialExpression` isn't null.

2022-05-26 10:04 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
Done

2022-06-03 11:19 UTC, jingtang10 requested changes

2022-06-03 11:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        questionnaireItem.initialExpression!!.isEmpty
```suggestion
      questionnaireItem.hasInitial() ||
        questionnaireItem.initialExpression == null ||
        questionnaireItem.initialExpression!!.isEmpty
```

2022-06-03 11:19 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has initial value and empty initialExpression`():
surely this test case would fail due to line 203 in `ResourceMapper.kt`???

2022-06-03 11:19 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has empty initial value and value for initialExpression`():
remove this test case if we're using `hasIntial` as per comment above

2022-06-03 11:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        questionnaireItem.initialExpression!!.isEmpty
again. not super sure we want line 203 - if you read the rule it doesn't say non-blank or non-empty expression. so i think we can remove line 203.

2022-06-03 17:32 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        questionnaireItem.initialExpression!!.isEmpty
Done

2022-06-03 17:33 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    assertFailsWith<IllegalStateException> { ResourceMapper.populate(questionnaire, patient) }
Done

2022-06-03 17:39 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has empty initial value and value for initialExpression`():
Done

2022-06-03 17:57 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        questionnaireItem.initialExpression!!.isEmpty
I did not get the suggested change from  questionnaireItem.initial.isEmpty() to questionnaireItem.hasInitial(). As per my understanding its contradicting to to the requirement

2022-06-04 10:45 UTC, jingtang10 approved these changes
thanks @PallaviGanorkar!

just final 3 comments - i really think with the latest change you only need to keep 1 test case.

2022-06-04 10:45 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has empty initial value and value for initialExpression`():
remove this please.

2022-06-04 10:45 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has initial value and empty initialExpression`():
remove this test case

2022-06-04 10:45 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has initial value and null initialExpression`():
remove this test case.

2022-06-06 11:19 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has initial value and empty initialExpression`():
Done

2022-06-06 11:19 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem has empty initial value and value for initialExpression`():
Done

2022-06-06 11:34 UTC, jingtang10 approved these changes

2022-06-06 11:34 UTC, jingtang10 approved these changes

2022-06-13 08:30 UTC, merged