Accept IntegerType in FHIR questionnaire for DecimalType
google/android-fhir pull request #1392
Opened 2022-05-13 02:40 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1219

**Description**
Internally IntegerType is converted to DecimalType

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-13 08:53 UTC, aditya-07 reviewed
Add tests for it.

2022-05-13 12:33 UTC, PallaviGanorkar commented
> Add tests for it.

Yes i am working on it

2022-05-16 12:53 UTC, jingtang10 requested changes

2022-05-16 12:53 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract_updateIntegerObservationForDecimalDefination_shouldUpdateAsDecimal() `() =
can you use a minimum test case?

2022-06-06 12:50 UTC, jingtang10 approved these changes
Thanks Pallavi! 🙏

2022-06-06 12:56 UTC, merged