Change database insert to insertOrUpdate, change insert onConflictStrategy from REPLACE to IGNORE
google/android-fhir pull request #1393
Opened 2022-05-13 07:08 UTC by wantingzhang77

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1172

**Description**
Change the database insert onConflictStrategy from "REPLACE" to "IGNORE"

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health 

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-13 18:11 UTC, yigit requested changes
can we also add some tests that would fail w/o this change so that if in the future someone reverts this, tests will catch?

2022-05-13 18:11 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  abstract suspend fun insertResourceEntity(resourceEntity: ResourceEntity): Long
i'm guessing the goal here is to never call these methods directly but instead call the new methods that delegate.
if so, lets make these protected so they cannot be called from outside.

2022-05-13 18:33 UTC, wantingzhang77 commented
Hi @yigit 
I am seeing testing error from the test of createAll_shouldCreateResource(). The error message is:
```
com.almworks.sqlite4java.SQLiteException: [787] DB[1] reset [FOREIGN KEY constraint failed]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1409)
	at com.almworks.sqlite4java.SQLiteConnection.cacheStatementHandle(SQLiteConnection.java:1338)
	at com.almworks.sqlite4java.SQLiteConnection.access$900(SQLiteConnection.java:51)
	at com.almworks.sqlite4java.SQLiteConnection$CachedController.dispose(SQLiteConnection.java:1733)
	at com.almworks.sqlite4java.SQLiteStatement.dispose(SQLiteStatement.java:187)
	at org.robolectric.shadows.ShadowLegacySQLiteConnection$Connections$5.call(ShadowLegacySQLiteConnection.java:551)
	at org.robolectric.shadows.ShadowLegacySQLiteConnection$Connections$5.call(ShadowLegacySQLiteConnection.java:548)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
I don't quit understand it. Is this some concurrent related issue? Do you think I missed anything in the code changing the "insert" to "insertOrUpdate".

2022-05-13 19:44 UTC, wantingzhang77 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  abstract suspend fun insertResourceEntity(resourceEntity: ResourceEntity): Long
> can we also add some tests that would fail w/o this change so that if in the future someone reverts this, tests will catch?

Room use `onConflictStrategy` to deal with conflict, and conflict happens only when 2 rows has the same "PrimaryKey". Now the PrimaryKey is auto generated using `@PrimaryKey(autoGenerate = true) val id: Long,` and it is hard to create test cases of 2 entities with same PrimaryKey.

In my opinion, the conflict won't happen in current FHIR Library with auto-gen PrimaryKey unless if there's any weird glitch in the system. But change "REPLACE" to "IGNORE" is a good practice for database manipulation. So maybe we don't need extra test for this? I can add comment in the code saying REPLACE should be avoided in room incase of any further change.

2022-05-18 12:47 UTC, aditya-07 commented
> Hi @yigit I am seeing testing error from the test of createAll_shouldCreateResource(). The error message is:
> 
> ```
> com.almworks.sqlite4java.SQLiteException: [787] DB[1] reset [FOREIGN KEY constraint failed]
> 	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
> 	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1409)
> 	at com.almworks.sqlite4java.SQLiteConnection.cacheStatementHandle(SQLiteConnection.java:1338)
> 	at com.almworks.sqlite4java.SQLiteConnection.access$900(SQLiteConnection.java:51)
> 	at com.almworks.sqlite4java.SQLiteConnection$CachedController.dispose(SQLiteConnection.java:1733)
> 	at com.almworks.sqlite4java.SQLiteStatement.dispose(SQLiteStatement.java:187)
> 	at org.robolectric.shadows.ShadowLegacySQLiteConnection$Connections$5.call(ShadowLegacySQLiteConnection.java:551)
> 	at org.robolectric.shadows.ShadowLegacySQLiteConnection$Connections$5.call(ShadowLegacySQLiteConnection.java:548)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> I don't quit understand it. Is this some concurrent related issue? Do you think I missed anything in the code changing the "insert" to "insertOrUpdate".

Docs in the `DatabaseImplTest` suggest that the Robolectric's SQLite implementation does not match Android's and hence it should be run as Integration test. Maybe moving `FhirEngineImplTest` to instrumentation tests may help with this issue.

2022-12-05 10:16 UTC, omarismail94 commented
Closing this PR:
https://github.com/google/android-fhir/issues/1172#issuecomment-1337082049

2022-12-05 10:16 UTC, closed without merging