configuration added for HTTP Client timeouts
google/android-fhir pull request #1394
Opened 2022-05-16 18:13 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1316

**Description**
connectTimeout, readTimeout, writeTimeout configuration added for HTTP client 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-16 20:09 UTC, vitorpamplona approved these changes

2022-05-18 12:20 UTC, aditya-07 requested changes

2022-05-18 12:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  val connectionTimeOut: Long = 10,
```suggestion
/** Connection timeout (in seconds). The default is 10 seconds. */
  val connectionTimeOut: Long = 10,
```

2022-05-18 12:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  val writeTimeOut: Long = 10
Add individual kdocs.

2022-05-18 12:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> + */
```suggestion
/** A configuration to provide the network connection parameters.*/
```

2022-05-18 12:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +data class NetworkConfiguration(
Would it make sense for this to be part of `ServerConfiguration` ? @jingtang10 
Like 
```
ServerConfiguration(
  val baseUrl: String, 
  val networkConfiguration NetworkConfiguration = NetworkConfiguration(),
  val authenticator: Authenticator? = null
) 
```

2022-05-18 12:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirServices.kt
> +    private var networkConfiguration: NetworkConfiguration = NetworkConfiguration()
Let's keep it nullable and pass a default value during `build()` if its not set.

2022-05-18 12:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/remote/RemoteFhirService.kt
> +  ) {
```suggestion
  class Builder(
    private val baseUrl: String
  ) {
  
  fun setNetworkConfiguration(networkConfiguration NetworkConfiguration) {}
```

2022-05-19 15:09 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  val writeTimeOut: Long = 10
Done

2022-05-19 15:10 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> + */
Done

2022-05-30 14:03 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +data class NetworkConfiguration(
i think this makes sense

2022-05-31 08:28 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +data class NetworkConfiguration(
DOne

2022-06-08 12:14 UTC, aditya-07 approved these changes
LGTM!

2022-06-08 20:14 UTC, merged