Tests for Compiling CQL with Roboelectric
google/android-fhir pull request #1395
Opened 2022-05-17 17:57 UTC by vitorpamplona

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Starts to fix #1365

**Description**
Adds short tests to compile CQL into ELM, assemble ELM into a FHIR Library and making a FHIR Bundle from it. 

**Alternative(s) considered**
No

**Type**
Testing

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-05-18 12:36 UTC, ktarasenko approved these changes
Great one!

2022-05-18 12:36 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLBuilderUtils.kt
> +    Truth.assertThat(translator.errors).isEmpty()
nit: add static import for assertThat

2022-05-18 12:36 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLBuilderUtils.kt
> +class CQLBuilderUtils {
can be an object

2022-05-18 12:36 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +@RunWith(RobolectricTestRunner::class)
I think it's suggested to use  AndroidJUnit4::class instead 
http://robolectric.org/androidx_test/

2022-05-18 12:36 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +  fun load(assetName: String): String {
throw an exception if the loading failed

2022-05-18 15:16 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLBuilderUtils.kt
> +class CQLBuilderUtils {
Done

2022-05-18 15:17 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +@RunWith(RobolectricTestRunner::class)
We are using Roboelectric on every other test in this repo. I am not sure which one is best..

2022-05-18 15:17 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +  fun load(assetName: String): String {
Done

2022-06-21 13:47 UTC, pld commented
is there anything blocking this from getting merged? we're going to add some test cases on top if this pr

2022-06-28 17:05 UTC, jingtang10 requested changes
Thanks Vitor!

2022-06-28 17:37 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLBuilderUtils.kt
> +    val elmLibrary = parseElm(strLib)
Because we need the `strLib` as a String to put the original bytes into the FHIR Library in the line below.

2022-06-28 17:45 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +    val library = CQLBuilderUtils.compile(open("/cql-compiler/FHIRHelpers-4.0.1.cql"))
Ideally, the utility class should not know how to open a file that is relative to the current test class. That's why it always takes an `InputStream` instead.

2022-06-28 17:54 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +  }
They also test if the Build function is correctly building FHIR Libraries with CQL content in it. For instance, the name of the library inside the CQL file MUST be equal to the FHIR Library's name.

2022-06-28 19:28 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLBuilderUtils.kt
> +
I initially added them as utility functions for others. But you are right, they are not needed at this moment. Thus I deleted them.

2022-07-04 13:08 UTC, jingtang10 commented on workflow/src/test/java/com/google/android/fhir/workflow/CqlBuilderUtils.kt
> +  }
make this inline?

```
fun compileAndBuild(stream) =
  compile(stream).let {
    it.toJxson(),
    it....,
    it...
  }
```

2022-07-07 14:04 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/CQLCompilerTest.kt
> +  }
Makes sense. I deleted it.

2022-07-07 15:26 UTC, jingtang10 approved these changes
I think we should do more work on documentation. How can this be used by developers? What advantages/disadvantages? Let's consider improving the github wiki regarding this?

For now this PR itself is fine.

thanks vitor

2022-08-22 08:07 UTC, Tarun-Bhardwaj commented
@vitorpamplona , since the PR has been approved, when do we intend to merge these changes?

2022-08-25 05:00 UTC, Tarun-Bhardwaj commented
> @vitorpamplona , since the PR has been approved, when do we intend to merge these changes?

@vitorpamplona , since the PR is approved, when can the changes get merged?
CC: @jingtang10

2022-10-10 15:37 UTC, closed without merging