Support Stringtype, Integertype as answer option type when item type is choice.
google/android-fhir pull request #1399
Opened 2022-05-18 13:35 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1360 

**Description**

- Support `IntegerType` and `StringType` as answer option type when item type is `Choice`.
- QuestionnaireResponse will always have answerOption type as Coding when item type is choice.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-16 12:53 UTC, jingtang10 requested changes
can you please add `integer|date|time|string|Coding|Reference(Any)` as per the spec.

2022-06-21 17:18 UTC, jingtang10 requested changes
Santosh can you also implement this: https://github.com/google/android-fhir/issues/1360#issuecomment-1157550094

2022-06-21 17:19 UTC, jingtang10 commented
@santosh-pingle this is now a high priorty item - thanks for fixing this.

2022-06-22 10:15 UTC, santosh-pingle commented
in progress.

2022-06-30 10:01 UTC, jingtang10 requested changes

2022-06-30 10:01 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +      else -> throw IllegalArgumentException("$value is not supported.")
test this

2022-07-01 10:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +      else -> throw IllegalArgumentException("$value is not supported.")
To test else part, it is required to set value of `QuestionnaireItemAnswerOptionComponent` with not supported type, if you do so then fhir library api throws error.
` throw new Error("Not the right type for Questionnaire.item.answerOption.value[x]: "+value.fhirType());`

2022-07-01 12:52 UTC, jingtang10 approved these changes
thanks @santosh-pingle

2022-07-01 12:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +      else -> throw IllegalArgumentException("$value is not supported.")
ok so the `QuestionnaireItemAnswerOptionComponent` class doesn't allow you to set a type that's not one of the types here. so it's sort of non-strict type safety. got it.

2022-07-01 13:15 UTC, merged