Create a questionnaire list page to display all the sample questionnaires
google/android-fhir pull request #144
Opened 2021-01-11 18:02 UTC by jingtang10

closes #143

2021-01-12 07:42 UTC, kashyapj2793 approved these changes

2021-01-12 19:46 UTC, yigit commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +    questionnaire.title = intent.getStringExtra(QUESTIONNAIRE_TITLE_KEY)
this can move into a view model that receives the saved state as a parameter.
then it can get the extras from that saved state handle and hold onto the created questionaire.

this will allow rotation handling.
https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate

it can also put the temporary information (user input)

2021-01-12 19:47 UTC, yigit commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +    val fragment = QuestionnaireFragment(questionnaire)
this "might" cause problem on state restoration as we might be adding more fragments. though right now fragment manager cannot create questionaire fragment (due to constructor argument) so i'm not sure what happens there (whether it crashes or drops the fragment)

2021-01-15 00:27 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +    questionnaire.title = intent.getStringExtra(QUESTIONNAIRE_TITLE_KEY)
done

2021-01-15 00:28 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +    val fragment = QuestionnaireFragment(questionnaire)
@kashyapj2793 is addressing this in #148

2021-01-15 00:28 UTC, jingtang10 reviewed
thanks yigit - ptal!

2021-01-15 16:51 UTC, yigit requested changes

2021-01-15 16:51 UTC, yigit commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/DataCaptureGalleryApplication.kt
> +        mContext = this
we don't use m prefix in kotlin, it is only in java.

2021-01-15 16:51 UTC, yigit commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +class QuestionnaireViewModel(private val state: SavedStateHandle) : ViewModel() {
you can extend AndroidViewModel, which can receive the application as a parameter.
that way, you don't need the static context in the application class.

2021-01-15 17:45 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/DataCaptureGalleryApplication.kt
> +        mContext = this
done

2021-01-15 17:45 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +class QuestionnaireViewModel(private val state: SavedStateHandle) : ViewModel() {
done

2021-01-18 17:01 UTC, deepankarb approved these changes

2021-01-18 17:04 UTC, merged