WIP configured Date picker to pick min and max value dates from exten…
google/android-fhir pull request #1442
Opened 2022-06-07 06:28 UTC by aurangzaibumer

…sion to make a range

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1040 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-14 09:59 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidator.kt
> +      answer.value > getExtensionValue(extension)
checked, this is inclusive. Also checked the Json by adding dates of today minus day & today plus day. 
http://hl7.org/fhir/R4/extension-minvalue.html

2022-06-14 10:21 UTC, aurangzaibumer commented on demo/src/main/assets/new-patient-registration-paginated.json
> +                  {
`  "extension" : [
              {
                "url" : "http://hl7.org/fhir/StructureDefinition/minValue",
                "valueDecimal" : 1,
                "_valueDecimal" : {
                  "extension" : [
                    {
                      "url" : "http://hl7.org/fhir/StructureDefinition/cqf-calculatedValue",`

I checked this from here https://build.fhir.org/ig/HL7/sdc/examples.html#cqf - please correct me if i'm wrong. thanks

2022-06-14 10:23 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +  return result!!
MoreQuestItemComp is returning exlusively a DateType, here we are returning as a Type so we don't have to case it on the DatePickerFactory as DateType because it needs a dateType. Please let me know if you have a better idea on this. thanks

2022-06-29 12:50 UTC, jingtang10 requested changes
thanks!

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  val fhirPathEngine: FHIRPathEngine =
revert this change.

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +      ResourceMapper.fhirPathEngine
create your own fhir path engine in this file.

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +                        expression = "today() - 1 'days'"
i think this would not be necessarily stable. is there a way for you to make this more stable?

can you set the system date in the test or something? try this: https://www.baeldung.com/java-override-system-time

2022-06-29 12:50 UTC, jingtang10 commented on demo/src/main/assets/new-patient-registration-paginated.json
> +            },
revert this change.

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +    extension.value.extension.firstOrNull()?.let {
you need to check the extension has the url: CQF_CALCULATED_EXPRESSION_URL

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +internal fun getExtensionValue(extension: Extension): Type {
i think it might be better to move this out of this file. just create a util file in the same package.

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +internal fun getExtensionValue(extension: Extension): Type {
can you change this to an extension property?

```
internal val Type.valueOrCalculatedValue
```

and then when you need to use this you do:

```
extension.value.valueOrCalculatedValue
```

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput() {
can you add a test case where this would fail?

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            setValue(DateType(2025, 0, 1))
please change this to something stable.

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +}
can you make sure this logic is in the validators, and maybe open up some internal functions.

and then when you're using this in the view holder factory you can just do a cast.

2022-06-29 12:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        val min = questionnaireItemViewItem.questionnaireItem.minimumValueForDate()?.value?.time
this should look like this:

```
val min = MinValueConstraintValidator.getMinValue(questionnaireItemViewItem.questionnaireItem) as Date
```

2022-07-22 11:53 UTC, aurangzaibumer commented
https://user-images.githubusercontent.com/35099184/180433662-5c6fde87-bbcf-4558-b2f7-ad1d47f7eeb7.mp4

I've resolved _non-test case classes_ feedback, can you please review so that i can move to resolve the unit test cases. thanks in advance. @jingtang10 

cc @f-odhiambo

2022-07-26 11:29 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValidationUtil.kt
> +  internal val fhirPathEngine: FHIRPathEngine =
Make this `private` as this is only used in this file.
```suggestion
  private val fhirPathEngine: FHIRPathEngine =
```

2022-07-26 11:33 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValidationUtil.kt
> +      ValidationUtil.fhirPathEngine.evaluate(this, expression).firstOrNull()?.let { it as Type }
and change it from `ValidationUtil.fhirPathEngine.evaluate` to `fhirPathEngine.evaluate`

2022-07-26 11:36 UTC, shoaibmushtaq25 reviewed
@aurangzaibumer , I reviewed non-test classes. Left a few comments. Otherwise LGTM. cc: @f-odhiambo

2022-07-26 12:45 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValidationUtil.kt
> +  internal val fhirPathEngine: FHIRPathEngine =
actually valueOrCalculatedValue is an extension that is out of scope of ValidationUtil that is why it was made internal so extension can access it. I have refactored ValidationUtil to use it as a file now.

2022-07-26 12:45 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValidationUtil.kt
> +      ValidationUtil.fhirPathEngine.evaluate(this, expression).firstOrNull()?.let { it as Type }
actually valueOrCalculatedValue is an extension that is out of scope of ValidationUtil that is why it was made internal so extension can access it. I have refactored ValidationUtil to use it as a file now. So now I can directly use fhirPathengine reference now.

2022-08-16 06:31 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +                        expression = "today() - 1 'days'"
I have used dynamic dateType (as an answer) to make it dynamic. this gives me an answerDate which is going to be dynamic with time. its a year before because this test is expected to throw a message. 

`val answerDate =
      DateType(
        SimpleDateFormat("yyyy-MM-dd")
          .parse(
            (DateTimeType.today()
              .apply {
                add(Calendar.YEAR, -1)
                add(Calendar.DAY_OF_MONTH, -1)
              }
              .valueAsString)
          )
      )`

2022-08-16 08:44 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput() {
I was trying to set a specific date on the date picker so that it can fail (out of the max range) for that I will have to use [PickerAction](https://github.com/vgrec/EspressoExamples/blob/master/app/src/androidTest/java/com/vgrec/espressoexamples/DateTimePickerTest.java) class that requires a separate library, I'm currently looking for any other alternative but this is what I found till yet.

2022-08-16 09:19 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput() {
maybe I can set min and max value before current's date. let me try some alternatives.

2022-08-22 10:38 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput() {
What is this test doing? It seems to be just setting today's date right now and not validating that it is in the range set in the extension (-1 to 4). Can you add a test that shows this?

Can you also add a test that sets the minimum value higher than the maximum value to see what happens?

2022-08-22 11:05 UTC, aurangzaibumer commented
> @aurangzaibumer please fix build errors (run spotlessApply)

done. thanks

2022-08-23 10:27 UTC, omarismail94 reviewed
Review complete. Comments left to address:

https://github.com/google/android-fhir/pull/1442/files#r951279669

2022-08-24 13:20 UTC, maimoonak commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +      .isEqualTo(today)
add an assertion for validity as well

2022-08-24 13:20 UTC, maimoonak commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +        onView(withId(R.id.text_input_layout)).perform(clickIcon(true))
import Assert.assertThrows

2022-08-24 13:20 UTC, maimoonak commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotSetDateInput_outsideRange() {
add separate tests for value outside min and max range with error text assertion

2022-08-24 13:20 UTC, maimoonak commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +    assertThat(exception.message).isEqualTo("currentPage cannot be after lastPage")
error message does not match with the actual issue

2022-08-24 13:20 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +              DateType)
import MinValueConstraintValidator.getMinValue

2022-08-24 13:20 UTC, maimoonak commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +    assertTrue(validationResult.message.equals("Minimum value allowed is:$expectedDateRange"))
use assertThat

2022-08-25 09:23 UTC, omarismail94 reviewed
I've made one comment about a potential edge case

2022-08-25 09:23 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            val minDate = DateType(Date()).apply { add(Calendar.YEAR, -1) }
What is the granularity of `minDate`?  I was able to set the date to August 1, even though that is outside of the year range. If today is Aug 25 2022, the `minDate` should be  Aug 25 2021.

I tried to set July 31 as well, but it correctly did not let me.

2022-08-26 07:27 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            val minDate = DateType(Date()).apply { add(Calendar.YEAR, -1) }
But when you select 1st August from Calendar as soon as you closes the date picker, the validation will trigger and show you the error on the edit text then minimum value date is 25 August. Date picker is not restricting the dates of that particular month but if user selects, it will be validated and the error will be shown.

2022-09-01 06:14 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            val minDate = DateType(Date()).apply { add(Calendar.YEAR, -1) }
I restricted min and max dates using CompositeDateValidator 
Here's the result, probably this is exactly what you were asking. Please correct me if I'm wrong. thanks

Considering 
my current date : 14th of Sept, 2022
minValue : "today() - 1 'months'" 
maxValue : "today() + 1 'months'"

https://user-images.githubusercontent.com/35099184/187844018-d2eed54d-1c9a-40f7-8bae-75c60d4b9cbe.mp4


cc : @f-odhiambo

2022-09-01 07:36 UTC, maimoonak approved these changes

2022-09-01 10:28 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            val minDate = DateType(Date()).apply { add(Calendar.YEAR, -1) }
can you please review @aditya-07

2022-09-08 17:36 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            val minDate = DateType(Date()).apply { add(Calendar.YEAR, -1) }
Is the change to use `CompositeDateValidator` uploaded yet to GitHub? I do not see that class being used as part of this PR

2022-09-09 08:15 UTC, aurangzaibumer commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +            val minDate = DateType(Date()).apply { add(Calendar.YEAR, -1) }
Pushed the new changes, I was waiting for your feedback so that I could commit the changes if you agree to the new implementation. thanks Omar

2022-09-13 01:20 UTC, omarismail94 reviewed
One more question about restricting date range

2022-09-13 01:20 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        max?.let { listValidators.add(DateValidatorPointBackward.before(it)) }
How granular are we allowing this? If someone set `min` to be granular up to seconds (i.e. 2022-09-12 15:05:44 UTC), should we allow it? Or should we just allow day as our most granular setting?

2022-09-14 08:48 UTC, f-odhiambo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        max?.let { listValidators.add(DateValidatorPointBackward.before(it)) }
Hey @omarismail94 I think we should limit this to just date (yyyy-mm-dd) and time (hh:mm). If all is ready we can close this Issue/PR and raise an enhancement ticket as a follow up   CC @aurangzaibumer @jingtang10

2022-09-15 08:56 UTC, aurangzaibumer commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        max?.let { listValidators.add(DateValidatorPointBackward.before(it)) }
> How granular are we allowing this? If someone set `min` to be granular up to seconds (i.e. 2022-09-12 15:05:44 UTC), should we allow it? Or should we just allow day as our most granular setting?

I did try "valueDate": "2022-09-02T05:11:13" , the date picker ignored the time and used the date part as expected to restrict the dates.

2022-09-16 06:38 UTC, f-odhiambo commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        max?.let { listValidators.add(DateValidatorPointBackward.before(it)) }
OK this is noted @aurangzaibumer seems this will only work with date , which is fine for this use case. @jingtang10 Kindly review and give feedback

2022-09-16 14:31 UTC, omarismail94 approved these changes

2022-09-16 14:32 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        max?.let { listValidators.add(DateValidatorPointBackward.before(it)) }
Thanks! Marking as resolved

2022-09-20 06:58 UTC, aurangzaibumer commented
Hello @omarismail94 
I've tried updating the branch with master couple of times but PR gateways are still failing. 
Error Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 120000 ms
Can you please guide me on this. Thanks

2022-09-21 19:31 UTC, merged

2022-10-21 06:44 UTC, santosh-pingle commented
For testing purpose updating example
``` {
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "1",
      "text": "When was your last menstrual period? (LMP)",
      "type": "date",
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/maxValue",
          "valueDate": "2022-12-30"
        },
        {
          "url": "http://hl7.org/fhir/StructureDefinition/minValue",
          "valueDate": "2022-12-21"
        }
]
...
```