answer expression full, reference type, and choice column basic support
google/android-fhir pull request #1447
Opened 2022-06-07 15:34 UTC by maimoonak

Fixes #1039 

**Description**
Implement answer expression support and example in datacapture, refereence field type and basic implementation of choice column

**Type**
Choose one: Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-15 12:09 UTC, Tarun-Bhardwaj commented
@aditya-07 , could you please review this PR?

2022-06-15 18:02 UTC, jingtang10 requested changes

2022-06-24 08:48 UTC, Tarun-Bhardwaj commented on datacapture/build.gradle.kts
> +  implementation(project(":engine"))
@maimoonak , have the comments above from @jingtang10 been addressed?

2022-06-28 17:50 UTC, maimoonak commented on datacapture/build.gradle.kts
> +  implementation(project(":engine"))
Done. 
PR engine = https://github.com/google/android-fhir/pull/1479
PR capture = https://github.com/google/android-fhir/pull/1480

2022-06-28 17:51 UTC, maimoonak commented on datacapture/build.gradle.kts
> +  implementation(project(":engine"))
@Tarun-Bhardwaj @jingtang10 @f-odhiambo @dubdabasoduba

2022-08-22 08:57 UTC, Tarun-Bhardwaj commented
@maimoonak , is there an ETA by when we can merge this PR?

2022-09-14 06:20 UTC, aditya-07 commented
@maimoonak Should this PR be closed since its now split into two separate ones?

2022-09-20 09:42 UTC, maimoonak commented
closing in favor of #1480

2022-09-20 09:42 UTC, closed without merging