Kj/sdc questionnaire integer edit text
google/android-fhir pull request #145
Opened 2021-01-13 09:23 UTC by kashyapj2793

Addressing #140

2021-01-21 10:09 UTC, jingtang10 requested changes
Thanks for the change @kashyapj2793!

2021-01-21 10:09 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetInputText() {
If there isn't an answer already, I think the edit text should remain empty.

2021-01-21 10:09 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetQuestionnaireResponseItemComponentAnswer() {
add a test case for if the edit text content is empty?

2021-01-21 10:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +                  questionnaireItemViewItem.singleAnswerOrNull =
in the case where there isn't any input (text box empty), we probably should make sure to remove any answer.

2021-01-21 13:06 UTC, kashyapj2793 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +                  questionnaireItemViewItem.singleAnswerOrNull =
If there isn't any input questionnaireItemViewItem.singleAnswerOrNull = null since  editable.toString().toIntOrNull() will be null

2021-01-21 14:15 UTC, kashyapj2793 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetQuestionnaireResponseItemComponentAnswer() {
done

2021-01-21 14:16 UTC, kashyapj2793 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +                  questionnaireItemViewItem.singleAnswerOrNull =
I think I have done this, please check the latest commit

2021-01-21 14:16 UTC, kashyapj2793 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetInputText() {
This is checking if there is an answer already the edit text should be set correctly

2021-01-22 14:47 UTC, jingtang10 approved these changes
thanks @kashyapj2793!

just one comment in the test file. otherwise good to merge.

2021-01-22 14:47 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetInputText() {
add another test case where questionnaire response doesn't contain an answer, and check the input is an empty string.

2021-01-22 15:21 UTC, merged