Add basic rev. mgmt. support
google/android-fhir pull request #146
Opened 2021-01-13 09:27 UTC by deepankarb

* Added Dao for writing local changes to db
* Diffing and squashing UPDATE type changes to yield a single UPDATE for sync

2021-01-25 17:48 UTC, deepankarb commented on datacapturegallery/build.gradle
> +    packagingOptions {
Excluding to avoid duplication. See: https://stackoverflow.com/questions/35417464/why-are-gradle-build-packagingoptions-needed

2021-01-26 00:40 UTC, jingtang10 reviewed
thanks deepankar! haven't looked at the tests.

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/Database.kt
> +     */
```suggestion
    /**
     * Retrieves all [LocalChange]s for all [Resource]s, which can be used to update the remote FHIR server. Each [resource] will have at most one [LocalChange] (multiple changes are squashed).
     */
```

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/LocalChange.kt
> +    val diff: String
maybe call this content or payload? diff seems only suitable for update.

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +            Type.UPDATE -> if (first.type.equals(Type.UPDATE)) {
use when rather than if

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +                throw IllegalArgumentException("Don't know how to merge $first and $second.")
```suggestion
                throw IllegalArgumentException("Cannot merge local changes with type ${first.type} and ${second.type}.")
```

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +     * Update a [Resource] with a JSON patch (RFC 6902).
I thinks this doesn't have to be a resourc at all? The documentation can be more generic. for example Update a json object with a json patch...

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +     * JSON patch diff b/w two [Resource]s.
nit: don't use abbreviations b/w.

2021-01-26 00:40 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +    fun squash(localChanges: List<LocalChange>): LocalChange =
I think this function needs to be 1) static (in a companion object) 2) in a separate class. it doesn't seem to belong to local change dao. a utility class seems more appropriate.

you might move the other functions this function uses too.

2021-01-26 05:28 UTC, deepankarb commented on fhirengine/src/main/java/com/google/fhirengine/Util.kt
> +}
It is indeed and the idea was to refactor `ResourceSynchronizer.kt` after this PR gets merged :)

2021-01-26 08:24 UTC, deepankarb commented
Updated with fixes based on comments. @jingtang10 PTAL.

2021-01-26 11:18 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeUtils.kt
> +/*
did you add tests for this static class? if not, please create an issue as a follow up :)

i think one of the benefits of having this static class is that the tests can be written very independently.

2021-01-26 11:18 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeUtils.kt
> +            "Trying to UPDATE resource ${target.resourceType}/${target.id} with no changes"
this error message seems wrong

2021-01-26 11:18 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeUtils.kt
> +        val jsonDiff = JsonDiff.asJson(sourceJson, targetJson)
I actually think this might look better and more readable if you inline source and target jsons?

```suggestion
        val jsonDiff = JsonDiff.asJson(
            objectMapper.readValue(
                parser.encodeResourceToString(source),
                JsonNode::class.java
            ),
            objectMapper.readValue(
                parser.encodeResourceToString(target),
                JsonNode::class.java
            )
        )
```

2021-01-26 11:18 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/DatabaseImpl.kt
> +        // TODO: impl insertAll in LocalChangeDao
this seems to have been implemented?

2021-01-26 16:24 UTC, deepankarb commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeUtils.kt
> +/*
Created #187

2021-01-26 16:50 UTC, deepankarb commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/DatabaseImpl.kt
> +        // TODO: impl insertAll in LocalChangeDao
There's discrepancy between `ResourceDao`, which replaces a duplicate row upon insert, and `LocalChangeDao` which throws upon duplicate row insertion. We need to decide and update tests accordingly.

2021-01-26 19:14 UTC, jingtang10 approved these changes
@yigit can you also take a look please? thanks!

2021-01-28 01:21 UTC, yigit requested changes

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +            assertThrows(ResourceNotFoundInDbException::class.java) {
nit: indentation seems off here though i'm surprised spotless didn't catch it.

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/Util.kt
> +fun Date.toTimeZoneString(): String {
`internal` unless we want this to be a public API.

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/DatabaseImpl.kt
>          resourceDao.deleteResource(
we should return int from deleteResorce dao which will return # of deleted rows. this way, we can avoid adding it to localChangeDao if it didn't exist in the first place.

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/DatabaseImpl.kt
> +                .groupBy { it.resourceId + it.resourceType }
better to use a pair here:
`it.resourceId to it.resourceType`

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +    @Insert(onConflict = OnConflictStrategy.ABORT)
we don't have anything unique in thsi table besides the auto-increment key so I guess we don't need abort?

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +        val localChanges = getLocalChanges(
since you only need the last change type, youi don't need to load all changes.

you can write a query that gets the type of last change:
something like:
```
@Query("select type from localChanges where resourceId = :resourceId AND resourceType = :resourceType ORDER BY ID ASC LIMIT 1)
protected fun getLastChangeType(resourceId:String, resourceType:ResourceType):LocalCHange.Type?
```

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +        val localChanges = getLocalChanges(
same for other methods below.

2021-01-28 01:21 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/Database.kt
> +    fun <R : Resource> deleteUpdates(clazz: Class<R>, id: String)
this cannot work like this because there might be more changes in the database between the time developer queried pending changes and by the time they finish uploading.

we need to given them some sorth of token (or ids of updates) and expect them to give those ids back to avoid any race condition

2021-01-28 01:43 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/Database.kt
> +    fun <R : Resource> deleteUpdates(clazz: Class<R>, id: String)
```
val res1 = fhir.getResource(...)
val updated = update(res1) // some changes
fhir.update(res1, updated)
fhir.getLocalChanges() // this will give me the update1
fhir.update(updated, updated2)
fhir.deleteUpdates(res1) // this will also delete update2
```
so instead:

```
(token, data) = fhir.getLocalChanges(...)
...
fhir.deleteLocalCHanges(token) //token can have the ids, so we can delete the rigth content
```

2021-01-28 01:50 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +        ORDER BY LocalChange.timestamp ASC"""
better to order by id as it auto-increments.

2021-01-28 01:51 UTC, yigit commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/LocalChangeDao.kt
> +        ORDER BY LocalChange.timestamp ASC"""
ditto

2021-01-28 17:23 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/Database.kt
> +    fun <R : Resource> deleteUpdates(clazz: Class<R>, id: String)
can that token just be the id of the local change?

2021-01-29 02:11 UTC, jingtang10 commented
Discussed with @yigit and concluded that the new APIs for local changes should all be internal -- they are used as part of our lib for synchronization, not for developers to do anything.

2021-01-29 03:38 UTC, deepankarb commented on fhirengine/src/main/java/com/google/fhirengine/db/Database.kt
> +    fun <R : Resource> deleteUpdates(clazz: Class<R>, id: String)
@yigit suggested a wrapper around List<Id>. Something like `internal data class Token(val ids: List<Int>)`

2021-01-29 03:43 UTC, deepankarb commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +            assertThrows(ResourceNotFoundInDbException::class.java) {
I thought split assignment and expressions need to be indented on the first new line.

2021-02-05 11:33 UTC, deepankarb commented on fhirengine/src/main/java/com/google/fhirengine/db/Database.kt
> +    fun <R : Resource> deleteUpdates(clazz: Class<R>, id: String)
Implemented.

2021-02-05 12:52 UTC, jingtang10 commented
@googlebot I consent.

2021-02-05 12:57 UTC, jingtang10 approved these changes
Looks good! 🎉

`LocalChangeUtils.kt` is a really critical class -- can you add more documentation in the class  in general please? like add some examples in the doc each method.

2021-02-08 16:15 UTC, yigit approved these changes

2021-02-09 18:33 UTC, merged