Adds Gradle task `dokkaHtml` to run Dokka document generation
google/android-fhir pull request #1466
Opened 2022-06-21 20:02 UTC by williamito

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1457

**Description**
Adds simple Gradle tasks to run Dokka document generation.

**Alternative(s) considered**
None; would love discussion on how to integrate doc generation better with current release processes however.

**Type**
Documentation

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/7772901/174883375-c0429af5-3263-467f-932e-cfe4cc6a769e.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-28 14:03 UTC, jingtang10 commented
what's the command to be run to generate the docs?

2022-07-18 04:40 UTC, williamito commented
You can generate docs like this for datacapture, you can specify the other subprojects as well:

./gradlew datacapture:dokkaHtml

Make sure to gradle sync successfully first, it seems a bit fickle about downloading Dokka from the plugins line sometimes.

2022-07-20 14:37 UTC, jingtang10 requested changes
can the config block be made into a `Dokka.kt` file in the `buildSrc` directory? Examples:

https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/JacocoConfig.kt
https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/SpotlessConfig.kt
https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/LicenseeConfig.kt

2022-07-20 14:37 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +      moduleVersion.set("0.1.0-beta03")
can this be linked from the `Releases.kt` file?

2022-07-20 14:37 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +      moduleName.set("datacapture")
can this be linked from the `Releases.kt` file?

2022-07-20 14:37 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  id("org.jetbrains.dokka").version("1.6.10")
this is repeated in a few sub modules - can you put this in `Plugins.kt` so it's centralized?

2022-07-20 14:37 UTC, jingtang10 commented on engine/build.gradle.kts
> +      moduleVersion.set("0.1.0-beta01")
ditto

2022-07-20 14:37 UTC, jingtang10 commented on workflow/build.gradle.kts
> +      moduleVersion.set("0.1.0-alpha01")
ditto

2022-07-20 16:48 UTC, williamito commented
> can the config block be made into a `Dokka.kt` file in the `buildSrc` directory? Examples:
> 
> https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/JacocoConfig.kt https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/SpotlessConfig.kt https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/LicenseeConfig.kt

I am not sure how to manage this, given how the Dokka plugin auto-creates tasks for every module it is added to. Would it be okay to merge having fixed your other comments?

2022-07-25 17:52 UTC, jingtang10 approved these changes
thanks william - the introduction of the util function in buildSrc will be done in my pr https://github.com/google/android-fhir/pull/1503

2022-07-25 19:29 UTC, merged