Migrating Validation Result logic from View factory to QuestionnaireViewModel
google/android-fhir pull request #1468
Opened 2022-06-22 06:23 UTC by aurangzaibumer

…iewMoDEL

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-24 10:54 UTC, aurangzaibumer commented
@jingtang10 can you please review. As discussed last week I had created a separate PR for the validationResult changes, removed validation being instantiated on View Factory.

2022-06-24 13:13 UTC, joiskash requested changes
Looks good to me! Just a small comment, Is there a unit test you can write to verify that validation is takes place in getQuestionnaireState function?

2022-07-04 12:29 UTC, aurangzaibumer commented
I tried to fix some of the unit tests by triggering validation for the first time in the viewmodel (in bind method), the problem is we need to fix https://github.com/google/android-fhir/issues/1427 first so on each interaction (when onAnswerChanged calls) there will be a new list of questionnaireItemViewItem along with the validationResult that gets generated by the View Model (in the getQuestionnaireState method) and we need to refresh the list so new validationResult can be reflected on the views. @jingtang10 @f-odhiambo

2022-07-04 14:41 UTC, aurangzaibumer commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryTest.kt
> -  @Test
Removed just for checking the PR gateways, will re-add

2022-07-05 14:06 UTC, aurangzaibumer commented
> With the patch in #1486 collect gets triggered as expected. The two issues raised by @aurangzaibumer are , please add any details that I missed:
> 
> 1. How do we trigger the validation result to be displayed? Currently since the QuestionnaireItemViewItem is refers to the questionnaireResponse, the diffUtil will return a true for areItemsSame and areContentsSame.
> 2. Since we create new questionnaireItemViewItems the modified field gets overwritten.
> 
> cc : @jingtang10

Thanks @joiskash, you have covered everything. So these are the issues i'm currently facing which is kind of a blocker to https://github.com/google/android-fhir/pull/1301 as well because that PR needs a validation in order to work for a PRIOR_EDIT Pagination (one of the entry mode). So we need to have keep the state of the **modified** field and to reflect the ValidationResult (that was captured from the QuestionnaireViewModel) to the UI level without refreshing the whole screen

2022-07-06 07:48 UTC, aurangzaibumer commented
![1468postfix](https://user-images.githubusercontent.com/35099184/177497261-1a158610-42ff-4cbb-9d73-3ba48cf11ed9.gif)

Tried adding a dedicated answer property to questionnaireitemviewitem and compared the new answer on QuestionnaireItemViewItem equal deeps method as mentioned below

`fun equalsDeep(other: QuestionnaireItemViewItem): Boolean {
    return this.questionnaireItem.equalsDeep(other.questionnaireItem) &&
      this.questionnaireResponseItem.equalsDeep(other.questionnaireResponseItem)
      this.questionnaireResponseItem.equalsDeep(other.questionnaireResponseItem) && this.answer == other.answer
  }`
  
  as you can see on the GIf, we faced UI rendering issue because it was rendering the whole UI element (which is currently visible to user), also the cursor reset to index 0. This is what we had tried in order to call the bind method if any change adapter can capture.

2022-07-06 10:19 UTC, jingtang10 requested changes
rebase/merge to update your pr and then revert all the license header changes.

2022-07-13 14:26 UTC, jingtang10 commented
This turned out to be major rewrite of the library.

In order for questionnaire item comparison to actually work, the way we create `QuestionnaireItemViewItem`s has been changed.

See documentation in the `QuestionnaireItemViewItem` class. The `questionnaireResponseItem` is marked as private so that views should not hav access to it. Instead, the views should use the APIs provided to update the answers.

The ansers are then used for comparison with what's already in the questionnaire to decide how the recycler view UI should be updated.

This results in changes in the `DiffCallback` implementation in the `QuestionnaireItemAdapter.kt` file. We consider two items to be the same if they're pointing to the same questionnaire item and questionnaire response item. But we will consider the contents to be the same only if the answers and validation results are also the same. These are the actual dynamic data during user interaction with the UI.

2022-07-13 14:27 UTC, jingtang10 approved these changes

2022-07-13 16:06 UTC, omarismail94 reviewed
Initial feedback

2022-07-14 15:56 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> + * - clearAnswer
no, this is fine!

2022-07-14 15:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryTest.kt
> -  @Test
these test cases are no longer valid after the validation code is moved to the view model.

2022-07-14 16:15 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    get() = _answers.map { it.copy() }
you can use a CopyOnWriteArrayList instead of copy

2022-07-14 16:21 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private var _answers:
val answers : List<...> = ...
    private set // so it cannot be set from outside but can be read

2022-07-14 17:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private var _answers:
![Screenshot 2022-07-14 at 18 02 36](https://user-images.githubusercontent.com/28757340/179040280-b1f2ab69-3433-4dc9-954c-49a95a8eaee2.png)

not sure if this works :/

2022-07-15 09:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private var _answers:
oh sorry - i tried that but wasn't sure that's what you meant - all good!

2022-07-15 10:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private var _answers:
this is done now.

2022-07-15 10:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    get() = _answers.map { it.copy() }
done

2022-07-15 10:34 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnaireItemViewItemList_shouldValidateModifiedQuestions() = runBlocking {
this is fixed now.

2022-07-15 10:59 UTC, omarismail94 approved these changes
This change is   👌👌👌👌👌👌👌👌👌

2022-07-15 13:07 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .firstOrNull()
@jingtang10 I could not figure out the recursion here when finding the item by linkId. Could you please confirm that this method would find the item even at 10th level inside hierarchy.
```
item: {
  linkId: 1
  answer.value -> value
  answer.item -> list of another nested 'item' with answer and items
}
```

So lets say inside linkId:1 there is item linkId=1.1.1.1 at fourth level .. would it find it with this method?

2022-07-15 14:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .firstOrNull()
all this function does is to look for the first item (DFS) in the questionnaire response with a certain link id. it doesn't concat the string or anything.

2022-07-15 14:45 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val child = item.firstOrNull { it.linkId == linkId }
@jingtang10 , I think @maimoonak wanted to add a comment on this method.
Here we are checking only one level down in the descendants but there is no recursion to check for all the levels down the hierarchy (Let's say if we have 10 levels of nesting). What do you think about it?

2022-07-15 15:34 UTC, merged

2022-07-18 15:50 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val child = item.firstOrNull { it.linkId == linkId }
okay, Thanks.

2022-07-19 17:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .firstOrNull()
see https://github.com/google/android-fhir/pull/1496

2022-07-19 17:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val child = item.firstOrNull { it.linkId == linkId }
see https://github.com/google/android-fhir/pull/1496