Improve Kdoc comments for QuestionnaireFragment.
google/android-fhir pull request #1470
Opened 2022-06-22 21:54 UTC by williamito

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

**Description**
Ongoing work to improve kdoc comments. There should be no changes to code.

**Type**
Documentation

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-23 19:29 UTC, williamito commented
I am not sure how to document `SUBMIT_REQUEST_KEY`.

2022-07-20 14:30 UTC, jingtang10 requested changes
for `SUBMIT_REQUEST_KEY`:

```
The result key for the [Fragment Result API][https://developer.android.com/guide/fragments/communicate#fragment-result] when the user clicks the submit button in the `QuestionnaireFragment`.

No actual data is included in the result [Bundle]. To retrieve the [QuestionnaireResponse], use the `getQuestionnaireResponse()` API.

```
setFragmentResultListener(SUBMIT_REQUEST_KEY) { _, _ ->
    val questionnaireResponse = questionnaireFragment.getQuestionnaireResponse()
}
```
```

2022-07-20 14:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +   */
remove this.

the companion object is just a kotlin construct that contains "java static" fields/methods. so comments about these extras should be on the actual extra fields rather than the companion object.

2022-07-20 14:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> -     *
recover this

2022-07-20 14:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> -     * This is required unless [EXTRA_QUESTIONNAIRE_RESPONSE_JSON_STRING] is provided.
recover this

2022-07-22 05:22 UTC, williamito commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  /** @suppress */
It didn't seem that developers using the SDK would need to use this function, so I suppressed it from Dokka output to reduce clutter. If this is wrong, we could add a proper doc comment instead.

2022-07-22 05:34 UTC, williamito commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> -     * This is required unless [EXTRA_QUESTIONNAIRE_RESPONSE_JSON_STRING] is provided.
This is for questionnaire response and I don't believe it is required.

2022-07-22 05:35 UTC, williamito commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> -     *
This is for questionnaire response and I don't believe it is required.

2022-07-22 05:37 UTC, williamito commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +   */
I believe I added this due to how dokka handles/renders companion objects. I'll confirm after the doc generation code is checked in whether/why this was useful.

2022-07-27 15:11 UTC, jingtang10 approved these changes

2022-07-27 15:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  /** @suppress */
oh i didn't know this is for dokka - got it.

2022-07-27 15:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  /** @suppress */
cool. thx

2022-07-27 15:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +   */
Just checked the generated doc - i see what you mean because you have to click into the companion object to see the extras.

ok this is fine.

2022-07-27 15:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> -     *
oh! yes

2022-07-27 15:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> -     * This is required unless [EXTRA_QUESTIONNAIRE_RESPONSE_JSON_STRING] is provided.
you're right

2022-07-27 15:40 UTC, merged