1420 make lastupdated configurable
google/android-fhir pull request #1478
Opened 2022-06-28 09:04 UTC by roywanyaga

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1420

**Description**
Update [ResourceParamsBasedDownloadWorkManager](https://github.com/google/android-fhir/blob/745e2e3145e1a7749604ab5412932e27898aea8b/engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt#L53-L55) to:
1. Use  `_lastUpdated ` search parameter timestamp value exactly as provided whenever its provided as part of the sync parameters
2. Add `_lastUpdated ` search parameter if the value is provided within the SyncDownloadContext and if it's not provided within the sync parameters. Default functionality for this will be as is (without the _greater than_ `gt ` prefix)
3. To fetch all resources updated after the last sync, explicitly provide the `_lastUpdated ` sync parameter and include the _greater than_ `gt` prefix in the timestamp value  (in line with point no. 1)

**Alternative(s) considered**
N/A

**Type**
Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-06-29 06:48 UTC, FikriMilano commented
@roywanyaga you can try to push an empty commit to re-trigger the CI.
`git commit --allow-empty`

2022-06-29 12:14 UTC, dubdabasoduba requested changes

2022-06-30 05:10 UTC, roywanyaga commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
> +        }
I have updated to make the search without the  _greater than_  `gt` prefix as to was the default functionality. 
The timestamp with the _greater than_  `gt` prefix should be provided with the `_lastUpdated `Key as part of the sync parameters.

2022-06-30 05:11 UTC, roywanyaga commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
> +        "Immunization?_sort=_lastUpdated&_lastUpdated=gt2022-03-20"
This has been updated

2022-06-30 06:43 UTC, roywanyaga commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
> +        }
I've updated the PR description to include this.

2022-07-05 15:16 UTC, pld approved these changes

2022-07-06 08:14 UTC, aditya-07 requested changes
Left some comments. Also see https://github.com/google/android-fhir/issues/1420#issuecomment-1175903757.

2022-07-07 14:24 UTC, aditya-07 requested changes
The changes look good. Only suggestion is to move test cases other than the ones for lastUpdate fix into a separate PR.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
> +          override suspend fun getLatestTimestampFor(type: ResourceType) = "2022-06-28"
The date provided in params and `getLatestTimestampFor` should be different so that we know exactly which date was picked up.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
> +          override suspend fun getLatestTimestampFor(type: ResourceType) = "gt2022-06-28"
Same as above. Also, in the real scenario, `getLatestTimestampFor` is implemented by FhirEngine and it would never pre or post fix anything to the date/datetime string.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
> +  }
This test case can be merged with lastUpdated test case to check that all provided params are used as-is to construct the url.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
> +  }
This test case can be part of a separate PR. This PR should focus on the lastupdated fix only.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
> +  }
Same as above, should be part of a different PR.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/BundleUploaderTest.kt
> +
Same as above.

2022-07-07 14:24 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
> +  }
Same as above.

2022-07-08 08:05 UTC, aditya-07 approved these changes
Great PR @roywanyaga . LGTM!
Do create a separate PR for the test cases that you had added for `TransactionBundleGenerator` & `ResourceParamsBasedDownloadWorkManager`.

2022-07-08 11:51 UTC, merged

2022-07-08 14:14 UTC, jingtang10 commented
thanks @roywanyaga and @aditya-07. please make sure future PRs don't update the header files for files tha thave not been changed. thanks!