Answer expression engine support | Feedback incorporated
google/android-fhir pull request #1479
Opened 2022-06-28 14:24 UTC by maimoonak

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-07-01 11:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +            unit = it.lastOrNull()
We should use size to figure out unit as well since first & last value can be same incase list has a single item.

2022-07-01 13:50 UTC, aditya-07 requested changes

2022-07-01 13:50 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  fun isInitialized() = fhirServices != null
Please remove if its not used anywhere.

2022-07-01 13:50 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/MoreSearchTest.kt
> +    Truth.assertThat(captor.firstValue.paramName).isEqualTo("address-country")
Import Truth.assertThat.

2022-07-01 13:50 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/MoreSearchTest.kt
> +    val search = spy(Search(ResourceType.Patient))
Do we need a spy object here? If not please remove.

2022-07-01 13:50 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/MoreSearchTest.kt
> +    Truth.assertThat(searchFilter.value).isEqualTo(12.toBigDecimal())
Same comments for rest of the tests, please remove spy.

2022-07-04 09:26 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  fun isInitialized() = fhirServices != null
this would be used in data capture in next [PR](https://github.com/google/android-fhir/pull/1480/files#diff-8cd45b205a44d10724e80221e479dbb6a10c58e7b110479f8ea2abdda793cf60R72) which is supposed to be merged after this is released

2022-07-04 09:32 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/search/MoreSearchTest.kt
> +    val search = spy(Search(ResourceType.Patient))
yes. it is needed. because 1- we do not want to run fhirEngine -> resourceDao -> database... 2- We want to capture the arg that is being passed to fhirEngine for search and validate if it has right parameters. Otherwise we would not be able to capture the argument and flow would run database search unnecessarily.

2022-07-04 09:34 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/search/MoreSearchTest.kt
> +    Truth.assertThat(searchFilter.value).isEqualTo(12.toBigDecimal())
yes. it is needed. because We want to capture the arg that is being passed to fhirEngine for search and validate if it has right parameters. Otherwise we would not be able to capture the argument

2022-07-04 11:32 UTC, maimoonak commented
@aditya-07 kindly check the changes and my comments. The PR was passing codcov check but now all of a sudden it has started failing it.

2022-07-08 12:02 UTC, aditya-07 reviewed
A small comment, otherwise the PR looks good. Should be able to approve it after this comment is discussed/addressed.

2022-07-14 07:36 UTC, aditya-07 approved these changes
LGTM !

2022-07-14 07:43 UTC, jingtang10 requested changes

2022-07-14 07:49 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  fun isInitialized() = fhirServices != null
in tests for data capture

2022-07-14 07:49 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  fun isInitialized() = fhirServices != null
This is supposed to be used by the Data Capture code. https://github.com/google/android-fhir/pull/1479#discussion_r911977031

2022-07-14 12:34 UTC, jingtang10 requested changes

2022-07-14 12:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/XFhirQuery.kt
> +  var search: Map<String, String?>,
seems to me the value of the filter shouldn't be nullable?

```suggestion
  var search: Map<String, String>,
```

2022-07-14 14:12 UTC, jingtang10 requested changes

2022-07-14 14:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +internal fun Search.filter(param: SearchParamDefinition, filterValue: String) =
can we create a new file called:

`FhirQueryTranslator.kt`

and have this API:

```
object FhirQueryTranslator {
  fun translate(fhirQuery: String): Search
}
```

and then in the `Search.kt` file, your code would be much simpler"

```
fun Search.search(fhirQuery: String): {
  return search(FhirQueryTranslator.translate(fhirQuery))
}
```

And then your test file `FhirQueryTranslatorTest.kt` will also have very clear test cases.

2022-07-14 16:31 UTC, jingtang10 requested changes

2022-07-14 16:31 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  fun isInitialized() = fhirServices != null
Use this test rule instead: https://github.com/google/android-fhir/blob/master/testing/src/main/java/com/google/android/fhir/testing/FhirEngineProviderTestRule.kt

2022-07-15 11:04 UTC, jingtang10 requested changes

2022-07-15 11:04 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/MoreDates.kt
> +/** Validates if given string matches ISO_DATE format i.e. yyyy-MM-dd or yyyy-MM-dd+00:00 */
nit: this is fine. but i think we normally prefer more explicit comment.

e.g.

```suggestion
/** Returns true if given string matches ISO_DATE format i.e. "yyyy-MM-dd" or "yyyy-MM-dd+00:00", false otherwise. */
```

I also don't necessarily think this should be an extension function to String. I think extension functions should in general be related to the class it's extending. isValidDateOnly isn't a generic string utility. so i think it's better off if we left this just as a general utility.

2022-07-15 11:04 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/XFhirQueryTranslator.kt
> +  internal fun Search.applyFilterParam(param: SearchParamDefinition, filterValue: String) =
OK I konw this is a lot to ask... but...

I kinda like the idea of keeping these functions private... I really want to just expose a single API in this class which is `translate`.

if we do that, do you think it's easy to modify the tests so that they're still testing all the different edge cases sufficiently? let me know if not.

same with `applySortParams`.

2022-07-15 11:04 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/XFhirQueryTranslator.kt
> +/*
move this class to a sub package called `query`. same with tests.

keep the `MoreSearch.kt` and `Search.kt` where they are and intact.

2022-07-15 11:05 UTC, jingtang10 commented
i really like the API change btw - i think the translator class is really clear

2022-07-15 11:07 UTC, jingtang10 requested changes

2022-07-15 11:07 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/XFhirQueryTranslator.kt
> +   */
why do you say "basic"? is there anything this function doesn't support right now? add comments to explain.

also, translates into what? please explain.

2022-07-15 11:07 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/XFhirQueryTranslator.kt
> +internal object XFhirQueryTranslator {
add a brief kdoc.

don't have to repeat the documentatino for the `translate` function. but briefly explain what this class does.

2022-07-15 14:12 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/XFhirQueryTranslator.kt
> +  internal fun Search.applyFilterParam(param: SearchParamDefinition, filterValue: String) =
The change might take some effort. We can sort it out in other ticket. I have seen that private methods with @VisibleForTesting allows access to private methods in Test classes, but in sdk there are 3/4 annotation for this in different apis, and none of them worked when I tried. We can figure out to make that work as a separate issue and that way we would be able to test private methods across the project.

2022-07-15 14:17 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/XFhirQueryTranslator.kt
> +   */
The search API in fhir is an extensive API with alot of other features as well including fhirpath support in query params, lt,gt,avg like functions into search, search over common params, search with complex params etc. Thus everything that a server has to offer. This PR addresses basic search including key-val literals, sorting (asc/desc), limit etc.

2022-07-15 14:57 UTC, maimoonak commented
@jingtang10 plz review it.

2022-07-22 18:03 UTC, jingtang10 requested changes
big fan of this PR - thanks so much @maimoonak

2022-07-22 18:03 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +    assertThat(result.size).isEqualTo(2)
why only checking the first patient not the second?

2022-07-22 18:03 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun search_byXFhirQueryString_shouldReturnResourceList() = runBlocking {
i don't really like this test case. i think the query is too complex. you're testing active, gender, sorting by name, and count...

can you split this into a test on sort, filter, and on count?

2022-07-22 18:03 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
> +  @Test(expected = UnsupportedOperationException::class)
same - don't use this annotation for the rest of this PR

2022-07-26 06:55 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun search_byXFhirQueryString_shouldReturnResourceList() = runBlocking {
Created 3 tests. All tests in current class are following similar naming convention. Thats why it was used

2022-07-26 07:28 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +        it.split("=").takeIf { it.size > 1 }?.let { it.first() to it.elementAt(1) }
Can we add test case for missing value like "Patient?**active=&gender=**&_sort=-name,gender&_count=11"

2022-07-26 07:28 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +    val count = queryParams?.find { it.first == XFHIR_QUERY_COUNT_PARAM }?.second?.toInt()
second?.toInt() can throw NumberFormatException if its not valid number. we may need to handle it

2022-07-26 07:28 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
> +  fun translate_shouldNotAddLimit_WhenMissing() {
Can we add test case where count value is missing like "Patient?active=true&gender=male&_sort=-name,gender&_count="

2022-07-26 08:13 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/Search.kt
> +suspend fun FhirEngine.search(xFhirQuery: String): List<Resource> {
Not possible. We do not know resource type beforehand. It has to be handled dynamically

2022-07-26 08:16 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
> +  fun translate_shouldNotAddLimit_WhenMissing() {
I just removed a method for a broader search as per this comment https://github.com/google/android-fhir/pull/1479#discussion_r927881928. Can add one only Patient?_count=

2022-07-26 08:17 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +    val count = queryParams?.find { it.first == XFHIR_QUERY_COUNT_PARAM }?.second?.toInt()
It should throw exception. Shall I add a test? OR throw a checked-exception?

2022-07-26 08:52 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +    val count = queryParams?.find { it.first == XFHIR_QUERY_COUNT_PARAM }?.second?.toInt()
resolved

2022-07-26 10:46 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/Search.kt
> +suspend fun FhirEngine.search(xFhirQuery: String): List<Resource> {
https://build.fhir.org/ig/HL7/sdc/examples.html#using-answerexpression-referenceresource-referenceprofile-and-lo here is the usage of this

2022-07-26 11:19 UTC, maimoonak commented
@PallaviGanorkar @jingtang10 kindly check comments and changes

2022-07-28 08:43 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +    val count = queryParams?.find { it.first == XFHIR_QUERY_COUNT_PARAM }?.second?.toInt()
We can catch it and skip count from the search param. @jingtang10   please provide you inputes as well

2022-07-29 12:24 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +    assertThat(exception.message).isEqualTo("Unknown resource typeCustomResource")
"typeCustomResource" this can be like "type CustomResource". not sure if this testcase assert for message is success

2022-07-29 12:26 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +    assertThat(exception.message).isEqualTo("Unknown resource typeCustomResource")
@maimoonak thanks!
added few comments. Other things LGTM. Code owner can have look

2022-07-29 12:31 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
> +  fun translate_shouldAddDescendingSort_ForQueryString() {
can we use the new kotlin test case names in reverse single quotes: https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

2022-07-29 12:34 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
> +  fun translate_shouldAddDescendingSort_ForQueryString() {
Thanks @maimoonak , added few comments, other things LGTM.

2022-08-02 11:58 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +    assertThat(exception.message).isEqualTo("Unknown resource typeCustomResource")
Error comes from FHIR ResourceType which sends message without space. 
![Screenshot from 2022-08-02 16-56-23](https://user-images.githubusercontent.com/4829880/182369172-5e9815d2-dd70-4b92-97c5-06ecbf4401ff.png)

2022-08-02 12:54 UTC, maimoonak commented
done @PallaviGanorkar @jingtang10

2022-08-04 07:43 UTC, PallaviGanorkar commented
> done @PallaviGanorkar @jingtang10

LGTM!

2022-08-05 15:29 UTC, jingtang10 approved these changes
This is great work! thank you @maimoonak

2022-08-05 15:30 UTC, merged