Answer expression data capture and catalog support | Feedback incorporated
google/android-fhir pull request #1480
Opened 2022-06-28 17:47 UTC by maimoonak

Fixes part of #1039 | Depends on #1479 

**Description**
Fhir data capture and catalog supporting basic xfhir-query i.e. https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirquery for [answer expression](https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-answerExpression.html). 
Implement reference data type

**Type**
Choose one: (Feature

**Screenshots (if applicable)**
<img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/176248728-77113b23-24f3-4feb-93b9-38a08b7509ad.png"/> <img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/176248729-617bb3a4-1c8e-4281-8423-13900bfbd77a.png"/>

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-16 09:51 UTC, jingtang10 requested changes

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +      QuestionnaireItemType.REFERENCE -> QuestionnaireItemViewHolderType.REFERENCE
Check the function below `getChoiceViewHolderType`, we could probably reuse the function to decide how to present the options that are references to other FHIR resources.

The `reference` here is about what are the answer options, not necessarily how they should be presented.

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  fhirPathEngine
think about moving the fhir path engine evaluate logic to the caller. and keep this function strictly "util".

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  this.choiceColumn
can you just early return?

```
if (this.choiceColumn == null) {
  return
}
```

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +                fhirPathEngine.evaluateToString(data, it.path)
make this a separate function?

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          // just use an empty questionnaireResponse Item
```suggestion
        // just use an empty questionnaire response item.
```

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +import com.google.android.fhir.datacapture.mapping.ResourceMapper.fhirPathEngine
can we have a separate fhir path engine provider please

2022-08-16 09:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +            if (it.hasValueReference()) it.valueReference.display
use `when`

2022-08-17 14:07 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  fhirPathEngine
done for base type. however, for resource type not possible to move this out as expression is specified with in choice column

2022-08-17 15:54 UTC, maimoonak commented
@jingtang10 kindly review the changes

2022-09-09 12:18 UTC, jingtang10 requested changes

2022-09-09 12:22 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +    ),
i feel this feature "answer expression" isn't super easy to demonstrate in the catalog app.  without context, this doesn't seem that different from the dropdown widget.

the interesting part of this feature really lies within the api integration with fhir engine. and therefore the best way to showcase this is through extensive and clear documentation (fyi @williamito) rather than catalog app.

2022-09-09 12:47 UTC, jingtang10 requested changes
the test failure for modle `demo` is likely caused by the fact in this PR a new dependency from the `datacapture` module to the public maven release of fhir engine is added.

the `demo` module already has a local dependency on the `engine` module. and now it has another dependency to the same set of classes through the `datacapture` module. this causes the build error.

to properly fix this, i think we probably should create 2 build flavours: local build that uses local modules, and release build that uses everything on maven as dependency.

but that can probably be done in a followup pr.

thanks!

2022-09-09 12:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    .also { this.answerOption.also { it.clear() }.addAll(it) }
i sort of see the `questionnaire` in `QuestionnaireViewModel.kt` as an immutable object - meaning that we should not modify it. in the `QuestionnaireItemViewItem`s, we reference the `QuestionnnaireItem`s from that `questionnaire` object in `QuestionnaireViewModel.kt`. So what you're doing here, is directly modifying the `questionnaire` object.

we need to make sure there's no unintended consequences of modifying this `answerOption` field. for example, will the questionnaire be reused? or when the screen refreshes, will these values be stale etc?

but i feel like a safer way to do this is just not modify the `answerOption`.

2022-09-13 23:56 UTC, maimoonak commented
@jingtang10 changes done. Kindly review

2022-09-15 15:52 UTC, jingtang10 requested changes

2022-09-15 15:52 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  debugImplementation(project(":engine"))
order these alphabetically. i.e. break them into separate blocks.

2022-09-15 15:52 UTC, jingtang10 commented on datacapture/build.gradle.kts
>    androidTestImplementation(Dependencies.Espresso.espressoCore)
move this line up to the androidTestImplementation block

2022-09-15 15:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +data class ChoiceColumn(val path: String, val label: String?, val forDisplay: Boolean)
can you try to mark this as internal?

2022-09-15 15:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  if (this.type != Questionnaire.QuestionnaireItemType.REFERENCE && dataList.first().isResource) {
```suggestion
  if (this.type != Questionnaire.QuestionnaireItemType.REFERENCE && dataList.all { it.isResource } ) {
```

2022-09-15 15:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +}
```
when {
  (question type is reference) -> {
    check(data list must be resources)
    return map...
  }
  else -> {
    check(data list can't be resources)
    return map...
  }
```

2022-10-07 08:02 UTC, jingtang10 approved these changes

2022-10-07 08:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val answerExpression = item.answerExpression!!
i feel this can be softened a bit - it wouldn't be idea if someone else unknowningly calls this function and gets a crash.

maybe `item.answerExpression?.let { ... }` and then change the return type to nullable as well.

at the call site, you'll add !! at the end of the return value.

2022-10-07 09:12 UTC, jingtang10 requested changes

2022-10-07 09:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val answerExpressionMap =
needs documentation. is this always up-to-date? when do you update this? add these to the documentation.

2022-10-07 09:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (answerExpression.isXFhirQuery && answerExpressionMap.contains(answerExpression.expression)
ok so the assumption is that if the expression is x fhir query the value will never change?

is this always true? can you have an x fhir query that refers to an id that might be changed by another answer?

2022-10-07 09:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +      .contains(ChoiceColumn("display", "DESCRIPTION", true))
make this stronger by using `containsExactly`

2022-10-07 09:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +    assertThat(answers.last().reference).isEqualTo("Patient/5678")
use containsExactly. or at least you'll need to assert the size of this list

2022-10-07 09:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private val resolveAnswerExpression:
we have done a huge amount of refactoring to make the data flow better, but i've just realised these callbacks do not seem to be consistent with what we've done.

the source of the truth should always be generated by the view model. is it possible to not have this callback but instead use a list which is populated by the view model?

2022-10-07 11:16 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +          require(dataList.all { it.isResource }) {
this was discussed in last review. the require needs to assert that each value is fulfilling the criteria. This assertion is dependent on the type of widget. This does not hold true for other branches hence can be only inside this block

2022-10-07 11:27 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  dataList: List<Base>
this can be Resource or Coding as well. The choice column can handle complex types https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-choiceColumn.html

2022-10-07 11:29 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/FhirPathUtil.kt
> +internal fun evaluateToDisplay(expressions: List<String>, data: Resource) =
For Reference items, if multiple columns are marked with 'forDisplay', the display value used will be a space-separated concatenation of all columns so-marked.
https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-choiceColumn.html

2022-10-07 11:48 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (answerExpression.isXFhirQuery && answerExpressionMap.contains(answerExpression.expression)
Current implementation does not allow it to change value. However, the advance implement suggests to evaluate the fhirpath before any evaluation https://build.fhir.org/ig/HL7/sdc/expressions.html#x-fhir-query-enhancements.

2022-10-07 11:58 UTC, maimoonak commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +    assertThat(answers.last().reference).isEqualTo("Patient/5678")
containsExactly does not work with fhir Type. Added list size assertion

2022-10-07 12:02 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private val resolveAnswerExpression:
Current implementation that is handling answer options using valueset also uses similar pattern. We would have to refactor both to accommodate this. Also this callback load the options in right way with using runBlocking. We need to implement a mechanism to load options in background with a progress bar and from the right source (answerOptions, valueSet, OR from answerOption etc). We can create a new ticket and add it as discussion item as this would need an overhaul.

2022-10-07 15:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private val resolveAnswerExpression:
please create a ticket

2022-10-07 15:35 UTC, jingtang10 requested changes

2022-10-07 15:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/FhirPathUtil.kt
> +internal fun evaluateToDisplay(expressions: List<String>, data: Resource) =
nice one - can you add that to the documentation?

2022-10-07 15:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +          require(dataList.all { it.isResource }) {
wait but you still map the list... just think how many times this require is run?

i think the `when` might need to be outside of the `dataList.map`

2022-10-07 16:44 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (answerExpression.isXFhirQuery && answerExpressionMap.contains(answerExpression.expression)
https://github.com/google/android-fhir/issues/1658

2022-10-07 17:13 UTC, jingtang10 approved these changes

2022-10-10 10:56 UTC, merged