Try Kokoro as CI Tool
google/android-fhir pull request #1481
Opened 2022-06-28 17:50 UTC by omarismail94

Use Kokoro as a CI Tool. 

It is a script-based, meaning that developers can run the `build.sh` script locally to see if there PRs will build and pass when run against Kokoro.

The tool completes its run in 30 minutes, halving the time from GitHub

Also added a `--record_screen` flag to `build.sh` so that users can record their screen locally when testing.

When Kokoro runs, it always adds this flag and uploads the screen capture as part of the artefacts it uploads. The artefacts also include the build logs, the `ci-repo` directory, the `build.zip` file, and any `xml` files from testing

I have kept the GitHub Actions config for now, and think we should use both CI tools for the time being, just for people to become familiar with Kokoro. We can migrate to using only Kokoro in a few weeks.

2022-07-07 11:52 UTC, jingtang10 requested changes

2022-07-07 11:52 UTC, jingtang10 commented on build.gradle.kts
> +  val buildNumber = System.getenv("KOKORO_BUILD_ID")
add document for this

2022-07-07 11:52 UTC, jingtang10 commented on build.sh
> +    echo "ERROR: Invalid number of args passed."
add number of args to the error message. or the args themselves.

2022-07-07 11:52 UTC, jingtang10 commented on build.sh
> +    $ADB pull "${RECORD_DIR}" || echo "No videos on phone"
should this be a warning or info if no video was recorded?

2022-07-07 11:52 UTC, jingtang10 commented on build.sh
> +  if [[ $1 == "--record_screen" || $2 == "--record_screen" ]]; then
i kinda feel like this is going to generate issues when the number of args grows. how about:
1) create a function to properly handle all args, and set some variable in the script before proceeding, or
2) use `$*`?

i'm not really familiar with the idiomatic ways of writing scripts... so feel free to correct me/ignore this. but this is what i found: https://superuser.com/questions/186272/check-if-any-of-the-parameters-to-a-bash-script-match-a-string

2022-07-07 11:52 UTC, jingtang10 commented on kokoro/README.md
> +The files in this directory serve as plumbing for running tests under Kokoro,
add link to public documentation of kokoro if any

2022-07-07 11:52 UTC, jingtang10 commented on kokoro/gcp_ubuntu/kokoro_build.sh
> +  # TODO(omarismail): remove when https://github.com/google/android-fhir/issues/1482 fixed
remove which lines?

2022-07-07 11:52 UTC, jingtang10 commented on kokoro/gcp_ubuntu/kokoro_build.sh
> +  wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip \
would this url change in the future? and when/if it doesn it'll break our pipeline?

2022-07-08 16:17 UTC, bashir2 reviewed
Thanks @omarismail94 for this, I can imagine how much work it has been to put everything together (video for screen capture is great).
I only looked at `.sh` changes and made a few comments. Nothing is blocking and all are minor.

2022-07-08 16:17 UTC, bashir2 commented on kokoro/gcp_ubuntu/kokoro_build.sh
> +  curl -Os https://uploader.codecov.io/latest/linux/codecov
Interesting; it seems their approach [is not bash based](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) anymore.
FYI, I was just curious and checked our analytics repo; then realized that we are not uploading coverage info since last September. I think [here](https://github.com/GoogleCloudPlatform/openmrs-fhir-analytics/commit/0137c66997897ec1c5d2300a1ae1010283ef7b60) is where we stopped it (unintentionally?).

2022-07-15 12:20 UTC, omarismail94 commented on kokoro/gcp_ubuntu/kokoro_build.sh
> +  find . -type f -regex ".*[t|androidT]est-results/.*xml" \
We do need to search in both folders for all XML files. In Android, each library can have two types of tests: AndroidTests, and Tests ([example](https://github.com/google/android-fhir/tree/master/engine/src). The former is for tests that run on android devices, and the other are for those that do not. When gradle runs  tests, it stores the results of the tests in the folder the test classes are part of

2022-07-15 12:24 UTC, omarismail94 commented on kokoro/gcp_ubuntu/kokoro_build.sh
> +  curl -Os https://uploader.codecov.io/latest/linux/codecov
Ah, it must have been unintentionally when we migrated to Cloud Build. I do not have access to:
https://codecov.io/github/GoogleCloudPlatform/openmrs-fhir-analytics

to see the token, but if you can give me write access on the repo, I can set this up on Cloud Build for OpenMRS

2022-07-26 12:36 UTC, omarismail94 commented on testing/build.gradle.kts
> +  }
I was getting an error about duplicates of this file existing. We also have the same function in our other libs:

* https://github.com/google/android-fhir/blob/master/engine/build.gradle.kts#L76
* https://github.com/google/android-fhir/blob/master/workflow/build.gradle.kts#L57

2022-07-26 12:37 UTC, omarismail94 commented on kokoro/gcp_ubuntu/kokoro_build.sh
> +  wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip \
I dont think so, I looked through old URLs and they still are valid with _latest appended:

```
wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
```

still works

2022-07-26 12:50 UTC, omarismail94 commented on build.sh
> +function check_adb_exists() {
Resolving as this file has been removed

2022-07-26 17:08 UTC, jingtang10 approved these changes

2022-07-26 17:08 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_multi_select_dialog.xml
> +            android:text="@string/cancel"
`@android:string/cancel` is the correct value: https://developer.android.com/reference/android/R.string#cancel

this value should be provided by the framework not by us... we don't want to have to translate cancel to different languages (thought we're not doing that now for any of our strings).

why do you think this is failing?

2022-07-26 17:47 UTC, omarismail94 commented on datacapture/src/main/res/layout/questionnaire_item_multi_select_dialog.xml
> +            android:text="@string/cancel"
There are other strings that are Android-defined as well that we do not use. For example, `yes` and `no`. We use our own definition as opposed to the android one.

2022-07-26 19:09 UTC, omarismail94 commented on build.gradle.kts
> +  // Check to see which CI tool is being used (Kokoro or GitHub Actions)
I reverted it back to GitHub only. My thinking was if we decide to only use Kokoro to run the instrumentation test, then we don't even need to change anything here

2022-07-26 20:13 UTC, merged