Purge API - clearDatabase() and getLocalChange() API implemented
google/android-fhir pull request #1487
Opened 2022-07-05 14:15 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1472 

**Description**
Purge API - clearDatabase() and getLocalChange() API implemented and test cases added

**Alternative(s) considered**
Yes, details are mentioned in design doc

**Type**
Choose one: | Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-07-19 12:44 UTC, jingtang10 requested changes

2022-07-19 12:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   * - default value is false here resource will not be deleted from LocalChangeEntity table but it
formatting

2022-07-19 12:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   * Purge resource from database based on resource type and id without any deletion of data from
```suggestion
   * Purges a resource from the database based on resource type and id without any deletion of data from
```

2022-07-19 12:47 UTC, jingtang10 requested changes

2022-07-19 12:47 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      }
this is a legitimate case where a resource does not have any local change. in this case just return an empty thing instead of throwing.

but you probably should throw if the resource itself actually doesn't exist.

2022-07-19 14:30 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      }
Done

2022-07-19 14:33 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   * PrimaryKey.autoGenerate.
Done

2022-07-19 14:34 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   * Purge resource from database based on resource type and id without any deletion of data from
Done

2022-07-28 10:16 UTC, jingtang10 requested changes

2022-07-28 10:16 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +  override suspend fun getLocalChange(type: ResourceType, id: String): LocalChangeEntity? {
i wonder if we should define a public local change data class, that encapsulates the local change entity class.

the local change entity class should be internal and for db layer only.... so if something happens in the future and we change our db implmementation, the public api which deveopers depend on will not be affected.

what do you think?

2022-07-28 10:16 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun getLocalChanges_withSingleLoaleChange_shouldReturnSingleLocalChanges() = runBlocking {
wonder if you can use the new kotlin test case names in reverse single quotes: https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

2022-07-29 13:17 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun getLocalChanges_withSingleLoaleChange_shouldReturnSingleLocalChanges() = runBlocking {
done

2022-08-03 12:09 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +  override suspend fun getLocalChange(type: ResourceType, id: String): LocalChangeEntity? {
Yes , I agreed, there must be separation for hiding internal implementation as well as app developer should not be affected due internal changes

2022-08-05 10:50 UTC, jingtang10 approved these changes
move local change data class outside of db package.

2022-08-08 08:49 UTC, PallaviGanorkar commented
> move local change data class outside of db package.

Done

2022-08-08 10:18 UTC, merged