Rename attributes and default styles.
google/android-fhir pull request #1488
Opened 2022-07-06 09:48 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1475 

**Description**

- Rename default styles and attributes in datacapture module.
- try to differentiate style and attributes names from android default names.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Code health 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-07-13 16:26 UTC, juanchazo approved these changes
Nice, these are definitely more concise and clear! 💯

2022-07-18 10:26 UTC, santosh-pingle commented
> Nice, these are definitely more concise and clear! 💯

@juanchazo thanks!
@jingtang10 
Can you please also review

2022-07-20 15:44 UTC, jingtang10 requested changes

2022-07-20 15:44 UTC, jingtang10 commented on datacapture/src/main/res/values/attrs.xml
>      <attr name="groupHeaderTextAppearanceQuestionnaire" format="reference" />
why is this not changed?

2022-07-21 09:23 UTC, santosh-pingle commented on datacapture/src/main/res/values/attrs.xml
>      <attr name="groupHeaderTextAppearanceQuestionnaire" format="reference" />
removed it, as not referenced in the code.

2022-07-21 09:24 UTC, santosh-pingle commented on datacapture/src/main/res/values/attrs.xml
>      <attr name="groupHeaderTextAppearanceQuestionnaire" format="reference" />
Updated change.

2022-07-22 10:29 UTC, jingtang10 approved these changes

2022-07-22 10:29 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_date_picker_view.xml
> +            style="?attr/questionnaireInputTextEditTextStyle"
```suggestion
            style="?attr/questionnaireTextInputEditTextStyle"
```

2022-07-22 10:29 UTC, jingtang10 commented on datacapture/src/main/res/values/attrs.xml
> +    <!--   Style for question text. -->
Maybe separate these styles into 2 different sections.
Add a header comment for styles for widgets

and then add another header comment for styles for navigation (submit, prev next buttons)

2022-07-22 15:41 UTC, jingtang10 approved these changes

2022-07-22 15:41 UTC, merged