Adds Benchmark module to evaluate the SDK's first run performance
google/android-fhir pull request #1489
Opened 2022-07-06 19:58 UTC by vitorpamplona

Fixes #1474, #825 and #1378, potential merger with #1414

**Description**
Adds a simple benchmark module to run performance tests on the engine and workflow. The module is focused on the first-time runs, which drive most of the performance issues we are having. The tests must be run in order. 

I am not convinced that yet another module needs to be added, but given our struggles with performance, it might be a good short-term investment. 

Current results in nanoseconds (seconds,milli,micro,nano) on an older Moto Z Play XT1635-02: (Android8, 3GB RAM, Octa-core 2.0 GHz) with Geekbench: 147 single core and 544 multi-core. These are single runs, but first-time runs (no caching): 
```
   49,577,870   ns    trace    AJacksonMapperBenchmark.loadJsonMapper
2,258,560,068   ns    trace    BFhirContextLoaderBenchmark.loadR4
2,642,449,743   ns    trace    BFhirContextLoaderBenchmark.loadR5
1,665,396,000   ns    trace    BFhirContextLoaderBenchmark.loadDstu3
6,920,873,294   ns    trace    CCqlEngineFhirContextLoaderBenchmark.loadDstu2FhirModelResolver
3,897,679,346   ns    trace    CCqlEngineFhirContextLoaderBenchmark.loadR4FhirModelResolver
2,907,996,227   ns    trace    CCqlEngineFhirContextLoaderBenchmark.loadDstu3FhirModelResolver
  630,341,938   ns    trace    DFhirJsonParserBenchmark.parseLightFhirLibrary
1,258,804,813   ns    trace    DFhirJsonParserBenchmark.parseLightFhirBundle
2,422,628,522   ns    trace    EElmJsonLibraryLoaderBenchmark.parseImmunicyCheckCqlFromFhirLibrary
2,481,479,986   ns    trace    EElmJsonLibraryLoaderBenchmark.parseFhirHelpersCqlFromFhirLibrary
  116,937,355   ns    trace    FEngineDatabaseBenchmark.createAndGet
8,807,674,783   ns    trace    GCqlEvaluatorBenchmark.evaluatesLibrary (evaluation only)
```

Pixel 6 GB7N6 (Android 12, 8GB RAM, Octa-core (2x2.80 GHz Cortex-X1 & 2x2.25 GHz Cortex-A76 & 4x1.80 GHz Cortex-A55) with Geekbench: 1036 single core and 2720 multi-core: 
```
   21,242,350   ns    trace    AJacksonMapperBenchmark.loadJsonMapper
  335,387,573   ns    trace    BFhirContextLoaderBenchmark.loadR4
  356,097,657   ns    trace    BFhirContextLoaderBenchmark.loadR5
  271,354,411   ns    trace    BFhirContextLoaderBenchmark.loadDstu3
  693,789,348   ns    trace    CCqlEngineFhirContextLoaderBenchmark.loadDstu2FhirModelResolver
  500,146,485   ns    trace    CCqlEngineFhirContextLoaderBenchmark.loadR4FhirModelResolver
  366,984,538   ns    trace    CCqlEngineFhirContextLoaderBenchmark.loadDstu3FhirModelResolver
  152,651,122   ns    trace    DFhirJsonParserBenchmark.parseLightFhirLibrary
  208,492,962   ns    trace    DFhirJsonParserBenchmark.parseLightFhirBundle
  297,588,461   ns    trace    EElmJsonLibraryLoaderBenchmark.parseImmunicyCheckCqlFromFhirLibrary
  276,356,160   ns    trace    EElmJsonLibraryLoaderBenchmark.parseFhirHelpersCqlFromFhirLibrary
   32,813,435   ns    trace    FEngineDatabaseBenchmark.createAndGet
1,018,112,914   ns    trace    GCqlEvaluatorBenchmark.evaluatesLibrary (evaluation only)
```

**Alternative(s) considered**
I tried building an app and a macro module, but I think this micromodule is a better approach. 

**Type**
Testing

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-07-25 14:20 UTC, vitorpamplona commented
Might close #1492 @Tarun-Bhardwaj

2022-08-16 08:58 UTC, jingtang10 requested changes

2022-08-16 08:58 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/AJacksonMapperBenchmark.kt
> +    benchmarkRule.measureRepeated { assertThat(JsonCqlLibraryReader.mapper()).isNotNull() }
do we actually need to assert?

feels redundant to assert since it's not what we're trying to test here.

same with all the other test cases.

2022-08-16 08:58 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/AJacksonMapperBenchmark.kt
> +/*
i wouldn't mind if we use something a bit more explicit as a prefix. e.g. add a divider `A_JacksonMapper...` or use numbers?

2022-08-16 08:58 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/CCqlEngineFhirContextLoaderBenchmark.kt
> +  }
order by version: dstu2, dstu3, r4.

2022-08-16 08:58 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/BFhirContextLoaderBenchmark.kt
> +  }
order by version: dstu3, r4, r5

2022-08-16 08:58 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/DFhirJsonParserBenchmark.kt
> +      assertThat(fhirHelpersLibrary.content[0].data.size).isEqualTo(220195)
even if we do assert (which i still would argue is not necessary), we probably should assert outside of the `measureRepeated` block?

2022-09-01 13:22 UTC, aditya-07 commented
@vitorpamplona Do you have any ETA for the changes?

2022-11-22 15:30 UTC, jingtang10 requested changes
can you add to the description how to run the benchmarking?

2022-11-22 15:30 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/G_CqlEvaluatorBenchmark.kt
> +        fhirOperator
```suggestion
        FhirOperator(fhirContext, fhirEngine).also {
        it.loadLibs(lib)
       }
```

2022-11-22 15:30 UTC, jingtang10 commented on benchmark/src/androidTest/java/com/google/android/fhir/benchmark/G_CqlEvaluatorBenchmark.kt
> +      val fhirContext = runWithTimingDisabled { FhirContext.forCached(FhirVersionEnum.R4) }
can we just do 1 `runWithTimingDisabled` instead of doing it many times? this seems like very fragile code.

2022-12-02 16:58 UTC, jingtang10 approved these changes

2022-12-02 16:58 UTC, merged