Date as text input in datePicker view.
google/android-fhir pull request #1493
Opened 2022-07-13 07:48 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1418 

**Description**

- Accept date as text input in dd/MM/yyyy date format, or else validation fails if text input is not in given format.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

https://user-images.githubusercontent.com/86107848/178679677-c63cf791-4a7e-49a9-ba46-aa3f7ad294f1.mov

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-07-22 10:34 UTC, jingtang10 requested changes

2022-07-22 10:34 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="hint_date_format">dd/mm/yyyy</string>
this needs to be removed

2022-07-22 10:34 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +    setLocale(Locale.US)
add tests for a different locale

2022-07-22 10:34 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    .withLocale(Locale.getDefault())
i feel this is too custom. is there no way to just use a format style that is yyyy

2022-07-22 10:36 UTC, jingtang10 requested changes

2022-07-22 10:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    .withLocale(Locale.getDefault())
can you try to use the android icu lib?

2022-08-02 12:08 UTC, santosh-pingle commented
Code changes as per review comments are in progress.

2022-08-03 10:10 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +    setLocale(Locale.US)
done

2022-08-03 10:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    .withLocale(Locale.getDefault())
done.

2022-08-03 10:21 UTC, santosh-pingle commented on datacapture/src/main/res/values/strings.xml
> +    <string name="hint_date_format">dd/mm/yyyy</string>
done

2022-08-03 10:23 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/182585687-f636c8e0-25c5-429f-ace2-b556c74ce1f3.mov

2022-08-05 10:28 UTC, jingtang10 requested changes

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="hint_date_format">dd/mm/yyyy</string>
missing a commit to be pushed?

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +                delay(1000)
this code that runs on the main thread seems fragile to me - i don't think we need this. simply updating answer within this callback seems enough?

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +            // allow user to enter the input, e.g year may be y, yy, yyyy
surely this is decided by the android api and not us?

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +              value = DateType(localDate!!.year, localDate!!.monthValue - 1, localDate!!.dayOfMonth)
i'm sure in our code we do this in multiple places. can we extract this to an extension function.

```
fun LocalDate.toDateType(): DateType {
  ...
}
```

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +              value = DateType(localDate!!.year, localDate!!.monthValue - 1, localDate!!.dayOfMonth)
and i'm sure i've seen the reverse in our code as well, but that can be done another time.

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +              value = DateType(localDate!!.year, localDate!!.monthValue - 1, localDate!!.dayOfMonth)
this whole thing can probably be in the `try` block and then you don't have to have the `localDate` variable which you have to check if it's null.?

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          FormatStyle.SHORT,
nit: just add a comment here to say that medium and long formatstyles use date names which isn't what we want. we want numerical date format.

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun textInputEditText_dateInput_localeUs() = runBlocking {
use the more readable kotlin style in reverse quote marks as test name.

2022-08-05 10:28 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun textInputEditText_dateInput_localeUs() = runBlocking {
i think there're some other stuff we want to test... e.g.

- if you type invalid date, the answer will be cleared
- if you open dialog, and input a date, the text will be updated
- if you open dialog, and cancel, the text and answer won't change

possibly not everything is testable in this class. but try to add some of these test cases.

2022-08-11 07:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          FormatStyle.SHORT,
done.

2022-08-12 06:17 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun textInputEditText_dateInput_localeUs() = runBlocking {
It accepts quote but does not allow space, it shows identifier are not allowed in android projects.

2022-08-12 07:25 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun textInputEditText_dateInput_localeUs() = runBlocking {
Added unit and android tests.

2022-08-12 07:26 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/184305589-3f98d05d-2044-47fe-a60a-4bd9560b155c.mov

2022-08-12 10:22 UTC, jingtang10 approved these changes

2022-08-12 10:22 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun textInputEditText_dateInput_localeUs() = runBlocking {
ok i didn't know this. thanks for trying. for the record: https://stackoverflow.com/questions/51562138/androidjunit4-doesnt-accept-space-function-test-name

this does seem to be an issue.

2022-08-12 10:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      // date format.
optional nit:

```suggestion
      // Medium and long format styles use alphabetical month names which are difficult for the user to input. Use short format style which is always numerical.
```

2022-08-12 10:22 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +  fun `parse date text input as per US locale`() {
nit:

```suggestion
  fun `parse date text input in US locale`() {
```

and below

2022-08-16 10:34 UTC, santosh-pingle commented
@jingtang10 
checking  below crash, if i enter date with 5 digit year e.g 21/12/19843 then it throws fhir data format exception in QuestionnaireViewModel. Same date is parsed as valid date  by android icu.

ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "19843-12-21": Expected character '-' at index 4 but found 3

2022-08-16 11:26 UTC, santosh-pingle commented
> @jingtang10 checking below crash, if i enter date with 5 digit year e.g 21/12/19843 then it throws fhir data format exception in QuestionnaireItemViewItem. Same date is parsed as valid date by android icu.
> 
> ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "19843-12-21": Expected character '-' at index 4 but found 3

Crash happens in fhir library when it performs deep copy operation on [QuestionnaireResponse.QuestionnaireResponseItemComponent] which has above mentioned date.

2022-08-16 12:25 UTC, santosh-pingle commented
> 

it also happens in QuestionnaireResponse deep copy operation.

2022-08-16 12:25 UTC, santosh-pingle commented
> > @jingtang10 checking below crash, if i enter date with 5 digit year e.g 21/12/19843 then it throws fhir data format exception in QuestionnaireItemViewItem. Same date is parsed as valid date by android icu.
> > ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "19843-12-21": Expected character '-' at index 4 but found 3
> 
> Crash happens in fhir library when it performs deep copy operation on [QuestionnaireResponse.QuestionnaireResponseItemComponent] which has above mentioned date.

it also happens in QuestionnaireResponse deep copy operation.

2022-08-18 10:42 UTC, jingtang10 approved these changes

2022-08-18 10:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          }
is it not better to have this logic in `parseDate` and throw a `ParseException` if the date is unparsable (even if it's by our definition)

2022-08-19 06:03 UTC, merged