Definition based extration for custom extensions
google/android-fhir pull request #1511
Opened 2022-07-28 07:21 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[1381]

**Description**
if field is not present in resource then added it as definition based custom extension

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-19 06:39 UTC, jingtang10 requested changes

2022-08-19 06:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  if (base is DomainResource) {
i think we need to handle the case to add extension to complex data types as well.

2022-09-09 09:32 UTC, jingtang10 requested changes

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val fieldName = getFieldNameByDefinition(questionnaireItem.definition) // 1111111111111
clean up the comment

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // If field not found in resource class add definition based extension
```suggestion
      // If field not found in resource class, assume this is an extension
```

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * Adds definition based custom extension for Resource.
```suggestion
 * Adds custom extension for Resource.
```

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    updateListFieldWithAnswer(base, field, answersOfFieldType) // given name updated here
revert this change

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  "resourceType": "Questionnaire",
fix the indentation here

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +        (patient.getExtensionByUrl(
if you do a type cast `as` you don't need this.

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +      .isEqualTo("Hausa")
combine these two by using a local variable for the `Coding` first.

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should perform definition based extraction for custom extensions with valueCodeableConcept`():
discussed: please make this test case minimum to focus on what we're trying to test. having a lot of information in the questionnaire is noisy and makes the test hard to debug.

2022-09-09 09:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should perform definition based extraction for Complex DataType with custom extensions`():
same comment as above - make this test case minimum.

2022-09-09 10:01 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val fieldName = getFieldNameByDefinition(questionnaireItem.definition) // 1111111111111
Done

2022-09-09 10:02 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // If field not found in resource class add definition based extension
Done

2022-09-09 10:03 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * Adds definition based custom extension for Resource.
Done

2022-09-09 10:04 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    updateListFieldWithAnswer(base, field, answersOfFieldType) // given name updated here
Done

2022-09-09 11:13 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  if (base is DomainResource) {
Done

2022-09-09 11:13 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  "resourceType": "Questionnaire",
Done

2022-09-09 11:13 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +        (patient.getExtensionByUrl(
Done

2022-09-09 11:13 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +      .isEqualTo("Hausa")
Done

2022-09-09 11:14 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should perform definition based extraction for custom extensions with valueCodeableConcept`():
Done

2022-09-09 11:14 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should perform definition based extraction for Complex DataType with custom extensions`():
Done

2022-09-09 14:26 UTC, jingtang10 approved these changes

2022-09-09 14:26 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val encounter = bundle.entry[0].resource as Encounter
```suggestion
    val encounter = bundle.entry.single().resource as Encounter
```

2022-09-09 14:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>      } catch (e: NoSuchMethodException) {
should there be a return statement after L448?

2022-09-10 08:06 UTC, PallaviGanorkar commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val encounter = bundle.entry[0].resource as Encounter
Done

2022-09-10 08:11 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>      } catch (e: NoSuchMethodException) {
Done

2022-09-13 14:48 UTC, merged