Unselect single choice option on click if option was previously selected.
google/android-fhir pull request #1519
Opened 2022-08-01 06:39 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1512 

**Description**
Unselect single choice answer option on click.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

https://user-images.githubusercontent.com/86107848/182087020-09edd007-f650-46d2-ade0-58c716960bb4.mov

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-01 10:25 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        var isCurrentlySelected = false
I think `false` is redundant here. Change to `var isCurrentlySelected: Boolean`

2022-08-01 10:25 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = questionnaireItemViewItem.isAnswerOptionSelected(answerOption)
can we use `isChecked` as the value for `isCurrentlySelected`? We run the same method twice

2022-08-01 10:25 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
>                  if (questionnaireItemViewItem.answers.isNotEmpty()) {
Since we are adding a layer of indentation with the `when`, let's extract the if/else statement into a separate function (`functionName(annswerOption)` to make this easier to read

2022-08-01 10:53 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        var isCurrentlySelected = false
done.

2022-08-01 10:53 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = questionnaireItemViewItem.isAnswerOptionSelected(answerOption)
done.

2022-08-01 10:53 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
>                  if (questionnaireItemViewItem.answers.isNotEmpty()) {
done.

2022-08-01 12:49 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
one more comment: `isCurrentlySelected`  wont be affected if `isChecked` changes later right? IIUC, Kotlin does not assign the same memory address, but rather a copy of the reference.

2022-08-01 12:50 UTC, omarismail94 approved these changes
Nice change! Just one comment

2022-08-02 05:46 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
correct!

2022-08-02 17:09 UTC, jingtang10 requested changes

2022-08-02 17:09 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt
> +  fun `onClick should unselect radio button if previous state is selected`() {
separate this into two test cases. one to assert on the button status (checked vs unchecked), one to assert on the answer component.

2022-08-02 17:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
what you have here is essentially a function closure - have you considered actually saving these as a variables in the delegate object?

you can declare a list of boolean values, for example.

2022-08-03 06:18 UTC, santosh-pingle commented
working on review comments.

2022-08-03 09:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        var isCurrentlySelected: Boolean
done.

2022-08-03 09:14 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryTest.kt
> +  fun `onClick should unselect radio button if previous state is selected`() {
done.

2022-08-03 09:17 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
there is only single boolean variable `isCurrentlySelected` and others are property which belongs to radio button itself.

2022-08-03 09:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
well this approach is probably fine. but the alternative is to create an array to track these things for the whole widget. have you considered that?

2022-08-03 10:34 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
Sorry, can you please help me to understand it, would you like to share some code suggestion.

2022-08-03 15:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          isCurrentlySelected = isChecked
you could add an array to the widget, e.g.

```
val selected: List<Boolean>
```

that tracks the status of all these selections.

i'm not suggesting that this is better, but this is an alternative approach to adding variables.

an article able function closures: https://www.i-programmer.info/programming/other-languages/12255-the-programmers-guide-to-kotlin-anonymous-and-lambda-functions.html?start=2#:~:text=3%20of%203-,Closure,variable%20work%20rather%20than%20closure.

your code only works because the variable you added is being maintained as environment to the lambda callback function. it's fine, but it's a bit implicit.

2022-08-03 15:54 UTC, jingtang10 commented
i think this is good to merge

2022-08-03 15:54 UTC, jingtang10 approved these changes
thanks @santosh-pingle

2022-08-03 15:54 UTC, merged