rename GitHub Action Files
google/android-fhir pull request #1522
Opened 2022-08-02 13:43 UTC by omarismail94

2022-08-02 13:54 UTC, jingtang10 requested changes

2022-08-02 13:54 UTC, jingtang10 commented on .github/workflows/deviceTests.yml
> +name: "GitHub Actions: DeviceTests"
should this be called instrumentation tests too? 

or should we change kokoro to device tests?

2022-08-05 16:32 UTC, omarismail94 commented on .github/workflows/deviceTests.yml
> +name: "GitHub Actions: DeviceTests"
changed the name of Kokoro to be the same as GitHub Actions

2022-08-06 02:59 UTC, yigit approved these changes

2022-08-08 08:29 UTC, omarismail94 commented on .github/workflows/deviceTests.yml
> +name: "GitHub Actions: DeviceTests"
done

2022-08-08 09:09 UTC, jingtang10 approved these changes

2022-08-08 09:09 UTC, merged