Pg/1530 code separation and optimization
google/android-fhir pull request #1531
Opened 2022-08-03 13:49 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1530 
**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-11 10:53 UTC, jingtang10 requested changes

2022-08-11 10:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/LocalChangeEntity.kt
> +internal data class LocalChangeEntity(
this is great

2022-08-11 10:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/LocalChangeType.kt
> +enum class LocalChangeType(val value: Int) {
i think this type enum class can be in the same fiile as the local change class that is public. it's easier for people to read and find the type for that class.

but also - i think the type for local change entity, which is internal, should be restored. and you will need to  add a mapping between this type, and the internal type.

2022-08-11 10:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/LocalChange.kt
>    /** last updated timestamp */
last updated locally? or on server? more details on what this is

2022-08-11 10:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/LocalChange.kt
> +  val versionId: String? = null,
this is the id of the version of the resource that this local change is based off of.

2022-08-11 10:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/LocalChange.kt
> +  val versionId: String? = null,
move this to after resource id

2022-08-11 12:48 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/LocalChange.kt
> +  val versionId: String? = null,
Done

2022-08-11 12:48 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/LocalChange.kt
> +  val versionId: String? = null,
Done

2022-08-11 12:50 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/LocalChange.kt
>    /** last updated timestamp */
Done

2022-08-12 01:47 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/db/LocalChangeType.kt
> +enum class LocalChangeType(val value: Int) {
Done

2022-08-19 06:18 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DbTypeConverters.kt
> + * Copyright 2022 Google LLC
revert this

2022-08-19 06:22 UTC, jingtang10 approved these changes

2022-08-19 08:52 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/db/impl/DbTypeConverters.kt
> + * Copyright 2022 Google LLC
done

2022-08-19 10:39 UTC, merged