Apply style to group type.
google/android-fhir pull request #1546
Opened 2022-08-08 14:03 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-18 10:50 UTC, jingtang10 approved these changes

2022-08-18 10:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +  view.forEach {
use `any`

2022-08-18 10:50 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +internal fun TextView.updateText(localizedText: Spanned?) {
```suggestion
internal fun TextView.updateTextAndVisibility(localizedText: Spanned?) {
```

2022-08-19 07:35 UTC, jingtang10 requested changes

2022-08-19 07:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +internal fun isViewVisible(vararg view: TextView): Int {
we discussed that this function naming is incorrect!

it needs to return a boolean.

2022-08-19 07:41 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +internal fun isViewVisible(vararg view: TextView): Int {
We also discussed one of the option is rename it to getVisibility and then keep return type Int, can you please confirm?

2022-08-19 09:12 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +internal fun isViewVisible(vararg view: TextView): Int {
renamed it to the getVisibility()

2022-08-25 09:52 UTC, jingtang10 approved these changes

2022-08-25 09:52 UTC, jingtang10 approved these changes

2022-08-25 09:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +internal fun getVisibility(vararg view: TextView): Int {
```suggestion
internal fun getViewGroupVisibility(vararg view: TextView): Int {
```

2022-08-26 06:04 UTC, merged