Cursor moves to start position while entering or deleting decimal values in text field.
google/android-fhir pull request #1552
Opened 2022-08-10 14:48 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1551 

**Description**
EditTextviewFactory view was just comparing string representation of decimal values while updating text, as result `x.0` and `x` was considered different values.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**
Just demo purpose.

https://user-images.githubusercontent.com/86107848/183932176-e8b33de4-7f94-4e76-99df-d878f07c1ba7.mov

https://user-images.githubusercontent.com/86107848/183932229-31a45d43-c0e1-4969-850d-6cba74b683d3.mov

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-12 10:32 UTC, jingtang10 requested changes

2022-08-12 10:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    when (rawInputType) {
i think this is the parent class doing the work for the child classes. an alternative way of doing this is to create an open function that has a default implementation to update answer, and then in your decimal cases you override that.

2022-08-12 10:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (answer.toDouble() != textInputEditText.text.toString().toDouble()) {
this is great. an alternative way of handing this, is that we just don't send the new answer to the view model at all. (see line 102 above). so do this check when you're updating the answer.

pro: we avoid an entire code path that recalculates the entire screen.
con: you'll have to introduce a variable in the UI to compare the new input with to decide if you send the answer to the view model

please try that - and discuss which way is better. thanks!

2022-08-12 13:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (answer.toDouble() != textInputEditText.text.toString().toDouble()) {
This check is required while text get updated in textfield.

Consider these 2 use cases : 

Case 1 : textfield is empty, answer is empty
User typed the values, now textfield has value, value get updated in answer. Now answers triggers the callback to update the value in textfield again, therefore check is required while text get updated in textfield.

Case 2 : textfield is empty, answer has value
Now answer value is set to the textfield in view factory, but it does not trigger the flow to update the value in answer. therefore check is not required while text get updated in answer.

2022-08-12 16:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (answer.toDouble() != textInputEditText.text.toString().toDouble()) {
what i'm saying is instead of doing the check here do the check in the on focus change listener.

2022-08-15 06:07 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (answer.toDouble() != textInputEditText.text.toString().toDouble()) {
please let me know when this is addressed.

2022-08-16 05:55 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (answer.toDouble() != textInputEditText.text.toString().toDouble()) {
looking into it.

2022-08-16 09:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (answer.toDouble() != textInputEditText.text.toString().toDouble()) {
It will not fix the issue if we  add this check in on focus change listener, because issue only occurs when user start typing the input. While user is typing the input an answer get updated for every single input which triggers the callback to update the text in bind api, therefore check is required in bind api before to set text in textfield.

2022-08-18 10:37 UTC, jingtang10 approved these changes

2022-08-18 10:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +        }
```suggestion
        if (answerText.isEmpty() && inputText.isEmpty()) {
          return false
        }
        if (answerText.isEmpty() || inputText.isEmpty()) {
          return true
        }
        // Avoid shifting focus by updating text field if the values are the same
        return answerText.toDouble() != inputText.toDouble()
```

2022-08-18 13:19 UTC, merged