WIP: Repeated groups
google/android-fhir pull request #1559
Opened 2022-08-18 02:49 UTC by kevinmost

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-28 14:37 UTC, jingtang10 requested changes
thanks @kevinmost! this is amazing!

2022-09-28 14:37 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +        <com.google.android.fhir.datacapture.views.QuestionnaireGroupTypeHeaderView
finding this a bit hard to read. shouldn't this xml file just be inline? (this is not part of your change admittedly)

2022-09-28 14:37 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +        android:text="Add item"
put this in `strings.xml`

2022-10-13 13:13 UTC, Tarun-Bhardwaj commented
Hi @kevinmost , could you please provide an ETA by when this can be done?

2022-10-18 14:02 UTC, kevinmost commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +        <com.google.android.fhir.datacapture.views.QuestionnaireGroupTypeHeaderView
Yeah. My follow-up change to this will involve changing the group header quite significantly anyway, so I'll address it then.

2022-10-18 14:06 UTC, kevinmost commented on datacapture/src/main/res/layout/questionnaire_item_group_header_view.xml
> +    <LinearLayout
Similarly, would rather address this in a follow-up when we revamp the entire group header to include a delete button, the instance index, etc.

2022-10-18 14:10 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          if (questionnaireItem.repeats) emptyList() else listOf(questionnaireResponseItem.item)
Yeah... this is basically the logic that we already had previously in the form of:

```kotlin
if (questionnaireResponseItem.answer.isEmpty()) {
  questionnaireResponseItem.item
} else {
  questionnaireResponseItem.answer.first().item
},
```

But now it handles multiple answers properly.

Any suggestions on how to improve this?

2022-10-18 14:13 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .flatMap { (questionnaireItem, questionnaireResponseItem) ->
Hm, I added a pretty extensive function-level comment to `createRepeatedGroupResponse`. I can pull out a val for the condition if it makes it cleaner, but I'm not sure if it does...

2022-10-18 14:42 UTC, kevinmost commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnaireHasNestedItem_ofTypeRepeatedGroup_shouldNestMultipleItems() = runBlocking {
Added an additional assertion, is this what you were thinking?

2022-10-18 14:42 UTC, kevinmost commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnaireHasNestedItem_ofTypeRepeatedGroup_shouldNestMultipleItems() = runBlocking {
Done, added multiple responses to multiple questions.

2022-10-18 14:52 UTC, kevinmost commented
I think this is ready for re-review, @jingtang10

2022-10-18 15:15 UTC, f-odhiambo commented
Thanks, @kevinmost Will review it. Not sure what app with the failing tests CC @jingtang10

2022-10-19 15:04 UTC, jingtang10 submitted a review, later dismissed

2022-10-19 15:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      .flatMap { (questionnaireItem, questionnaireResponseItem) ->
thanks yeah it looks good.

2022-10-21 19:11 UTC, kevinmost commented
Hm, the changes from #1670 seem to be breaking my tests (reverting that commit locally shows them working again).

The issue is definitely with my PR though (I agree that the ViewModel should be the source-of-truth for answers, and `QuestionnaireItemViewItem` should just be a snapshot).

Testing locally, the logic still seems to work. Any suggestions on how to restructure this test so it passes, @jingtang10?

2022-10-26 18:44 UTC, omarismail94 commented
@kevinmost @jingtang10 

Is the issue in the `modifiedQuestionnaireResponseItemSet` variable in the  `answersChangedCallback` function in the QuestionnaireViewModel?  As it's a set, does it fail to add the repeated `questionnaireResponseItem`?
```
  private val answersChangedCallback:
    (
      Questionnaire.QuestionnaireItemComponent,
      QuestionnaireResponse.QuestionnaireResponseItemComponent,
      List<QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent>,
    ) -> Unit =
    { questionnaireItem, questionnaireResponseItem, answers ->
      // TODO(jingtang10): update the questionnaire response item pre-order list and the parent map
      questionnaireResponseItem.answer = answers.toList()
      if (questionnaireItem.hasNestedItemsWithinAnswers) {
        questionnaireResponseItem.addNestedItemsToAnswer(questionnaireItem)
      }
      modifiedQuestionnaireResponseItemSet.add(questionnaireResponseItem)

      updateDependentQuestionnaireResponseItems(questionnaireItem)

      modificationCount.update { it + 1 }
    }
```

2022-10-26 18:44 UTC, omarismail94 commented
@kevinmost @jingtang10 

Is the issue in the `modifiedQuestionnaireResponseItemSet` variable in the  `answersChangedCallback` function in the QuestionnaireViewModel?  As it's a set, does it fail to add the repeated `questionnaireResponseItem`?
```
  private val answersChangedCallback:
    (
      Questionnaire.QuestionnaireItemComponent,
      QuestionnaireResponse.QuestionnaireResponseItemComponent,
      List<QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent>,
    ) -> Unit =
    { questionnaireItem, questionnaireResponseItem, answers ->
      // TODO(jingtang10): update the questionnaire response item pre-order list and the parent map
      questionnaireResponseItem.answer = answers.toList()
      if (questionnaireItem.hasNestedItemsWithinAnswers) {
        questionnaireResponseItem.addNestedItemsToAnswer(questionnaireItem)
      }
      modifiedQuestionnaireResponseItemSet.add(questionnaireResponseItem)

      updateDependentQuestionnaireResponseItems(questionnaireItem)

      modificationCount.update { it + 1 }
    }
```

2022-10-26 20:14 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    )
To get the test to pass, I replaced this part of the code with the code below.

I used `setAnswer` instead of `addAnswer`.

@jingtang10  WDYT of using this instead, and adding a TODO to make repeated groups work with `addAnswer`?

```
    repeatedGroupA.setAnswer(
      QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
        item = repeatedGroupA.questionnaireItem.getNestedQuestionnaireResponseItems()
      },
      QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
        item = repeatedGroupA.questionnaireItem.getNestedQuestionnaireResponseItems()
      }
    )
    repeatedGroupB.setAnswer(
      QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
        item = repeatedGroupB.questionnaireItem.getNestedQuestionnaireResponseItems()
      },
      QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
        item = repeatedGroupB.questionnaireItem.getNestedQuestionnaireResponseItems()
      }
    )
```

2022-11-01 18:13 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    )
not sure about this - if this works it's kind of saying the failure is legit...

2022-11-02 11:59 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    )
I looked into this a little bit. I think the issue is that we're not capturing the newly updated `QuestionnaireItemViewItem`s emitted from the view model after `addAnswer` is called. Remeber, with the recent change, if the user answers a question, a new list of items is computed and emitted by the view model, taking into account enable when and expressions.

In the test code here, we're calling `addAnswer` on the same `QuestionnaireItemViewItem` the second time which still held the empty answer list. So that resulted in the wrong answers being set in the view model.

The solution is to properly capture the new list of items and calling the answer callback on the new items.

The following code works:

```

    var repeatedGroupA = viewModel.getQuestionnaireItemViewItemList()[0]
    var repeatedGroupB = viewModel.getQuestionnaireItemViewItemList()[1]
    val observer =
      launch(Dispatchers.Main) {
        viewModel.questionnaireStateFlow.collect {
          repeatedGroupA = it.items.single { it.questionnaireItem.linkId == "repeated-group-a" }
          repeatedGroupB = it.items.single { it.questionnaireItem.linkId == "repeated-group-b" }
        }
      }
    try {
      // Calling addAnswer out of order should not result in the answers in the response being out
      // of
      // order; all of the answers to repeated-group-a should come before repeated-group-b.
      repeatedGroupA.addAnswer(
        QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
          item = repeatedGroupA.questionnaireItem.getNestedQuestionnaireResponseItems()
        }
      )
      ShadowLooper.runUiThreadTasksIncludingDelayedTasks()

      repeatedGroupB.addAnswer(
        QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
          item = repeatedGroupB.questionnaireItem.getNestedQuestionnaireResponseItems()
        }
      )
      ShadowLooper.runUiThreadTasksIncludingDelayedTasks()

      repeatedGroupA.addAnswer(
        QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
          item = repeatedGroupA.questionnaireItem.getNestedQuestionnaireResponseItems()
        }
      )
      ShadowLooper.runUiThreadTasksIncludingDelayedTasks()

      repeatedGroupB.addAnswer(
        QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
          item = repeatedGroupB.questionnaireItem.getNestedQuestionnaireResponseItems()
        }
      )
      ShadowLooper.runUiThreadTasksIncludingDelayedTasks()

      assertThat(viewModel.getQuestionnaireItemViewItemList().map { it.questionnaireItem.linkId })
        .containsExactly(
          "repeated-group-a",
          "nested-item-a",
          "another-nested-item-a",
          "nested-item-a",
          "another-nested-item-a",
          "repeated-group-b",
          "nested-item-b",
          "another-nested-item-b",
          "nested-item-b",
          "another-nested-item-b"
        )
        .inOrder()

      assertResourceEquals(
        actual = viewModel.getQuestionnaireResponse(),
        expected =
          QuestionnaireResponse().apply {
            addItem(
              QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                linkId = "repeated-group-a"
                text = "Group question A"
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "nested-item-a"
                    text = "Basic question"
                  }
                )
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "another-nested-item-a"
                    text = "Basic question"
                  }
                )
              }
            )
            addItem(
              QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                linkId = "repeated-group-a"
                text = "Group question A"
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "nested-item-a"
                    text = "Basic question"
                  }
                )
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "another-nested-item-a"
                    text = "Basic question"
                  }
                )
              }
            )
            addItem(
              QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                linkId = "repeated-group-b"
                text = "Group question B"
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "nested-item-b"
                    text = "Basic question"
                  }
                )
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "another-nested-item-b"
                    text = "Basic question"
                  }
                )
              }
            )
            addItem(
              QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                linkId = "repeated-group-b"
                text = "Group question B"
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "nested-item-b"
                    text = "Basic question"
                  }
                )
                addItem(
                  QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
                    linkId = "another-nested-item-b"
                    text = "Basic question"
                  }
                )
              }
            )
          }
      )
    } finally {
      observer.cancel()
      ShadowLooper.runUiThreadTasksIncludingDelayedTasks()
      observer.cancelAndJoin()
    }
```

2022-11-02 11:59 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    )
@kevinmost sorry the sample code isn't necessarily tidied up - but please feel free to use this and modify the test. thanks!

2022-11-04 18:29 UTC, kevinmost commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    )
Wrapping these calls in `viewModelScope.launch(Dispatchers.Main) { ... }` eliminates the need for `ShadowLooper` calls.

I made a `runViewModelBlocking` helper function, and replaced all of our other `ShadowLooper` usages with this helper.

2022-11-07 13:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    )
this is great - thanks!

2022-11-07 15:29 UTC, jingtang10 approved these changes
thanks kevin - approved.

just a commen to add some tests for the group header widget. once that's done please feel free to merge

2022-11-07 15:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt
> +        addItemButton.visibility =
this needs a test?

2022-11-10 14:19 UTC, merged