drop down item with valueString answer options selection crash fixed
google/android-fhir pull request #1560
Opened 2022-08-18 14:41 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1542 

**Description**
1. App crash on drop down item re-selection with valueString as Answer option
2. 2. test cases added for same

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-08-19 06:51 UTC, jingtang10 requested changes

2022-08-19 06:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +          questionnaireItemViewItem.answers.singleOrNull()?.value?.toString() ?: ""
the logic for display value coding object needs to be present here: if there's a display field, we should show that, and if there isn't, we fall back to the coding string itself.

this needs to be consistent for the entire library. but i feel currently we're not doing a good job making sure that the same logic is called everywhere.

we probably should have some kind of extension function on `Type` to unify this logic for different types, so you can call `value?.displayValue` here.

2022-08-25 10:24 UTC, jingtang10 approved these changes

2022-08-25 10:24 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +        require(answerType == "Coding" || answerType == "string") {
matching answer type with the widget type choice/open should probably be in a function (see line 283 below which is the same).

2022-08-25 11:36 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +        require(answerType == "Coding" || answerType == "string") {
Done

2022-08-25 11:36 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +          questionnaireItemViewItem.answers.singleOrNull()?.value?.toString() ?: ""
Done

2022-08-25 11:55 UTC, merged