Clearing the old state of date and date-time ViewHolders
google/android-fhir pull request #1581
Opened 2022-09-05 15:08 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1580 

**Description**

**Cause:** 
The date and date time view holders only set text to the TextInput if it was empty before. This logic is required when answer update causes an update in the adapter and subsequent bindView on the ViewHolder.
 But, this causes issue when the ViewHolder is recycled for a new QuestionnaireItem and the ViewHolder retains the old text (date).

**Fix:**
Cleanup up the the ViewHolder state when bind is called for a different QuestionnaireItem.

**Alternative(s) considered**
1. [RecyclerView.Adapter#onViewRecycled](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#onViewRecycled(VH)) could be used to forward a callback to the individual `QuestionnaireItemViewHolderDelegate` to do cleanup.
2. Have a way for `QuestionnaireItemViewHolderDelegate` to know that the bind is called as an update for the same item user is updating or is a regular bind.

Both of these require refactoring in all the `QuestionnaireItemViewHolderDelegate` and can be taken as a separate PR if required.

**Type**
Choose one: Bug fix
**Screenshots (if applicable)**
[Date Picker](https://user-images.githubusercontent.com/18224849/188478128-ecdb8c37-1b0f-4563-878d-eff548b143a1.webm)
[Date Time Picker](https://user-images.githubusercontent.com/18224849/188478268-009d7201-44e2-44be-86a7-3dbd0e889372.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-06 05:22 UTC, santosh-pingle reviewed
If possible, can you please add one positive and negative test case in both pickers, otherwise it looks ok to me. thanks!

2022-09-07 06:05 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +    }
nit: is it ok to have this logic in test itself, so that test will be more readable?

2022-09-07 06:05 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
> +  fun `bind multiple times with separate QuestionnaireItemViewItem should show proper date and time`() {
nit : ditto

2022-09-07 16:49 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +    assertThat(viewHolder.dateInputView.text.toString()).isEqualTo("11/19/21")
This tests the case of overriding the old date with the new date. The function tests 3 cases in total :
Empty -> Text, Text -> New Text, Text to Empty.

2022-09-07 16:49 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
> +    assertThat(viewHolder.timeInputView.text.toString()).isEqualTo("2:30 AM")
This tests the case of overriding the old date/ time with the new date/time. The function tests 3 cases in total :
Empty -> Text, Text -> New Text, Text to Empty.

2022-09-07 16:50 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +    }
IMO this makes test more readable.

2022-09-07 16:53 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +  fun `bind multiple times with different QuestionnaireItemViewItem should show proper date`() {
The name would be misleading unless the test in broken into  2 separate tests.

2022-09-07 16:53 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
> +  fun `bind multiple times with separate QuestionnaireItemViewItem should show proper date and time`() {
The name would be misleading unless the test in broken into  2 separate tests.

2022-09-09 16:32 UTC, jingtang10 requested changes

2022-09-09 16:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    if (answer == null || inputDate == null) return true
why do you need this as a separate condition?

2022-09-09 16:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  val localDate = LocalDate.of(date.year + 1900, date.month + 1, date.date)
do we not have a java util `Date` to `LocalDate` conversion util function anywhere?

2022-09-09 16:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            LocalDateTime.of(it.year, it.month + 1, it.day, it.hour, it.minute, it.second)?.also {
likewise

2022-09-12 08:46 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  val localDate = LocalDate.of(date.year + 1900, date.month + 1, date.date)
No, we don't have any utility for this.

2022-09-12 08:46 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            LocalDateTime.of(it.year, it.month + 1, it.day, it.hour, it.minute, it.second)?.also {
No, we don't have any utility for this.

2022-09-12 10:00 UTC, jingtang10 approved these changes

2022-09-12 10:03 UTC, merged