Configurable Bundle size to upload to the server
google/android-fhir pull request #1584
Opened 2022-09-07 15:29 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1483

**Description**
1. Added `UploadConfiguration` that the users can provide via `FhirSyncWorker` to override the max size of upload Bundle.
2. Added internal `Splitter` interface that `BundleUploader` now depends on to split all the `LocalChanges` into smaller chunks based on the provided `UploadConfiguration`.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-13 07:12 UTC, PallaviGanorkar commented on engine/src/test/java/com/google/android/fhir/sync/upload/SplitterTest.kt
> +    changes.forEach { println(it.resourceId) }
I think this print statement is not required

2022-09-13 08:51 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +            Splitter.create(UploadConfiguration())
can we use  Splitter.DEFAULT here

2022-09-13 08:51 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +            Splitter.create(UploadConfiguration())
same comment about use of Splitter.DEFAULT

2022-09-13 08:51 UTC, PallaviGanorkar commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +            Splitter.create(UploadConfiguration())
Also is it possible to provide configurable UploadConfiguration() here

2022-09-14 05:22 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/SplitterTest.kt
> +    changes.forEach { println(it.resourceId) }
done

2022-09-14 05:23 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +            Splitter.create(UploadConfiguration())
Added upload config as param.

2022-09-14 05:23 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +            Splitter.create(UploadConfiguration())
Added upload config as param.

2022-09-15 12:55 UTC, PallaviGanorkar commented
Thanks @aditya-07 
Other changes LGTM, Code Owner to have look once

2022-09-21 13:38 UTC, jingtang10 commented
@joiskash please take a look at this to see if this suits your needs.

2022-09-21 13:54 UTC, jingtang10 requested changes

2022-09-21 13:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/Splitter.kt
> +internal fun interface Splitter {
to me this more like a local change pager, or local change paginator. or local change chunker/bundler.

2022-09-21 13:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +  val resourceTypes: List<ResourceType>? = null
i'm not sure about the necessity of including this in the same PR - can we delay this as it might be useful for the future but not immediately blocking the functionality of splitting local changes.

2022-09-21 13:54 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/upload/SplitterTest.kt
> +  fun `SizeSplitter split should return 3 lists inorder`() {
```suggestion
  fun `SizeSplitter split should return 3 lists in order`() {
```

2022-09-21 13:54 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
> +      .isEqualTo(3)
```suggestion
    assertThat(result.all { it.first.type == Bundle.BundleType.TRANSACTION })
```

2022-09-21 13:54 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
> +    assertThat(result.map { it.first.entry.size }.filter { it == 1 }.size).isEqualTo(3)
same here

2022-09-22 06:44 UTC, joiskash commented
> @joiskash please take a look at this to see if this suits your needs.

This looks good, I was just wondering if referential integrity is maintained if we upload in the order of the changes created.

2022-09-22 07:34 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/Splitter.kt
> +internal fun interface Splitter {
Renamed to `LocalChangesPaginator`.

2022-09-22 07:34 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/SplitterTest.kt
> +  fun `SizeSplitter split should return 3 lists inorder`() {
Done.

2022-09-22 07:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +  val resourceTypes: List<ResourceType>? = null
Removed this and associates Splitter + Tests.

2022-09-22 07:35 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
> +      .isEqualTo(3)
done

2022-09-22 07:35 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
> +    assertThat(result.map { it.first.entry.size }.filter { it == 1 }.size).isEqualTo(3)
Done

2022-09-22 07:44 UTC, aditya-07 commented
> > @joiskash please take a look at this to see if this suits your needs.
> 
> This looks good, I was just wondering if referential integrity is maintained if we upload in the order of the changes created.

Order doesn't matter if all the associated resources ( in terms of referential integrity) are in the same Bundle.
But, if they are split into separate Bundles,  referential integrity is maintained as long as the changes are created in the correct order e.g. An Encounter should be created before the associated Observations. 
`FhirEngine.create(vararg resource: Resource)` creates the resources in order they are provided. So, as long as the create api is called with a correctly ordered list, referential integrity during uploads should be maintained.

2022-09-22 11:40 UTC, joiskash commented
> Order doesn't matter if all the associated resources ( in terms of referential integrity) are in the same Bundle.
> But, if they are split into separate Bundles,  referential integrity is maintained as long as the changes are created in the correct order e.g. An Encounter should be created before the associated Observations. 
> `FhirEngine.create(vararg resource: Resource)` creates the resources in order they are provided. So, as long as the create api is called with a correctly ordered list, referential integrity during uploads should be maintained.

Ok.. this may not be followed unless forced by the SDK. In our implementation, we checked for each resource that is referred to by the current resource and uploaded that first before uploading the current resource.

2022-09-22 12:53 UTC, jingtang10 commented
@williamito will you please be able to help with updating the documentation?

2022-09-22 12:53 UTC, jingtang10 approved these changes
thanks @aditya-07 

can you please hold off merging this until @joiskash provides some feedback?

2022-09-22 13:02 UTC, jingtang10 commented
> > Order doesn't matter if all the associated resources ( in terms of referential integrity) are in the same Bundle.
> > But, if they are split into separate Bundles,  referential integrity is maintained as long as the changes are created in the correct order e.g. An Encounter should be created before the associated Observations.
> > `FhirEngine.create(vararg resource: Resource)` creates the resources in order they are provided. So, as long as the create api is called with a correctly ordered list, referential integrity during uploads should be maintained.
> 
> Ok.. this may not be followed unless forced by the SDK. In our implementation, we checked for each resource that is referred to by the current resource and uploaded that first before uploading the current resource.

the server might not have the referential integrity enforced either. in those cases this is not a problem.

however, i am very wary of opening up the uploader any further (e.g. letting the app decide the order of upload). we can have a separate discussion about that.

2022-09-22 13:08 UTC, merged