Fix resource update
google/android-fhir pull request #160
Opened 2021-01-20 14:37 UTC by deepankarb

* Change from delete and reinsert to updating the rows via query
* Change non-existent resource update test to expect no insertion

2021-01-20 14:54 UTC, jingtang10 requested changes

2021-01-20 14:54 UTC, jingtang10 commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +                        "!")
nit

```suggestion
        Truth.assertThat(resourceNotFoundInDbException.message).isEqualTo(
            "Resource not found with type ${TEST_PATIENT_2.resourceType.name} and id ${TEST_PATIENT_2_ID}!"
        )
```

2021-01-20 14:54 UTC, jingtang10 commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +                { database.select(Patient::class.java, TEST_PATIENT_2_ID) })
nit on indentation

```suggestion
        val resourceNotFoundInDbException = assertThrows(
            ResourceNotFoundInDbException::class.java,
            { database.select(Patient::class.java, TEST_PATIENT_2_ID) }
        )
```

2021-01-20 14:54 UTC, jingtang10 commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +    fun update_nonExistingResource_shouldNotInsertResource() {
```suggestion
    fun update_nonExistingResource_shouldThrowResourceNotFoundInDbException() {
```

2021-01-20 14:54 UTC, jingtang10 commented on fhirengine/src/main/java/com/google/fhirengine/db/impl/dao/ResourceDao.kt
> +                iParser.encodeResourceToString(resource))
```suggestion
        updateResource(
            resource.id,
            resource.resourceType,
            iParser.encodeResourceToString(resource)
        )
```

2021-01-20 14:54 UTC, jingtang10 commented on fhirengine/src/test-common/java/com/google/fhirengine/resource/TestingUtils.kt
> +                iParser.encodeResourceToString(expected))
nit: always leave the closing bracket on a new line

more examples https://kotlinlang.org/docs/reference/coding-conventions.html

2021-01-20 15:00 UTC, jingtang10 commented
Thanks for the fast change @deepankarb!

I think you'll need to re-index the reource in the ResourceDao.kt

2021-01-20 15:53 UTC, deepankarb commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +    fun update_nonExistingResource_shouldNotInsertResource() {
We are not throwing on `ResourceDao.update()` because the underlying raw query does not update any rows. To verify that no rows were modified we load the non-existent resource which throws. It's not the update mewthod which is throwing. Should we still name it as suggested?

2021-01-21 04:49 UTC, deepankarb commented
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fandroid-fhir%2Fpull%2F160) for more info**.

@googlebot I fixed it.

2021-01-21 10:54 UTC, jingtang10 requested changes

2021-01-21 10:54 UTC, jingtang10 commented on fhirengine/src/test-common/java/com/google/fhirengine/resource/TestingUtils.kt
> +                .isEqualTo(iParser.encodeResourceToString(expected))
nit: odd indentation. can you change to 4?

2021-01-21 11:02 UTC, deepankarb commented on fhirengine/src/test-common/java/com/google/fhirengine/resource/TestingUtils.kt
> +                .isEqualTo(iParser.encodeResourceToString(expected))
I thought I did that. Will fix.

2021-01-21 13:52 UTC, deepankarb commented on fhirengine/src/test-common/java/com/google/fhirengine/resource/TestingUtils.kt
> +                iParser.encodeResourceToString(expected))
Moved entire method call to next line.

2021-01-21 13:56 UTC, jingtang10 approved these changes

2021-01-21 13:56 UTC, jingtang10 commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +            /* ktlint-enable max-line-length */
oh sorry feel free to put this in 2 lines. i didn't realise my suggestion was too long.

2021-01-21 13:56 UTC, jingtang10 commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +        val resourceNotFoundException =
can this val be removed?

2021-01-21 13:56 UTC, jingtang10 commented on fhirengine/src/test/java/com/google/fhirengine/impl/FhirEngineImplTest.kt
> +                        "!"
use the same kotlin string format (with $ signs) as the previous comment.

2021-01-21 13:58 UTC, deepankarb commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +            /* ktlint-enable max-line-length */
I think this is better since the other option is harder to write/maintain even in an IDE.

2021-01-21 14:08 UTC, deepankarb commented on fhirengine/src/androidTest/java/com/google/fhirengine/db/impl/DatabaseImplTest.kt
> +        val resourceNotFoundException =
I don't think so.

2021-01-21 14:46 UTC, merged