CQL combo 2.0.0 Upgrade - Full PD$apply implementation
google/android-fhir pull request #1603
Opened 2022-09-12 20:08 UTC by vitorpamplona

Fixes #1403, #1423, #1407, #1365, #915, #656, #718, #1189 
Unlocks: #1334, #1055
Depreciates: #1395

**Description**
Migrates the CQL Translator, Engine, and Evaluator to version 2.0, which enables the on-device compilation of CQL as well as import/export of JSON and XML executable libraries, dependent libraries and model info. Upgrades HAPI to 6.0.1 and Java to 11, min SDK to 26, reorganizes the dependency stack, and creates a new module to share workflow testing assets (code and data) between androidTest and test. 

This PR brings the full functionality of the $apply operator on the server side to Android. 

**Alternative(s) considered**
No

**Type**
Choose one: Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-16 00:01 UTC, vitorpamplona commented
@jingtang10 @fredhersch @pld @ktarasenko 

CQL 2.0 is good to go. This proposal moves us to minSDK 26, pending confirmation from all stakeholders.

2022-09-16 14:41 UTC, ktarasenko requested changes
Amazing! Thanks for the update!

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt
> +object CqlBuilderUtils {
Utils classes were abolished in Kotlin, feel free to use the 
https://kotlinlang.org/docs/java-to-kotlin-interop.html#package-level-functions 
use `@file:JvmName("CqlBuilderUtils")` for java interop, same for other utils

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt
> +      Assert.fail("Could not compile CQL File. Errors:\n$errors")
use static import for `fail`, same in the other classes

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilderUtils.kt
> +  fun assembleFhirLib(
I'd really prefer 3 different functions, but for test utils this is ok

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/XMLAssert.kt
> +        ) // Overrides an incomplete implementation
move the comment up

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/XMLAssert.kt
> +    Assert.assertFalse(diff.fullDescription(), diff.hasDifferences())
We use `Truth` for other tests, it reads a bit better

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java
> +import java.util.*;
please avoid * imports

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java
> +public class MockFhirDal implements FhirDal {
Technically it's FakeFhirDal

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/MockFhirDal.java
> +/*
Please convert it to Kotlin, it will help saving some boilerplate

2022-09-16 14:41 UTC, ktarasenko commented on workflow/src/test/java/com/google/android/fhir/workflow/plandefinition/PlanDefinitionProcessorJavaTests.kt
> +    test(
Wow, this is hard to read, by now I already forgot what test() function does .  I also don't like that the whole structure of the test (init-act-assert) is hidden inside the function.  
What if we: 
- turn `test` to `generateCarePlan` and explicitly name parameters there 
- turn the assertion into kotlin extension function for example `CarePlan.assertEquals(json)` 


The same comments apply for CqlBuilderTestBase

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java
> +            fail("Unable to compare jsons: " + e.getMessage());
can fail accept an exception?

2022-09-16 14:41 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java
> +public class PlanDefinitionProcessorTestBase {
Inheritance in the tests is kind of discouraged. 

Do you think converting it to a TestRule will be a lot of effort?

2022-09-16 15:24 UTC, vitorpamplona commented on buildSrc/build.gradle.kts
> +  implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.0.1")
There is a buildSrc/../codegen/GenerateSourcesTask class that uses FhirContext and FhirVersionEnum. This is called by the :engine's generateSourcesTask

2022-09-16 15:30 UTC, vitorpamplona commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java
> +            fail("Unable to compare jsons: " + e.getMessage());
No :(

2022-09-16 16:12 UTC, vitorpamplona commented on workflow/src/test/java/com/google/android/fhir/workflow/plandefinition/PlanDefinitionProcessorJavaTests.kt
> +    test(
We can try to make a fluid interface for these Test Utils 

What about something like: 
```kotlin
CqlBuilderAssert
  .that("/cql-compiler/FHIRHelpers-4.0.1.cql")
  .compiles()
  .generatesJsonEqualsTo("/cql-compiler/FHIRHelpers-4.0.1.elm.json")
  .generatesXmlEqualsTo("/cql-compiler/FHIRHelpers-4.0.1.elm.xml")
  .generatesFhirLibraryEqualsTo("/cql-compiler/FHIRHelpers-4.0.1.fhir.json")
```

And PlanDefinition to: 
```kotlin
PlanDefinitionAssert
  .thatGeneratedCarePlan(
    "ChildRoutineVisit-PlanDefinition-1.0.0", 
    "Patient/ChildRoutine-Reportable", 
    null
  )
  .withData("/plan-definition-apply/child-routine-visit/child_routine_visit_patient.json")
  .withLibrary("/plan-definition-apply/child-routine-visit/child_routine_visit_plan_definition.json")
  .isEqualTo("/plan-definition-apply/child-routine-visit/child_routine_visit_careplan.json")
```

2022-09-16 16:16 UTC, vitorpamplona commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/plandefinition/PlanDefinitionProcessorTestBase.java
> +public class PlanDefinitionProcessorTestBase {
these are copy/paste classes from the `evaluator.plandefinition` module. I left them as is to simplify adding new test cases from changes on  the `evaluator.plandefinition`. If we rewrite them in Kotlin, we could also make use of the FhirOperator instead of recreating the evaluator for these test cases.

2022-09-17 14:47 UTC, ktarasenko approved these changes
Love the fluent interface for the testing lib!

2022-09-17 14:47 UTC, ktarasenko commented on workflow-testing/src/main/java/com/google/android/fhir/workflow/testing/CqlBuilder.kt
> +      org.junit.Assert.fail("Could not compile CQL File. Errors:\n$errors")
static import

2022-09-26 20:33 UTC, vitorpamplona commented
@jingtang10 this PR is now running engine and sdc in 24 and workflow on 26, ready for review.

2022-09-28 09:03 UTC, maimoonak commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
Fro reference the reference depends on the type of referenced entity. Plz chekc an example in this PR. https://github.com/google/android-fhir/pull/1624/files#diff-6f6f5e0316d326e6597666ce4608dce8607c00e2172e2f0facddf4fdc408c3aeR75

The Task needs special handling for our CQL.
Task sends `requestor` as contextPath (automatically driven from somewhere in cql-evaluator), and the context and contextValue is Patient and its `id`. This does not filter Tasks correctly as `requestor` is Practitioner most of the times and we need Tasks of a Patient by `for` field.

2022-09-28 13:03 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
do we know why this behaviour exists? I don't see the same map `requested` -> `for` in other retrieve implementations. This could be a bug in the evaluator. Do we have a specific plan definition that generates this type of retrieve call?

2022-09-28 13:05 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
This test case does work, but it has to use "for" 

```kotlin
    val result =
      retrieveProvider.retrieve(
        context = "Patient",
        contextPath = "for",
        contextValue = "P2",
        dataType = "Task",
        templateId = null,
        codePath = null,
        codes = null,
        valueSet = null,
        datePath = null,
        dateLowPath = null,
        dateHighPath = null,
        dateRange = null
      )
        .map { it as Task }
```

2022-09-28 17:02 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
Got it! The issue should be resolved in the modelInfo, not at the RetrieveProvider https://github.com/DBCG/cql_engine/issues/621

2022-09-29 12:34 UTC, maimoonak commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
@vitorpamplona do we have any timeline the modelInfo issue. Can we add a temporary fix for Task with a TODO until the actual issues resolves. 
cc: @f-odhiambo can comment better on the priority of measure report indicators we are using (so basically our indicators using Task as denomintor/numerator would return 0 until we have the issue fixed)

2022-09-29 12:57 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
Can we make a unit test with the complete measure-evaluate in question? We need to ensure the solution addresses your use case because there are other ways to get a `requester` and not a `for` on $apply definitions and expression evaluations. I just don't know how exactly you are getting that retrieve.

2022-09-29 12:59 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
The issue of hardcoding this in the engine is that somebody else might be using the `requester` instead of the `for`. It would break for them to make this use case work.

2022-10-05 14:18 UTC, pld commented
@Tarun-Bhardwaj can you give an update on this? since this is approved, and the failures seem to be network related, is it possible to go ahead and merge?

2022-10-06 01:32 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +          ReferenceClientParam(ann.name),
Resolved on: https://github.com/DBCG/cql_engine/pull/624

2022-10-06 02:15 UTC, vitorpamplona commented
We also need more memory for the GitHub Actions machines. Either that or we need to stop running things in parallel with shared gradle deamon.

2022-10-06 18:04 UTC, vitorpamplona commented
@jingtang10 now without the changes in the test environment (P->O), as requested.

2022-10-07 15:41 UTC, jingtang10 approved these changes

2022-10-07 15:41 UTC, jingtang10 commented on contrib/barcode/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt
> - * Copyright 2021 Google LLC
can you please revert these files that only have a license header change?

2022-10-07 15:44 UTC, jingtang10 approved these changes

2022-10-07 15:44 UTC, jingtang10 commented on workflow-testing/build.gradle.kts
> +plugins {
is there anyway to do this without creating another top-level gradle module?

2022-10-07 16:05 UTC, vitorpamplona commented on contrib/barcode/src/test/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/UtilsTest.kt
> - * Copyright 2021 Google LLC
copyright changes reverted.

2022-10-10 14:44 UTC, merged