Skip hidden field from validation
google/android-fhir pull request #1610
Opened 2022-09-19 10:07 UTC by maimoonak

Fixes #1579 

**Description**
Hidden field does not qualify for any validation. Response validation marks hidden field as valid and passes validation irrespective of it value

**Alternative(s) considered**
The validation skips the hidden field in when doing questionnaire-reponse validation. The other option could have doing it inside each and every validator but that makes it repetitive, non central, and does not keep room to revert it easily for specific validator types in future. 

**Type**
Choose one: Bug fix 

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-19 13:36 UTC, ellykits commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +          ConstraintValidator.ConstraintValidationResult(true, "Field is hidden")
Should the text `"Field is hidden"` be translatable?

2022-09-19 13:39 UTC, shoaibmushtaq25 approved these changes
Thanks @maimoonak. LGTM. :+1:

2022-09-22 09:08 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +          ConstraintValidator.ConstraintValidationResult(true, "Field is hidden")
This is not used anywhere on UI, so translation is not required.

2022-09-23 08:09 UTC, ellykits approved these changes
LGTM :+1:

2022-09-30 12:12 UTC, jingtang10 commented
@maimoonak please use the assignee field to assign PRs to reviewers for a faster turn around

2022-09-30 13:57 UTC, jingtang10 requested changes
thanks @maimoonak !

2022-09-30 13:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +          ConstraintValidator.ConstraintValidationResult(true, "Field is hidden")
please move this logic to the beginning of this function.

if a questionnaire item is hidden, validation should be skipped altogether.

at the moment, you're still going through all the possible validators and generating a valid result for each of them. this is unnecessary.

2022-09-30 13:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> -
thank you for catching this problem and fixing it.

2022-09-30 13:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
> +  fun `validation passes for required questionnaire item with hidden extension when value specified`() {
personally, i don't think this test case is needed. it's not exercising any new code paths compared with the previous test case.

2022-09-30 13:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +          ConstraintValidator.ConstraintValidationResult(true, "Field is hidden")
i also think in this case you probably should return `NotValidated`

2022-10-03 22:32 UTC, jingtang10 approved these changes
Thanks

2022-10-04 13:58 UTC, merged