Skip logic Behavior implemented in Catalog app
google/android-fhir pull request #1611
Opened 2022-09-19 12:42 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1526

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-07 12:24 UTC, jingtang10 requested changes

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/assets/skip_logic_behavior_questionnaire.json
> +{
please rename this file to `behavior_skip_logic.json`

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/BehaviorListViewModel.kt
> +    val workFlow: WorkflowType = WorkflowType.COMPONENT
i feel this workflow type thing is getting confusing. for this at least please rename it to component and behavior.

@santosh-pingle i feel this abstraction (workflow type) is not really capturing what needs to be set in the different screens. we should just set different themes and different menu buttons in different sections of the catalog app.

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_demo_questionnaire.xml
> +    <com.google.android.material.card.MaterialCardView
can you try to do a code reformat in android studio? (and then run spotless) that will reorder the attributes in a nice way.

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +        infoCard.visibility = View.VISIBLE
i would normally put this at the end so that you update the content before showing the actual card. so there's no reflow/glitch in the UI.

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_demo_questionnaire.xml
> +        android:layout_marginBottom="@dimen/info_card_view_margin_bottom"
start and end can be replaced with horizontal.

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_demo_questionnaire.xml
> +        android:visibility="visible"
can you remove this?

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_demo_questionnaire.xml
> +        android:layout_marginTop="@dimen/info_card_view_margin"
```suggestion
        android:layout_marginTop="@dimen/info_card_margin"
```

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_demo_questionnaire.xml
> +                android:layout_marginBottom="@dimen/info_header_margin_bottom"
this is inconsistent:

```suggestion
                android:layout_marginBottom="@dimen/info_card_header_margin_bottom"
```

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/values/dimens.xml
> +  <dimen name="info_card_icon_padding">8dp</dimen>
move this to after line 15

2022-10-07 12:24 UTC, jingtang10 commented on catalog/src/main/res/values/strings.xml
> +  <string name="behavior">Behavior</string>
can this be removed?

2022-10-11 08:34 UTC, PallaviGanorkar commented on catalog/src/main/java/com/google/android/fhir/catalog/BehaviorListViewModel.kt
> +    val workFlow: WorkflowType = WorkflowType.COMPONENT
Created another WorkflowType.BEHAVIOR as though theme is same as WorkflowType.COMPONENT but don't required menu item.

2022-10-14 13:44 UTC, jingtang10 approved these changes
thanks Pallavi!

2022-10-16 18:52 UTC, merged