Add support for "Help" questionnaire item control
google/android-fhir pull request #1617
Opened 2022-09-21 10:44 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1528

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-22 06:08 UTC, santosh-pingle commented
@shelaghm 
Below material3 style is applied for Help (title and subtitle text in card view), as shared figma style was as per material2.
-  Text typography `TextAppearance.Material3.TitleSmall` and text color `colorOnSurfaceVariant` is applied for Help title text.
-  Text typography `TextAppearance.Material3.BodyMedium` and text color `colorOnSurfaceVariant` is applied for help subtitle (description) text.

2022-09-22 23:13 UTC, shelaghm commented
@santosh-pingle those textstyles and colors look good. Thanks for checking with me. I have now updated the figma with the M3 style.

2022-09-23 11:11 UTC, jingtang10 requested changes

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Returns true if any one of the nested display item has [DisplayItemControlType.HELP] control. */
```suggestion
/** Whether any one of the nested display item has [DisplayItemControlType.HELP] control. */
```

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> + * Returns [true] if item type is display and [displayItemControl] is
```suggestion
 * Whether item type is display and [displayItemControl] is
```

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> + * [DisplayItemControlType.FLYOVER].
```suggestion
 * [DisplayItemControlType.HELP].
```

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun `localizedHelpSpanned should returns help`() {
```suggestion
  fun `localizedHelpSpanned should return help`() {
```

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun `localizedHelpSpanned should returns null if no help code`() {
```suggestion
  fun `localizedHelpSpanned should return null if no help code`() {
```

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun `localizedHelpSpanned does not match locale should returns help`() {
```suggestion
  fun `localizedHelpSpanned not matching locale should return help`() {
```

2022-09-23 11:11 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun `localizedHelpSpanned returns localized text for matching locale`() {
```suggestion
  fun `localizedHelpSpanned matching locale should return localized text`() {
```

2022-09-26 11:43 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +      if (isHelpCardViewVisible) {
done.

2022-09-29 10:37 UTC, jingtang10 approved these changes

2022-09-29 12:31 UTC, merged