Flyover text added for open choice view
google/android-fhir pull request #1625
Opened 2022-09-23 07:39 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1516

**Description**
1. added support for flyover text in in open choice view in SDC library
2. Updated json for open choice component with flyover extension
**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 
**Screenshots (if applicable)**
![FlyoverForOpenChoiceView](https://user-images.githubusercontent.com/13957417/191912412-0f599fad-8ea7-4844-89c1-ee936be27716.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-23 09:00 UTC, santosh-pingle commented
@PallaviGanorkar 
Can you please also attached screenshot for `Modal component` with flyover text?

2022-09-23 12:26 UTC, PallaviGanorkar commented
> @PallaviGanorkar Can you please also attach screenshot for `Modal component` with flyover text?

I have already attached screen from catalog app open choice component, Are you expecting something else?

2022-09-26 06:24 UTC, santosh-pingle reviewed
It looks good to me, except few optional comments. thanks!

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/modal-questionnaire.json
> +                    "display": "Fly-over"
nit : let's remove line no. 22.

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/modal-questionnaire.json
> +                "text": "Flyover"
nit : let's remove line no. 25.

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/modal_with_validation_questionnaire.json
> +                    "display": "Fly-over"
nit: ditto

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/modal_with_validation_questionnaire.json
> +                "text": "Flyover"
nit: ditto.

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/open-choice-questionnaire.json
> +                    "display": "Fly-over"
nit: ditto

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/open-choice-questionnaire.json
> +                "text": "Flyover"
nit : ditto

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/open_choice_with_validation_questionnaire.json
> +                    "display": "Fly-over"
nit : ditto

2022-09-26 06:24 UTC, santosh-pingle commented on catalog/src/main/assets/open_choice_with_validation_questionnaire.json
> +                "text": "Flyover"
nit: ditto

2022-09-26 06:24 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt
> +        holder.summaryHolder.hint =
If possible can you please check whether unit test can be written to assert whether text is assigned to hint field?

2022-09-30 10:45 UTC, jingtang10 requested changes

2022-09-30 10:45 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun bindView_SetHintText() {
```suggestion
  fun bindView_setHintText() {
```

2022-09-30 10:45 UTC, jingtang10 commented on catalog/src/main/assets/open_choice_with_validation_questionnaire.json
> +                "text": "Flyover"
this is not done?

2022-09-30 10:45 UTC, jingtang10 commented on catalog/src/main/assets/open_choice_with_validation_questionnaire.json
> +                    "display": "Fly-over"
this is not done?

2022-09-30 15:46 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun bindView_SetHintText() {
Done

2022-10-07 12:35 UTC, jingtang10 approved these changes
looks good. thanks @PallaviGanorkar

2022-10-12 06:36 UTC, merged