Asterisk support.
google/android-fhir pull request #1644
Opened 2022-09-30 10:29 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #544

**Description**
Append * to question text if required field is true.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-09-30 13:23 UTC, jingtang10 requested changes

2022-09-30 13:23 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +      localizedTextSpanned?.toString()?.plus("*")?.toSpanned()
1) can you make this into a separate string resource? and 2) add a space between the text and the asterisk 3) can you apply the typical red color to it? use the material colour attributes?

2022-09-30 13:37 UTC, aditya-07 requested changes
Added a few comm

2022-09-30 13:37 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderView.kt
> +    question.updateTextAndVisibility(questionnaireItem.localizedTextSpannedWithAsterisk)
In the error state, please change the * to red colour. (see https://github.com/google/android-fhir/issues/544#issuecomment-1256568985)

2022-09-30 13:37 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +    question.updateTextAndVisibility(questionnaireItem.localizedTextSpannedWithAsterisk)
Same as above.

2022-09-30 13:37 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  @Test
If possible, add tests for error state as well.

2022-09-30 13:37 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +    assertThat(view.findViewById<TextView>(R.id.question).text.toString()).isEqualTo("Question?*")
There should be some space between the end of text and the asterisk .

2022-09-30 13:37 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
> +    assertThat(view.findViewById<TextView>(R.id.question).text.toString()).isEqualTo("Question?*")
Same as above for space and maybe error state test.

2022-10-03 05:21 UTC, santosh-pingle commented
working on review comments.

2022-10-04 07:17 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  @Test
@aditya-07 Can you please mention the use in error state to assert it.

2022-10-04 07:18 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
> +    assertThat(view.findViewById<TextView>(R.id.question).text.toString()).isEqualTo("Question?*")
ditto

2022-10-04 11:15 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/193805017-5b74d28d-c117-4896-8d83-fda0b32ca14a.mov

2022-10-07 10:54 UTC, jingtang10 requested changes

2022-10-07 10:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +        )
this is optional since this is really a nit: might be nice to have this as a util function on builder called `SpannableStringBuilder.appendWithSpan`.

2022-10-07 10:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +  fun `Does not show * at the end of question text`() {
starts with lower case

and below

2022-10-07 10:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +    assertThat(view.findViewById<TextView>(R.id.question).text.toString()).isEmpty()
duplicate?

2022-10-07 10:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +  fun `Does not show * at the end of question text`() {
I do think it's important we make sure asterisk is shown consistently whenever the question is a required question.

If we take the approach of not showing the asterisk for questions with no text, then it's difficult for the user to trust the asterisk, because even questions that don't have it might still be required if the text is empty.

I'm ok with showing the asterisk even if the text is empty. Even if it might look a little odd. I think having the asterisk in those cases will give the user a consistent experience and therefore they can use the asterisk as a hint reliably.

If we don't show it just becasue a question doesn't have a text, then we might as well not show it at all in all cases.

@shelaghm please let us know if you disagree.

2022-10-07 19:07 UTC, shelaghm commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +  fun `Does not show * at the end of question text`() {
@jingtang10 I agree that we need to be consistent and always show the * even if there's no text, so people can learn what the * means and it also helps people troubleshoot errors

2022-10-11 10:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +  fun `Does not show * at the end of question text`() {
thanks shelagh! just an additional comment - i really don't believe having a question without text is a very common thing. the questionnaire author is really at their own peril if they do that.

2022-10-11 11:10 UTC, jingtang10 approved these changes
thanks @santosh-pingle

2022-10-11 11:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +  resolveRefs: Boolean = true
can you remove these 2 optional params that are not used anywhere? unless there's a reason and a usecase we know that really needs this in the code.

2022-10-11 11:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +  view.findViewById<TextView>(R.id.question).updateTextAndVisibility(builder)
some issue with this function (effectively an internal API).

but here there's this assumption that the view (the first param of this API) has a descendent of id `question`.

i feel you could just pass the descendent as the first param directly, so that the logic to find the text view to be updated can be at the call site.

2022-10-11 11:10 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +  fun `shows * though question text is missing`() {
```suggestion
  fun `shows * even if question text is missing`() {
```

2022-10-12 05:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +  view.findViewById<TextView>(R.id.question).updateTextAndVisibility(builder)
done.

2022-10-12 05:34 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireGroupTypeHeaderViewTest.kt
> +  fun `shows * though question text is missing`() {
done.

2022-10-13 08:29 UTC, aditya-07 approved these changes

2022-10-13 14:43 UTC, Tarun-Bhardwaj commented
@santosh-pingle , since the PR is approved, can the changes be merged and the associated issue be closed?

2022-10-14 05:07 UTC, merged