Add top margin to error text.
google/android-fhir pull request #1655
Opened 2022-10-07 07:12 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1586

**Description**
Single choice, Boolean choice, Multiple choice error text was not having top margin.
Top margin is given to error text.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-07 07:12 UTC, santosh-pingle commented
@shelaghm 
Before change 
<img width="422" alt="Screen Shot 2022-10-07 at 12 40 48 PM" src="https://user-images.githubusercontent.com/86107848/194491950-8f8572e8-756e-47fd-8013-d3b6fcb0ef2d.png">
<img width="422" alt="Screen Shot 2022-10-07 at 12 40 35 PM" src="https://user-images.githubusercontent.com/86107848/194492015-313b46d7-f83c-43d1-88f4-9724690ba779.png">
<img width="422" alt="Screen Shot 2022-10-07 at 12 40 24 PM" src="https://user-images.githubusercontent.com/86107848/194492202-c3fdb526-5b24-46c6-9c48-133000dc16ca.png">


After change
<img width="422" alt="Screen Shot 2022-10-07 at 12 29 29 PM" src="https://user-images.githubusercontent.com/86107848/194487186-44e81df0-6f63-484d-ac41-8e976774c1fd.png">
<img width="422" alt="Screen Shot 2022-10-07 at 12 28 59 PM" src="https://user-images.githubusercontent.com/86107848/194487210-1c5913b8-d1a1-48a0-bff0-672a65744487.png">
<img width="422" alt="Screen Shot 2022-10-07 at 12 28 29 PM" src="https://user-images.githubusercontent.com/86107848/194487243-f87ccb4a-5ce6-4360-8787-cf1f0d6f048e.png">

2022-10-07 18:37 UTC, shelaghm commented
@santosh-pingle @jingtang10 The top margin padding looks good. 

However, I'm a bit concerned that the error message for Single choice, Boolean choice, Multiple choice error text is being displayed at the bottom of the list. I was assuming the error text for these components would be displayed in the `instructions`  text field. What are your thoughts on this?

Example:
<img width="207" alt="Screen Shot 2022-10-07 at 11 36 51" src="https://user-images.githubusercontent.com/86378921/194626575-bbb555af-eacf-4aad-bd2e-2a5e3b934a4f.png">

2022-10-11 08:00 UTC, santosh-pingle commented
> @santosh-pingle @jingtang10 EDIT**: Please reference padding suggestions in #1586
> 
> > Spacing: @santosh-pingle what is the line spacing on the text element for the EntryFormat / error text?
> > According to our M3 guidelines, the line height of the text is 16px, the font is 12px and with 4px padding. I'm guessing the issue is that the text line spacing is not 16px, which is why it looks like less padding than it should be?
> 
> However, I'm a bit concerned that the error message for Single choice, Boolean choice, Multiple choice error text is being displayed at the bottom of the list. I was assuming the error text for these components would be displayed in the `instructions` text field. What are your thoughts on this?
> 
> Example: <img alt="Screen Shot 2022-10-07 at 11 36 51" width="207" src="https://user-images.githubusercontent.com/86378921/194626575-bbb555af-eacf-4aad-bd2e-2a5e3b934a4f.png">

@shelaghm 
Actually, there are other views where we shows error text at the bottom.

2022-10-11 10:01 UTC, jingtang10 commented
> > @santosh-pingle @jingtang10 EDIT**: Please reference padding suggestions in #1586
> > > Spacing: @santosh-pingle what is the line spacing on the text element for the EntryFormat / error text?
> > > According to our M3 guidelines, the line height of the text is 16px, the font is 12px and with 4px padding. I'm guessing the issue is that the text line spacing is not 16px, which is why it looks like less padding than it should be?
> > 
> > 
> > However, I'm a bit concerned that the error message for Single choice, Boolean choice, Multiple choice error text is being displayed at the bottom of the list. I was assuming the error text for these components would be displayed in the `instructions` text field. What are your thoughts on this?
> > Example: <img alt="Screen Shot 2022-10-07 at 11 36 51" width="207" src="https://user-images.githubusercontent.com/86378921/194626575-bbb555af-eacf-4aad-bd2e-2a5e3b934a4f.png">
> 
> @shelaghm Actually, there are other views where we shows error text at the bottom.

@santosh-pingle what do you mean?

2022-10-11 10:54 UTC, jingtang10 commented
just to clarify what santosh meant (just discussing with him)

We have 2 types of widgets

1. widgets that are derivatives of the text input layout from material. these include all the text input widgets (integer, single line, multi line etc), the date and date time inputs (because we use the text field to display the date and time), drop down (again, we use a text field to display the selected value). because we use the text input layout from material for these widgets, they already have the error text correctly laid out 4dp below the text input.
2. widgets that have custom layout that we have written - single, boolean, multiple choices and potentially others.

just a note - we don't necessarily have to use the material error text either in the first type of widgets, we could also create another error text field and place it elsewhere instead of using the text input layout's error field. but that's a different question.

2022-10-11 21:10 UTC, shelaghm commented
@santosh-pingle @jingtang10 I think the 4dp padding looks fine on the radio button. It is consistent with M3 guidelines, so let's keep this as Santosh has implemented and not make further adjustments on the padding.

2022-10-11 21:11 UTC, shelaghm commented
> 2\. widgets that have custom layout that we have written - single, boolean, multiple choices and potentially others.

Thanks for the context, this is very helpful.

2022-10-18 15:12 UTC, jingtang10 commented
any update here @santosh-pingle?

2022-10-18 15:33 UTC, santosh-pingle commented
> any update here @santosh-pingle?

These changes are obsolete now. 
As per discussion which we had in ux design call, error text will be shown just below the instructions.
I have not started working on it yet, as there were other priority task.

Can you please help me to know the priority of this task vs sdc module testing which I supposed to start on tomorrow after ux testing build?

2022-11-01 13:52 UTC, santosh-pingle commented
@shelaghm 
<img width="426" alt="Screen Shot 2022-10-31 at 4 14 25 PM" src="https://user-images.githubusercontent.com/86107848/199248960-4508cadb-e340-4938-8565-1c00d64da938.png">
<img width="466" alt="Screen Shot 2022-10-31 at 4 14 50 PM" src="https://user-images.githubusercontent.com/86107848/199248989-f70a180d-9902-481d-bc0b-6fa7f61ebfb3.png">
<img width="433" alt="Screen Shot 2022-10-31 at 4 15 10 PM" src="https://user-images.githubusercontent.com/86107848/199249020-3a67c14c-bc80-4e9b-b21a-d3ee4388445c.png">

2022-11-01 16:18 UTC, jingtang10 requested changes
can you update the PR name please? thanks

2022-11-01 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
> +  fun `shows custom error text`() {
not sure what is meant by custom here. can you please remove? same for the next test case.

2022-11-02 05:33 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +    fun TextView.showError() {
working on this change.

2022-11-02 05:33 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +  fun showCustomErrorText(errorText: String? = null, isErrorTextVisible: Boolean = true) {
working on this change.

2022-11-02 05:33 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewTest.kt
> +  fun `shows custom error text`() {
working on this change.

2022-11-04 13:14 UTC, jingtang10 approved these changes

2022-11-04 13:14 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +  fun showErrorText(errorText: String? = null, isErrorTextVisible: Boolean = true) {
add documentation here to say that this is showing error in the header. and widgets could either use this, or use another view (i.e. TextInputLayout's error field) to display error.

2022-11-08 05:23 UTC, santosh-pingle commented
Closing this pr as cla/google check is failing, which ask other author approval which is not required.
Instead created PR#1700

2022-11-08 05:23 UTC, closed without merging