Highlight missing fields and Show validation popup.
google/android-fhir pull request #1671
Opened 2022-10-17 22:15 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1576 

**Description**
1. Validate questionnaire response after user clicks Submit button.
2. Based on the validation result,  highlight missing fields and Show missing fields popup.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature

**Screenshots (if applicable)**
![Screenshot_20221018_034336](https://user-images.githubusercontent.com/18224849/196293669-ae92ad5e-965b-4d45-a641-1f4e67ace50e.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-19 17:01 UTC, omarismail94 reviewed
@aditya-07 took an initial look and left some comments. PTAL and lmk what you think!

2022-10-28 08:40 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +        addItem(QuestionnaireResponse.QuestionnaireResponseItemComponent(StringType("name-id")))
The `linkid` doesn't have to be same across tests and its just a coincidence here. So, I just want to keep the `linkid` localised to the tests itself for better readability.

2022-10-28 08:44 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          modificationCount.update { count -> count + 1 }
Added `count` as having `it` was causing warning from IDE `Implicit parameter 'it' of enclosing lambda is shadowed`.  But it makes sense to keep it consistent, so have added a named param for the `also`.

2022-10-28 08:48 UTC, aditya-07 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="ok">Ok</string>
Done.

2022-10-28 08:50 UTC, aditya-07 commented on datacapture/src/main/res/layout/questionnaire_validation_error_dialog.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Since the layout if for the Custom Material Dialog and not the fragment itself, we shouldn't append `_fragment` to the name.

2022-10-28 08:50 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +  fun `createCustomView with invalid`() {
Done

2022-10-28 08:50 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +    )
Done

2022-10-28 08:52 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +      .isEqualTo(1)
Done. The Recycler view isn't actually drawn in this test unless the code explicitly asks it. So, had to modify the tests for that.

2022-10-28 08:53 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +  fun createCustomView(context: Context = requireContext()): View {
Done.

2022-10-28 11:48 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +  //  @Test fun `createCustomView` () {
Yes. Removed.

2022-11-03 11:34 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          forceValidate = true
Once `forceValidate` is set to `true`, it makes sure that each page is validated (show inline errors) going forward as the user swipes back and forth. We don't want to set it to `false` as it would stop validating page (showing inline errors) for some entry modes.

2022-11-09 17:49 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +  }
how do you feel about creating a factory method for this ViewModel so that `questionnaire` and `validation` become values as opposed to variables , and we get rid of this function?

2022-11-16 11:29 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +              "QuestionnaireValidationErrorMessageDialogFragment"
Done

2022-11-16 11:30 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +  }
Since we need to access the same ViewModel in both the Fragments to pass data, it isn't possible to create ViewModel with params in one place and access the same one in other fragment.

2022-11-22 17:13 UTC, jingtang10 requested changes
as i commented in the issue - if you can modify the dialog to have two buttons that'd be great. one button to go back to questionnaire, another to submit.

2022-11-22 17:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +data class ValidationErrorDataModel(val linkId: String, val questionnaireItemText: String)
add documentation

2022-11-22 17:13 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +  fun `createCustomView with a valid questionnaire response validation result`() {
i don't really think you need this test case

2022-11-28 08:28 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +            .isEmpty()
Done, but flattened map values instead.

2022-11-28 08:28 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var forceValidate = false
Done, changed to hasPressedSubmitButton

2022-11-28 08:29 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * Validates questionnaire and return the validation results. As a side effect, it triggers the UI
Done

2022-11-28 08:48 UTC, aditya-07 commented on datacapture/src/main/res/values/strings.xml
> +    >Complete all required fields</string>
Done.

2022-11-28 08:49 UTC, aditya-07 commented on datacapture/src/main/res/values/strings.xml
> +    <string
Grouped validation strings, can do rest in a separate PR.

2022-11-28 08:50 UTC, aditya-07 commented on datacapture/src/main/res/values/styles.xml
> +        <item name="android:visibility">visible</item>
Updated the PR.

2022-11-28 08:52 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +  fun onCreateCustomView(layoutInflater: LayoutInflater = getLayoutInflater()): View {
Tried inflating the popup with regular context and styles weren't applied to the popup.

2022-11-28 08:52 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +data class ValidationErrorDataModel(val linkId: String, val questionnaireItemText: String)
Done

2022-11-28 08:52 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragmentTest.kt
> +  fun `createCustomView with a valid questionnaire response validation result`() {
Removed.

2022-11-28 14:09 UTC, jingtang10 requested changes

2022-11-28 14:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +private val ValidationDiffCallback =
discussed with @aditya-07.

i suggest that we do not use recycler view here. i think this is making this pr more complicated. in reality we just want a simple bulleted list.

2022-12-02 07:45 UTC, aditya-07 commented on datacapture/src/main/res/layout/questionnaire_validation_error_dialog.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Done

2022-12-02 07:46 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireValidationErrorMessageDialogFragment.kt
> +private val ValidationDiffCallback =
Done. The errors are now line separated string displayed in a textbox.

2022-12-02 15:32 UTC, jingtang10 approved these changes

2022-12-04 20:19 UTC, merged