load different profile for definition based extraction
google/android-fhir pull request #1676
Opened 2022-10-19 08:28 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1659

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-11-02 14:01 UTC, jingtang10 requested changes

2022-11-02 14:01 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +           ]
this field in meta is saying that this resource (Questionnaire) confirms to a certain profile... so this looks wrong to me.

2022-11-09 15:22 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +             "definition": "http://fhir.org/guides/who/anc-cds/StructureDefinition/anc-patient#Patient.birthTime",
As per discussion in https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/meta.2Eprofile.20for.20resource.20in.20Definition.20based.20extraction, implementation is changed and updated PR

2022-11-11 13:37 UTC, jingtang10 requested changes

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +            getStructureDefinition("structure_definition_who_patient.json", context)
add documentation here to specify where this file comes from - it's important for us to update the test case in the future etc.

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ProfileLoader.kt
> + * different profiles.
```suggestion
 * Loads `StructureDefinition` for profile based on canonical URL.
```

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ProfileLoader.kt
> +   * @return StructureDefinition resource conform to this StructureDefinition/Profile
```suggestion
   * @return a [StructureDefinition] with the specified canonical `url`
```

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ProfileLoader.kt
> +   * field (eg. questionnaire.meta.profile)
```suggestion
   * @param url the canonical URL for the [StructureDefinition] to be loaded. This may come from `resource.meta.profile` or as part of `questionnaire.item.definition` to inform extraction of values into fields definied in the profile.
```

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     * Resource claims to conforms to.
```suggestion
     * [MutableMap] from canonical URLs to [StructureDefinition]s of profiles to avoid calling the profile loader multiple times.
     *
```

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val profiles: List<CanonicalType> = questionnaire.meta.profile
why is this needed?

2022-11-11 13:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    profileLoader: ProfileLoader?
it feels like a lot to pass these two down the call chain. would it not be easier to create a version of profile loader that also does caching (storing in structure definition map) and than pass that down.

2022-11-14 09:00 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val profiles: List<CanonicalType> = questionnaire.meta.profile
As per FHIR standard if any resource conforms to different profile then respective canonical URL must be mentioned in resource.meta.profile field. So i have kept this line for future use if any thing required from questionnaire StructureDefinition while resource extraction from questionnaire.

2022-11-14 10:18 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    profileLoader: ProfileLoader?
Instead of passing it down to every function, I have defined  structureDefinitionMap: MutableMap<String, StructureDefinition> as class level private variable for cache

2022-11-16 13:30 UTC, jingtang10 requested changes

2022-11-16 13:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +          ?.value
can remove these 2 lines? just checking the extension is null.

2022-11-16 13:30 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +  private lateinit var questionnaireResponse: QuestionnaireResponse
make this into consts so they don't need to be in setup. so that test cases not using these don't have go to through the same setup.

call it something like questionnaire with birth time and questionnaire response with birth time etc.

2022-11-16 13:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // Variable to check whether extension defined in profile
```suggestion
      // Whether the field is defined as an extension in the profile
```

2022-11-21 10:56 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      var structureDefinition = structureDefinitionMap.get(canonicalUrl)
Can not use this method as default value  in getOrPut can not be null

2022-11-21 13:32 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    structureDefinitionMap.clear()
create a version of profile loader that also does caching

2022-11-30 13:42 UTC, jingtang10 requested changes

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureDefinitionCanonicalUrls.kt
> +/*
optional: you could just have this in the resource mapper file.

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +                return structureDefinitionMap[url.toString()]
```suggestion
              structureDefinitionMap[url.toString()]?.also{ return it }
```

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    profileLoader: ProfileLoader?
i think? you can remove ? from all the following private functions for profile loader.

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        profileLoader?.loadProfile(CanonicalType(canonicalUrl))
```suggestion
        profileLoader.loadProfile(CanonicalType(canonicalUrl))
```

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      var isExtensionSupported = false
is this really needed?

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      val structureDefinition: StructureDefinition? =
i think this can even be inlined?

2022-11-30 13:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        /* eg for "definition": "http://fhir.org/guides/who/anc-cds/StructureDefinition/anc-patient#Patient.address.address-preferred"
use // instead of /* */ for inline comments

2022-11-30 14:49 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureDefinitionCanonicalUrls.kt
> +/*
This field is no more required. So removed it.

2022-11-30 17:31 UTC, jingtang10 requested changes

2022-11-30 17:31 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +    assertThat(dateTimeType.timeZone).isEqualTo(expectedDateTimeType.timeZone)
can you not just do `assertThat(dateTimeType).isEqualTo(expectedDateTimeType)`

2022-11-30 17:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ProfileLoader.kt
> +   * @return a [StructureDefinition] with the specified canonical `url`
```suggestion
   * @return a [StructureDefinition] with the specified canonical `url`, or `null` if it cannot be found
```

2022-11-30 17:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    //     "id" : "Patient.extension:birthPlace",
why is id relevant in this example?

2022-11-30 17:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    //     "id" : "Patient.extension:birthPlace",
i find this example really confusing i don't feel like it's explaining the process of extracting a field in the profile to me

2022-11-30 17:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // Resource
i don't feel this is very important to be called out here.

2022-12-01 07:18 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +    assertThat(dateTimeType.timeZone).isEqualTo(expectedDateTimeType.timeZone)
it does not work , fails with error "non-equal instance of same class with same string representation"

2022-12-01 07:51 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    //     "id" : "Patient.extension:birthPlace",
After code optimization missed to move this example in different function, not this example is added in isExtensionSupportedByProfile() method. Here "id" and "path" is part of ElementDefinition from StructureDefinition.

2022-12-01 11:53 UTC, jingtang10 requested changes

2022-12-01 11:53 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +    assertThat(dateTimeType.timeZone).isEqualTo(expectedDateTimeType.timeZone)
ok i think we have seen this before - but why doesn't this work? is there a fix? which part of the code is throwing this error?

please simplify this

2022-12-01 11:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +             */
i think it's better to use inline style //

2022-12-01 11:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    //
i'm still not sure what these examples are actually donig.

you just have to explain what they are demonstrating

2022-12-01 13:34 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +            // This json file is available at
```suggestion
            // This JSON file is available at
```

2022-12-01 13:36 UTC, jingtang10 approved these changes

2022-12-01 13:36 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/mapping/ResourceMapperInstrumentedTest.kt
> +            // in WHO IG can be downloaded as raw json file
```suggestion
            // in WHO IG can be downloaded as raw JSON file
```

2022-12-01 13:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +            // Mutable map of key-canonical url as string for profile and
```suggestion
            // Mutable map of key-canonical url as string for profile and
```

2022-12-01 13:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +              if (profileLoader == null) {
```suggestion
              if (profileLoader == null) {
```

2022-12-01 14:07 UTC, merged