Add support for Attachment widget
google/android-fhir pull request #1680
Opened 2022-10-20 09:03 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1621 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-26 13:18 UTC, FikriMilano commented
Here's a demo

[Attachment demo.webm](https://user-images.githubusercontent.com/62053304/198035687-756dbe36-43c6-4b58-9fb7-2621e710f3f6.webm)

2022-10-26 13:54 UTC, FikriMilano commented
3 button scenario:

1. Image only
<img src="https://user-images.githubusercontent.com/62053304/198044710-f514ab32-8c73-4d16-8bd0-084afe1df52f.png" width="200">

2. Image and Non Image
<img src="https://user-images.githubusercontent.com/62053304/198033830-0ed2364c-94bb-4211-9287-857991719367.png" width="200">

3. Non Image
<img src="https://user-images.githubusercontent.com/62053304/198044533-aa1f16b9-a5bd-4502-9846-2913bf1a16ad.png" width="200">

2022-10-30 22:00 UTC, ekigamba requested changes

2022-10-31 20:34 UTC, ekigamba requested changes

2022-11-01 11:50 UTC, ekigamba requested changes

2022-11-02 08:49 UTC, FikriMilano commented
@jingtang10 Can we use dependencies that have a BSD license? 
In this PR, I'm using Glide, which uses a BSD license.

2022-11-04 07:17 UTC, FikriMilano commented on catalog/src/main/assets/attachment_questionnaire.json
> +        }
I don't have that doc.

But what I know is, currently the SDK allows instruction extension to be nested in a questionnaire item.
It will be completely handled by questionnaire header.

2022-11-04 07:17 UTC, FikriMilano commented on catalog/src/main/assets/attachment_with_validation_questionnaire.json
> +        }
I don't have that doc.

But what I know is, currently the SDK allows instruction extension to be nested in a questionnaire item.
It will be completely handled by questionnaire header.

2022-11-04 07:24 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal fun Questionnaire.QuestionnaireItemComponent.hasMimeType(mimeType: String): Boolean {
sure

2022-11-04 07:27 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal fun Questionnaire.QuestionnaireItemComponent.hasMimeTypeOnly(mimeType: String): Boolean {
sure

2022-11-04 07:31 UTC, FikriMilano commented on datacapture/src/main/res/layout/input_error_text_view.xml
> -    android:layout_marginStart="@dimen/item_margin_horizontal"
Yes, it's intentional, and it should apply to all views.

I noticed all the usages of this error layout have 16 dp horizontal margin already, and having this change avoids having 32 dp margin instead.

2022-11-04 07:34 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +                context.getString(R.string.image_uploaded),
Hmm, since this error message is for Take Photo scenario, perhaps it would make sense to keep it.

2022-11-04 07:38 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +            android:ellipsize="middle"
Sure, thanks, I missed this one

2022-11-04 07:44 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +                  context.getString(R.string.upload_failed),
I think this is fine.
The Snackbar error message is to let the user know there's something wrong; it's short and quick.
Then the complete error message will be displayed by the error layout, which will not disappear until addressed.

It's what the design says too.

2022-11-04 07:45 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +                context.getString(R.string.image_uploaded),
It's what the design says too.

2022-11-09 13:20 UTC, ekigamba requested changes

2022-11-09 13:20 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +            displaySnackbar(takePhoto, R.string.upload_failed)
We probably need to delete the temporary file here also

2022-11-09 13:20 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +            displaySnackbar(takePhoto, R.string.upload_failed)
We should probably delete the file here also

2022-11-10 08:37 UTC, ekigamba requested changes

2022-11-10 08:37 UTC, ekigamba commented on catalog/src/main/assets/attachment_questionnaire.json
> +{
rename this file to `component_attachment.json` and the other file to `component_attachment_with_validation.json` to match the naming pattern of these questionnaires

2022-11-10 08:37 UTC, ekigamba commented on catalog/src/main/assets/attachment_with_validation_questionnaire.json
> +{
rename this file to  `component_attachment_with_validation.json` to match the naming pattern of these questionnaires

2022-11-10 08:37 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +class QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest {
Nice work

2022-11-10 08:37 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +    assertThat(viewHolder.itemView.findViewById<Button>(R.id.upload).visibility)
You can add tests to assert that the `take_photo` button's visibility is `GONE`

2022-11-10 08:37 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldShowPreviewVideoFileFromAnswer() {
This test is similar to the previous one other than the `QuestionnaireResponse.answer[0].attachment.title` which changes. The test name makes it sound as if this was based on the general mime type but I see that the actual mime type is `application/pdf`

2022-11-10 08:37 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +    val questionnaireItemView =
This test is similar to the previous one other than the `QuestionnaireResponse.answer[0].attachment.title` which changes. The test name makes it sound as if this was based on the general mime type but I see that the actual mime type is `application/pdf`

2022-11-10 08:37 UTC, ekigamba commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldShowSelectFileButtonOnly() {
You can add other tests cases to show this for `audio/*` and `video/*` and name the tests appropriately to show the distinction. Good work! I understood a lot of the workings just from the tests :smile:

2022-11-18 06:55 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  return uploadedFileSize > (maxSizeInB ?: BigDecimal(0))
Whops, you're right

2022-11-18 08:22 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +              questionnaireItem.maxSizeInMB
Fixed

2022-11-18 08:22 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +            displayError(
Fixed

2022-11-18 08:30 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        upload.setOnClickListener { onUpload(questionnaireItem) }
Done

2022-11-18 08:36 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +            displaySnackbar(takePhoto, R.string.upload_failed)
Thanks, missed that one

2022-11-18 08:39 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +class QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest {
Thanks

2022-11-18 08:44 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +    assertThat(viewHolder.itemView.findViewById<Button>(R.id.upload).visibility)
Done

2022-11-18 08:52 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldShowPreviewVideoFileFromAnswer() {
I updated those accordingly

2022-11-18 08:52 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +    val questionnaireItemView =
I updated those accordingly

2022-11-18 08:52 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldShowSelectFileButtonOnly() {
Thanks, I forgot to change some things in those tests

2022-11-22 10:25 UTC, jingtang10 commented on datacapture/src/main/res/layout/input_error_text_view.xml
> -    android:layout_marginStart="@dimen/item_margin_horizontal"
please see https://github.com/google/android-fhir/issues/1586. i think the starting margin for hte error text is intentional.

2022-11-22 13:01 UTC, jingtang10 requested changes
thanks @FikriMilano

2022-11-25 09:07 UTC, FikriMilano commented on datacapture/src/main/res/layout/input_error_text_view.xml
> -    android:layout_marginStart="@dimen/item_margin_horizontal"
Okay, will revert

2022-11-25 09:10 UTC, FikriMilano commented on buildSrc/src/main/kotlin/LicenseeConfig.kt
> +      because("BSD Clause. https://github.com/bumptech/glide#license")
Added

2022-11-25 11:29 UTC, FikriMilano commented on buildSrc/src/main/kotlin/LicenseeConfig.kt
> +    allow("BSD-2-Clause")
yeah, now removed.

initially, this was added because the exceptions below doesn't seem to work, in the past.
now it works, somehow.

2022-11-25 12:15 UTC, FikriMilano commented on catalog/src/main/AndroidManifest.xml
> +        android:requiredFeature="true"
`required` default value is true.
for line 27 only, should we set it as false instead?

we can remove 28.

2022-11-25 12:32 UTC, FikriMilano commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      R.string.component_name_attachment,
<img src="https://user-images.githubusercontent.com/62053304/203986338-49c8bb75-b063-459d-b302-f9904cf3216d.png" width="200">

2022-11-25 12:34 UTC, FikriMilano commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.Glide.glide)
sure

2022-11-25 12:39 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +    <ImageView
makes sense

2022-12-26 06:22 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +class CameraLauncherFragment : DialogFragment() {
the main reason I did this is because `registerForActivityResult` can only be declared in the `onCreate` method of a Fragment or Activity, and DialogFragment makes it easier to do so.

at first, I tried to declare it in QuestionnaireFragment, but I couldn't find a simple way to do it.

2022-12-26 06:22 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +            android:textAppearance="@style/TextAppearance.Material3.BodySmall"
sure

2022-12-26 06:33 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
it's a habit of mine, we can use LinearLayout if you prefer

2022-12-26 06:34 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        if (questionnaireItem.hasGeneralMimeTypeOnly(GeneralMimeTypes.IMAGE.value)) {
that's true, I can try that

2022-12-26 07:02 UTC, FikriMilano commented on catalog/src/main/AndroidManifest.xml
> +        android:requiredFeature="true"
so I ended up writing it this way, since `required` default value is `true`

```
<uses-permission
    android:name="android.permission.CAMERA"
    android:required="false"
/>
```

2022-12-27 20:13 UTC, shelaghm commented
@FikriMilano please use [this file attachment icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aattach_file%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048) for the widget page. 

Size: 48px, color #1A73E8

2023-01-02 07:59 UTC, FikriMilano commented
Thanks!

2023-01-02 08:09 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +  const val MIME_TYPE = "mime_type"
Sure

2023-01-02 08:09 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +  const val SAVED_PHOTO_URI = "saved_photo_uri"
Sure

2023-01-02 08:11 UTC, FikriMilano commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      R.string.component_name_attachment,
Solved

2023-01-02 08:30 UTC, FikriMilano commented on datacapture/src/main/res/drawable/audio_file.xml
> +<vector
<img src="https://user-images.githubusercontent.com/62053304/210208284-d320f746-0791-4b95-b836-09371cfea21a.png" width="250">      <img width="380" alt="Screen Shot 2023-01-02 at 15 29 31" src="https://user-images.githubusercontent.com/62053304/210208374-e1c31a87-f450-4ba3-b60e-5cc17746d719.png">

2023-01-02 08:37 UTC, FikriMilano commented on datacapture/src/main/res/drawable/camera.xml
> +<vector
<img src="https://user-images.githubusercontent.com/62053304/210208284-d320f746-0791-4b95-b836-09371cfea21a.png" width="250">      <img width="414" alt="Screen Shot 2023-01-02 at 15 35 42" src="https://user-images.githubusercontent.com/62053304/210209059-703a91db-090c-4d98-b156-0aa881024650.png">

2023-01-02 08:42 UTC, FikriMilano commented on datacapture/src/main/res/drawable/image_file.xml
> +<vector
<img src="https://user-images.githubusercontent.com/62053304/210209356-3103f8a9-faef-4bb9-ac4f-83e2583ccdf5.png" width="250">      <img width="414" alt="Screen Shot 2023-01-02 at 15 41 21" src="https://user-images.githubusercontent.com/62053304/210209386-e4b526f9-21f9-4f71-9603-f332ca35adff.png">

2023-01-02 08:44 UTC, FikriMilano commented on datacapture/src/main/res/drawable/video_file.xml
> +<vector
<img src="https://user-images.githubusercontent.com/62053304/210209552-03468fa9-6713-4156-b3ac-924d37f6d25e.png" width="250"> <img width="414" alt="Screen Shot 2023-01-02 at 15 44 15" src="https://user-images.githubusercontent.com/62053304/210209620-4ccc0cd0-4405-4e07-b4bc-fbbdfcd83a8f.png">

2023-01-02 08:47 UTC, FikriMilano commented on datacapture/src/main/res/drawable/file.xml
> +<vector
<img src="https://user-images.githubusercontent.com/62053304/210209717-432e4d5d-c3ff-4c8c-8957-99775f9ce66e.png" width="250"> <img width="414" alt="Screen Shot 2023-01-02 at 15 46 04" src="https://user-images.githubusercontent.com/62053304/210209793-273fb336-8a53-419e-b1f6-9daf117cc635.png">

2023-01-02 08:48 UTC, FikriMilano commented on datacapture/src/main/res/drawable/delete.xml
> +<vector
<img src="https://user-images.githubusercontent.com/62053304/210209552-03468fa9-6713-4156-b3ac-924d37f6d25e.png" width="250"> <img width="414" alt="Screen Shot 2023-01-02 at 15 47 23" src="https://user-images.githubusercontent.com/62053304/210209925-fc256434-eb8b-4f91-824b-9cf2f5cbfc99.png">

2023-01-02 08:49 UTC, FikriMilano commented on datacapture/src/main/res/values/strings.xml
> +    <string name="take_photo">Take Photo</string>
<img src="https://user-images.githubusercontent.com/62053304/198033830-0ed2364c-94bb-4211-9287-857991719367.png" width="250">

2023-01-02 08:49 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +    <ImageView
<img src="https://user-images.githubusercontent.com/62053304/198034535-93d288e5-4eb0-4fa2-93ac-ede8c95989b8.png" width="250">

2023-01-03 00:15 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal fun Questionnaire.QuestionnaireItemComponent.hasGeneralMimeType(
sure

2023-01-03 00:17 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  generalMimeType: String
sure

2023-01-03 00:17 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal fun Questionnaire.QuestionnaireItemComponent.hasGeneralMimeTypeOnly(
sure

2023-01-03 00:17 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal enum class GeneralMimeTypes(val value: String) {
sure

2023-01-03 06:11 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal fun Questionnaire.QuestionnaireItemComponent.hasGeneralMimeType(
sure

2023-01-03 11:34 UTC, jingtang10 commented on catalog/src/main/AndroidManifest.xml
> +        android:requiredFeature="true"
thanks - this seems correct to me.

2023-01-03 11:38 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      R.string.component_name_attachment,
@FikriMilano can you please move this to lower and replace `image`?

also, can you please do me a favour and move up auto complete to before date picker?

so the order should be:

...
...
text filed
auto complate
date picker
date time picker
attachment
repeated group

2023-01-03 12:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +private val SIZE_UNIT_DIVIDER = BigDecimal(1024)
please resolve this

2023-01-03 12:32 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +    assertThat(viewHolder.itemView.findViewById<ConstraintLayout>(R.id.file_preview).visibility)
i think this cast needs to be fixed:

```
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
	at com.google.android.fhir.datacapture.views.QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.shouldShowPreviewAudioFileFromAnswer(QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt:323)
```

2023-01-03 12:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +class CameraLauncherFragment : DialogFragment() {
fair enough. you do need a fragment to launch a new activity. but the widget itself is a view - thanks for the explanation. 

if you can add a little documentation that'd be great. for example at the top of the class say something like `Used for launching camera activity` and `Used for launching open document activity`

2023-01-03 12:48 UTC, FikriMilano commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      R.string.component_name_attachment,
surely

2023-01-03 12:49 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInB: BigDecimal?
surely

2023-01-03 12:50 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    return maxSizeInKB?.div(SIZE_UNIT_DIVIDER)
okay, will do that

2023-01-03 12:51 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +private val SIZE_UNIT_DIVIDER = BigDecimal(1024)
sure, I can try the B->KB and B->MB

2023-01-03 12:52 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +class CameraLauncherFragment : DialogFragment() {
@jingtang10 are you ok with this?

2023-01-03 12:54 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +class CameraLauncherFragment : DialogFragment() {
I made it as seamless as possible that the user won't see the initial / greyish fragment showing.

2023-01-03 12:56 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +class CameraLauncherFragment : DialogFragment() {
ah okay, I just saw your comment below.
sure, I will add some documentation for these classes

2023-01-03 13:55 UTC, jingtang10 requested changes

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +  const val MIME_TYPE = "mime_type"
this hasn't been resovled yet

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +      return
what if you don't dismiss and return?

one problem i found is that after i grant the camera permission (for the first time) i'll have to click the camera button again. can we make it so we don't need to do that?

thanks

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +    const val RESULT_REQUEST_KEY = "result"
make the actual string much less generic please - something like camera result at least

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        delete.setOnClickListener {
might as well make this into a separate function.

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +              loadDeleteButton(R.string.delete_image)
load delete button line can be outside of this `when` block

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +
hey can this and line 130-153 be extracted into a function?

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        }
i don't feel it's important to change the upload button icon depending on if image is the only mime type allowed. (@shelaghm fyi)

so we can actually just simplify this logic to set the visibility of take photo button depending on if image is allowed.

the upload button will always be the same. i think you can just get ride of the `loadUploadButton` function.

2023-01-03 13:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/SelectFileLauncherFragment.kt
> +    registerForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
i think you need to set the mime type filter here too. can you do that?

2023-01-03 17:13 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +      return
I had this issue as well when testing

2023-01-03 17:55 UTC, omarismail94 reviewed
Great change Fikri! Left some comments as well

2023-01-03 17:55 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +  override fun onCreate(savedInstanceState: Bundle?) {
one small nice to have: adding a "back" button in the camera app. In the default Android Messages app, if you open the camera within the app, when the camera launches, there is a back button you can press on the top left

2023-01-03 17:55 UTC, omarismail94 commented on catalog/src/main/assets/component_attachment_with_validation.json
> +          "text": "Media types supported: jpg, png, .mp3, .mp4, pdf",
nit: consistency with regards to adding the `.` before the extension. Either add it for all the extensions or remove for all. Here and in the other JSON file

2023-01-03 17:55 UTC, omarismail94 commented on catalog/src/main/assets/component_attachment_with_validation.json
> +      "text": "Select an image to upload",
nit: make this more accurate as to what the function is: Select an image or file to upload

2023-01-03 17:55 UTC, omarismail94 commented on catalog/src/main/assets/component_attachment_with_validation.json
> +      "text": "Select an image to upload",
here and in the other json

2023-01-03 17:55 UTC, omarismail94 commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +        android:layout_marginTop="@dimen/padding_default"
add `android:contentDescription` to any ImageView. Example: https://github.com/google/android-fhir/blob/master/contrib/barcode/src/main/res/layout/top_action_bar_in_live_camera.xml

2023-01-03 17:55 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          delete.alpha = 1F
if this is the default, can we set this parameters in the XML file?

For example, for takePhoto, having this line in the Button field:
       
```
 android:alpha="1"
```

this way, we can remove this entire else statement

2023-01-03 17:55 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          clearDeleteButton()
when uploading files or images, we also display a snackbar. Do we need to do the same when deleting images or files?

2023-01-03 22:29 UTC, shelaghm commented on datacapture/src/main/res/drawable/audio_file.xml
> +<vector
@FikriMilano yes, this icon is great for audio file.

2023-01-03 22:29 UTC, shelaghm commented on datacapture/src/main/res/drawable/camera.xml
> +<vector
@FikriMilano yes, this icon is great for take photo icon.

2023-01-03 22:30 UTC, shelaghm commented on datacapture/src/main/res/drawable/image_file.xml
> +<vector
@FikriMilano yes, this icon is great for upload photo icon.

2023-01-03 22:30 UTC, shelaghm commented on datacapture/src/main/res/drawable/video_file.xml
> +<vector
@FikriMilano yes, this icon is great for video file.

2023-01-03 22:31 UTC, shelaghm commented on datacapture/src/main/res/drawable/file.xml
> +<vector
@FikriMilano yes, this icon is great for file.

2023-01-03 22:31 UTC, shelaghm commented on datacapture/src/main/res/drawable/delete.xml
> +<vector
@FikriMilano yes, this icon is great for delete

2023-01-03 22:34 UTC, shelaghm commented on datacapture/src/main/res/values/strings.xml
> +    <string name="take_photo">Take Photo</string>
@FikriMilano these look good to me!

2023-01-03 23:17 UTC, shelaghm commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +    <ImageView
@FikriMilano @jingtang10 I've created a mockup for this so we can look at and discuss in [this comment](https://github.com/google/android-fhir/issues/1621#issuecomment-1370320599). In summary, I think constraining to a 72px thumbnail might be a good option?

2023-01-04 13:21 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +            style="?attr/questionnaireAttachmentTakePhotoButtonStyle"
surely

2023-01-04 13:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +      private lateinit var delete: Button
sure

2023-01-04 13:22 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +      private lateinit var error: TextView
sure

2023-01-04 13:23 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +      return
sure, let me see

2023-01-04 13:24 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        delete.setOnClickListener {
oh, you're right

2023-01-04 13:25 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +              loadDeleteButton(R.string.delete_image)
okay, that's true

2023-01-04 13:29 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        }
okay

2023-01-04 13:32 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/SelectFileLauncherFragment.kt
> +    registerForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
could you elaborate why we need a mime type filter here?

2023-01-04 13:36 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/SelectFileLauncherFragment.kt
> +    registerForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
open document will only show files based on the mime type provided.

say, if the mime type declared is only pdf, then it won't show image or other files, only pdfs

2023-01-04 13:36 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +  override fun onCreate(savedInstanceState: Bundle?) {
okay, let me try

2023-01-04 13:37 UTC, FikriMilano commented on catalog/src/main/assets/component_attachment_with_validation.json
> +          "text": "Media types supported: jpg, png, .mp3, .mp4, pdf",
sure

2023-01-04 13:37 UTC, FikriMilano commented on catalog/src/main/assets/component_attachment_with_validation.json
> +      "text": "Select an image to upload",
okay

2023-01-04 13:37 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +        android:layout_marginTop="@dimen/padding_default"
okay

2023-01-04 13:41 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          delete.alpha = 1F
okay, I was concerned with edit mode, but looking at other widgets, I think it's fine using your way

2023-01-04 13:43 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          delete.alpha = 1F
and perhaps I can try to use `view.isEnabled` as it's simpler to use

2023-01-04 13:53 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          clearDeleteButton()
I don't think so? 
when uploading, there is some process needs to be done before a file is ready, the snackbar acts as an indicator that the process is a success or failure.
as for delete, it's rather simple and clears everything out.

@shelaghm could you add your suggestion for this please?

2023-01-04 14:27 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_attachment_view.xml
> +    <ImageView
yeah, 72px with the new design is good and looks consistent for single/multi attachment.
looking at the discussion in there, we've agreed to have this addressed in another ticket and also because it's part of a new design for single and multi attachment as well.

@shelaghm @jingtang10 
I will change this to 200px for now

2023-01-04 15:59 UTC, shelaghm commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          clearDeleteButton()
@FikriMilano @omarismail94 Using the snackbar to display a message `sample-video.mov deleted`or `image/file/video/audio deleted` is helpful for users to see a confirmation that an action has been completed, so I recommend including one.

2023-01-05 03:02 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +          clearDeleteButton()
I see, that make sense, I will do as you suggest

2023-01-06 03:45 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        }
@jingtang10 
I have an end result of this, I hope it's simple enough

```suggestion
      private fun displayTakePhotoButton(questionnaireItem: QuestionnaireItemComponent) {
        if (questionnaireItem.hasMimeType(MimeType.IMAGE.value)) {
          takePhotoButton.visibility = View.VISIBLE
        }
      }

      private fun displayUploadButton(questionnaireItem: QuestionnaireItemComponent) {
        when {
          questionnaireItem.hasMimeTypeOnly(MimeType.IMAGE.value) -> {
            uploadPhotoButton.visibility = View.VISIBLE
          }
          questionnaireItem.hasMimeTypeOnly(MimeType.AUDIO.value) -> {
            uploadAudioButton.visibility = View.VISIBLE
          }
          questionnaireItem.hasMimeTypeOnly(MimeType.VIDEO.value) -> {
            uploadVideoButton.visibility = View.VISIBLE
          }
          questionnaireItem.hasMimeTypeOnly(MimeType.DOCUMENT.value) -> {
            uploadDocumentButton.visibility = View.VISIBLE
          }
          else -> {
            uploadFileButton.visibility = View.VISIBLE
          }
        }
      }
```

2023-01-09 04:09 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/attachment/CameraLauncherFragment.kt
> +  override fun onCreate(savedInstanceState: Bundle?) {
@omarismail94
was looking into this and I think that is a custom camera which require a lot of extra work.
should we perhaps address this in a different ticket?

cc @jingtang10

2023-01-09 13:38 UTC, FikriMilano commented
@jingtang10 this is ready for review

2023-01-16 07:21 UTC, jingtang10 approved these changes
Looks great to me! Thanks so much @FikriMilano for the excellent PR!

🎉🎉🎉

@omarismail94 FYI

2023-01-16 07:23 UTC, merged