Fix Issue #1677
google/android-fhir pull request #1684
Opened 2022-10-21 14:23 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1677 

**Description**
Run check whether to display review and submit button _after_ pages has been updated when pagination is on

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**
[device-2022-10-21-142233.webm](https://user-images.githubusercontent.com/44980219/197218932-843cae12-1b9b-4bcb-b9a5-fbe2a26744f2.webm)

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-27 12:55 UTC, jingtang10 requested changes
can we add some tests?

2022-11-01 21:42 UTC, omarismail94 commented
> can we add some tests?

Done! I added a UI test that loads a questionnaire, then clicks on the buttons to test if the `Review` button is visible

2022-11-03 16:29 UTC, jingtang10 approved these changes

2022-11-03 16:29 UTC, jingtang10 commented on datacapture/sampledata/paginated_questionnaire_with_dependent_answer.json
> +      "type": "group",
i don't think we need this group at all to be honest. this doesn't contribute to testing what we want to test. and just makes the test slower.

2022-11-04 10:13 UTC, omarismail94 commented on datacapture/sampledata/paginated_questionnaire_with_dependent_answer.json
> +      "type": "group",
Removed!

2022-11-04 10:35 UTC, merged