Add Implementation guide management library module
google/android-fhir pull request #1686
Opened 2022-10-22 12:50 UTC by ktarasenko

**Description**
Introduce an empty module for Implementation guide management library 

**Checklist**
- [] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-27 12:56 UTC, jingtang10 requested changes

2022-10-27 12:56 UTC, jingtang10 commented on settings.gradle.kts
> +include()
are these needed?

2022-11-07 12:17 UTC, ktarasenko commented on settings.gradle.kts
> +include()
removed

2022-11-07 12:17 UTC, ktarasenko commented on implementationguide/proguard-rules.pro
> +#-renamesourcefileattribute SourceFile
done

2022-11-22 14:25 UTC, jingtang10 approved these changes

2022-11-22 14:25 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Releases.kt
> +    override val name = "Android FHIR Implementation Guide management Library"
```suggestion
    override val name = "Android FHIR Implementation Guide Library"
```

2022-11-23 10:17 UTC, merged