Disable leniency in DateFormat lib when converting date
google/android-fhir pull request #1687
Opened 2022-10-24 18:32 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1638 

**Description**
By default, the [`DateFormat.parse`](https://developer.android.com/reference/java/text/DateFormat#parse(java.lang.String,%20java.text.ParsePosition)) method parsing is lenient: If the input is not in the form used by this object's format method but can still be parsed as a date, then the parse succeeds.

So in the case of `40/0/2`, with leniency set to true, it would convert this to `March 31, 5`. Not 2005. 05. FIVE! Mind blowing haha. I didnt dig into the implementation, but I assume it does `2 + 40//12 = 5` for the year, and then the remainder becomes the month and day.

**Alternative(s) considered**

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**
Date Time picker now throws validation error when typing `40/0/5`

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-31 17:48 UTC, jingtang10 requested changes

2022-10-31 17:48 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput_invalid_date_entry() {
can you add another one with 5-digit year?

2022-10-31 17:48 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput_invalid_date_entry() {
can you rename this test to be explicit about what this is testing?

I feel like in "40/0/2" there are actually 3 oddities - the month, day, and year are all unexpected and potentially invalid. So it would be good to separate them. For example, I'd like "40/5/2022", "12/0/2022" and "12/5/2022" as 3 different test cases so that you really cover everything.

2022-11-01 11:56 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
> +  fun shouldSetDateInput_invalid_date_entry() {
Added!

2022-11-01 16:22 UTC, jingtang10 approved these changes
thanks omar!

2022-11-01 17:00 UTC, merged