Add maxSize extension support
google/android-fhir pull request #1688
Opened 2022-10-25 05:23 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1675

**Description**
Allows Questionnaire Item to limit the maximum file size the user can upload

**Alternative(s) considered**
N/A

**Type**
Feature

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-10-25 07:09 UTC, shoaibmushtaq25 approved these changes
Thanks @FikriMilano. LGTM :+1:

2022-10-25 10:02 UTC, omarismail94 reviewed
Thanks @FikriMilano for this PR! Added a few comments for review. PTAL and lmk what you think!

2022-10-25 10:02 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_shouldReturnKilobytes() {
same comment as the other file. Update function name to match the correct unit name we're return. Here and everywhere else in this file

2022-10-25 10:02 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +import org.hl7.fhir.r4.model.DecimalType
is it possible to add a test that attempts to add a file that is larger than the maxSize (you can set max size to 0 or something small) and asserting that an error is thrown?

2022-10-25 12:46 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInKB: BigDecimal?
Oh that's right, we had this conversation the other day

2022-10-25 12:46 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInMB: BigDecimal?
sure

2022-10-25 12:48 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +import org.hl7.fhir.r4.model.DecimalType
I don't think it's possible in this PR.
But it should be possible on this one https://github.com/google/android-fhir/pull/1680

It will assert the error validation

2022-10-25 12:50 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +import org.hl7.fhir.r4.model.DecimalType
But I can still do something similar on this PR

2022-10-26 21:56 UTC, omarismail94 reviewed
Looks good to me! Will ask @jingtang10 to review quickly and approve!

2022-10-27 05:23 UTC, FikriMilano commented
Awesome, thanks!

2022-10-27 10:18 UTC, FikriMilano commented
@omarismail94 The CI was having a 12000 timeout error. Let me see if re-triggering it will work.

Same with this one https://github.com/google/android-fhir/pull/1678

2022-10-27 12:06 UTC, omarismail94 commented
@FikriMilano can you bring your branch up to date with `master` please?

The "Kokoro: Build and Device Tests" failed on your branch: https://source.cloud.google.com/results/invocations/eb72ef0d-76a6-40a9-8e42-f5d9de252d68/targets/openhealthstack%2Fandroid-fhir%2Fgcp_ubuntu%2Fpresubmit/log

due to an error with the CI tool setup. I fixed it but your branch doesn't have it yet

2022-10-28 06:48 UTC, FikriMilano commented
@omarismail94 the "Kokoro: Build and Device Tests" still failed

2022-10-28 10:14 UTC, omarismail94 commented
The Instrumentation test failed due to the Firebase Android phone timing out. Re-ran it and everything passed! 

@jingtang10 can you PTAL and approve?

2022-10-28 11:57 UTC, FikriMilano commented
@omarismail94 
Is it possible to give me permission to re-run such thing? I have a feeling it will happen again (in other PRs)

2022-10-28 12:00 UTC, omarismail94 commented
> @omarismail94 Is it possible to give me permission to re-run such thing? I have a feeling it will happen again (in other PRs)

I think you do! In the Labels section on the right of the PR page, you can add the `kokoro:force-run` label to get the CI to re-run

2022-10-28 12:28 UTC, FikriMilano commented
@omarismail94 
Well, I also don't have permission to add labels

2022-11-22 13:30 UTC, jingtang10 requested changes

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +private val SIZE_UNIT_DIVIDER = BigDecimal(1024)
as i commented in the other pr - i'm not a big fan of this constant. i think the meaning of this isn't' really clear.

much better just to explicitly define B->KB and B->MB. e.g. private  const BYTES_PER_KB = 1024

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    return maxSizeInB?.div(SIZE_UNIT_DIVIDER)
just go directly from b to mb (define a constant)

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Maximum size an attachment can be. Unit in Kibibytes. */
```suggestion
/** The maximum size of an attachment in Kibibytes. */
```

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Maximum size an attachment can be. Unit in Mebibytes. */
```suggestion
/** The maximum size of an attachment in Mebibytes. */
```

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_whenAnswerSizeIsAboveLimit_shouldBeKnown() {
not really sure what this test case is testing.

i feel it's not really testing any logic or functionality in this PR.

can we just remove this test case?

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_missingExtension_shouldReturnNull() {
you'd need this for kib and mib methods too.

2022-11-22 13:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInKiB: BigDecimal?
hey can you remind me why we need the kib and mib methods here? is it better for this to be handled by the ui? or is it better to keep these methods here?

2022-12-26 07:26 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    return maxSizeInB?.div(SIZE_UNIT_DIVIDER)
sure

2022-12-26 07:26 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +private val SIZE_UNIT_DIVIDER = BigDecimal(1024)
I see, so you mean to jump directly from B to other units right? 
Then sure, I'll create other constants for each of them.

2022-12-26 07:27 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Maximum size an attachment can be. Unit in Kibibytes. */
sure

2022-12-26 07:27 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Maximum size an attachment can be. Unit in Mebibytes. */
sure

2022-12-26 07:27 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_whenAnswerSizeIsAboveLimit_shouldBeKnown() {
okay

2022-12-26 07:28 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_missingExtension_shouldReturnNull() {
will add those

2022-12-26 08:33 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInKiB: BigDecimal?
Use case:
1. User uploads a file
2. Turns out the file is bigger than the Questionnaire allows
3. The widget displays an error that says e.g. "File must not be bigger than 10 MB"

2022-12-26 08:37 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInKiB: BigDecimal?
I would say to keep this here, because FHIR spec doesn't mention a specific unit to be used.
So we need to handle the units ourselves.
https://www.hl7.org/fhir/extension-maxsize.html

2022-12-26 08:42 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInKiB: BigDecimal?
But from a FHIR example below. 
They are using `Byte` as the base unit, and the system understands it as `Mebibyte` / `Bibyte` units.
https://build.fhir.org/ig/HL7/sdc/examples.html#using-mimetype-and-maxsize

2023-01-04 12:47 UTC, FikriMilano commented
@jingtang10 this is ready for another review

2023-01-06 11:02 UTC, jingtang10 approved these changes

2023-01-06 11:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInMiB: BigDecimal?
```suggestion
internal val Questionnaire.QuestionnaireItemComponent.maxSizeInMiBs: BigDecimal?
```

2023-01-06 11:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_shouldReturnBytes() {
can we make these use the kotlin test name style with back quotes?

```
`should return max size in bytes`
```

2023-01-06 11:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSizeInByte_missingExtension_shouldReturnNull() {
```
`should return null for max size in bytes`
```

2023-01-06 11:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +    val questionnaire =
```suggestion
    val questionnaireItem =
```

and below. it's just a bit confusing to call this a questionnaire when it's not.

also i think these can all be inlined.

2023-01-06 12:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  }
sure

2023-01-06 12:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInKiB: BigDecimal?
done

2023-01-06 12:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInByte: BigDecimal?
done

2023-01-06 12:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInByte: BigDecimal?
I also updated the doc of this method a bit

2023-01-06 12:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.maxSizeInMiB: BigDecimal?
done

2023-01-06 12:22 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +  fun maxSize_shouldReturnBytes() {
sure

2023-01-06 12:22 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +    val questionnaire =
sure, renamed.
I inlined the null type tests.

2023-01-10 15:39 UTC, merged