Help button workflow
google/android-fhir pull request #1697
Opened 2022-11-03 06:06 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1612 

**Description**
- Show help button workflow use case.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**
<img width="433" alt="Screen Shot 2022-11-03 at 11 33 46 AM" src="https://user-images.githubusercontent.com/86107848/199656778-d1e23d05-19ec-4a16-883a-9f2ad14b74e2.png">

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-11-03 11:40 UTC, omarismail94 approved these changes
Nice change @santosh-pingle ! Just left one nit

2022-11-03 11:40 UTC, omarismail94 commented on catalog/src/main/assets/component_help.json
> +}
nit: add empty line at the bottom

2022-11-21 13:36 UTC, santosh-pingle commented
@shelaghm 
<img width="419" alt="Screen Shot 2022-11-21 at 7 03 17 PM" src="https://user-images.githubusercontent.com/86107848/203068588-8a04f0e2-53c9-4c50-8cd1-d2a7cfdcda82.png">
<img width="432" alt="Screen Shot 2022-11-21 at 7 03 40 PM" src="https://user-images.githubusercontent.com/86107848/203068605-2094a865-7564-4ff3-812b-a28832b4abbb.png">

2022-11-28 18:01 UTC, shelaghm commented
@santosh-pingle looks good. Thanks!

2022-11-30 14:17 UTC, jingtang10 requested changes

2022-11-30 14:17 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +    WIDGETS(textId = R.string.widgets, viewType = HEADER_TYPE),
you can just create another list that is used as the order for the grid.

2022-12-01 05:34 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +    WIDGETS(textId = R.string.widgets, viewType = HEADER_TYPE),
looking into it.

2022-12-01 08:59 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +    WIDGETS(textId = R.string.widgets, viewType = HEADER_TYPE),
done

2022-12-01 11:28 UTC, jingtang10 approved these changes
thanks @santosh-pingle for this change! looks much cleaner!

2022-12-01 11:28 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      ViewItem.HeaderItem(Header.WIDGETS),
optional:

if you add a function in the `Header` enum and the `Component` enum called something like `toViewItem` and wraps the enum value in a `ViewItem` I think that might make this list looks a little more succint:

```
val viewItemList =
    listOf(
      Header.WIDGETS.toViewItem(),
      Component.BOOLEAN_CHOICE.toViewItem(),
      ...
```

up to you though

2022-12-04 20:37 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ComponentListViewModel.kt
> +      ViewItem.HeaderItem(Header.WIDGETS),
i've done this.

2022-12-04 20:49 UTC, merged