Show time-picker in input mode.
google/android-fhir pull request #1702
Opened 2022-11-09 09:21 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1620 

**Description**

- Existing implementation shows time picker view in clock mode.
- This change shows time-picker in input mode.  

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-11-09 09:31 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/200792581-9bea6dbe-16d4-436d-8342-72ef8e6dec05.mov

2022-11-09 20:59 UTC, omarismail94 commented
@santosh-pingle  This PR doesn't solve the problem that Shelagh had. Right now, the PR changes the input format to the keyboard, as opposed to having a clock. 

The issue that Shelagh had was if you press on the textbox, the pop-up window to select the time doesn't open. It only opens if you press the icon

2022-11-10 05:01 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            setInputMode(INPUT_MODE_KEYBOARD)
It wont fix the actual issue , it has just changed TimePicker dialog UI, 
Here Instead of selecting time from analogue clock , user can now enter time with keyboard.
But still the TimePicker dialog open only on the click of clock icon on the right, it still doesn't open on click of time input box which is expected.

2022-11-10 06:07 UTC, santosh-pingle commented
> @santosh-pingle This PR doesn't solve the problem that Shelagh had. Right now, the PR changes the input format to the keyboard, as opposed to having a clock.
> 
> The issue that Shelagh had was if you press on the textbox, the pop-up window to select the time doesn't open. It only opens if you press the icon

sorry, I misunderstood the Jing's comment, he suggested to open the time picker in input mode when user click on input text field.
I will implement that change.

2022-11-10 06:07 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            setInputMode(INPUT_MODE_KEYBOARD)
sorry, I misunderstood the Jing's comment, he suggested to open the time picker in input mode when user click on input text field.
I will implement that change.

2022-11-16 13:37 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            setInputMode(INPUT_MODE_KEYBOARD)
done.

2022-11-24 11:47 UTC, PallaviGanorkar commented
@santosh-pingle Please attach video after latest fix for this issue

2022-11-25 09:23 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/203945244-bc7e1ac7-f5af-46b8-ad41-61d88034b421.mov

2022-11-29 09:54 UTC, PallaviGanorkar commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +
if possible we can add test case to check input mode( INPUT_MODE_CLOCK and INPUT_MODE_KEYBOARD) OR can add assert for same in existing test case when click on input text or icon

2022-11-29 09:56 UTC, PallaviGanorkar reviewed
Added one small comment, other things LGTM. code owner can have look.

2022-11-29 11:16 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +
This test already cover if time picker is launched in keyboard input mode or not, 
Basically, if input mode is Keyboard then time picker launch with layout element `material_textinput_timepicker` for which check(assertion) is added.

2022-12-14 13:58 UTC, jingtang10 requested changes

2022-12-14 13:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +      private fun createMaterialTimePicker(context: Context, inputMode: Int): MaterialTimePicker {
i think your `createMaterialTimePicker` and `showMaterialTimePicker` can be one function.

2022-12-14 13:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +      private fun createMaterialTimePicker(context: Context, inputMode: Int): MaterialTimePicker {
the only case where i can think of we might want to have these 2 functions separate is when you cache the time picker and reuse it throughout the questionnaire - which might have a performance gain. but if we're not doing that i feel the code is simpler (more readable) if we just merge the two functions.

2022-12-14 13:58 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +    onView(allOf(withId(R.id.material_textinput_timepicker)))
add a comment here to say that R.id.material_textinput_timepicker is the id for the text input in the time picker.

2022-12-14 13:58 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +
would be useful to add another test case to check that the dialog with clock is shown when you click the icon.

2022-12-15 06:01 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +      private fun createMaterialTimePicker(context: Context, inputMode: Int): MaterialTimePicker {
done.

2022-12-15 06:16 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +    onView(allOf(withId(R.id.material_textinput_timepicker)))
done.

2022-12-15 06:16 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryEspressoTest.kt
> +
done.

2022-12-22 13:43 UTC, jingtang10 approved these changes
thanks @santosh-pingle

2022-12-22 13:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            .build()
```suggestion
          let timeFormat = if (DateFormat.is24HourFormat(context)) {
                TimeFormat.CLOCK_24H
              } else {
                TimeFormat.CLOCK_12H
              }
          MaterialTimePicker.Builder()
            .setTitleText(R.string.select_time)
            .setHour(selectedTime.hour)
            .setMinute(selectedTime.minute)
            .setTimeFormat(timeFormat)
            .setInputMode(inputMode)
            .build()
            .apply{ ... }
            .show( ... )
```

2022-12-23 09:42 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            .build()
done.

2022-12-23 12:26 UTC, merged