Support choice orientation in boolean view.
google/android-fhir pull request #1710
Opened 2022-11-10 13:08 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1515 

**Description**

- Support choice orientation in boolean view.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-11-10 13:47 UTC, santosh-pingle commented
<img width="433" alt="Screen Shot 2022-11-10 at 6 09 55 PM" src="https://user-images.githubusercontent.com/86107848/201108348-1f70749c-980b-401f-980b-eab2908682a9.png">

2022-11-11 07:41 UTC, aditya-07 commented
@santosh-pingle Could we not use `android:orientation` in the `RadioGroup`?

2022-11-11 09:38 UTC, santosh-pingle commented
> @santosh-pingle Could we not use `android:orientation` in the `RadioGroup`?

Advantage of having constraintLayout flow is that if views does not get fit on same line then it get wrap on next line.

2022-11-11 10:13 UTC, aditya-07 commented
> > @santosh-pingle Could we not use `android:orientation` in the `RadioGroup`?
> 
> Advantage of having constraintLayout flow is that if views does not get fit on same line then it get wrap on next line.

Since the boolean view has just two options, do you think overflow will still be an issue?

2022-11-11 11:15 UTC, santosh-pingle commented
> > > @santosh-pingle Could we not use `android:orientation` in the `RadioGroup`?
> > 
> > 
> > Advantage of having constraintLayout flow is that if views does not get fit on same line then it get wrap on next line.
> 
> Since the boolean view has just two options, do you think overflow will still be an issue?

- Considering the local language translation support in future, and translation values does not get fit on the same line, flow will be good option to wrap these options to next line.
- Also changes in layout resource will be consistent with single/multiple view change.

2022-11-14 07:31 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        }
The code should set values for both the orientation cases so that recycled views can be used for either types.

2022-11-14 07:36 UTC, aditya-07 reviewed
We should also add a unit test to check that `choiceOrientation` is properly getting applied in  the view.

2022-11-14 07:36 UTC, aditya-07 commented on datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
>          android:id="@+id/radio_group"
```suggestion
        android:id="@+id/radio_constraint_layout"
```

2022-11-14 07:36 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        }
The code should set values for both the orientation cases so that recycled views can be used for either types.

2022-11-14 09:05 UTC, santosh-pingle commented
> We should also add a unit test to check that `choiceOrientation` is properly getting applied in the view.
@aditya-07 
There are tests which asserts whether answer options are shown.
But I am not sure if there is way to assert in unit/android test to check if answer options are shown horizontally or vertically, except screenshot testing.

2022-11-16 08:20 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        }
done

2022-12-04 22:30 UTC, jingtang10 commented
@shelaghm fyi

2022-12-05 18:06 UTC, shelaghm commented
@santosh-pingle See below for feedback on how to adjust the padding so that the buttons look more balanced. See screenshot on how to adjust the padding. Otherwise, it looks great to me. 
<img width="511" alt="Screen Shot 2022-12-05 at 10 04 03" src="https://user-images.githubusercontent.com/86378921/205709619-5d88e8e1-fc36-44a0-bcc3-dbc38c44d043.png">

2022-12-14 06:04 UTC, santosh-pingle commented
> @santosh-pingle See below for feedback on how to adjust the padding so that the buttons look more balanced. See screenshot on how to adjust the padding. Otherwise, it looks great to me. <img alt="Screen Shot 2022-12-05 at 10 04 03" width="511" src="https://user-images.githubusercontent.com/86378921/205709619-5d88e8e1-fc36-44a0-bcc3-dbc38c44d043.png">

@shelaghm 
- left edge padding 16 dp is already present.
- top padding not changed
- padding between icon and text is updated to 16 dp
-  right edge padding updated to 24 dp

<img width="372" alt="Screen Shot 2022-12-14 at 11 08 38 AM" src="https://user-images.githubusercontent.com/86107848/207518931-da300902-579e-45be-8780-9b508863d8db.png">

2022-12-14 14:17 UTC, jingtang10 requested changes

2022-12-14 14:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +              flow.setWrapMode(Flow.WRAP_NONE)
```suggestion
              setWrapMode(Flow.WRAP_NONE)
```

2022-12-14 14:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        noRadioButton.isChecked = false
can you put these two lines inside the when?

and add a null case in when

2022-12-14 14:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +          questionnaireItemViewItem.questionnaireItem.choiceOrientation
don't recalculate this - pass the choiceOrientation on line 59.

2022-12-14 14:17 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryTest.kt
> +            .getChildAt(1) as RadioButton)
just use yes_radio_button id?

and use no_radio_button id later?

2022-12-15 05:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +              flow.setWrapMode(Flow.WRAP_NONE)
done.

2022-12-15 05:12 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        noRadioButton.isChecked = false
done.

2022-12-15 05:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +          questionnaireItemViewItem.questionnaireItem.choiceOrientation
done.

2022-12-22 13:31 UTC, jingtang10 approved these changes
thanks @santosh-pingle

2022-12-23 13:57 UTC, merged