Fix integer exceed upper limit
google/android-fhir pull request #1727
Opened 2022-11-23 03:16 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1718 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-11-23 03:23 UTC, FikriMilano commented
Facing this issue
[Bug.webm](https://user-images.githubusercontent.com/62053304/203463156-3a4659d5-5161-4025-be9c-be4ef4f4cab5.webm)

What I'm trying to achieve is:
1. The cursor stay at the end
2. The user won't be able to input more than the integer limit

2022-11-25 07:53 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent()
move this out of if else and value should should be evaluated inside if else to remove duplication

2022-11-25 07:53 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +              .setValue(IntegerType(Int.MAX_VALUE))
We are explicitly setting value to something else here. Kindly add a comment here how app is handling the error propagation to user to let them know that their input value is not entertained.. For e.g. text can be 999999999999999... but int is changing it to int.max-value. How we make sure that this does not go unnoticed. by user

2022-11-25 07:53 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +  open fun getTextDefaultLimit() = ""
this seems confusing. text default limit should be null or max possible value. empty string makes it confusing.

2022-11-25 07:53 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +          textInputEditText.append(getTextDefaultLimit())
update answer actually sets the response-answer-value. the code updates the answer value to something else the edit text shows a different value by overriding the value to default

2022-11-25 07:53 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      textInputEditText.setText("")
why we are doing this?

2022-11-25 09:15 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      textInputEditText.setText("")
- Changed `editText.setText(text)` to `editText.append(text)`, so the cursor can stay at the end
- `editText.setText(emptyText)` is only used to clear the previous text before appending the new one

2022-11-25 11:44 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      textInputEditText.setText("")
if we use `editText.setText(text)` - when it's triggered while the edit text has focus, the cursor will go to the start.

I tried to use .setSelection() to move the cursor, but it doesn't seem to work.

2022-12-27 04:43 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent()
sure

2022-12-27 04:47 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +              .setValue(IntegerType(Int.MAX_VALUE))
sure I will add some comments.
and we will also add an error message to let the user know, when their input is not entertained

2022-12-27 04:47 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +  open fun getTextDefaultLimit() = ""
ok, I think `null` makes more sense here. 
because input doesn't necessarily always a number, which has max value

2022-12-27 05:08 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +          textInputEditText.append(getTextDefaultLimit())
yes that's right, let me know if you have more suggestion about this.

by appending the new text, it will trigger a recursive, in which it will call the update answer again, then break off from the recursive since it no longer exceeds the limit

2022-12-27 13:33 UTC, FikriMilano commented
@maimoonak 
There was a change in the approved solution.

The new solution is:
- Show error if value exceed limit
- Prevents text field to clear itself, exclusive for integer field type

2023-01-09 09:49 UTC, ndegwamartin commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (input.hasValue()) {
Perhaps we should combine these two checks?

2023-01-09 10:00 UTC, ndegwamartin commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryEspressoTest.kt
> +      .isNotEmpty()
Is it possible to also assert the actual value?

If the concern is localisation I think regardless of the local CI runs with at the time the correct value will be used. This will require the expected value to be retrieved from the context via string_id

2023-01-09 12:14 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryEspressoTest.kt
> +      .isNotEmpty()
yeah, let's do that

2023-01-09 12:14 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (input.hasValue()) {
actually, we need to keep this, with a bit of change and comments.

I made a change in which getValue returns an empty value instead a null, to prevent it clear itself.
null happens because the value surpasses the integer limit.
https://github.com/google/android-fhir/pull/1727/files#diff-6cb9f6285e5c442c229a831e85323b5c22edab8427019f3e735fe67a48108ecbR43

line 104 makes sure it only accepts non empty value, perhaps I need to change this to non empty checks

2023-01-09 13:05 UTC, ndegwamartin commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      if (input.hasValue()) {
Got it, sounds good!

2023-01-09 13:06 UTC, ndegwamartin approved these changes

2023-01-09 13:37 UTC, FikriMilano commented
@jingtang10 this is ready for review

2023-02-03 13:22 UTC, jingtang10 requested changes
A couple of high level comments

1. Please check out the `validation` package in the SDC library code, it is a collection of validators that the view model uses to validate answers the user inputs. I think you can add a new validator (maybe name it `IntegerRangeValidator` or something similar) and by doing this, we are using an existing validation mechanism. Probably a bit more modularised and easier to maintain.
2. As I commented in the issue itself, I think you need to format the number correctly depending on the locale. Try this API and see if it works https://developer.android.com/reference/android/icu/text/NumberFormat. And maybe change your device's locale to see if the number format has changed.

2023-02-06 11:49 UTC, FikriMilano commented
thanks, sure Jing

2023-02-07 13:09 UTC, FikriMilano commented
@jingtang10 
was having some issues with this.
the IntegerType answer value never surpasses it's limit, hence whenever we do validation, it shows no error.

the validation mechanism is not feasible, unless we use DecimalType for integer field widget.

2023-02-21 02:03 UTC, FikriMilano commented
closed by https://github.com/google/android-fhir/pull/1873
cc @jingtang10

2023-02-21 02:03 UTC, closed without merging