Reduce question text font size in review mode.
google/android-fhir pull request #1737
Opened 2022-11-29 13:53 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1716 

**Description**
Issue : Question text font style of edit mode get applied to the question text in review mode.
Fix : Created separate header item view for review mode so that title medium text style can be applied. 

Also do not show the help button in the review mode. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-11-29 13:55 UTC, santosh-pingle commented
@shelaghm 
<img width="438" alt="Screen Shot 2022-11-29 at 5 51 21 PM" src="https://user-images.githubusercontent.com/86107848/204547307-35d61bb4-6cf5-4143-bcfb-ac4cdef7c609.png">

2022-11-30 12:49 UTC, santosh-pingle commented
@shelaghm 
<img width="440" alt="Screen Shot 2022-11-30 at 6 17 03 PM" src="https://user-images.githubusercontent.com/86107848/204800269-16f7797f-9aa1-4601-994e-ace9e9ab90ba.png">

2022-11-30 18:16 UTC, shelaghm commented
@santosh-pingle Great! Can you check the red text color? It looks too light, it should be `#B3261E`

2022-12-02 09:39 UTC, santosh-pingle commented
<img width="419" alt="Screen Shot 2022-12-02 at 3 08 09 PM" src="https://user-images.githubusercontent.com/86107848/205262782-c7c450db-efcd-4d39-bb3c-a76c5cd4d031.png">

2022-12-02 12:05 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt
> +    updateQuestionText(question, questionnaireItem)
the functions we call here are in the `QuestionnaireItemHeaderView` class. How about we move the common functions we have between classes into a new file?

2022-12-02 12:12 UTC, omarismail94 commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +                EXTRA_ENABLE_REVIEW_PAGE to true
did you add this to enable a review page at the end of each questionnaire?

Reading the kdoc for `EXTRA_ENABLE_REVIEW_PAGE` it says:

```
 A [Boolean] extra to control if a review page is shown. By default it will be shown at the end of the questionnaire.
```

which seems to indicate that by default, this flag is true. However, when looking at the QuestionnaireViewMode, it sets it by default to `false`:

```
  private val shouldEnableReviewPage =
    state[QuestionnaireFragment.EXTRA_ENABLE_REVIEW_PAGE] ?: false
```

either update the kdoc to say by default the flag is false, or update the default value to `true` and remove the need to set `EXTRA_ENABLE_REVIEW_PAGE` here

2022-12-05 10:34 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt
> +internal class QuestionnaireItemHeaderViewInReviewMode(context: Context, attrs: AttributeSet?) :
yes, I can create separate pr to rename  `QuestionnaireItemHeaderView ` to `QuestionnaireItemHeaderViewInEditMode`, as this change will affect many files.

2022-12-05 10:52 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
>    QuestionnaireItemViewHolderFactory(R.layout.questionnaire_item_simple_question_answer_view) {
done

2022-12-05 10:52 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt
> +    updateQuestionText(question, questionnaireItem)
done.

2022-12-05 10:57 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +                EXTRA_ENABLE_REVIEW_PAGE to true
I am updating kdoc for `EXTRA_ENABLE_REVIEW_PAGE` with default value is false.

2022-12-22 13:10 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +                EXTRA_ENABLE_REVIEW_PAGE to true
yeah the kdoc needed to be udpated.

2023-01-04 13:30 UTC, santosh-pingle commented on datacapture/src/main/res/layout/questionnaire_item_header_in_review_mode.xml
> +<?xml version="1.0" encoding="utf-8" ?>
done.

2023-01-04 13:30 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewModeTest.kt
> +  fun shouldShowPrefix() {
done.

2023-01-04 13:33 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +import androidx.core.graphics.ColorUtils
yes, its required here `ColorUtils.setAlphaComponent(...`

2023-01-04 13:33 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +  val helpButton = view.findViewById<Button>(R.id.helpButton)
done.

2023-01-05 12:40 UTC, jingtang10 requested changes

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +     * shown at the end of the questionnaire if value is true.
```suggestion
     * A [Boolean] extra to enable the review page. Default to false.
```

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +internal fun initHelpButton(
```suggestion
internal fun initHelpViews(
```

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +      questionnaireItem
```suggestion
    initHelpButton(
      helpButton = findViewById(R.id.helpButton),
      helpCardView = findViewById(R.id.helpCardView),
      helpText = findViewById(R.id.helpText),
      questionnaireItem
```

and in the later call sites.

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +  helpText: TextView,
```suggestion
  helpTextView: TextView,
```

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +      questionTextView.context.getColorFromAttr(R.attr.colorError)
please update this as per reply to https://github.com/google/android-fhir/issues/544#issuecomment-1372143034 

and the kdoc above.

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +internal fun getViewGroupVisibility(vararg view: TextView): Int {
header view visibility

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +  var isHelpCardViewVisible = false
instead of using this variable, can you just check if the card view is visible and then toggle it?

i think we had an issue with function closure in the library before.

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +internal fun initHelpButton(
delete this function

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
> +            android:layout_height="20dp"
put these in dimens.xml

2023-01-05 12:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +        errorIcon = itemView.findViewById(R.id.error_icon_in_review_mode)
errorTextView

2023-01-09 06:57 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +        errorIcon = itemView.findViewById(R.id.error_icon_in_review_mode)
@jingtang10 

As per ux design, we are showing an error icon at left and `not answered ` text in a red color which is just normal text and not an error text(which get shown just below the main view).

Now, as per comment, if we do use error property/attribute of TextView to show the 'Not answered' text in red color and error icon to the left, then there will be mismatch in output and ux design. Because with error attribute/property of textView it shows 'not answered' in the pop up when focus even happens on it and error icon to the right of the view.

Please refer below link for more info.
https://developer.android.com/reference/android/widget/TextView#setError(java.lang.CharSequence)
<img width="423" alt="Screenshot 2023-01-09 at 12 17 12 PM" src="https://user-images.githubusercontent.com/86107848/211253667-d85884b1-fb33-4b31-8626-2b9605a81dde.png">


So, we need to keep existing approach where two views are used to show error icon at left and `not answered` text in red color separately, but those will not be referenced individually in kotlin code, instead of it only layout container of the views will be referenced.

Thanks!

2023-01-10 10:10 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  internal val hasAnswerString: Boolean
done.

2023-01-10 10:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
>      }
done.

2023-01-10 10:11 UTC, santosh-pingle commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
> +            android:layout_height="20dp"
done.

2023-01-10 10:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +internal fun initHelpButton(
done.

2023-01-10 10:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +  helpText: TextView,
done.

2023-01-10 10:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderView.kt
> +      questionnaireItem
done.

2023-01-10 10:20 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +     * shown at the end of the questionnaire if value is true.
done.

2023-01-10 10:20 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +internal fun initHelpButton(
done.

2023-01-10 10:21 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +internal fun getViewGroupVisibility(vararg view: TextView): Int {
done.

2023-01-10 10:21 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewUtil.kt
> +  var isHelpCardViewVisible = false
done.

2023-01-13 12:07 UTC, jingtang10 requested changes

2023-01-13 12:07 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
> +        android:id="@+id/not_answered_view"
```suggestion
        android:id="@+id/error_view"
```

2023-01-13 12:07 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
> +        android:id="@+id/not_answered_view"
move this to below the answer view

2023-01-13 12:07 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
>          android:id="@+id/answer_text_view"
make sure to set this text to be either the answer text, or the no answer string.

2023-01-13 23:12 UTC, shelaghm commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +          }
To clarify `"Specifically, if the question is required, but there's no answer. we should show no answer in normal color."`  Do you mean that if a question is `not` required to show `no answer` in normal/grey color instead of red? If that's the case, then that makes sense to me and I can update my designs.

I agree with showing the same error messages as it is displayed in the edit view. So in that case we'd likely not show "no answer", but rather `missing answer for required question` (depending on what the error message actually is.)

2023-02-08 10:33 UTC, santosh-pingle commented
Addressing review comments, thanks!

2023-02-08 12:43 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +          }
@jingtang10 
With this suggested logic, if the user does not interact with questionnaire items, all questionnaire items will be marked as NOT_VALIDATED, and there will be no error messages indicating that some of them have errors (e.g. when 'required' is set to true). Furthermore, questionnaire item types such as Group and Display do not have answers as they serve as labels only, but their validation result will also be NOT_VALIDATED. The decision on whether the answer item view should be displayed or not remains unclear in this scenario.

2023-02-08 16:23 UTC, shelaghm commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +          }
Discussion w/ Jing:
- Show validation result/error message
- Show no answer and validation result "answer missing for required question"

If a user did not interact with the form --> should fix this so the run the validation @santosh-pingle to figure this out

@shelaghm AI: need another field to display validation errors.

2023-03-01 11:28 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +          }
@shelaghm 
There is a small error in the mock that needs to be corrected for question "Highest level of education", The expected behavior is as follows:
If a question is mandatory and not answered, then it should show 'Not Answered' and just below it an error message indicating that the answer is missing for the required field. The 'Not Answered' option will be displayed in the same normal gray color that is used in other parts of the mock.

2023-03-01 17:08 UTC, jingtang10 requested changes

2023-03-01 17:08 UTC, jingtang10 commented on datacapture/src/main/res/layout/review_view.xml
> -    <com.google.android.fhir.datacapture.views.HeaderView
so you're not using the same view any more - can you explain a bit more the rationale?

2023-03-02 12:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          hasPressedReviewButton = true
done.

2023-03-02 12:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +internal fun initHelpViews(
done.

2023-03-02 12:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +/** Returns [VISIBLE] if any of the [view] is visible, else returns [GONE]. */
done.

2023-03-02 12:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +internal fun headerViewVisibility(vararg view: TextView): Int {
done.

2023-03-02 12:23 UTC, santosh-pingle commented on datacapture/src/main/res/layout/review_view.xml
> -    <com.google.android.fhir.datacapture.views.HeaderView
Basically, the style for the header view in the review summary page is set separately, because there is no api to set the style by attribute name in Kotlin code therefore existing headerView is not used here. As a result, we have created a separate view that is inlined in review_view.xml.

2023-03-03 05:16 UTC, santosh-pingle commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
>          android:id="@+id/answer_text_view"
done.

2023-03-03 05:16 UTC, santosh-pingle commented on datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
> +        android:id="@+id/not_answered_view"
done.

2023-03-03 05:17 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +          }
done.

2023-03-03 05:17 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +        notAnsweredView = itemView.findViewById(R.id.not_answered_view)
done.

2023-03-03 05:19 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +        errorIcon = itemView.findViewById(R.id.error_icon_in_review_mode)
done.

2023-03-03 05:21 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +                EXTRA_ENABLE_REVIEW_PAGE to true
done.

2023-03-03 05:25 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemHeaderViewInReviewMode.kt
> +internal class QuestionnaireItemHeaderViewInReviewMode(context: Context, attrs: AttributeSet?) :
file does not exist anymore.

2023-03-06 19:26 UTC, jingtang10 commented on datacapture/src/main/res/layout/review_view.xml
> -    <com.google.android.fhir.datacapture.views.HeaderView
would something like this work? https://stackoverflow.com/questions/17277618/get-color-value-programmatically-when-its-a-reference-theme

2023-03-06 19:55 UTC, jingtang10 requested changes
thanks @santosh-pingle just one question below

2023-03-06 19:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          viewModel.validateQuestionnaireAndUpdateUI()
why do you need this line? i think the questionnaire view model would take care of this (line 610 in this PR)?

2023-03-06 19:55 UTC, jingtang10 commented on datacapture/src/main/res/layout/review_view.xml
> -    <com.google.android.fhir.datacapture.views.HeaderView
actually i think i get what you mean - you have to set multiple styles within the view.. it's kinda tricky. i'm happy with this given that in the future the view might diverge anyway from what we show in edit mode.

2023-03-07 07:17 UTC, shelaghm commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
> +          }
@santosh-pingle Yes, that's right. This is what we agreed on and my mocks are out of date. Thank you for writing this up so clearly, I've updated my design mocks to match this pattern.

2023-03-09 05:56 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +          viewModel.validateQuestionnaireAndUpdateUI()
It is not required, I removed it. 
done.

2023-03-10 10:42 UTC, jingtang10 approved these changes

2023-03-10 10:42 UTC, merged