Add Reference class to display string function
google/android-fhir pull request #1740
Opened 2022-11-30 22:35 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1735 

**Description**
Add Reference type and obtain the field to display the string of on the UI.

Follow-up question: are there other class types we could be missing here other than `Reference`? 

**Alternative(s) considered**
N/A

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

https://user-images.githubusercontent.com/44980219/204922839-c989e03e-540c-4014-bcf1-fe3de9a493d3.mp4

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-01 12:09 UTC, jingtang10 approved these changes
thanks @omarismail94!

2022-12-01 12:12 UTC, jingtang10 requested changes
thanks @omarismail94!

2022-12-01 12:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireResponseItemAnswerComponentTest.kt
> +        .setValue(Reference().setDisplay("Newton"))
actually do you need to consider the case where display is null for a reference? do you then need to display the actual reference value?

2022-12-05 12:22 UTC, omarismail94 commented
@jingtang10  PTAL. I resolved your comment and also moved where the `displayString` function is called to `MoreAnswerOptions` to be in the same location where `displayString` value is called for `QuestionnaireItemAnswerOptionComponent`. 

I wanted to come up with one function to combine both like this:
```
internal val Questionnaire.QuestionnaireItemAnswerOptionComponent.displayString: String
  get() = displayString(null, value)

internal fun QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent.displayString(
  context: Context
) = displayString(context, value)


private fun displayString(context: Context?, value: Type?) : String =
  return when(value) {
   //logic
  }
    
```

however, the logic becomes divergent. An example: in `QuestionnaireItemAnswerOptionComponent`, if the `value` is `DateType`, we just return `value.primitiveValue()`; so if we pass 2022-01-01 it will return 2022-01-01.

For `DateType`s in  `QuestionnaireResponseItemAnswerComponent`, we return `value.localDate?.localizedString`; so if we pass 2022-01-01, it will return 01/01/22. 

Do we want to make what is displayed consistent, or is there a reason there is a difference between how `QuestionnaireItemAnswerOptionComponent`s  and ` `QuestionnaireResponseItemAnswerComponent`s are displayed?

2022-12-12 18:23 UTC, jingtang10 commented
> @jingtang10 PTAL. I resolved your comment and also moved where the `displayString` function is called to `MoreAnswerOptions` to be in the same location where `displayString` value is called for `QuestionnaireItemAnswerOptionComponent`.
> 
> I wanted to come up with one function to combine both like this:
> 
> ```
> internal val Questionnaire.QuestionnaireItemAnswerOptionComponent.displayString: String
>   get() = displayString(null, value)
> 
> internal fun QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent.displayString(
>   context: Context
> ) = displayString(context, value)
> 
> 
> private fun displayString(context: Context?, value: Type?) : String =
>   return when(value) {
>    //logic
>   }
>     
> ```
> 
> however, the logic becomes divergent. An example: in `QuestionnaireItemAnswerOptionComponent`, if the `value` is `DateType`, we just return `value.primitiveValue()`; so if we pass 2022-01-01 it will return 2022-01-01.
> 
> For `DateType`s in `QuestionnaireResponseItemAnswerComponent`, we return `value.localDate?.localizedString`; so if we pass 2022-01-01, it will return 01/01/22.
> 
> Do we want to make what is displayed consistent, or is there a reason there is a difference between how `QuestionnaireItemAnswerOptionComponent`s and ` `QuestionnaireResponseItemAnswerComponent`s are displayed?

I don't think they need to be different - please unify them.

2022-12-13 12:59 UTC, omarismail94 commented
@jingtang10 Unified the functions. With regards to existing tests that I needed to change, I only had to change [MoreAnswerOptionsTest](https://github.com/google/android-fhir/pull/1740/files#diff-6d2bb499344c625955cd158ed797e7047659a1ef898ba22daea16d57a1e18a4e); I had to change the display format of the Date

2022-12-14 15:05 UTC, jingtang10 requested changes

2022-12-14 15:05 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +internal fun QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent.displayString(
actually i think this should be in a separate file...

this file should be renamed to `MoreQuestionnaireItemAnswerOptionComponents.kt`.

and there should be another file `MoreQuestionnaireResponseItemAnswerComponents.kt`

2022-12-15 11:48 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +internal fun QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent.displayString(
Created these two files, and third one called DisplayStringUtil and refactored the different functions to the right files

2022-12-15 14:48 UTC, jingtang10 reviewed
discussed with @omarismail94 - will refactor and make context mandatory, and then maybe move the extension function to `Type` instead.

2022-12-15 17:01 UTC, omarismail94 commented
> discussed with @omarismail94 - will refactor and make context mandatory, and then maybe move the extension function to `Type` instead.

implemented this

2022-12-15 18:35 UTC, jingtang10 approved these changes
thanks omar!

2022-12-15 18:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/MoreTypes.kt
> +    is IntegerType -> this.valueAsString ?: context.getString(R.string.not_answered)
can you merge these together?

2022-12-15 18:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/MoreTypes.kt
> +    is UriType -> this.valueAsString ?: context.getString(R.string.not_answered)
can you merge these as well?

2023-01-03 13:10 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/MoreTypes.kt
> +    is IntegerType -> this.valueAsString ?: context.getString(R.string.not_answered)
Done

2023-01-03 13:10 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/MoreTypes.kt
> +    is UriType -> this.valueAsString ?: context.getString(R.string.not_answered)
Done

2023-01-03 13:11 UTC, merged