itemAnswerMedia extension support added for image
google/android-fhir pull request #1749
Opened 2022-12-05 13:54 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1614

**Description**
itemAnswerMedia extension support added for image with data field in extension

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-14 14:33 UTC, jingtang10 requested changes

2022-12-14 14:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/OptionSelectDialogFragment.kt
> +          item.option.item.itemAnswerOptionImage(compoundButton.context),
if the locale is RTL, doesn't this look odd?

2023-01-04 13:44 UTC, jingtang10 requested changes
thanks @PallaviGanorkar! great change!

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +        "image/jpg" -> {
just a nit - can you group jpg and jpeg together? sort alphabetically.

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +          val px = context.resources.getDimensionPixelOffset(R.dimen.choice_button_image)
```suggestion
          val imageSize = context.resources.getDimensionPixelOffset(R.dimen.choice_button_image)
```

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +  val extension =
just inline this variable.

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +    this.extension.singleOrNull { it.url == EXTENSION_ITEM_ANSWER_MEDIA }?.value as Attachment?
you also don't need `this`

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
> +    this.extension.singleOrNull { it.url == EXTENSION_ITEM_ANSWER_MEDIA }?.value as Attachment?
you could do
```
return extension.singleOrNull{ ... }?.value
  ?.let{
  }
```

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +      // null)
remove

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_list.xml
>  <TextView
this file needs to be renamed to `questionnaire_item_drop_down_list_item.xml`

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +      e.printStackTrace()
don't do this - use timber

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +    }
val listItemView = convertView ?: LayoutInflater.from(parent.context).inflate(layoutResourceId, parent, false)

2023-01-04 13:44 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryTest.kt
> +    assertThat(selectedItem.answerOptionImage).isEqualTo(null)
you're not really testing what the view is. but you're testing your item has the image set/unset.

2023-01-11 13:59 UTC, jingtang10 approved these changes
thanks pallavi!

2023-01-11 13:59 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt
> +  private fun answerOptionsValueWithImageExtension(vararg options: String) =
might be slightly better to add a optional parameter so that this function and the previous one `answerOptionsValueString` can be merged.

```
private fun createAnswerOptions(vararg options: String, hasImageExtension: Boolean = false)
```

2023-01-11 14:18 UTC, PallaviGanorkar commented
@jingtang10 As discus

https://user-images.githubusercontent.com/13957417/211828845-7be7c6d5-f09c-4ccc-9cba-7d4d65925434.mp4

sed attaching video for drop down view item selection with AnswerOptionImage

2023-01-12 07:38 UTC, merged

2023-01-23 05:53 UTC, santosh-pingle commented
@PallaviGanorkar 
can you please share questionnaire json to demonstrate this feature if its not integrated in catalog app?

2023-01-23 06:42 UTC, PallaviGanorkar commented
@santosh-pingle Please find questionnaire for both paginated and default layout having random images for  testing.      (Please change extension for both files to .json)

[sample_registration_questionnaire.txt](https://github.com/google/android-fhir/files/10477280/sample_registration_questionnaire.txt)
[questionnaire_anc_quick_check.txt](https://github.com/google/android-fhir/files/10477289/questionnaire_anc_quick_check.txt)