Add FhirAdapter class and R4 lib to SDK
google/android-fhir pull request #1750
Opened 2022-12-05 17:12 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**
Fixes #1706 

**Description**
* Add data class, `FhirAdapter`, that holds lambdas to apply operations on FHIR-version specific resources
* Add interface, UploadWorkManager, that will be implemented by `TransactionBundleGenerator`  in a follow-up PR
* Add a new data class, `ResourceMetadataToUpdate`, to save response results retrieved from remote server to DB. This class will be used later to remove the need for the `FhirEngine` to know of the returned response is a Bundle or something different 
* Implement an R4 adapter, making public any classes in the engine library that the R4 adapter needs to use

**Alternative(s) considered**
Yes, see  PRs:
 #1734
  #1538
 #1707 

**Type**
Choose one: (Bug fix | **Feature** | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-08 16:49 UTC, yigit approved these changes
just 1 small nit in the enum class.

2022-12-08 16:49 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/index/SearchParamType.kt
> +enum class SearchParamType {
why not declare this as

```
enum class SearchParamType(
   val code: String,
   val system: String,
   val definition: String,
    ... etc)
   ```

instead of when statements?

2022-12-08 16:49 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/index/SearchParamType.kt
> +    fun fromCode(codeString: String?): SearchParamType? {
i think it is better if you made this iterate over values and hold a map.
e.g.

```
companion object {
    private val codeMapping = SearchParamType.values().associateBy { it.code }
   fun fromCode(codeString: String?)  = codeMapping[codeString] ?: error("...")
}
```
so you won't need to update any of this class when you add a new enum (with the other constructor change)

2022-12-13 11:40 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/index/SearchParamType.kt
> +enum class SearchParamType {
great idea! done

2022-12-13 11:41 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/index/SearchParamType.kt
> +    fun fromCode(codeString: String?): SearchParamType? {
adopted!

2023-01-03 14:06 UTC, jingtang10 requested changes
This pr will break release as of today.

Issue being that the gradle publish task in engine will not automatically include the source code from the new r4 module.

Can you test this? To fix this you might need to change the build rule (add source code path) in the engine module.

2023-01-03 15:19 UTC, jingtang10 commented
> This pr will break release as of today.
> 
> Issue being that the gradle publish task in engine will not automatically include the source code from the new r4 module.
> 
> Can you test this? To fix this you might need to change the build rule (add source code path) in the engine module.

Actually can you please hold on. Does it really make sense for us to create a separate module? Or does it make more sense simply to add different implementations inside the engine module. The bulk of binary size probably comes from HAPI structures, and our implementation to the adapter interface is probably a very small addition. Do we really want to manage multiple releases for each fhir version, or can we just put them in the same lib? For now, at least.

2023-01-12 13:06 UTC, omarismail94 commented
> This pr will break release as of today.
> 
> Issue being that the gradle publish task in engine will not automatically include the source code from the new r4 module.
> 
> Can you test this? To fix this you might need to change the build rule (add source code path) in the engine module.

@jingtang10 From our in-person discussion, I've moved everything back into the engine library so we can maintain one release as opposed to (X+1) releases each time we update the FHIR Engine (X being the number of FHIR versions we support and the one for the core engine lib)

2023-09-14 09:23 UTC, closed without merging