Add ig manager
google/android-fhir pull request #1751
Opened 2022-12-05 17:22 UTC by ktarasenko

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-19 15:12 UTC, jingtang10 reviewed
thanks @ktarasenko for this change! i think it woudl be great if you can write down some high level api design in the pr description and add some documentation to the new classes and apis - i think this is important for the reader to understand due to the new concepts introduced in this pr.

thanks!

2022-12-19 15:12 UTC, jingtang10 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +class IgManager internal constructor(igDatabase: ImplementationGuideDatabase) {
can you please add documentation for this class and for all the methods?

2022-12-19 15:12 UTC, jingtang10 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +  suspend fun delete(igDependency: IgContext.Dependency) {
i don't really understand the delete and import functions. can you explain in documentation with some examples?

why is this ever needed?

2022-12-22 16:27 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +  suspend fun delete(igDependency: IgContext.Dependency) {
Importing from file system will be used later. Made it internal for now. 
Deleting might be handy to let users clean up downloaded IGs

2022-12-22 16:27 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgContext.kt
> +class IgContext(internal val dependencies: List<Dependency>) {
added some

2022-12-22 16:29 UTC, ktarasenko commented
Added documentation. I will update the DD with the high-level interface and we can go back to this PR

2023-02-02 11:29 UTC, jingtang10 requested changes

2023-02-02 11:29 UTC, jingtang10 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +  private suspend fun importResource(igId: Long, resource: Resource, file: File) {
i see that in this PR we're not touching the files at all... is this intended? i think the api should control the files... at the moment the user of the api can pass a root directory an then modify the files as they wish.. that doesn't seem right to me?

2023-02-04 20:24 UTC, ktarasenko commented on implementationguide/src/test/java/com/google/android/fhir/implementationguide/IgManagerTest.kt
> +  fun `importing IG creates entries in DB`() = runBlocking {
It fails reliably for wrong assertions.  Do you have PR with fixes? I can try to apply it here too.

2023-02-04 20:24 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +class IgManager internal constructor(igDatabase: ImplementationGuideDatabase) {
Copied static methods from the follow-up PR.

2023-02-04 20:26 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +/** Responsible for downloading, accessing and deleting Implementation Guides. */
Right, it will trigger the downloading, but not really responsible for it. Updated the doc.

2023-02-04 20:30 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +   * [rootDirectory]
done

2023-02-04 20:31 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +  private suspend fun importResource(igId: Long, resource: Resource, file: File) {
Great point, I'll add a TODO and address it in a followup PR.

2023-02-04 20:35 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +          is Resource -> importResource(igId, resource, file)
You are right, some of the testdata I used had bundles, but the actual IG seem to only have single-resource files. 

I will remove this for now, until we need

2023-02-04 20:37 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgManager.kt
> +    // }
removed (see bundle vs resource)  comment

2023-02-17 08:17 UTC, jingtang10 requested changes

2023-02-17 08:31 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/IgDependency.kt
> +data class IgDependency(val packageId: String, val version: String, val uri: String)
done

2023-02-17 08:40 UTC, jingtang10 approved these changes

2023-02-17 09:36 UTC, ktarasenko commented on implementationguide/src/test/java/com/google/android/fhir/implementationguide/IgManagerTest.kt
> +  fun `importing IG creates entries in DB`() = runBlocking {
https://github.com/google/android-fhir/pull/1827 there were some problems with `runViewModelBlocking`  simple runBlocking is fine, but I will still update it to `runTest` as @omarismail94 suggested

2023-02-17 12:15 UTC, merged