Workflow: Cache ModelResolver and use cached FhirContext
google/android-fhir pull request #1753
Opened 2022-12-05 21:38 UTC by vitorpamplona

ModelResolver is one of the slowest objects to load: 5.12 seconds in debug. 

This PR
1. Makes R4FhirModelResolver a singleton. 
2. Makes use of a cached context for increased performance. 
 
The default constructor R4FhirModelResolver() constructor recreates the FhirContext.

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-14 11:06 UTC, jingtang10 requested changes

2022-12-14 11:06 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +object cachedR4FhirModelResolver : R4FhirModelResolver(FhirContext.forR4Cached())
if we are gonna make this a top level object i feel we should make this initialised lazily:
```
val r4FhirModelResolver : R4FhirModelResolver by lazy { ... }
```

but i don't even know if that's necessary - do we need R4FhirModelResolver also cached or just a matter of using the cached version of the FhirContext? if so, can we just simply modify `R4FhirModelResolver()` to `R4FhirModelResolver(FhirContext.forR4Cached())` in line 71?

2022-12-14 13:43 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +object cachedR4FhirModelResolver : R4FhirModelResolver(FhirContext.forR4Cached())
The constructor R4FhirModelResolver(cxt) is protected. So, the only way to access it is by extending the class, which is what the line does behind the scenes. 

Aren't all singletons (object defs) lazy by default?

2022-12-20 20:17 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +object cachedR4FhirModelResolver : R4FhirModelResolver(FhirContext.forR4Cached())
I just run a few tests and I can confirm `object` will be initialized whenever the (singleton) object is called the first time, as static objects are lazily initialized.

2023-03-06 19:57 UTC, jingtang10 approved these changes

2023-03-06 19:57 UTC, merged