Show asterisk in flyover text if question text is not present and questionnaire item is required.
google/android-fhir pull request #1762
Opened 2022-12-09 13:09 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #544

**Description**
Clear and concise code change description. 

- If question text is not present and questionnaire item is required then show asterisk in flyover text of sdc widgets which uses text input text layout (Edit text).

 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-12 10:18 UTC, santosh-pingle commented
@shelaghm 
All attached screenshots does not have question text and questionnaire item is required (mandatory).

<img width="431" alt="Screen Shot 2022-12-12 at 3 41 54 PM" src="https://user-images.githubusercontent.com/86107848/207019968-fc3de32f-e2c1-46a4-9a77-7e89ae881997.png">
<img width="418" alt="Screen Shot 2022-12-12 at 3 42 26 PM" src="https://user-images.githubusercontent.com/86107848/207019987-f06369c3-08dd-42a0-ae4f-77b4fb1133e4.png">
<img width="421" alt="Screen Shot 2022-12-12 at 3 42 57 PM" src="https://user-images.githubusercontent.com/86107848/207020022-c17135af-0533-4801-9aae-e735a82566f8.png">
<img width="429" alt="Screen Shot 2022-12-12 at 3 43 33 PM" src="https://user-images.githubusercontent.com/86107848/207020046-0b27bbe1-f619-42df-abda-e3b6079f4e7e.png">
<img width="429" alt="Screen Shot 2022-12-12 at 3 44 04 PM" src="https://user-images.githubusercontent.com/86107848/207020082-d76efb39-7f54-44ab-bd65-4a90c103cce4.png">

2022-12-13 13:06 UTC, omarismail94 commented
@santosh-pingle did we resolve whether we wanted `* required`  to appear on the bottom of all questions?

2022-12-14 05:06 UTC, santosh-pingle commented
> @santosh-pingle did we resolve whether we wanted `* required` to appear on the bottom of all questions?

I will start this thread in issue #544.

2022-12-14 11:00 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/MoreQuestionnaireItemView.kt
> +/*
done.

2022-12-14 11:01 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/MoreQuestionnaireItemView.kt
> +inline fun TextInputLayout.showAsteriskInFlyoverText(
it was typo mistake, i meant internal and not inline.

2022-12-14 11:01 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/MoreQuestionnaireItemView.kt
> +inline fun TextInputLayout.showAsteriskInFlyoverText(flyoverText: String) {
done.

2022-12-15 14:06 UTC, omarismail94 commented
Thanks @santosh-pingle ! LGTM!

2022-12-15 14:54 UTC, omarismail94 commented
We will wait for @shelaghm actually to get back to @jingtang10 's comment in the Issue #544  before approving

2022-12-22 22:19 UTC, shelaghm commented
@omarismail94 @santosh-pingle I've commented over on https://github.com/google/android-fhir/issues/544 let me know if either of you have thoughts as well :)

2023-01-13 12:12 UTC, jingtang10 requested changes
i think we're gonna not use asterisk at all as the result of UX research findings and discussions with @shelaghm.

sorry that you'll need to rework this pr.

2023-01-13 23:27 UTC, shelaghm commented
Let's wait while we get some input from the community on how they use required and then make a decision on how we re-work this issue. So far we've heard from Ona's designers. Will be great to hear from a few others how they are using this feature in their deployments.

2023-01-13 23:27 UTC, shelaghm commented
FYI https://github.com/google/android-fhir/issues/544 Ona uses `Optional` instead of `Required`.

2023-02-02 10:53 UTC, FikriMilano commented
@santosh-pingle can we make this configurable? would like to show nothing if required and show `Optional` if not required

2023-02-22 08:31 UTC, jingtang10 commented
@santosh-pingle can we close this PR now given it's also out of date?

we can reopen/create a new PR once we have conclusion on UX.

2023-02-22 09:35 UTC, closed without merging

2023-02-22 16:14 UTC, jingtang10 commented
thanks!