Bump CQL Translator/Evaluator to 2.4
google/android-fhir pull request #1771
Opened 2022-12-19 21:45 UTC by vitorpamplona

**Description**
1. Moves the CQL Evaluator from 2.1 to 2.4 and the translator from 2.1 to 2.4. 
2. Adjusts test cases to match the changes in the CQL-Translator
3. Removes the old `antlr` fix due to the fix being applied in this version of the Translator. 
4. Forces Jackson 2.14.1 due to this bug: https://github.com/FasterXML/jackson-databind/issues/3627. This will be fixed in the next version of HAPI/Translator/Evaluator combo, somewhere in January/February.  
5. Adjusts `generateCarePlan` to return IBaseResource to prepare for R5. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2022-12-19 23:26 UTC, vitorpamplona commented
:( We are going to need HAPI 6.3 to push this forward (We need that caffeine/guava modules shipped to Maven central)

2022-12-21 15:02 UTC, vitorpamplona commented
This is now ready to be reviewed. @jingtang10 @omarismail94 @ktarasenko @pld 

We need this for a more stable plan definition release.

2022-12-23 09:58 UTC, jingtang10 requested changes
@vitorpamplona thanks for working this out this is great. why do we need hapi 6.3?

fyi @brynrhodes

2022-12-23 09:58 UTC, jingtang10 commented on benchmark/build.gradle.kts
> +    resolutionStrategy {
can you define a common block for this repeated block?

2022-12-23 09:58 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val hapiFhirCore = "5.6.36"
add an explanation here why

2022-12-23 14:52 UTC, vitorpamplona commented on benchmark/build.gradle.kts
> +    resolutionStrategy {
Thanks Jing. I just added a block in the Dependencies file. See if this is better.

2023-01-10 17:25 UTC, jingtang10 approved these changes

2023-01-10 19:06 UTC, merged