Address DB PR review changes.
google/android-fhir pull request #1777
Opened 2022-12-22 16:38 UTC by ktarasenko

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-10 14:05 UTC, jingtang10 requested changes

2023-01-11 11:50 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceMetadataEntity.kt
> +      Index(value = ["resourceType", "url", "implementationGuideId"], unique = true)
Removed

2023-01-11 11:51 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ImplementationGuideEntity.kt
> +  val canonicalUrl: String? = null,
done

2023-01-11 11:51 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ImplementationGuideEntity.kt
> +  val canonicalUrl: String? = null,
done

2023-01-16 18:14 UTC, omarismail94 reviewed
Nice changes @ktarasenko ! Left a few comments (mostly nits) and questions

2023-01-16 18:14 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ImplementationGuideEntity.kt
> +  /** Location of the physical files of Implementation guide */
this comment is a bit confusing. how about we say:
```
 Directory where the Implementation Guide files are stored
```

2023-01-16 18:14 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceMetadataEntity.kt
>    val fileUri: File,
the variable name, `fileUri` makes me think the type should be `Uri` as opposed to `File`. How about we either update the variable name to `filePath` or keep the name but update the type to `Uri`?

2023-01-16 18:14 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/IgResourceCrossRef.kt
> + */
Do you think we shoud add a link to this documentation:
https://developer.android.com/training/data-storage/room/relationships#many-to-many

I found it useful when reading how CrossRefs work

2023-01-16 18:14 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/IgResourceCrossRef.kt
> + */
Also add a short blurb on what makes us want a many-to-many relationship (or a link to a public doc)

2023-01-16 18:14 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/dao/ImplementationGuideDao.kt
> +  // TODO: implement better conflict resolution (compare the substantive part of the resource and
add a usernamme or an Issue ID in the Todo. e.g. TODO(Issue #0000)

2023-01-16 18:14 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/dao/ImplementationGuideDao.kt
> +  ): ImplementationGuideWithResources?
should the return type here be `List<ImplementationGuideWithResources>`, and later the caller checks if the list is empty? 

Just looking at how it was done in:
https://developer.android.com/training/data-storage/room/relationships#many-to-many

2023-01-16 19:10 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/ImplementationGuideDatabase.kt
> +    [ImplementationGuideEntity::class, ResourceMetadataEntity::class, IgResourceCrossRef::class],
Let's meet at `ImplementationGuideResourceMetadataEntity` :D

2023-01-16 19:16 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ImplementationGuideEntity.kt
> + * [Implementation Guide](https://build.fhir.org/implementationguide.html) description.
What I tried to say, is the fields stored in this entity are a small part of what` ImplementationGuide` FHIR Resource has. It's minimal in the sense of it's as much as necessary to uniquely idenify and resolve an IG from Npm Package manager. 

Tried to reword it, let me know if it looks better.

2023-01-16 19:18 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceMetadataEntity.kt
>    val fileUri: File,
`filePath` sounds like `String` to me. 
How about `resourceFile`?

2023-01-16 19:41 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/IgResourceCrossRef.kt
> + */
Moved the meta description to the Database class. Kept one in this class short.

2023-01-16 19:46 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/dao/ImplementationGuideDao.kt
> +  ): ImplementationGuideWithResources?
This method queries IGs by Id, there must be 0..1 IGs returned. I feel like returning List will be misleading

2023-01-17 13:05 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/ImplementationGuideDatabase.kt
> +    [ImplementationGuideEntity::class, ResourceMetadataEntity::class, IgResourceCrossRef::class],
Deal! 🤝

2023-01-17 13:15 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceMetadataEntity.kt
>    val fileUri: File,
yeah, that's better

2023-01-17 13:22 UTC, omarismail94 reviewed
Just a couple of minor nits!

2023-01-17 13:22 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/ImplementationGuideDatabase.kt
> + * IGs. To spare avoid duplications, [ImplementationGuideEntity] are connected with
nit: To spare avoid duplications -> To avoid duplicates

2023-01-17 13:22 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/entities/ResourceMetadataEntity.kt
>    val fileUri: File,
Yes, that works!

2023-01-17 13:22 UTC, omarismail94 commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/dao/ImplementationGuideDao.kt
> +  ): ImplementationGuideWithResources?
Makes sense, thanks!

2023-01-17 18:53 UTC, ktarasenko commented on implementationguide/src/main/java/com/google/android/fhir/implementationguide/db/impl/ImplementationGuideDatabase.kt
> + * IGs. To spare avoid duplications, [ImplementationGuideEntity] are connected with
done

2023-01-18 16:05 UTC, omarismail94 approved these changes
Great change!!  👌

2023-01-18 16:07 UTC, merged