Support definition based extraction for lists with Non - primitive types
google/android-fhir pull request #1788
Opened 2023-01-03 14:08 UTC by vbothe23

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1769 

**Description**
Issue:
In `addAnswerToListField` if the answerValue is of non-primitive type then the primitiveValue will be null and app crashes with NullPointerException.

Fix:
Added isPrimitiveType check to handle answerValue of primitive and non-primitive types when extracting to list in definition based extraction.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-04 05:15 UTC, joiskash requested changes
Looks good! Congratulations on your first PR, I left a small comment please have a look at it

2023-01-04 05:15 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    observation.value
Remove this line since it is not doing anything

2023-01-04 05:39 UTC, vbothe23 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    observation.value
okay.

2023-01-04 15:30 UTC, omarismail94 reviewed
Nice change @vbothe23 ! Left a few comments

2023-01-04 15:30 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        "add${field.name.capitalize(Locale.ROOT)}",
capitalize is a deprecated call. Can you replace it with `replaceFirstChar`?

2023-01-04 15:30 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  if (answerValue.first().isPrimitive) {
is there a way we can get rid of this if/else, and just have one method call that works on both primitives and non-primitives?

For example:
```
answerValue.first().fhirType().capitalize(Locale.ROOT).javaClass
```

I experimented with this quickly and it seems like it works. Can you further test?

2023-01-05 05:40 UTC, vbothe23 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val iParser: IParser = FhirContext.forR4().newJsonParser()
okay

2023-01-05 05:40 UTC, vbothe23 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        "add${field.name.capitalize(Locale.ROOT)}",
Sure

2023-01-05 05:41 UTC, vbothe23 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  if (answerValue.first().isPrimitive) {
Sure. I will test.

2023-01-06 12:05 UTC, joiskash approved these changes
LGTM!

2023-01-09 09:52 UTC, omarismail94 commented
LGTM, and will let @jingtang10  give the final approval!

Jing - I reviewed the PR and the suggestion I made was to use a method, fhirType(), that works on both primitives and non-primitives

2023-01-16 11:26 UTC, merged

2023-01-26 13:23 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>      .let { method -> answerValue.forEach { method.invoke(base, it.primitiveValue()) } }
this line is still takeing the `it.primitiveValue()` from the answer value. can you tell me who this is working?

2023-01-26 13:24 UTC, jingtang10 commented
@joiskash @omarismail94 @vbothe23 can you please help addressing my above comments in a follow up cl?

2023-01-31 09:57 UTC, joiskash commented
Sure @vbothe23  will do this ASAP.

2023-01-31 11:07 UTC, vbothe23 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +              }
okay

2023-01-31 11:08 UTC, vbothe23 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                }
okay

2023-01-31 11:08 UTC, vbothe23 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +            "linkId": "9",
Sure

2023-01-31 11:14 UTC, vbothe23 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>      .let { method -> answerValue.forEach { method.invoke(base, it.primitiveValue()) } }
Here for non primitive values, `getMethod()` function will throw `NoSuchMethodException` which intern call `updateListFieldWithAnswer()`. UpdateListFieldWithAnswer() function will set the answer.

2023-03-08 18:03 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>      .let { method -> answerValue.forEach { method.invoke(base, it.primitiveValue()) } }
actually nvm i think this code is actually clear enough.

thanks for the reply.