added candidateExpression support
google/android-fhir pull request #1789
Opened 2023-01-04 09:40 UTC by owais-vd

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1038 

**Description**
added implementation based on https://github.com/google/android-fhir/pull/1480 support. 

**Type**
Feature 

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-04 16:34 UTC, omarismail94 reviewed
Nice change! Left a comment on a way to avoid duplicate code. lmk what you think!

2023-01-04 16:34 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
other that the first line, what is different about this function that isn't the same as `resolveAnswerExpression` ?

In `resolveAnswerExpression`, we could change the first line from:

```
    val answerExpression = item.answerExpression ?: return emptyList()
```

to:

```
val answerExpression = item.answerExpression ?: item.candidateExpression ?: return emptyList()
```


If we do this. We can get rid of this function, and the `candidateExpressionMap` variable. 

This only works if an item cannot have both an answer expression and a candidate expression. Can you find out if that is true?

2023-01-04 16:34 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          resolveCandidateExpression = { resolveCandidateExpression(it) }
if we go with the comment above in having everything in `resolveAnswerExpression`, we can delete this

2023-01-04 16:34 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private val resolveCandidateExpression:
if we go with the comment above in having everything in `resolveAnswerExpression`, we can delete this

2023-01-04 16:34 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        runBlocking { viewModel.resolveCandidateExpression(questionnaire.itemFirstRep) }
if we go with the comment above in having everything in `resolveAnswerExpression`, we can call `resolveAnswerExpression` instead

2023-01-05 14:46 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
Thanks, @omarismail94 I've done the changes and updated a PR

2023-01-05 14:47 UTC, owais-vd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        runBlocking { viewModel.resolveCandidateExpression(questionnaire.itemFirstRep) }
fixed according to the above comment.

2023-01-05 14:47 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  private val resolveCandidateExpression:
fixed according to the above comment.

2023-01-05 14:48 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          resolveCandidateExpression = { resolveCandidateExpression(it) }
fixed according to the above comment.

2023-01-06 08:03 UTC, owais-vd commented
Hi @omarismail94 feedback resolved and PR is ready for review.

2023-01-09 09:58 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt
> +              QuestionnaireItemViewHolderType.DROP_DOWN
hmmm, we are making a big change here. Basically, we are saying that if there is a candidate expression, only use a drop down; is that what you want? 

I don't think that makes sense, as we can have candidate expressions in free forms or radio groups etc.

2023-01-09 14:58 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt
> +              QuestionnaireItemViewHolderType.DROP_DOWN
yes you are right, I changed this because in the dropdown we have an option for typing a different value if we need none of the provided list Because according to the second point of the ticket detail (example section), we also need to allow a text entry and other UI options, like `DIALOG_SELECT` and `CHECK_BOX_GROUP` don't have text entry option

2023-01-16 10:40 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt
> +              QuestionnaireItemViewHolderType.DROP_DOWN
@owais-vd  if the change only needs to be done in the drop_down, then the change should only be done in the `QuestionnaireItemDropDownViewHolderFactory` class. `questionnaireItem.candidateExpression` is encapsulated in the `questionnaireItemViewItem` variable in that class. We should not be making changes in this file.

We need to see flush out from a UX design which widgets should support candidate expression. For now,  can you revert this file? Once that is done, we can merge the PR so that the logic to support candidateExpressions is in, without the UX display part

2023-01-17 09:14 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt
> +              QuestionnaireItemViewHolderType.DROP_DOWN
Hi @omarismail94 as per your suggestion, I've reverted `QuestionnaireItemEditAdapter` file. For now, `candidateExpression`  will use `answerExpression` UI by default because both have a reference type.

2023-01-17 11:24 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val answerExpression = item.answerExpression ?: item.candidateExpression ?: return emptyList()
Reading description here https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-candidateExpression.html looks like that the extensions are not mutually exclusive. Also despite having candidate expression user can still lookup or enter other values.

2023-01-17 11:52 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val answerExpression = item.answerExpression ?: item.candidateExpression ?: return emptyList()
@maimoonak https://github.com/google/android-fhir/pull/1789#discussion_r1064733361

2023-04-23 21:54 UTC, jingtang10 requested changes

2023-04-23 21:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    val answerExpression = item.answerExpression ?: item.candidateExpression ?: return emptyList()
candidate expression should not be part of this function. revert this change please.

candidate expression needs to be added to questionnaire view item, so that UI widgets can make decisions about how to render them.

2023-04-27 10:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
@omarismail94 answer expression and candidate expression are two separate functionalities and we need to be explicit about that even though the might be similar functionalities that we can extract into helper functions / utilities.

2023-04-27 11:13 UTC, jingtang10 approved these changes

2023-04-27 11:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
let's' revert changes in this file.

2023-04-27 11:14 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +    val questionItem =
```suggestion
    val questionnaire =
```

2023-04-27 12:29 UTC, owais-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
done

2023-04-27 12:29 UTC, owais-vd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +    val questionItem =
done

2023-04-27 12:29 UTC, owais-vd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +    val questionItem =
done

2023-05-03 10:55 UTC, jingtang10 approved these changes

2023-05-03 10:56 UTC, merged