Hide items if all items they are depending on have also been hidden.
google/android-fhir pull request #1790
Opened 2023-01-04 11:11 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1765 

**Description**
Once a `QuestionnaireItemComponent` is disabled, remove its corresponding answers so that the depending `QuestionnaireItemComponent`s  `enableWhen` fails and disables it.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
[disabled_items.webm](https://user-images.githubusercontent.com/18224849/210542690-e924aaa6-f328-4207-853f-3e8c00a19215.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-12 12:30 UTC, jingtang10 commented
reassigned to aditya. as discussed, we'll make changes to this pr following: https://github.com/google/android-fhir/issues/1765#issuecomment-1380257330

2023-01-13 15:04 UTC, jingtang10 requested changes

2023-01-16 08:38 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val linkIdToAnswersMapForDisabledQuestionnaireResponseItem =
Done

2023-01-16 08:39 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>      // Disabled/hidden questions should not get QuestionnaireItemViewItem instances
Updated. Split the comments for both Hidden and Disabled and added them at appropriate places.

2023-01-16 08:39 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      )
Done

2023-01-16 17:44 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  @Test
can you add a test case where we disable, then re-enable the question item to make sure the caching of disabled answers works?

2023-01-16 17:44 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      }
to avoid a nested if, what if we create a private function (`cacheResponseItemOfDisabledQuestionnaireItem` or something along those lines) that holds this logic? We can then put the comment above this if statement as the Kdoc of the new function?

2023-01-17 08:20 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  @Test
done.

2023-01-17 08:21 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      }
Done

2023-01-17 08:43 UTC, omarismail94 approved these changes
Most excellent! 🚀🚀

2023-01-17 10:41 UTC, merged