Support added for CodeType value in itemExtractionContext extension
google/android-fhir pull request #1791
Opened 2023-01-04 11:55 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1770

**Description**
CodeType value support added in itemExtractionContext extension in ResourceMapper

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-04 13:14 UTC, jingtang10 requested changes
i think in the case of expression, we need to update an exsiting resource. in that case i think we need to use the interface @aditya-07 added to load up the existing resource.

2023-01-04 13:14 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>   */
this needs to be updated. and please add a link to the relevant section in the sdc ig.

2023-01-11 13:28 UTC, jingtang10 requested changes

2023-01-11 13:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
>      this.singleOrNull { it.url == ITEM_CONTEXT_EXTENSION_URL }
can you add a comment to clarify that if there are multiple item extraction context extensions, we will ignore them.

2023-01-11 13:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +            expression.expression
if you're gonna fix this in a follow up pr please add a todo and create an issue.

2023-01-11 14:52 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +            expression.expression
Created issue #1799 for follow up PR

2023-02-08 13:20 UTC, jingtang10 approved these changes

2023-02-08 13:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  get() = this.extension.itemExtractionContextExtensionValue
kinda feel like this function could just be inlined...

2023-02-08 13:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  get() = this.extension.itemExtractionContextExtensionValue
same here

2023-02-10 06:54 UTC, merged