automatically date separator are added between day month year
google/android-fhir pull request #1822
Opened 2023-01-24 07:45 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1802

**Description**
1. issue- date format error message was visible after entering valid date as text input in uestionnaireItemDateTimePickerViewHolderFactory
2. isAndroidIcuSupported check is removed as 24 min API level is supported
3. Figure out separator from date pattern
4. generate new date format have 2 digits for day and month, 4 digits for year mandatory.
5. automatically date separator are added between day month year

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-25 05:35 UTC, santosh-pingle commented
@PallaviGanorkar is it ready for review? (in case if you missed to ask for review)

2023-01-25 11:24 UTC, santosh-pingle commented
@PallaviGanorkar @aditya-07 Is it okay if I do initial review?

2023-01-25 12:05 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        }
```suggestion
        dateFormatSeparator?.let {
          acceptableDateFormat =
            generateAcceptableDateFormat(localeDatePattern, it)
        }
```

2023-01-25 12:52 UTC, PallaviGanorkar commented
> ase if you missed t

you are welcome @santosh-pingle , please go ahead

2023-01-25 12:53 UTC, PallaviGanorkar commented
> @PallaviGanorkar @aditya-07 Is it okay if I do initial review?

Your WC, Please do review

2023-01-25 13:08 UTC, santosh-pingle reviewed
@PallaviGanorkar thanks for this change.

can you please upload the video for this change?

2023-01-25 13:08 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +        object : TextWatcher {
Can we use same text watcher for DatePicker and DatetimePicker for formatting date, it will avoid duplication of the code?

2023-01-26 14:03 UTC, omarismail94 reviewed
Thanks Pallavi for this change! In addition to the comments from Santosh, I noticed that when you type  the date in full. wrongly or correctly, e.g: `01/01/1999`, and then press backspace 3 times, it deletes the entire string, as opposed to having the text box showing `01/01/1`

2023-01-27 06:18 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      private var dateFormatSeparator: Char? = null
lateinit can not be used with primitive type

2023-01-27 06:53 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  return newDateFormat.toString()
This does not work for some locate date format like Korean, it throws exception

2023-01-27 06:58 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +        }
after null safety  we  are using not null operator(!!) ,So it will not Given NPE. Also dateFormatSeparator is nullable so nee to have null safety  check

2023-01-27 07:01 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +        object : TextWatcher {
it has different handling in afterTextChanged(), but i will try to make common logic in in separate function.

2023-01-27 08:05 UTC, PallaviGanorkar commented
> Thanks Pallavi for this change! In addition to the comments from Santosh, I noticed that when you type the date in full. wrongly or correctly, e.g: `01/01/1999`, and then press backspace 3 times, it deletes the entire string, as opposed to having the text box showing `01/01/1`
> 
> Also, if I put the pointer anywhere in the middle and press backspace, the entire string is removed.
> 
> Can you fix this and add a test case?

@omarismail94  this behavior is expected. as we clear text with backspace from end or middle and date parsing is failed answer will be cleared from questionnaireItemViewItem.clearAnswer() , and results in clearing /removing entire string

2023-01-27 09:46 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +      private var dateFormatSeparator: Char? = null
added comment

2023-01-27 14:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  if (editableLength < acceptableDateFormat.length) {
```suggestion
  if (editable.length < acceptableDateFormat.length) {
```
editable.length will be consistent with acceptableDateFormat.length, can you please update at other places as well.

2023-01-27 14:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      editable.append(acceptableDateFormat[editableLength])
can you please add inline comment to explain this use case with example?

2023-01-27 14:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      editable.append(acceptableDateFormat[editableLength])
can you please add inline comment to explain this use case with example.
e.g 02 is matching with dd/MM/yyyy so appending `/` to editable 02/
2023 is matching with yyyy/MM/dd so appending `/ `to editable 2023/

2023-01-27 14:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    }
please refer earlier comment to add inline comment to explain use case with example.

2023-01-27 14:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            dateFormatSeparator?.let {
can you please refer earlier comment?

2023-01-30 07:06 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  return newDateFormat.toString()
@santosh-pingle Thanks for suggestion,
1. Actually it breaks in Korean because it has space in between like yy. M. d. and 
2.  Korean has postfix, and some other locale may have prefix, So we my have to handle every scenario there instead of that I preferred to keep this logic simple.
 Please let me know if you have other thought

2023-01-30 10:19 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  if (editableLength < acceptableDateFormat.length) {
Its used around 10 places , so defined variable for this

2023-01-31 03:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    }
```suggestion
        if (acceptableDateFormat[editable.lastIndex] == dateFormatSeparator &&
      editable[editable.lastIndex] != dateFormatSeparator
    ) {
      // this case to handle when user deletes separator from "12/" to "12" and enter digit again
      // like "123" then it should convert to "12/3" as per format
      editable.insert(editable.lastIndex, dateFormatSeparator.toString())
    }
```

2023-01-31 03:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +        private val dateFormatSeparator = dateFormatSeparator
please refer earlier comment.

2023-01-31 13:24 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  return newDateFormat.toString()
lets discuss it over call and sort it out

2023-01-31 13:31 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +internal fun handleDateFormatAfterTextChange(
its internal function and name is self explanatory So have added kdoc as its not there for other internal methods as well.

2023-01-31 14:41 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  return newDateFormat.toString()
As discussed this code work, previous suggested code was breaking for Korean locale date format. its good suggestion and in Kotlin way optimized.

Here In my opinion instead of handling both postfix and prefix separately, and joining list with separator, let date separator get added sequentially in acceptable date format as per locale date format due avoid further issues(code break) as we can not test all locales date patterns

2023-01-31 14:42 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +internal fun handleDateFormatAfterTextChange(
done

2023-02-01 01:42 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      editable.append(acceptableDateFormat[editableLength])
Is this resolved?

2023-02-01 01:57 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  return newDateFormat.toString()
thanks! @PallaviGanorkar

Pallavi and me reviewed it, if any suggestion is missed from our end please feel to add @aditya-07 @omarismail94 @jingtang10 thanks!

2023-02-01 02:16 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDatesTest.kt
> +  fun getDateSeparator_US() {
```suggestion
  fun `parse separator for US locale date pattern`
```
please also update the change at other places

2023-02-01 02:23 UTC, santosh-pingle commented
Thanks! @PallaviGanorkar its look ok to me, others can review it.

2023-02-01 03:32 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +}
is it okay to have return type String? if yes, can you please try below suggestion ?

```suggestion
  internal fun formatDate(localDate: LocalDate?, acceptableDateFormat: String?) =
    localDate?.let {
      if (acceptableDateFormat.isNullOrEmpty()) {
        it.localizedString
      } else {
        DateTimeFormatter.ofPattern(acceptableDateFormat).format(localDate)
      }
    }
```
Or if you need return type String only, you can try below suggestion

```
internal fun formatDate(localDate: LocalDate?, acceptableDateFormat: String?): String {
    localDate?.let {
      return if (acceptableDateFormat.isNullOrEmpty()) {
        it.localizedString
      } else {
        DateTimeFormatter.ofPattern(acceptableDateFormat).format(localDate)
      }
    }
    return ""
  }
```

2023-02-01 11:31 UTC, jingtang10 requested changes

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +        >%1$s</xliff:g>\nExample: %2$s</string>
this looks good. but my only question is that do we want to keep this in one line to take up less space in the screen. for example:

`Date format needs to be dd/mm/yyyy (e.g. 01/01/2023)`

@shelaghm 

i think the difference here is that the multi line error message in the dialog doesn't affect other parts of the screen because it's a modal dialog. but our date widget is inline as part of a questionnaire, so if it's multi line it does push things down the screen a bit more.

i'll let you and @shelaghm decide

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +/** Special character used in date format */
please add an example in the kdoc.

```
Returns the first character that is not a letter in the given date pattern string (e.g. "/" for "dd/mm/yyyy").
```

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> + * Convert date pattern to acceptable date pattern where 2 digits are expected for day(dd) and
```suggestion
 * Converts date pattern to acceptable date pattern where 2 digits are expected for day(dd) and
```

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> + * month(MM), 4 digits are expected for year(yyyy).
```suggestion
 * month(MM), and 4 digits are expected for year(yyyy).
```

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> + * month(MM), 4 digits are expected for year(yyyy).
optionally: add an example, "e.g. dd/mm/yyyy is returned for d/mm/yy"

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +internal fun generateAcceptableDateFormat(datePattern: String, dateFormatSeparator: Char): String {
i think the second parameter can be removed and within this function you can find out the separator by calling function `getDateSeparator`

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +        if (!newDateFormat.contains("dd")) {
can you add 3 local variables: hasDay, hasMonth, hasYear that are set to false, and set to true when you have seen d or m or y.

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +/** Parse date string into given date format. */
```suggestion
/** Parses a date string using the given date format. */
```

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +    throw ParseException("Year has lesss than 4 digits.", -4)
```suggestion
    throw ParseException("Year has less than 4 digits.", -4)
```

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +    throw ParseException("Year has lesss than 4 digits.", -4)
shouldn't the error offset be something like `localDate.indexOf("y")`?

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +    throw ParseException("Year has more than 4 digits.", 4)
same here with the error offset.

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +
```suggestion
  val dateFormat = if (!acceptableDateFormat.isNullOrEmpty()) {
    SimpleDateFormat(acceptableDateFormat)
  } else {
    ...
  }
  val localDate =
    dateFormat.apply { isLenient = false }
      .parse(text.toString())
      .localDate
```

2023-02-01 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  // date/localDate with year less than 4 digit throws ParseException which force user to enter year
```suggestion
  // Throw ParseException if year is less than 4 digits.
```

2023-02-01 12:16 UTC, jingtang10 requested changes

2023-02-01 12:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +internal fun formatDate(localDate: LocalDate?, acceptableDateFormat: String?): String? {
```suggestion
internal fun formatDate(localDate: LocalDate, acceptableDateFormat: String): String {
```

2023-02-01 12:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> -internal val localeDatePattern =
can you just make this a function called `getLocalizedDateTimePattern`

2023-02-01 12:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      inner class DateTextWatcher(private val dateFormatSeparator: Char) : TextWatcher {
either give it a slightly more descriptive name (DatePatternTextWatcher? DateSeparatorTextWatcher?), and/or add kdoc that says:

`Automatically appends date separator (e.g. "/") during date input.`

2023-02-01 12:32 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +    throw ParseException("Year has lesss than 4 digits.", -4)
localDate is object of type LocalDate, so can not get indexOf("y"),  instead using localDate.year.length() as error offset because year length is causing exception here. Please let me know if you have other thoughts

2023-02-01 12:34 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +    throw ParseException("Year has more than 4 digits.", 4)
same as above comment

2023-02-01 13:13 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +  if (editableLength > acceptableDateFormat.length) {
Same thing is handled here, if we have fix length then we can add property of max length but this is dynamic

2023-02-01 13:19 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +      editable.append(acceptableDateFormat[editableLength])
Done

2023-02-01 13:47 UTC, PallaviGanorkar commented on datacapture/src/main/res/values/strings.xml
> +        >%1$s</xliff:g>\nExample: %2$s</string>
Waiting for discussion with @shelaghm

2023-02-01 16:08 UTC, jingtang10 requested changes

2023-02-01 16:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +    // if user is deleting separator then don't add it again. So check is added if its not deleting.
```suggestion
    // Do not add the separator again if the user has just deleted it.
```

2023-02-01 16:15 UTC, PallaviGanorkar commented on datacapture/src/main/res/values/strings.xml
> +        >%1$s</xliff:g>\nExample: %2$s</string>
AS discussed with @shelaghm , doing changes as @jingtang10 suggested

2023-02-08 13:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDatesTest.kt
> +  fun `get date separator for US locale`() {
```suggestion
  fun `should get date separator for US locale`() {
```

2023-02-08 13:13 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/MoreLocalDatesTest.kt
> +  fun `format ITALY locale date using no canonicalizedDatePattern gives localized date string`() {
```suggestion
  fun `should use default locale if pattern is empty`() {
```

2023-02-08 13:30 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +import java.util.*
Yes, it was auto converted. thank for pointing out this.  Its resolved now.

2023-02-08 14:34 UTC, jingtang10 approved these changes

2023-02-08 14:34 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +internal fun parseDate(text: String, canonicalizedDatePattern: String): LocalDate {
```suggestion
internal fun parseDate(text: String, datePattern: String): LocalDate {
```

2023-02-08 14:34 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +internal fun canonicalizeDateFormat(datePattern: String): String {
let's call this date format or date pattern and use this across all functions.

2023-02-08 15:00 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDateTimes.kt
> +  get() = toLocalDate().format()
Do we use this variable anywhere in our codebase anymore after the changes done int he MoreTypes file?

2023-02-08 15:00 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +    if (!canonicalizedDatePattern.isEmpty()) {
replace this with `canonicalizedDatePattern.isNotEmpty()`

2023-02-08 15:00 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  val localDate = dateFormat.apply { isLenient = false }.parse(text.toString()).localDate
do we need the extra `toString()` call in the `text` variable?

2023-02-08 15:00 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/MoreLocalDates.kt
> +  // Expected character '-' at index 4 but found 3
nit: can we make this in the docstring format: 
```
/*

/
```

and have the referenced classes linked via [] ?

2023-02-09 10:34 UTC, omarismail94 approved these changes

2023-02-09 10:34 UTC, merged

2023-02-14 10:36 UTC, PallaviGanorkar commented
Attaching video for updated changes in this PR
[date_picker.webm](https://user-images.githubusercontent.com/13957417/218710980-e9e235f6-50ac-419f-b24b-3e97b2fe5f79.webm)
[date_time_picker.webm](https://user-images.githubusercontent.com/13957417/218711030-edbabbba-f9a1-4e8b-a6ba-fff3eb0ced76.webm)

2023-02-14 21:32 UTC, shelaghm commented
Thanks @PallaviGanorkar for the videos. Looks good to me.