Show submit button in review mode.
google/android-fhir pull request #1826
Opened 2023-01-24 13:19 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1817

**Description**
 1. Make submit button Visible in Review mode if the app is using the inbuilt submit button.
 2. Updated `QuestionnaireValidationErrorMessageDialogFragment` and `QuestionnaireFragment` to pass in appropriate result messages in callback to change mode from Review to Edit incase there are errors on Submit and user decides to fix them.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
[review_mode_edit.webm](https://user-images.githubusercontent.com/18224849/214304944-d5fd066d-a9f8-4626-91a8-d5fe219b8843.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-25 05:31 UTC, santosh-pingle reviewed
@aditya-07 can we please also add unit tests or android tests, if possible?

2023-01-25 05:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +            submitButton.visibility = if (displayMode.showSubmitButton) View.VISIBLE else View.GONE
```suggestion
            submitButton.visibility = if (displayMode.showSubmitButton) {
            View.VISIBLE 
            } else {
            View.GONE
            }
```

2023-01-25 11:21 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +            submitButton.visibility = if (displayMode.showSubmitButton) View.VISIBLE else View.GONE
Since the whole `if else ` fits in a single line, I don't think adding brackets is necessary.

2023-01-25 11:21 UTC, aditya-07 commented
> @aditya-07 can we please also add unit tests or android tests, if possible?

Added some tests for checking the visibility of Submit Button.

2023-01-26 15:32 UTC, jingtang10 requested changes

2023-01-26 15:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +        else -> setFragmentResult(SUBMIT_REQUEST_KEY, Bundle.EMPTY)
can you make this a bit more explicit but using RESULT_VALUE_SUBMIT?

this is so that if in the future we add another value it would be more obvious what to do

2023-01-26 15:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        .isEqualTo(DisplayMode.ReviewMode(showEditButton = true, showSubmitButton = true))
is there a case where showSubmitButton would be false? is that covered here?

2023-01-30 14:05 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        .isEqualTo(DisplayMode.ReviewMode(showEditButton = true, showSubmitButton = true))
It would be false when the application overrides the default theme to disable SDC's Submit button and have their own.

2023-01-30 20:10 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +        else -> setFragmentResult(SUBMIT_REQUEST_KEY, Bundle.EMPTY)
Done

2023-02-01 13:03 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        .isEqualTo(DisplayMode.ReviewMode(showEditButton = true, showSubmitButton = true))
may be one more test can be added in QuestionnaireFragmentTest.kt by enabling readOnlyMode  with argument `QuestionnaireFragment.EXTRA_READ_ONLY to true` which can set showSubmitButton as false?

2023-02-03 11:40 UTC, jingtang10 approved these changes

2023-02-06 07:35 UTC, merged