Fix unit tests in QuestionnaireViewModelTest
google/android-fhir pull request #1827
Opened 2023-01-24 18:36 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1820 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-24 18:36 UTC, omarismail94 commented
TODO: get the two tests that are failing to pass

2023-02-06 10:27 UTC, aditya-07 reviewed
We should also add a small writeup describing how to write these tests with turbine for anyone adding tests in the future.

2023-02-06 13:54 UTC, jingtang10 requested changes
thanks so much @omarismail94!

2023-02-06 13:54 UTC, jingtang10 commented on buildSrc/src/main/kotlin/JacocoConfig.kt
> + * Copyright 2022 Google LLC
please revert

2023-02-06 13:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  internal companion object {
revert

2023-02-06 13:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    internal val paginationExtension =
revert

2023-02-06 13:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    internal val hiddenExtension =
revert

2023-02-06 13:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        assertThat(awaitItem().items.map { it.asQuestion() }.map { it.questionnaireItem.linkId })
as discussed:
1. try if you can call awaitItem multiple times to get to the later state
2. see what you can do with `getQuestionnaireItemViewItemList`

2023-02-06 13:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            QuestionnaireResponseItemValidator.validate(
can you explain why this is needed?

2023-02-06 23:55 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        .isEqualTo(true)
I got rid of Turbine and found a way to get the test to work. We need to add our own dispatcher to override the hardcoded viewModelScope, and make sure we launch any collect jobs in it as well. Please see the documentation I added to the top of the file

2023-02-06 23:57 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            QuestionnaireResponseItemValidator.validate(
we dont need this anymore. I found a way to run the tests correctly. The issue was the tests were not running in the viewModelScope. I fixed this!  Please see the documentation I added to the top of the file that links to how I got to this solution!

2023-02-06 23:57 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        assertThat(awaitItem().items.map { it.asQuestion() }.map { it.questionnaireItem.linkId })
This is outdated as I got rid of the need to have turbine.awaitItem

2023-02-08 18:48 UTC, jingtang10 approved these changes

2023-02-08 18:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +      collectJob.cancel()
you could have a private helper function:

```
private fun something(block: {}) {
  val collectJob = ...
  block.run()
  collectJob.canel()
}
```

2023-02-08 21:17 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +      collectJob.cancel()
Implemented this! Great suggestion as this cleaned up the code. I also added a test case where we do an incorrect cast just to check that an exception is raised and is not swallowed like before

2023-02-08 21:48 UTC, merged