Attachment widget clear preview if no answer
google/android-fhir pull request #1828
Opened 2023-01-25 08:31 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1821

**Description**
Clear preview if no answer

**Alternative(s) considered**
N/A

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

[device-2023-01-25-152610.webm](https://user-images.githubusercontent.com/62053304/214514994-3d009bb0-3067-4baf-a066-b2ef0ef301d9.webm)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-01-25 10:09 UTC, santosh-pingle reviewed
Can you please also write unit or android tests if possible?
thanks!

2023-01-25 10:09 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
>        }
```suggestion
      private fun displayInitialPreviewOrClear() {
        val answer = questionnaireItemViewItem.answers.firstOrNull()

        // When there are several Attachment widgets, this prevents a bug when the user uploads a
        // file then shows a preview on the first widget, the last widget will also have the same
        // preview but with no appended answer. So we should always clear the preview when there is
        // no answer.
        // This happens because RecyclerView is recycling a widget that already displays the
        // preview.
        if (answer == null) {
          clearPhotoPreview()
          clearFilePreview()
          hideDeleteButton()
          return
        }
        
        answer.valueAttachment?.let { attachment ->
          displayPreview(
            attachmentType = attachment.contentType.type,
            attachmentTitle = attachment.title,
            attachmentByteArray = attachment.data
          )
        }
      }
```

2023-01-25 13:25 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
>        }
Done

2023-01-25 13:25 UTC, FikriMilano commented
Sure. doing test

2023-01-25 13:30 UTC, FikriMilano commented
@santosh-pingle kindly do another review

2023-01-26 14:12 UTC, jingtang10 requested changes

2023-01-26 14:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +      private fun displayInitialPreviewOrClear() {
this sounds better:

```suggestion
      private fun displayOrClearInitialPreview() {
```

or actually the original function name seemed fine to me.

up to you

2023-01-26 14:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        // preview.
I think this is a bit too verbose. also, this bug isn't to do with "first" or "last", it's just the fact that some views are recycled.

I'd suggest simply:

```suggestion
        // Clear preview if there is no answer to prevent showing old previews in views that have been recycled.
```

2023-01-26 14:12 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotDisplayPreviewFromNullAnswer() {
does this actually test the case? don't you have to bind the widget to an item with answer first, and then bind the widget to an item without answer and check the preview is cleared?

2023-01-27 07:33 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotDisplayPreviewFromNullAnswer() {
my bad, let me do that

2023-01-27 07:33 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +        // preview.
sure

2023-01-27 07:36 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +      private fun displayInitialPreviewOrClear() {
i actually like this one

2023-01-27 07:36 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentViewHolderFactory.kt
> +      private fun displayInitialPreviewOrClear() {
the new name i mean

2023-01-30 13:25 UTC, FikriMilano commented
@jingtang10 this is ready for another review

2023-02-01 12:24 UTC, santosh-pingle reviewed
thanks! @FikriMilano,  it looks ok to me, others can please review it.

2023-02-01 12:24 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotDisplayPreviewFromNullAnswerAfterPreviouslyBindingNonNullAnswer() {
optional : may be we can name something like
```suggestion
  fun doNotShowPreviewOfPreviousAnswerAttachmentForCurrentAnswerItem() {
```

2023-02-01 12:24 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotDisplayPreviewFromNullAnswer() {
optional : can we name something like
```suggestion
  fun doNotShowPreviewIfAnswerDoesNotHaveAttachment() {
```

2023-02-02 07:00 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotDisplayPreviewFromNullAnswerAfterPreviouslyBindingNonNullAnswer() {
sure

2023-02-02 07:00 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAttachmentPickerViewHolderFactoryEspressoTest.kt
> +  fun shouldNotDisplayPreviewFromNullAnswer() {
sure

2023-02-02 09:27 UTC, jingtang10 approved these changes
Thanks @FikriMilano for fixing and thanks @santosh-pingle for taking a look!

2023-02-02 09:27 UTC, merged