Add x-fhir-query enhancement
google/android-fhir pull request #1844
Opened 2023-02-06 10:57 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1658 

**Description**
* Enhance x-fhir-query to handle fhirpath expression in query as defined in spec https://build.fhir.org/ig/HL7/sdc/expressions.html#x-fhir-query-enhancements
* Pass in context into QuestionnaireViewMode

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

In this PR, we pass in the context as a JSON string which we then parse.  I tried passing in the context as  an ID only, so that it can be fetched, but we cannot use the xFhirQueryResolver to fetch the resource as the query  `Resource/Id` does not work

**Type**
Choose one: (Bug fix | **Feature** | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-01 15:34 UTC, KhumboLihonga commented
@omarismail94 @jingtang10 Just bringing awareness to this as I see this was marked for review 3 weeks ago but there hasn't been an update since.

2023-03-02 10:19 UTC, omarismail94 commented
thanks @KhumboLihonga for the ping! We were busy working on the 1.0.0 SDC release and now that's over we can re-focus on this. I updated the PR and will talk to @jingtang10 and team on getting a review

2023-03-02 14:46 UTC, jingtang10 requested changes
👍👍👍

2023-03-02 14:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +internal fun Base.asExpectedType(): Type {
move this to the `extensions` package.

2023-03-02 14:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +  internal val xFhirQueryEnhancementRegex = Regex("\\{\\{(.*?)\\}\\}")
please add move extensive unit tests to just test this string.

2023-03-02 14:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_QUESTIONNAIRE_RESOURCE_CONTEXT_JSON_STRING =
internal

2023-03-02 14:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            .map {
See if you can use `mapValues` for this one i think

2023-03-02 14:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          ExpressionEvaluator.xFhirQueryEnhancementRegex
explore packaging this up in the `ExpressionEvaluator.kt` file in `fhirpath` package

2023-03-02 14:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              val (fhirPathWithParentheses, fhirPath) = it.groupValues
does this work?

```suggestion
            .map { (fhirPathWithParentheses, fhirPath) ->
```

2023-03-06 19:36 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            .map {
I am not sure if that works. ` Sequence<MatchResult>` is what `findAll` returns and `mapValues`  operates on a `Map<out K, V>`.

2023-03-24 17:57 UTC, jingtang10 requested changes
thanks omar - discussed... please see http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-launchContext.html and make sure we're matching the launch context code with the resource provided using the new arg.

2023-03-24 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirquery
```suggestion
   * https://build.fhir.org/ig/HL7/sdc/expressions.html#x-fhir-query-enhancements
```

2023-03-24 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private fun createXFhirQueryFromExpression(expression: Expression): String =
optional: maybe organise this functionality in a different package? maybe in a new package called `expression` which includes the current `fhirpath` package.

2023-03-24 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +  fun `evaluateXFhirEnhancement() should  return one pair`() {
```suggestion
  fun `evaluateXFhirEnhancement() should return one pair`() {
```

2023-03-24 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +  fun `evaluateXFhirEnhancement() should evaluate to null for field that does not exist in resource`() {
add a test case where the type of the resource provided to the expression evaluator does not match the base type in the fhir path expression.

2023-03-27 15:55 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreTypes.kt
> +fun Type.valueOrCalculateValue(): Type? {
Fixed in this PR

2023-03-29 10:01 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private fun createXFhirQueryFromExpression(expression: Expression): String =
I explored this option and found it just easier to move all the x-fhir stuff in ExpressionEvaluator

2023-03-29 12:57 UTC, jingtang10 reviewed
i think the launch context is actually coming from a value set containing a small set of resource types. so please make sure you're enforcing that and that there is documentation.

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      "questionnaire-resource-id-for-context"
```suggestion
      "questionnaire-resource-context"
```

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val questionnaireResourceContext: Resource?
```suggestion
  private val questionnaireLaunchContext: Resource?
```

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +   * Create an x-fhir-query string for evaluation
```suggestion
   * Creates an x-fhir-query string for evaluation.
```

and apply for the rest of the PR

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +    resourceContext: Resource?
```suggestion
    launchContext: Resource?
```

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +      }
add new line

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +      .map {
as discussed, move the warning to `evaluateXFhirEnhancement`

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  //        Initialization with Questionnaire Resource Context            //
```suggestion
  //         Initialization with Questionnaire Launch Context             //
```

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  @Test
add new line

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `should throw exception if resource context is set but questionnaire does not contain launchContext extension`() =
```suggestion
  fun `should throw exception if launch context is set but questionnaire does not contain launchContext extension`() =
```

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +                )
can just remove this

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `should throw exception if resource type in context is not part of launchContext set`() =
maybe:

```suggestion
  fun `should throw exception if launch context is not one of the allowed resource types`() =
```

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
as discussed, some of these test cases should be in `MoreQuestionnairesTest.kt`

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +  fun `createXFhirQueryFromExpression() should evaluate to empty string for incorrect fhir path`() {
this is a degenerative case of the previous

2023-03-29 17:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +  @Test
add empty line

2023-04-04 10:33 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesTest.kt
> +              )
remove this?

2023-04-06 13:32 UTC, jingtang10 approved these changes

2023-04-06 14:54 UTC, merged