Improve overriding dimens
google/android-fhir pull request #1852
Opened 2023-02-08 02:04 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1832

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-02-08 05:54 UTC, FikriMilano commented
@jingtang10 this is ready for review

2023-02-14 11:06 UTC, jingtang10 requested changes

2023-02-14 11:06 UTC, jingtang10 commented on datacapture/src/main/res/values/dimens.xml
> +    <dimen name="dialog_option_item_margin_horizontal">8dp</dimen>
let's keep these the same as the option item margins outside the dialog - so remove these.

2023-02-14 11:06 UTC, jingtang10 commented on datacapture/src/main/res/values/dimens.xml
> +    <dimen name="option_item_margin">16dp</dimen>
```suggestion
    <dimen name="option_item_margin_vertical">16dp</dimen>
```

2023-02-14 11:06 UTC, jingtang10 commented on datacapture/src/main/res/values/dimens.xml
>      <dimen name="radio_button_item_gap">16dp</dimen>
this should be now `option_item_margin_horizontal`

can you also move this next to `option_item_margin_vertical` and add emtpy lines above and below and add a small comment.

2023-02-16 07:45 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_item_edit_text_multi_line_view.xml
> +    android:layout_marginTop="@dimen/item_margin_top"
okay, will do that.

however, because the item_margin_vertical is also used for purposes other than the gap between widgets. I will create new dimens to replace those other purposes. So that when we override item_margin_vertical, it won't affect other stuff.

2023-02-16 07:47 UTC, FikriMilano commented on datacapture/src/main/res/values/dimens.xml
> +    <dimen name="dialog_option_item_margin_horizontal">8dp</dimen>
okay, we might need this at some point, but let's do that if people ask for it

2023-02-22 01:14 UTC, FikriMilano commented on datacapture/src/main/res/values/dimens.xml
>      <dimen name="radio_button_item_gap">16dp</dimen>
done

2023-02-22 01:15 UTC, FikriMilano commented on datacapture/src/main/res/values/dimens.xml
> +    <dimen name="option_item_margin">16dp</dimen>
done

2023-02-22 01:15 UTC, FikriMilano commented on datacapture/src/main/res/values/dimens.xml
> +    <dimen name="dialog_option_item_margin_horizontal">8dp</dimen>
done

2023-02-22 01:17 UTC, FikriMilano commented
@jingtang10 I'll check all dimens and make sure people can override those safely

2023-03-28 13:35 UTC, jingtang10 approved these changes
Thanks!

2023-03-31 09:16 UTC, FikriMilano commented
I'll resolve this once I'm back from exam leave. 
Will return on April 17th. 

2023-04-21 17:55 UTC, merged