Enable bottom container style and behavior customization
google/android-fhir pull request #1859
Opened 2023-02-10 09:59 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1842

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-02-14 11:09 UTC, jingtang10 commented
@shelaghm fyi

2023-02-14 21:20 UTC, shelaghm commented
@FikriMilano Great work! 
One suggestion is to center the button inside the bottom container with 8px padding on top and bottom. See screenshot below.
<img width="945" alt="Screenshot 2023-02-14 at 13 17 57" src="https://user-images.githubusercontent.com/86378921/218865582-c1d29bfa-187b-4ea8-96ea-ebd2894bd7f4.png">

2023-02-15 09:03 UTC, FikriMilano commented
@shelaghm thanks! I'll add that as the default style

2023-02-16 07:34 UTC, FikriMilano commented
@shelaghm padding fixed!

<img src="https://user-images.githubusercontent.com/62053304/219297316-7ebd3e29-47f1-40f6-96d6-25bbecfd1f9f.png" width="300">

2023-02-16 23:13 UTC, shelaghm commented
Excellent, thank you @FikriMilano

2023-02-17 13:37 UTC, jingtang10 requested changes

2023-02-17 13:37 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        parent="Widget.Material3.MaterialDivider"
remove this

2023-02-17 13:37 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:visibility">gone</item>
can you post a screenshot with this not being gone in the catalog app and see if @shelaghm thinks we should change this to visible by default.

2023-02-17 13:37 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:paddingBottom">@dimen/padding_quarter_size</item>
can we define more concrete size attributes. quarter size seems very generic.

2023-02-17 14:05 UTC, FikriMilano commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:visibility">gone</item>
<img src="https://user-images.githubusercontent.com/62053304/219676726-b912bed6-b1f9-4994-9d26-67bfe404a4a6.png" width="300">

2023-02-17 17:21 UTC, shelaghm commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:visibility">gone</item>
The benefit of the divider being visible is that it's likely more obvious for users to discover that there's more content to see below the fold. I agree we can make this visible by default. @FikriMilano

2023-02-17 17:23 UTC, shelaghm commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:paddingBottom">@dimen/padding_quarter_size</item>
@FikriMilano what is this padding for? I suggest using padding in increments of 8. So 8/16/24 etc

2023-02-20 12:35 UTC, FikriMilano commented on datacapture/src/main/res/values/styles.xml
> +        parent="Widget.Material3.MaterialDivider"
removed

2023-02-20 12:35 UTC, FikriMilano commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:visibility">gone</item>
okay, will do that

2023-02-20 12:54 UTC, FikriMilano commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:paddingBottom">@dimen/padding_quarter_size</item>
this padding is for general purposes, hence the name. But I will change this because we need the naming to be more specific. So people can override it without affecting other components.

@shelaghm are you ok if the result looks a bit different from the original design? because when I try this, 4dp looks more similar to the design, than 8dp.
if you're ok, then we can implement the 8dp.

- 4dp vertical padding 
   <img src="https://user-images.githubusercontent.com/62053304/220111479-b2550f11-1fab-4dcc-ba88-b3d7718d1ee2.png" width="300">

- 8dp vertical padding 
   <img src="https://user-images.githubusercontent.com/62053304/220111810-01e36502-1b80-4602-81c3-24e93de78c1f.png" width="300">

2023-02-22 05:03 UTC, shelaghm commented on datacapture/src/main/res/values/styles.xml
> +      <item name="android:paddingBottom">@dimen/padding_quarter_size</item>
@FikriMilano I think the 8dp looks better due to it having more breathing room.  Thanks for checking.

2023-03-03 05:28 UTC, santosh-pingle commented
Reviewing pr, thanks!

2023-03-03 07:24 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  open fun onScrollListener(
QuestionnaireFragment is no more open.

One of the approaches is 
QuestionnaireFragment can be accessed by using its tag in the application code, and the recycler view within it can be manipulated and set up with an onScrollListener.
```
val fragment = childFragmentManager.findFragmentByTag(QUESTIONNAIRE_FRAGMENT_TAG) as? QuestionnaireFragment
    fragment?.let {
      view?.findViewById<RecyclerView>(R.id.questionnaire_edit_recycler_view)
        ?.setOnScrollChangeListener { v, scrollX, scrollY, oldScrollX, oldScrollY ->
         // you can update your change.
        }
    }
```

2023-03-03 07:24 UTC, santosh-pingle commented on datacapture/src/main/res/values/attrs.xml
> +    <!--   Style for bottom container. -->
please add blank line above it.

2023-03-06 20:25 UTC, jingtang10 requested changes

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +        android:id="@+id/container_divider"
this id needs to be more specific. probably `bottom_nav_container_divider`?

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +        android:id="@+id/bottom_container"
```suggestion
        android:id="@+id/bottom_nav_container"
```

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +import androidx.constraintlayout.widget.ConstraintLayout
As @santosh-pingle said QuestionnaireFragment is no longer open. Can all changes in this file be reverted?

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/res/values/attrs.xml
> +    <attr name="questionnaireBottomContainerStyle" format="reference" />
```suggestion
    <attr name="questionnaireBottomNavContainerStyle" format="reference" />
```

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/res/values/attrs.xml
> +    <attr name="questionnaireBottomContainerDividerStyle" format="reference" />
```suggestion
    <attr name="questionnaireBottomNavContainerDividerStyle" format="reference" />
```

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +    <style name="Questionnaire.BottomContainerStyle" parent="">
```suggestion
    <style name="Questionnaire.BottomNavContainerStyle" parent="">
```

2023-03-06 20:25 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        name="Questionnaire.BottomContainerDividerStyle"
```suggestion
        name="Questionnaire.BottomNavContainerDividerStyle"
```

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  open fun onScrollListener(
yup, cool

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +        android:id="@+id/container_divider"
sure

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +        android:id="@+id/bottom_container"
sure

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +import androidx.constraintlayout.widget.ConstraintLayout
sure

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/res/values/attrs.xml
> +    <attr name="questionnaireBottomContainerStyle" format="reference" />
sure

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/res/values/attrs.xml
> +    <attr name="questionnaireBottomContainerDividerStyle" format="reference" />
sure

2023-03-13 13:21 UTC, FikriMilano commented on datacapture/src/main/res/values/styles.xml
> +    <style name="Questionnaire.BottomContainerStyle" parent="">
sure

2023-03-13 13:22 UTC, FikriMilano commented on datacapture/src/main/res/values/styles.xml
> +        name="Questionnaire.BottomContainerDividerStyle"
sure

2023-03-24 19:33 UTC, jingtang10 approved these changes

2023-03-24 20:01 UTC, merged