DateTime Picker : Do not enable time input if date textfield is empty, do not show error message if date input is valid.
google/android-fhir pull request #1871
Opened 2023-02-15 09:52 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1870 

**Description**

- Do not enable the time input textField if the date input textField is empty.
- If the date input in the date textField is valid, then there should be no error message displayed.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-02-15 10:42 UTC, jingtang10 requested changes

2023-02-15 10:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          val dateAsPartialInput =
jsut remove this variable

2023-02-15 10:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          }
just put this in the catch block

2023-02-15 10:43 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            } catch (parseException: Exception) {
Use ParseException instead of Exception

2023-02-15 12:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          val dateAsPartialInput =
done.

2023-02-15 12:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          }
done.

2023-02-15 12:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            } catch (parseException: Exception) {
done.

2023-02-15 13:05 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/219035310-d7c6675c-903c-4744-a9be-a2de6617564f.mov

2023-02-15 14:25 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +internal fun Context.invalidDateErrorText(@StringRes resId: Int, formatPattern: String) =
As discussed, let's make this a function as opposed to an extension function

2023-02-15 14:34 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          displayDateValidationError(NotValidated)
is there a reason we set this now as `NotValidated` as opposed to `Valid`?

2023-02-16 02:32 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          displayDateValidationError(NotValidated)
If the validation result is either `Valid` or `NotValidated', it removes the validation error text from the view, except in one case where if the result is 'valid' but the answer is not present.
In this case, even though the date is valid, the answer cannot be present, so it is still necessary to remove the error text.

2023-02-20 11:19 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +internal fun Context.invalidDateErrorText(@StringRes resId: Int, formatPattern: String) =
done.

2023-02-20 13:15 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          displayDateValidationError(NotValidated)
Im still struggling to understand this. I just ran the catalog app and wrote text in the Date field, then deleted it, but the error text remained. From your comment, that is not supposed to happen right? Please add a unit test for this case if so

2023-02-20 13:15 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +internal fun invalidDateErrorText(context: Context, @StringRes resId: Int, formatPattern: String) =
Can we move this function to another file? I think `MoreLocalDates` or `QuestionnaireItemDatePickerViewHolderFactory` are better suited as this function only deals with Dates, and not DateTime

2023-02-20 13:15 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +/** Replaces 'dd' with '31', 'MM' with '01' and 'yyyy' with '2023' and returns new string. */
Could you add an example of this? e.g:

```
For example, given a formatPattern of dd/MM/yyyy, returns 31/01/2023
```

2023-02-21 02:44 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          displayDateValidationError(NotValidated)
If a date input is parsed as a partial answer, then 'NotValidated' is required to remove the error text.
I have already added a unit test, but I renamed it to `if the date input is parsed, do not display the error message for a parsed date input` and added one more assertion to make it clearer.

2023-02-21 08:33 UTC, santosh-pingle commented
```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "1",
      "text": "Schedule an appointment 1",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "2",
      "text": "Schedule an appointment 2",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "3",
      "text": "Schedule an appointment 3",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "4",
      "text": "Schedule an appointment 4",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "5",
      "text": "Schedule an appointment 5",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "6",
      "text": "Schedule an appointment 6",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "7",
      "text": "Schedule an appointment 7",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "8",
      "text": "Schedule an appointment 8",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "9",
      "text": "Schedule an appointment 9",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "10",
      "text": "Schedule an appointment 10",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "11",
      "text": "Schedule an appointment 11",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-display-category",
                    "code": "instructions"
                  }
                ]
              }
            }
          ],
          "linkId": "1-most-recent",
          "text": "Select a date 4 weeks from now",
          "type": "display"
        }
      ]
    },
    {
      "linkId": "12",
      "text": "Schedule an appointment 12",
      "type": "dateTime",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-displayCategory",
              "valueCodeableConcept": {
                "coding [...]

2023-02-22 13:22 UTC, aditya-07 reviewed
Some initial comments.

2023-02-22 13:22 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> -          updateAnswerAfterTextChanged(editable.toString())
We don't have to update /invalidate answer? In a case where user sets proper date and time (so that answer gets set) and then changes date text, would answer get removed from questionnaireItemViewItem?

2023-02-22 14:57 UTC, jingtang10 approved these changes

2023-02-22 14:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  /** Clears existing answers and any draft answer. */
add to the documentation of `setAnswer`, `addAnswer` and `removeAnswer` that they will clear the draft answer.

2023-02-22 14:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
> +  fun `if the draft answer input is null, do not enable the time text input layout`() {
```suggestion
  fun `if there is no answer or draft answer, do not enable the time text input layout`() {
```

2023-02-22 14:57 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
> +      assertThat(questionnaireResponse.item.first().answer.first().hasValueDateTimeType()).isTrue()
assert on the value

2023-02-22 17:05 UTC, merged