Refactor edit text widget to fix integer issue
google/android-fhir pull request #1873
Opened 2023-02-15 18:50 UTC by jingtang10

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-02-16 09:48 UTC, omarismail94 reviewed
Do we need to write unit tests as well?

2023-02-16 09:48 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
>    fun bind(questionnaireItemViewItem: QuestionnaireItemViewItem)
minor nit: should we move the `bind` function definition below `displayValidationResult` as the latter now gets called before in `open fun bind`?

2023-02-16 09:48 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +        handleInput(editable!!, questionnaireItemViewItem)
is `editable!!` always guaranteed to be non-null?

2023-02-16 09:48 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +  /** Handles the */
nit: please update doc string

2023-02-16 09:48 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
>    override fun displayValidationResult(validationResult: ValidationResult) {
should we now move `displayValidationResult` above `bind`?

2023-02-16 09:48 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +          )
we are saying here that any input that can be turned into an Integer will be saves in the Questionnaire Response. Is there a scenario where we want to save the integer as a partial answer

2023-02-20 14:29 UTC, omarismail94 requested changes

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * Map from QuestionnaireResponseItems to draft answers, e.g "02/02" for date with missing year
```suggestion
   * Map from [QuestionnaireResponseItemComponent] to draft answers, e.g "02/02" for date with missing year
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * recycled as a result of scrolling. Draft answers cannot saved in [QuestionnaireResponse]
```suggestion
   * recycled as a result of scrolling. Draft answers cannot be saved in [QuestionnaireResponse]
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * because it might be incomplete and unparsable. Without this map, incomplete and unparsable
```suggestion
   * because they might be incomplete and unparsable. Without this map, incomplete and unparsable
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * If a draft answer becomes valid then the entry in this map should be removed, e.g, "02/02/2023"
```suggestion
   * When the draft answer becomes valid, its entry in the map is removed, e.g, "02/02/2023"
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="submit_questionnaire">Submit</string>
nit: can we have these in alphabetical order?

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="submit_questionnaire">Submit</string>
here and in every section in this file

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
> +  fun `clear darft value on an valid answer update`() {
```suggestion
  fun `clear draft value on an valid answer update`() {
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> -  fun displayValidationResult(validationResult: ValidationResult)
Maaan, the code is sooooo much nicer without this function now!

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +      fun displayValidationResult(validationResult: ValidationResult) {
```suggestion
     private fun displayValidationResult(validationResult: ValidationResult) {
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
>        fun displayDateValidationError(validationResult: ValidationResult) {
```suggestion
      private fun displayDateValidationError(validationResult: ValidationResult) {
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
> +        if (input.isNullOrEmpty()) {
Since `editable` is non-nullable, do we need the `isNull`?
```suggestion
        if (input.isEmpty()) {
```

2023-02-20 14:29 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
>  import java.time.format.FormatStyle
Since we're touching this file, could you delete the function `isTextUpdateRequired` ? We don't use it anywhere

2023-02-20 14:32 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> -  fun displayValidationResult(validationResult: ValidationResult)
We also need to remove this function from [QuestionnaireItemBarCodeReaderViewHolderFactory.kt](https://github.com/google/android-fhir/blob/master/contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/QuestionnaireItemBarCodeReaderViewHolderFactory.kt#L121-L123) as the 'displayValidationResult' overrides nothing

2023-02-20 14:34 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> -  fun displayValidationResult(validationResult: ValidationResult)
and in [CustomNumberPickerFactory](https://github.com/google/android-fhir/blob/master/catalog/src/main/java/com/google/android/fhir/catalog/CustomNumberPickerFactory.kt#L46-L48)

2023-02-20 16:37 UTC, jingtang10 reviewed
thanks omar!

2023-02-20 16:47 UTC, omarismail94 approved these changes
Excellent change!! 🚀

2023-02-20 16:55 UTC, jingtang10 commented
thanks omar!

2023-02-20 17:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> -  fun displayValidationResult(validationResult: ValidationResult)
done

2023-02-20 17:20 UTC, merged