Sp/date picker refactoring
google/android-fhir pull request #1880
Opened 2023-02-22 11:08 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Refactor the code for the DatePickerView to make it more readable and maintainable.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-02-23 17:00 UTC, jingtang10 requested changes

2023-02-24 09:12 UTC, aditya-07 reviewed
Small comment, otherwise LGTM.

2023-02-24 09:21 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreLocalDates.kt
> +      LocalDate.parse(text, DateTimeFormatter.ofPattern(datePattern))
Great suggestion - added!

2023-02-24 09:24 UTC, jingtang10 approved these changes
🚀

2023-02-24 09:42 UTC, merged