Support Entry format for date component
google/android-fhir pull request #1897
Opened 2023-03-03 13:34 UTC by PallaviGanorkar

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1850

**Description**
1. supported entry format in questionnaire for date component .
2. If entry format not present in questionnaire then device locale date format is used

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-06 08:58 UTC, PallaviGanorkar commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DatePickerViewHolderFactory.kt
> +internal fun datePattern(questionnaireItem: Questionnaire.QuestionnaireItemComponent): String {
Here entryFormat extension is used to read value from QuestionnaireItemComponent if its value is not available or not as expected then this method return device local date pattern which is not part QuestionnaireItemComponent. So i have preferred to write this functionality as separate method.

2023-03-08 14:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DatePickerViewHolderFactory.kt
> +}
```suggestion
internal fun datePattern(questionnaireItem: QuestionnaireItemComponent) =
  if (isValidDateEntryFormat(questionnaireItem.entryFormat)) {
    questionnaireItem.entryFormat
  } else {
    getLocalizedDateTimePattern()
  }

fun isValidDateEntryFormat(entryFormat: String?): Boolean {

  if (entryFormat == null) return false
  return try {
    val text = LocalDate.now().format(DateTimeFormatter.ofPattern(entryFormat))
    LocalDate.parse(text, DateTimeFormatter.ofPattern(entryFormat))
    true
  } catch (e: Exception) {
    false
  }
}
```

2023-03-08 14:37 UTC, jingtang10 requested changes

2023-03-08 14:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreLocalDates.kt
>  internal fun getDateSeparator(localeDatePattern: String): Char =
as discussed, the right thing to do here is probably make the return type nullable?

2023-08-29 15:36 UTC, jingtang10 commented
I did some tidying up:

- reorganized MoreQuestionnaireItemComponents.kt file and put things in groups
- added unit tests
- merged to HEAD

2023-08-31 06:04 UTC, aditya-07 approved these changes
LGTM

2023-08-31 15:13 UTC, jingtang10 approved these changes

2023-08-31 15:13 UTC, merged

2023-09-08 08:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DatePickerViewHolderFactory.kt
> +
this changes broke the catalog app's behaviour calculated expression.
the widget cannot update the date based on calculated-expression from the quantity widget below it.

if you move this block of code to init() the widget starts working again, but we cannot use dateEntryFormat in that case.