Support for displaying display items based on conditions.
google/android-fhir pull request #1898
Opened 2023-03-04 07:32 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1835 

**Description**
Support for items of display type given some conditions (defined by enableWhen, enableWhenExpression) by passing "enabledDisplayItems" information in QuestionnaireViewItem.

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
<img width="298" alt="Screenshot 2023-03-03 at 9 27 05 PM" src="https://user-images.githubusercontent.com/22965002/222882181-f8f6393a-e364-4f57-84e5-28915443de7d.png">
<img width="298" alt="Screenshot 2023-03-03 at 9 27 00 PM" src="https://user-images.githubusercontent.com/22965002/222882184-e3bd86f4-f91d-4e5a-905d-a16924d09701.png">

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-06 19:10 UTC, jingtang10 requested changes

2023-03-06 19:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +      questionnaireViewItem.enabledDisplayItems?.localizedInstructionsSpanned
use `let`

```
questionnaireViewItem.questionnaireItem.let {
  prefix.update...(it.prefix)
  ...
}
```

2023-03-06 19:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal val enabledDisplayItems: List<Questionnaire.QuestionnaireItemComponent>? = null
can this default to empty list?

2023-03-10 03:39 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal val enabledDisplayItems: List<Questionnaire.QuestionnaireItemComponent>? = null
Done

2023-03-10 03:40 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                  (it.isInstructionsCode || it.isFlyoverCode || it.isHelpCode) &&
Added QuestionnaireItemComponent.isDisplayItem in MoreQuestionnaireItemComponents.kt

2023-03-10 03:40 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +      questionnaireViewItem.enabledDisplayItems?.localizedInstructionsSpanned
Done

2023-03-13 13:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +internal val List<Questionnaire.QuestionnaireItemComponent>.localizedFlyoverSpanned: Spanned?
Done

2023-03-13 13:59 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +  fun bind(questionnaireViewItem: QuestionnaireViewItem) {
Jing suggested to use `let` but personally even I think GroupHeaderView is neater.
Both bind functions and HeaderViews look similar now!

2023-03-13 13:59 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +internal val List<Questionnaire.QuestionnaireItemComponent>.localizedHelpSpanned: Spanned?
Done

2023-03-13 14:09 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +internal val List<Questionnaire.QuestionnaireItemComponent>.localizedInstructionsSpanned: Spanned?
Done.

2023-03-13 16:44 UTC, omarismail94 reviewed
Could you add an espresso test that loads a quesitonnaire similar to the [one]( https://github.com/google/android-fhir/files/10551783/displayCategoryEnableWhenQuestionnaire.txt) posted in the issue, asserting the right text is shown?

2023-03-13 16:44 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/GroupHeaderView.kt
> +      questionnaireViewItem.questionnaireItem
if you are listing the parameter names of the variables of the function, list them all:
```suggestion
      questionnaireItem = questionnaireViewItem.questionnaireItem
```

2023-03-14 04:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/GroupHeaderView.kt
> +      questionnaireViewItem.questionnaireItem
Done. Added `displayItems_shouldGetEnabled_withAnswerChoice` in `QuestionnaireUiEspressoTest`.

2023-03-14 17:39 UTC, omarismail94 approved these changes
Great job! Just resolve these minor comments and then merge

2023-03-14 17:39 UTC, omarismail94 commented on datacapture/sampledata/questionnaire_with_enabled_display_items.json
> +}
nit: add blank line

2023-03-14 17:39 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
> +      val hintText = (view as TextView).text.toString()
```suggestion
      val hintText = view.text.toString()
```

2023-03-14 17:39 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
> +      val hintText = (view as TextView).text.toString()
```suggestion
      val hintText = view.text.toString()
```

2023-03-15 09:05 UTC, omarismail94 commented
@jingtang10 resolving your reviews as @MJ1998 completed them!

2023-03-15 09:05 UTC, merged