Changes in engine to Remove SyncedResourceEntity from database.
google/android-fhir pull request #1902
Opened 2023-03-09 15:35 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1889

**Description**
1. Removed `SyncedResourceEntity` from database.
2. Removed `SyncDownloadContext` from `FhirEngine`.
3. The onus is on Developer Apps now to store the lastUpdated timestamp the way they want to use for syncing.
4. Added a showcase `DemoDataStore` and way for devs to provide the lastUpdated timestamp to `ResourceParamsBasedDownloadWorkManager`

**Alternative(s) considered**
No

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-17 18:12 UTC, omarismail94 reviewed
This is a _great_ change!

2023-03-17 18:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
> +class ResourceParamsBasedDownloadWorkManager(
We only seem to be using this class in the unit tests. Should we move it there?

2023-03-17 18:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
> +  interface Context {
can we name to something else as it might be confused with all the different `Context` interfaces that exist. How about, `TimestampContext` or something like that

2023-03-17 18:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/DemoDataStore.kt
> +class DemoDataStore(private val context: Context) {
If this is only used in the Demo app, should it be moved to there?

2023-03-21 13:35 UTC, jingtang10 requested changes

2023-03-21 13:35 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/data/DownloadWorkManagerImpl.kt
> +class DownloadWorkManagerImpl(private val dataStore: DemoDataStore) : DownloadWorkManager {
maybe this name:

```suggestion
class TimestampBasedDownloadWorkManagerImpl(private val dataStore: DemoDataStore) : DownloadWorkManager {
```

?

I'll let you decide :)

2023-03-24 07:01 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
> +class ResourceParamsBasedDownloadWorkManager(
It is a `DownloadWorkManager` implementation available to the developers to use. It can be used as-is and afaik some devs are using it as well [fhircore](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt#L44).
 It also makes testing some paths easier for us without having to implement a test `DownloadWorkManager` .

2023-03-24 07:12 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/DemoDataStore.kt
> +class DemoDataStore(private val context: Context) {
Yes, my bad. It was supposed to be in Demo app from the start but I unknowingly created it in the engine.

2023-03-24 07:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/DemoDataStore.kt
Moved it to demo, was accidentally created in the engine.

2023-03-24 07:37 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    database.insertSyncedResources(resources)
done

2023-03-24 07:37 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
> +  interface Context {
done

2023-03-24 07:38 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/data/DownloadWorkManagerImpl.kt
> +class DownloadWorkManagerImpl(private val dataStore: DemoDataStore) : DownloadWorkManager {
done, renamed class to `TimestampBasedDownloadWorkManagerImpl`

2023-03-24 15:29 UTC, jingtang10 approved these changes

2023-03-24 15:29 UTC, merged