Do not call updateAnswers first time if initial value is not selected.
google/android-fhir pull request #1904
Opened 2023-03-10 06:32 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1514 

**Description**

Although the initial value was not selected, the 'update answer' function was called the first time the bind API was used. As a result, it validated the required field with an invalid result. Now, a check has been added to verify whether the bind API has been called for the first time and whether an initial answer option has been selected. If there is no initial answer option selected, then the answer will not be updated.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-10 06:36 UTC, santosh-pingle commented
https://user-images.githubusercontent.com/86107848/224241563-1cfc3c2b-c7fe-4022-9ff4-5ae46b3f5e02.mov

2023-03-10 12:05 UTC, jingtang10 requested changes

2023-03-10 12:05 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +              when {
i think a better (and possibly cleaner) fix is to change the call on line 82 to `updateSelectedOptions` so that when you initialize the answer options for the dialog, you don't trigger an update of the view model.

2023-03-14 05:06 UTC, santosh-pingle commented
looking into review comments.

2023-03-15 05:30 UTC, santosh-pingle commented
I will update my analysis regarding the review comment soon, so that it can be reviewed, thanks!

2023-03-16 02:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +              when {
Basically, the implementation of the SDC modal view involves three classes: 1. QuestionnaireItemDialogSelectViewHolderFactory, 2. QuestionnaireItemDialogSelectViewModel, and 3. OptionSelectDialogFragment. The QuestionnaireItemDialogSelectViewHolderFactory and OptionSelectDialogFragment classes reference the QuestionnaireItemDialogSelectViewModel to access a MutableSharedFlow, which triggers the answerOptions list and collects it as well.

Initially, when an API call is made to bind data, the QuestionnaireItemDialogSelectViewHolderFactory class serves as the data source for the answer options list. It triggers the sharedFlow through `viewmodel.updateSelectedOptions` so that the answer options list can be collected by the OptionSelectDialogFragment and displayed in the dialog box when the box is clicked. If an option item is selected or deselected, this triggers an updated answer options list that can be listened to by the QuestionnaireItemDialogSelectViewHolderFactory class to update the answer in the questionnaire response item.

Therefore, the `updateSelectedOptions` call on the `viewmodel` cannot be eliminated, as it is required for this functionality to work correctly.

2023-03-16 02:29 UTC, santosh-pingle commented
@omarismail94 @aditya-07 I replied to the comment. Can you please review once?

2023-03-29 14:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +              when {
i think the flow in `QuestionnaireItemDialogSelectViewModel` is unfortunately used for two different purposes: 1) setting up the UI in the dialog fragment (the dialog fragment listens to this for UI change) 2) update the selection which is then propagated to the qustionnaire view model by `updateAnswers` function.

let's separate these two different tasks - and i think the problem will be solved.

2023-04-05 14:57 UTC, jingtang10 requested changes

2023-04-05 14:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +      private fun onSelectedOptions(selectedOptions: SelectedOptions) {
```suggestion
      private fun onOptionsSelected(selectedOptions: SelectedOptions) {
```

2023-04-05 14:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        }
why does this block need to be here?

2023-04-05 14:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        holder.summary.text = selectedOptions.selectedSummary
this line should be removed from here.

and this line should probably be added in the bind() function.

2023-04-07 08:11 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        }
Yes, you are right, this code snippet is not required here.
Basically, updateAnswers() function should not be called in the bind() function.
It just requires to update header summary text.
thanks!

2023-04-07 08:14 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        holder.summary.text = selectedOptions.selectedSummary
done.

2023-04-19 12:20 UTC, jingtang10 requested changes

2023-04-19 12:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        val selectedOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
```suggestion
        val initialOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
```

2023-04-19 12:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        val selectedOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
i think this can be passed directly to the dialog on line 94.

2023-04-19 12:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +  fun getSelectedOptions() = selectedOptions
i think this change can be reverted if you're passing the initial options directly to the dialog and skip the view model.

2023-04-20 06:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +        val selectedOptions = questionnaireViewItem.extractInitialOptions(holder.header.context)
done.

2023-04-20 06:30 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +  fun getSelectedOptions() = selectedOptions
done.

2023-04-25 14:21 UTC, jingtang10 approved these changes

2023-04-25 17:12 UTC, merged