Added rules for required for engine and datacapture libraries.
google/android-fhir pull request #1916
Opened 2023-03-17 08:01 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1901 

**Description**
Added the proguard rules required for engine and datacapture libs in Demo and catalog app respectively.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-17 17:53 UTC, omarismail94 approved these changes
Great change @aditya-07 ! Just two nits

2023-03-17 17:53 UTC, omarismail94 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
nit: add new line

2023-03-17 17:53 UTC, omarismail94 commented on engine/proguard-rules.pro
> +## retrofit ends
nit: add new line

2023-03-17 17:54 UTC, omarismail94 commented
Im also assuming we don't need this in any of our other libraries as they depend on engine and datacapture

2023-03-21 13:26 UTC, jingtang10 requested changes

2023-03-21 13:26 UTC, jingtang10 commented on catalog/proguard-rules.pro
> +#-renamesourcefileattribute SourceFile
these can be removed. i don't mind if you keep the block on top - up to you.

and below

2023-03-21 13:26 UTC, jingtang10 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
i don't understand why this is needed. as a argument to pass to the fragment, i feel this should still work even if it's minified/shrunk?

2023-03-21 13:26 UTC, jingtang10 commented on datacapture/proguard-rules.pro
> +-keep class org.hl7.fhir.r4.hapi.ctx.*  { *; }
can you do `org.hl7.fhir.*` ?

2023-03-21 13:26 UTC, jingtang10 commented on datacapture/proguard-rules.pro
> +-keep class org.hl7.fhir.exceptions.*  { *; }
why are these needed?

2023-03-21 13:26 UTC, jingtang10 commented on datacapture/proguard-rules.pro
> +## hapi libs starts
```suggestion
# HAPI Strucutres need to be kept beause
# 1.  Reflection is used in resource extraction as the FHIR Path expression is then translated to field names to locate data elements in FHIR resources
# 2. In HAPI Strucures, ClassLoader is used...
```

2024-06-12 12:27 UTC, aditya-07 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
Done

2024-06-12 12:44 UTC, aditya-07 commented on engine/proguard-rules.pro
> +## retrofit ends
done

2024-06-12 12:45 UTC, aditya-07 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
Removed as not required in catalog app anymore.

2024-06-12 12:46 UTC, aditya-07 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
Even if something similar is required later, it needs to go in Catalog's proguard-rules and not here.

2024-06-12 12:46 UTC, aditya-07 commented on datacapture/proguard-rules.pro
> +-keep class org.hl7.fhir.exceptions.*  { *; }
removed. Keeping the top package now

2024-06-12 12:46 UTC, aditya-07 commented on datacapture/proguard-rules.pro
> +## hapi libs starts
done

2024-06-13 15:18 UTC, jingtang10 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
you can't delete this?

2024-06-13 15:21 UTC, jingtang10 commented on datacapture/proguard-rules.pro
this is excellent - thanks so much for updating the doc!

2024-06-13 15:59 UTC, jingtang10 commented on catalog/proguard-rules.pro
> +-keep class com.google.android.fhir.catalog.WorkflowType
i actually just built a release apk of the catalog app without this rule and it seems to be working...

so can you just remove this file altogether

2024-06-13 16:10 UTC, jingtang10 requested changes

2024-06-13 16:10 UTC, jingtang10 commented on catalog/build.gradle.kts
> +      isMinifyEnabled = true
and demo app?

2024-06-13 16:17 UTC, aditya-07 commented on catalog/build.gradle.kts
> +      isMinifyEnabled = true
its there

2024-06-13 16:23 UTC, jingtang10 commented
tested a minified release build of the demo app and got this:

```
2024-06-13 17:22:21.350 27518-27518 AndroidRuntime          com.google.android.fhir.demo         E  FATAL EXCEPTION: main
                                                                                                    Process: com.google.android.fhir.demo, PID: 27518
                                                                                                    ca.uhn.fhir.context.ConfigurationException: HAPI-1753: Unable to initialize StAX - XML processing is disabled
                                                                                                    	at ca.uhn.fhir.util.XmlUtil.newInputFactory(SourceFile:59)
                                                                                                    	at ca.uhn.fhir.util.XmlUtil.getOrCreateInputFactory(SourceFile:1)
                                                                                                    	at ca.uhn.fhir.util.XmlUtil.createXmlReader(SourceFile:1)
                                                                                                    	at ca.uhn.fhir.parser.XmlParser.createStreamReader(SourceFile:1)
                                                                                                    	at ca.uhn.fhir.parser.XmlParser.doParseResource(Unknown Source:0)
                                                                                                    	at ca.uhn.fhir.parser.BaseParser.parseResource(SourceFile:4)
                                                                                                    	at ca.uhn.fhir.parser.BaseParser.parseResource(SourceFile:2)
                                                                                                    	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.parseBundle(Unknown Source:8)
                                                                                                    	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.loadStructureDefinitions(SourceFile:80)
                                                                                                    	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.provideStructureDefinitionMap(Unknown Source:30)
                                                                                                    	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.fetchStructureDefinition(SourceFile:62)
                                                                                                    	at ca.uhn.fhir.context.support.DefaultProfileValidationSupport.fetchStructureDefinition(Unknown Source:2)
                                                                                                    	at ca.uhn.fhir.context.support.IValidationSupport.fetchResource(Unknown Source:136)
                                                                                                    	at org.hl7.fhir.common.hapi.validation.support.ValidationSupportChain.fetchResource(Unknown Source:18)
                                                                                                    	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.lambda$fetchResource$0(Unknown Source:2)
                                                                                                    	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.b(SourceFile:1)
                                                                                                    	at org.hl7.fhir.common.hapi.validation.support.f.apply(SourceFile:1)
                                                                                                    	at ca.uhn.fhir.sl.cache.guava.CacheDelegator.lambda$get$0(Unknown Source:0)
                                                                                                    	at ca.uhn.fhir.sl.cache.guava.CacheDelegator.a(SourceFile:1)
                                                                                                    	at ca.uhn.fhir.sl.cache.guava.a.call(SourceFile:1)
                                                                                                    	at a8.j0.load(SourceFile:1)
                                                                                                    	at a8.h0.h(SourceFile:28)
                                                                                                    	at a8.m0.l(SourceFile:185)
                                                                                                    	at a8.b1.e(SourceFile:74)
                                                                                                    	at h4.t.b(SourceFile:1)
                                                                                                    	at ca.uhn.fhir.sl.cache.guava.CacheDelegator.get(SourceFile:10)
                                                                                                    	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.fetchResource(Unknown Source:15)
                                                                                                    	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.fetchResourceWithException(SourceFile:1)
                                                                                                    	at i6.a.fetchResourceWithException(SourceFile:1)
                                                                                                    	at org.hl7.fhir.r4.context.BaseWorkerContext.fetchResource(Unknown Source:0)
                                                                                                    	at org.hl7.fhir.r4.context.SimpleWorkerContext.fetchResource(SourceFile:1)
                                                                                                    	at org.hl7.fhir.r4.context.BaseWorkerContext.fetchTypeDefinition(Unknown Source:8)
                                                                                                    	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(SourceFile:2)
                                                                                                    	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(SourceFile:1)
                                                                                                    	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(SourceFile:4)
                                                                                                    	at i6.d.a(SourceFile:7)
                                                                                                    	at b6.d0.g(SourceFile:220)
                                                                                                    	at a6.i.r(SourceFile:134)
                                                                                                    	at a6.i.h(SourceFile:16)
                                                                                                    	at m1.c0.r(SourceFile:68)
                                                                                                    	at m1.c0.m(SourceFile:13)
                                                                                                    	at s3.u0.A0(SourceFile:5)
                                                                                                    	at g8.b.u1(SourceFile:75)
                                                                                                    	at m1.b0.r(SourceFile:88)
                                                                                                    	at l9.a.f(SourceFile:1)
                                                                                                    	at aa.b0.run(SourceFile:1)
                                                                                         [...]

2024-06-13 18:42 UTC, jingtang10 approved these changes

2024-06-13 19:14 UTC, aditya-07 commented
> tested a minified release build of the demo app and got this when i create a patient:
> 
> ```
> 2024-06-13 17:22:21.350 27518-27518 AndroidRuntime          com.google.android.fhir.demo         E  FATAL EXCEPTION: main
>                                                                                                     Process: com.google.android.fhir.demo, PID: 27518
>                                                                                                     ca.uhn.fhir.context.ConfigurationException: HAPI-1753: Unable to initialize StAX - XML processing is disabled
>                                                                                                     	at ca.uhn.fhir.util.XmlUtil.newInputFactory(SourceFile:59)
>                                                                                                     	at ca.uhn.fhir.util.XmlUtil.getOrCreateInputFactory(SourceFile:1)
>                                                                                                     	at ca.uhn.fhir.util.XmlUtil.createXmlReader(SourceFile:1)
>                                                                                                     	at ca.uhn.fhir.parser.XmlParser.createStreamReader(SourceFile:1)
>                                                                                                     	at ca.uhn.fhir.parser.XmlParser.doParseResource(Unknown Source:0)
>                                                                                                     	at ca.uhn.fhir.parser.BaseParser.parseResource(SourceFile:4)
>                                                                                                     	at ca.uhn.fhir.parser.BaseParser.parseResource(SourceFile:2)
>                                                                                                     	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.parseBundle(Unknown Source:8)
>                                                                                                     	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.loadStructureDefinitions(SourceFile:80)
>                                                                                                     	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.provideStructureDefinitionMap(Unknown Source:30)
>                                                                                                     	at ca.uhn.fhir.context.support.DefaultProfileValidationSupportBundleStrategy.fetchStructureDefinition(SourceFile:62)
>                                                                                                     	at ca.uhn.fhir.context.support.DefaultProfileValidationSupport.fetchStructureDefinition(Unknown Source:2)
>                                                                                                     	at ca.uhn.fhir.context.support.IValidationSupport.fetchResource(Unknown Source:136)
>                                                                                                     	at org.hl7.fhir.common.hapi.validation.support.ValidationSupportChain.fetchResource(Unknown Source:18)
>                                                                                                     	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.lambda$fetchResource$0(Unknown Source:2)
>                                                                                                     	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.b(SourceFile:1)
>                                                                                                     	at org.hl7.fhir.common.hapi.validation.support.f.apply(SourceFile:1)
>                                                                                                     	at ca.uhn.fhir.sl.cache.guava.CacheDelegator.lambda$get$0(Unknown Source:0)
>                                                                                                     	at ca.uhn.fhir.sl.cache.guava.CacheDelegator.a(SourceFile:1)
>                                                                                                     	at ca.uhn.fhir.sl.cache.guava.a.call(SourceFile:1)
>                                                                                                     	at a8.j0.load(SourceFile:1)
>                                                                                                     	at a8.h0.h(SourceFile:28)
>                                                                                                     	at a8.m0.l(SourceFile:185)
>                                                                                                     	at a8.b1.e(SourceFile:74)
>                                                                                                     	at h4.t.b(SourceFile:1)
>                                                                                                     	at ca.uhn.fhir.sl.cache.guava.CacheDelegator.get(SourceFile:10)
>                                                                                                     	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.fetchResource(Unknown Source:15)
>                                                                                                     	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.fetchResourceWithException(SourceFile:1)
>                                                                                                     	at i6.a.fetchResourceWithException(SourceFile:1)
>                                                                                                     	at org.hl7.fhir.r4.context.BaseWorkerContext.fetchResource(Unknown Source:0)
>                                                                                                     	at org.hl7.fhir.r4.context.SimpleWorkerContext.fetchResource(SourceFile:1)
>                                                                                                     	at org.hl7.fhir.r4.context.BaseWorkerContext.fetchTypeDefinition(Unknown Source:8)
>                                                                                                     	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(SourceFile:2)
>                                                                                                     	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(SourceFile:1)
>                                                                                                     	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(SourceFile:4)
>                                                                                                     	at i6.d.a(SourceFile:7)
>                                                                                                     	at b6.d0.g(SourceFile:220)
>                                                                                                     	at a6.i.r(SourceFile:134)
>                                                                                                     	at a6.i.h(SourceFile:16)
>                                                                                                     	at m1.c0.r(SourceFile:68)
>                                                                                                     	at m1.c0.m(SourceFile:13)
>                                                                                                     	at s3.u0.A0(SourceFile:5)
>                                                                                                     	at g8.b.u1(SourceFile:75)
>                                                                                                     	at m1.b0.r(SourceFile:88)
>                                                                                                     	at l9.a.f(SourceFile:1)
>                                                                                          [...]

2024-06-13 20:05 UTC, merged

2024-06-13 20:32 UTC, jingtang10 commented
Thanks Aditya!