Add _tag and _profile search parameters for x-fhir-query
google/android-fhir pull request #1938
Opened 2023-03-27 06:14 UTC by gosso22

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[1935]

**Description**
In the toSearchParamDefinitionValueMap method, I added _tag and _profile in the paramDefinition.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-27 06:52 UTC, maimoonak requested changes

2023-03-27 06:52 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +          "_tag" ->
We can add _tag and _ profile as Constants?

2023-03-27 06:52 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
> +  @Test
Add a test in com.google.android.fhir.impl.FhirEngineImplTest#search() by x-fhir-query should return female patients for gender param as well for _tag and _profile for integration testing.

2023-03-28 11:59 UTC, maimoonak requested changes

2023-03-28 11:59 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun `search() by x-fhir-query should return patients for gender param as well for _tag`() =
Keep it simple. Just run it for tag. Remove gender based search and properties

2023-03-28 11:59 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun `search() by x-fhir-query should return patients for gender param as well for _profile`() =
same as above comment. Keep it simple and just test profile. Remove gender

2023-03-28 12:45 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +            SearchParamDefinition("_tag", Enumerations.SearchParamType.TOKEN, "$type.meta.tag")
use XFHIR_QUERY_TAG_PARAM constant here... do the same for profile

2023-03-28 12:47 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +        buildPatient("4", "C", Enumerations.AdministrativeGender.MALE).apply {
change it FEMALE so that only difference is profile

2023-03-28 13:42 UTC, maimoonak approved these changes
Just one issue with spelling.. rest is fine.

2023-03-28 13:42 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +          XFHIR_QUERT_PROFILE_PARAM ->
Rename spelling to quer**Y**.. its **T** here...

2023-03-28 14:12 UTC, gosso22 commented
@jingtang10 - can you approve and merge these changes?

2023-04-03 19:00 UTC, MJ1998 requested changes
So `_tag` and `_profile` fall under standard search parameters for all resources.
link: https://hl7.org/fhir/search.html#all
For these standard search params, we already have `SearchParamDefinition` defined in `getSearchParamList` under "Resource" option. So instead of rewriting this code we can make advantage of that.
source code: com.google.android.fhir.index.getSearchParamList

2023-04-03 19:00 UTC, MJ1998 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +                mutableListOf(Coding("http://d-tree.org/", "salima-catchment", "Salima Patients"))
I think we should have generalised names like Tag1, Patient1

2023-04-03 19:00 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
> +  private const val XFHIR_QUERY_PROFILE_PARAM = "_profile"
Can we use com.google.android.fhir.index.getSearchParamList instead ?

2023-04-04 12:51 UTC, gosso22 commented
> So `_tag` and `_profile` fall under standard search parameters for all resources. link: https://hl7.org/fhir/search.html#all For these standard search params, we already have `SearchParamDefinition` defined in `getSearchParamList` under "Resource" option. So instead of rewriting this code we can make advantage of that. source code: com.google.android.fhir.index.getSearchParamList

@MJ1998 - Thank you for looking at this and for the feedback. XFhirQueryTranslator is already using the method com.google.android.fhir.index.getSearchParamList [here](https://github.com/google/android-fhir/blob/96af7f12cc8f95a2922dd184ef969745a544641a/engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt#L177), I expected it to pick _tag and _profile however this is not happening and it throws an error that _tag is not found in ResourceName. I am not sure why that is happening, that's why I decided to handle it explicitly.

2023-04-04 14:41 UTC, MJ1998 commented
> > So `_tag` and `_profile` fall under standard search parameters for all resources. link: https://hl7.org/fhir/search.html#all For these standard search params, we already have `SearchParamDefinition` defined in `getSearchParamList` under "Resource" option. So instead of rewriting this code we can make advantage of that. source code: com.google.android.fhir.index.getSearchParamList
> 
> @MJ1998 - Thank you for looking at this and for the feedback. XFhirQueryTranslator is already using the method com.google.android.fhir.index.getSearchParamList [here](https://github.com/google/android-fhir/blob/96af7f12cc8f95a2922dd184ef969745a544641a/engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt#L177), I expected it to pick _tag and _profile however this is not happening and it throws an error that _tag is not found in ResourceName. I am not sure why that is happening, that's why I decided to handle it explicitly.

@gosso22 Either we need to modify static method `resourceSearchParameters` so that it searches for standard parameters under "Resource" first and then for the specific resourceType (eg, "Patient") OR we need to modify `SearchParameterRepositoryGenerator.kt` to generate function `getSearchParamList` that also searches for standard parameters under "Resource". I prefer the latter solution.

2023-04-04 15:10 UTC, gosso22 commented
> > > So `_tag` and `_profile` fall under standard search parameters for all resources. link: https://hl7.org/fhir/search.html#all For these standard search params, we already have `SearchParamDefinition` defined in `getSearchParamList` under "Resource" option. So instead of rewriting this code we can make advantage of that. source code: com.google.android.fhir.index.getSearchParamList
> > 
> > 
> > @MJ1998 - Thank you for looking at this and for the feedback. XFhirQueryTranslator is already using the method com.google.android.fhir.index.getSearchParamList [here](https://github.com/google/android-fhir/blob/96af7f12cc8f95a2922dd184ef969745a544641a/engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt#L177), I expected it to pick _tag and _profile however this is not happening and it throws an error that _tag is not found in ResourceName. I am not sure why that is happening, that's why I decided to handle it explicitly.
> 
> @gosso22 Either we need to modify static method `resourceSearchParameters` so that it searches for standard parameters under "Resource" first and then for the specific resourceType (eg, "Patient") OR we need to modify `SearchParameterRepositoryGenerator.kt` to generate function `getSearchParamList` that also searches for standard parameters under "Resource". I prefer the latter solution.

@MJ1998 - I am also in favor of the latter solution.

2023-04-14 11:51 UTC, gosso22 commented
@MJ1998 - I spent sometime to look on how to do the suggested:
_we need to modify SearchParameterRepositoryGenerator.kt to generate function getSearchParamList that also searches for standard parameters under "Resource"._
My thinking is to include the search parameters included in Resource for example _tag, _profile to also be available for other resources in such a way that when I do getSearchParamList for Location, _tag and _profile are also included with their path defined as Location.meta.tag and Location.meta.profile respectively. What do you think? Would this work?

2023-04-20 09:45 UTC, MJ1998 commented
@gosso22 
Apologies for late response.
Yes your thinking is correct. We are on the same page. But we would like to modify the generation of `getSearchParamList` in a way to search for only a subset of [standard search parameters](https://hl7.org/fhir/search.html#all) for every resource.
`SearchParameterRepository_Generated:getResource` is already a subset of the list given in the above link. 
@jingtang10 Do you think subset defined in `SearchParameterRepository_Generated:getResource` is enough ? More technically, do you think modifying generator to add statement `addAll(getResource())` is the right thing to do ?

2023-04-27 10:30 UTC, MJ1998 submitted a review, later dismissed

2023-04-27 10:30 UTC, MJ1998 commented on engine/src/test/java/com/google/android/fhir/index/SearchParameterRepositoryGeneratedTest.kt
> +    val searchParams = mutableListOf<SearchParamDefinition>()
Thanks for modifying this test! 
The current set of supported search parameters for all resources are given in codegen/src/main/res/search-parameters.json. We would somehow like to use that instead of hardcoding the subset here.

2023-04-27 10:30 UTC, MJ1998 commented on buildSrc/src/main/kotlin/codegen/SearchParameterRepositoryGenerator.kt
> +            )
This is nice and definitely one way of solving! 
But what if instead of adding duplicate codes to every function we just add a new statement like ```"addAll(getResource())"```  ? (Maybe on line 120 of the original file)
We would also **not** need to store baseResourceSearchParams then. Unless storing it makes sense for using it elsewhere.

2023-04-27 11:01 UTC, gosso22 commented on buildSrc/src/main/kotlin/codegen/SearchParameterRepositoryGenerator.kt
> +            )
@MJ1998 - I thought about adding `addAll(getResource())`, but I think the challenge there is the path. For example if we consider tag for  Location resource, with the above statement, the path for tag will be Resource.meta.tag instead of Location.meta.tag. I am no so sure if this works.

2023-04-27 11:14 UTC, gosso22 commented on engine/src/test/java/com/google/android/fhir/index/SearchParameterRepositoryGeneratedTest.kt
> +    val searchParams = mutableListOf<SearchParamDefinition>()
For this one, what I found is the resources defined in model classes  inherits from Resource which does not have these standard search parameters annotated `SearchParamDefinition`. I am not sure how to proceed with this one.

2023-04-28 03:38 UTC, MJ1998 commented on buildSrc/src/main/kotlin/codegen/SearchParameterRepositoryGenerator.kt
> +            )
That's correct. Resolving.

2023-04-28 03:41 UTC, MJ1998 commented on engine/src/test/java/com/google/android/fhir/index/SearchParameterRepositoryGeneratedTest.kt
> +    val searchParams = mutableListOf<SearchParamDefinition>()
@jingtang10

2023-05-05 10:25 UTC, jingtang10 requested changes
i think you might need to change/remove this function `addIndexesFromResourceClass` in `ResourceIndexer.kt` because now the base search parameters are already provided for each resource type when the indexer calls `getSearchParamList(...)` function.

hopefullly you won't need to change the indexer's tests much.

with this change, instead of adding `_tag` and `_profile`, or even `_lastUpdated` etc in the indexer manually, we're  including these base search paramters for each resource type in the search parameter repository. this is a *very good* change - makes our code more unfied.

thanks @gosso22!

2023-05-05 10:25 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/SearchParameterRepositoryGeneratedTest.kt
> +    val searchParams = mutableListOf<SearchParamDefinition>()
i don't think modifying that file would work for this test case. the "expected" search parameters here are generated from using reflection on HAPI structures java classes... so we'd have to hardcode somehow these search parameters that don't exist in those java classes.

i do think @MJ1998 is right in the way that these can be extracted to a separate function just to make it a bit more explicit, something like `fun getBaseSearchParameters(...)`... and add some comments to say that we do this because these don't exist in the HAPI java classes...

2023-05-05 10:25 UTC, jingtang10 commented on buildSrc/src/main/kotlin/codegen/SearchParameterRepositoryGenerator.kt
optional:

explore the alternative approach of creating a new function that returns the base search parametesr for all resources, and calling that function in `getSearchParamList()` so that you're not adding the same code to each function for each resoure type.

2023-05-26 15:04 UTC, gosso22 commented
> i think you might need to change/remove this function `addIndexesFromResourceClass` in `ResourceIndexer.kt` because now the base search parameters are already provided for each resource type when the indexer calls `getSearchParamList(...)` function.
> 
> hopefullly you won't need to change the indexer's tests much.
> 
> with this change, instead of adding `_tag` and `_profile`, or even `_lastUpdated` etc in the indexer manually, we're including these base search paramters for each resource type in the search parameter repository. this is a **very good** change - makes our code more unfied.
> 
> thanks @gosso22!

@jingtang10 - I removed the above function `addIndexesFromResourceClass` in the `ResourceIndexer.kt`, and change a few things. First I changed the type for _profile in `search-parameters.json` from uri to reference as defined in the fhir specification and also as it was implemented in `addIndexesFromResourceClass`. Also I had to handle the case for _id. But other than that all tests passed without the `addIndexesFromResourceClass`.

2023-06-15 09:16 UTC, jingtang10 requested changes

2023-06-19 05:51 UTC, gosso22 commented
@jingtang10, @aditya-07 - I have updated this, I think it is ready.

2023-07-03 09:04 UTC, aditya-07 requested changes

2023-07-04 11:28 UTC, aditya-07 commented on buildSrc/src/main/resources/search-parameters.json
> +      "type" : "reference",
I am not sure about the rationale behind **_profile** being added as a reference in [here](https://github.com/google/android-fhir/blob/f05cd76e84b91643313093bc394128f1303efcdc/engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L144). But, I think we should keep the search-parameters.json as-is since its dowloaded directly from the [registry](https://www.hl7.org/fhir/searchparameter-registry.html).

2023-07-05 13:24 UTC, jingtang10 reviewed
Thanks for this change! I love this PR!

Once @aditya-07 's comment is addressed in the json file i'm happy to approve this!

2023-07-10 09:10 UTC, gosso22 commented on buildSrc/src/main/resources/search-parameters.json
> +      "type" : "reference",
@jingtang10 and @aditya-07 - I have resolved this and modified the tests that were using reference.

2023-07-10 09:10 UTC, gosso22 commented on buildSrc/src/main/kotlin/codegen/SearchParameterRepositoryGenerator.kt
> + * `generateSearchParamsTask`. If you are using Android Studio, you can usually find this task in
Thanks @jingtang10

2023-07-10 09:59 UTC, jingtang10 approved these changes

2023-07-10 10:01 UTC, aditya-07 approved these changes

2023-07-11 13:52 UTC, merged