Nested questionnaireResponseComponent with enableWhen in repeated group is missing from questionnaire response.
google/android-fhir pull request #1940
Opened 2023-03-28 06:17 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1895

**Description**
The questionnaire response contains answers to all selected and enabled questionnaire items. However, when copying the questionnaire response, the use of 'getEnabledResponseItems' fails to copy the selected answers of enabled items.
when the type is a repeated group item, the questionnaireResponseItemParentMap is always empty in the findEnableWhenQuestionnaireResponseItem() API. This is because the buildParentList logic in EnablementEvaluator fails to correctly build the parent list for repeated group items.

**Alternative(s) considered**

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-03-28 06:34 UTC, santosh-pingle commented
I am adding end to end android test for this fix, but getting below error when `Add item ` get clicked second time to add more repeated group.

```
androidx.test.espresso.AmbiguousViewMatcherException: 'view.getId() is <2131230792/com.google.android.fhir.datacapture.test:id/add_item>' matches multiple views in the hierarchy.
Problem views are marked with '****MATCHES****' below.
```
Can we please review the PR? If the Android test gets fixed, I will push the changes; otherwise, I will have a separate PR for this Android test.

2023-03-29 13:40 UTC, jingtang10 requested changes
This is a great catch! Thanks for debugging!

2023-03-29 13:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> -        buildParentList(child)
```
  for (child in item.item) {
    ...
  }
  for (answer in item.ansewr) {
    for (nestedItem in answer.item) {
      map[nestedItem] = item
      ... // recursion
    }
  }
```

2023-03-29 13:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        getEnabledResponseItems(
```suggestion
        // Use the view model's questionnaire and questionnaire response for calculating enabled items because the calculation relies on references to the questionnaire response items.
        getEnabledResponseItems(
```

2023-03-29 13:40 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
I feel the changes in this test can be in the QuestionnaireViewModelTest.kt file.

The reason that I say this, is that, espresso tests and integration tests are more expensive than unit tests. Their purpose is to test the e2e user journey and especially UI. In this case, the bug is a specific case for repeated group and is the result of `getQuestionnaireResponse` function. So if we can write a unit test case to catch this, it is preferable.

2023-04-03 15:21 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
done. 
Added unit test.

2023-04-03 15:21 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        getEnabledResponseItems(
done.
Updated inline comment.

2023-04-03 15:21 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> -        buildParentList(child)
done.

2023-04-05 15:11 UTC, jingtang10 approved these changes
@santosh-pingle thanks again for this change!

2023-04-05 15:11 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `repeatedGroupItem response contains enabled items`() {
1) this function needs to be moved up. under the section called "Questionnaire Response"

```suggestion
  fun `getQuestionnaireResponse() should return enabled repeated groups`() {
```

2023-04-05 15:11 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
> +  @Test
i think we don't need this test case for two reasons:

1) i think the bug is sufficiently covered by your test case in QVM test.
2) @kevinmost 's work to complete repeate group UI might add new items in the recycler view, and your test case relies on the indices of UI widgets. i think this test will break with kevin's change.

2023-04-05 15:11 UTC, jingtang10 commented on datacapture/sampledata/repeated_group.json
can this be removed? see comment later.

2023-04-07 08:15 UTC, santosh-pingle commented on datacapture/sampledata/repeated_group.json
done.

2023-04-07 08:15 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/QuestionnaireUiEspressoTest.kt
> +  @Test
done.

2023-04-07 08:15 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun `repeatedGroupItem response contains enabled items`() {
done.

2023-04-07 08:15 UTC, merged