EnableWhenExpression context literal fhirpath supplement implementation
google/android-fhir pull request #1957
Opened 2023-04-06 18:10 UTC by maimoonak

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-04-17 09:35 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FhirPathUtil.kt
> + */
nit: Could you please review the Kotlin API documentation one more time? I'm sorry, but I'm having trouble understanding it.

2023-04-24 09:24 UTC, jingtang10 requested changes
Thanks @maimoonak for this PR.

I'm having some trouble understanding what this PR is doing beyond wrapping fhir path engine functions in wrappers.

To support fhirpath supplements, we need to use `FHIRPathEngineHostServices` so that it can resolve `%resource`, `%context` etc. It is the service `FHIRPathEngine` uses when it sees a variable with `%` that it cannot resolve.

2023-04-24 13:51 UTC, jingtang10 commented
@omarismail94 fyi - we discussed this before.

2023-04-26 12:14 UTC, maimoonak commented
> Thanks @maimoonak for this PR.
> 
> I'm having some trouble understanding what this PR is doing beyond wrapping fhir path engine functions in wrappers.
> 
There is a bug where we are not passing focusResource (which is recognized as %resource in expression) and baseResource (which is recognized as %context or $this in expression) separately into evaluate function when evaluating enableWhen-expression. This leads to a missing feature i.e. use of %context to get current questionnaireResponseItem in expression as defined here https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements and a bug where user can use %resource, %context, $this all constants for questionnaireResponse which is wrong.

> To support fhirpath supplements, we need to use `FHIRPathEngineHostServices` so that it can resolve `%resource`, `%context` etc. It is the service `FHIRPathEngine` uses when it sees a variable with `%` that it cannot resolve.

As per implementation here org.hl7.fhir.r4.utils.FHIRPathEngine#resolveConstant(ExecutionContext, String, boolean, ExpressionNode), the constants which are part of default fhir spec (https://hl7.org/fhir/fhirpath.html#variables and https://hl7.org/fhir/fhirpath.html#vars) i.e. %constant_name are resolved automatically by engine. We can not provide implementation for those. If any variable is not reserved one and is provided by specific IG, then we need to provide it via HostServices. Some of the examples of such cases are StructureMap extraction and SDC variable resolution. 

See attached image to see the code flow.

![Screenshot from 2023-04-26 16-59-36](https://user-images.githubusercontent.com/4829880/234568475-b7a76f58-38f4-4c6e-91d5-795da5379897.png)

2023-04-27 11:38 UTC, jingtang10 requested changes

2023-04-27 11:38 UTC, jingtang10 commented on catalog/src/main/res/values/strings.xml
> +    >Enable When Expression</string>
```suggestion
    >Context Variables</string>
```

can you also rename the other elements...

2023-04-27 11:38 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FhirPathUtil.kt
> +
we'll need to make changes to `evaluateToDisplay` as well i think

2023-04-27 11:38 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FhirPathUtil.kt
> +
also change `ExpressionEvaluator`

2023-04-27 11:38 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FhirPathUtil.kt
> +
we need to review the usage of fhir path engine in the whole of sdc, and make sure we're passing the right context in the rigth places, and hopefully creating a single place where we're passing these contexts.

but - i understand you might need this feature soon - and that can be done as a follow-up

2023-04-27 13:52 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FhirPathUtil.kt
> +
New issue created here https://github.com/google/android-fhir/issues/1993 to record changes needed.

2023-05-04 21:41 UTC, jingtang10 approved these changes

2023-05-04 22:28 UTC, merged