Cqf expression implementation for dynamic question title
google/android-fhir pull request #1959
Opened 2023-04-07 10:10 UTC by maimoonak

Fixes #1945 , depends on #1957 

**Description**
Display questionnaire.item.text from FHIRPath expression. In a nutshell, it's like calculated expression which's for answer, but this time for questionnaire.item.text. [Advance rendering questionnaire](https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-render.html )allows the cf-expression on title to display it based on other question`s answers [example](https://build.fhir.org/ig/HL7/sdc/examples.html#using-text-and-cqf-expression) 

**Type**
Choose one: Feature

**Screenshots (if applicable)**

![dynamic-title](https://user-images.githubusercontent.com/4829880/230590770-6b00ab64-2b49-4cd2-b9b7-5c771649df8b.gif)

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-04-17 09:30 UTC, FikriMilano commented
@maimoonak awesome work here!
I will spare some time tomorrow to review this.

2023-04-18 07:53 UTC, FikriMilano requested changes
nicely done! 🚀

can you write a test that makes sure when an answer from a QuestionnaireItem was changed, the next QuestionnaireItem.title is updated?

2023-04-18 08:43 UTC, FikriMilano reviewed
@maimoonak can you also check if the dynamic title works with variable expression?
Try to save the answer to variable expression, then call that variable in cqf expression.

I tried this, it doesn't seem to work, though it works with calculated expression

2023-04-19 07:14 UTC, maimoonak commented
Good catch! Thanks for this. Feedback resolved and PR is ready for review

2023-04-24 09:50 UTC, jingtang10 commented
@shelaghm please take a look at the video @maimoonak attached.

2023-04-24 12:20 UTC, jingtang10 requested changes
thanks for this pr @maimoonak! great work!

some high-level comments first to address. thanks!

2023-04-24 12:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  private val resolveCqfExpression: (Element) -> List<Base> = { emptyList() },
i don't think this should be a callback in the questionnaire view item. i know that the other callbacks (`resolveAnswerValueSet`, `resolveAnswerExpression`) may be pointing to this pattern... but i think cql expression should be resolved in questionnaire view model already, and this should probably be totally opaque to the UI.

so either create a new extension property in questionnaire item, or create another data field in questionnaire view item. i would probably prefer the former rather than the latter.

2023-04-24 12:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    element: Element,
cqf expression is on text only right? i think it doesn't need to be an element. in fact this can probably be an extension function of questionnaire item...

see my comment below.

2023-04-25 00:03 UTC, shelaghm commented on catalog/src/main/res/drawable/ic_dynamic_title_behavior.xml
Is it this? I think we created this for "range picker" but it also works here! <img width="97" alt="Screenshot 2023-04-24 at 17 01 41" src="https://user-images.githubusercontent.com/86378921/234140479-a953bafb-31ee-4b74-9bae-ed408035414b.png">

2023-04-25 00:07 UTC, shelaghm commented
@maimoonak Great work! Thanks for adding the video. Looks good to me. +1 to Jing's suggestion to use generic copy.

2023-04-26 11:40 UTC, FikriMilano approved these changes
@maimoonak approved 👍
nice work :D

2023-04-26 13:50 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  private val resolveCqfExpression: (Element) -> List<Base> = { emptyList() },
The cqf-expression is an extension on textElement (nested on another element level down the hierarchy). This approach is changed to add text on response-item if it is supposed to be dynamic. We have to output it into response as well at the end of submission.

2023-04-26 13:58 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    element: Element,
cqf-expression https://build.fhir.org/ig/HL7/sdc/behavior.html#cqf-expression is very dynamic and flexible and can be present on various elements including questionnaireItem or its nested elements which can include minOccurs, maxOccurs, required, repeats, readOnly , answerValueSet, text. This means that this expression would run on any "Element" and not only on "QuestionnaireItemComponent"

2023-04-26 14:22 UTC, maimoonak commented
@jingtang10 Kindly check the new approach where we are using questionnaire-reponse text as primary source for dynamic title.
<img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/234605620-bc271cd5-36b6-4451-8e8f-93662eac38f5.gif"/>

2023-04-27 05:25 UTC, santosh-pingle commented
I am reviewing this, thanks!

2023-04-27 09:56 UTC, FikriMilano approved these changes
@maimoonak Thanks, I find the new change very useful :D
Our use case doesn't seem to be affected; it's getting better instead, and the new code looks great to me 👍

cc @f-odhiambo

2023-04-27 09:56 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
I like the addition of this, now we can see the selected answers in the QuestionnaireResponse, which doesn't happen previously 👍

2023-04-27 11:54 UTC, jingtang10 requested changes

2023-04-27 11:54 UTC, jingtang10 commented on catalog/src/main/res/values/strings.xml
> +    >Dynamic Question Title</string>
```suggestion
    >Dynamic Question Text</string>
```

2023-04-27 11:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal val questionTitle: Spanned? by lazy {
```suggestion
  internal val questionText: Spanned? by lazy {
```

2023-04-27 11:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +      questionTitle == other.questionTitle
i think this change needs to be in `hasTheSameAnswer`.

and you can probably change the name of that function to `hasTheSameResponse`

2023-04-27 13:56 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +    question.updateTextAndVisibility(questionnaireViewItem.questionTitle)
please add also add unit test to just check cqfExpression text value is shown over questionnaireItem.localizedTextSpanned

2023-04-27 14:09 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +   */
Could you please update the documentation to include that if a CQF expression result is present, it will be used as the question text, otherwise, localizedTextSpanned will be used?

2023-04-27 14:13 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +    question.updateTextAndVisibility(questionnaireViewItem.questionTitle)
Maybe you need to update the same change in `GroupHeaderView` class as well.

2023-04-27 14:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +    )
optional : If you think existing code is more readable, then in that case you can please ignore this suggestion.

```suggestion
    val appContext = mutableMapOf<String, Base?>()
    return with(appContext) {
      extractDependentVariables(
        expression,
        questionnaire,
        questionnaireResponse,
        questionnaireItemParentMap,
        questionnaireItem,
        appContext
      )
      fhirPathEngine.evaluate(
        appContext,
        questionnaireResponse,
        null,
        questionnaireResponseItem,
        expression.expression
      )
    }
```

2023-05-03 05:38 UTC, santosh-pingle approved these changes
@maimoonak thanks!
Is there a way to add unit test to `HeaderViewTest` and 'GroupHeaderViewTest' where dynamic text from cqf expression can be shown, or android test?
otherwise it looks good to me.

2023-05-04 22:52 UTC, jingtang10 requested changes
Great change! Thanks very much! Just a few comments below:

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreExpressions.kt
> +    }
Can you put this in a new file called `MoreElements.kt`?

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +    }
i don't see why `with` here is more readable? we're referring to `appContext` within the `with` block as `appContext` anyway? at the very least it could be `this`?

but i think we should just not use `with` here. i don't see the value.

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +   * [QuestionnaireResponse] %context = [QuestionnaireResponseItemComponent]
```suggestion
   * Returns the evaluation result of the CQF expression.
   * 
   * FHIRPath supplements are handled according to
   * https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements.
   *
   * %resource = [QuestionnaireResponse]
   * %context = [QuestionnaireResponseItemComponent]
```

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +  fun evaluateCqfExpression(
is this actually a function for cql expression or any expression would work?

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (cqfExpression.isFhirPath) {
can you flip this `if` so that we throw the exception if it's not fhir path.

and you don't need `else` any more.

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    // set title dynamically from cqf expression on textElement
```suggestion
    // Set question text dynamically from CQL expression
```

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/GroupHeaderView.kt
> +    // use questionText to ensure cqf-expression derived text is prioritized over localized text
```suggestion
    // CQF expression takes precedence over static question text
```

2023-05-04 22:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +    // use questionText to ensure cqf-expression derived text is prioritized over localized text
```suggestion
    // CQF expression takes precedence over static question text
```

2023-05-17 13:59 UTC, jingtang10 approved these changes
thanks @maimoonak! great job!

2023-05-17 14:30 UTC, merged