Answer expression catalog
google/android-fhir pull request #1960
Opened 2023-04-07 11:13 UTC by maimoonak

Fixes Answer expression catalog entry to see usage of the expression

**Description**
Answer expression is a complex expression which needs a demonstration of usage into catalog. 

**Type**
Choose one:  Code health

**Screenshots (if applicable)**

<img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/230599382-48cfe13b-f0ad-44a0-941b-e0dc9fd08fe5.gif"/>

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-04-18 07:52 UTC, santosh-pingle commented
I will do an initial review, thanks!

2023-04-18 13:38 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/CatalogApplication.kt
> +      }
nit: Please feel free to further modify the suggestion below.
```suggestion
    CoroutineScope(Dispatchers.IO).launch {
      assets
        .open("resource_data_bundle.json")
        .bufferedReader()
        .use { bufferedReader -> bufferedReader.readText() }
        .let { stringValue ->
          FhirContext.forR4Cached().newJsonParser().parseResource(stringValue) as Bundle
        }
        .entry
        .map { bundleEntryComponent -> bundleEntryComponent.resource }
        .let { resources ->
          fhirEngine.create(*resources.toTypedArray())
        }
    }
```

2023-07-19 08:45 UTC, aditya-07 submitted a review, later dismissed

2023-07-19 08:45 UTC, aditya-07 commented on catalog/src/main/java/com/google/android/fhir/catalog/CatalogApplication.kt
> +    FhirEngineProvider.init(FhirEngineConfiguration(testMode = true))
Is there reason for testMode to be true? Its should be true in **Tests only**.

2023-09-12 17:40 UTC, jingtang10 requested changes

2023-09-12 17:40 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +                    this.expression = "0x"
why this change?

2023-09-12 17:40 UTC, jingtang10 commented on catalog/src/main/assets/behavior_answer_expression.json
This file is really complicated. What's the minimal questionnaire you can come up with to demonstrate answer expression? Can we reduce the number of questions? Can we simplify the expressions? Can we change the question text to make it really clear what we're demonstrating with the questions?

2023-09-19 10:39 UTC, maimoonak commented
@jingtang10 I have resolved the feedback. The kokoro build is failing due to tests but I do not see any specific issue in logs. Looks like it passess on one device and fails on other
![Screenshot from 2023-09-19 15-38-18](https://github.com/google/android-fhir/assets/4829880/ce7cb87f-2d8b-4366-8990-256671b0c995)

2023-10-02 12:25 UTC, jingtang10 approved these changes

2023-10-02 13:16 UTC, merged