Support required text and optional text configuration.
google/android-fhir pull request #1963
Opened 2023-04-12 07:02 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1954 

**Description**

-  Show required text to the beginning of the instructions if views are non textInputLayout views.
-  Show required text as helper text if view are InputTextLayout views.
-  Support optional text configuration
-  If optional text is configured, then show optional text at the end of the question text.
-  If question text is not present then show optional text as helper text.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-04-13 07:02 UTC, santosh-pingle commented
@shelaghm 
Required text : 
<img width="417" alt="Screenshot 2023-04-13 at 12 30 06 PM" src="https://user-images.githubusercontent.com/86107848/231679321-890b7f37-167b-4c0f-8eb0-e008dd54c586.png">

Optional text : 
<img width="417" alt="Screenshot 2023-04-13 at 12 24 13 PM" src="https://user-images.githubusercontent.com/86107848/231679336-8f01515f-34f0-4297-8526-721f551dfe4f.png">

2023-04-13 17:18 UTC, shelaghm commented
This looks good to me. Thanks @santosh-pingle

2023-04-24 23:42 UTC, shelaghm commented
1. To be consistent between the two, I recommend we use the instruction text field to append required/optional. In paginated layout the (required) or (optional) text is very large and I think it's not THAT important to display. In default layout it works better than in paginated as the text proportions are more subtle.
2. Breaking it into two lines is a nice suggestion. @santosh-pingle Do you think we could do a line-break?

I've gone through and mocked up all the options, so we can be sure we are talking about the same options. I'll also post link in group chat as it's a lot! 
<img width="727" alt="Screenshot 2023-04-24 at 16 40 13" src="https://user-images.githubusercontent.com/86378921/234138352-32b823e0-c000-434c-9365-1d20bc714021.png">

2023-04-24 23:43 UTC, shelaghm commented
Feedback from @mberg 
To confirm does this mean the sdc will no longer support * or will that be supported as an option? I would want to keep the option to not have to display optional on every question. I feel like it’s a bit overwhelming to see it on every question.  Odk and most of the form libraries just use the *.  I think a lot of people are used to the pattern but I see why required text is a nice option too. I would want to disable optional on all questions though as I feel that becomes a bit overwhelming.

2023-04-25 05:08 UTC, santosh-pingle commented
@shelaghm 
Thanks for sharing the details.
The only pending questions are: what will be the default behavior, and what will be supported from the given table?

2023-04-25 23:07 UTC, shelaghm commented
@santosh-pingle I recommend that the default is `2 - Required` and that is appended to `instructions or help text`. So that is 2A, 2B, 2C. Default should be separate lines for Required/Optional and additional instructions

I suggest we make the following configurable:
- Optional (3)
- Asterisk (1)

I'm not sure if we need to add ability to also append the required/optional text behind the question title instead of in the instructions/help field. 

@jingtang10 what do you think? Let's discuss

2023-05-02 19:29 UTC, dubdabasoduba requested changes

2023-05-02 19:29 UTC, dubdabasoduba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    state[QuestionnaireFragment.EXTRA_MARK_OPTIONAL_QUESTION] ?: false
@santosh-pingle While testing I changed this to `true` and then re-run the code. The optional text was shown but even on the required fields. I haven't investigated much but I think we only need to show the optional text on the non-required fields. 

Feel free to update me incase I missed something.

2023-05-03 05:16 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    state[QuestionnaireFragment.EXTRA_MARK_OPTIONAL_QUESTION] ?: false
I am going to make changes as per above mentioned comment, once it is done I will update you. thanks!

2023-05-04 18:20 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    state[QuestionnaireFragment.EXTRA_MARK_OPTIONAL_QUESTION] ?: false
@dubdabasoduba Can you please test the latest changes I have made?

2023-05-05 05:22 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    state[QuestionnaireFragment.EXTRA_MARK_OPTIONAL_QUESTION] ?: false
Please update below existing functions to `DemoQuestionnaireFragment` in the catalog app while testing the changes.

```
  private fun addQuestionnaireFragment() {
    viewLifecycleOwner.lifecycleScope.launch {
      if (childFragmentManager.findFragmentByTag(QUESTIONNAIRE_FRAGMENT_TAG) == null) {
        childFragmentManager.commit {
          setReorderingAllowed(true)
          add(
            R.id.container,
            QuestionnaireFragment.builder()
              .setQuestionnaire(viewModel.getQuestionnaireJson())
              .showOptionalText(true)
              .showAsterisk(true)
              .showRequiredText(true)
              .build(),
            QUESTIONNAIRE_FRAGMENT_TAG
          )
        }
      }
    }
  }

private fun replaceQuestionnaireFragmentWithQuestionnaireJson() {
    // TODO: remove check once all files are added
    if (args.questionnaireFileWithValidationPathKey.isNullOrEmpty()) {
      return
    }
    viewLifecycleOwner.lifecycleScope.launch {
      val questionnaireJsonString =
        if (isErrorState) {
          viewModel.getQuestionnaireWithValidationJson()
        } else {
          viewModel.getQuestionnaireJson()
        }
      childFragmentManager.commit {
        setReorderingAllowed(true)
        replace(
          R.id.container,
          QuestionnaireFragment.builder()
            .setQuestionnaire(questionnaireJsonString)
            .showOptionalText(true)
            .showAsterisk(true)
            .showRequiredText(true)
            .build(),
          QUESTIONNAIRE_FRAGMENT_TAG
        )
      }
    }
  }

2023-05-05 05:29 UTC, santosh-pingle commented
@shelaghm 

<img width="406" alt="Screenshot 2023-05-05 at 10 56 26 AM" src="https://user-images.githubusercontent.com/86107848/236383243-c7ef60c9-e828-4048-854c-ce06bd2ebf4b.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 56 17 AM" src="https://user-images.githubusercontent.com/86107848/236383253-e4306f86-5581-4084-9576-00163c43c2bc.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 56 04 AM" src="https://user-images.githubusercontent.com/86107848/236383268-9c19b173-241f-4d0b-a2e4-554c37c535c7.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 55 56 AM" src="https://user-images.githubusercontent.com/86107848/236383280-22975c17-1a4d-486d-b32e-edb26bc4bb73.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 55 42 AM" src="https://user-images.githubusercontent.com/86107848/236383289-22b9c52b-dacc-4c54-8416-82be21608d4b.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 55 33 AM" src="https://user-images.githubusercontent.com/86107848/236383323-ffe41cb4-3290-4874-937c-b3fa09c21119.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 55 19 AM" src="https://user-images.githubusercontent.com/86107848/236383335-2e1cd456-f5eb-4715-80f4-ad306bf356ac.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 55 12 AM" src="https://user-images.githubusercontent.com/86107848/236383363-1629448a-1fa8-4148-8b8f-32d74b88aa21.png">
<img width="406" alt="Screenshot 2023-05-05 at 10 54 59 AM" src="https://user-images.githubusercontent.com/86107848/236383378-fa47db14-db73-49a6-aa13-ccc57d03e811.png">

2023-05-08 14:11 UTC, dubdabasoduba commented
@santosh-pingle I tested all three options and they seem to work well. I however have a small design request for the Asterisk display

![Screenshot 2023-05-08 at 14 08 05](https://user-images.githubusercontent.com/4817531/236846466-a2be9098-e61c-4066-8c16-3fb21062fae4.png)

I think we need some spacing between the text and the (*). I think the (*) should have a red text colour. 

cc: @shelaghm

2023-05-08 16:39 UTC, dubdabasoduba commented
@shelaghm should these 3 options be mutually exclusive? Right now you can how all can be turned on at the same time. 

![Screenshot 2023-05-08 at 16 39 14](https://user-images.githubusercontent.com/4817531/236880652-280bfe92-063d-4894-9855-5a92bdb7fe35.png)

2023-05-09 15:41 UTC, shelaghm commented
> I think we need some spacing between the text and the Asterisk. 

Yes, agreed. @santosh-pingle we should add one space before the asterisk. 

> I think the Asterisk should have a red text colour.

From our usability testing we learned that the red color on the asterisk was confusing, some people thought it was an error because it was red. So I don't recommend making the asterisk red. 

> should these 3 options be mutually exclusive? Right now you can how all can be turned on at the same time.
Yes, you can turn on all of these at the same time, because you might want to show the required text and the asterisk at the same time. 

@dubdabasoduba @santosh-pingle @jingtang10

2023-05-10 14:55 UTC, jingtang10 requested changes
thanks @santosh-pingle

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="required_in_instructions">Required.\u0020</string>
remove

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var showRequiredText = state[QuestionnaireFragment.EXTRA_SHOW_REQUIRED_TEXT] ?: true
```suggestion
  private val showRequiredText = state[QuestionnaireFragment.EXTRA_SHOW_REQUIRED_TEXT] ?: true
```

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var markOptionalQuestionText =
```suggestion
  private val markOptionalQuestionText =
```

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var markOptionalQuestionText =
```suggestion
  private var showOptionalText =
```

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal val showOptionalText: Boolean = false,
wrap in one data class

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +    appendAsteriskToQuestionText(question, questionnaireViewItem)
can you keep calling `question.updateTextAndVisibility` here but just call it with a different param?

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +  questionTextView.updateTextAndVisibility(builder)
```suggestion
  return SpannableStringBuilder().apply {
    ...
  }
```

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +}
remove

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/res/layout/header_view.xml
> +        android:text="@string/required"
remove this as a default?

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +  /** Shows an required text in the header. */
update the doc

2023-05-10 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DateTimePickerViewHolderFactory.kt
> +            }
extract this and reuse

2023-05-17 05:39 UTC, santosh-pingle commented
Resolving review comments.

2023-05-17 11:29 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +  fun showRequiredOrOptionalTextInHeaderView(questionnaireViewItem: QuestionnaireViewItem) {
Required/Optional text is shown as helper text for views like EditTextViewHolderFactory, DatePickerViewHolderFactory etc, therefore it is not called in the bind() of the HeaderView.

2023-05-17 12:25 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DateTimePickerViewHolderFactory.kt
> +            }
done.

2023-05-17 12:25 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +  /** Shows an required text in the header. */
done.

2023-05-17 12:25 UTC, santosh-pingle commented on datacapture/src/main/res/layout/header_view.xml
> +        android:text="@string/required"
done.

2023-05-17 12:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +}
done.

2023-05-17 12:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +  questionTextView.updateTextAndVisibility(builder)
done.

2023-05-17 12:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/HeaderView.kt
> +    appendAsteriskToQuestionText(question, questionnaireViewItem)
done.

2023-05-17 12:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal val showOptionalText: Boolean = false,
done.

2023-05-17 12:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var markOptionalQuestionText =
done.

2023-05-17 12:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var markOptionalQuestionText =
done.

2023-05-17 12:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var showRequiredText = state[QuestionnaireFragment.EXTRA_SHOW_REQUIRED_TEXT] ?: true
done.

2023-05-17 12:27 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var showAsterisk = state[QuestionnaireFragment.EXTRA_SHOW_ASTERISK_TEXT] ?: false
done.

2023-05-17 12:28 UTC, santosh-pingle commented on datacapture/src/main/res/values/strings.xml
> +    <string name="required_text_and_new_line">Required \n</string>
done.

2023-05-17 12:28 UTC, santosh-pingle commented on datacapture/src/main/res/values/strings.xml
> +    <string name="optional_text">\u0020(optional)</string>
done.

2023-05-17 12:28 UTC, santosh-pingle commented on datacapture/src/main/res/values/strings.xml
> +    <string name="required_in_instructions">Required.\u0020</string>
done.

2023-05-17 12:57 UTC, jingtang10 approved these changes

2023-05-17 12:57 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  }
move this to before the required test case, and also add a test case where asterisk is not enabled and check there's no asterisk appended to the question text.

2023-05-17 12:57 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  fun shows_optionalText() {
add a test case where optional / required are not enabled

2023-05-17 12:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +  questionTextView: TextView,
remove

2023-05-17 12:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +    QuestionTextConfiguration()
```suggestion
    QuestionTextConfiguration(),
```

2023-05-17 12:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/CheckBoxGroupViewHolderFactoryTest.kt
> +  fun `show required text`() {
add a case where there's no required or optional or asterisk.

and add that for every other test class here.

2023-05-18 06:38 UTC, santosh-pingle commented on datacapture/src/main/res/values/strings.xml
> +    <string name="optional_helper_text">Optional</string>
At the moment, `Optional` text is not shown in the error message, therefore it does not require \n to separate out rest of the text in the error message.

2023-05-18 10:05 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  }
done.

2023-05-18 10:05 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +    QuestionTextConfiguration()
done.

2023-05-18 10:05 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/factories/CheckBoxGroupViewHolderFactoryTest.kt
> +  fun `show required text`() {
done.

2023-05-18 12:10 UTC, merged