Allow users to request referenced resources along with the searched via inline params.
google/android-fhir pull request #1978
Opened 2023-04-18 08:36 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1947

**Description**
1. Add revInclude function to search api's w.r.t https://build.fhir.org/search.html#_revinclude .

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-04-24 12:34 UTC, jingtang10 requested changes

2023-04-24 12:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  fun revInclude(resourceType: ResourceType, vararg clientParam: ReferenceClientParam) {
why is the client param `vararg`?

2023-04-24 12:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +   * Allows user to include additional resources to be included in the search results that reference
```suggestion
   * Includes additional resources in the search results that reference ...
```

2023-04-24 12:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/Search.kt
> +suspend fun FhirEngine.search(resourceType: ResourceType, init: Search.() -> Unit): List<Resource> {
This weakens type safety by quite a bit.

can we do something like this: so you package the reverse included resources together with their parents?

```
fun <R, S> search(...) : List<Map<R, S>> { ... }
```

2023-04-24 12:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        """.trimIndent()
can you fix the indentation? all a bit hard to read for me.

2023-04-24 12:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        revIncludeMap.isNotEmpty() -> {
can you have nested and revinclude together? what happens in that case?

2023-04-24 13:01 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        """.trimIndent()
can you try the annotation? @JSON... something like that..

2023-04-26 14:26 UTC, ellykits commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  internal val revIncludeMap = mutableMapOf<ResourceType, MutableList<ReferenceClientParam>>()
I think the iterate modifier will be a useful enhancement for the next iteration as well as an implementation of  **_include**  which is different from the **_revinclude** syntax.

2023-04-26 14:27 UTC, ellykits commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  internal val revIncludeMap = mutableMapOf<ResourceType, MutableList<ReferenceClientParam>>()
I think the iterate modifier will be a useful enhancement for the next iteration as well as an implementation of  **_include**  which is different from the **_revinclude** syntax.

2023-04-26 14:28 UTC, ellykits commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  internal val revIncludeMap = mutableMapOf<ResourceType, MutableList<ReferenceClientParam>>()
An example use case is : Retrieve a Group resource including all the referenced Resources of `Group#member` property.

2023-04-27 07:02 UTC, ellykits commented on engine/src/main/java/com/google/android/fhir/search/Search.kt
> +suspend fun FhirEngine.search(resourceType: ResourceType, init: Search.() -> Unit): List<Resource> {
I think `S` should instead be a `List<S>`

2023-04-27 10:10 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  internal val revIncludeMap = mutableMapOf<ResourceType, MutableList<ReferenceClientParam>>()
> For _revinlcude are we supporting just this syntax: `[_include|_revinclude]=[resource]:[parameter]` ? What about other syntaxes ?
> 
> ```
> [_include|_revinclude]=*
> [_include|_revinclude]=[resource]:*
> [_include|_revinclude]=[resource]:[parameter]:[targetType]
> ```

We don't necessarily want to implement the exact same spec as sever on the device. Instead we want to provide the subset of apis that would be useful and make most sense of the device. As the client app would only need a subset of resources,  I don't think we need to do the wildcard matching. 

Incase of [_include|_revinclude]=[resource]:[parameter]:[targetType], we can infer the [targetType] from the Resource on which the [_include|_revinclude] is being called upon.

2023-05-02 09:00 UTC, ellykits requested changes

2023-05-02 09:00 UTC, ellykits commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        includedResources
We can convert this to a sequence using the `asSequence()` function.

2023-05-02 10:12 UTC, aditya-07 commented
I have added some experimental code in it for quick testing. Will convert it back once the changes are in better shape.

2023-07-10 13:58 UTC, jingtang10 requested changes

2023-07-20 09:09 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +internal data class IndexedIdAndResource(
Done

2023-07-20 09:09 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +internal data class IndexedIdAndSerializedResource(
Done

2023-07-20 09:11 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +class Search(val type: ResourceType, var count: Int? = null, var from: Int? = null) : ISearch {
This change may pollute this PR with just the name change. So, planning to do it in a separate PR.

2023-07-20 09:13 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/ISearch.kt
> +  fun operations(operation: Operation)
I have change it to properties instead and added docs to them.

2023-07-20 09:13 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/ISearch.kt
> +interface ISearch {
Done **BaseSearch**. Added documentation as well.

2023-07-20 10:17 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +typealias ReferencedResources = Map<ResourceType, List<Resource>>
Done. The referenced resources are of type `Map<ResourceType, Map<SearchParamName, List<Resource>>>`.

2023-07-20 10:19 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  fun revInclude(resourceType: ResourceType, vararg clientParam: ReferenceClientParam) {
Not applicable after refactor.

2023-07-20 10:22 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/Search.kt
> +suspend fun FhirEngine.search(resourceType: ResourceType, init: Search.() -> Unit): List<Resource> {
Done as part of refactor.

2023-07-20 10:46 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +   * Allows user to include additional resources to be included in the search results that reference
Done

2023-07-20 10:47 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        revIncludeMap.isNotEmpty() -> {
Not applicable after refactor.

2023-07-20 10:47 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        includedResources
Not applicable after refactor.

2023-07-20 11:04 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        """.trimIndent()
Couldn't find a way to do it by annotations. Recomended spotless way is to use `spotless:off` and `spotless:on` [toggle](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson).

2023-07-20 11:39 UTC, aditya-07 commented
> I have added some experimental code in it for quick testing. Will convert it back once the changes are in better shape.

Experimental code has been removed or moved to a production ready state.

2023-07-24 13:03 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_patient_with_reference_resources(): Unit = runBlocking {
can we also create smaller and more focused test cases.. for forward and backward includes.

2023-07-24 13:05 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  val included: ReferencedResources?,
i think the forward include return type doesn't have to have resource type.

2023-07-25 11:46 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_patient_with_reference_resources(): Unit = runBlocking {
Done

2023-07-25 11:46 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  val included: ReferencedResources?,
Done

2023-07-27 08:02 UTC, jingtang10 requested changes

2023-07-27 08:02 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  private fun equalsShallow2(
avoid fuction names like this :)

2023-07-27 14:18 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +/** It contains the searched resource and referenced resources as per the search query. */
Done

2023-07-31 13:05 UTC, jingtang10 approved these changes
great job!

2023-08-01 10:28 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  val revIncluded: Map<ResourceType, Map<SearchParamName, List<Resource>>>?
Done

2023-08-03 09:59 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineTerminologyProvider.kt
you could revert these changes i think

2023-08-11 10:23 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineTerminologyProvider.kt
done

2023-08-11 10:23 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
done

2023-08-11 10:23 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineDal.kt
done

2023-08-21 18:57 UTC, merged