Placed help button location to after question title
google/android-fhir pull request #1984
Opened 2023-04-24 11:45 UTC by khyativyasargus

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1965 

**Description**
Move help button location to after question title as subtitle might be empty in some cases.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/121015652/233986785-ca20f3ef-6d25-45fb-a703-12de514da089.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-04-25 06:06 UTC, santosh-pingle commented
@khyativyasargus 
I noticed a slight cut on the right side of the help button. Could you please confirm this?

Can you also try the following precondition and see how the help button aligns?
Please modify questionnaire.json and add 1. precondition text 2. long question text

2023-04-26 05:32 UTC, khyativyasargus commented
Thanks @santosh-pingle for drawing my attention. Sure will check and provide requested details. Just one doubt can you elaborate about precondition here?

2023-04-26 06:13 UTC, santosh-pingle commented
> Thanks @santosh-pingle for drawing my attention. Sure will check and provide requested details. Just one doubt can you elaborate about precondition here?

Actually, i just wanted to see if prefix text is present and question text is 2-3 line text in the json file then how help button get aligns`.

In the component_help.json, you can add `"prefix":"3."` and `"text": "Adding long text to just see how help button get aligns, its just testing.Adding long text to just see how help button get aligns, its just testing.Adding long text to just see how help button get aligns, its just testing",`

2023-04-27 14:30 UTC, khyativyasargus commented
> I noticed a slight cut on the right side of the help button. Could you please confirm this?

@santosh-pingle  This is because for help button, Button widget is used which is ideally in square shape with edges and we are putting round shape image into that.
so to solve that there are 2 options in my mind right now,
1)increase button width and height by 1dp and put 1dp padding 
2)change widget type from Button to ImageView 

what do you suggest?  Let me know if you have any other option on your mind , I'll do changes accordingly.

2023-04-27 14:34 UTC, khyativyasargus commented
> Actually, i just wanted to see if prefix text is present and question text is 2-3 line text in the json file then how help button get aligns`.
> 
> In the component_help.json, you can add `"prefix":"3."` and `"text": "Adding long text to just see how help button get aligns, its just testing.Adding long text to just see how help button get aligns, its just testing.Adding long text to just see how help button get aligns, its just testing",`

@santosh-pingle I've done some corrections to manage long text, but I'll commit them with help button changes together. Here it is SS for how it looks

![image](https://user-images.githubusercontent.com/121015652/234895904-033d12dc-1f1b-4b18-97f2-113e0471b593.png)

2023-05-03 05:46 UTC, santosh-pingle commented
> > Actually, i just wanted to see if prefix text is present and question text is 2-3 line text in the json file then how help button get aligns`.
> > In the component_help.json, you can add `"prefix":"3."` and `"text": "Adding long text to just see how help button get aligns, its just testing.Adding long text to just see how help button get aligns, its just testing.Adding long text to just see how help button get aligns, its just testing",`
> 
> @santosh-pingle I've done some corrections to manage long text, but I'll commit them with help button changes together. Here it is SS for how it looks
> 
> ![image](https://user-images.githubusercontent.com/121015652/234895904-033d12dc-1f1b-4b18-97f2-113e0471b593.png)
> 
> ![image](https://user-images.githubusercontent.com/121015652/234896391-ce8a4357-ab45-4ca8-9a4a-f3d6eb416c0a.png)
> 
> ![image](https://user-images.githubusercontent.com/121015652/234898752-0233d010-395a-48fc-b84d-33190ca5e9ea.png)

@shelaghm Can you please review attached screenshots by @khyativyasargus 

You mean, changes will be updated to this pr, correct?

2023-05-03 14:37 UTC, khyativyasargus commented
> @khyativyasargus, you mean, changes will be updated to this pr, correct?

Yes @santosh-pingle , once you & @shelaghm approves screenshots I'll commit changes in this PR only.

2023-05-04 07:24 UTC, khyativyasargus commented
> @khyativyasargus thanks for this change, would it be possible to also refactor the header so that the prefix is also inline the same way the icon is inline in the link i posted above?

Yes @jingtang10 this option sounds more convenient to me as per UI perspective. so you wan prefix & help icon both inline with title right?  I'll give it check and will update you with changes.

2023-05-10 12:07 UTC, khyativyasargus commented
> @khyativyasargus thanks for this change, would it be possible to also refactor the header so that the prefix is also inline the same way the icon is inline in the link i posted above?

Hi @jingtang10 @santosh-pingle ! As per our conversation, I've done with refactoring the question header view in such a way that the Prefix, Title, and icon stay inline with the help of Spannable. 
But I think Text & Icon should also be customized with custom style attributes and I am not sure how we can achieve that. Can you guide me about the possibility?

2023-05-11 17:43 UTC, jingtang10 commented
hey @khyativyasargus thanks for the update. can you add new screenshots, especially for long titles?

2023-05-12 11:36 UTC, khyativyasargus commented
> hey @khyativyasargus thanks for the update. can you add new screenshots, especially for long titles?

Sure @jingtang10 , Here is a screenshot of inline headerview with longer title

![image](https://github.com/google/android-fhir/assets/121015652/c8b42738-52c5-4301-9f23-619b0c9dcfc6)

2023-05-17 15:06 UTC, shelaghm commented
Thanks @khyativyasargus Looks better, one small adjustment would be to make the help button aligned to the text line height? See screenshot as an example <img width="675" alt="Screenshot 2023-05-17 at 08 04 50" src="https://github.com/google/android-fhir/assets/86378921/b251becc-9c76-4fa2-8f08-c7c649093656">

2023-07-19 09:04 UTC, aditya-07 requested changes
If we are not depending on any kotlin code to place the Help Button, then we should remove it from this PR.

2023-07-19 09:04 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +}
Can we remove this code if it is not being used anywhere?

2023-07-19 09:04 UTC, aditya-07 commented
@khyativyasargus Please update the PR to latest changes.

2023-07-19 09:10 UTC, khyativyasargus commented
> If we are not depending on any kotlin code to place the Help Button, then we should remove it from this PR.

Hi @aditya-07 these changes are required but as we haven't been able to find a way to configure Image using style attribute with Spannable so it's still pending. We can refactor the code of this PR once we find the final solution.

2024-06-10 17:20 UTC, jingtang10 commented
Given the status of this PR I'm going to close this for now until we have a proper solution that works well. @khyativyasargus if this becomes blocking please feel free to reopen.

2024-06-10 17:20 UTC, closed without merging