Repeated Group Headers
google/android-fhir pull request #1994
Opened 2023-05-03 15:19 UTC by kevinmost

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #726

**Description**
Add headers to repeated groups.

The header shows the index of the repeated group instance, plus a delete button that removes that entire instance.

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-05-11 03:23 UTC, jingtang10 commented
@shelaghm please take a look at the screenshot!

we didn't really know what to do with the heading so used cardinal numbers 1,2,...

@kevinmost and i did wonder if there's a group header extension from the FHIR spec we can use... or maybe we can use a placeholder like Group 1, Group 2,...

2023-05-11 04:08 UTC, jingtang10 requested changes
great pr! love this ❤️. thanks @kevinmost

2023-05-11 04:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +internal val Questionnaire.QuestionnaireItemComponent.isRepeatedGroup: Boolean
need unit test coverage

2023-05-11 04:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +internal val Questionnaire.QuestionnaireItemComponent.isRepeatedGroup: Boolean
also this should be in a different class.

2023-05-17 15:19 UTC, shelaghm commented
Looks amazing! @kevinmost
A few suggestions to make it even better:

1.  Add 'Group' in front of 1, 2. So it reads Group 1, Group 2, etc.
2. Move the `sample date question` text so that it is the placeholder text inside the text field and dropdown. 
3. Use the EntryFormat / hint text field for the date format. 

(See screenshot for details)
![Repeat Group 12](https://github.com/google/android-fhir/assets/86378921/03ce06f4-57e8-4f95-a89f-ddd2e8c5ca27)

2023-07-25 14:19 UTC, kevinmost commented
Updated

2023-07-25 14:20 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          if (!questionnaireItem.isRepeatedGroup) {
Aren't these cases already extensively covered? For example, `questionnaireHasNestedItem_ofTypeGroup_shouldNestItemWithinItem` hits this code-path.

2023-07-28 10:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal fun removeAnswerAt(index: Int) {
oh ok i see

2023-07-28 10:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
@kevinmost

2023-08-02 09:12 UTC, jingtang10 requested changes
thanks for this @kevinmost!

happy to approve once all comments have been addressed - don't think i have any more comments.

2023-08-02 09:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          if (!questionnaireItem.isRepeatedGroup) {
yeah i think you're right! i'm just sensitive to any change that doesn't trigger a change in the unit test.

2023-08-02 09:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
are we missing a test for delete?

2023-08-02 09:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreViews.kt
`MoreViewGroups.kt`?

2023-08-10 14:54 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireAdapterItem.kt
> +    val responses: List<QuestionnaireResponse.QuestionnaireResponseItemComponent>,
We'll change `areItemsTheSame` to use the `questionnaireResponseItem`, and `areContentsTheSame` to use the `index`

2024-05-30 05:26 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreViews.kt
done.

2024-05-30 05:27 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/PhoneNumberViewHolderFactoryInstrumentedTest.kt
> +    viewHolderFromAdapter as QuestionnaireEditAdapter.ViewHolder.QuestionHolder
done.

2024-05-30 08:44 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +internal val Questionnaire.QuestionnaireItemComponent.isRepeatedGroup: Boolean
done.

2024-05-30 10:30 UTC, santosh-pingle commented on datacapture/src/main/res/layout/repeated_group_instance_header_view.xml
> +    android:gravity="center_vertical"
The `android:gravity="center_vertical"` attribute is used to vertically center align the child views, such as the Group text (TextView) and Delete icon (ImageView), within the LinearLayout. According to Shelagh's mockup, the Group text is already aligned to the left by default.

2024-05-30 11:21 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/PhoneNumberViewHolderFactoryInstrumentedTest.kt
> +    assertThat(viewHolderFromAdapter.holder).isInstanceOf(viewHolder::class.java)
done.

2024-05-31 11:10 UTC, jingtang10 requested changes

2024-05-31 13:13 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/QuestionnaireUiEspressoTest.kt
> +      }
done.

2024-05-31 13:13 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +        type = Questionnaire.QuestionnaireItemType.BOOLEAN
done.

2024-05-31 13:13 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +  fun testQuestionnaireItemComponentIsNotRepeatedGroup() {
done.

2024-05-31 13:13 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +  fun testQuestionnaireItemComponentIsRepeatedGroup() {
done.

2024-06-03 06:41 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
Works in the review mode.

2024-06-03 07:39 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
Added `readonly' attribute implementation to repeated group.

2024-06-03 07:46 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
In the existing implementation, a repeatedGroup only shows nested items if the "Add Item" button is clicked. If it is in Read Only mode, the "Add Item" button is not displayed, hence there is no way to show nested items. 
@jingtang10

2024-06-03 12:49 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal fun removeAnswerAt(index: Int) {
@santosh-pingle please add a test case

2024-06-04 13:48 UTC, santosh-pingle commented
https://github.com/google/android-fhir/pull/1994/files#diff-1f4ba456c28c5400e29ae89383faf8d1a8d9109c80299bc0efb1ed3cf11818b2R834

This change has side effects:

Nested items of repeated group items are not shown.
Answers that are captured in questionnaireResponse.json and passed as an argument to QuestionnaireFragment do not show nested items of repeated group items.

If the following fix is added, then the above-mentioned issues are not seen:
`add(questionnaireResponseItem.item)`

@jingtang10

2024-06-05 15:04 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireAdapterItem.kt
> +    val responses: List<QuestionnaireResponse.QuestionnaireResponseItemComponent>,
It sounds to me like we wanted to flip the `areItemsTheSame` and `areContentsTheSame` implementations?

i.e, `areItemsTheSame` should be `newItem is QuestionnaireAdapterItem.RepeatedGroupHeader && oldItem.responses == newItem.responses`

and `areContentsTheSame` should be `newItem is QuestionnaireAdapterItem.RepeatedGroupHeader && oldItem.index == newItem.index`

2024-06-07 06:58 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +  internal suspend fun removeAnswerAt(index: Int) {
done.

2024-06-10 02:28 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
>            viewModel.getQuestionnaireItemViewItemList().map {
local function was already renamed.

2024-06-10 03:53 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
>        viewModel.getQuestionnaireItemViewItemList().single {
this change was already updated in the codebase.

2024-06-10 04:12 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireAdapterItem.kt
> +    val responses: List<QuestionnaireResponse.QuestionnaireResponseItemComponent>,
Kevin had already updated this change, so resolving it.

2024-06-10 06:12 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/QuestionnaireUiEspressoTest.kt
> +      )
Acknowledged. 
I will check other way to add questionnaire response.
(If the fix is not ready by the time the PR gets merged, I will create a separate PR.)

2024-06-10 11:26 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/QuestionnaireUiEspressoTest.kt
> +      )
done, provided questionnaire response to the fragment.

2024-06-10 13:52 UTC, jingtang10 approved these changes

2024-06-10 14:40 UTC, santosh-pingle commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/QuestionnaireUiEspressoTest.kt
> +import java.util.*
done.

2024-06-10 18:03 UTC, merged