Allow multiple resources to be set in context
google/android-fhir pull request #2000
Opened 2023-05-04 19:25 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1844 

**Description**
Clear and concise code change description. 

Allow multiple resources to be set in context

In the resource table, it says: 

```
Context resources needed for Questionnaire
```
 https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-launchContext.html

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-05-10 06:18 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      "list-of-questionnaire-launch-contexts"
optional : 
optional : 
```suggestion
    internal const val EXTRA_QUESTIONNAIRE_LAUNCH_CONTEXT_JSON_STRINGS =
      "questionnaire-launch-contexts"
```

2023-05-10 06:21 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        val launchContextsAsStrings: List<String> =
optional:
```suggestion
        val launchContextJsonStrings: List<String> =
```

2023-05-22 14:55 UTC, jingtang10 requested changes

2023-05-22 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          .filter { it.url == EXTENSION_SDC_QUESTIONNAIRE_LAUNCH_CONTEXT }
make this an extension to the questionnaire class (in `MoreQuestionnaires.kt`)

2023-05-22 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          ?.let { extensions ->
better naming plz

2023-05-22 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt
> +  launchContextResourceTypes: List<String>
can you try to resctructure the code so that you just are checking that these 2 things are basically 1:1 mapping.

2023-05-25 16:55 UTC, jingtang10 requested changes
can you add a test case that tests multiple contexts? i feel that it is not covered in the current test cases.

2023-05-25 16:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt
> +  if (launchExtension.extension.size != 2) {
can you use `require` or `check`?

2023-05-25 16:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt
> +      "The extension:name or extension:type extension is missing in $EXTENSION_SDC_QUESTIONNAIRE_LAUNCH_CONTEXT"
this doesn't feel right - fhir is highly extensible so you may well have other extensions apart from name and type... so why not check name and type actually exists instead of checking the size of the extension list?

2023-05-25 16:55 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +        mapOf("Practitioner" to Practitioner())
why do you use string here, but resource name on line 714, but resource name in lowercase on line 738?

2023-05-25 16:55 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesTest.kt
> +  fun `should throw exception if both name and type extension are not present`() {
this test case is only testing type is not present, can you add another one that tests name isn't present? and rename accordingly.

2023-05-26 12:07 UTC, omarismail94 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaires.kt
> +      "The extension:name or extension:type extension is missing in $EXTENSION_SDC_QUESTIONNAIRE_LAUNCH_CONTEXT"
the extensions that are passed in are only the name and type extension. The calling function calls `validateLaunchContextExtension` with:

```
  launchContextExtensions.forEach { launchExtension ->
    validateLaunchContextExtension(
      Extension().apply {
        addExtension(launchExtension.extension.firstOrNull { it.url == "name" })
        addExtension(launchExtension.extension.firstOrNull { it.url == "type" })
      }
    )
```

so the validation function only gets the name and type extensions

2023-05-26 13:31 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
> +        mapOf("Practitioner" to Practitioner())
fixed

2023-05-26 13:31 UTC, omarismail94 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnairesTest.kt
> +  fun `should throw exception if both name and type extension are not present`() {
fixed

2023-05-26 13:32 UTC, omarismail94 commented
> can you add a test case that tests multiple contexts? i feel that it is not covered in the current test cases.

added a test case with multiple contexts in `ExpressionEvaluatorTest`

2023-05-26 16:38 UTC, jingtang10 approved these changes

2023-05-26 16:38 UTC, merged