Support for headers in the http requests.
google/android-fhir pull request #2009
Opened 2023-05-18 13:32 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1989 

**Description**
1. Added a way for users to specify http headers in DownloadWorkManager requests. 
2. Update and Delete requests now use If-Match Http header with [weak Etag](https://hl7.org/fhir/http.html#Http-Headers).

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-05-23 09:04 UTC, jingtang10 requested changes
please add a network config to control if etag is used.

2023-05-24 03:48 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/HttpVerbBasedBundleEntryComponentGenerator.kt
> +          LocalChange.Type.DELETE -> ifMatch = "W/\"${localChange.versionId}\""
This header will be passed irrespective of the value in the headers. 
This addition is making this compulsory. Should we do it or make it configurable?

2023-05-25 11:33 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    if (eTag.startsWith("W/")) {
nit : can you please check below suggestion.
```suggestion
private companion object {
    // E.G  ETag: W/"3141"
    private const val ETAG_PREFIX = "W/"
    private const val ETAG_VERSION_ID_DELIMITER = "\""
    private const val ETAG_VERSION_ID_INDEX = 1
  }
 ...
    if (eTag.startsWith(ETAG_PREFIX)) {
      eTag.split(ETAG_VERSION_ID_DELIMITER)[ETAG_VERSION_ID_INDEX]
    } else {
 ...
    
```

2023-05-30 09:41 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/DownloadWorkManager.kt
> +data class UrlRequest(val url: String, override val headers: Map<String, String> = emptyMap()) :
Done.

2023-05-30 10:21 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/DownloadWorkManager.kt
> +sealed class Request(open val headers: Map<String, String>) {
Added a brief doc on the usage of Request. Planning to rename the class to DownloadRequest in a subsequent PR to keep this PR lean.

2023-05-30 10:24 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +   */
Added a comment. Though server should always send W/, if for some reason the server send a strong etag, we will keep as-is it instead of discarding it.

2023-05-30 10:25 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/HttpVerbBasedBundleEntryComponentGenerator.kt
> +          LocalChange.Type.DELETE -> ifMatch = "W/\"${localChange.versionId}\""
Yes, as per Jing and your suggestion, I have moved it under a flag defined in `UploadConfiguration`.

2023-06-11 07:37 UTC, merged