Upload work manager
google/android-fhir pull request #2022
Opened 2023-06-01 04:04 UTC by anchita-g

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2021 

**Description**
- Create an interface for UploadWorkManager which will be able to orchestrate over what to upload from the list of local changes and how to upload (create Bundle from the list of changes to be uploaded) 

**Alternative(s) considered**
NA

**Type**
 Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-07-11 08:57 UTC, anchita-g commented
To contain the size of the changes, I have just added major refactoring and interface changes in this PR. I will follow this one with another PR to support other upload requests (per resource based uploads).

2023-07-12 10:22 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  open fun preprocessLocalChanges(localChanges: List<LocalChange>): List<LocalChange> {
actually, on looking at the code again, can we create an interface, and combine both these functions into one? Each implementation of `createUploadRequestsFromChanges` can decide what it wants to do with the changes (squash or not)

2023-07-12 10:22 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun createUploadRequestsFromChanges(localChanges: List<LocalChange>): List<UploadRequest> {
nit:
```suggestion
  fun createUploadRequestsFromLocalChanges(localChanges: List<LocalChange>): List<UploadRequest> {
```

2023-07-12 10:22 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt
> +  private val uploadWorkManager: UploadWorkManager
nit: add trailing comma at the end so when we go to add more parameters (hopefully never), we don't have to edit this line
```suggestion
  private val uploadWorkManager: UploadWorkManager,
```

2023-07-12 10:34 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +abstract class UploadWorkManager(private val uploadRequestGenerator: UploadRequestGenerator) {
The abstract class was created to provide an out-of-the-box implementation for `preprocessing` changes - to squash changes. This was a default implementation till now, hence, was of the opinion to provide this as is.

2023-07-12 10:37 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/Uploader.kt
> +sealed class UploadRequest(
IMO we should keep Download requests different from Upload requests as the Upload requests could be of different types like `PATCH`, `PUT`, `DELETE` (as my follow up PR would do). I agree with keeping the Request out of DWM. We should also consider renaming `Request` here with `DownloadRequest`

2023-07-12 10:39 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpDataSource.kt
>        is BundleRequest -> fhirHttpService.post(request.bundle, request.headers)
Makes sense. Will do this!

2023-07-12 10:43 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  open fun preprocessLocalChanges(localChanges: List<LocalChange>): List<LocalChange> {
We could do this. I was thinking about doing something similar. However, felt like it would be really helpful to provide squashing of changes as a default implementation of pushing changes. If that is to happen, it would need the changes transformation to be different from how to upload them.

2023-07-12 10:45 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpDataSource.kt
> +  override suspend fun upload(request: UploadRequest): Resource =
If we keep the Download Requests separately from the Upload Requests, we might not need this.

2023-07-12 10:47 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +abstract class UploadWorkManager(private val uploadRequestGenerator: UploadRequestGenerator) {
I think we can still do that if we switch this to an interface. See `ResourceParamsBasedDownloadWorkManager` as an example of an implementation of `DownloadWorkManager` that gives an out-of-the box implementation of the whole class. In general we should favour composition over inheritance

2023-07-12 10:50 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  open fun preprocessLocalChanges(localChanges: List<LocalChange>): List<LocalChange> {
We can still do this with a default implementation of the interface that is public, if we go the route of converting this class to an interface

2023-07-13 12:57 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Request.kt
> +sealed class UploadRequest(
could you make the creation of this class similar to that of `DownloadRequest`, i.e. having a companion object with `of` functions and having UploadRquest just take in headers in its constructor

2023-07-13 12:57 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  /** Generates a list of [UploadRequest] from the [LocalChange]s to be uploaded to the server */
nit
```suggestion
  /** Generates a list of [UploadRequest]s from the [LocalChange]s to be uploaded to the server */
```

2023-07-13 12:57 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
>     * Transform the [localChanges] to the final set of changes that needs to be uploaded to the
nit"
```suggestion
   * Transform the [LocalChange]s to the final set of changes that needs to be uploaded to the
```

2023-07-13 12:57 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpDataSource.kt
> +  override suspend fun upload(request: UploadRequest): Resource =
what are the advantage of keeping Download Request separate from Upload requests that make it worth it to have two functions doing almost the same thing (sending post/get request)

2023-07-13 12:57 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +   * server.
if you want to maintain having a generator as a property, you can have it in the interface:

https://kotlinlang.org/docs/interfaces.html#properties-in-interfaces

 i don't know how useful it is. What are your thoughts?

2023-07-13 12:57 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/testing/Utilities.kt
> +    urls.poll()?.let { DownloadRequest.of(it) }
nit: add space
```suggestion
    urls.poll()?.let { DownloadRequest.of(it) }
    
```

2023-07-13 13:01 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  open fun preprocessLocalChanges(localChanges: List<LocalChange>): List<LocalChange> {
unresolving this as the function name is still the same

2023-07-14 06:56 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/remote/FhirHttpDataSource.kt
> +  override suspend fun upload(request: UploadRequest): Resource =
The nuances of what needs to go in a Upload/Download request is different. For upload, we need to manage local change tokens, resource type information of the resource to be uploaded etc. The semantics of constructing a request for Download is different from Upload. As for post/get and other types of requests, we do have `FhirHttpService` where in we do not differentiate on the type of request (download/upload). These are simple HTTP method calls.
`DataSource` will help us map the correct Upload/Download request to the corresponding HTTP method call in `FhirHttpService`.  I like the way where we have clear way to `download` using the `DownloadRequest` as it clearly specifies the type of requests that are supported for downloading. Similarly for uploading

2023-07-14 06:59 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/Request.kt
> +sealed class UploadRequest(
I am going to follow PR this with another PR, where in, I would add more types of `UploadRequest`. The `of` way of doing things might not be that intuitive for the developer. Can we keep this discussion for the follow-up PR?

2023-07-14 07:02 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +   * server.
TIL!!! Very helpful. Didn't know something like this exists. (Part of the reason why I wanted to go the abstract class way)

2023-07-14 07:04 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +   * server.
I am not sure if this will be useful to provide it as a property as we can not use it in the interface itself. But thanks for this, TIL!!

2023-07-14 07:06 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/testing/Utilities.kt
> +    urls.poll()?.let { DownloadRequest.of(it) }
Oh you meant a new line!! Done

2023-07-20 17:02 UTC, jingtang10 requested changes

2023-07-20 17:20 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Uploader.kt
> +sealed class UploadRequest(
would upload and download requests also need to handle other differences such as page size? i'm not in favour of unifying prematurely.

2023-07-21 07:47 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangesPaginator.kt
I agree, removed the interface.

2023-07-24 14:34 UTC, jingtang10 approved these changes

2023-07-24 14:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/HttpVerbBasedBundleEntryComponentGenerator.kt
> +abstract class HttpVerbBasedBundleEntryComponentGenerator(
```suggestion
abstract class BundleEntryComponentGenerator(
```

2023-07-24 14:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +   * Transform the [LocalChange]s to the final set of changes that needs to be uploaded to the
```suggestion
   * Transforms the [LocalChange]s to the final set of changes that needs to be uploaded to the
```

2023-07-25 07:10 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun createUploadRequestsFromLocalChanges(localChanges: List<LocalChange>): List<UploadRequest>
As I see we are using these 2 APIs one after the other in UploaderImpl. Could we not combine these 2 APIs into 1 ?
If it's needed for probable future work then do you mind kdocing the use-case ?

2023-07-28 10:00 UTC, jingtang10 approved these changes
Thanks @anchita-g - happy for this to be merged but we might have some follow-ups to do.

2023-07-28 10:00 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun getPendingUploadsIndicator(uploadRequests: List<UploadRequest>): Int
Discussed this with @anchita-g. One alternative way of handling this is to make the `UploadWorkManager` a little more stateful, similar to the `DownloadWorkManager`. In that case, there would be an API to feed local changes to the `UploadWorkManager`, there will be an API to pull next upload request to be sent to the FHIR server, and there'll be an API to get the sync status - almost like an iterator with a sync progress.

That would make the job of `Uploader` a little simpler - the while loop currently in `UplaoderImpl` would be simplified (because the work is done by the `UploadWorkManager`. This affords the developers a little more control - but admittedly we're not entirely sure if the additional contronl is urgently needed by the developers.

But that would make the design more alinged with the download workflow which @omarismail94 worked on.

FYI @aditya-07 as well.

2023-07-28 10:21 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun getPendingUploadsIndicator(uploadRequests: List<UploadRequest>): Int
Created an issue https://github.com/google/android-fhir/issues/2103 for this

2023-07-28 10:21 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun createUploadRequestsFromLocalChanges(localChanges: List<LocalChange>): List<UploadRequest>
These APIs will go for refactoring, will write up a proper wiki thereafter

2023-07-31 05:29 UTC, merged