Implement a simple NpmManager
google/android-fhir pull request #2028
Opened 2023-06-07 21:16 UTC by ktarasenko

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1729

**Description**
Introduces a simple way to download Implementation Guides and Knowledge Artifacts from the  NPM package server. 

**Alternative(s) considered**
I spent some amount of time trying to port the [NpmManager from Cqf framework](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cqf-fhir-npm/src/main/java/org/cqframework/fhir/npm/NpmPackageManager.java) to support android, but the amount of work to make the underlying HAPI machinery was more than the actual implementation of the simple NPM client. 
Key difference to Cqf/Hapi solution: 
- The implementation reads files one-by-one and doesn't require keeping the whole NPM package in memory
- hapi NPM client has a long tail of features to support edge cases that might or might not be necessary to communicate to the simple NPM server (searching over the package manager, intensive caching, resolving packages using external indices), For simplicity, most of them were omitted in the implementation, but might be necessary after the extensive testing 

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-06-07 21:23 UTC, ktarasenko commented on knowledge/src/main/java/com/google/android/fhir/knowledge/ImplementationGuide.kt
> +data class ImplementationGuide(val packageId: String, val version: String, val uri: String? = null)
I don't remember why exactly the url was made non-nullable initially, but the most packages in the https://simplifier.net/packages don't have the information about its canonical URL, and they don't have the URL for their dependencies, so it should be made optional with a proper db migration 😞

2023-07-11 14:29 UTC, jingtang10 requested changes

2023-07-11 14:29 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/npm/CacheManager.kt
> +internal class CacheManager(private val cacheRoot: File) {
```suggestion
internal class NpmFileManager(private val cacheRoot: File) {
```

2023-07-11 14:29 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/npm/NpmPackageManager.kt
> +  suspend fun install(implementationGuide: ImplementationGuide): List<NpmPackage> {
```suggestion
  suspend fun getOrInstall(implementationGuide: ImplementationGuide): List<NpmPackage> {
```

2023-07-11 14:29 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +          knowledgeDao.getImplementationGuide(npmPackage.packageId, npmPackage.version)
this check probably can be moved earlier on

2023-07-18 08:13 UTC, omarismail94 commented
@ktarasenko can you resolve the dependency conflict and tag Jing or I when done? We can probably merge this PR!

2023-08-16 10:39 UTC, ktarasenko commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val apacheCommonsCompress =
The alternative will be to use less popular jTar (last change in 2015), but i'd rather stick to commonsCompress. I did the test with proguard, and the difference is ~8kb

2023-09-13 11:01 UTC, aditya-07 reviewed
Added a few comments.

2023-09-13 11:01 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperatorBuilder.kt
>      return this
Should this be renamed to `withDependencies` ?

2023-09-27 13:34 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperatorBuilder.kt
>      return this
i'm going to delete this function since it's not used. also not clear if this is actually the right api to be used by fhir operator.

2023-10-04 14:16 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/db/impl/entities/ImplementationGuideEntity.kt
> +internal fun Dependency.toEntity(rootFolder: File): ImplementationGuideEntity {
wouldn't this trigger db table name change and hence db migration required? we can wait i think.

2023-10-04 14:54 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/Dependency.kt
> +data class Dependency(val packageId: String, val version: String, val uri: String? = null)
i added a link to the spec. also renamed the uri to canonical (because i figured that's what it actually is)

2023-10-04 15:07 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +          packageDownloader.downloadPackage(dependency, PACKAGE_SERVER)
yes. creating a new issue.

2023-10-04 15:34 UTC, aditya-07 approved these changes
LGTM

2023-10-04 16:20 UTC, jingtang10 approved these changes

2023-10-04 16:54 UTC, merged