Implement answerOption initialSelected to set initial value for choice
google/android-fhir pull request #2032
Opened 2023-06-12 17:37 UTC by maimoonak

Fixes #[issue number]

**Description**
Fhir spec allows to add boolean property to set initial selection of answerOptions as defined [here](http://hl7.org/fhir/R5/questionnaire-definitions.html#Questionnaire.item.answerOption.initialSelected) . Also [Rule 11](https://hl7.org/fhir/R5/questionnaire-definitions.html#Questionnaire.item.initial) specifies that "If one or more answerOption is present, initial cannot be present. Use answerOption.initialSelected instead"

**Alternative(s) considered**
Rule specifies to use only one of the property for initial answers. When we are creating responseItem we are setting initial value hence updating answer there.

**Type**
Choose one: (Bug fix | Feature)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-07-19 11:17 UTC, jingtang10 requested changes
Thanks @maimoonak! Great job! 🙏🙏🙏

2023-07-19 11:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +        (initialFirstRep.hasValueQuantity() && initialFirstRep.valueQuantity.value == null))
i'm not actually so sure if this block is needed any more. can you test what happens if we have a quantity without value and how the widgets will behave?

2023-07-19 11:17 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/BehaviorListViewModel.kt
> +    INITIAL_VALUE(
i actually think this should be in widgets, but added as part of the misc components. can you move this there?

2023-07-19 11:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +    .ifEmpty { answerOption.filter { it.initialSelected }.map { it.value } }
can you move up the `ifEmpty` so that you can just call the `it.value` once?

2023-07-24 09:48 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +    "Questionnaire item $linkId has both initial value(s) and has answerOption. See rule que-11 at https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial."
That`s true but we may have people already using initial / initial-expression into existing questionnaires with answerOptions as SDK allowed i and use of initialSelected was not available as an alternate. If we can get a consensus from stakeholders on this then we can float this update. Otherwise it can cause breaking changes if users of SDK do not update their existing questionnaires. 
Let me know how to proceed with it

2023-07-24 11:18 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +    .ifEmpty { answerOption.filter { it.initialSelected }.map { it.value } }
I have removed the ifEmpty as we are already checking that its not possible to have both in same item. However, the ifEmpty can not be moved  above as initial is InitialAnswerComponent and answerOption is AnswerOptionComponent class.

2023-07-24 14:06 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +        (initialFirstRep.hasValueQuantity() && initialFirstRep.valueQuantity.value == null))
`createQuestionResponse should not set answer for quantity type with missing value` tests the behavior. Added the quantity to catalog as well. The output only has a correct quantity if user inputs data into quantity where initial was only to suggest unit

2023-07-25 06:12 UTC, maimoonak commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +        (initialFirstRep.hasValueQuantity() && initialFirstRep.valueQuantity.value == null))
<img width="200" height="400" src="https://github.com/google/android-fhir/assets/4829880/ee4a0e4b-6b7e-41eb-8231-a8e99d764bd6"/>

2023-08-31 09:19 UTC, jingtang10 approved these changes
Thanks @maimoonak - i do have some comments but this PR is good to be merged. Please just address the comments (in some cases just acknowledge them and create todo/issue). Thanks again for the great work! 🎉🙏👍

2023-08-31 09:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemAnswerOptionComponents.kt
> +internal val List<QuestionnaireItemAnswerOptionComponent>.initial: List<Type>
maybe add some unit tests for this one?

2023-08-31 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemAnswerOptionComponents.kt
> +internal val List<QuestionnaireItemAnswerOptionComponent>.initial: List<Type>
can you rename this to initialSelected?

```suggestion
internal val List<QuestionnaireItemAnswerOptionComponent>.initialSelected: List<Type>
```

2023-09-11 16:57 UTC, jingtang10 approved these changes

2023-09-11 16:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemAnswerOptionComponentsTest.kt
> +      this.value = Coding().setCode(code).setDisplay(display).setSystem(url)
```suggestion
      value = Coding().setCode(code).setDisplay(display).setSystem(url)
```

2023-09-11 16:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemAnswerOptionComponentsTest.kt
> +  }
A comment on writing tests: it's much better to write tests in modular ways, meaning:

```
should not select option with initialSelected as null
should not select option with initialSelected as false
should select option with intialSelected as true
should select multiple options with initialSelected as true 
```

in the first 3 test cases, you can just have one single answer option for each test case. and for the last test case, you can have a few answer options, maybe one with initialSelect as null, one as false, and two as true.

the reason is, if, for example, the logic to handle null case is broken, if we had the two test cases in this file, they would both fail, and it's hard to know what's the problem without debugging. but if we had more modular test cases, then you can see that one test case is failing and others are still passing - so you can very easily figure out what the bug is without even debugging.

2023-09-11 16:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +              initialSelected = true
remove this line. this is not necessary.

2023-09-11 16:57 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponentsTest.kt
> +              initialSelected = true
remove this line

2023-09-12 13:54 UTC, jingtang10 approved these changes

2023-09-12 13:54 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemAnswerOptionComponentsTest.kt
> +    assertThat(selectedOptions).isEmpty()
```suggestion

    assertThat(answerOptions.initialSelected).isEmpty()
```

2023-09-12 16:22 UTC, merged