Add support for Answer Options Toggle Extension
google/android-fhir pull request #2034
Opened 2023-06-13 05:26 UTC by LZRS

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1773 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-06-26 04:25 UTC, FikriMilano commented
@LZRS thanks for the PR :D
Is this ready for review?

2023-06-26 11:44 UTC, LZRS commented
> @LZRS thanks for the PR :D
> Is this ready for review?

Yes, it's ready for review

2023-06-27 19:15 UTC, jingtang10 requested changes
Thanks for this change - really good tests and in general high quality code!

The most important comment is my first comment in `QuestionnaireViewItem.kt`. Please take a look and address. I think as a result this will also improve the general code quality of the SDC library. At the moment we're incorrectly handling some answer option logic in the UI code - this should be changed.

Thanks!

2023-06-27 19:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItemTest.kt
> +          extension =
what about using `addExtension` instead of `extension =`

2023-06-27 19:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +      runBlocking(Dispatchers.IO) {
as per my previous comment, this code should live in `QuestionnaireViewModel` - and you won't need to do this awkward `runBlocking` thing.

2023-06-27 19:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItemTest.kt
you should add another test case to show that answer options that don't have an answer options toggle expression for them are included in the enabled answer options.

See this page: https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-answerOptionsToggleExpression.html and this quote: `Any options not listed by one of the answerOptionsToggleExpression occurrences are presumed to be ‘enabled’`

2023-06-27 19:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItemTest.kt
> +  fun `enabledAnswerOption removes answers no longer in allowed answer options evaluated from evaluateAnswerOptionsToggleExpressions`() {
tihs test case should probably only be in `QuestionnaireViewModelTest`.

2023-06-30 13:08 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      }
Oh, for this there was this part of the spec 

> More than one repetition of this extension is possible. If an option appears in more than one repetition, then it will be enabled if it appears in ANY of the extensions whose expressions are evaluated as true. I.e. the expressions that pertain to a given option are treated as 'or'.

See: http://build.fhir.org/ig/HL7/sdc/expressions.html#answerOptionToggleExpression

2023-07-06 13:33 UTC, FikriMilano requested changes
Thanks for the good work! :D
I left a comment.

2023-07-06 13:33 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              )
@LZRS I think you need to also give access to other FHIRPath context e.g. variable extensions, %resource. 

It's important for FHIRPath expression to be able to access other context, so that questionnaire.item can 'communicate' with other items.

You can check the ExpressionEvaluator file, or here's a calculatedExpressions's code for reference:
https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt#L126-L155

fyi @MJ1998, since you're currently working on something similar

2023-07-06 14:18 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              )
Hmm I think it should be working, I have this test checking for that scenario 
https://github.com/google/android-fhir/blob/01728d0165b2d5aab8febb868f3b6bc3361e278b/datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt#L4213

Could you maybe share a sample of the questionnaire you intend to use?

2023-07-06 14:40 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              )
@LZRS can you also add a test that uses variable extension? refer to this questionnaire
https://drive.google.com/file/d/1ZCcS60CzE-EdQawUYbCO8dbxFd2XsiUs/view?usp=sharing

2023-07-06 14:40 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              )
NVM about the %resource, it works as you mentioned.
But the variable extension doesn't works when you use it in the answer option toggle expression

2023-07-11 07:01 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              )
@FikriMilano It should now be working for variable extension expression

2023-07-12 13:07 UTC, FikriMilano approved these changes
Looks great, thanks @LZRS :D

2023-07-12 19:45 UTC, jingtang10 requested changes

2023-07-12 19:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        it.second.filterNot { option -> allowedOptions.any { type -> equals(type, option) } }
can you explain what's going on here?

2023-07-12 19:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    return answerOptions.filterNot { answerOption ->
according to: https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-answerOptionsToggleExpression.html

"Any options not listed by one of the answerOptionsToggleExpression occurrences are presumed to be ‘enabled’"

doesn't this mean that we can simply remove the disabled options from all the options and our job is done? in other words, we don't really need to take into account the allowed options. is this right?

2023-07-12 19:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        it.second.filterNot { option -> allowedOptions.any { type -> equals(type, option) } }
does the spec say anything about if allowed of disallowed options taking precedence?

if not, i'm happy for us to do the simplest thing here.

2023-07-21 08:49 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private fun evaluateAnswerOptionsToggleExpressions(
I've moved most of the functions related to evaluation of answer options to a separate class `EnabledAnswerOptionsEvaluator`

2023-07-21 08:52 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        it.second.filterNot { option -> allowedOptions.any { type -> equals(type, option) } }
Yeah, on this [page](https://build.fhir.org/ig/HL7/sdc/expressions.html#answerOptionToggleExpression) it states that 

> More than one repetition of this extension is possible. If an option appears in more than one repetition, then it will be enabled if it appears in ANY of the extensions whose expressions are evaluated as true. I.e. the expressions that pertain to a given option are treated as 'or'.

2023-07-21 09:43 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    return answerOptions.filterNot { answerOption ->
@jingtang10 Yes, although we may have to take into account disabled options that are also included in enabled options. According to https://build.fhir.org/ig/HL7/sdc/expressions.html#answerOptionToggleExpression
>If an option appears in more than one repetition, then it will be enabled if it appears in ANY of the extensions whose expressions are evaluated as true. I.e. the expressions that pertain to a given option are treated as 'or'.

2023-07-21 10:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnabledAnswerOptionsEvaluator.kt
enablement package is for enableWhen evaluation (maybe it should just be renamed to enablewhen but let's do that another time) - let's keep this class out of it.

i would advocate for creating a new package called expressions.

i really like what you've done with this class though - nicely packaged class with a single public function.

2023-07-21 10:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>              .also { detectExpressionCyclicDependency(questionnaire.item) }
can you remove the two `.also` calls below if you're only creating an empty questionnaire state to begin with?

2023-07-21 10:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  object InitMode : DisplayMode()
i'm nervous about this, but also curious why this works. have you tested sufficiently this doesn't break questionnaire initialization?

can you add documentation to say why this is needed?

does this mean we always did more work than necessary when initializing the questionnaire?

2023-07-21 10:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        it.second.filterNot { option -> allowedOptions.any { type -> equals(type, option) } }
got it - thanks

2023-07-21 14:36 UTC, jingtang10 commented
@omarismail94 @FikriMilano I want to bring this PR to your attention too. @LZRS managed to remove one call to initialize the questionnaire state - I wonder if this PR would have a positive impact on the performance. Can you two take a look at this?

Thanks
Jing

2023-07-21 14:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          initialValue =
@yigit is this right? this seems to work for us and is possibly a big improvement gain for us as at the moment it looks like we're doing initialization twice... is the initial state flow value ever useful?

2023-07-24 14:08 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  object InitMode : DisplayMode()
I tested using the demo and catalog app, that questionnaires are initialized correctly and also ran local unit tests to ensure they were not broke.

Yeah, the questionnaire state was being loaded twice in the `initial` and also when `questionnaireStateFlow` is collected since all the flows in the combine() have default initial states. The `questionnaireStateFlow` is only accessed by collection in the `questionnaireFragment` which essentially made an unnecessary getQuestionnaireState call on initial=, since the flow would also emit on initial collection.

2023-07-24 14:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  object InitMode : DisplayMode()
thanks for this

2023-07-24 20:36 UTC, LZRS commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              ),
The `answersDisabledCallback ` is used when a previously selected answers in the questionnaireResponse becomes disabled and are no longer in the enabledAnswerOptions. It  removes the disabled answers that are no longer valid in the questionnaireResponse. Some answers may become invalid on re-evaluation of answerOptionsToggle expressions

2023-07-25 13:56 UTC, jingtang10 requested changes

2023-07-25 13:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              ),
wait hang on - great catch @MJ1998... @LZRS what if instead of passing the callback, we simply remove answers that are not enabled after the calculation. i think having this callback passed into the evaluator is a bit strange.

2023-07-26 10:56 UTC, jingtang10 approved these changes

2023-07-26 11:16 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/expressions/EnabledAnswerOptionsEvaluator.kt
> +   * Returns allowed answer options that are enabled based on the evaluation of
Can you update the kdoc what this function is returning ?

2023-07-26 11:16 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/expressions/EnabledAnswerOptionsEvaluator.kt
> +  internal suspend fun evaluate(
Also this function could be renamed? At first, I thought its evaluating enabled answer options only.

2023-07-26 11:16 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
I don't understand why we need to invoke `answersChangedCallback` in `removeDisabledAnswers` when constructing the QuestionnaireViewItems. Infact why do we even need fn:`removeDisabledAnswers`..

Correct me if I am wrong. What I think `enabledAnswerOptions` mean is that we calculate a set of enabled-answer-options based on `toggleAnswerOptionExpression`  (by filtering from all possible answer options). Then we can simply pass this list to the QuestionnaireViewItem. Upon change in answer, answersChangedCallback is invoked by the QuestionnaireViewItem which will update the enabledAnswerOptions.

2023-07-26 12:16 UTC, jingtang10 approved these changes
thanks for this - just a really small comment otherwise good to merge

2023-07-27 00:29 UTC, merged