Fix Date/DateTime indexes to speed up Left joins on Search
google/android-fhir pull request #2047
Opened 2023-06-26 12:44 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2040

**Description**
Clear and concise code change description. 

In the Search API, we perform a LEFT JOIN when sorting:

```
LEFT JOIN ${sortTableName.tableName} $tableAlias
      ON a.resourceType = $tableAlias.resourceType AND a.resourceUuid = $tableAlias.resourceUuid AND $tableAlias.index_name = ?
```

this join uses the resourceType, resourceUuid and index_name columns. To speed this up, we should create a composite index made up of these 3 columns

TESTED:
Downloaded 7000 households. Opened App Inspector and ran query generated. Returned results almost instantaneously as opposed to many seconds 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-06-29 12:29 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +  version = 4,
Since version 3 is not released yet, we can keep that version and add the migration as a step in MIGRATION_2_3 itself.

2023-07-04 12:40 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +  version = 4,
Reverted

2023-07-04 13:55 UTC, jingtang10 requested changes

2023-07-04 13:55 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +        "CREATE INDEX IF NOT EXISTS `index_DateTimeIndexEntity_resourceType_index_name_resourceUuid_index_from_index_to` ON `DateTimeIndexEntity` (`resourceType`, `index_name`, `resourceUuid`, `index
i think this needs to change.

the way migration works is that, if you're on db version n, the migration code would be run to migrate your db schema from n to n+1.

this means you should NOT modify existing migration code - people already on v3 would not get your new db index!

you should create a new version, and write another migration step to handle 3 to 4.

2023-07-04 13:56 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +        "CREATE INDEX IF NOT EXISTS `index_DateTimeIndexEntity_resourceType_index_name_resourceUuid_index_from_index_to` ON `DateTimeIndexEntity` (`resourceType`, `index_name`, `resourceUuid`, `index
@aditya-07 fyi since aditya added migration code to begin with.

2023-07-04 14:02 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +        "CREATE INDEX IF NOT EXISTS `index_DateTimeIndexEntity_resourceType_index_name_resourceUuid_index_from_index_to` ON `DateTimeIndexEntity` (`resourceType`, `index_name`, `resourceUuid`, `index
@jingtang10 DB version in the latest released engine library is 2. DB version 3 was added for a new change and hasn't been released via the library.

2023-07-04 14:06 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +        "CREATE INDEX IF NOT EXISTS `index_DateTimeIndexEntity_resourceType_index_name_resourceUuid_index_from_index_to` ON `DateTimeIndexEntity` (`resourceType`, `index_name`, `resourceUuid`, `index
sure - but as far as i know @khyativyasargus, @nsabale7, @dubdabasoduba fork our libs... I know theoretically we're not making promises in between releases, but i don't really see the downside of creating another migration step.

2023-07-04 14:32 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/db/impl/ResourceDatabase.kt
> +        "CREATE INDEX IF NOT EXISTS `index_DateTimeIndexEntity_resourceType_index_name_resourceUuid_index_from_index_to` ON `DateTimeIndexEntity` (`resourceType`, `index_name`, `resourceUuid`, `index
I reverted to how I have it but for some reason GitHub hated me doing that on this PR and the change is not getting picked up here. 

Created a new PR: https://github.com/google/android-fhir/pull/2063 that has the migration to a new version

2023-07-04 14:48 UTC, closed without merging