Add drop down support to sdc
google/android-fhir pull request #209
Opened 2021-02-02 12:09 UTC by joiskash

#153

2021-02-02 21:31 UTC, jingtang10 requested changes
Great work @joiskash! Thanks so much!

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +        assertThat(viewHolder.itemView.findViewById<AutoCompleteTextView>
nit: add new line

also generally add a new line between the action to be tested and the assertions for all the test cases.

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
> +        />
nit: pull up

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
> +    android:id="@+id/dropdown_menu"
nit: can we name this exposed_dropdown_menu and the AutoCompleteTextView below auto_complete_text_view or something similar?

just trying to avoid two ids being too similar so that we don't cause bugs inadverdently.

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_list.xml
> +    android:padding="16dp"
add this value to the dimens.xml file

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
> +    fun getResponseAnswerValueX_ShouldReturnAnswerValueCoding() {
add a test case for the exception

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
> +    fun getString_choiceItemType_answerOptionShouldReturnValueCoding() {
add a test case where there isn't display value set

and add another test case for the exception

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +                }
```suggestion
                val answerOptionString = this.questionnaireItemViewItem.questionnaireItem.answerOptionList.map {
                    it.getDisplayString()
                }
```

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +                QuestionnaireResponse.Item.newBuilder().addAnswer(0,
can you use the version of `addAnswer` that doesn't take an index?

2021-02-02 21:31 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +@RunWith(AndroidJUnit4::class)
are you able to test the click behaviour in this class?

if not, please create an issue. (i had problems testing dialogs in the date and date time types).

2021-02-02 21:35 UTC, jingtang10 requested changes

2021-02-02 21:35 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
> +        android:id="@+id/exposed_dropdown_menu"
nit: rename to `auto_complete` or `text_view`.

just trying to avoid two ids being too similar so that we don't cause bugs inadverdently.

2021-02-03 09:05 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +        var MINIMUM_NUMBER_OF_ITEMS_FOR_DROP_DOWN = 4
I left as var thinking maybe the user of this SDK may want to override this

2021-02-03 09:29 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    }
why would the extensions be single or null? There may be more than one extension, we only care about itemControl

2021-02-04 13:01 UTC, jingtang10 reviewed
Thanks @joiskash

Looks good! Just a few more minor comments. Thanks!

2021-02-04 13:01 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +    fun shouldSetAutoTextureViewEmptyIfAnswerNull() {
the test names in this file seem strange: AutoCompleteTextView rather than AutoTextureView?

2021-02-04 13:30 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +    fun shouldSetAutoTextureViewEmptyIfAnswerNull() {
oh my bad was working with AutoTexture view in another project :p

2021-02-04 13:44 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +@RunWith(AndroidJUnit4::class)
Sure let me create an issue

2021-02-04 14:27 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +        }
Should this be moved to the init of QuestionnaireViewModel? considering that every time we call the extension we iterate over  the list of extensions.

2021-02-04 15:12 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +@RunWith(AndroidJUnit4::class)
done

2021-02-04 15:13 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +        }
done

2021-02-04 15:23 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ItemControlTypeConstants.kt
> +object ItemControlTypeConstants {
done

2021-02-04 15:23 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
> +    @Test(expected = IllegalArgumentException::class)
done

2021-02-04 15:23 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +    fun shouldSetAutoTextureViewEmptyIfAnswerNull() {
done

2021-02-04 15:29 UTC, joiskash commented
Thanks for the comments @jingtang10, I have addressed them all in the last few commits. Please do review the PR again

2021-02-05 23:16 UTC, jingtang10 reviewed
please resolve the conflicts

2021-02-05 23:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensions.kt
> +        return null
does this work?

```suggestion
        this.extensionList.firstOrNull {
            it.url.value == EXTENSION_ITEM_CONTROL_URL
        }?.value?.codeableConcept?.codingList?.firstOrNull {
            it.system.value == EXTENSION_ITEM_CONTROL_SYSTEM
        }?.code?.value
```

2021-02-05 23:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +        val questionnaireViewItem = questionnaireItemViewItemList[position]
`questionnaireItemViewItem`

2021-02-05 23:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +        if (questionnaireViewItem.questionnaireItem.itemControl.equals(
use `==` instead of `.equals`

they're the same in kotlin but `==` is more concise

2021-02-05 23:16 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
> +    android:hint="">
remove the empty attribute

2021-02-05 23:16 UTC, jingtang10 commented on deps.gradle
>  kotlin.plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
while we're here, can you swap these two lines so they're ordered alphabetically? thanks!

2021-02-05 23:16 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensionsTest.kt
> +    fun getItemControl_shouldReturnNull() {
you need to hit the other case where the url is right but the coding isn't right.

so the naming of the test cases should be 

```
itemControl_shouldReturnItemControlCode
itemControl_wrongExtensionUrl_shouldReturnNull
itemControl_wrongExtensionCoding_shouldReturnNull
```

2021-02-05 23:16 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +    }
nit on line breaks:

```suggestion
        assertThat(
            viewHolder.itemView.findViewById<AutoCompleteTextView>(R.id.auto_complete)
                .adapter
                .getItem(0)
                .toString()
        ).isEqualTo("test-code")
    }
```

2021-02-05 23:18 UTC, jingtang10 reviewed
thanks!

2021-02-08 06:26 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensions.kt
> +        return null
@jingtang10 there can be more than one extension. It is not compulsory that the first one is an item-control, so wouldn't you have to go through the list?

2021-02-08 06:39 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +    fun shouldSetAutoTextureViewEmptyIfAnswerNull() {
yes sorry done now.

2021-02-08 09:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensions.kt
> +        return null
firstOrNull is a function that finds the first item in the list that satisfies your criterion. So it's like a filtering function.

2021-02-08 09:20 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensions.kt
> +        return null
oh thats cool let me test your suggestion and commit it

2021-02-08 09:37 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +    fun shouldthrowErrorForAnswerOptionWithoutCoding() {
```suggestion
    fun shouldThrowErrorForAnswerOptionWithoutCoding() {
```

2021-02-08 09:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
nit: remove new line

2021-02-08 09:37 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +            questionnaireItem.answerOptionCount >
this should be >=

the documentation below indicates this should be >= as well.

2021-02-08 09:37 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    @Test
add test case where drop down is returned because item count >= 4

2021-02-08 11:28 UTC, jingtang10 approved these changes
👌

🎉🎉🎉

2021-02-08 14:07 UTC, merged