Support multiple instructions.
google/android-fhir pull request #2098
Opened 2023-07-26 06:08 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2092 

**Description**
It was only showing first instructions.
Now, changes are updated to show all instructions by separator `\n`.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-07-26 06:35 UTC, santosh-pingle commented
<img width="441" alt="Screenshot 2023-07-26 at 12 03 42 PM" src="https://github.com/google/android-fhir/assets/86107848/7f6b15bc-d6b8-45e1-92ca-4448b83cab06">

2023-07-26 12:51 UTC, jingtang10 requested changes
thanks for the quick work!

2023-07-26 12:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +val List<Questionnaire.QuestionnaireItemComponent>.localizedInstructionSpannedList: List<Spanned?>
can you change line 322 above to use `filter` and then add `.joinToString(separator = "\n")` to that function. so that you're not changing the caller code?

but you will nded to update the kdoc.

2023-07-26 12:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +val List<Questionnaire.QuestionnaireItemComponent>.localizedInstructionSpannedList: List<Spanned?>
and you'll need to change the test case (or create a new test case) to test the multiple instructions case.

but then you can revert the change in `GroupHeaderViewTest.kt` and `HeaderViewTest.kt`.

2023-07-27 17:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +val List<Questionnaire.QuestionnaireItemComponent>.localizedInstructionSpannedList: List<Spanned?>
done.

2023-08-02 17:32 UTC, jingtang10 approved these changes
Thanks @santosh-pingle! Happy to approve this.

But proposing one change - please address before merging.

2023-08-02 17:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +        .joinTo(this, "\n")
```suggestion
        .joinTo(this, separator)
```

2023-08-03 06:05 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +val List<Questionnaire.QuestionnaireItemComponent>.localizedInstructionsSpanned: Spanned
done.

2023-08-03 06:05 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +        .joinTo(this, "\n")
done.

2023-08-03 07:14 UTC, merged