Make UploaderImpl an iterator
google/android-fhir pull request #2115
Opened 2023-08-03 16:46 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2103

**Description**
Clear and concise code change description. 

* Refactored Uploader so that it functions as an interator
* UploadWorkManager is responsible for chunking out the list of local changes into a list of lists, with each element being a set to upload
* UploadWorkManager responsible for creating the upload request from a given set of local. changes to upload

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | **Code health** | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-08-09 11:41 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun createNextRequest(localChanges: List<LocalChange>): UploadRequest
Do you wanna change this to getNextRequest like in DownloadWorkManager ?

2023-08-09 11:41 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun chunkLocalChanges(localChanges: List<LocalChange>): List<List<LocalChange>>
It's possible that some local changes are dropped in the application specific UploadWorkManagerImpl.
Are we relying on the application to handle this ?
Otherwise, those changes remain in the database for eternity.

2023-08-10 09:11 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
> +  fun chunkLocalChanges(localChanges: List<LocalChange>): List<List<LocalChange>>
This is true and I should factor that in. Thanks!

2023-08-10 12:12 UTC, jingtang10 requested changes

2023-08-10 12:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/UploadWorkManager.kt
is it possible to actually implement the Iterator interface? Or at least change the function signatures so that it is possible to implement it?

2023-09-14 09:03 UTC, closed without merging