Handle local insert-delete sequence as no-op when squashing
google/android-fhir pull request #2133
Opened 2023-08-14 15:52 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1951, #2031 

**Description**
Clear and concise code change description. 

  *  Introduced a new Type.NO_OP to represent no-operation actions.
   *  Modified the mergeLocalChanges function to recognize a local insert followed by a delete, converting the sequence into a Type.NO_OP.
   *  Added error handling for unexpected usage of Type.NO_OP within the merge context.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

PR #2111

**Type**
Choose one: (**Bug fix** | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-08-14 17:45 UTC, jingtang10 requested changes

2023-08-14 17:45 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt
> +        Type.NO_OP -> null
shouldn't this never happen?

so throw an exception? and keep the type non-null?

2023-08-14 17:45 UTC, jingtang10 commented
thanks for this fix Omar! 👍🙏

2023-08-15 08:00 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/TransactionBundleGenerator.kt
> +        Type.NO_OP -> null
yes, you are right. updated the code to reflect that

2023-08-15 15:43 UTC, jingtang10 approved these changes

2023-08-15 15:55 UTC, merged