Add a LocalChangeSelector
google/android-fhir pull request #2135
Opened 2023-08-15 15:07 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-08-16 10:18 UTC, jingtang10 commented
updated title after discussion

2023-08-30 06:16 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt
> +  override suspend fun upload(localChangeFetcher: LocalChangeFetcher): Flow<UploadState> = flow {
Should we make this function just take in a ` List<LocalChange>` only. The syncUpload could be expected to iterate over the `LocalChangeFetcher` iterator and pass in the next state of changes

2023-09-07 12:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt
> +  override suspend fun upload(localChangeFetcher: LocalChangeFetcher): Flow<UploadState> = flow {
Great suggestion! Implemented

2023-09-08 05:11 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +interface LocalChangeFetcher {
Should the interface be internal as well?

2023-09-08 05:14 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  class AllChanges(val pageSize: Int) : FetchMode()
We are not utilising the `pageSize` argument while creating the fetcher object for this. Should we add it as an argument in the `AllChangesLocalChangeFetcher` constructor.

2023-09-08 05:20 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    fetchMode: FetchMode,
Should we call this `LocalChangesFetchMode`.
IMO, `FetchMode` is not able to convey the implication clearly.

2023-09-08 10:43 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  class AllChanges(val pageSize: Int) : FetchMode()
i deleted the page size variable as we do not currently have a database API to fetch N changes per call

2023-09-08 10:43 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +interface LocalChangeFetcher {
done

2023-09-08 10:43 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    fetchMode: FetchMode,
changed

2023-09-08 14:51 UTC, jingtang10 requested changes

2023-09-08 14:51 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      println(it.first())
println?

2023-09-08 14:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  suspend fun getProgress(): Double
kdoc for internal apis

2023-09-08 14:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  override suspend fun getProgress(): Double = database.getAllLocalChanges().size.toDouble()
the implementation here seems to be returning total instead of progress?

2023-09-08 14:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> + * Defines the contract for fetching local changes.
try to reduce boiler plate langauge:

```suggestion
 * Fetches local changes.
```

2023-09-11 10:11 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  override suspend fun getProgress(): Double = database.getAllLocalChanges().size.toDouble()
fixed, and I added tests for it

2023-09-12 13:25 UTC, jingtang10 requested changes

2023-09-12 13:25 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  override suspend fun getProgress(): Double =
i think - even as internal apis, it would be beneficial to simply expose the raw data instead of trying to calculate this and return a double... the caller may wish to further aggregate / calculate / present the progress data. it doesn't lose anything to just pass on the done and total numbers.

2023-09-13 15:38 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +  override suspend fun getProgress(): Double =
added a ProgressState data class to capture the remaining and initial count

2023-09-14 10:39 UTC, jingtang10 requested changes
thanks omar - this is great.

only blocking change is in fhir engine impl. other comments optional and can create follow ups.

2023-09-14 10:39 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    upload(localChangeFetcher.next()).collect {
wait - shouldn't there be a loop using `hasNext` as condition?

2023-09-14 10:39 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +data class ProgressState(
we will end up having a lot of progress classes. just to make this clear:

```suggestion
data class FetchProgress(
```

2023-09-14 10:39 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +      val totalLocalChangeCount = database.getAllLocalChanges().size
slightly uneasy about this being in here. optionally:

1) can we open up another db api to return only the count?
2) is it possible to move this to the implementations (e.g. create another intialize() method)? if this is here, can you comment on the fact that this is retrieved once and never updated? (we might end up with returning progress that's >100% ?)

2023-09-14 13:01 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    upload(localChangeFetcher.next()).collect {
fixed

2023-09-14 13:12 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +
can you rename these test cases so they can be lexicographically together?

i.e.

getLocalChangesCount_noLocalChange_reutrnsZero
getLocalChangesCount_oneLocalChange_reutrnsOne
getLocalChangesCount_twoLocalChange_reutrnsTwo

2023-09-14 13:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +          AllChangesLocalChangeFetcher(database).apply { initTotalCount() }
so now the interface needs to know about the particular implemetation to intiialise...

what i was suggesting was for initialize to become an interface function.

2023-09-14 15:11 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangeFetcher.kt
> +   * total to upload
```suggestion
   * Returns [FetchProgress], which contains the remaining changes left to upload and the initial
   * total to upload.
```

2023-09-14 16:24 UTC, merged