Add ResourceConsolidator
google/android-fhir pull request #2137
Opened 2023-08-17 09:13 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2103

**Description**
Clear and concise code change description. 

The resource consolidator would handle any post-processing that needs to be made to the database. Examples of this would be, updating the lastUpdated timestamp field, or deleting the local change from the database, or updating the resource IDs and payloads to correspond with the server’s feedback.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-08-18 05:32 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
>      val localChanges = database.getAllLocalChanges()
We would have to modify the fetcher as well based on the upload mode

2023-08-18 05:34 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt
> +    localChanges: List<LocalChange>,
Would we not need `UploadMode` here to decide how to create patches of request and request builder.

2023-08-18 09:07 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt
> +    localChanges: List<LocalChange>,
I didn't add the patch and request builder as they have yet to be created. In the future, the upload function would look like this:

```
override suspend fun upload(localChangeFetcher: LocalChangeFetcher, patchGenerator: PatchGenerator, requestBuilder: RequestBuilder, resourceConsolidator: ResourceConsolidator): Flow<UploadState>
```

determining what to pass into the `upload` function based on UploadMode can be done either in the FhirSynchronizer, or in FhirEngineImpl.syncUpload. For the latter, it is for interfaces whose initialisation relies on variables that are only accessible from FhirEngine, such as `Database`

2023-09-07 14:29 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploaderImpl.kt
> +    localChanges: List<LocalChange>,
Obsolete now as I removed UploadMode from this PR

2023-09-08 14:56 UTC, jingtang10 requested changes

2023-09-08 14:56 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    consolidatorMode: ConsolidatorMode,
this is unfortuantely glossed over in our previous discussions. do we really need a consolidator mode? or maybe one consolidator is enough? the same consolidator can clear the local changes and update resource id if needed?

2023-09-11 06:58 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +  override suspend fun consolidate(localChangeToken: LocalChangeToken, response: Resource) {
Will the information from the `localChangeToken` be enough to perform resource consolidation in more complex cases like ID updation, I was thinking there needs to be some kind of indicator for if the changes were at a per resource level, or were they POST changes, was the request a bundle?

2023-09-12 10:46 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +    consolidatorMode: ConsolidatorMode,
I thought about this, and I think one consolidator should be enough. Within the default consolidator, we could have when statements based on the HTTP verb

2023-09-12 10:48 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +  override suspend fun consolidate(localChangeToken: LocalChangeToken, response: Resource) {
I think it should be? If it isn't, it should be able to figure out the consolidation by querying the database (that could come at a performance cost)

2023-09-14 10:48 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +/** Represents a mechanism to consolidate resources after they are uploaded. */
this kdoc can probably be enriched a bit - why do we have this? what is this class actually gonna do? any edge cases?

2023-09-14 14:30 UTC, merged