use preference datastore to monitor syncJobStatus.
google/android-fhir pull request #2142
Opened 2023-08-23 08:36 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-08-23 08:44 UTC, santosh-pingle commented
https://github.com/google/android-fhir/assets/86107848/f174041d-545b-4b16-ab6e-a1c0bca19a81

2023-08-29 12:00 UTC, santosh-pingle commented
combine workstate and syncjobstatus 


https://github.com/google/android-fhir/assets/86107848/edea03f7-6302-42c9-99d9-4090f0cdee4e

2023-08-30 13:01 UTC, jingtang10 requested changes

2023-08-30 13:01 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
> +        context = ApplicationProvider.getApplicationContext()
```suggestion
        context = ApplicationProvider.getApplicationContext(),
```

2023-08-30 13:01 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
> +        context = ApplicationProvider.getApplicationContext()
```suggestion
        context = ApplicationProvider.getApplicationContext(),
```

2023-08-30 13:01 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    //    Cancels any ongoing sync job before starting a new one. Since this function may be called
```suggestion
    // Cancels any ongoing sync job before starting a new one. Since this function may be called
```

2023-08-31 06:04 UTC, anchita-g requested changes

2023-08-31 06:04 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +        val uniqueWorkerName = inputData.getString(PREFERENCES_DATASTORE_STRING_KEY)!!
Could this be "PREFERENCES_DATASTORE_KEY"

2023-09-06 08:07 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +private const val FHIR_PREFERENCES_NAME = "fhir_preferences"
Kotlin does not have the 'static' keyword, but this is equivalent to the 'static' keyword in Java.

2023-09-06 08:11 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +private const val FHIR_PREFERENCES_NAME = "fhir_preferences"
I am sorry I mean in the companion object

2023-09-06 08:48 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +data class SyncJobStatusPreferences(
done.

2023-09-06 08:48 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +          val stateType = data.getString("StateType")
done.

2023-09-06 08:49 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +private const val FHIR_PREFERENCES_NAME = "fhir_preferences"
ok.

2023-09-06 08:50 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    //    Cancels any ongoing sync job before starting a new one. Since this function may be called
done.

2023-09-06 08:51 UTC, santosh-pingle commented on engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
> +        context = ApplicationProvider.getApplicationContext()
done.

2023-09-06 08:51 UTC, santosh-pingle commented on engine/src/test/java/com/google/android/fhir/FhirEngineProviderTest.kt
> +        context = ApplicationProvider.getApplicationContext()
done.

2023-09-06 08:51 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  var state: WorkInfo.State? = null
done.

2023-09-06 08:51 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        context = applicationContext
done.

2023-09-06 11:30 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +)
In my view, we allow the API to publish two separate states instead of a combined enumeration or sealed class. The reason for this is that the states for PeriodicSync and OneTimeSync are distinct.

PeriodicSync doesn't have a final or terminal state, whereas OneTimeSync does. In OneTimeSync, we have final states like "succeeded," "failed," and "cancelled."

If we were to introduce a combined state, there might be a risk of missing some states when mapping from one state to another. This could make it more challenging to handle and understand the different sync states. Therefore, keeping them as separate states can be clearer and more straightforward.

For example, in OneTimeSync, after reaching a terminal state, there won't be any scheduling for the next job. However, in PeriodicSync, we only have two states, which are "Running" and "Enqueued."

2023-09-06 12:08 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    oneTimeSynjob?.cancel()
Actually, it doesn't cancel the FHIR sync job because the oneTimeSync request is configured with ExistingWorkPolicy.KEEP.

Actually, I added this check because I observed that every time a user clicks on manual sync, it introduces a new coroutine where each one collects the same data and emits the same data to the view.

2023-09-06 12:57 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +)
but maybe we should have two different enums/sealed classes for period sync state and one time sync state?

2023-09-15 06:12 UTC, MJ1998 commented
Perhaps add #2046 getting resolved by this too ?

2023-10-04 06:58 UTC, MJ1998 requested changes

2023-10-04 06:58 UTC, MJ1998 commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        context = applicationContext,
We should not store context in FhirEngineConfiguration.
Once the FhirDataStore is created we do not need this and it can lead to memory leaks.

2023-10-04 06:58 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  @PublishedApi @Synchronized internal fun getFhirDataStore() = fhirDataStore
By doing following you can eliminate storing context in FhirEngineConfiguration
1. Pass context in this API 
2. Store FhirDataStore in FhirServices


```suggestion
  @PublishedApi @Synchronized internal fun getFhirDataStore(context: Context): FhirDataStore {
    return getOrCreateFhirService(context).fhirDataStore
  }
```

2023-10-04 06:58 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +          fhirDataStore?.updateSyncJobStatus(
Ok so we persist each status. Nice!

2023-10-04 06:58 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return if (syncJobStatusFlow != null) {
When will this flow be null ?

2023-10-04 08:49 UTC, anchita-g commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    oneTimeSyncJob?.cancel()
Why is this cancellation required? Should we not enqueue the incoming job instead?

2023-10-04 08:53 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +internal class FhirDataStore(context: Context) {
we already have a datastore in `DatastoreUtil`. Can you utilise that or move the functions from there to here?

2023-10-04 08:53 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +          }
* do we log the exceptions any where?
* why do we distinguish between IOExceotion and other types of exceptions

2023-10-04 08:53 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +            stateData?.let { gson.fromJson(stateData, Class.forName(type)) as? SyncJobStatus }
Can we introduce a whitelisting mechanism to ensure only known `SyncJobStatus` types are deserialized:

```
private val allowedSyncJobStatusPackages = listOf("org....syncStatus1", "org.....syncStatus2")

private fun String.isAllowedClass(): Boolean {
    return allowedSyncJobStatusPackages.any { this.startsWith(it) }
}

internal fun getSyncJobStatusPreferencesFlow(key: String): Flow<SyncJobStatus> =     syncJobStatusFlowMap.getOrPut(key) {
// code

        if (stateType?.isAllowedClass() == true) {
            stateData?.let { gson.fromJson(it, Class.forName(stateType)) as? SyncJobStatus }
        } else null
```

2023-10-04 08:56 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  internal fun getSyncJobStatusPreferencesFlow(key: String): Flow<SyncJobStatus> =
Should we remote `Preferences` from the function name?

2023-10-05 07:06 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +          }
If an error is encountered while reading data, I add fallback behavior; for any other exceptions, I simply rethrow them.

2023-10-05 07:26 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    oneTimeSyncJob?.cancel()
https://github.com/google/android-fhir/pull/2142#discussion_r1310009122

2023-10-05 07:32 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    oneTimeSyncJob?.cancel()
https://github.com/google/android-fhir/issues/2191

2023-10-05 11:04 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class OneTimeSyncState {
Did you mean`SyncState` ?

2023-10-05 11:39 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return if (syncJobStatusFlow != null) {
It should not be null, let me check, thanks!

2023-10-05 11:40 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +          }
do we log the exceptions any where? -> I need to check, thanks!

2023-10-05 11:41 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class OneTimeSyncState {
Yes, I have to clean up the code.

2023-10-10 05:44 UTC, santosh-pingle commented
I am currently updating the design document based on the comments provided by the reviewer in the design. Afterward, I will incorporate these changes into the pull request. Following that, I will address the review comments in the current PR accordingly. Thank you.

2023-10-30 06:09 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  internal fun getSyncJobStatusPreferencesFlow(key: String): Flow<SyncJobStatus> =
done.

2023-10-30 06:09 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class OneTimeSyncState {
done.

2023-10-30 06:09 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +            stateData?.let { gson.fromJson(stateData, Class.forName(type)) as? SyncJobStatus }
done.

2023-10-30 06:09 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +          }
done.

2023-10-30 06:10 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +internal class FhirDataStore(context: Context) {
done.

2023-10-30 06:10 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return if (syncJobStatusFlow != null) {
done.

2023-10-30 06:10 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  internal fun combineSyncJobStatusAndWorkInfoState(
doen.

2023-10-30 06:10 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  @PublishedApi @Synchronized internal fun getFhirDataStore() = fhirDataStore
done.

2023-10-30 06:10 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        context = applicationContext,
done.

2023-10-30 06:11 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      .flatMapConcat { it.asFlow() }
done.

2023-11-10 18:13 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  private val gson =
can we have an intenral data class to encapsulate the serialization and deserialization of the SyncJobStatuses?

```
internal class SyncJobStatusSerializer {
    private val gson = GsonBuilder()
        .registerTypeAdapter(OffsetDateTime::class.java, OffsetDateTimeTypeAdapter().nullSafe())
        .setExclusionStrategies(FhirSyncWorker.StateExclusionStrategy())
        .create()

    fun deserialize(data: String): SyncJobStatus? {
        return gson.fromJson(data, SyncJobStatus::class.java)
    }

    fun serialize(syncJobStatus: SyncJobStatus?): String {
        return gson.toJson(syncJobStatus)
    }
}
```

that we initialize here:
```suggestion
   private val serializer = SyncJobStatusSerializer()
```

2023-11-10 18:14 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +        .map { statusData -> gson.fromJson(statusData, Data::class.java) }
why do we always use map? should we not be getting only one value? is it possible to get multiple?

2023-11-10 18:15 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      combine(syncJobProgressStateFlow, syncJobTerminalStateFlow) { inprogress, terminal,
nit
```suggestion
      combine(syncJobProgressStateFlow, syncJobTerminalStateFlow) { inProgress, terminal,
```

2023-11-10 18:16 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    syncJobIntermediateState: SyncJobStatus,
how about:
```suggestion
    currentSyncJobStatus: SyncJobStatus,
```

2023-11-16 06:43 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +
Some of the code is moved from another file, as a response to an earlier review request. I might follow that convention to avoid any surprises, but I will thoroughly check this.

2023-11-16 06:43 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +        .map { statusData -> gson.fromJson(statusData, Data::class.java) }
let me check.

2023-11-21 07:39 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    syncJobIntermediateState: SyncJobStatus,
done.

2023-11-21 07:40 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      combine(syncJobProgressStateFlow, syncJobTerminalStateFlow) { inprogress, terminal,
done.

2023-11-21 07:40 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +        .map { statusData -> gson.fromJson(statusData, Data::class.java) }
done.

2023-11-21 07:40 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  private val gson =
done.

2023-11-21 07:40 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +            emit(emptyPreferences())
done.

2023-11-21 07:41 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +
done.

2023-11-21 07:41 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class SyncState {
done.

2023-11-21 07:45 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +)
done.

2023-11-27 14:49 UTC, omarismail94 commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +    oneTimeSyncJob?.cancel()
Do we not handle this now by running `cancel()` in the `FhirSyncWorker` class? Do we still need this call here

2023-11-27 16:28 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +          is SyncJobStatus.Started,
do we still need `SyncJobStatus.Started`. I think the object can be dropped from the code

2023-11-27 16:28 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +            else -> {
can we be explicit and list all the SyncJonStatus'? if we remove the need for `Started`, change this to `is SyncJobStatus.InProgress`

2023-11-27 16:28 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +              fhirDataStore.updateSyncJobTerminalState(uniqueWorkerName)
why do we rely on setting the syncjobstatus as null to do this. can we do it in a safer manner?

2023-11-28 11:31 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  internal fun combineSyncStateForOneTimeSync(
If I remove @PublishedApi internal and update private as acess specifier then it gives error 
``` Public-API inline function cannot access non-public-API 'private final fun combineSyncStateForOneTimeSync(context: Context, workName: String, syncJobProgressStateFlow: Flow<SyncJobStatus>, uuid: UUID): Flow<SyncState> defined in com.google.android.fhir.sync.Sync'```

2023-11-28 13:10 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +          is SyncJobStatus.Started,
Is it acceptable if we do not skip it and instead include it as part of the Running state? Alternatively, should we create a new sync state, a combination of (WorkInfo.Running, SyncJobStatus.Started) = SyncState.Started? If we choose to skip it, is it worth keeping SyncJobStatus.Started altogether?

2023-11-29 06:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +            else -> {
Do you mean to remove the object Started : SyncJobStatus() state from SyncJobStatus? If it is not removed, then it has to be mentioned as an explicit case to avoid the else case.

2023-11-30 06:04 UTC, santosh-pingle commented
> I made some comments. Importantly, have you tested that these changes worked? I just checked out the PR and when I ran it on my device, it immeadiatly crashed with:
> 
> ```
> java.lang.NullPointerException: Parameter specified as non-null is null: method com.google.android.fhir.sync.Result$Failed.<init>, parameter exceptions
> ```
> 
> Can you double check that the changes dont cause a regression?

I have tried several times, and I did not encounter any crashes. I was able to perform periodic sync and one-time sync successfully. I managed to upload local data to the remote server, and I was also able to download updates on the local device. Maybe I am missing something. Let me check with old build and try to reproduce these use cases with this change.

I have kept this review comment open until I am able to reproduce this issue.

2023-11-30 06:15 UTC, santosh-pingle commented
https://github.com/google/android-fhir/assets/86107848/336248e4-7878-4d8d-a67c-0abd170fd4d9

2023-11-30 08:45 UTC, santosh-pingle commented
> > I made some comments. Importantly, have you tested that these changes worked? I just checked out the PR and when I ran it on my device, it immeadiatly crashed with:
> > ```
> > java.lang.NullPointerException: Parameter specified as non-null is null: method com.google.android.fhir.sync.Result$Failed.<init>, parameter exceptions
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you double check that the changes dont cause a regression?
> 
> I have tried several times, and I did not encounter any crashes. I was able to perform periodic sync and one-time sync successfully. I managed to upload local data to the remote server, and I was also able to download updates on the local device. Maybe I am missing something. Let me check with old build and try to reproduce these use cases with this change.
> 
> I have kept this review comment open until I am able to reproduce this issue.

Observed crash with below use case : 

- Install an old demo app build on the device, open the demo app, and let it sync the data, e.g., periodic sync.
- Close the demo app and wait for 15 minutes.
- Install the new build with the current pull request.
- Open the demo app, and periodic sync will be triggered.
- The demo app crashes.
- Root cause:
The job name serves as the key to store the state in the datastore and is generated when PeriodicSyncRequest is created. The old build scheduled periodic sync without this unique name as a key in the input data, resulting in it being null when the new changes attempted to read this value from inputData in FhirSyncWorker. The pull request initially had a change to throw a null pointer exception if the uniqueName value is null, but now that change has been removed.

2023-12-01 05:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  private val gson = SyncJobStatusSerializer()
done.

2023-12-01 07:52 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +    internal const val STATE_TYPE = "STATE_TYPE"
done

2023-12-01 07:53 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
> +internal class SyncJobStatusSerializer {
done.

2023-12-01 07:56 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    syncJobTerminalState: SyncJobStatus?,
done.

2023-12-01 08:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +              fhirDataStore.updateSyncJobTerminalState(uniqueWorkerName)
I have introduced the "Unknown" state instead of using null to eliminate null values and associated exceptions.

2023-12-01 16:23 UTC, omarismail94 reviewed
@santosh-pingle I made a lot of suggested changes based on code that I wrote that worked. I think the code I am suggesting is cleaner, as I think it does a better job in making it clear that the FhirDataStore is only for saving terminal sync job status, and only them. It also reduces the number of flows needed by creating a Pair from one of the flows. Finally, it removes the need to having an Unknown sync job status. 


I've also created a commit on my branch that takes into account these changes:
https://github.com/google/android-fhir/commit/23c437447b3f2719d599baec039809ad4f9754b0#diff-be5aa8b6ab8b28619c138960f171ce4a6fc8eb07151a8374d24f3596b7b4ac7c

to make it easier for you to see the changes I made. 

lmk what you think

also. please add tests to take into account the different SyncStates that can be emitted

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
> +
can you also change the `Started` and `Finished` objects to `class` ? Having them as objects means that the `timestamp` is never updated when either one gets called repeatedly. This leads to incorrect timestamps in the demo app logs

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
>            }
we only write to the fhirstore when in a terminal state, which simplifies the logic a lot
```suggestion
          when (syncJobStatus) {
            is SyncJobStatus.Finished,
            is SyncJobStatus.Failed, -> {
              // While creating periodicSync request if
              // putString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY, uniqueWorkName) is not present,
              // then inputData.getString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY) can be null.
              if (uniqueWorkerName != null) {
                fhirDataStore.writeTerminalSyncJobStatus(uniqueWorkerName, syncJobStatus)
              }
              cancel()
            }
            else -> setProgress(buildWorkData(syncJobStatus))
          }
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      workInfo.state
We do not need this function. We can get the `WorkInfo.State` by having it as part of the flow return in the`getWorkerInfo` function. If you change the `getWorkerInfo` function to look like it does below, it will return a Flow<Pair<WorkInfo.State, SyncJobStatus?>>, which contains both things we want from one flow.
```
  fun getWorkerInfo(context: Context, workName: String) =
    WorkManager.getInstance(context)
      .getWorkInfosForUniqueWorkLiveData(workName)
      .asFlow()
      .flatMapConcat { it.asFlow() }
      .mapNotNull { workInfo ->
        workInfo.state to
          workInfo.progress
            .takeIf { it.keyValueMap.isNotEmpty() && it.hasKeyWithValueOfType<String>("StateType") }
            ?.let {
              val state = it.getString("StateType")!!
              val stateData = it.getString("State")
              gson.fromJson(stateData, Class.forName(state)) as SyncJobStatus
            }
      }
```

```suggestion
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return combineSyncStateForOneTimeSync(context, uniqueWorkName, flow, oneTimeWorkRequest.id)
we no longer need the id to be passed as the flow we create will contain workInfo state

```suggestion
    return combineSyncStateForOneTimeSync(context, uniqueWorkName, flow)
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return combineSyncStateForPeriodicSync(context, uniqueWorkName, flow, periodicWorkRequest.id)
same comment as above. 

```suggestion
    return combineSyncStateForPeriodicSync(context, uniqueWorkName, flow)
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
you can simplify this function now:

```suggestion
  internal fun combineSyncStateForPeriodicSync(
    context: Context,
    workName: String,
    workerInfoSyncJobStatusPairFromWorkManagerFlow: Flow<Pair<WorkInfo.State, SyncJobStatus?>>,
  ): Flow<PeriodicSyncState> {
    val syncJobStatusInDataStoreFlow: Flow<SyncJobStatus?> =
      FhirEngineProvider.getFhirDataStore(context).observeTerminalSyncJobStatus(workName)

    return combine(workerInfoSyncJobStatusPairFromWorkManagerFlow, syncJobStatusInDataStoreFlow) {
      workerInfoSyncJobStatusPairFromWorkManager,
      syncJobStatusFromDataStore,
      ->
      PeriodicSyncState(
        lastJobState = mapSyncJobStatusToResult(syncJobStatusFromDataStore),
        currentJobState =
          createSyncState(
            workerInfoSyncJobStatusPairFromWorkManager.first,
            workerInfoSyncJobStatusPairFromWorkManager.second,
            syncJobStatusFromDataStore,
          ),
      )
    }
  }
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
this function can be simplified a lot now with our WorkInfo.State, SyncJobStatus pair
```suggestion
  internal fun combineSyncStateForOneTimeSync(
    context: Context,
    workName: String,
    workerInfoSyncJobStatusPairFromWorkManagerFlow: Flow<Pair<WorkInfo.State, SyncJobStatus?>>,
  ): Flow<SyncState> {
    val syncJobStatusInDataStoreFlow: Flow<SyncJobStatus?> =
      FhirEngineProvider.getFhirDataStore(context).observeTerminalSyncJobStatus(workName)

    return combine(workerInfoSyncJobStatusPairFromWorkManagerFlow, syncJobStatusInDataStoreFlow) {
      workerInfoSyncJobStatusPairFromWorkManager,
      syncJobStatusFromDataStore,
      ->
      createSyncState(
        workerInfoSyncJobStatusPairFromWorkManager.first,
        workerInfoSyncJobStatusPairFromWorkManager.second,
        syncJobStatusFromDataStore,
      )
    }
  }
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
I think how i've written it simplifies the code and is based on the table that you had drawn in your design doc
```suggestion
  private fun createSyncState(
    workInfoState: WorkInfo.State,
    syncJobStatusFromWorkManager: SyncJobStatus?,
    syncJobStatusFromDataStore: SyncJobStatus?,
  ): SyncState {
    return when (syncJobStatusFromWorkManager) {
      is SyncJobStatus.Started,
      is SyncJobStatus.InProgress, -> Running(syncJobStatusFromWorkManager)
      is SyncJobStatus.Finished -> Succeeded(syncJobStatusFromDataStore!!)
      is SyncJobStatus.Failed -> Failed(syncJobStatusFromDataStore!!)
      null -> {
        when (workInfoState) {
          RUNNING -> Running(SyncJobStatus.Started())
          ENQUEUED -> Enqueued
          CANCELLED -> Cancelled
          SUCCEEDED -> Succeeded(SyncJobStatus.Finished())
          else -> error("Error message here")
        }
      }
    }
  }
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    }
cleaned up to take care of case where there is no lastSyncJobStatus
```suggestion
  private fun mapSyncJobStatusToResult(
    lastSyncJobStatus: SyncJobStatus?,
  ) =
    lastSyncJobStatus?.let {
      when (it) {
        is SyncJobStatus.Finished -> Result.Succeeded(it.timestamp)
        is SyncJobStatus.Failed -> Result.Failed(it.exceptions, lastSyncJobStatus.timestamp)
        else -> error("Can't have")
      }
    }
```

2023-12-01 16:23 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    }
delete. no longer needed i think
```suggestion
```

2023-12-04 10:27 UTC, santosh-pingle commented
> @santosh-pingle I made a lot of suggested changes based on code that I wrote that worked. I think the code I am suggesting is cleaner, as I think it does a better job in making it clear that the FhirDataStore is only for saving terminal sync job status, and only them. It also reduces the number of flows needed by creating a Pair from one of the flows. Finally, it removes the need to having an Unknown sync job status.
> 
> I've also created a commit on my branch that takes into account these changes: [23c4374#diff-be5aa8b6ab8b28619c138960f171ce4a6fc8eb07151a8374d24f3596b7b4ac7c](https://github.com/google/android-fhir/commit/23c437447b3f2719d599baec039809ad4f9754b0#diff-be5aa8b6ab8b28619c138960f171ce4a6fc8eb07151a8374d24f3596b7b4ac7c)
> 
> to make it easier for you to see the changes I made.
> 
> lmk what you think
> 
> also. please add tests to take into account the different SyncStates that can be emitted

Certainly, thank you for your suggestion. Lately,I introduced the "Unknown" state to prevent null pointer exceptions, but I agree it doesn't convey a cleaner state. I'll incorporate your suggestions.

2023-12-05 08:24 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +  object Unknown : SyncState()
Recently, I added this state. Initially, I was cautious about introducing it, but I opted for it instead of passing a null value. However, it doesn't make the state clearer; it only adds more ambiguity. Therefore, I am removing this state altogether.

2023-12-05 08:25 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +  object Unknown : Result()
I opted for it instead of passing a null value. However, it doesn't make the state clearer; it only adds more ambiguity. Therefore, I am removing this state altogether.

2023-12-05 08:36 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> + * @property timestamp The timestamp when the synchronization result occurred.
Yes, once I remove this Unknown state, I'll simply move this property to the base class level, and we'll keep this documentation here.

2023-12-05 08:39 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  private val syncJobStatusFlowMap = mutableMapOf<String, Flow<SyncJobStatus>>()
yes, I am reverting this change.

2023-12-05 08:59 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  internal fun observeSyncJobTerminalState(key: String): Flow<SyncJobStatus> =
yes.

2023-12-05 12:45 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
"Yes, it simplifies the code. Thanks for that!"
These are my observations:

1. Below cases will never be executed, as the terminal state involves only writing and reading from the dataStore. However, I understand that to avoid the 'else' case, we have explicitly mentioned those states here, correct?
```
is SyncJobStatus.Finished -> Succeeded(syncJobStatusFromDataStore!!)
is SyncJobStatus.Failed -> Failed(syncJobStatusFromDataStore!!)
```

2. Is the terminal state of syncJobStatus in periodic sync only updated through `lastJobState`? So, to determine whether the current job is finished or failed, it is required to read `PeriodicSyncState (lastJobState = Failed/Succeeded, currentJobState = Enqueued)`. One property is not enough, correct?

3. In OneTimeSync, if terminal state is failed, then it does not throw exceptions from SyncJobStatus.Failed

2023-12-05 17:42 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
> "Yes, it simplifies the code. Thanks for that!" These are my observations:
> 
> 1. Below cases will never be executed, as the terminal state involves only writing and reading from the dataStore. However, I understand that to avoid the 'else' case, we have explicitly mentioned those states here, correct?
> 
> ```
> is SyncJobStatus.Finished -> Succeeded(syncJobStatusFromDataStore!!)
> is SyncJobStatus.Failed -> Failed(syncJobStatusFromDataStore!!)
> ```

This is an excellent observation that I didn't realise. I tested for a successful sync and you're right, `SyncJobStatus.Finished` is never executed ! We probably need to handle the case where `syncJobStatusInDataStoreFlow` state is Failed like this though:

```
  private fun createSyncState(
    workInfoState: WorkInfo.State,
    syncJobStatusFromWorkManager: SyncJobStatus?,
    syncJobStatusFromDataStore: SyncJobStatus?,
  ): SyncState =
     when (syncJobStatusFromWorkManager) {
      is SyncJobStatus.Started,
      is SyncJobStatus.InProgress -> Running(syncJobStatusFromWorkManager)
      null -> {
        syncJobStatusFromDataStore?.let {
          return when (it) {
            is SyncJobStatus.Failed -> SyncState.Failed(it)
            is SyncJobStatus.Finished -> Succeeded(it)
            else -> error("Error message here")
          }
        }
        when (workInfoState) {
          RUNNING -> Running(SyncJobStatus.Started())
          ENQUEUED -> Enqueued
          CANCELLED -> Cancelled
          SUCCEEDED -> Succeeded(SyncJobStatus.Finished())
          else -> error("Error message here")
        }
      }
      else -> error("Error message here")
    }
```

WDYT?

> 
> 2. Is the terminal state of syncJobStatus in periodic sync only updated through `lastJobState`? So, to determine whether the current job is finished or failed, it is required to read `PeriodicSyncState (lastJobState = Failed/Succeeded, currentJobState = Enqueued)`. One property is not enough, correct?
I think so yes

> 3. In OneTimeSync, if terminal state is failed, then it does not throw exceptions from SyncJobStatus.Failed

We pass the exceptions to the user

2023-12-06 07:56 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
yes, it looks ok to me, thanks! 
I just added small change to accommodate  ```(workInfoState= ENQUEUED, syncJobStatusFromWorkManager=null, syncJobStatusFromDataStore=Finished/Failed) ```


```
private fun createSyncState(
    workInfoState: WorkInfo.State,
    syncJobStatusFromWorkManager: SyncJobStatus?,
    syncJobStatusFromDataStore: SyncJobStatus?,
  ): SyncState =
    when (syncJobStatusFromWorkManager) {
      is SyncJobStatus.Started,
      is SyncJobStatus.InProgress, -> Running(syncJobStatusFromWorkManager)
      null -> {
        when (workInfoState) {
          RUNNING -> Running(SyncJobStatus.Started())
          ENQUEUED -> Enqueued
          CANCELLED -> Cancelled
          SUCCEEDED -> {
            syncJobStatusFromDataStore?.let {
              return when (it) {
                is SyncJobStatus.Finished -> Succeeded(it)
                else -> error("Error message here")
              }
            }
            Succeeded(SyncJobStatus.Finished())
          }
          FAILED -> {
            syncJobStatusFromDataStore?.let {
              return when (it) {
                is SyncJobStatus.Failed -> Failed(it)
                else -> error("Error message here")
              }
            }
            error("Error message here")
          }
          else -> error("Error message here")
        }
      }
      else -> error("Error message here")
    }
```

2023-12-06 08:44 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
nice! i refactored it a bit to to reduce the nested blocks and make it a bit easier to read:
 
```
private fun createSyncState(
    workInfoState: WorkInfo.State,
    syncJobStatusFromWorkManager: SyncJobStatus?,
    syncJobStatusFromDataStore: SyncJobStatus?,
): SyncState =
    when (syncJobStatusFromWorkManager) {
        is SyncJobStatus.Started,
        is SyncJobStatus.InProgress -> Running(syncJobStatusFromWorkManager)
        null -> handleNullWorkManagerStatus(workInfoState, syncJobStatusFromDataStore)
        else -> error("Error message here")
    }

private fun handleNullWorkManagerStatus(
    workInfoState: WorkInfo.State,
    syncJobStatusFromDataStore: SyncJobStatus?
): SyncState = when (workInfoState) {
    RUNNING -> Running(SyncJobStatus.Started())
    ENQUEUED -> Enqueued
    CANCELLED -> Cancelled
    SUCCEEDED, FAILED -> handleFinishedOrFailedState(workInfoState, syncJobStatusFromDataStore)
    else -> error("Error message here")
}

private fun handleFinishedOrFailedState(
    workInfoState: WorkInfo.State,
    syncJobStatusFromDataStore: SyncJobStatus?
): SyncState = syncJobStatusFromDataStore?.let {
    when (it) {
        is SyncJobStatus.Finished ->  Succeeded(it)
        is SyncJobStatus.Failed -> Failed(it)
        else -> error("Error message here")
    }
} ?: when (workInfoState) {
    SUCCEEDED -> Succeeded(SyncJobStatus.Finished())
    FAILED -> error("Error message here")
    else -> error("Error message here")
}
```

2023-12-06 11:58 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +  object Unknown : SyncState()
done.

2023-12-06 11:59 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +  object Unknown : Result()
done.

2023-12-06 11:59 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +/*
done.

2023-12-06 11:59 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  private val syncJobStatusFlowMap = mutableMapOf<String, Flow<SyncJobStatus>>()
done.

2023-12-06 12:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  }
done.

2023-12-06 12:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +    }
done.

2023-12-06 12:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +  }
done.

2023-12-06 12:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
> +  fun deserialize(data: String?): SyncJobStatus {
done.

2023-12-06 12:01 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return combineSyncStateForPeriodicSync(context, uniqueWorkName, flow, periodicWorkRequest.id)
done.

2023-12-06 12:01 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
done.

2023-12-06 12:02 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    return combineSyncStateForOneTimeSync(context, uniqueWorkName, flow, oneTimeWorkRequest.id)
done.

2023-12-06 12:03 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  }
done.

2023-12-06 12:03 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    }
done.

2023-12-06 12:03 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    }
done.

2023-12-06 12:04 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      workInfo.state
done.

2023-12-06 12:04 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
> +  object Unknown : SyncJobStatus()
done.

2023-12-06 12:05 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +    private const val LAST_JOB_TERMINAL_STATE = "LAST_JOB_TERMINAL_STATE"
done.

2023-12-07 11:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> + * @property timestamp The timestamp when the synchronization result occurred.
done.

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      else -> error("Error message here")
write a proper error message

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      else -> error("Error message here")
same here

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      else -> error("Error message here")
i think it might need to be like this? what do you think?
```suggestion
      is SyncJobStatus.Started,
      is SyncJobStatus.InProgress, -> Running(syncJobStatusFromWorkManager)
      is SyncJobStatus.Finished -> Succeeded(syncJobStatusFromWorkManager
      else -> handleNullWorkManagerStatus(workInfoState, syncJobStatusFromDataStore)
```

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        else -> error("Error message here")
add proper error message

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        else -> error("Error message here")
same here

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        else -> error("Can't have")
same here

2023-12-07 13:05 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
> +        error("Not allowed")
same here

2023-12-12 07:33 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      else -> error("Error message here")
I do not see any advantages if we update the existing code with the suggested change. However, at the same time, I also do not see any issues if we accommodate the suggested change. The reason is that the terminal state (finished, failed) is only fetched from the dataStore, so it will not be part of in-progress states. If the build has legacy code and gets upgraded to the current pull request, in that case, the terminal syncJobStatus gets updated through setProgress, but this state never gets published, and this is the original issue where the terminal state gets lost.

Let me test this behavior.

2023-12-12 10:43 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
> +        error("Not allowed")
done.

2023-12-12 10:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        else -> error("Can't have")
done.

2023-12-12 10:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        else -> error("Error message here")
done.

2023-12-12 10:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +        else -> error("Error message here")
done.

2023-12-12 10:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      else -> error("Error message here")
done.

2023-12-12 10:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +      else -> error("Error message here")
done.

2023-12-13 10:41 UTC, santosh-pingle commented
Adding tests to assert the failed sync state caught an issue where the Failed state was not emitted. The reason was that the exceptions list was null, resulting in a null pointer exception.

2023-12-13 13:59 UTC, jingtang10 requested changes

2023-12-13 13:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +            is SyncJobStatus.Finished,
i think this should be renamed to succeeded. can you please make that change?

@omarismail94 fyi

2023-12-13 13:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +internal class FhirDataStore(context: Context) {
now the data store is in this file, fhir engine impl is calling to this data store which is in the sync module. i think the dependency here is wrong.

2023-12-13 13:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirDataStore.kt
> +internal class FhirDataStore(context: Context) {
i think the fhir engine pref datastore and the sync datastore can actually be separate.

@omarismail94 what's the benefits of having them together? are you concerned with concurrency? in terms of code reuse, datastore code boilerplate is minimal.

2023-12-13 13:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
i actually think this class can be inlined in `SyncJobStatus.kt file`, the `Serializer` class can even be nested under `SyncJobStatus`

2023-12-14 08:41 UTC, santosh-pingle commented
@omarismail94 
In a one-time sync, if the syncJobStatus is Failed in all retries, it emits the Failed state only for the last retry and not for all retries. For example, if the maximum number of retries is set to 3, and in each retry, if the terminalSyncJobStatus is Failed, it emits the Failed state only for the last retry. For the other retries, it emits the Enqueued/Running (SyncJobStatus.Started) state.
In my opinion, the expected result is that the state should be Failed if terminalSyncJobStatus is Failed in one time sync.

2023-12-14 11:33 UTC, jingtang10 requested changes

2023-12-14 11:33 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
can you add doc to this class to ambiguate sync job status and sync state?

2023-12-14 11:33 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +/** Sealed class representing different states of a synchronization operation. */
what's the diff between this and the sync job status?

2023-12-14 11:33 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class Result(val timestamp: OffsetDateTime) {
Can't call this result. It's too generic...

I'd rather call this LastJobState, but maybe we can come up with something better

@yigit @omarismail94

2023-12-14 11:33 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class Result(val timestamp: OffsetDateTime) {
maybe `LastSyncJobStatus` and `CurrentSyncJobStatus` make `SyncJobStatus`

2023-12-14 11:33 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
> +              .putString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY, "FailingPeriodicSyncWorker")
why do we need this?

2023-12-14 11:33 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +          val uniqueWorkerName = inputData.getString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY)
this line of code just doesn't seem right... why is the datastore key the unique worker name?

if this is an assumption you have made - it needs to be either made explicitly, or the assumption should be challenged.

2023-12-15 10:13 UTC, santosh-pingle commented on engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
> +              .putString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY, "FailingPeriodicSyncWorker")
I will verify and inform you if this fix is still necessary.

2023-12-15 10:23 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +          val uniqueWorkerName = inputData.getString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY)
From what I gather, the key naming (`SYNC_STATUS_PREFERENCES_DATASTORE_KEY`) is misleading and seems inappropriate. In reality, the key is not derived from the datastore; instead, it is derived from the worker name in the Sync class. It is simply fetched in the worker and then forwarded to the datastore to store the terminal state against it. 

If you find the naming concerning, I am open to renaming it. Please let me know if you have a different perspective.

2023-12-15 11:23 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
I'm uncertain about moving this class to the `SyncJobStatus.kt` file, as this serializer was specifically designed for serializing and deserializing terminal `syncJobStatus`. I'm also leaning towards renaming this class to `TerminalSyncJobStatusSerializer`. In that regard, I am inclined to either keep it as a single class or consider moving it to the `FhirDatastore` as a nested class.

2023-12-18 09:35 UTC, santosh-pingle commented
Resolving conflicts.

2023-12-18 10:25 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +          val uniqueWorkerName = inputData.getString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY)
done.

2023-12-18 10:25 UTC, santosh-pingle commented on engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
> +              .putString(SYNC_STATUS_PREFERENCES_DATASTORE_KEY, "FailingPeriodicSyncWorker")
changes are reverted. done.

2023-12-18 10:26 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +sealed class Result(val timestamp: OffsetDateTime) {
done.

2023-12-18 10:45 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncState.kt
> +/** Sealed class representing different states of a synchronization operation. */
done.

2023-12-18 10:45 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
done.

2023-12-18 10:46 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +            is SyncJobStatus.Finished,
done.

2023-12-18 11:01 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
please let me know if you do have other thoughts.

2023-12-18 12:31 UTC, omarismail94 commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +  private val _pollState = MutableSharedFlow<CurrentSyncJobStatus>()
add a shared flow for periodic jobs that is separate from the one for one time sync

2023-12-18 12:31 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
>    /** Gets the worker info for the [FhirSyncWorker] */
make the getWorkerInfo function private

2023-12-18 12:31 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/CurrentSyncJobStatus.kt
> +sealed class CurrentSyncJobStatus {
For periodic, it is called PeriodicSyncState, not Status. let us be consistent
```suggestion
sealed class CurrentSyncJobState {
```

2023-12-18 12:31 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/CurrentSyncJobStatus.kt
> +}
if this file name is `CurrentSyncJonStatus`, why does the PeriodicSyncState live here? Either move to a separate file or rename this file back to SyncState to capture the file's contents (I prefer the latter)

2023-12-19 06:13 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/CurrentSyncJobStatus.kt
> +}
I am renaming it to SyncState, but I am of the opinion to move this entire file to the SyncJobStatus file. Essentially, it will include SyncJobStatus, CurrentSyncJobStatus, and PeriodicSyncJobStatus classes. Please share your thoughts on this.

2023-12-19 08:34 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/CurrentSyncJobStatus.kt
> +sealed class CurrentSyncJobStatus {
done.

2023-12-19 08:36 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
>    /** Gets the worker info for the [FhirSyncWorker] */
As it is called by `inline fun`,  it is required to be updated `@publishapi internal` instead of private to avoid build error.

2023-12-19 08:37 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/MainActivityViewModel.kt
> +  private val _pollState = MutableSharedFlow<CurrentSyncJobStatus>()
done.

2023-12-19 08:42 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
>    /** Gets the worker info for the [FhirSyncWorker] */
done.

2023-12-19 12:55 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/CurrentSyncJobStatus.kt
> +}
sure, please do that

2023-12-20 11:31 UTC, jingtang10 requested changes

2023-12-20 11:31 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
> +  private val allowedSyncJobStatusPackages =
why do we use the strings and not use the actual enum for the check? if we rename this class or move it to a different package, i guarantee you that we'll forget changing this string and we'll end up with buggy code.

@omarismail94

2023-12-20 11:31 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
i feel that these functions can arguably be member functions of the sync job status class. just for organization and keeping things together, i really feel this should be part of that class, be it only for teminal status or not.

2023-12-20 11:31 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +    lifecycleScope.launch {
shouldn't we have a suceeded/failed states here? i don't feel this is clear for applications to use.

2023-12-20 11:31 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +    lifecycleScope.launch {
@omarismail94 @aditya-07 you thoughts?

2023-12-26 10:01 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +    lifecycleScope.launch {
done.

2023-12-27 09:40 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
> +  private val allowedSyncJobStatusPackages =
done.

2023-12-27 11:23 UTC, jingtang10 approved these changes
thanks @santosh-pingle

@MJ1998 fyi

2023-12-27 11:23 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
> +sealed class LastSyncJobStatus(val timestamp: OffsetDateTime) {
should there be a cancelled state here too?

2023-12-27 11:23 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
> +internal class SyncJobStatusSerializer {
you can move this to inside SyncJobStatus class

2023-12-27 11:23 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
order the classes in this file a bit more logically:

periodic sync status first
followed by last and current

and then have sync job status at the end, with the serialisation methods inside the class.

2023-12-27 11:23 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +      mainActivityViewModel.pollPeriodicSyncJobStatus.collect {
add code to handle the last sync timestamp and update the ui.

2024-01-02 09:52 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
> +      mainActivityViewModel.pollPeriodicSyncJobStatus.collect {
done.

2024-01-02 09:52 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
done.

2024-01-02 09:52 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
> +internal class SyncJobStatusSerializer {
done.

2024-01-02 10:55 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatusSerializer.kt
done.

2024-01-02 11:04 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobStatus.kt
> +sealed class LastSyncJobStatus(val timestamp: OffsetDateTime) {
acknowledged, #2399

2024-01-02 13:04 UTC, merged