use FetchProgress to track upload progress
google/android-fhir pull request #2173
Opened 2023-09-15 17:15 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-09-18 10:38 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +      is UploadSyncResult.Failure -> {}
add comment what is to be expected here

2023-10-03 08:29 UTC, anchita-g requested changes

2023-10-03 16:00 UTC, jingtang10 requested changes
have you tested the demo app with this?

2023-10-04 10:34 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +          is UploadSyncResult.Success -> result
syncUpload needs to know the UploadSyncResult in order to consolidate the resources in the response

2023-10-04 10:37 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    emit(FetchProgress(localChangeFetcher.total, localChangeFetcher.total))
i have a test for this, and i added this on purpose. at the beginning, we want to emit that we have all the changes to upload and we haven't uploaded any. I will add the argument names to make this more readable 

```
    emit(FetchProgress(remaining = localChangeFetcher.total, initialTotal = localChangeFetcher.total))
```

2023-10-04 10:47 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +          is UploadSyncResult.Success -> result
Should the `syncUpload` then just consume the `UploadSyncResult`.  Maybe we should combine the `FetchProgress` and the "upload state" so that we do not have distributed logic like this?

2023-10-04 11:52 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +          is UploadSyncResult.Success -> result
I've also removed the need for the `when` statement by only just passing uploader.uplaod(it) to the syncUpload function

2023-10-04 14:35 UTC, omarismail94 commented
> have you tested the demo app with this?

@jingtang10 yes, and it worked. I was able to see the upload status update emissions being printed in the logs

2023-10-05 12:23 UTC, jingtang10 approved these changes
woohoo!

2023-10-05 12:23 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +      .syncUpload(localChangesFetchMode) { uploader.upload(it) }
further simplify as discused

2023-10-05 13:06 UTC, merged