constraint support
google/android-fhir pull request #2199
Opened 2023-09-26 03:05 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2003

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-09-27 04:21 UTC, FikriMilano commented
@jingtang10 @santosh-pingle 
this is ready for review

2023-09-27 04:33 UTC, FikriMilano commented
@shelaghm we might need a new icon for this new behavior

2023-09-29 23:01 UTC, shelaghm commented
@FikriMilano How about [this icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Afunctions%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)? I recommend just pulling from this list of open source icons if you ever need one since these are easy to implement and open source.

2023-10-01 23:38 UTC, FikriMilano commented
@shelaghm That's fine, thanks!

2023-10-02 12:41 UTC, FikriMilano commented
@shelaghm Done.

<img width='300' src='https://github.com/google/android-fhir/assets/62053304/dac814cc-d35a-4e0d-a972-f0410cc0a5c3'>

2023-10-02 17:36 UTC, shelaghm commented
@FikriMilano Could you make the icon slightly smaller: 48px? Thanks!

2023-10-02 17:49 UTC, jingtang10 commented
not sure i am super keen on the sigma sign - it means sum in mathamatics so i think it's a bit weird to use that for constraint.

how about this: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:rule:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=rule?

2023-10-02 17:50 UTC, jingtang10 commented
@FikriMilano how are you determining where to show the error message since constraints are global?

2023-10-02 17:52 UTC, shelaghm commented
> not sure i am super keen on the sigma sign - it means sum in mathamatics so i think it's a bit weird to use that for constraint.
> 
> how about this: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:rule:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=rule?

"Rule' one is better, thanks @jingtang10 @FikriMilano

2023-10-03 07:54 UTC, FikriMilano commented
> how are you determining where to show the error message since constraints are global?

@jingtang10 
As we may know, the constraint extension can be used used in the Questionnaire itself (global) and it's item.
If the extension is declared inside an item, then this validator will show the error message below the field (as usual).

I kind of forgot that the extension can be applied to the Questionnaire / globally, so I haven't add the code to do that yet. The solution would be: 

use a sub-extension called `location` that contains the _Relative paths to the questions this rule is enforced against_. Using this path, we can find the item where the rule belongs to, then show the error message below the field of that item.

or

we can use a snackbar/toast/modal to show an error message if the constraint extension is declared in the Questionnaire itself / globally.

2024-02-19 14:08 UTC, jingtang10 commented
i think in the global case, i'm happy for it to be displayed on top of the questionnaire or in the confirmation popup dialog before submission. i feel deduction of where the error message should be could end up being unreliable / not what the questionnaire author expects.

> > how are you determining where to show the error message since constraints are global?
> 
> @jingtang10 As we may know, the constraint extension can be used used in the Questionnaire itself (global) and it's item. If the extension is declared inside an item, then this validator will show the error message below the field (as usual).
> 
> I kind of forgot that the extension can be applied to the Questionnaire / globally, so I haven't add the code to do that yet. The solution would be:
> 
> use a sub-extension called `location` that contains the _Relative paths to the questions this rule is enforced against_ / Link ID of the item. Using this path, we can find the item where the rule belongs to, then show the error message below the field of that item.
> 
> or
> 
> we can use a snackbar/toast/modal to show an error message if the constraint extension is declared in the Questionnaire itself / globally.

2024-02-26 14:20 UTC, ndegwamartin commented
Additionally perhaps as part of this PR we should enforce that `qItem` & `questionnaire` are reserved keywords within the `ExpressionEvalutor.kt` class when populating the _dependent variables_ data structure [see comment here](https://github.com/google/android-fhir/issues/1849#issuecomment-1964248249).

2024-02-27 08:14 UTC, joiskash requested changes
Left some comments, in general I was wondering if we could re-use the existing interface. 
It is also not clear as to what changes will need to be done to support global mode of this extension. It might be worthwhile adding a TODO with a small explanation of what changes will be needed with an issue link.

2024-02-27 08:42 UTC, ellykits commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MultiConstraintValidator.kt
> +    questionnaireResponseItem: QuestionnaireResponseItemComponent,
Is this item obtained from the `QuestionnaireResponse` if so it may not be necessary to provide it as a function argument with the `QuestionnaireResponse`.

2024-02-27 08:50 UTC, ellykits commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MultiConstraintValidator.kt
> +  data class Result(val isValid: Boolean, val errorMessage: String?)
Duplication of [QuestionnaireResponseItemConstraintValidator.Result](https://github.com/google/android-fhir/blob/8714236ef5ce07c8e143034057d4e1425d10c45f/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemConstraintValidator.kt#L48C14-L48C20)

2024-03-21 10:58 UTC, MJ1998 requested changes

2024-03-21 10:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintExtensionValidator.kt
> +        // TODO: Add constraint support for warning case, update the [ConstraintValidator.Result]
NIT: wrap this within /** */ instead of //..//

2024-03-21 10:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintExtensionValidator.kt
> +// TODO: Add constraint support for global case, add questionnaire in constructor, and process that
NIT: Wrap this within /** */ instead of //..//

2024-03-21 10:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintExtensionValidator.kt
> +  override suspend fun validate(
I am wondering how will we differentiate between item level vs global level extensions ?

2024-03-21 10:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintExtensionValidator.kt
> +          )
Can you use `expressionEvaluator.evaluateExpression` directly ?
```suggestion
val isValid = expressionEvaluator.evaluateExpression(
    questionnaireItem,
    questionnaireResponseItem,
    expression
).convertToBoolean()
```

I think there is a convertToBoolean function for List<Base> in `FhirPathUtil`.

2024-03-21 10:58 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemConstraintValidator.kt
> +  ): List<ConstraintValidator.Result>
Why do we need to make it a List ?
Even if it's absolutely necessary, we can combine the results into 1 result, right ?

2024-03-27 04:21 UTC, MJ1998 approved these changes
LGTM

2024-03-27 04:25 UTC, merged