Allow sorting in [rev]include results.
google/android-fhir pull request #2200
Opened 2023-09-26 12:28 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Allow developers to return sorted results of [rev]include search block.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-03 13:05 UTC, jingtang10 requested changes

2023-10-12 07:26 UTC, aditya-07 commented on demo/src/main/java/com/google/android/fhir/demo/FhirApplication.kt
> +        enableEncryptionIfSupported = false,
Done.

2023-10-12 07:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  override fun toString(): String {
Removed `equals` and `toString` from `SearchResult`. Used `com.google.common.truth.Correspondence` to do equality check and generate diff.

2023-10-12 07:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
Done

2023-12-12 17:05 UTC, jingtang10 requested changes

2023-12-12 17:05 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    database.insertRemote(*(patients + practitioners).shuffled().toTypedArray())
instead of shuffling, can we just make sure they go in a specific order that is not already the expected order? i'm asking because i want to eliminate indeterminism in the test cases.

2023-12-14 18:48 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +data class ResourceAndUUID<R>(
Done

2023-12-14 18:48 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +      .containsAtLeast("Patient", "general-practitioner", "Practitioner")
Done

2023-12-14 18:48 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +      .containsAtLeast(
Done

2023-12-14 18:49 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +      .containsAtLeast(
Done

2023-12-14 18:49 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        .getRevIncludeQuery(listOf("pa01", "pa02"))
Done

2023-12-14 18:50 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +internal data class SerializedResourceAndUuid(
Done

2023-12-14 18:50 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    database.insertRemote(*(patients + practitioners).shuffled().toTypedArray())
Done

2023-12-14 20:34 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
>            IndexedIdAndResource(
refactored the code.

2023-12-14 20:34 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        ON re.resourceType = b.resourceType AND re.resourceUuid = b.resourceUuid AND b.index_name = 'recorded-date'LEFT JOIN DateTimeIndexEntity c
done

2023-12-14 20:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +            uuidOfBaseResourceOnWhichThisMatched = it.idOfBaseResourceOnWhichThisMatchedInc,
refactored code to simplify logic

2023-12-14 20:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
>  internal data class IndexedIdAndResource(
done

2023-12-14 20:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
>  internal data class IndexedIdAndSerializedResource(
done

2023-12-15 08:49 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private fun Search.getSortOrder(otherTable: String): Pair<String, String> {
Done

2023-12-15 08:49 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          ON re.resourceType = b.resourceType AND re.resourceUuid = b.resourceUuid AND b.index_name = 'given'
Done

2023-12-15 09:15 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          include<Practitioner>(Patient.GENERAL_PRACTITIONER) {
Done

2023-12-15 09:16 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          ON re.resourceType = b.resourceType AND re.resourceUuid = b.resourceUuid AND b.index_name = 'given'
Done

2023-12-18 13:23 UTC, jingtang10 approved these changes
A high level comment: we need to think about limiting the search DSL so that invalid queries are either prohibited syntactically, or in the worst case, throw an exception at runtime.

Together with this, we need to improve documentation.

2023-12-18 13:23 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    val ArgsComparator: Correspondence<Any, Any> =
optional: a more descriptive name.

2023-12-19 09:58 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      ON $otherTable.resourceType = $tableAlias.resourceType AND $otherTable.resourceUuid = $tableAlias.resourceUuid AND $tableAlias.index_name = ?
Will it be more efficient to order these filters based on the order of columns in the index ?
For example DateIndexEntity have `Index(value = ["resourceType", "index_name", "resourceUuid", "index_from", "index_to"])`

Would it be more efficient to order and write it like this:-

ON $otherTable.resourceType = $tableAlias.resourceType AND $tableAlias.index_name = ? AND $otherTable.resourceUuid = $tableAlias.resourceUuid

2023-12-26 10:00 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      ON $otherTable.resourceType = $tableAlias.resourceType AND $otherTable.resourceUuid = $tableAlias.resourceUuid AND $tableAlias.index_name = ?
Since we are checking the equality, the order shouldn't matter much.

2023-12-26 10:59 UTC, merged