Ignore flaky UI Test, for now (see #1482, fixes #2197)
google/android-fhir pull request #2203
Opened 2023-09-26 21:25 UTC by vorburger

Fixes #2197, see also #1482

**Description**
This disables a known flaky UI test. This reduces confusion on why PRs fail to build.

**Alternative(s) considered**
_Have you considered any alternatives? And if so, why have you chosen the approach in this PR?_
The alternative is to fix the flaky UI test. My Android foo isn't strong enough to know how to do that, unfortunately.

**Type**
Choose one: **Bug fix** ~Feature | Documentation | Testing | Code health | Builds | Releases | Other~

2023-09-27 07:56 UTC, omarismail94 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/QuestionnaireItemDialogMultiSelectViewHolderFactoryEspressoTest.kt
> +  @Ignore // TODO https://github.com/google/android-fhir/issues/1482 FIXME
@Ignore takes a parameter where you can add the link:
```suggestion
  @Ignore("https://github.com/google/android-fhir/issues/1482")
```

2023-09-28 10:29 UTC, jingtang10 requested changes
sorry for the delay... i thought i sent this out: but my main comment here is can you try to ignore this only for api level 24? this is not flaky on api level 33.

2023-09-28 10:33 UTC, vorburger commented
> sorry for the delay... i thought i sent this out: but my main comment here is can you try to ignore this only for api level 24? this is not flaky on api level 33.

I have no idea if it's possible to (easily) do that. @omarismail94 would you happen to know?

If it's not, my recommendation is to ignore it for all, until fixed, to have green CI.

2023-09-29 10:08 UTC, omarismail94 commented
> > sorry for the delay... i thought i sent this out: but my main comment here is can you try to ignore this only for api level 24? this is not flaky on api level 33.
> 
> I have no idea if it's possible to (easily) do that. @omarismail94 would you happen to know?
> 
> If it's not, my recommendation is to ignore it for all, until fixed, to have green CI.

In the flaky test, you can add this block:

```
    @Test
    fun testMethodToIgnoreOnApi24() {
        // Ignore this specific test if the API level is 24
        Assume.assumeTrue(Build.VERSION.SDK_INT != Build.VERSION_CODES.N)
        
        // Your test code here...
    }
```

https://github.com/google/android-fhir/pull/2203#issuecomment-1738892206

2023-09-29 10:11 UTC, vorburger commented
An alternative suggested by @jingtang10 is https://developer.android.com/reference/androidx/test/filters/SdkSuppress.

2023-10-02 08:23 UTC, omarismail94 reviewed
@vorburger can you also add the same thing to:
`clickAddAnotherAnswer_shouldScrollDownToShowAddAnotherAnswer`

It is the other flaky test this library

2023-10-06 09:41 UTC, omarismail94 approved these changes

2023-10-06 10:25 UTC, jingtang10 approved these changes

2023-10-06 10:49 UTC, merged