Add resource UUID to LocalChangeEntity
google/android-fhir pull request #2210
Opened 2023-09-27 05:33 UTC by anchita-g

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2209 

**Description**
We need to LocalChangeEntity agnostic of the resource ID as there can be cases where the resource ID of a resource might change (POST for creation). In such cases we can use resource UUID to keep the mapping between the resource and LocalChanges intact.
There are cases where in download of a resource which already exists in the database leads to new resource UUID being assigned to the same resource. Hence we need to keep the same resource UUID as the previous version in such cases

**Alternative(s) considered**
One alternative in the first scenario was to just keep the resourceUuid and remove resourceId. However, when LocalChanges are uploaded to the server, we would need to look up the ResourceEntity using the resourceUuid in the LocalChangeEntity to obtain the server recognisable identifier of the resource. This would be a problem in case of deleted resources, where in for any LocalChange of a resource that has been deleted, we would not be able to find the corresponding ResourceEntity. Hence, keeping resourceId is also crucial

**Type**
Choose one:  Feature
**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-09-27 13:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    if (existingResourceEntity != null) {
is this code relevant to adding resource UUID to LocalChangeEntity? If not, can we remove it and have it in another PR?

2023-09-27 13:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    if (existingResourceEntity != null) {
I see that in the PR description:
```
There are cases where in download of a resource which already exists in the database leads to new resource UUID being assigned to the same resource. Hence we need to keep the same resource UUID as the previous version in such cases
```

did this problem exist before this change?

2023-09-27 13:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +            }
same comment as above about `timeOfLocalChange` being nullable

2023-09-27 13:12 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +          val resourceEntity = selectEntity(it.resourceType, it.logicalId)
should we just have `insertLocalResource` return `resourceUUId`, or a `Pair<resourceId, recourceUUID>` to avoid making extra calls to the DB?

2023-09-28 06:05 UTC, anchita-g commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/ResourceDatabaseMigrationTest.kt
> +    val migratedDatabase = helper.runMigrationsAndValidate(DB_NAME, 2, true, MIGRATION_1_2)
Yes, the migrations before did not change any existing table by adding any non-null new columns. Hence running entire migrations till the latest version and then testing only against the specific migration did not cause any problems.

2023-09-28 06:07 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  open suspend fun update(resource: Resource, timeOfLocalChange: Instant?) {
Yes, this is for cases where we update the resource when it is downloaded from the server. As of now we insert a new resource entity which leads to change in resource UUID. We need to instead update it and it can happen that the resource did not change at all since it was last donwloaded and hence, `timeOfLocalChange` can be nullable

2023-09-28 06:08 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +            }
Addressed it in the above comment. Thanks!

2023-09-28 06:09 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    if (existingResourceEntity != null) {
Yes, every time we downloaded an entity, we assigned it a new resource UUID

2023-09-28 07:35 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +          val resourceEntity = selectEntity(it.resourceType, it.logicalId)
Makes sense. Done!

2023-09-29 05:46 UTC, anchita-g commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    if (existingResourceEntity != null) {
The changes I added make sure that the uuid for the resource remains the same
We need the resource uuid to remain the same for its entire life it's on the device until it is deleted

2023-09-29 10:06 UTC, aditya-07 requested changes

2023-09-29 10:19 UTC, MJ1998 requested changes
I don't understand why the alternative solution won't work.

In case of locally deleted resource, we can remove resourceId and still fetch the mapped ResourceEntity via LocalChangeEntity.resourceUuid.

2023-09-29 10:19 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  open suspend fun insertAllRemote(resources: List<Resource>): List<UUID> {
Will the return List\<UUID\> be used ?
I guess List\<String\> was also not being used.

2023-09-29 10:19 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/entities/LocalChangeEntity.kt
> +      Index(value = ["resourceType", "resourceUuid"]),
Isnt Index on resourceUuid enough ?
Why do we need to pair it with resourceType ?

2023-09-29 10:42 UTC, aditya-07 commented
> One alternative in the first scenario was to just keep the resourceUuid and remove resourceId. However, when LocalChanges are uploaded to the server, we would need to look up the ResourceEntity using the resourceUuid in the LocalChangeEntity to obtain the server recognisable identifier of the resource. This would be a problem in case of deleted resources, where in for any LocalChange of a resource that has been deleted, we would not be able to find the corresponding ResourceEntity. Hence, keeping resourceId is also crucial

For the DELETE resource event, engine removes its entry from `ResourceEntity` and adds a corresponding DELETE entry into the `LocalChangeEntity`. Hence, to sync the change to sever, `LocalChangeEntity` should have the resourceID so that it can be uploaded properly.

2023-09-29 10:43 UTC, aditya-07 commented
> I don't understand why the alternative solution won't work.
> 
> In case of locally deleted resource, we can remove resourceId and still fetch the mapped ResourceEntity via LocalChangeEntity.resourceUuid.


One alternative in the first scenario was to just keep the resourceUuid and remove resourceId. However, when LocalChanges are uploaded to the server, we would need to look up the ResourceEntity using the resourceUuid in the LocalChangeEntity to obtain the server recognisable identifier of the resource. This would be a problem in case of deleted resources, where in for any LocalChange of a resource that has been deleted, we would not be able to find the corresponding ResourceEntity. Hence, keeping resourceId is also crucial

For the DELETE resource event, engine removes its entry from ResourceEntity and adds a corresponding DELETE entry into the LocalChangeEntity. Hence, to sync the change to sever, LocalChangeEntity should have the resourceID so that it can be uploaded properly.

2023-10-03 06:04 UTC, MJ1998 approved these changes
LGTM

2023-10-03 08:22 UTC, aditya-07 approved these changes
LGTM!

2023-10-03 09:05 UTC, merged

2023-10-04 09:26 UTC, jingtang10 commented
@anchita-g have you tested the db migration on a real device? thanks!

2023-10-09 08:12 UTC, anchita-g commented
> @anchita-g have you tested the db migration on a real device? thanks!

Hello, yes I was able to test the db migration on a real device using the demo application. It works seamlessly and I was able to see the new column in the `App Inspection` database explorer