Workflow multiword property handling- for cql fhir-retreiver
google/android-fhir pull request #2213
Opened 2023-09-27 14:36 UTC by maimoonak

Fixes #2190 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-09-28 09:32 UTC, aditya-07 requested changes

2023-09-28 09:32 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
> +    }
Just like `filterByCode`, `filterByValueSet` should also be passing `param` to `TokenClientParam` instead of using the `codePath`.

2023-11-30 14:13 UTC, omarismail94 commented
@maimoonak is this PR still relevant? the workflow lib has changed a lot since this PR. Could you please merge with master and see if the issue is now resolved, or still needs fixing?

2024-01-05 07:42 UTC, maimoonak commented
> @maimoonak is this PR still relevant? the workflow lib has changed a lot since this PR. Could you please merge with master and see if the issue is now resolved, or still needs fixing?

not relevant anymore

2024-01-05 07:42 UTC, closed without merging