UnpackReapted Groups Fix for single group item
google/android-fhir pull request #2216
Opened 2023-09-29 07:09 UTC by AdityaKBhadragond14

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2162

**Description**
Consider a scenario where there is a questionnaire with one questionnaire item whose type is group and repeats is set to true for the same.

```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "type": "group",
      "linkId": "parent-item",
      "text": "Parent Group Item",
      "repeats": true,
      "item": [
        {
          "linkId": "1",
          "type": "string",
          "text": "Personal information",
          "initial": [
            {
              "valueString": "ABC"
            }
          ]
        }
      ]
    }
  ]
}
```

In this case if only group item is answered then questionnaire response returned is with empty item list like following:

```
{
  "resourceType": "QuestionnaireResponse",
  "item": [
    {
      "linkId": "parent-item",
      "text": "Parent Group Item",
      "item": [
        {
          "linkId": "1",
          "text": "Personal information",
          "answer": [
            {
              "valueString": "ABC"
            }
          ]
        }
      ]
    }
  ]
}
```

But if there are more than one group items being answered in the questionnaire then the questionnaire response is proper.
To fix this issue if there are more than one repeated group items in the questionnaire response then do the recursive unpacking logic or else if there is only one group item in the questionnaire response then do not do the unpacking of repeated groups instead return the group item.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug Fix

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-05 09:19 UTC, jingtang10 requested changes

2023-10-05 09:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
please add a test case in `MoreQuestionnaireResponsesTest.kt`

2023-10-06 08:37 UTC, AdityaKBhadragond14 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
I have added the test case please review and let me know.

2023-10-06 17:10 UTC, jingtang10 reviewed
after looking at the test case, i'm not entirely sure this is the right fix. the example you give is already unpacked, why do you think the unpack function is the problem?

in the questionnaire view model class, we pack repeated groups under the same questionnaire response item, and use each answer to host nested questions in each repeated group. have you checked that's been handled correctly?

2023-10-10 04:21 UTC, AdityaKBhadragond14 commented
> after looking at the test case, i'm not entirely sure this is the right fix. the example you give is already unpacked, why do you think the unpack function is the problem?
> 
> in the questionnaire view model class, we pack repeated groups under the same questionnaire response item, and use each answer to host nested questions in each repeated group. have you checked that's been handled correctly?

The issue was when there is only group item in the questionnaire response. In this case the group item won't be under answer of the questionnaire response due to this the unpack function was returning the empty questionnaire response.

2024-02-13 09:07 UTC, joiskash commented
We can close this PR. #1911 has the fix for this.

2024-02-13 09:32 UTC, jingtang10 commented
ok let's close this. thanks both!

2024-02-13 09:32 UTC, closed without merging