Prototype definition-based extraction
google/android-fhir pull request #222
Opened 2021-02-07 18:06 UTC by jingtang10

2021-02-12 12:08 UTC, joiskash requested changes
Great work! The code looks very neat! Just a few comments

2021-02-12 12:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     * This method assumes there is only one FHIR resource to be extracted from the given
Just  putting this here so we can ask the Tuesday WG if this assumptions holds good most of the time.
> In some cases, the context of an element will switch. For example, an item might have a definition of "http://hl7.org/fhir/MedicationStatement#MedicationStatement.medicationReference" and a questionnaire-itemContext extension that shifts the context to "Medication". Subsequent children would then have definitions based on the "http://hl7.org/fhir/Medication" resource.

2021-02-12 12:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        val builder = questionnaire.itemContextNameToExpressionMap.values.first().let {
> Include the questionnaire-itemContext extension either on the Questionnaire root or on 'group' items within the Questionnaire to identify the resource that will serve as the context for any extraction.
Do we need a validator to make sure this is not violated

2021-02-14 13:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     * This method assumes there is only one FHIR resource to be extracted from the given
Created https://github.com/google/android-fhir/issues/240

2021-02-14 13:51 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    get() = this.definition.value.substringAfterLast(".")
Created https://github.com/google/android-fhir/issues/240

2021-02-14 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val targetFieldName = questionnaireItem.definitionFieldName
Created https://github.com/google/android-fhir/issues/240

2021-02-14 13:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     * This method assumes there is only one FHIR resource to be extracted from the given
Cool. I think that's quite an advanced use case and happy to leave it to the future. But yes let's definitely discuss this on tuesday.

2021-02-14 13:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        val builder = questionnaire.itemContextNameToExpressionMap.values.first().let {
I'm not sure we need a validator -- if the extension is not on the root or on a group we'll simply ignore it. But we do need to handle extensions on groups (which we don't). Again I feel this is quite advanced and I'm quite happy to leave it to later.

2021-02-14 13:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val targetFieldName = questionnaireItem.definitionFieldName
also added a note in the code to reference that issue.

2021-02-14 13:58 UTC, jingtang10 commented
Thanks @joiskash for the review. Please take another look.

2021-02-14 14:14 UTC, joiskash approved these changes
Ok great! The advance features can be added in the future!

2021-02-15 12:54 UTC, merged