Default m3 style to survey button.
google/android-fhir pull request #2225
Opened 2023-10-04 06:14 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes

**Description**
Apply default m3 button style to survey button, and remove the existing applied padding.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-04 06:15 UTC, santosh-pingle commented
<img width="385" alt="Screenshot 2023-10-04 at 11 20 23 AM" src="https://github.com/google/android-fhir/assets/86107848/29a9aacb-87a8-4512-b398-2f6ac558b384">

2023-10-04 11:13 UTC, jingtang10 requested changes

2023-10-04 11:13 UTC, jingtang10 commented on demo/src/main/res/layout/patient_details_header.xml
> +            android:textAppearance="?attr/textAppearanceBodyMedium"
can we use the default style from material button? try and see how it looks without this

2023-10-09 07:21 UTC, santosh-pingle commented on demo/src/main/res/layout/patient_details_header.xml
> +            android:textAppearance="?attr/textAppearanceBodyMedium"
done.

<img width="383" alt="Screenshot 2023-10-09 at 12 48 26 PM" src="https://github.com/google/android-fhir/assets/86107848/af9a3901-b26d-4c12-85c1-d3c0c0b53c4e">

2023-10-18 12:48 UTC, jingtang10 approved these changes

2023-10-19 14:41 UTC, merged