Fixed bug with date and date time widgets where you cannot reenter without moving away
google/android-fhir pull request #223
Opened 2021-02-08 15:24 UTC by varunvjha

Fixes: #208

2021-02-08 17:27 UTC, jingtang10 commented
This is excellent! Thanks for the fix!

Can you just do the same in https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt?

I will approve after that.

2021-02-08 18:19 UTC, jingtang10 requested changes
Thanks! Just a couple of small things!

2021-02-08 18:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +                timeInputLayout.clearFocus()
I think this should be one line higher i.e. within the curly brackets?

2021-02-08 18:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +                    textInputLayout.clearFocus()
please add the following comment (or something similar) and add the same to the other two placess

```suggestion
                    // Clear focus so that the user can refocus to open the dialog
                    textInputLayout.clearFocus()
```

2021-02-08 18:20 UTC, varunvjha commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +                timeInputLayout.clearFocus()
Yes, yes  I realized the mistake. Changing it.

2021-02-08 18:29 UTC, jingtang10 approved these changes
👍

Thanks Varun!

2021-02-08 18:45 UTC, jingtang10 commented
Please feel free to merge once the tests pass.

2021-02-08 19:11 UTC, varunvjha commented
@jingtang10 1 check is failing and I am not able to interpret the reason for it's failure. Can you check?

2021-02-09 12:00 UTC, jingtang10 commented
tests passing now -- please feel free to merge your first PR! 🎉

2021-02-09 13:26 UTC, varunvjha commented
Only those with write access to this repo can merge PRs. There doesn't seem to be an option for me to merge the PR.

2021-02-09 13:26 UTC, merged

2021-02-09 19:27 UTC, jingtang10 commented
Merged it for you Varun -- and thanks for your contribution. If you're looking to contribute regularly I will add you as a collaborator thanks!

2021-02-09 19:30 UTC, varunvjha commented
> Merged it for you Varun -- and thanks again for your contribution. If you're looking to contribute regularly I will add you as a collaborator thanks!

Sure, I'd love that.