Support for minValue & maxValue extension for the data type integer
google/android-fhir pull request #224
Opened 2021-02-08 18:45 UTC by kunjan8794

@jingtang10 @joiskash Please review the pr.

2021-02-08 18:51 UTC, kunjan8794 commented
@googlebot I signed it!

2021-02-08 19:02 UTC, kunjan8794 commented
@googlebot I signed it!

2021-02-08 19:18 UTC, kunjan8794 commented
@googlebot I signed it!

2021-02-08 23:33 UTC, jingtang10 commented
Thanks for the PR @kunjan8794. My first comment is that I think the validation logic should not be in the view holders. This is because there migth be multiple view types for the same data type (input box for integer but also slider for integer) but the validation logic for the same data type is always the same (there should be only one validator for integer type).

Can you please create a new validation package under datacapture and add the following interface (or something similar)?

```
interface Validator {
    fun validate(questionnaireItem: Questionnaire.Item, questionnaireResponseItem: QuestionnaireResponse.Item): ValidationResult
}
```

and the result class:

```
data class ValidationResult(val pass: Boolean, val errorMsgs: List<String>)
```

2021-02-08 23:34 UTC, jingtang10 requested changes
Thanks for the PR @kunjan8794. My first comment is that I think the validation logic should not be in the view holders. This is because there migth be multiple view types for the same data type (input box for integer but also slider for integer) but the validation logic for the same data type is always the same (there should be only one validator for integer type).

Can you please create a new validation package under datacapture and add the following interface (or something similar)?

```
interface Validator {
    fun validate(questionnaireItem: Questionnaire.Item, questionnaireResponseItem: QuestionnaireResponse.Item): ValidationResult
}
```

and the result class:

```
data class ValidationResult(val pass: Boolean, val errorMsgs: List<String>)
```

2021-02-09 05:58 UTC, kunjan8794 commented
@jingtang10 sure, I will do the changes as per the suggestion

2021-02-11 17:20 UTC, kunjan8794 commented
@jingtang10 Please review it

2021-02-12 01:13 UTC, jingtang10 requested changes

2021-02-12 01:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +                }
This is difficult to extend. You'll end up in a situation where you have way too many branches of `when` very quickly.

A couple of things to consider.

Create extensions to `Questionnaire.Item`. Have something like
```
internal fun Questionnaire.Item.maxValueExtension
    get() {
        ...
    }
```
this will simplify this logic.

Secondly, consider having more role-specific validators. i.e. max value validator, min value validator. So in your validator all you have to do is to apply all these validators to a question/answer and then aggregate the results.

2021-02-12 01:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    abstract fun validate(questionnaireItemViewItem: QuestionnaireItemViewItem, textInputLayout: TextInputLayout)
This shouldn't be abstract. I think this should be actually calling your validator (which callls sub validators such as min/max value validators).

2021-02-12 01:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +class QuestionnaireItemIntegerValidator : QuestionnaireItemValidator {
I'm not sure I agree with this abstraction. I think the logic of validation quickly becomes unmanageable across all data types...

Have you considered creating a validator for the max value extesions and just checks if the answer doesn't exceed the max value? and creating a min value validator that just checks the answer isn't less than the min value?

And then in your overall validator you just have this logic where you call all these validators, and aggregate the results by composing a validator result from all the error messages from the sub validators.

2021-02-12 09:42 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +class QuestionnaireItemIntegerValidator : QuestionnaireItemValidator {
My assumption here was, there will be different validators for different data types. So the interface QuestionnaireItemValidator can have the abstract validator that can be implemented by implementor classes of different data types such as integer, decimal, or even a date

2021-02-12 09:54 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    abstract fun validate(questionnaireItemViewItem: QuestionnaireItemViewItem, textInputLayout: TextInputLayout)
@jingtang10  I believe we have 'getText' and 'getValue' implemented separately for the individual data types, so in that case, shouldn't the method 'validate' be implemented separately as well? Because maybe we will need to handle the validation logic of the answer as per the data type? 

Please point out if I am missing something major here

2021-02-12 10:01 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +class QuestionnaireItemIntegerValidator : QuestionnaireItemValidator {
Sure, changing this

2021-02-12 10:01 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +    companion object {}
Done

2021-02-12 10:03 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +
done

2021-02-12 10:22 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireItemIntegerValidator.kt
> +class QuestionnaireItemIntegerValidator : QuestionnaireItemValidator {
Got it, done

2021-02-12 19:41 UTC, kunjan8794 commented
@jingtang10 please review the PR (hopefully finally :P)

2021-02-13 13:11 UTC, jingtang10 requested changes

2021-02-22 06:49 UTC, kunjan8794 commented
@jingtang10 Hi Jing, please review the recent code changes

2021-02-22 15:48 UTC, jingtang10 requested changes
Thanks @kunjan8794 ! Really good progress -- can you also add some tests please? Thanks!

2021-02-22 15:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +    }
I think there needs to be a `when` block for the different types because we will be adding support for `Decimal`, `Date`, `DateTime` etc.

2021-02-22 15:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +        }
I think you can use something like this: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/join-to-string.html

2021-03-11 17:59 UTC, kunjan8794 commented
@googlebot I consent.

2021-03-19 14:06 UTC, jingtang10 requested changes
Thanks I think the interface is much better.

Please rebase/merge to pull in the latest change on master. You'll need to adapt to the new hapi structures lib too.

2021-03-22 08:21 UTC, jingtang10 commented
@googlebot I consent.

2021-03-22 12:08 UTC, jingtang10 requested changes
Thanks @kunjan8794!

2021-03-22 12:08 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/ConstraintValidatorTest.kt
> +class ConstraintValidatorTest {
in the interest of avoiding exponential permutations of tests, i think we can reorganise this file in the following way:

1. have a test class that just tests the `QuestionnaireResponseItemValidator`. what it needs to test is that it aggregates the result of child validators.
2. have a test class that tests the max validator
3. have a test class that tests the min validator

2021-03-22 13:34 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    val messagesSeparator = '\n'
Inline, separated by a comma? Maybe? Or a space? @jingtang10

2021-03-22 17:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +    val messagesSeparator = '\n'
no i mean inline the variable `messageSeparator`. Also can you try using `System.getProperty("line.separator")` instead?

2021-03-24 12:22 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
@jingtang10 in that case can we just have one MinMaxValueValidator class that would validate both Min and Max values in case the QuestionnaireItem has any of the extensions?

2021-03-24 13:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
I think you should have

`ValueConstraintValidator` which `MaxValueConstraintValidator` and `MinValueConstraintValidator` extend.

The `ValueConstraintValidator` would basically compare the answer with the given value using a predicate and generate the error message. The min and max implementations would overload that predicate (one of them would be `>` and the other `<`) and generate different error message.

2021-03-24 14:56 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
This is what should be the template for the validators, am I right?

class MinValueValidator : ValueConstraintValidator(), ConstraintValidator { }

2021-03-24 20:00 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
Hi @jingtang10 , I have created a class ValueConstraintValidator.kt & it has a companion method -->

fun valueConstraintValidator(extension: Extension, questionnaireResponseItemBuilder: QuestionnaireResponse.QuestionnaireResponseItemComponent, operator: String): Boolean

Here, there is comparison based on the operator being passed from the MaxValueValidator and MinValueValidator.

Will this work? I am committing this, in case you want to have a look.

2021-03-25 00:24 UTC, jingtang10 requested changes

2021-03-25 00:24 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
Maybe something like this:

```
class ValueConstraintValidator(
  val url: String, 
  val predicate: (extension) -> Boolean,
  val messageGenerator: (extension) -> String
) : ConstraintValidator {
  override fun validate(...) {
    if (hasExtensionUrl(url)) {
      if (predicate(extension.value, questionnaireResponseItem.value)) {
        return (false, messageGenerator())
      } else {
        return (true, ...)
      }
    }
  } 
}

object MaxValueConstraintValidator = ValueConstraintValidator(
  ...,
  { a, b
    a > b
  },
  ...
)

...
```
?

2021-03-25 11:41 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
@jingtang10 i am just wondering how will we handle the different data types in the predicate function? We need to handle float & date as well.

2021-03-25 15:25 UTC, s-ayush2903 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +import com.google.common.truth.Truth.*
@kunjan8794 Can you please remove this wildcard import, maybe it is the cause for spotless failure

2021-03-25 19:08 UTC, kunjan8794 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +import com.google.common.truth.Truth.*
@s-ayush2903 thank you Ayush! That was simple :)

2021-03-25 19:26 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
@jingtang10 can you please review the recent code push? I have committed based on your comments, but thats for the integer type for now

2021-03-25 19:29 UTC, s-ayush2903 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +import com.google.common.truth.Truth.*
Oh apologies for inconvenience :sweat_smile:

2021-03-26 09:34 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +open class ValueConstraintValidator(
Is this class intended to only validate Integer constraints? In that case, I wonder if `IntegerValueConstraintValidator` is a more suitable name?

2021-03-26 12:13 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueValidator.kt
> +object MaxValueValidator : ConstraintValidator {
So let's keep this PR to integer type. For the future, we should create some utilities similar to in this class: https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemTypes.kt.

For now please do the following

- [ ] Create an issue to add support for other types
- [ ] Assign yourself
- [ ] Add a comment to link to that issue in the code

2021-03-26 12:35 UTC, jingtang10 approved these changes
Thanks - I think the interface is much better and extensible now.

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintValidator.kt
> +   * Validates the \`answer\`(s) in [questionnaireResponseItem] satify any constraints of the
fix the escape:

```suggestion
   * Validates the `answer`(s) in [questionnaireResponseItem] satify any constraints of the
```

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +    questionnaireResponseItemBuilder: QuestionnaireResponse.QuestionnaireResponseItemComponent
```suggestion
    questionnaireResponseItem: QuestionnaireResponse.QuestionnaireResponseItemComponent
```

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintValidator.kt
> +   * `questionnaireItem` and its child items.
```suggestion
   * [questionnaireResponseItem] and its child items are structurally consistent with the
   * [questionnaireItem] and its child items.
```

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +open class ValueConstraintValidator(
@kunjan8794 please add a todo and link to an issue here. But I don't think we need to rename this class if we have a follow-up PR after this PR.

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +object MaxValueValidator :
this is great, thanks :)

let's move these out of this file -- we'll probably end up with a bunch of these validators, they probably deserve to be in their own files.

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      validationResult.validationMessages.filter { it != null }.joinToString {
```suggestion
      validationResult.validationMessages.filterNotNull().joinToString {
```

actually why would you end up with `null`s in the list?

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/ConstraintValidatorTest.kt
> +class ConstraintValidatorTest {
still to do in this PR:
- [ ] have a test class that just tests the QuestionnaireResponseItemValidator. what it needs to test is that it aggregates the result of child validators.
- [ ] have a test class that tests the max validator
- [ ] have a test class that tests the min validator

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    assertThat(validateMaxValueViolation.validationMessages.size == 1).isTrue()
in general in unit tests we like our test cases to be as isolated as possible. you should be able to read the test failures and immediately get a sense of why the test is failing.

if you mix all these different cases in the same `@Test`, when you get a test failure you still need to come back to the code and debug to figure out what is failing.

so separate these into separate cases and give them descriptive names.

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  data class ValidationResult(var isValid: Boolean, val validationMessages: MutableList<String?>)
```suggestion
  data class ValidationResult(var isValid: Boolean, val validationMessages: List<String?>)
```

2021-03-26 12:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  }
```suggestion
= ValidationResult(
      validationResults.all { it.isValid },
      validationResults.mapNotNull { it.message }.toList()
    )
```

2021-03-26 12:36 UTC, jingtang10 requested changes
unapprove. sorry misclicked. please address the comments.

2021-03-27 00:35 UTC, jingtang10 requested changes

2021-03-27 00:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintValidator.kt
> +interface ConstraintValidator {
internal

2021-03-27 00:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +object QuestionnaireResponseItemValidator {
internal

2021-03-27 00:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  data class ValidationResult(var isValid: Boolean, val validationMessages: MutableList<String?>)
move this out of the class and keep it in the same file. and make it internal.

2021-03-27 00:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +open class ValueConstraintValidator(
internal

2021-03-27 00:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +object MaxValueValidator :
internal

2021-03-27 00:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +object MinValueValidator :
internal

2021-03-28 18:14 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      validationResult.validationMessages.filter { it != null }.joinToString {
@jingtang10 I think yeah, now we will not end up with null values here.

2021-03-28 18:19 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  data class ValidationResult(var isValid: Boolean, val validationMessages: MutableList<String?>)
@jingtang10 I am packing the not null values of ConstraintValidationResult into ValidationResult in the method "packConstraintValidationResults" and hence we needed a mutable list. Or else it wont allow me to use the method "add"

2021-03-28 18:24 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintValidator.kt
> +interface ConstraintValidator {
@jingtang10 ConstraintValidator is being implemented by ValueConstraintValidator and hence it gives me an error if I make ConstraintValidator internal.

2021-03-28 18:57 UTC, kunjan8794 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    assertThat(validateMaxValueViolation.validationMessages.size == 1).isTrue()
@jingtang10 done

2021-03-28 20:15 UTC, jingtang10 requested changes
Thanks @kunjan8794!

2021-03-28 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +  }
these two are actuall the same case. what you need is a case where both child validators fail. so you'll need a min validator with a high value e.g. 200 and a max validator with a low value e.g. 100 and an answer with a value in between e.g. 150 so both will fail.

2021-03-28 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +  private fun maxValueValidatorScenarioTester(
i think if you write idiomatic kotlin by using apply (see comment below) you don't really need this. just inline this function.

2021-03-28 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +/*
most comments in this file should be applied to the other two test files also

2021-03-28 20:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +  val predicate: (Int, Int) -> Boolean,
hm sorry i missed this in the last review - I think the predicate should be type agnostic. If you keep it this way, in the next PR you'll need to write a separate validator for each data type for max and min. that's too much.

so you should pass in the Type (which is the value in the extension) and the QuestionnaireResponseItemAnswerComponent which is the value in the answer. and in the predicate in the max and min validators you should have a when statement that compares each type.

```suggestion
  val predicate: (Type, QuestionnaireResponseItemAnswerComponent) -> Boolean,
```

2021-03-28 20:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +  val messageGenerator: (allowedValue: String) -> String
```suggestion
  val messageGenerator: (Type, QuestionnaireResponseItemAnswerComponent) -> String
```

2021-03-29 08:25 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +    validators.forEach {
@jingtang10 quick question, if I read this correctly, the logic here will always iterate over all possible validators on a field even when they're not specified for that field? In that case, I wonder if it would be better to only get the validation extensions defined by the field upfront instead of relying on the list?

2021-03-29 11:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +    validators.forEach {
yeah definitely. a map would be more efficient. but that can be a follow-up.

2021-03-30 12:22 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +  val predicate: (Int, Int) -> Boolean,
@jingtang10 Using "Extension" instead of "Type"

2021-03-30 12:22 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintValidator.kt
> +  val messageGenerator: (allowedValue: String) -> String
@jingtang10 Using "Extension" instead of "Type"

2021-03-31 10:12 UTC, jingtang10 requested changes

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    Truth.assertThat(validationResult.message.equals("Maximum value allowed is:200000"))
```suggestion
    Truth.assertThat(validationResult.message).isEuqalTo("Maximum value allowed is:200000")
```

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidator.kt
> +    url = "http://hl7.org/fhir/StructureDefinition/maxValue",
reminder to do this

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +    url = "http://hl7.org/fhir/StructureDefinition/minValue",
reminder to do this

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +  // Scenario 1 - answerValue is greater than maxValue
remove comments like this

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +  // Scenario 2 - answerValue is less than maxValue
remove

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +  //Scenario 1 - answerValue is less than minValue
remove

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +  // Scenario 2 - answerValue is greater than minValue
remove

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    Truth.assertThat(validationResult.isValid).isFalse()
import assertThat

2021-03-31 10:12 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    extensionMinValue.setValue(IntegerType(minValue))
do the same thing as you did in the other test files

2021-03-31 13:56 UTC, jingtang10 approved these changes
Thanks @kunjan8794! 🎉

Please address the final few nits before merging.

2021-03-31 13:56 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    assertThat(validateAggregationFromChildValidators.validationMessages.size == 2).isTrue()
```suggestion
    assertThat(validateAggregationFromChildValidators.validationMessages.size).isEqualTo(2)
```

2021-03-31 13:56 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    assertThat(validateAggregationFromChildValidators.validationMessages.isEmpty()).isTrue()
```suggestion
    assertThat(validateAggregationFromChildValidators.validationMessages).isEmpty()
```

2021-03-31 13:56 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    val validationResult =
new line

let's try to follow this structure:

```
test() {
  set up 
  set up 
  set up 

  the action to be tested

  assertions
  assertions
  assertions
}
```

2021-03-31 13:56 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    assertThat(validationResult.isValid).isFalse()
new line

2021-03-31 13:56 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    val validationResult =
new line

2021-03-31 13:56 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    assertThat(validationResult.isValid).isTrue()
new line

and same with the other 2 files.

2021-03-31 15:13 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +    assertThat(validationResult.message.isNullOrBlank()).isTrue()
does this work?
```suggestion
    assertThat(validationResult.message)isEmpty()
```

2021-03-31 15:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    val validateAggregationFromChildValidators =
```suggestion
    val validationResult =
```

2021-03-31 15:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    val validateAggregationFromChildValidators =
```suggestion
    val validationResult =
```

2021-03-31 16:27 UTC, merged