Made the selection drop-downs not editable
google/android-fhir pull request #2256
Opened 2023-10-10 08:48 UTC by kanahia1

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2228

**Description**
Made the selection drop-downs not editable

**Type**
Bug fix

**Screenshots (if applicable)**

![WhatsApp Image 2023-10-10 at 14 16 47_3670dc77](https://github.com/google/android-fhir/assets/114223204/a8b2589e-6585-494e-8e35-014cd11b66c5)

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-13 11:14 UTC, omarismail94 reviewed
Can you add an instrumentation test here:
https://github.com/google/android-fhir/blob/master/datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt

to test that if a user tries to edit the text, it does not work?

2023-10-15 19:50 UTC, kanahia1 commented
Hi @omarismail94, I have added a test case that checks if the user is able to type or not. Since when the user tries to type text, it will throw an exception as it is not editable.
Can you please review it.
[[`247696f` (#2256)](https://github.com/google/android-fhir/pull/2256/commits/247696f962b682cb3bdd1879e05dc5315efc9cb5)]

2023-10-16 09:43 UTC, omarismail94 commented
Thanks @kanahia1 ! The CLA check is failing, can you resolve that here: https://cla.developers.google.com/clas

2023-10-16 10:04 UTC, kanahia1 commented
Hi @omarismail94 , I have submitted my CLA.
Can you please check it now.

2023-10-16 12:14 UTC, omarismail94 commented
thanks @kanahia1, GitHib Actions is failing due to Spotless failue: https://github.com/google/android-fhir/actions/runs/6531828200/job/17733797033?pr=2256

can you run spotless apply and upload the commit?

2023-10-17 12:49 UTC, jingtang10 commented
Thanks for fixing this @kanahia1. Usually with this type of change, we would like to see before/after screenshots or before/after videos. This makes the review process much easier.

2023-10-17 13:25 UTC, kanahia1 commented
Oh sorry @jingtang10 , I will try to upload screen recording/ screenshots from now on!

Here's a video demonstrating the non-edit behavior of drop-downs.

https://github.com/google/android-fhir/assets/114223204/a774795b-d3fc-42ae-b264-f03ed8b5f3df

2023-10-22 16:01 UTC, kanahia1 commented
Hi @omarismail94 , I have made all the requested changes can you please review it

2023-11-08 16:36 UTC, jingtang10 requested changes

2023-11-08 16:36 UTC, jingtang10 commented on datacapture/src/main/res/layout/drop_down_view.xml
> +            android:focusableInTouchMode="false"
can you remove these two? we're only changing if this is editable but not if it's focasable?

2023-11-08 16:38 UTC, jingtang10 requested changes

2023-11-08 16:38 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt
> +      throw e
i think this is very fragile... this test case succeeds by assuming the error message is a certain string... if we upgrade the lib version this might start vailing.

in my view, this whole test case is not needed. can you please remove?

2023-11-12 18:40 UTC, kanahia1 commented on datacapture/src/main/res/layout/drop_down_view.xml
> +            android:focusableInTouchMode="false"
Sure! I have made changes in newer commits.

2023-11-20 18:05 UTC, jingtang10 approved these changes
thanks very much!

2023-11-30 14:01 UTC, omarismail94 commented
@kanahia1 the change you have is causing two instrumentation test to fail:

*  com.google.android.fhir.datacapture.test.views.DropDownViewHolderFactoryEspressoTest.shouldReturnFilteredDropDownMenuItems
* com.google.android.fhir.datacapture.test.views.DropDownViewHolderFactoryEspressoTest.shouldReturnFilteredWithNoResultsDropDownMenuItems

both fail due to:
```
Error performing 'type text(Coding)' on view 'view.getId()
```

I can replicate the test failure on my local machine. Can you do so on yours, and fix the broken tests?

2024-01-15 17:07 UTC, jingtang10 commented
closing this in favour of #2393

2024-01-15 17:07 UTC, closed without merging