Fix issue with duplicated IDs inside the Knowledge Manager
google/android-fhir pull request #2262
Opened 2023-10-12 19:29 UTC by vitorpamplona

Search by ID in the KnowledgeManager was used to return only the first reference. If the ID was duplicated in the DB, it would not filter by type and return the wrong one. This fixes it while also enforcing the ID to be a complete word in the URL

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-13 10:53 UTC, omarismail94 approved these changes

2023-10-13 18:57 UTC, jingtang10 requested changes
1) please add tests.
2) is this definitely the right fix? trying to match part of the url is still weird to me. if there is an id that is a substring of another id, the result isn't guaranteed... i have been a little worried about this actually regarding id and name... seems really confusing in our code.

2023-10-13 18:57 UTC, jingtang10 commented
let's not merge this as is - i think we still have issues to address here.

2023-10-17 15:37 UTC, jingtang10 commented
closing in favour of the new pr. thx vitor!

2023-10-17 15:37 UTC, closed without merging