Update the version of resource after updates are downloaded from the server
google/android-fhir pull request #2272
Opened 2023-10-17 11:27 UTC by aditya-07

Fixes #2271

**Description**
When updates are downloaded from the server, the database update code wasn't putting the new versionID of the updated resource into the table. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 
**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-17 11:57 UTC, jingtang10 requested changes

2023-10-17 11:57 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/MoreResources.kt
> +internal val Resource.versionId: String?
why is this change needed? something to do with java/kotlin interoperability?

2023-10-17 11:57 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +          versionId = resource.versionId ?: it.versionId,
please add a test

2023-10-17 14:18 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +          versionId = resource.versionId ?: it.versionId,
Done. 
Also, after our discussion I realised that having separate apis for local and remote updates would simplify code readability and correctness incase app developers add updated meta data to the locally changed resource that ideally should be ignored by engine as those values are assigned by server only.

2023-10-17 15:16 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +              addGiven("Tony")
lol

2023-10-17 15:17 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +      val remoteChange =
```suggestion
      val updatedPatient =
```

2023-10-17 15:17 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +      val remoteChange =
```suggestion
      val updatedPatient =
```

2023-10-17 15:20 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  open suspend fun updateChanges(entity: ResourceEntity, resource: Resource) {
do these have to be open?

2023-10-18 06:52 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  open suspend fun updateLocalChange(resource: Resource, timeOfLocalChange: Instant?) {
It is the same as the last downloaded remote version.

2023-10-18 06:59 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  open suspend fun updateRemoteChange(resource: Resource) {
Done

2023-10-18 07:05 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +      val lastUpdatedRemote: Date? = resource.meta.lastUpdated
done

2023-10-18 07:13 UTC, jingtang10 approved these changes

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
>    open suspend fun insertAllRemote(resources: List<Resource>): List<UUID> {
```suggestion
 suspend fun insertAllRemote(resources: List<Resource>): List<UUID> {
```

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +   * @param [resource] The resource with local (on device) updates.
```suggestion
   * @param [resource] the resource with local (on device) updates
```

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +   * @param [timeOfLocalChange] Time when the local change was made.
```suggestion
   * @param [timeOfLocalChange] time when the local change was made
```

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +   * @param [resource] The resource with the remote(server) updates.
```suggestion
   * @param [resource] the resource with the remote(server) updates
```

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +   * Updates the resource in the [ResourceEntity] and adds indexes.
```suggestion
   * Updates the resource in the [ResourceEntity] and adds indexes as a result of downloading the resource from server.
```

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +   * Updates the resource in the [ResourceEntity] and adds indexes.
```suggestion
   * Updates the resource in the [ResourceEntity] and adds indexes as a result of changes made on device.
```

2023-10-18 07:13 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  // WARNING : This is a private function and shouldn't be called directly.
```suggestion
```

2023-10-18 07:15 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  open suspend fun updateChanges(entity: ResourceEntity, resource: Resource) {
Removed open and made it private.

2023-10-18 08:03 UTC, merged