Add structure map helper classes
google/android-fhir pull request #2280
Opened 2023-10-22 13:18 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
The simple worker context cannot handle loading multiple NPM pacakges. This is needed for complex structure maps that have a two step process. Added the TransformSupportServices , ConceptMapEngine from MatchBoxServer to handle Custom Structure Definitions.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Feature 

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-10-22 14:14 UTC, jingtang10 approved these changes
thanks @joiskash

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ConceptMapEngine.kt
> +    }
```suggestion
ct.target.singleOrNull {!it.hasDependsOn() && !it.hasProduct()} ?.let {tt = it}
```

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/TransformSupportService.kt
> +    return cme.translate(source, conceptMapUrl)
namings in this class as well please

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/StructureMapUtilitiesTest.kt
> +  fun `perform extraction for ot`() {
expand ot

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/StructureMapUtilitiesTest.kt
> +    Assert.assertEquals("Bundle", targetResource.resourceType.toString())
we try to use the truth lib in this codebase. let's try to be consistent

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/StructureMapUtilitiesTest.kt
> +    Assert.assertEquals("Bundle", targetResource.resourceType.toString())
e.g. `assertThat(..).isEqualTo(...)`

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/StructureMapUtilitiesTest.kt
> +    Assert.assertEquals("Bundle", targetResource.resourceType.toString())
also make this assertion a bit more detailed. this is only checing the resource type.

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/StructureMapUtilitiesTest.kt
> +  fun `perform extraction for ot`() {
can you add a comment to explain what this test case is actually testing (it's very extensive):
1. it checks that we can load multiple packages into the context
2. it checks that we're able to retrieve a structure definition that's referenced by the structure map from one of the packages loaded into the context
3. ... maybe more?

2023-10-22 14:14 UTC, jingtang10 commented on datacapture/src/test/resources/QuestionnaireResponse_ot_all_answers.json
if these resources are used by only this test case, can we put them in the same directory?

i want to avoid a situation where in the test/resources directory we have loads of json files for different test cases, it's kinda hard to see which ones are for which test cases... and if we ever need to update the test cases or do some kind of cleanup, it'll be hard.

2023-10-22 14:16 UTC, dubdabasoduba commented
@jingtang10 @joiskash @nsabale7 I think we update this to probably use the KnowledgeManager to load the packages.

2023-10-30 08:16 UTC, jingtang10 requested changes
on-hold as per ben's comment

2023-10-30 08:28 UTC, jingtang10 commented
@joiskash as per this comment https://github.com/google/android-fhir/issues/2240#issuecomment-1774127729 is it possible to rewrite this pr using knowledge manager?

2023-12-06 11:46 UTC, joiskash commented
Yes I will work on it in a separate PR. Closing this for now.

2023-12-06 11:46 UTC, closed without merging