Add radio button to item control
google/android-fhir pull request #229
Opened 2021-02-09 14:46 UTC by joiskash

Just a low hanging fruit ;) . Added radio-button to the supported list of item-control extensions and fixed the OutlinedBox issue for drop down mentioned in #228

2021-02-09 16:28 UTC, jingtang10 commented
We ❤️ low hanging fruits!

2021-02-09 16:30 UTC, jingtang10 requested changes
Looks good. Please upate tests :)

2021-02-09 16:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensions.kt
> +internal const val ITEM_CONTROL_RADIO_BUTTON = "radio-button"
At a certain point this will need to become an enum... maybe when we have 3.

2021-02-09 23:02 UTC, jingtang10 approved these changes
some nits on test naming and one comment on test change.

2021-02-09 23:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
>      fun getItemViewType_choiceItemType_shouldReturnDropDownViewHolderTypeWithoutExtension() {
similarly please update the test name:

```suggestion
    fun getItemViewType_choiceItemType_moreAnswerOptions_shouldReturnDropDownViewHolderType() {
```

2021-02-09 23:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
>      fun getItemViewType_choiceItemType_shouldReturnDropDownViewHolderTypeWithoutExtension() {
and for the next test case

fun getItemViewType_choiceItemType_itemControlExtensionWithDropDown_shouldReturnDropDownViewHolderType() {

2021-02-10 07:36 UTC, merged

2021-02-10 22:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +            )
the line break here is odd. I would do

assertThat(questionnaireItemAdapter.getItemViewType(0)).isEqualTo(
    QuestionnaireItemViewHolderType.DROP_DOWN.value
)

2021-02-10 22:03 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +            )
line break:
```
assertThat(questionnaireItemAdapter.getItemViewType(0)).isEqualTo(
    QuestionnaireItemViewHolderType.RADIO_GROUP.value
)
```

2021-02-10 22:04 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensionsTest.kt
> +
nit: remove new line

2021-02-10 22:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemExtensionsTest.kt
> +            .build()
nit: this can be pulled up to the previous line. same with the `.build()` below

2021-02-10 22:06 UTC, jingtang10 commented
sorry i added a few styling comments -- if you can add the fixes in your next PR that'd be great. thanks!

2021-02-11 09:12 UTC, joiskash commented
Sure thanks I'll correct them in the next PR :)