Created QuantityViewHolderFactory to handle the Quantity Input type
google/android-fhir pull request #230
Opened 2021-02-09 16:17 UTC by MuhammadSalman-7214

2021-02-10 00:46 UTC, jingtang10 requested changes
Thanks for the PR! Please also add tests.

2021-02-10 00:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +
nit: remove new line

2021-02-10 00:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +    then we need to change the parent Factory*/
nit: use kotlin doc comment format: https://kotlinlang.org/docs/reference/kotlin-doc.html
```suggestion
/**
 * Inherits from QuestionnaireItemEditTextViewHolderFactory as only the numeric part of the quantity is being handled right now.
 * Will use a separate layout to handle the unit in the quantity.
 */
```

2021-02-10 00:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                                            .setInteger(Integer.newBuilder().setValue(it).build())
You need to set Quantity here rather than Integer. This will result in an integer type answer which isn't what we want with a quantity type question.

2021-02-10 00:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    return answer?.value?.integer?.value?.toString() ?: ""
This needs to read the value from the numeric part of the quantity. Not the integer.

2021-02-10 21:47 UTC, jingtang10 requested changes
I'm seeing some changes but please reply to the review comments.

And the main thing that is missing is the tests.

2021-02-10 21:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                                            .setQuantity(Quantity.newBuilder().setValue(Decimal.newBuilder().setValue(it).build()))
this line might be too long.

you might also need to run 
```
./gradlew spotlessApply
```
to format your code.

2021-02-10 21:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    true
nit: use named arguemnt to make it clear what this boolean is for: https://kotlinlang.org/docs/reference/functions.html#named-arguments

2021-02-11 08:51 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +
Done

2021-02-11 08:52 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +    then we need to change the parent Factory*/
Done

2021-02-11 08:52 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                                            .setInteger(Integer.newBuilder().setValue(it).build())
Done

2021-02-11 08:52 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    return answer?.value?.integer?.value?.toString() ?: ""
Done

2021-02-11 08:56 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    true
Done

2021-02-11 11:31 UTC, jingtang10 commented
Please add a test file similar to this: https://github.com/google/android-fhir/blob/master/datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactoryInstrumentedTest.kt

Once done please re-request review. Thanks!

2021-02-12 01:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +    then we need to change the parent Factory*/
I don't think this is done? Do you need to push new change?

2021-02-12 01:25 UTC, jingtang10 requested changes
thanks @MuhammadSalman-7214 !

please configure your IDE so that it only uses 4 spaces for indentation as per kotlin's style guide: https://kotlinlang.org/docs/coding-conventions.html#indentation

2021-02-12 01:25 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    return text.let {
```suggestion
                    return text.toDoubleOrNull()?.let {
```

2021-02-15 10:35 UTC, jingtang10 requested changes
Thanks Salman. Almost there!👍  A couple of comments in the code.

Througout the change the indentation is still a bit off -- please configure our IDE to use 4 spaces as per the kotlin style guide.

2021-02-15 10:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +    then we need to change the parent Factory*/
Looking at the latest commit this hasn't been updated. Can you do that please? Thanks!

2021-02-15 10:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    return text.let {
if the user has input text that isn't convertible to a number, you would get an invalid answer and you won't know it.

So the very least you can do is to try to convert it to double or null, and then convert it back to a string on line 42.

Also add a test case for this.

2021-02-16 06:50 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +                    return text.let {
Done

2021-02-16 12:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
> +    then we need to change the parent Factory*/
Done

2021-02-16 12:49 UTC, jingtang10 approved these changes
Thanks @MuhammadSalman-7214 for this PR! Approved with 2 nits. 👍

2021-02-16 12:49 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +                                        .build()
this can now be on the same line

2021-02-16 12:49 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +                                        .build()
this can now be on the same line

2021-02-16 12:56 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +                                        .build()
Done

2021-02-16 12:56 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +                                        .build()
Done

2021-02-16 12:58 UTC, merged