Initial Git Tips documentation for contributors
google/android-fhir pull request #2315
Opened 2023-10-26 17:42 UTC by vorburger

@jingtang10 the other day in the meeting you suggested "sharing git know how" - here's a start, is this useful?

@omarismail94 and @fredhersch FYI

2023-10-30 09:35 UTC, jingtang10 requested changes
@vorburger can you possibly incorporate the single-commit per review round point in bashir's doc: https://github.com/google/fhir-data-pipes/blob/master/doc/review_process.md? it's a great set of rules by the way we probably should incorporate most/all of them.

2023-10-30 09:35 UTC, jingtang10 commented on docs/git.md
> +in this case, as such branches get automatically deleted on merge of PRs.
why don't we just suggest contributors do this from the forked repo?

2024-07-11 12:24 UTC, vorburger commented
> @vorburger can you possibly incorporate the single-commit per review round point in bashir's doc: https://github.com/google/fhir-data-pipes/blob/master/doc/review_process.md? it's a great set of rules by the way we probably should incorporate most/all of them.

Done! Just pushed, plz have another look - better, like this? Merge?

2024-07-12 10:30 UTC, jingtang10 commented on docs/git.md
> +in this case, as such branches get automatically deleted on merge of PRs.
I just realised if you don't have write access it will actually create a change in your forked repo.

So few people have write permission in the repo I'm totally ok for us to not mention the second paragraph.

2024-07-12 10:32 UTC, vorburger commented on docs/git.md
> +in this case, as such branches get automatically deleted on merge of PRs.
@jingtang10 sure thing; done! Merge?

2024-07-12 10:37 UTC, jingtang10 commented on docs/contrib/git.md
> +in this case, as such branches get automatically deleted on merge of PRs.
```suggestion
```

2024-07-12 10:37 UTC, jingtang10 commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
I was wondering about this

```
Please try to have a single commit per each review round. When you want to send your PR, if you have multiple commits, [squash them](https://stackoverflow.com/questions/5189560/how-to-squash-my-last-x-commits-together). Also, when you are responding to review comments, make sure to create exactly one commit to address all required changes. You can use [--amend](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend) feature of git commit. This is to help your reviewer see all of the changes since last review round in a single commit.
```

In https://github.com/google/fhir-data-pipes/blob/master/doc/review_process.md which I particularly like. I think having clear review history is a boost to productivity. do you think we should recommend the contributor to create 1 commit for each round of review?

2024-07-12 10:38 UTC, vorburger commented on docs/contrib/git.md
> +in this case, as such branches get automatically deleted on merge of PRs.
@jingtang10 I think we may just have "crossed"? I've (just) rm this, in a34e8a5036eae0d026834eed3df2efaeeb0b783d, did you see? Please _Resolve Conversation_ if OK for you?

2024-07-12 10:39 UTC, jingtang10 commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
@bashir2 fyi

I'm ok to copy some of the tips bashir wrote actually.

2024-07-12 10:41 UTC, jingtang10 approved these changes
thanks for writing these tips Michael! I recognise this is of huge value to developers - and I'm also ok for us to iterate on this instead of dragging this out.

approved and fix/merge as you see fit. thanks!

2024-07-12 10:41 UTC, vorburger commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
Yeah I do agree with that recommendation! I was hoping the link(s, twice) to https://github.com/google/fhir-data-pipes/blob/master/doc/review_process.md  which I have added (did you see?) and the change I made to the recommended Git CLI commands (it originally used to recommend the `git commit --amend` flag, which I have removed now; did you notice?) the instructions now do lead to having a single commit per each review round. Do you think it's not clear enough as-is? I was trying to avoid copy/pasting from https://github.com/google/fhir-data-pipes/blob/master/doc/review_process.md ...

2024-07-12 10:41 UTC, jingtang10 commented on docs/contrib/git.md
> +in this case, as such branches get automatically deleted on merge of PRs.
resolving

2024-07-12 11:33 UTC, jingtang10 commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
i think the point is that whilst you might have many local commits - when you push you should squash them? or, whilst you do git commit -a -m the first time, you should git commit --amend in the following commits before replying to the review comments?

2024-07-12 12:20 UTC, vorburger commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
Oh, I see... tell you what, I'll resolve this comment thread so that we can merge this already, to have at least a first version of Git guidelines for contributors in. Then I'll follow-up with a new PR to refine this, and we can further discuss there. Hope that works for you!

2024-07-12 12:20 UTC, merged

2024-07-12 13:14 UTC, vorburger commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
==> 2617

2024-07-12 14:49 UTC, bashir2 commented on docs/contrib/git.md
> +       git commit -a -m "Incorporated review feedback."
Thanks @vorburger for creating this; and yes @jingtang10 the point of that recommendation is that after the review starts, there should exactly be one commit per review round. Otherwise it is very hard to follow what changes are done to address each comment (and sometimes even finding previous comments).