Support evaluation of variables, launchContext and other FHIR contexts for cqf-calculatedValue expressions
google/android-fhir pull request #2326
Opened 2023-11-02 10:24 UTC by LZRS

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2292 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-11-15 11:08 UTC, MJ1998 requested changes
Instead of changing the original questionnaire's extensions, we can resolve the min and max values on-fly, ie, when creating the QuestionnaireViewItem instance.

2023-11-15 11:08 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
This will modify the original questionnaire and we will lose the original extension.

2023-11-15 11:08 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> +
Having min and max value in QuestionnaireViewItem makes sense as ViewHolder's cant really evaluate these.

Instead of here I would evaluate it at the time of creation of QuestionnaireViewItem in QuestionnaireViewModel.
This is because I will have access to `expressionEvaluator`.

2023-12-15 12:41 UTC, jingtang10 requested changes

2023-12-15 12:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreTypes.kt
> +      ?.value as? Expression
can this be simplified? and the previous extension function can also be removed.

```suggestion
internal val Type.cqfCalculatedValueExpression
  get() =
    this
      ?.getExtensionByUrl(EXTENSION_CQF_CALCULATED_VALUE_URL)
      ?.value as? Expression
```

2023-12-15 12:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreTypes.kt
> +  return if (getValueString(this) != null) {
as @ellykits pointed out this can be rewritten using an elvis operator too.

2023-12-15 12:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreTypes.kt
>  private fun getValueString(type: Type): String? =
add kdoc here.

Returns localised or calculated value string for string or quantity types, and the default string for other types.

2023-12-15 12:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +  private fun ExpressionEvaluator.resolveCqfCalculatedValue(
why isn't this in the `ExpressionEvaluator` class?

2023-12-15 12:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +              if (evaluatedValue != null) extension.setValue(evaluatedValue)
should this value be set on the questionnaire response item?

2023-12-15 16:18 UTC, jingtang10 requested changes

2023-12-15 16:18 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +        questionnaireItem.extension
can you move this code to the individual validators? also extract a function to do this calculation.

2023-12-15 16:20 UTC, jingtang10 requested changes

2023-12-15 16:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private fun resolveCqfCalculatedValueExpressions(
i'm not sure about this approach of changing questionnaires. i'd rather we don't modify extensions in questionnaires as intermediary steps of our validation.

2024-02-14 10:04 UTC, MJ1998 requested changes
Its a little difficult to follow the changes.
Can you please update the description with major changes in this PR that supports the said feature ? Thanks.

2024-02-23 14:55 UTC, jingtang10 commented
@LZRS please address the above comments by replying and resolving them. just so that it's clear when everything's been addressed. thanks!

2024-02-27 17:50 UTC, jingtang10 commented
can you resolve the merge conflicts

2024-02-28 17:14 UTC, jingtang10 commented
thanks! will take a look shortly. in the future please also reply to comments you've addressed if you've addressed them and resolve them.

2024-03-04 16:00 UTC, jingtang10 requested changes

2024-03-04 16:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> -  private fun resolveCqfCalculatedValueExpressions(
hang on - isn't this a functional change? the cqf expression can be used for things like text.

see the cql expression on text field here:

https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-render.html

2024-03-04 16:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/AnswerExtensionConstraintValidator.kt
> +      val extensionValue = extensionCalculatedValue ?: extension.value
can you merge these two please? one variable is enough with elvis operator i think.

2024-03-04 16:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireViewItem.kt
> + * @param maxAnswerValue the inclusive upper bound on the range of allowed answer values.
just make it clear in the documentation these are needed for widgets that require behaviour change for min/max values (for example some widgets might naturally require these values to be rendered, e..g slider.)

2024-03-06 19:02 UTC, jingtang10 approved these changes

2024-03-13 18:45 UTC, merged