Api to clear all answers of questionnaire response.
google/android-fhir pull request #2329
Opened 2023-11-08 12:19 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2221 

**Description**
Provide api to clear all answers present in the questionnaire response.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-11-15 07:09 UTC, MJ1998 requested changes

2023-11-15 07:09 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    item.answer = listOf()
You can use `QuestionnaireResponse.allItems` defined in `MoreQuestionnaireResponse`
```suggestion
    questionnaireResponse.allItems().forEach { it.answer = emptyList() }
    modificationCount.update { it + 1 }
```

2023-11-16 06:29 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    item.answer = listOf()
done.

2023-11-16 16:06 UTC, MJ1998 reviewed
What about draftAnswerMap, modifiedQuestionnaireResponseItemSet, responseItemToAnswersMapForDisabledQuestionnaireItem ,etc ?
Do they need to be cleared as well ?

2023-11-17 09:12 UTC, santosh-pingle commented
> What about draftAnswerMap, modifiedQuestionnaireResponseItemSet, responseItemToAnswersMapForDisabledQuestionnaireItem ,etc ? Do they need to be cleared as well ?

I am trying to understand why it is necessary to clear these data structures individually. Is there any use case that requires attention? Wouldn't calling this function modificationCount.update { it + 1 } be sufficient?

2023-11-18 07:03 UTC, MJ1998 commented
I am suspecting that draftAnswers can still show up. 

Notice the `answersChangedCallback`. Whenever any answer changes we updated draftAnswer, modifiedQuestionnaireResponseItemSet and then do `modificationCount.update { it + 1 }`.
So I think draftAnswer and modifiedQuestionnaireResponseItemSet definitely needs to be cleared otherwise the obsolete values will still show. Try a testcase where you can have draftAnswers, eg, edittext.

Again, the cached answers in `responseItemToAnswersMapForDisabledQuestionnaireItem` should  also be cleared even though I don't think it will effect anything but no point keeping obsolete answers.

2023-11-22 08:46 UTC, santosh-pingle commented
> I am suspecting that draftAnswers can still show up.
> 
> Notice the `answersChangedCallback`. Whenever any answer changes we updated draftAnswer, modifiedQuestionnaireResponseItemSet and then do `modificationCount.update { it + 1 }`. So I think draftAnswer and modifiedQuestionnaireResponseItemSet definitely needs to be cleared otherwise the obsolete values will still show. Try a testcase where you can have draftAnswers, eg, edittext.
> 
> Again, the cached answers in `responseItemToAnswersMapForDisabledQuestionnaireItem` should also be cleared even though I don't think it will effect anything but no point keeping obsolete answers.

Ohhh!, thats correct, it requires to clear draftAnswer or else it keep showing partial answer in the textfields, e.g partial date answer in the datePicker. Basically, clears dataStructures which get modified by answerChangeCallback.

2023-11-30 17:10 UTC, merged