Add fhirpath supplements
google/android-fhir pull request #2346
Opened 2023-12-01 07:39 UTC by maimoonak

Fixes #https://github.com/google/android-fhir/issues/2163

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-12-04 22:49 UTC, jingtang10 requested changes
hi maimoona - thanks for this great work!

2023-12-04 22:49 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +          dependentVariables,
add named parameters

2023-12-12 17:17 UTC, jingtang10 commented
i don't hink this pr builds with the latest changes. can you fix please @maimoonak? thanks

2023-12-15 12:00 UTC, jingtang10 approved these changes
Please double-check the code paths going through `evaluateExpression` and `evaluateVariable` and see if there's any more unification you can do.

Thanks for this PR! Great job!

2023-12-15 15:15 UTC, maimoonak commented
> Please double-check the code paths going through `evaluateExpression` and `evaluateVariable` and see if there's any more unification you can do.
> 
> Thanks for this PR! Great job!

https://github.com/google/android-fhir/issues/2373 The methods are covered by a good amount of test which indeed is important to ensure complex variable evaluation validation. We need to figureout a way to keep unit tests. (VisibleForTesting annotation not working)

2023-12-20 11:18 UTC, merged