Save the help card visibility in a state flow
google/android-fhir pull request #2357
Opened 2023-12-07 08:58 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2356

**Description**
1. Create a state flow that keeps the link ID of the help card, if the link ID of that help card exists in the state flow, then that help card is currently visible
2. Create a callback to save the help card visibility to the state flow

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-12-15 16:49 UTC, jingtang10 requested changes

2023-12-15 16:49 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<String>> =
link ids don't actually uniquely identify (questionnaire item, questionnaire response item) pairs, see https://build.fhir.org/questionnaireresponse.html#link.

i think this set should probably be of type questionnaire response.

2023-12-15 21:18 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<String>> =
@jingtang10 yeah that works too

2023-12-16 03:58 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<String>> =
or, the set could be of type questionnaire item, since the help code is tied to it.

2023-12-22 09:31 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<String>> =
updated to questionnaire item type

2023-12-22 09:34 UTC, FikriMilano commented
@jingtang10 this is ready for review again.
Also, please have a nice holiday :D

2024-01-02 16:59 UTC, jingtang10 requested changes

2024-01-02 16:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<QuestionnaireItemComponent>> =
this should be questionnaire response item component instead.

in the case of repeated groups, or repeated nested items, you would end up with multiple questions corresponding to the same questionnaire item. in these cases it would not make sense to show/hide help card for all of them at once.

2024-01-02 16:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    { shouldBeVisible, linkId ->
```suggestion
    { shouldBeVisible, questionnaireResponseItem ->
```

2024-01-02 16:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +          helpCardStateChangedCallback.invoke(false, helpCardItem)
```suggestion
          helpCardStateChangedCallback(false, helpCardItem)
```

2024-01-02 16:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreHeaderViews.kt
> +          helpCardStateChangedCallback.invoke(true, helpCardItem)
```suggestion
          helpCardStateChangedCallback(true, helpCardItem)
```

2024-01-02 16:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<QuestionnaireItemComponent>> =
does this actually need to be a mutable state flow? it's not really being listened to by the ui - it's simply used to populate the questionnaire view item right?

this can just be a private set.

2024-01-03 09:07 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<QuestionnaireItemComponent>> =
ah I see, okay

2024-01-03 09:15 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val openedHelpCardSet: MutableStateFlow<MutableSet<QuestionnaireItemComponent>> =
yeah, we can have it as a set

2024-01-19 12:53 UTC, FikriMilano commented
@jingtang10 this PR is ready for review

2024-01-31 15:31 UTC, jingtang10 approved these changes

2024-02-01 01:25 UTC, merged