Handle op:add for same path in patch
google/android-fhir pull request #2370
Opened 2023-12-12 13:31 UTC by omarismail94

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2342

**Description**
When merging JSON patches:
    *  "replace" and "remove" operations from the second patch will overwrite any existing operations for the same path.
   *  "add" operations from the second patch will be added to the list of operations for that path, even if operations already exist for that path.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-12-13 11:00 UTC, kelvin-ngure commented
@omarismail94 since mergePatches is being called in a reduce function, the first time it runs, the parameters will receive strings withthis sort of structure (the below are patch strings)

[{"op":"add","path":"\/member\/-","value":{"entity":{"reference":"Patient\/dbe7936d-a1bc-4593-b219-025f34a8a8bf"}}}]
[{"op":"add","path":"\/member\/-","value":{"entity":{"reference":"Patient\/e4ebe735-cbf5-4365-b8ad-0169466d51r9"}}}]

The output of the mergePatches function has this structure since it is create from an Array Node (I use the word Patch String in place of the above objects)

[
    Patch string,
    Patch String,
]

Therefore, the next time the merge patches function is run (e.g when there are more than 2 LocalChange), the parameter for firstPatch will receive the correct data type but not the same structure. The first time, it was like this => [{}] but subsequent times it will be like this => [[{}], [{}]]. 

Will the op.get("path") still work? I assume that due to the nesting, path won't be recognized as a key. Thoughts?

2023-12-13 11:50 UTC, kelvin-ngure requested changes

2023-12-13 11:50 UTC, kelvin-ngure commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +    patchNode1.forEach { op ->
@omarismail94 

could we rename this op to patch or patchNode or something patch related? Calling it op can cause confusion and even forced us to name the actual op in the patch as opType

2023-12-14 09:53 UTC, omarismail94 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +    patchNode1.forEach { op ->
will do!

2023-12-14 09:54 UTC, omarismail94 commented
> Edit: Below the *** was a concern had but I was wrong since the code is extracting the object from the list. And at the end, only the objects are inserted into the output array. So the structure during the reduction stays the same.
> 
> @omarismail94 since mergePatches is being called in a reduce function, the first time it runs, the parameters will receive strings with this sort of structure (the below are patch strings)
> 
> [{"op":"add","path":"/member/-","value":{"entity":{"reference":"Patient/dbe7936d-a1bc-4593-b219-025f34a8a8bf"}}}] [{"op":"add","path":"/member/-","value":{"entity":{"reference":"Patient/e4ebe735-cbf5-4365-b8ad-0169466d51r9"}}}]
> 
> The output of the mergePatches function has the below structure since it is created from an Array Node (I use the word Patch String in place of the above objects)
> 
> [ Patch string, Patch String, ]
> 
> Therefore, the next time the merge patches function is run (e.g when there are more than 2 LocalChange), the parameter for firstPatch will receive the correct data type but not the same structure. The first time, it was like this => [{}] but subsequent times it will be like this => [[{}], [{}]].
> 
> Will the op.get("path") still work? I assume that due to the nesting, path won't be recognized as a key. Thoughts?

@kelvin-ngure thanks for clarifying!  i assume the change fixes the issue you have then?

2023-12-14 10:33 UTC, kelvin-ngure commented
@omarismail94 yes it looks like it will work for my highlited usecase

2023-12-21 11:08 UTC, MJ1998 reviewed
Have you tried using latest version of jsonpatch ?

I think for each activity the path generated should be unique and not `activity/-`

We are using 1.13 but 1.9 is also available. I haven't checked if they have solved this problem or not but worth verifying.

2024-02-07 07:58 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +    val secondPatchNode: JsonNode = JsonLoader.fromString(secondPatch)
i think node is fine

2024-02-07 07:58 UTC, jingtang10 approved these changes

2024-02-07 09:38 UTC, merged