Add API call options to the FhirOperator for OpenSRP
google/android-fhir pull request #2383
Opened 2023-12-19 15:05 UTC by vitorpamplona

Offers additional options to evaluate measures and plan def apply in the FhirOperator

**Type**
Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-12-21 10:08 UTC, MJ1998 requested changes
In generateCarePlan APIs,
can we add options for the third API as well:-

```
fun generateCarePlan(
    planDefinitionId: String,
    subject: String,
    encounterId: String?,
  ): IBaseResource {
  ```

2023-12-21 10:08 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +        report.setSubject(Reference(subjectId))
practitioner and subjectId should mandatorily be in either of the following formats for `Reference`:-
(e.g. "Patient/123" or "http://example.com/Patient/123")

From comment above we can use `practitionerWithType` and `subjectWithType` here!

2023-12-21 10:08 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +    practitioner: String? = null,
Not sure how `MeasureProcessor` evaluates when both practitioner and subject Id is given.
If it assumes `MeasureEvalType.SUBJECT` even when practitioner is given then is it wrong ?

Consider dividing this API into 2 : `evaluateMeasureForSubject` & `evaluateMeasureForPopulation` ?

2023-12-21 10:08 UTC, MJ1998 commented
Thanks @vitorpamplona for the PR. This looks necessary!

Requesting to create an issue and tag it here as well! Thanks.

2023-12-21 13:48 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +    practitioner: String? = null,
Yep, that seems to be a pattern in most of the server tests I have seen. Practitioner overrides subject.

2023-12-21 14:05 UTC, vitorpamplona commented
The 

```
fun generateCarePlan(
    planDefinitionId: String,
    subject: String,
    encounterId: String?,
  ): IBaseResource {
```

signature is deprecated. I am not sure if we should change it at this point.

2023-12-21 16:28 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +    practitioner: String? = null,
I think SUBJECT overrides POPULATION (Practitioner)

```
MeasureEvalType evalType = (MeasureEvalType)MeasureEvalType.fromCode(reportType)
      .orElse(subjectIds.get(0) != null && subjectIds != null && !subjectIds.isEmpty() 
        ? MeasureEvalType.SUBJECT : MeasureEvalType.POPULATION);
```
Infact now I think it's always SUBJECT even when we give practitioner in subjectIds.
[PS: The check `subjectIds.get(0) != null` should be at last]

2023-12-21 16:38 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +    practitioner: String? = null,
Sure, having a subject will make the report a Subject type. That subject can then be a Patient, Group or the Practitioner (just another type of group). 

But if you have a practitioner AND a patient at the same time in this API, the report will be about the practitioner.

2023-12-21 16:38 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
I saw this function `evalTypeToReportType` in R4MeasureProcessor. Seems like MeasureEvalType.POPULATION is mapped to MeasureReportType.SUMMARY but for POPULATION, the subject is null.

Not sure if this function is even being used because I am not able to find any usage.

Also there are other non-individual types like SUBJECTLIST, PATIENTLIST as well .

What is intended here ?

2023-12-21 16:38 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +        /* additionalData = */ null,
Since now we changing the API, might as well add `additionalData` as an optional parameter in the API ?

2023-12-21 17:00 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +        /* additionalData = */ null,
My initial impression is that this should be given by the Engine module, but I am not sure if we will need it in the SDK.

2023-12-21 17:10 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
> Seems like MeasureEvalType.POPULATION is mapped to MeasureReportType.SUMMARY but for POPULATION, the subject is null.

Correct, then the server-side folks set the reference in a separate class: 

https://github.com/cqframework/clinical-reasoning/blob/6ee71b792b1dc32ba9e077831dd89a5462077200/cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureService.java

PATIENTLIST should not be a thing. If it is, it's some non-specified case. Details here: https://hapifhir.io/hapi-fhir/docs/clinical_reasoning/measures.html

2023-12-24 11:29 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +    practitioner: String? = null,
Hence the practitioner check first! Cool.

2023-12-24 11:44 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
My point is that report.type will be SUMMARY when subject is null. 
This if condition will never satisfy, right ?

2023-12-24 11:45 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +        /* additionalData = */ null,
My guess would be if this API will be available to be used independent of fhir engine then `additionalData` should also be an API parameter.

2023-12-24 22:10 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +        /* additionalData = */ null,
Cool, I just added it.

2023-12-24 22:18 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
In theory yes, in practice users can force the `reportType` from params. I am not sure why they would do this, but it is certainly an option.

2023-12-27 08:19 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
I think we should handle it!
Maybe just adding another require statement that both reportType and subjectId cannot be null ?

2023-12-27 13:09 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
But both can be null at the same time.

2023-12-27 13:43 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +      report.setSubject(Reference(subject))
oh yeah my bad. this looks good!

2023-12-27 13:43 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun generateCarePlan(
can we not have just 1 API to accept all three: id, canonical and plandefinition?

internally the plandefinitionprocessor does a "resolvePlanDefinition"

2023-12-27 14:00 UTC, vitorpamplona commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun generateCarePlan(
We could, but the knowledge manager is changing IDs on inserting so it's not ideal to call these functions by id (that's why it is deprecated). We could have one function with the other two. But this seems more explicit to the user that he/she has to choose one of them. It's a similar issue to the other params, but here we know how it should operate.

2023-12-27 14:30 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun generateCarePlan(
Fair enough.

2023-12-27 14:30 UTC, MJ1998 approved these changes
LGTM

2023-12-27 14:32 UTC, MJ1998 commented
Also create an issue (if it does not exist) and tag it.

2024-01-08 16:30 UTC, jingtang10 approved these changes
thanks vitor!

2024-01-09 16:10 UTC, vitorpamplona commented
@jingtang10 can you enable auto-merge again here?

2024-01-09 17:13 UTC, merged