Update questionnaire buttons in xml fragment
google/android-fhir pull request #2384
Opened 2023-12-20 11:44 UTC by sharon2719

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**    git push --set-upstream origin questionnaire-content-customization

Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2023-12-21 09:33 UTC, MJ1998 requested changes

2023-12-21 09:33 UTC, MJ1998 commented on datacapture/src/main/res/values/styles.xml
> +        <item name="questionnaireButtonStyle">@style/Questionnaire.ButtonStyle
```suggestion
        <item name="questionnaireButtonStyle">Questionnaire.ButtonStyle
```

With style it gives me error: Cannot resolve symbol '@style/Questionnaire.ButtonStyle'

2023-12-21 16:46 UTC, MJ1998 commented
Thanks. Please add a description to the solution!

2023-12-22 09:46 UTC, sharon2719 commented
@MJ1998  I did further testing and noted that if the `@style` is not added then it fails with this error `Android resource linking failed
com.google.android.fhir.demo-mergeDebugResources-60:/values/values.xml:7034: error: expected reference but got (raw string) Questionnaire.ButtonStyle.
error: failed linking references.`. However when its added it works just fine

2023-12-24 11:20 UTC, MJ1998 commented
@sharon2719 

You are right! My IDE was throwing some error. After invalidate-restart its good.

2023-12-24 11:21 UTC, MJ1998 approved these changes
LGTM

2024-02-02 06:36 UTC, sharon2719 commented
@MJ1998 Kindly prompt kokoro

2024-02-06 02:58 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name="questionnaireButtonStyle">@style/Questionnaire.ButtonStyle
@sharon2719 did you address this comment?

2024-02-06 02:58 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name= "android:layout_width">wrap_content </item>
```suggestion
        <item name= "android:layout_width">wrap_content</item>
```

2024-02-06 02:58 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name= "android:layout_height">wrap_content </item>
```suggestion
        <item name= "android:layout_height">wrap_content</item>
```

2024-02-06 02:58 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name= "android:layout_width">wrap_content </item>
```suggestion
        <item name= "android:layout_width">wrap_content</item>
```

2024-02-06 02:58 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name= "android:layout_height">wrap_content </item>
```suggestion
        <item name= "android:layout_height">wrap_content</item>
```

2024-02-06 07:26 UTC, sharon2719 commented on datacapture/src/main/res/values/styles.xml
> +        <item name="questionnaireButtonStyle">@style/Questionnaire.ButtonStyle
@jingtang10 Yes this was addressed. @MJ1998 had an issue with his machine while testing but after an update it was sorted and working as expected

2024-02-13 07:44 UTC, ellykits approved these changes
LGTM

2024-02-13 10:08 UTC, santosh-pingle submitted a review, later dismissed
I think we can remove the visibility attribute change, as it get handled through the flags in the configuration.

2024-02-13 10:08 UTC, santosh-pingle commented on datacapture/src/main/res/values/styles.xml
> +        <item name="android:visibility">visible</item>
```suggestion
```

2024-02-14 09:09 UTC, MJ1998 commented
Build fails on spotless apply.
Can you run spotless and raise a commit ?
Thanks @sharon2719

2024-02-27 17:07 UTC, merged