Synchronize sync workers
google/android-fhir pull request #2385
Opened 2023-12-21 20:09 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2361 

**Description**
We use lock-and-release mechanism to run only 1 worker at any time.
This implementation handles 2 scenarios:-
1. Periodic sync is running and one time sync is triggered
2. One time sync is running and periodic sync kicks in

Additionally to ensure that one time request is processed despite a running worker we return Result.retry and also set `syncLockedRetryConfiguration` instead of the default one.

However, for second scenario, which I think is very unlikely, the WorkManager will keep retrying periodic sync in every 30 seconds as we cannot set `syncLockedRetryConfiguration` for periodic work.

**Alternative(s) considered**
Another alternative is to keep same work names for both request. This will enable WorkManager to run only 1 work at a time. But  the periodic worker won't run after as it's over-written due to having the same name [Refer [PR's description](https://github.com/google/android-fhir/pull/2053)]. To solve this we will need to cancel and re-enqueue the old periodic work once one time work finishes. 
This solution works well for the second scenario as well but I don't like the idea of cancelling and re-enqueueing periodic work requests.

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-01-29 09:46 UTC, aditya-07 requested changes
Please add a test to check the change.

2024-01-29 16:46 UTC, MJ1998 commented
I am not sure if automation test for this is a good idea. Because it takes lot of execution time to be able to verify the synchronicity of any concurrent jobs.  See how concurrent behavior is verified [here](https://medium.com/mobile-app-development-publication/mutex-for-coroutines-5f4a4ca60763).

Such long execution time, however, is very likely in case of long sync time in an actual app

@aditya-07

2024-01-30 11:15 UTC, jingtang10 approved these changes
please feel free to merge once tested manually again.

2024-01-30 11:15 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +      val result = synchronizer.synchronize()
i actually think the mutex can be just inside the synchronizer's synchronize function instead. in general we want to keep the locked code path as minimum as possible. and i think it's unnecessary to lock the rest of this function.

2024-01-30 13:26 UTC, aditya-07 approved these changes

2024-01-31 07:07 UTC, MJ1998 commented
I figured how to test the mutex locking.
@aditya-07 @jingtang10

2024-01-31 08:04 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +      val result = synchronizer.synchronize()
Moved. Also added test.

2024-01-31 09:32 UTC, aditya-07 requested changes

2024-01-31 09:32 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt
> +      val result = fhirSynchronizer.synchronize()
The test should call `synchronize()` on 2 different `FhirSynchronizer` objects to simulate two workers getting started concurrently. 
Also, you should be able to provide Test downloader / uploader (with longer delay in first synchronizer) instead of mock to simulate a real scenario and use the `SyncJobStatus` maybe to assert that the second synchronize job doesn't start before the end of first synchronize job.

2024-01-31 09:32 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt
> +            }
We shouldn't depend on the exception message as the verbiage may change in subsequent versions (which comes from kotlin framework) causing the test to fail.

2024-01-31 09:57 UTC, MJ1998 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt
> +      val result = fhirSynchronizer.synchronize()
Done.

2024-01-31 09:58 UTC, MJ1998 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSynchronizerTest.kt
> +            }
Changed the test.

2024-01-31 13:39 UTC, aditya-07 approved these changes

2024-01-31 13:39 UTC, merged

2024-01-31 13:48 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
>    }
@MJ1998 Forgot to add this earlier, but could you please add doc to the function explaining its locking.

2024-01-31 14:13 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
>    }
Added in #2417