Add enablement operators EQUALS and NOT_EQUAL_TO
google/android-fhir pull request #239
Opened 2021-02-14 03:02 UTC by pld

Closes https://github.com/google/android-fhir/issues/236

Based on [Valueset-questionnaire-enable-operator](https://www.hl7.org/fhir/valueset-questionnaire-enable-operator.html) `EQUALS` is true if any answers contain the `enableWhen` answer. The definition of Not Equals is oddly worded, coded as `NOT_EQUAL_TO` is the negation of `EQUALS`.

2021-02-14 03:03 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +        responseItem.answerList.map { it.value.toByteString() }.contains(
Is there a better way to equality? `values` with the same content are not equal

2021-02-14 03:04 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +            QuestionnaireItemOperatorCode.Value.NOT_EQUAL_TO ->
There was no `NOT_EQUALS`  enum

2021-02-14 13:20 UTC, jingtang10 requested changes
Thanks Peter for your contribution 👍  just a couple of high-level comments. Haven't looked through the tests yet.

2021-02-14 13:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +                responseItemContainsAnswer(responseItem, enableWhen)
Looking at rest of the opeartors: https://www.hl7.org/fhir/valueset-questionnaire-enable-operator.html it probably would make a lot of sense to provide some kind of predicate function here.

so you'd have in here:
```
responseItem.contains(enableWhen.operator.toPredicate())
```
and then have two extension functions.

the first extension function converts an enable when operator to a predicate
```
private fun Questionnaire.Item.EnableWhen.OperatorCode.toPredicate(): (QuestionnaireResponse.Item.Answer) -> Boolean {
    ...
}
```

and the second extension function takes that predicate to figure out if any answer in the answer list in the response item satisfies that predicate:
```
private fun QuestionnaireResponse.Item.contains(predicate:(QuestionnaireResponse.Item.Answer) -> Boolean) {
    ...
}
```
I think as a result this `when` block will be moved to the `toPredicate` extension function, and the code in this function will be simplified.

2021-02-14 13:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +        responseItem.answerList.map { it.value.toByteString() }.contains(
hm I think this doesn't equal because they're different classes (`Questionnaire.Item.EnableWhen.AnswerX` and `QuestionnaireResponse.Item.Answer.ValueX`)... The right way of doing this probably write a utility function to compare each data type (since we don't actually know the type here). I'm happy for that to be a follow-up (or just create an issue)

2021-02-14 20:19 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +            (responseItem.answerCount > 0) == enableWhen.answer.boolean.value else
this operator seems like a special case

2021-02-14 20:19 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +private fun Questionnaire.Item.EnableWhen.toPredicate(): (QuestionnaireResponse.Item.Answer)
because the predicate depends on the value of the EnableWhen.Answer, I wrote this extending EnableWhen instead of EnableWhen.operator. This could take the answer as an additional argument, hmm maybe there's a way to clean this up

2021-02-14 20:19 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +                this.answer.toByteString() == it.value.toByteString()
Kinda suspicious, I'm sure I'm missing a better way with the similarity here to line 123.

I looked a bit at how to write the type aware comparisons, having this return only the operator could help to remove the need for the answer here (but then the answer would need to be passed to contains I think) and the type aware comparisons could go in contains, using the operator.

Or, and probably better,  have a helper here that takes the operator and the answer, then runs the type aware comparisons

2021-02-15 15:14 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ValueForType.kt
> +package com.google.android.fhir.datacapture
is there better name for this file? not sure how best to name structure in kotlin projects

2021-02-15 18:05 UTC, jingtang10 requested changes
Thanks Peter!

2021-02-15 18:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +    fun evaluate_expectsAnswer_answerEqualOne_shouldReturnTrue() {
the way i think about these test cases is that: we'll cover each operator in positive and negative cases, and then we'll have some tests that cover cases with multiple answers regardless of operators. having these cases is fine, but i kinda feel they'll really make the number of test cases explode without improving test coverage (since all cases should already have been hit).

as an example: we also have the ANY / OR enable when behaviors, does it mean the number of tests cases will x2? I don't think that'd be manageable.

2021-02-15 22:22 UTC, jingtang10 approved these changes
🎉🎉🎉

approved. just a few nits. thanks again peter!

2021-02-15 22:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemTypes.kt
> + * Used to retrieve the value to set the field in the extracted FHIR resource.
this line can be removed since it's now a utility function used for various things.

2021-02-15 22:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemTypes.kt
> + * Used to retrieve the value to set the field in the extracted FHIR resource.
and this.

2021-02-15 22:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +            (responseItem.answerCount > 0) == enableWhen.answer.boolean.value else
hm. yeah. damn. 😛 

nit: can you please just reformat this a little bit

```
return if (...) {
    ...
}
else {
    ...
}

2021-02-15 22:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +        (QuestionnaireResponse.Item.Answer) -> Boolean {
nit: this can be on the previous line

2021-02-15 22:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +        when (val operator = enableWhen.operator.value) {
i think the structure here should be changed. here a function closure is returned... and the branching of operator happens when the function closure predicate is called. in other words if you need to evaluate multiple answers, each time you check which operator and choose the correct comparison logic. that seems logically redundant and an (admitedly tiny tiny) performance penalty.

2021-02-15 23:06 UTC, pld commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +        when (val operator = enableWhen.operator.value) {
cool yea definitely makes sense to keep the closure tight, there's probably room later for a further refactor here to get rid of some redundancy, was looking at the `compareTo` function, but couldn't get to a better place, will push in

2021-02-15 23:08 UTC, jingtang10 commented
i'm not sure this bot is working...

2021-02-15 23:09 UTC, jingtang10 commented
it seems to think your email address is pld@users.noreply.github.com for some reason...

2021-02-15 23:11 UTC, pld commented
Oh yea that's correct w/the email privacy option on, let me turn it off and rebase my commits to add my email...

2021-02-15 23:15 UTC, pld commented
should be set to peter@ona.io now

2021-02-16 12:20 UTC, jingtang10 commented
from what I can see peter@ona.io is still in the state of `need_sender_cla`... urg i'm so sorry about this faff. can you check again?

2021-02-17 17:01 UTC, pld commented
@googlebot I signed it!

2021-02-17 17:03 UTC, merged