Improve Dropdown Behavior in Questionnaire Items
google/android-fhir pull request #2393
Opened 2023-12-29 14:36 UTC by qaziabubakar-vd

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes # https://github.com/google/android-fhir/issues/2228

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-01-16 06:06 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        )
```suggestion
      autoCompleteTextView.doAfterTextChanged {
          if (it.isNullOrBlank()) {
            Handler(Looper.getMainLooper())
              .postDelayed(
                {
                  if (autoCompleteTextView.isPopupShowing.not()) {
                    autoCompleteTextView.showDropDown()
                  }
                },
                100,
              )
          }
        }
```

2024-01-16 06:06 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                    100,
is there any specific reason we are adding delay here?

2024-01-16 06:06 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +            if (isDropdownEditable) {
Can we please add android test or unit test to just see dropdown autotextview is not editable

2024-02-13 07:31 UTC, ellykits commented
@qaziabubakar-vd Any updates on this PR? Update the PR with the functionality to reset/clear the selected item.

2024-02-13 08:07 UTC, qaziabubakar-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                    100,
The delay ensures proper synchronization with the `AutoCompleteTextView`'s internal state after text clearing, preventing potential conflicts and ensuring a smoother dropdown display. Without the delay, the `showDropDown()` method gets called before the AutoCompleteTextView's internal state is fully updated after text clearing.

2024-02-13 10:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                    100,
```suggestion
                autoCompleteTextView.post(
                    {
                      if (autoCompleteTextView.isPopupShowing.not()) {
                        autoCompleteTextView.showDropDown()
                      }
                    }
```

Can you check if this helps. Anyways, we should just do a `post` / `postDelayed` on the `autoCompleteTextView`

2024-02-26 15:48 UTC, jingtang10 requested changes
This PR has zero tests right now. Can you add some tests?

2024-02-26 15:56 UTC, jingtang10 requested changes

2024-02-26 15:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +              }, 100
is there a way to avoid using this delay? why is it here? can you add some comments?

2024-02-26 15:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +          autoCompleteTextView.text = null
don't you have to clear the answer in the questionnaire view item too?

2024-02-28 07:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +      private var isDropdownEditable = true
Actually, we need to handle below use case where item can be readonly

```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "1",
      "type": "choice",
      "readOnly" : true,
       ....
```

2024-02-28 07:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +          setReadOnly(false)
ditto.

2024-02-28 07:31 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        autoCompleteTextView.isEnabled = isDropdownEditable
Is it insufficient to only enable/disable TextInputLayout or AutoCompleteTextView? We also need to enable/disable state of the clear icon based on the item's readOnly property.

2024-02-28 10:49 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                if (autoCompleteTextView.isPopupShowing.not() && isDropdownEditable) {
You could try adding 10-12 dropdown items to the questionnaire and observe the behavior.

Selecting one dropdown item in a questionnaire form shouldn't trigger popups for other dropdown items.

2024-03-15 11:26 UTC, qaziabubakar-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +              }, 100
I have tried to use several other implementation, using the `setOnDismissListener` as well but the internal mechanism of the `MaterialAutoCompleteTextView` is such that it resets the view when the text get cleared. 
Our implementation should have been a straight forward one that when the text is cleared we display the dropdown but `MaterialAutoCompleteTextView` resets its state every time the text gets cleared. 
I will also put some comments here.

2024-03-15 11:28 UTC, qaziabubakar-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                if (autoCompleteTextView.isPopupShowing.not() && isDropdownEditable) {
I have tried with multiple dropdowns, it works as expected.
Selecting one dropdown item in a questionnaire form does not trigger popups for other dropdown items

2024-03-15 11:38 UTC, qaziabubakar-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        autoCompleteTextView.isEnabled = isDropdownEditable
I have updated the clearIcon visibility based on its readOnly property, since if the item is readOnly we don't need to display the clearIcon

2024-03-15 11:43 UTC, qaziabubakar-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +          autoCompleteTextView.text = null
Yes, I have added this here, now when the user taps on the clearIcon, I call the `questionnaireViewItem.clearAnswer()` as well.

2024-03-26 17:52 UTC, jingtang10 requested changes

2024-03-26 17:52 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt
additional test cases to consider:
- free text input to be disabled after selecting an option
- answer changed callback to be called after selecting an option
- answer changed callback to be called after clicking x

2024-03-26 17:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +      private var isDropdownEditable = true
is there anyway to write this widget without adding this state? i feel like if the dropdown is editable or not can be entirely decided by the questionnaire view item? i.e. if draft answer exists then its editable, but if there's an actual answer it's not editable?

2024-03-26 17:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        if (isReadOnly) clearIcon.visibility = View.GONE
!? why this

readonly has a very specific meaning - why are you piggybacking on this setting?

2024-03-26 17:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +          setReadOnly(false)
i'm not really uk with setting readonly as false. what if this is a question that is actually readonly, you will override the setting?

2024-03-26 17:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        autoCompleteTextView.doAfterTextChanged {
i don't know if you can use draft answer here... try to set draft answer and reset the widget? i guess one problem might be the cursor moving? @aditya-07 do you have experience with this?

2024-06-22 08:53 UTC, jingtang10 commented
Hey @qaziabubakar-vd any progress here? Thanks!

2025-01-28 08:12 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        }
On second thoughts, I can probably move this to the `init()` function

2025-01-28 08:14 UTC, FikriMilano commented
Remaining todo is test

2025-01-28 08:15 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                    100,
refactored

2025-01-28 08:16 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +      private var isDropdownEditable = true
refactored, readOnly mode won't be affected

2025-01-28 08:19 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +        if (isReadOnly) clearIcon.visibility = View.GONE
the refactored code won't affect readOnly mode

2025-01-28 08:20 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +          setReadOnly(false)
refactored, the new code won't affect readOnly

2025-01-28 10:01 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +                    100,
I've refactored that to
https://github.com/google/android-fhir/pull/2393/commits/12fb10b5ba7c89681d7d812e3a1d4d9709a7dd3d

2025-01-28 14:06 UTC, MJ1998 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt
> +    Thread.sleep(1000)
Can you check if this is needed. Espresso should handle this automatically.

2025-01-28 14:06 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +            delay(200) // to show ripple effect on the icon before clearing the answer
This is unnecessary. May cause flakiness in test cases.

2025-01-29 01:42 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DropDownViewHolderFactory.kt
> +            delay(200) // to show ripple effect on the icon before clearing the answer
sure

2025-01-29 07:49 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt
> +    Thread.sleep(1000)
we don't actually, not sure why it's there

2025-01-29 10:23 UTC, FikriMilano commented
@jingtang10 @MJ1998 this is ready for review

2025-02-06 09:09 UTC, MJ1998 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/test/views/DropDownViewHolderFactoryEspressoTest.kt
> +    Thread.sleep(1000)
This is done.

2025-02-20 15:54 UTC, closed without merging