Configure prev and next button when disabled
google/android-fhir pull request #2397
Opened 2024-01-02 04:02 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2394

**Description**
1. Pass the 2 boolean config for disabled prev and next button through the Questionnaire builder
2. In the ViewModel, if the config is set to true then always show the buttons, if it's false then ONLY show the buttons if at the current page there's a previous or next page
3. In the ViewModel, pass the 2 boolean config to a QuestionnairePagination object
4. In the View, use the config by observing the ViewModel's QuestionnairePagination

**Alternative(s) considered**
N/A

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-01-02 04:03 UTC, FikriMilano commented
this is ready for review

2024-01-02 18:59 UTC, jingtang10 requested changes

2024-01-02 18:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  val showDisabledNextButton: Boolean = true,
not that this matters hugely but i think for someone without context these variables can be a bit confusing.

two options for you to consider: we could create a tri-state, hidden, disabled, enabled for these buttons.

or we could have a variable that simply states if they're shown, and another variable to state if they're enabled.

2024-01-02 18:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
do we definitely need these options?

@shelaghm do you think we should simply always hide the diabled buttons?

2024-01-03 08:24 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
I think this will need a design decision, I'm ok if we are to simply always hide the disabled buttons

2024-01-03 08:25 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
I think this will need a design decision, @rowo what do you think?

2024-01-03 08:56 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  val showDisabledNextButton: Boolean = true,
nice, either of these makes sense

2024-01-16 16:57 UTC, jingtang10 commented
as discussed in emails, we'll just hide by default in these cases. please update the pr fikri - thanks!

2024-01-17 11:32 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
@FikriMilano @rowo Any updates on this?

2024-01-18 10:14 UTC, FikriMilano commented
@jingtang10 this PR is ready for review

2024-01-23 10:59 UTC, jingtang10 approved these changes

2024-01-23 12:14 UTC, merged