Add Launch and Submission Timestamps to QR
google/android-fhir pull request #2400
Opened 2024-01-04 08:06 UTC by hamza-vd

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2372 

**Description**
PR adds `QuestionnaireItemComponent` and `QuestionnaireResponseItemComponent` for form launch and submission timestamps

**Alternative(s) considered**
N/A

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-01-10 08:58 UTC, aditya-07 commented
@hamza-vd Please update the branch to latest.

2024-01-10 10:25 UTC, hamza-vd commented
@aditya-07 this is done

2024-01-22 04:46 UTC, MJ1998 requested changes
I think we should not implicitly do this for all Questionnaires as it might be undesirable to receive unexpected items in QuestionnaireResponse.

We should consider adding the flag to either DataCaptureConfig or via QuestionnaireFragment.args!

2024-01-22 04:46 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      questionnaire.addItem(getTimestampItem("submission-timestamp"))
You can move this to the end of previous init block where the questionnaire is initialized!

2024-01-22 04:46 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                        value = StringType(Date().toTimeZoneString())
Why not value of type date / datetime itself ?

2024-01-25 06:39 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      questionnaire.addItem(getTimestampItem("submission-timestamp"))
Updated

2024-01-25 06:44 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                        value = StringType(Date().toTimeZoneString())
This makes more sense. Item type changed to `DATETIME`

2024-01-26 11:09 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    // Add timestamp questionnaire items
@aditya-07 Where should I reference these strings as constants?

2024-01-26 11:11 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
@aditya-07 Where should I reference these strings as constants?

2024-01-26 13:32 UTC, qiarie commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
Can this be made to be reusable?

2024-01-26 14:13 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
Yes, but could you kindly suggest the best place where it can be moved to?

2024-01-31 12:45 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
Since they are internal to this class only, just create a companion object for QuestionnaireViewModel.kt and add these in it.

2024-01-31 13:01 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
`MoreDates.kt` in the sdc module and add this extension function there. Create one if not already there.

2024-01-31 13:09 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
```suggestion
if (shouldAddTimestampItems) {
questionnaire.addItem(getTimestampItem("launch-timestamp"))
questionnaire.addItem(getTimestampItem("submission-timestamp"))
}
```

It is easier to read with the if condition here than to figure out from exploring the `getTimestampItem` function firsts to know what's going on.

Or 
maybe rename `getTimestampItem` to something that explains both its intents better.

2024-01-31 13:10 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    addTimeStampValue(questionnaireResponse.item, "launch-timestamp")
```suggestion
   if (shouldAddTimestampItems) {
      addTimeStampValue(questionnaireResponse.item, "launch-timestamp")
    }
```

Same as above

2024-01-31 13:23 UTC, aditya-07 requested changes

2024-01-31 13:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
Based on the previous comments

```suggestion
    private fun getTimestampItem(linkIdVal : String) = 
        QuestionnaireItemComponent().apply {
            linkId = linkIdVal
            readOnly = true
            type = Questionnaire.QuestionnaireItemType.DATETIME
            extension.add(Extension("http://hl7.org/fhir/StructureDefinition/questionnaire-hidden", BooleanType(true)))
        } 

```

2024-01-31 13:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
```suggestion
    private fun addTimeStampValue(items: List<QuestionnaireResponseItemComponent>, itemLinkId : String) {
            items.forEach { item ->
                if (item.linkId == itemLinkId) {
                    item.answer = arrayListOf<QuestionnaireResponseItemAnswerComponent?>().apply {
                        add(QuestionnaireResponseItemAnswerComponent().apply {
                            value = DateTimeType(Date().toTimeZoneString())
                        })
                    }
                }
            }
        }
```

Or maybe rename it to describe the intent better.

2024-01-31 13:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
Add the sample response to showcase what should be expected by the application developers.

2024-01-31 13:23 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
@jingtang10 

Link ids "launch-timestamp" and "submission-timestamp" are hardcoded right now.  Would it make sense for the sdc to take these values as optional parameters as well incase some developers want other linkIds for the timestamp?

Otherwise, we should highlight them explicitly in the kdoc here.

2024-02-06 07:38 UTC, ellykits requested changes

2024-02-06 07:55 UTC, ellykits commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
@hamza-vd Is the intended usage of `submission-timestamp` in any way different from [QuestionnaireResponse.authored](https://hl7.org/fhir/R4B/questionnaireresponse-definitions.html#QuestionnaireResponse.authored) property?. `authoredOn` from the specs refers to the date and/or time that the set of QuestionnaireResponse answers were last changed and is differentiated from the `lastUpdateTime` of the resource.

2024-02-06 09:27 UTC, jingtang10 requested changes
I agree with @ellykits's point about using the authored field, but also, I am not sure if I like the approach of adding more questions to the questionnaire and the questionnaire response. I think the timestamps are meta data and should be appended to the questionnaire response as extensions. can you try to define extension for the launch timestamp?

2024-02-06 09:29 UTC, jingtang10 commented
> I think we should not implicitly do this for all Questionnaires as it might be undesirable to receive unexpected items in QuestionnaireResponse.
> 
> We should consider adding the flag to either DataCaptureConfig or via QuestionnaireFragment.args!

I don't think we should use items at all for this type of metadata. And if we use extension we can avoid adding additional configs too.

2024-02-07 08:36 UTC, qiarie commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +
@ellykits The 2 timestamps are different. Questionnaire launch and submission timestamps when available are for use to analyse and report on data collection.

2024-02-19 10:40 UTC, jingtang10 commented
Any update here?

2024-02-21 12:32 UTC, hamza-vd commented
@jingtang10 
 As suggested there will be a change in the implementation. I will implement the following changes.

1. The `authored` field will be used as a submission timestamp.
2. The launch-timestamp will be added as an extension to the `QuestionnaireResponse`

2024-02-22 10:29 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireResponse.extension.add(Extension("launch-timestamp", DateTimeType(Date())))
@jingtang10 
Kindly suggest what should be the `url` for the launch timestamp value

2024-03-26 11:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireResponse.extension.add(Extension("launch-timestamp", DateTimeType(Date())))
sorry i missed this. how about `https://github.com/google/android-fhir/StructureDefinition/questionnaireresponse-launchTimestamp`

Also - have you considered having an extension that just record the actual duration it took to fill out the questionnaire... effectively submission timestamp - launch timestamp... i'm not saying this is better, it's just an alternative approach i think we should consider before dismissing it completely.

2024-05-08 06:52 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireResponse.extension.add(Extension("http://github.com/google-android/launch-timestamp", DateTimeType(Date())))
@aditya-07 Kindly review this extension URL

2024-05-16 08:48 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireResponse.extension.add(Extension("http://github.com/google-android/launch-timestamp", DateTimeType(Date())))
```suggestion
    questionnaireResponse.extension.add(Extension("http://github.com/google-android/questionnaire-launch-timestamp", DateTimeType(Date())))
```
To specify the extension namespace.

2024-06-06 11:25 UTC, jingtang10 requested changes

2024-06-06 11:25 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    )
can you move this logic to MoreQuestionnaireResponses.kt file?

https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt

also can you make sure to handle the case where this extension already exists? i guess we should overwrite the value in that case?

also add tests please. thanks.

2024-06-11 21:41 UTC, jingtang10 requested changes

2024-06-11 21:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +internal fun QuestionnaireResponse.addLaunchTimestamp() {
please take a look at how extensions are implemented in this class https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt and try to do something similar.

see https://kotlinlang.org/docs/properties.html for how to implement this as a property. note that most properties in teh above class are probably read-only but you want to have a setter for your property.

2024-06-11 21:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +      it.url == "http://github.com/google-android/questionnaire-launch-timestamp"
don't hardcode values like this

2024-06-11 21:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
please add tests

2024-07-05 06:16 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    )
This is handled

2024-07-05 06:16 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +internal fun QuestionnaireResponse.addLaunchTimestamp() {
This is done

2024-07-05 06:16 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +      it.url == "http://github.com/google-android/questionnaire-launch-timestamp"
This is addressed

2024-07-05 07:24 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
Added

2024-07-09 20:15 UTC, jingtang10 requested changes

2024-07-09 20:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +    if (noLaunchTimeStampExists) {
if this extension already exists we probably should update the value?

2024-07-09 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
> +  fun `test launchTimestamp added correctly`() {
```suggestion
  fun `should add launchTimestamp`() {
```

2024-07-09 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
> +  fun `test launchTimestamp added correctly`() {
and rename the other test cases similarly

2024-07-09 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
> +  fun `test setLaunchTimestamp should not override previously added extension if any`() {
why do we want this behavior?

2024-07-09 20:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
> +    assertNotNull(launchTimestamp)
we use the truth library instead of assertEquals - pls take a look at other test cases.

2024-07-10 09:08 UTC, hamza-vd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponses.kt
> +    if (noLaunchTimeStampExists) {
We need to track the metric from the point the user has opened the Questionnaire until submission. The original timestamp should remain as is even if user navigates away from the questionnaire and later resumes on it. cc: @qiarie

2024-07-10 09:10 UTC, hamza-vd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
> +  fun `test setLaunchTimestamp should not override previously added extension if any`() {
Discussed [here](https://github.com/google/android-fhir/pull/2400#discussion_r1671914029)

2024-07-29 09:33 UTC, hamza-vd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireResponsesTest.kt
> +    assertNotNull(launchTimestamp)
Updated

2024-09-12 09:22 UTC, hamza-vd commented
Closing in the favor of #2672

2024-09-12 09:22 UTC, closed without merging