Add API for remote inserts
google/android-fhir pull request #241
Opened 2021-02-16 10:32 UTC by deepankarb

* No local change for remote inserts
* Fixed JSON patch merge logic

2021-02-18 21:25 UTC, jingtang10 requested changes

2021-02-18 21:25 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        val first = JSONArray(firstPatch)
`firstJsonArray` or some similar name that's more descriptive

2021-02-18 21:25 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        }
I find this use of `forEach` harder to read than a plain `for` loop:

```suggestion
        for (i in 0..first.length()) {
           ...
        }
```

what do you think?

2021-02-18 21:25 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/Database.kt
> +     * already exists, it will be overwritten
nit: period

2021-02-18 21:25 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/Database.kt
>       * already exists, it will be overwritten
nit: period

2021-02-18 21:25 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/Database.kt
> +     * Inserts a list of remote `resource`s into the FHIR resource database. If any of the resources
```suggestion
     * Inserts a list of remote `resources` into the FHIR resource database. If any of the resources
```

2021-02-18 21:25 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/Database.kt
> +     * Inserts a list of local `resource`s into the FHIR resource database. If any of the resources
```suggestion
     * Inserts a list of local `resources` into the FHIR resource database. If any of the resources
```

2021-02-19 04:55 UTC, deepankarb commented on core/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
>              .isEqualTo("Resource not found with type ${TEST_PATIENT_2.resourceType.name} and id $TEST_PATIENT_2_ID!"
Noted. It makes the line even longer though and not possible see easily in a tiled window :)

2021-02-19 05:06 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        }
Agree.

2021-02-19 05:08 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        }
One thing though range `0..n` includes n but `0 until n` yields from 0 till n-1.

2021-02-22 08:46 UTC, jingtang10 commented on core/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +            .isTrue()
new line:
```suggestion
        assertThat(
            database.getAllLocalChanges()
                .map { it.second }
                .none { it.resourceId in listOf(patient.id, TEST_PATIENT_2_ID) }
        ).isTrue()
```

2021-02-22 08:46 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        for (i in 0 until firstPatchJsonArray.length()) {
I wonder if it's more idiomatic to use `..` rather than `until`?

2021-02-22 08:46 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        }
I think you can do something along these lines:

```suggestion
        val firstJsonObjectList = (0..firstJsonArray.length()).map { firstJsonArray.optJSONObject(it) }
        val firstJsonObjectMap = firstJsonObjectList.associate {
            it.optString("op") to it
        }.toMutableMap()
        
        val secondJsonObjectList = (0..secondJsonArray.length()).map { secondJsonObjectList.optJSONObject(it) }
        val secondJsonObjectMap = secondJsonObjectList.associate {
            it.optString("op") to it
        }.toMap()
        
        firstJsonObjectMap.putAll(secondJsonObjectList)
```

also may create a utility function for the repeated code? up to you.

2021-02-22 09:42 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        for (i in 0 until firstPatchJsonArray.length()) {
Seems like `until` is preferred over open ranges per https://kotlinlang.org/docs/coding-conventions.html#loops-on-ranges. It feels like off-by-one errors are less likely with `until` but I could be wrong.

2021-02-22 13:32 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
> +        }
Done.

2021-02-22 13:32 UTC, deepankarb commented on core/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +            .isTrue()
Done.

2021-02-22 15:50 UTC, jingtang10 approved these changes
does the problem still exist (e.g. delete and add)? do you plan to resolve it in a future PR?

2021-02-22 16:29 UTC, deepankarb commented
> does the problem still exist (e.g. delete and add)? do you plan to resolve it in a future PR?

On second thought it doesn't apply since remove and add would be separate operations.

I'll create an issue to test various combinations of JSON patch operations on same and different properties.

2021-02-22 16:29 UTC, merged