Sp/issue 2140
google/android-fhir pull request #2413
Opened 2024-01-18 11:56 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2140 

**Description**
Remove workflow type argument value to differentiate the component, layout and behavior questionnaire.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-01-22 04:08 UTC, MJ1998 approved these changes
LGTM

2024-01-31 13:55 UTC, jingtang10 requested changes

2024-01-31 13:55 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +      R.style.Theme_Androidfhir_PaginatedLayout
how different is paginated layout and component layout? can we merge them?

2024-02-02 09:27 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +      R.style.Theme_Androidfhir_PaginatedLayout
done.

2024-02-02 11:03 UTC, santosh-pingle commented on catalog/src/main/java/com/google/android/fhir/catalog/DemoQuestionnaireFragment.kt
> +      R.style.Theme_Androidfhir_PaginatedLayout
done.

2024-02-06 02:34 UTC, jingtang10 approved these changes
thanks @santosh-pingle for this cleanup!

2024-02-06 03:18 UTC, merged