Add support for additional data during CQL evaluation
google/android-fhir pull request #2420
Opened 2024-01-31 19:02 UTC by ndegwamartin

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2419 

**Description**
 #2419 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-02-15 10:27 UTC, MJ1998 reviewed
Why not add this parameter `additionalData` to this API itself:-
```
fun evaluateLibrary(
    libraryUrl: String,
    patientId: String?,
    parameters: Parameters?,
    expressions: Set<String>?,
  ): IBaseParameters {
  ```

2024-02-15 10:28 UTC, MJ1998 commented
Please also run `./gradlew spotlessapply`

2024-02-15 15:19 UTC, ndegwamartin commented
@MJ1998 additionally the the method is heavily overloaded in the same class so just added the new one. I've pushed an update that refactors it in line with the implementation of the other overloads.

2024-02-19 11:27 UTC, MJ1998 commented
@ktarasenko @jingtang10 
Can you take a look at this? Thanks

2024-02-21 14:25 UTC, brynrhodes commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun evaluateLibrary(
I'd also ask for what the motivation for the change here is, who needs this added and why? It is "somewhat" analagous to the prefetchData parameter, but there's a transformation to get there, and it's lossy, and the fact that it's lossy is part of some current reconciliation on the Using CQL With FHIR IG (https://jira.hl7.org/browse/FHIR-43763)

2024-02-22 10:22 UTC, ndegwamartin commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun evaluateLibrary(
In our case we use it to avoid the performance hit of accessing the DB since we already have the resource data required for evaluation _e.g. after Form submission_ where we extract the various resources using Structure Maps.

2024-02-23 14:30 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun evaluateLibrary(
> can we keep this as the same api but just make all the nullable arguments optional?

please still address this comment @ndegwamartin.

@brynrhodes given that this is indeed supported by the library processor, i think it does make sense to expose this to the application through our workflow library apis. whether they should use it is perhaps too philosophical to answer here. but we can continue in our email discussions.

2024-02-27 14:29 UTC, jingtang10 requested changes

2024-02-27 14:29 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
> +  fun evaluateLibrary(
i mean not to add a new function but to change the existing funtion

2024-02-28 16:57 UTC, jingtang10 approved these changes
Thanks @ndegwamartin!

2024-03-20 13:07 UTC, ndegwamartin commented
@vitorpamplona any idea why the Benchmarking tests would fail here?

2024-03-21 09:08 UTC, ndegwamartin commented
> @vitorpamplona any idea why the Benchmarking tests would fail here?

nvm, figured out the issue

2024-03-22 12:09 UTC, merged