Added SHL Decoding Interfaces and Implementations
google/android-fhir pull request #2434
Opened 2024-02-06 22:14 UTC by hugomilosz

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Added interfaces and implementations of them for the decoding of Smart Health Links, along with unit tests.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-02-07 10:32 UTC, jingtang10 requested changes

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> +  /* Decode and decompress a SHL into an IPSDocument object */
is shl an url or a structured data object? why is it a json object?

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> +  /* Decode and decompress a SHL into an IPSDocument object */
add comment, and add example

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> +  /* Decode and decompress a SHL into an IPSDocument object */
make it clear if/how this should handle network communication.

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/ReadSHLinkUtils.kt
> +class ReadSHLinkUtils {
i think this can be an object.

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private val apiService: RetrofitSHLService,
more descriptive name

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private val shLinkScanDataInput: SHLinkScanData?,
why does the constructor take in this whole object? this ties the decoder to a specific shl right? i feel like the decoder should be reusable.

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private fun constructShlObj(): SHLinkScanData {
can you try to refactor this function? this function is constructing an SHLinkScanData object from the shLinkScanDataInput object which is of the same type. can you please try to simplify?

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +      IPSDocument(bundle, ArrayList(), Patient()) // change this construction
1. in kotlin, if you're passing things like ArrayList(), or emptyList(), or null to a function, use named parameters to improve readability. `documents = emptyList()`
2. if you have an obscure way of creating something, you can just create a static function in the IPSDocument class so the caller can create it by calling `IPSDocument.create(bundle)` and then the creation logic lives inside the IPSDocument class, a bit more readable, and also, reducing the chances of the caller passing incorrect initial parameters.

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private fun decodeEmbeddedArray(
add comments

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private suspend fun decodeResponseBody(
add comments

2024-02-07 10:32 UTC, jingtang10 commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +    for (elem in embeddedArray) {
nit: i'd try to avoid shortened words as names

2024-02-07 10:32 UTC, jingtang10 commented on document/src/test/java/com/google/android/fhir/document/ReadSHLinkUtilsTest.kt
> +  fun testExtractUrlWithValidSHL() {
i would use backticks in kotlin to name the tests

https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

2024-02-07 10:32 UTC, jingtang10 commented on document/src/test/java/com/google/android/fhir/document/ReadSHLinkUtilsTest.kt
> +    assertEquals("example-url", result)
we use the truth library. can you take a look at some other tests in the repo?

basically something like this:

`assertThat(...).isEqualTo(...)`

2024-02-07 10:32 UTC, jingtang10 commented on document/src/test/java/com/google/android/fhir/document/SHLinkDecoderImplTest.kt
> +  @Mock private lateinit var shLinkScanData: SHLinkScanData
is it really necessary to mock this? if this is a data class normally you can just create fake objects?

2024-02-21 15:01 UTC, jingtang10 requested changes

2024-02-28 16:22 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> +  /* Decode and decompress a SHL into an IPSDocument object */
Updated kdoc with a more detailed explanation and an example workflow

2024-02-28 16:23 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private val apiService: RetrofitSHLService,
Changed name to retrofitSHLService

2024-02-28 16:24 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private val shLinkScanDataInput: SHLinkScanData?,
Removed the SHL object from the constructor - the DecoderImpl is now generic and not related to a specific SHL

2024-02-28 16:26 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +    for (elem in embeddedArray) {
Changed shortened names like 'elem' and 'doc' to 'element' and 'document'

2024-02-28 16:27 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/ReadSHLinkUtils.kt
> +class ReadSHLinkUtils {
Changed to an object

2024-02-28 16:29 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +  private fun constructShlObj(): SHLinkScanData {
Removed the constructShlObj from file. The functionality has been moved to the .create() in the data class' companion object

2024-02-28 16:33 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +    val shLinkScanData = SHLinkScanData().create(shLink)
Added the create() function to the SHLinkScanData's companion object

2024-02-28 16:34 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/scan/SHLinkScanData.kt
> +  ) : this(fullLink, extractedJson, manifestUrl, key, "", flag, "", "", null)
Removed all the constructors - an SHLinkScanData object can now only be constructed by called the create() function

2024-02-28 16:35 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> +  suspend fun decodeSHLinkToDocument(shLink: String, jsonData: String): IPSDocument?
Changed to take in two strings: a recipient and an optional passcode. The JSON object is now constructed in this function

2024-02-28 16:36 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> +   * Decode and decompress a Smart Health Link (SHL) into an [IPSDocument] object.
kdoc changed to this

2024-02-28 16:37 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> + * retrieve the data.
kdoc updated to make the two cases (and how to handle them) more clear

2024-02-28 16:37 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoder.kt
> + * "embeddedLengthMax":INT. Example request body:
Comment corrected

2024-02-28 16:56 UTC, hugomilosz commented on document/src/main/java/com.google.android.fhir.document/decode/SHLinkDecoderImpl.kt
> +      IPSDocument(bundle, ArrayList(), Patient()) // change this construction
Implemented a create() function in the IPSDocument's companion object - IPSDocument objects can now only be constructed with this function

2024-02-28 16:56 UTC, hugomilosz commented on document/src/test/java/com/google/android/fhir/document/ReadSHLinkUtilsTest.kt
> +    assertEquals("example-url", result)
Updated all tests to use the Truth library

2024-02-28 16:57 UTC, hugomilosz commented on document/build.gradle.kts
> +    minSdk = 26
Change reverted - no longer need the minSdk to be 26 as dependencies were changed

2024-02-28 17:00 UTC, hugomilosz commented on document/src/test/java/com/google/android/fhir/document/SHLinkDecoderImplTest.kt
> +  @Mock private lateinit var shLinkScanData: SHLinkScanData
ReadSHLinkUtils is now an object, but is still mocked for these tests. All the functions in the object have been tested separately, but mocking is required to thoroughly test the DecoderImpl.

2024-03-06 17:32 UTC, jingtang10 approved these changes

2024-03-06 17:32 UTC, jingtang10 commented on document/src/test/java/com/google/android/fhir/document/SHLinkDecoderImplTest.kt
> +    assertThat(result!!.document).isNotNull()
can you verify the document at least?

2024-03-13 14:32 UTC, hugomilosz commented on document/src/test/java/com/google/android/fhir/document/ReadSHLinkUtilsTest.kt
> +    assertThat(result.exceptionOrNull()!!::class).isEqualTo(IllegalArgumentException::class)
Done - changed in both test files in this PR

2024-03-13 14:33 UTC, hugomilosz commented on document/src/test/java/com/google/android/fhir/document/SHLinkDecoderImplTest.kt
> +    assertThat(result).isNotNull()
Made tests more explicit - now asserts the bundle's ID is equal to the expected value

2024-03-13 14:33 UTC, hugomilosz commented on document/src/test/java/com/google/android/fhir/document/SHLinkDecoderImplTest.kt
> +    assertThat(result!!.document).isNotNull()
Done - now uses bundle ID as verification

2024-06-18 12:34 UTC, merged