Prefill questionnaire with an optional questionnaire response
google/android-fhir pull request #244
Opened 2021-02-18 09:55 UTC by joiskash

#189

2021-02-19 11:45 UTC, jingtang10 requested changes

2021-02-19 11:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    private var questionnaireResponseBuilder = QuestionnaireResponse.newBuilder()
use `lateinit`

2021-02-19 11:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    private var cnt = 0
revert

2021-02-19 11:45 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +                                    .setValue("test-code"))
as discussed, these can be on one line. same below.

2021-02-19 11:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +fun validateQuestionnaireResponse(
internal

2021-02-19 11:45 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                .xor(questionnaireResponseItemListIterator.hasNext()))
you could also use the kotlin infix notation:

https://kotlinlang.org/docs/functions.html#infix-notation

```suggestion
    questionnaireItemListIterator.hasNext() xor questionnaireResponseItemListIterator.hasNext()
```

2021-03-01 09:44 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    private var cnt = 0
Done

2021-03-01 09:44 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +                                    .setValue("test-code"))
done

2021-03-01 09:45 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +fun validateQuestionnaireResponse(
done

2021-03-01 09:45 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                .xor(questionnaireResponseItemListIterator.hasNext()))
done

2021-03-01 10:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    private var questionnaireResponseBuilder = QuestionnaireResponse.newBuilder()
done

2021-03-05 01:28 UTC, jingtang10 reviewed
thanks @joiskash sorry for the delay!

2021-03-05 01:28 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +                "hl7-questionnaireresponse-example-bluebook.json"
fix indentation

2021-03-05 01:28 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListItem.kt
> +    val pathQuestionnaireResponse: String?
can i suggest `questionnairePath` and `questionnaireResponsePath`? read better i think. wdyt?

2021-03-05 01:28 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +    var questionnaireResponseJson: String? = null
so i think `questionnaireJson` above should be marked as private. Please follow that pattern and have a private var and a public val (read-only)

2021-03-05 06:14 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                                .setValue(QuestionnaireItemTypeCode.Value.CHOICE))
oh thats weird.. i remember fixing this .. anyway will do

2021-03-05 07:23 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                                            .setDisplay(String.newBuilder().setValue("Test Code"))))
done sorry bout this. Thought I had fixed it

2021-03-05 07:23 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        // TODO: Validate type and item nesting
done #286

2021-03-05 07:23 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun validateQuestionnaireResponse(
done

2021-03-05 07:45 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun validateQuestionnaireResponse(
just that now the unit test validateQuestionnaireResponseItems_shouldReturnTrue does not have an assert statement since nothing is returned

2021-03-05 07:46 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun validateQuestionnaireResponse(
I have changed the test name to validateQuestionnaireResponseItems_shouldNotThrowException

2021-03-05 07:46 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            throw IllegalArgumentException("Structure mismatch")
done

2021-03-05 07:46 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun validateQuestionnaireResponse(
done. But now the unit test validateQuestionnaireResponseItems_shouldReturnTrue does not have an assert statement since nothing is returned.


I have changed the test name to validateQuestionnaireResponseItems_shouldNotThrowException

2021-03-05 07:47 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListItem.kt
> +    val pathQuestionnaireResponse: String?
yes sure that makes sense

2021-03-05 08:01 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +    var questionnaireResponseJson: String? = null
sure done

2021-03-08 07:22 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +                "hl7-questionnaireresponse-example-bluebook.json"
done

2021-03-09 10:09 UTC, jingtang10 commented
thanks @joiskash - looks good. did you also mean to add some tests for the model?

2021-03-09 12:05 UTC, jingtang10 requested changes

2021-03-09 12:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    fun validateQuestionnaireResponseItems_shouldReturnThrowError_wrongStructure_moreItemsInQuestionnaireResponse() { // ktlint-disable max-line-length
```suggestion
    fun validateQuestionnaireResponseItems_moreItemsInQuestionnaireResponse_shouldThrowError() { // ktlint-disable max-line-length
```

same below

2021-03-09 12:05 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    fun validateQuestionnaireResponseItems_shouldNotThrowException() {
i feel these tests are slightly overlapping with the tests above you added. i think one way to simplify these is actually just convert these tests to the same structure as your tests above and only test the public interface.

that way you can also mark the validation function as private.

2021-03-09 13:51 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +        )
yup thats true. done

2021-03-09 13:51 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    fun questionnaireResponse_group_shouldCopyQuestionnaireStructure_nestedItemsWithinGroupItems() { // ktlint-disable max-line-length
done

2021-03-09 13:51 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    fun validateQuestionnaireResponseItems_shouldReturnThrowError_wrongLinkId() {
done

2021-03-09 13:51 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    fun validateQuestionnaireResponseItems_shouldReturnThrowError_wrongStructure_moreItemsInQuestionnaireResponse() { // ktlint-disable max-line-length
done

2021-03-09 13:51 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    fun validateQuestionnaireResponseItems_shouldNotThrowException() {
done

2021-03-09 16:19 UTC, jingtang10 submitted a review, later dismissed
a few nits but good to merge once those are addressed.

2021-03-09 16:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        throw IllegalArgumentException("Structure mismatch")
nit: add brackets around this. (i try to do so to make sure the semantics of the code doesn't depend on the formatting. admittedly kotlin does break that a little bit.)

2021-03-09 16:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            throw IllegalArgumentException("linkId mismatch")
please use a more descriptive message. perhaps at least reference two different link ids?

e.g. `Questionnaire response items mismatch with linkIds $first and $second`

2021-03-09 16:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        throw IllegalArgumentException("Structure mismatch")
similar to link ids make this message a bit more descriptive.

2021-03-10 05:20 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    @Test
done

2021-03-10 05:20 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        throw IllegalArgumentException("Structure mismatch")
done

2021-03-10 05:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            throw IllegalArgumentException("linkId mismatch")
done

2021-03-10 05:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        throw IllegalArgumentException("Structure mismatch")
done

2021-03-12 17:47 UTC, jingtang10 requested changes
can you please remove all the reformatting of other files?

i think we should try to add an xml plugin for spotless. but before that let's hold off on reformatting the whole codebase. thanks!

2021-03-12 17:49 UTC, joiskash commented
Oh my bad . Ok so we just do it for data capture module?

2021-03-14 00:22 UTC, jingtang10 commented
I just mean revert all the reformatting of XML files etc.

2021-03-15 18:39 UTC, jingtang10 requested changes

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                                ) // ktlint ignore max-line-limit
nit: remove the `// ktlint ignore max-line-limit`

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                                ) // ktlint-disable max-line-length
nit: remove the `// ktlint ignore max-line-limit`

2021-03-15 18:39 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +  // Display Quesitonnaire response as a dialog
there's a misspelling here.

2021-03-15 18:39 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +    const val QUESTIONNAIRE_FRAGMENT_TAG = "questionannire-fragment-tag"
misspelling.

there's been a PR that fixed these misspellings. so this must be a merge error.

2021-03-15 18:39 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +              .use { it.readText() }
can you extract a small private util function in this class?

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          questionnaireItemListIterator.next().linkId.value
```suggestion
        "No matching questionnaire response item for questionnaire item ${questionnaireItemListIterator.next().linkId.value}"
```

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          questionnaireResponseItemListIterator.next().linkId.value
```suggestion
        "No matching questionnaire item for questionnaire response item ${questionnaireResponseItemListIterator.next().linkId.value}"
```

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          questionnaireResponseItem.linkId.value
```suggestion
        "Mismatching linkIds for questionnaire item ${questionnaireItem.linkId.value} and questionnaire response item ${questionnaireResponseItem.linkId.value}"          
```

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertThat(errorMessage).contains("linkId")
can you please exact match the whole string?

2021-03-15 18:39 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertThat(errorMessage).contains("Structure")
and here too

2021-03-16 06:43 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                                ) // ktlint ignore max-line-limit
done

2021-03-16 06:43 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                                ) // ktlint-disable max-line-length
done

2021-03-16 06:46 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +  // Display Quesitonnaire response as a dialog
done

2021-03-16 06:46 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +    const val QUESTIONNAIRE_FRAGMENT_TAG = "questionannire-fragment-tag"
done

2021-03-16 06:52 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +              .use { it.readText() }
done

2021-03-16 06:53 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          questionnaireResponseItem.linkId.value
done

2021-03-16 06:53 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertThat(errorMessage).contains("linkId")
done

2021-03-16 06:53 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertThat(errorMessage).contains("Structure")
done

2021-03-16 09:09 UTC, jingtang10 approved these changes
Thanks @joiskash for persisting on this!

one tiny thing but all good otherwise 🎉

2021-03-16 09:09 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +            viewModel.questionnaireResponse // ktlint-disable max-line-length
get rid of `// ktlint-disable max-line-length`

2021-03-16 09:15 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt
> +            viewModel.questionnaireResponse // ktlint-disable max-line-length
done 🎉

2021-03-16 09:53 UTC, merged