Updated PerResourcePatchGenerator  to return ordered PatchMapping to avoid referential integrity issues.
google/android-fhir pull request #2442
Opened 2024-02-15 08:07 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
1. Create a Directed Graph based on all the outgoing references for each Patch. Since the referential integrity comes to picture if the resource is not created yet, the edges of the graph are only the outgoing references to resources that are getting created during this upload. This may helps avoid some cycles as well.
2. Order the Patches so that if the resource A has outgoing references {B,C} (CREATE) and {D} (UPDATE), then B,C needs to go before the resource A so that referential integrity is retained. Order of D shouldn't matter for the purpose of referential integrity.

**Alternative(s) considered**
1. Splitting changes to CREATE first and subsequent UPDATE, but this would also require ordering the the create list incase it can overflow to multiple Bundles.  This would be similar to the current approach but, would require multiple PUSH for the same resource incase the resource was Created and then Updated on the device before being pushed to the server.

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-02-16 09:43 UTC, MJ1998 requested changes
I feel we can improve complexity of this solution by using LocalChangeReferenceEntity table to fetch all the outgoing references.

2024-02-22 18:00 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +internal fun List<PatchMapping>.createReferenceAdjacencyList(
Done

2024-02-22 18:01 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +      JsonLoader.fromString(generatedPatch.payload).forEach {
Yes, I have removed this code .

2024-02-22 18:02 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +      JsonLoader.fromString(generatedPatch.payload).forEach {
N.A

2024-02-26 11:57 UTC, MJ1998 reviewed
Nice job stitching the `LocalChangeResourceReferenceEntity` here. 

Although I dont like PatchGenerator having access to database which is from another package. I think we should abstract this out in a separate interface which is parent of the two packages: db and sync. 
Maybe FhirSyncDbInteractor works well in this case as well. Will raise a PR soon so that this can be imagined better.

2024-02-26 12:01 UTC, MJ1998 requested changes

2024-02-26 12:01 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +      is PatchGeneratorMode.PerResource -> PerResourcePatchGenerator(database)
This will create a new instance every time as contrary to earlier where the object was a singleton. And singleton is what I would prefer because the upload strategy wont change.

2024-02-27 17:59 UTC, jingtang10 requested changes

2024-02-27 17:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +internal suspend fun List<PatchMapping>.orderByReferences(database: Database): List<PatchMapping> {
if you add a reference in a resource that you later remove, by this method you'd have a dependency. but in reality there isn't after squashing... how do you handle that?

2024-03-05 13:06 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +internal suspend fun List<PatchMapping>.orderByReferences(database: Database): List<PatchMapping> {
This function is called on the squashed `PatchMapping` and as such only finds the references that are present in it.

2024-03-05 16:29 UTC, jingtang10 approved these changes
thanks aditya! great job!

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +    // integrity is retained.
this needs to go into the function doc

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +/** Orders the [PatchMapping]s to maintain referential integrity during upload. */
needs examples

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +    insertResourceIds: Set<String>,
can you try to remove this as an argument - and just calculate this inside this function? does it make it look better?

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +  internal fun List<PatchMapping>.createAdjacencyListForCreateReferences(
i wonder if it looks better without this being an extension function - please just give it a try.

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
> +            createUpdateLocalChange(
maybe make this a bit more prominent - feel like this is the crux of this test case.

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
can you consider simplifying the test cases a little bit? are there shorter test cases that you can write that would give you the same coverage?

2024-03-05 16:29 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
> +        "observation-3",
i'm fine with this. but maybe add a comment to say that this order is so only because we know the implementation of the topological sort - it's entirely possible to generate a different order here which is acceptable/correct, should we have a different implementation of the topological sort.

2024-03-07 11:22 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +  // to it. This may make the sub graphs smaller and also help avoid cyclic dependencies.
NIT: Encapsulate this comment within /** */

2024-03-07 11:22 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +    private lateinit var _instance: PerResourcePatchGenerator
I think this should be marked @Volatile
[source](https://www.baeldung.com/kotlin/singleton-classes#1-companion-object)

2024-03-07 22:48 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt
> +    private lateinit var _instance: PerResourcePatchGenerator
Done

2024-03-07 22:48 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +  // to it. This may make the sub graphs smaller and also help avoid cyclic dependencies.
done

2024-03-07 22:48 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
> +        "observation-3",
Done

2024-03-07 22:51 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
Added a Utility to help create the LocalChange and LocalChangeResourceReference for various resources and operations (Create & Update). This has simplified reading the test.

2024-03-07 22:52 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
> +            createUpdateLocalChange(
Done

2024-03-07 22:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +  internal fun List<PatchMapping>.createAdjacencyListForCreateReferences(
Kept it as extension but removed the extra function argument.

2024-03-07 22:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +    insertResourceIds: Set<String>,
Done

2024-03-07 22:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +/** Orders the [PatchMapping]s to maintain referential integrity during upload. */
Done

2024-03-07 22:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +    // integrity is retained.
Done

2024-03-07 22:54 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/upload/patch/PatchOrderingTest.kt
> +          .also { localChanges.add(createInsertLocalChange(it, Random.nextLong())) }
Done

2024-03-07 22:54 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +object PatchOrdering {
Done

2024-03-07 22:54 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +  @VisibleForTesting(otherwise = VisibleForTesting.PROTECTED)
Done

2024-03-08 17:05 UTC, MJ1998 reviewed
I think we can have a better design:-
Crux: Instead of fetching LocalChanges we will fetch LocalChange.id as we don't need full LocalChange objects to create a toposort of Patches.

Steps:-

1. **fetchLocalChangeIds**(): List\<LocalChangeId\>
2. **orderByResourceTypeAndId**(): Map\<ResourceTypeWithId, List\<LocalChangeId\>\>
[ referencing ResourceTypeWithId as RTWI, and  List\<LocalChangeId\> as IDPatch ]
So orderByResourceTypeAndId(): Map\<RTWI, IDPatch\>
3. **buildTopoSort**(): List\<Pair\<RTWI, IDPatch\>\> (use database.getLocalChangeResourceReferenceIds)
4. **Process** this list based on UploadStrategy. For "single-resource" strategy process one by one, for "all-local-changes" process all of them at once. process = fetch whole of local changes: Flow\<List\<LocalChange\>\>
5. **patchGenerator**(List\<LocalChange\>\>): List\<Patch\>
6. **uploadRequestGenerator**(List\<Patch\>): List\<UploadRequest\>

Pros:-
This will significantly reduce the memory consumed by delaying the fetching of full LocalChange objects.
Supports both upload strategies.

Con:-
One caveat could be double database fetching. But fetching just the LocalChangeIds should not take much time as its LocalChangeEntity's PrimaryKey.

I think given we want to support offline, memory is a more concerning issue than time complexity to sync here. But without profiling the two designs agains a db it's difficult to say.

Also, maybe we can take this up as a new issue and a new PR.

2024-03-08 17:26 UTC, jingtang10 commented
> I think we can have a better design:- Crux: Instead of fetching LocalChanges we will fetch LocalChange.id as we don't need full LocalChange objects to create a toposort of Patches.
> 
> Steps:-
> 
> 1. fetchLocalChangeIds(): List<LocalChangeId>
> 2. orderByResourceTypeAndId(): Map<ResourceTypeWithId, List<LocalChangeId>>
>    set alias RTWI = ResourceTypeWithId
>    set alias IDPatch = List<LocalChangeId>
>    So orderByResourceTypeAndId(): Map<RTWI, IDPatch>
> 3. buildTopoSort(): List<Pair<RTWI, IDPatch>> (use database.getLocalChangeResourceReferenceIds)
> 4. Process this list based on UploadStrategy. For "single-resource" strategy process one by one, for "all-local-changes" process all of them at once. process = fetch whole of local changes: Flow<List<LocalChange>>
>    Now our old approach
> 5. patchGenerator(List<LocalChange>>): List<Patch>
> 6. uploadRequestGenerator(List<Patch>): List<UploadRequest>
> 
> Pros:- This will significantly reduce the memory consumed by delaying the fetching of full LocalChange objects. Supports both upload strategies.
> 
> Con:- One caveat could be double database fetching. But fetching just the LocalChangeIds should not take much time as its LocalChangeEntity's PrimaryKey.
> 
> I think given we want to support offline, memory is a more concerning issue than time complexity to sync here. But without profiling the two designs agains a db it's difficult to say.
> 
> Also, maybe we can take this up as a new issue and a new PR.

thanks for this suggestion jajoo! i'd like to understand a bit better the exact savings of this approach. but yes we should do this in a separate issue.

2024-03-08 17:31 UTC, jingtang10 approved these changes

2024-03-08 17:33 UTC, jingtang10 commented
looks good - if jajoo is ok with this you can merge this aditya!

thanks!

2024-03-08 17:55 UTC, MJ1998 reviewed
LGTM

2024-03-08 17:56 UTC, MJ1998 approved these changes

2024-03-11 12:13 UTC, merged

2024-03-20 12:43 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +
Same here.

2024-03-20 12:44 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +
I unblock myself by updating given change to 
```
SELECT *
        FROM LocalChangeResourceReferenceEntity
        WHERE localChangeId IN (:localChangeId)
```