Loading workerContext using the Knowledge manager
google/android-fhir pull request #2449
Opened 2024-02-26 09:07 UTC by nsabale7

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2448

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-03-05 09:05 UTC, owais-vd commented
@nsabale7 just a question about the worker-context. I'm not sure why we created two different worker-context.
1. https://github.com/google/android-fhir/pull/2449/files#diff-0abdac65d1f5c5a9700253625ed1b9d36a465bc0b5fec7e7e9cf26c5abc02779R36
2. https://github.com/google/android-fhir/pull/2449/files#diff-63f547d1547f3d76757693a33c9f6ff6b911b03ab2aa4280843f9ddcddee3821R201

It shouldn't be one? and where the [loadWorkerContext](https://github.com/google/android-fhir/pull/2449/files#diff-63f547d1547f3d76757693a33c9f6ff6b911b03ab2aa4280843f9ddcddee3821R195) method is being called?

2024-03-05 09:41 UTC, nsabale7 commented
> 1. https://github.com/google/android-fhir/pull/2449/files#diff-0abdac65d1f5c5a9700253625ed1b9d36a465bc0b5fec7e7e9cf26c5abc02779R36
A. This defines a default simple worker-context object which does not load any packages.
> 2. https://github.com/google/android-fhir/pull/2449/files#diff-63f547d1547f3d76757693a33c9f6ff6b911b03ab2aa4280843f9ddcddee3821R201
A. This worker-context loads provided npmPackages and returns the object.

2024-03-05 09:44 UTC, joiskash requested changes
Please take a look at my comments. Thanks.

2024-03-05 09:44 UTC, joiskash commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +  private suspend fun loadWorkerContext(
This function is not being used anywhere. Is there something that is missing?

2024-03-05 09:44 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
Add a UT where multiple IGs are loaded.

2024-03-05 09:44 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val simpleWorkerContext: IWorkerContext = SimpleWorkerContext(),
This context should be set through the knowledge manager if it is available.

2024-03-05 09:44 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      structureMapExtractionContext.simpleWorkerContext.apply { setExpansionProfile(Parameters()) }
This simpleWorkerContext should be retrieved from the knowledge Manager

2024-03-05 10:47 UTC, nsabale7 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +  private suspend fun loadWorkerContext(
Rhis is knowledge manager api which returns worker context and can be used the application.

2024-03-05 10:50 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val simpleWorkerContext: IWorkerContext = SimpleWorkerContext(),
currently this has default value and can be replaced.

2024-03-05 10:52 UTC, nsabale7 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      structureMapExtractionContext.simpleWorkerContext.apply { setExpansionProfile(Parameters()) }
Please refer [this ](https://github.com/google/android-fhir/issues/2448#issuecomment-1962293873). It describes the usage of this api

2024-03-05 18:22 UTC, jingtang10 commented
fyi left a comment in the issue: https://github.com/google/android-fhir/issues/2448#issuecomment-1979375776

i think we need to resolve this before we can merge this pr

2024-03-18 06:31 UTC, nsabale7 commented
@joiskash @owais-vd @dubdabasoduba @jingtang10 I have added test using outbreak package. Please review this PR.

2024-04-18 06:50 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      structureMapExtractionContext.simpleWorkerContext.apply { setExpansionProfile(Parameters()) }
The simpleWorkerContext is being loaded from KM and provided via `StructureMapExtractionContext`. This is the agreed behaviour from Jing's comment [here](https://github.com/google/android-fhir/issues/2448#issuecomment-1983793669)

2024-04-18 06:53 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val simpleWorkerContext: IWorkerContext = SimpleWorkerContext(),
The workerContext is currnetly loaded using KM api `loadWorkerContext` and provided to the datacapture (specifically ResourceMapper) via `StructureMapExtractionContext`. If that's what you mean by "through" KM then we can resolve this comment.

2024-04-18 06:56 UTC, MJ1998 approved these changes
LGTM

2024-04-18 09:24 UTC, MJ1998 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +   * Loads and initializes a worker context with the specified npm packages.
Add in this kdoc a use case of this api or link to the test in `ResourceMapperTest`.

2024-04-18 15:09 UTC, merged