Failing Test Case has been Corrected Now
google/android-fhir pull request #245
Opened 2021-02-18 15:16 UTC by MuhammadSalman-7214

2021-02-18 17:23 UTC, jingtang10 requested changes

2021-02-18 17:23 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +            .isEqualTo("10.0")
move to the line above

2021-02-18 17:48 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +            .isEqualTo("10.0")
you are saying that I move line 137 to merge with 136 or move both 136 and 137 lines to merge with line 135?

2021-02-18 17:49 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +            .isEqualTo("10.0")
No I'm saying you don't need a new line. This can be on the same line as the previous line.

2021-02-19 14:01 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactoryInstrumentedTest.kt
> +            .isEqualTo("10.0")
Done

2021-02-19 15:02 UTC, jingtang10 commented
Hi @MuhammadSalman-7214 thanks for the fix. I have incorporated your change in https://github.com/google/android-fhir/pull/248 which was submitted last night to fix the build. I'll close this PR for now.

2021-02-19 15:02 UTC, closed without merging

2021-02-19 15:06 UTC, MuhammadSalman-7214 commented
ok great @jingtang10