Update the purge API to accept a list of resource IDs
google/android-fhir pull request #2462
Opened 2024-03-05 15:48 UTC by ndegwamartin

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2439 

**Description**
1. Overloaded the `FhirEngine.purge` and modified `Database.purge` since has access modifier `internal` which is reused by the FhirEngine overloads.
2. In the implementation of `Database.purge`, wrapped the processing of the resource ids list in a transaction. Either they all pass or it fails.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Feature

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-03-05 15:51 UTC, vorburger commented
@ndegwamartin Thank You for requesting a review from me!

As I only "volunteer" and do not "work for" this project, unfortunately I do not have the "free cycles" to help here.

I trust that some of my colleagues who are working on this project will review this.

Thank You for your understanding!

2024-03-11 09:15 UTC, MJ1998 requested changes

2024-03-11 09:15 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    database.purge(type, ids, forcePurge)
Should this fail, I think we should report to the application "why".
Maybe propagate the transaction failure with a proper message ?

2024-03-11 09:15 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   */
Add kdoc to the base function about what happens when purging of the whole list fails.

2024-03-18 17:09 UTC, ndegwamartin commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    database.purge(type, ids, forcePurge)
This can fail for a number of reasons:
1. The Resource in question is not found in the DB 
2. The Resource has ref. entries in the local changes table and FORCE_PURGE is false
3. Some other (system) issue

For the first two we throw the exceptions explicitly for each resource processed

2024-04-04 09:52 UTC, ndegwamartin commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    database.purge(type, ids, forcePurge)
After the conversation today we've agreed to wrap the whole batch list processing logic in a transaction. Thus if any item fails it throws an `IllegalStateException`. 

Left [the same comment on ticket #2439](https://github.com/google/android-fhir/issues/2439#issuecomment-2036718710) as well

2024-04-04 13:51 UTC, MJ1998 approved these changes
There is one scenario which we never covered. What happens in case we purge a resource with forcePurge set to true but there is same resource reference in another LocalChange - referential integrity broken. 
For example when application does a purge Patient of given id(s) but not Observation. 

We can either:-
1. Support reference resource recursive purging with another flag.
2. Throw an exception when there are references which were not purged ?

This can be taken up in a new PR. Could you create an issue for the same?  thanks.

Nit comments. 
LGTM.

2024-04-04 13:51 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   * Purges a resource from the database based on resource type and id without any deletion of data
Can you modify it to suit set of ids. Maybe:-
`Purges resources of the specified type, identified by their IDs.`

2024-04-04 13:51 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * Purge resources from database based on resource type and id without any deletion of data from
Similarly here.

2024-04-12 14:34 UTC, ndegwamartin commented
@MJ1998 ticket created there https://github.com/google/android-fhir/issues/2510

2024-04-18 12:28 UTC, ndegwamartin commented
@MJ1998 when you get a chance please assist in merging this

2024-04-18 13:35 UTC, merged