In progress : Resource Creation using POST http verb
google/android-fhir pull request #2464
Opened 2024-03-06 06:07 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2440 

**Description**
Resource is created locally, http post verb is used to sync the resource with fhir server, in return server send response with resource with newly created resource id, then local database is updated with given resource.
Upload strategy : SingleResourcePost
Update response resource resourceId in the local database.
Update response resource meta data in the local database.
Update response resource json payload in the local database.

Update reference id in the resource : (in progress)

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-03-19 06:31 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +              val preSyncResourceId = it.localChanges.firstOrNull()?.resourceId
I think `preSyncResourceId` will be non null for PUT upload strategy, right ?

2024-03-20 13:29 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +              val preSyncResourceId = it.localChanges.firstOrNull()?.resourceId
Yes, every resource has a resource ID.

2024-03-27 14:37 UTC, jingtang10 requested changes

2024-03-27 14:37 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/ResourceConsolidatorTest.kt
> +    assertThat(database.select(ResourceType.Patient, "patient2").logicalId)
Also check (in this test case or in a new test case) that patient1 has been updated / deleted.

2024-03-27 14:37 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/ResourceConsolidatorTest.kt
> +    assertThat(
Maybe separate this into a separate test case?

2024-03-27 14:37 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * Maps the [postSyncResource] with the [preSyncResourceId] present in the [ResourceEntity],
Rephrase by saying "Updates ..."

2024-03-27 14:40 UTC, jingtang10 requested changes

2024-03-27 14:40 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      updateLocalChangesPostSync(postSyncResource, preSyncResource)
i find the change of the order of pre/post resources in the argument list a bit confusing

2024-03-28 11:34 UTC, jingtang10 requested changes

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +        iParser.parseResource(preSyncResourceEntity.serializedResource) as Resource
optionally - these two can be inlined together

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun getResourceUuidToUpdateReferences(preSyncResource: Resource): List<UUID> {
can you add documentation

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun getResourceUuidToUpdateReferences(preSyncResource: Resource): List<UUID> {
some naming suggestions:

get resource uuids that referece the given resource
get dependent resource uuids
get resource uuids with references

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun getResourceUuidToUpdateReferences(preSyncResource: Resource): List<UUID> {
especially explain that you're going from resource -> local change references -> local changes.

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      val uuids = getResourceUuidToUpdateReferences(preSyncResource)
move this line to just before 187 and maybe add a new line before this...

so that it's clear you have 3 steps
1. update the resource itself
2. update the local changes to resources that reference the posted resource
3. update the resources that reference the posted resource

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      val uuids = getResourceUuidToUpdateReferences(preSyncResource)
actually can you try flipping 2 and 3? feels it's a little bit more "logical"....

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun updateResourcePostSync(
because these functions' names are so similar - even though they are private, can you add some documentation?

2024-03-28 11:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      updateReferringResources(
can you check test coverage on this function?

2024-04-03 07:55 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/ResourceConsolidatorTest.kt
> +    assertThat(database.select(ResourceType.Patient, "patient2").logicalId)
done.

2024-04-03 07:55 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/ResourceConsolidatorTest.kt
> +    assertThat(database.select(ResourceType.Patient, "patient2").logicalId)
done.

2024-04-03 07:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      updateLocalChangesPostSync(postSyncResource, preSyncResource)
done.

2024-04-03 07:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +        iParser.parseResource(preSyncResourceEntity.serializedResource) as Resource
done.

2024-04-03 07:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun getResourceUuidToUpdateReferences(preSyncResource: Resource): List<UUID> {
done.

2024-04-03 07:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun getResourceUuidToUpdateReferences(preSyncResource: Resource): List<UUID> {
done.

2024-04-03 07:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      val uuids = getResourceUuidToUpdateReferences(preSyncResource)
done

2024-04-03 07:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  private suspend fun updateResourcePostSync(
done.

2024-04-03 08:01 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      updateReferringResources(
Acknowledged.

2024-04-04 09:21 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +}
Is this extra ?

2024-04-05 09:32 UTC, dubdabasoduba commented
> @santosh-pingle How is this going to work? Are we making it the default behaviour for all CREATEs.
> 
> Right now if you **POST** to a HAPI server, the server assigns the resource its own `id`.
> 
> e.g posting the following resource
> 
> ```json
> {
>   "resourceType": "List",
>   "id": "af17fe86-561a-44b0-84d3-5e75c753f6f8",
>   "meta": {
>     "versionId"  : "1"                            ,
>     "lastUpdated": "2024-03-13T15:41:42.808+00:00",
>     "source"     : "#fd2dc30247cf61b8"
>   },
>   "identifier": [
>     {"use": "official", "value": "f39c5f68-ab0f-4ae5-a9e2-47b0beb73d8e"}
>   ],
>   "status": "current",
>   "code": {
>     "coding": [
>       {
>         "system" : "http://smartregister.org/",
>         "code"   : "22138876"                 ,
>         "display": "Supply Inventory List"
>       }
>     ],
>     "text": "Supply Inventory List"
>   }
> }
> ```
> 
> will result in
> 
> ```json
> {
>   "resourceType": "List",
>   "id": "1759",
>   "meta": {
>     "versionId"  : "1"                            ,
>     "lastUpdated": "2024-04-04T09:09:05.431+00:00",
>     "source"     : "#fd2dc30247cf61b8"
>   },
>   "identifier": [
>     {"use": "official", "value": "f39c5f68-ab0f-4ae5-a9e2-47b0beb73d8e"}
>   ],
>   "status": "current",
>   "code": {
>     "coding": [
>       {
>         "system" : "http://smartregister.org/",
>         "code"   : "22138876"                 ,
>         "display": "Supply Inventory List"
>       }
>     ],
>     "text": "Supply Inventory List"
>   }
> }
> ```
> 
> The above behaviour is going to distort the resource references for any resources created on the mobile application
> 
> cc: @ellykits @qiarie @ndegwamartin

This was clarified on the SDK dev call. I think this is a good addition

2024-04-08 21:15 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +      FhirContext.forCached(FhirVersionEnum.R4)
nit: for here and rest of the file
```suggestion
      FhirContext.forR4Cached()
```
maybe?

2024-04-08 21:15 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun postSync_resourceConsolidation_updateResourceId() = runBlocking {
```suggestion
  fun consolidate_should_update_resourceId() = runBlocking {
```

2024-04-08 21:15 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun postSync_resourceConsolidation_updateReferencesForResource() = runBlocking {
```suggestion
  fun consolidate_should_update_resourceId_in_reference_in_other_resources() = runBlocking {
```

2024-04-08 21:15 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun postSync_resourceConsolidation_updateReferencesForLocalChanges() = runBlocking {
```suggestion
  fun consolidate_should_update_resourceId_in_reference_in_localChanges() = runBlocking {
```

2024-04-10 11:58 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +}
Actually, it has shown this line 94 as new change, and line 195 as old change.

2024-04-10 12:00 UTC, santosh-pingle commented
> @santosh-pingle How is this going to work? Are we making it the default behaviour for all CREATEs.
> 
> Right now if you **POST** to a HAPI server, the server assigns the resource its own `id`.
> 
> e.g posting the following resource
> 
> ```json
> {
>   "resourceType": "List",
>   "id": "af17fe86-561a-44b0-84d3-5e75c753f6f8",
>   "meta": {
>     "versionId"  : "1"                            ,
>     "lastUpdated": "2024-03-13T15:41:42.808+00:00",
>     "source"     : "#fd2dc30247cf61b8"
>   },
>   "identifier": [
>     {"use": "official", "value": "f39c5f68-ab0f-4ae5-a9e2-47b0beb73d8e"}
>   ],
>   "status": "current",
>   "code": {
>     "coding": [
>       {
>         "system" : "http://smartregister.org/",
>         "code"   : "22138876"                 ,
>         "display": "Supply Inventory List"
>       }
>     ],
>     "text": "Supply Inventory List"
>   }
> }
> ```
> 
> will result in
> 
> ```json
> {
>   "resourceType": "List",
>   "id": "1759",
>   "meta": {
>     "versionId"  : "1"                            ,
>     "lastUpdated": "2024-04-04T09:09:05.431+00:00",
>     "source"     : "#fd2dc30247cf61b8"
>   },
>   "identifier": [
>     {"use": "official", "value": "f39c5f68-ab0f-4ae5-a9e2-47b0beb73d8e"}
>   ],
>   "status": "current",
>   "code": {
>     "coding": [
>       {
>         "system" : "http://smartregister.org/",
>         "code"   : "22138876"                 ,
>         "display": "Supply Inventory List"
>       }
>     ],
>     "text": "Supply Inventory List"
>   }
> }
> ```
> 
> The above behaviour is going to distort the resource references for any resources created on the mobile application
> 
> cc: @ellykits @qiarie @ndegwamartin

We have kept existing DefaultConsolidator as it is.

2024-04-11 02:57 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +  }
thanks! This api is not required, I have removed it.

2024-04-11 02:58 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      }
thanks! i have update api for super method.

2024-04-11 03:08 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +internal class HttpPostResourceConsolidator(private val database: Database) : ResourceConsolidator {
Actually, HttpPostResourceConsolidator is not the DefaultResourceConsolidator. The DefaultResourceConsolidator is designed for a specific HTTP verb, such as PUT. Additionally, I see that there is no common code. I have already moved a couple of helper APIs from the DefaultResourceConsolidator, and consolidate() has to be overridden.

2024-04-11 03:08 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +      FhirContext.forCached(FhirVersionEnum.R4)
done.

2024-04-11 03:08 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun postSync_resourceConsolidation_updateResourceId() = runBlocking {
done.

2024-04-11 03:09 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun postSync_resourceConsolidation_updateReferencesForResource() = runBlocking {
done.

2024-04-11 03:09 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun postSync_resourceConsolidation_updateReferencesForLocalChanges() = runBlocking {
done

2024-04-19 09:17 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +internal class HttpPostResourceConsolidator(private val database: Database) : ResourceConsolidator {
Resource creation and updates work for this HttpPostResourceConsolidator.

2024-05-02 09:49 UTC, MJ1998 requested changes

2024-05-02 09:49 UTC, MJ1998 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .syncUpload(AllChangesSquashedBundlePut) {
Should this UploadStrategy come from some configuration ?
Also this is "PUT" ?!

2024-05-02 09:49 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
Is this API different from  `updateResourceAndReferences` we already have in Database ?

2024-05-02 09:51 UTC, MJ1998 commented
Checkout this PR which added bunch of stuffs for POST upload strategy.

2024-05-06 09:17 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .syncUpload(AllChangesSquashedBundlePut) {
Yes, this strategy is fetched from FhirSyncWorker, which is provided by the application.

https://github.com/google/android-fhir/pull/2464/files#diff-b6ecd05373073db7061842a028f92cd818ba7b9fa34f0f7beb496211a6c38060R105

2024-05-06 09:29 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .syncUpload(AllChangesSquashedBundlePut) {
It just uses the LocalChangesFetchMode.AllChanges from AllChangesSquashedBundlePut strategy.

You can pass any other upload strategy with the value `LocalChangesFetchMode.AllChanges.

2024-05-06 10:03 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
There was something that was not updated or included in the old API. Let me check what was not included.

2024-05-06 10:12 UTC, santosh-pingle commented
> Checkout [this PR](https://github.com/google/android-fhir/pull/2217) which added bunch of stuffs for POST upload strategy.

Yes, I am using the core logic as it is. Only delta changes are added on top of it to achieve the end-to-end use case for resource consolidation.

2024-05-06 10:37 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
Essentially, the old API was not updating metadata such as version ID, last updated time, and the new resource ID in both the payload of the resource and externally

2024-05-06 11:01 UTC, MJ1998 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .syncUpload(AllChangesSquashedBundlePut) {
The wondering is that this should be "POST" strategy right ? - and not "PUT" ?
Something like `AllChangesSquashedBundlePost` .

2024-05-06 11:02 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
Shouldn't we modify the existing API to update metadata instead of creating a new API ?
Or in case if this is not possible then rename the APIs to distinguish them properly ?

2024-05-06 11:15 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .syncUpload(AllChangesSquashedBundlePut) {
This change has nothing to do with the POST strategy. These tests already exist and were added for the old default behavior. It's just an API signature change that requires the UploadStrategy value.

The rationale behind passing AllChangesSquashedBundlePut instead of AllChangesSquashedBundlePOST is that these tests were added when the default behavior (PUT) was present, just to avoid confusion. Nonetheless, it will work even if you pass AllChangesSquashedBundlePOST, as they only expect the LocalChangesFetchMode.AllChanges value.

Tests for resource consolidation for the POST verb are written separately in a separate suite.

2024-05-06 11:16 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
I am thinking of renaming api.

2024-05-06 11:51 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
Also the kdoc for both

2024-05-08 10:51 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
fixed version id issue in existing api.

2024-05-21 15:35 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
Exisitng api you mean `updateResourceAndReferences`  which is already there in DatabaseImpl ?

2024-05-21 16:34 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +  suspend fun updateResourcesAndLocalChangesPostSync(
Can you please confirm if you have the latest code changes? For me it looks like you are referring outdated code which is no more present in the pr.
`updateResourcesAndLocalChangesPostSync` is no longer valid, and the `Database` file does not contain any changes in the PR.

Actual fix is here
engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt

2024-05-24 02:52 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +  internal suspend fun updateReferencesInLocalChange(
Why change this to internal ?

2024-05-24 02:52 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +      .syncUpload(uploadConfiguration.uploadStrategy, uploadConfiguration.uploader::upload)
has spotless been applied on this code ?

2024-05-24 02:52 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +        /* For now, do nothing (we do not delete the local changes from the database as they were
But we have already deleted the local changes above ?

2024-05-24 02:52 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +  object SingleResourcePost :
Can you move this above to where all the implemented UploadStrategies are there. Check for this comment in the code: 
```
As
   * and when an [UploadStrategy] is implemented, it should be moved above this comment section and
   * made non private.
```

2024-05-24 08:58 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +        /* For now, do nothing (we do not delete the local changes from the database as they were
Local changes are only deleted if upload operation is successful.

2024-05-24 09:23 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +  object SingleResourcePost :
done.

2024-05-24 09:24 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +  internal suspend fun updateReferencesInLocalChange(
This change is not required, its outdated change.

2024-05-24 11:26 UTC, MJ1998 reviewed
Thanks this looks good now!
Can we add few integration tests as well ? Maybe in FhirEngineImplTest ?

2024-05-28 06:00 UTC, MJ1998 approved these changes
LGTM

2024-05-28 06:00 UTC, MJ1998 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun `test consolidate() is called`() = runBlocking {
```suggestion
  fun `test local changes are consumed when using POST upload strategy`() = runBlocking {
```

2024-05-28 06:40 UTC, santosh-pingle commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +  fun `test consolidate() is called`() = runBlocking {
done.

2024-05-28 07:39 UTC, merged