Fix issue on windows with sqlite
google/android-fhir pull request #2471
Opened 2024-03-12 09:20 UTC by icrc-fdeniger

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2470

**Description**
To be polished.
- move stdlib to 1.9.20 ( to be compatible with ksp 1.9.21
- use ksp instead of kapt

**Alternative(s) considered**
Have to run the demo in admin mode on windows but not possible due to our entreprise policy

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-03-13 16:51 UTC, jingtang10 commented
thanks for this pr this looks fine to me if tests pass

2024-03-13 16:51 UTC, jingtang10 approved these changes

2024-03-14 04:47 UTC, MJ1998 requested changes

2024-03-14 04:47 UTC, MJ1998 commented on demo/build.gradle.kts
> -  id(Plugins.BuildPlugins.kotlinKapt)
Is it needed to remove this or will it work even with this ?

2024-03-14 04:47 UTC, MJ1998 commented on engine/build.gradle.kts
> +  id(Plugins.BuildPlugins.kotlinKsp).version(Plugins.Versions.ksp)
Is it needed to apply the version here ? Can we not do something similar to the other Plugins being added here ?

2024-03-14 04:47 UTC, MJ1998 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/db/dao/KnowledgeDao.kt
> +  internal abstract suspend fun deleteOrphanedResources(): Int
Is this causing an error with ksp? If not, then this is not needed to be changed in this PR.

2024-03-14 08:07 UTC, jingtang10 commented on demo/build.gradle.kts
> -  id(Plugins.BuildPlugins.kotlinKapt)
no we don't want unnecessary dependencies

2024-03-14 08:48 UTC, icrc-fdeniger commented on knowledge/src/main/java/com/google/android/fhir/knowledge/db/dao/KnowledgeDao.kt
> +  internal abstract suspend fun deleteOrphanedResources(): Int
this modification has been done by @jingtang10. I suppose it's ok :)

2024-03-14 10:04 UTC, icrc-fdeniger commented
push a new version with something similar to other plugins.
3 tests are failing with this error:
`java.lang.IllegalStateException: Illegal connection pointer 4411. Current pointers for thread Thread[arch_disk_io_1 @coroutine#204,5,SDK 24] []`
Will try to investigate today. don't know the root cause for now

2024-03-14 17:04 UTC, icrc-fdeniger commented
I fixed some unit tests:

- NpmFileManagerTest: was failing on Windows due to File separator.
- FhirSyncWorkerTest: I add to start in test mode and clean up FhirEngineProvider to let the test pass. Without this modification I get the  error `java.lang.IllegalStateException: Illegal connection pointer 4411` 

Some tests are still failing and I suppose it's due to my locale:

- For instance QuestionnaireUiEspressoTest (expected: 2005-01-05T06:10 but was : 2005-01-05T18:10)

2024-03-14 17:48 UTC, MJ1998 commented
I believe the test failing in QuestionnaireUiEspressoTest is `dateTimePicker_shouldSetAnswerWhenDateAndTimeAreFilled`. It's a flaky test.  Even [this PR](https://github.com/google/android-fhir/pull/2326) has this problem.
@jingtang10 Is someone working on this flaky test ?

2024-03-14 17:49 UTC, MJ1998 approved these changes
LGTM. Thanks for testing these out on Windows.

2024-03-15 10:14 UTC, jingtang10 commented
> Some tests are still failing and I suppose it's due to my locale:

thanks for these! we shouldn't have tests that fail in different locales - we should fix those - can you point out which tests those are?

2024-03-15 10:15 UTC, jingtang10 commented
> I believe the test failing in QuestionnaireUiEspressoTest is `dateTimePicker_shouldSetAnswerWhenDateAndTimeAreFilled`. It's a flaky test. Even [this PR](https://github.com/google/android-fhir/pull/2326) has this problem. @jingtang10 Is someone working on this flaky test ?

got ya - can you take a look at this?

2024-03-16 09:58 UTC, vorburger commented
FYI I have created #2485 re. the flaky `QuestionnaireUiEspressoTest$dateTimePicker_shouldSetAnswerWhenDateAndTimeAreFilled` test 12/24h problem.

2024-03-18 07:23 UTC, icrc-fdeniger commented
Hello, thanks for your answers. Is there another step to let this PR be accepted ? I see that Kokoro step is still pending but I can't have the details.

2024-03-18 14:12 UTC, vorburger commented
> Hello, thanks for your answers. Is there another step to let this PR be accepted ?

I (only now, didn't look before) noticed that it already has 2 approvals and auto-merge, so it just needs a green build, then it will go in.

> I see that Kokoro step is still pending but I can't have the details.

There were some problems which were just solved, see #2485 and #2488, I've tried to click _Update branch_ to see if it helps.

2024-03-18 16:26 UTC, vorburger commented
@icrc-fdeniger following the merge of #2463 there is a small conflict - can you have a look and (manually) resolve that? Tx!

2024-03-25 11:57 UTC, merged