Activity flow api changes.
google/android-fhir pull request #2476
Opened 2024-03-14 14:42 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2469

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-08-05 10:27 UTC, MJ1998 requested changes
This looks great!
Requesting few small changes .

2024-09-12 10:42 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +    } catch (e: Exception) {
Removed the catching of exception. The error is propagated to the users now since we can't recover it.

2024-09-12 10:44 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResource.kt
> +    resource.update()
This is a helper function for the users to update a Resource directly. This doesn't persist it into the Repository.
User needs to call `PerformPhase.update` to persist it where these check are done.

2024-09-12 10:45 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/request/CPGRequestResource.kt
> +    resource.update()
This is a helper function for the users to update a Resource directly. This doesn't persist it into the Repository.
User needs to call `RequestPhase.update` to persist it where these check are done.

2024-09-12 10:47 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResourceForOrderMedication.kt
> +abstract class CPGEventResourceForOrderMedication<out R : Resource>(override val resource: R) :
Done

2024-09-12 10:50 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGCaseEvent.kt
> +class CPGCaseEvent(override val resource: EpisodeOfCare) :
I have tried to keep the naming in line with the [CPG classes](https://build.fhir.org/ig/HL7/cqf-recommendations/activityflow.html#activity-lifecycle---event-phase) . This particular is for [Enroll a patient](https://build.fhir.org/ig/HL7/cqf-recommendations/examples-activities.html#enroll-a-patient)

2024-09-12 10:52 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGCommunicationEvent.kt
> +          status = Communication.CommunicationStatus.PREPARATION
The request and even are two different FHIR resource classes and their status are incompatible enums.

2024-09-12 11:02 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +  override suspend fun <D : E> startPerform(klass: Class<D>, init: R.() -> Unit): EndPerform<D> {
The function has changed a bit but the `klass: Class<D>` param is still there.
The type declaration `<D : E>` makes sure that the `Class<D>` is specific Event to the started activity and not any generic Event class.
e.g. When Order a Medication Activity is created `ActivityFlow<CPGMedicationRequest, CPGOrderMedicationEvent<*>>` , `startPerform` will only take CPGOrderMedicationEvent types.

2024-09-12 11:08 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlowPhases.kt
> +  suspend fun <D : E> startPerform(klass: Class<D>, init: R.() -> Unit): EndPerform<D>
The APIs are changed in the new code. And the `beginPerform` is now `draftPerform` as it aligns more with that the expectation of `beginPerform` is.

2024-09-12 11:08 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlowPhases.kt
> +  suspend fun startOrder(init: R.() -> Unit): EndOrder<R, E>
The APIs are changed in the new code. And the beginOrder is now draftOrder as it aligns more with that the expectation of beginOrder is.

2024-09-12 11:09 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlowPhases.kt
> +  suspend fun startPlan(init: R.() -> Unit): EndPlan<R, E>
The APIs are changed in the new code. And the `beginPlan` is now `draftPlan` as it aligns more with that the expectation of `beginPlan` is.

2024-09-16 15:03 UTC, jingtang10 requested changes
can you add a page in the doc folder?

2024-09-16 15:41 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +  fun draftPlan(): Result<R> {
make it clear that this does not persist the draft.

2024-09-16 15:55 UTC, jingtang10 reviewed
just noting comments from bryn:

1. Can we change "draft" to "prepare"
2. Can we change "start" to "submit"
3. Can we change "resume" in the test cases to "continue"?

2024-09-17 16:42 UTC, MJ1998 requested changes
Thanks Aditya for the changes. 
2 main concerns:-
1. Should we consider making the operations asynchronous ? Since we are dealing with Repository it only makes sense to do the operations in a IO coroutine. Suggesting to make the initiate and update methods suspend functions.
2. Do you think we should add a rollback api ? If there are errors in later phases one might want to rollback. To do this we could maintain a stack pf phases instead of only the currentPhase.

2024-09-17 16:42 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +   * @return [R] if the action is successful, error otherwise.
Correct the return kdoc.
```suggestion
   * @return [Result]<R> containing the draft plan resource if the action is successful, [Result.failure] otherwise.
```

2024-09-17 16:42 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +   * @return [R] if the action is successful, error otherwise.
Correct the return kdoc like above and other places.

2024-09-17 16:42 UTC, MJ1998 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +class ActivityFlow<R : CPGRequestResource<*>, E : CPGEventResource<*>>
Can you comment on thread-safety of this class ?

2024-09-17 16:42 UTC, MJ1998 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +  fun `order medication flow for medication dispense no test `(): Unit = runBlockingOnWorkerThread {
Is this the same as `order medication flow for medication dispense` ?
I see a lot of duplicate codes. Can we reuse them ?

2024-09-17 16:42 UTC, MJ1998 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +  fun `draftPlan is success when flow is in proposal phase`(): Unit = runBlockingOnWorkerThread {
Maybe this is better ?
```suggestion
  fun `preparePlan should succeed when in proposal phase`(): Unit = runBlockingOnWorkerThread {
```

2024-09-17 16:42 UTC, MJ1998 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +  fun `draftPlan is failure when flow is in plan phase`(): Unit = runBlockingOnWorkerThread {
Similarly others ?
```suggestion
  fun `preparePlan should fail when in plan phase`(): Unit = runBlockingOnWorkerThread {
```

2024-09-18 11:27 UTC, aditya-07 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +      ActivityFlow2.sendMessage(
Outdated

2024-09-18 11:29 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/request/CPGRequestResource.kt
> + * This may not represent all the Request Resource status. For the activity flow, we may ony be
The doc has been changed completly.

2024-09-18 11:29 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +  get() = getResourceClass<Resource>(reference.split("/")[0])
Moved them to appropriate places. Added comments and necessary example.

2024-09-18 11:30 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + * The user may do valid state transitions on the current phase by calling appropriate apis on
Rewrote doc. Please check.

2024-09-18 11:30 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + *   .draftPlan()
Done

2024-09-18 11:30 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + *       },
Done with new doc.

2024-09-18 11:31 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + * The application developer may create the flow of a new proposal and move it through the various
Done with new doc.

2024-09-18 11:31 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + *           update { addNote(Annotation(MarkdownType("Event looks OK."))) }
As discussed offline, removed `fun update` from CPG request and event classes.

2024-09-18 11:35 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +class ActivityFlow<R : CPGRequestResource<*>, E : CPGEventResource<*>>
`CPGRequestResource` and `CPGEventResource` are sealed classes and help us maintain the type safety for a particular `ActivityFlow`. The concrete implementations of `CPGRequestResource` and `CPGEventResource` take particular fhir resource classes.

We can't make `ActivityFlow` take HAPI FHIR Resource like medication request or medication dispense event since there is no hierarchy in HAPI FHIR  resources to distinguish Request and Event types.

2024-09-18 11:36 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/phase/request/PlanPhase.kt
> +class PlanPhase<R : CPGRequestResource<*>>(repository: Repository, r: R) :
Done

2024-09-18 11:36 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/phase/request/PlanPhase.kt
> +  override fun getPhaseName() = Phase.PhaseName.PLAN
Done

2024-09-18 11:36 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/CPGCaseEvent.kt
> +  CPGEventResource<EpisodeOfCare>(resource) {
Done.

2024-09-18 11:36 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +  fun draftPlan(): Result<R> {
Done

2024-09-18 11:36 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + * stages or they may resume the workflow of a request already in a later stage (plan,order).
Done

2024-09-18 11:38 UTC, aditya-07 commented on workflow/build.gradle.kts
> +  testImplementation(libs.kotlin.test.junit)
Done

2024-09-18 11:39 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> + * This abstracts the flow of various
Done

2024-09-24 07:57 UTC, aditya-07 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +  fun `draftPlan is failure when flow is in plan phase`(): Unit = runBlockingOnWorkerThread {
Done

2024-09-24 07:57 UTC, aditya-07 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +  fun `draftPlan is success when flow is in proposal phase`(): Unit = runBlockingOnWorkerThread {
Done

2024-09-24 07:58 UTC, aditya-07 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
> +  fun `order medication flow for medication dispense no test `(): Unit = runBlockingOnWorkerThread {
Removed it. There are 2 full flow tests here for now one for each supported activity.

2024-09-24 07:59 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +   * @return [R] if the action is successful, error otherwise.
Done

2024-09-24 07:59 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +   * @return [R] if the action is successful, error otherwise.
Done

2024-09-24 08:07 UTC, aditya-07 commented
> Thanks Aditya for the changes. 2 main concerns:-
> 
> 1. Should we consider making the operations asynchronous ? Since we are dealing with Repository it only makes sense to do the operations in a IO coroutine. Suggesting to make the initiate and update methods suspend functions.
> 2. Do you think we should add a rollback api ? If there are errors in later phases one might want to rollback. To do this we could maintain a stack pf phases instead of only the currentPhase.

1. Since we are working with `Repository` java interface and its implementation does a `runBlocking` call, it is better to keep it non-suspending. I have added a note to emphasize the use of worker thread when accessing AcivityFlow/ Phase apis.

2. Once a new phase is initiated, its success marks the previous phase as `Completed`  (status of the request in previous phase is updated to completed). The expectation is that once a Request is completed, it should never be mutated later. 
Keeping that in mind, I don't think we can allow phase rollback. 
Unless everything is OK, user won't be allow to `initiate` a new phase and once user is in new phase, old phase is completed.

2024-09-24 08:10 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResource.kt
> +  CANCELLED("not-done"),
Updated this system for different resources to specify the status code.

2024-09-24 08:10 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResource.kt
> +  DECLINED("decline"),
Updated this system for different resources to specify the status code.

2024-09-24 08:10 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResource.kt
> +        "not-done" -> CANCELLED
Updated this system for different resources to specify the status code.

2024-09-24 08:10 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResource.kt
> +        "decline" -> DECLINED
Updated this system for different resources to specify the status code.

2024-09-24 08:10 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/event/CPGEventResource.kt
> +    fun of(code: String) =
Updated this system for different resources to specify the status code.

2024-09-24 08:11 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/request/CPGGenerateReportTask.kt
> +class CPGGenerateReportTask(override val resource: Task) : CPGTaskRequest(resource) {
Removed for now

2024-09-24 08:11 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/request/CPGProposeDiagnosisTask.kt
> +class CPGProposeDiagnosisTask(override val resource: Task) : CPGTaskRequest(resource) {
Removed for now

2024-10-01 15:00 UTC, jingtang10 requested changes

2024-10-01 15:00 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/request/StatusCodeMapper.kt
> +internal interface StatusCodeMapper {
```suggestion
internal interface RequestStatusCodeMapper {
```

?

2024-10-01 15:00 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/EventStatusCodeMapper.kt
> +      else -> EventStatus.OTHER(code)
this block looks kinda odd with mixture of imported and not imported enum values - can we unify how we import these values?

2024-10-01 15:00 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/CPGOrderMedicationEvent.kt
> +        CPGMedicationDispenseEvent::class.java -> CPGMedicationDispenseEvent.from(request)
this is a bit odd to me - you're basically saying that the event class must be `CPGMedicationDispenseEvent`. why not just make that part this of class instead of asking the api user to pass the event class?

2024-10-01 15:00 UTC, jingtang10 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
the tests in this class are too long - can we make most of them super short? follow the patter:

1. set up
2. action
3. assertion

2024-10-04 04:45 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/request/StatusCodeMapper.kt
> +internal interface StatusCodeMapper {
Done

2024-10-04 04:45 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/EventStatusCodeMapper.kt
> +      else -> EventStatus.OTHER(code)
Done

2024-10-04 04:49 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/CPGOrderMedicationEvent.kt
> +        CPGMedicationDispenseEvent::class.java -> CPGMedicationDispenseEvent.from(request)
The Order Medication flow may result in one of three different events that we might not know until the perform is called. That's why `CPGOrderMedicationEvent` represents the abstract `Event` for the `Order Medication Activity`
and `CPGMedicationDispenseEvent` represents one of the outcomes of the said activity.
The other two eventually would be `CPGMedicationAdministration` and `CPGMedicationStatement`.

2024-10-04 04:50 UTC, aditya-07 commented on workflow/src/test/java/com/google/android/fhir/workflow/activity/ActivityFlowTest.kt
As per our discussion, removed the two flow tests as they aren't adding any additional value to the test.

2024-10-04 12:07 UTC, jingtang10 approved these changes

2024-10-04 12:58 UTC, MJ1998 approved these changes
LGTM.

2024-10-04 12:58 UTC, merged