Resource creation using AllChangesSquashedBundlePost upload strategy.
google/android-fhir pull request #2509
Opened 2024-04-08 07:03 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2499 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-07-29 18:44 UTC, nsabale7 requested changes
Please look into the meta tag overwriting issue, as we have encountered this problem.

2024-07-29 18:44 UTC, nsabale7 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +        }
I see that the resource's meta field is completely replaced with a new Meta object. This means that any tags added locally at the time of resource creation will be overwritten.

2024-07-29 18:44 UTC, nsabale7 commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +import java.util.*
nit: Remove wild card imports

2024-08-06 09:15 UTC, jingtang10 requested changes

2024-08-06 09:15 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +      FhirContext.forCached(FhirVersionEnum.R4)
can you just create the patient directly? i don't think this string is used anywhere else in this test.

same with the following test cases.

2024-08-06 09:15 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    val patientResponseEntry =
don't do firstOrNull - it's too lenient. in test we can just do first

2024-08-06 09:15 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    runBlocking {
use runTest on the entire test case?
```
fun testName = runTest {
  ...
}
```

2024-08-06 09:15 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    runBlocking {
and for other test cases

2024-08-06 09:15 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +      FhirContext.forCached(FhirVersionEnum.R4)
i do think for the bundles it's easier to read in JSON. but the patients encounters are simple enough to be created in memory?

2024-08-06 09:26 UTC, jingtang10 requested changes

2024-08-06 17:20 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  override suspend fun updateResourcesPostSync(
please add database tests for this.

2024-08-06 17:27 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun consolidate_allChangesBundleSquashedPost_shouldUpdateResourceId() = runBlocking {
actually they are different... the above tests are for ResourceUploadResponseMapping, and the new tests are for BundleComponentUploadResponseMapping.

@santosh-pingle can you clarify this with clearer test names please?

2024-08-13 08:41 UTC, joiskash commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +    if (response.hasEtag() && response.hasLastModified() && response.hasLocation()) {
Not really. Depends on the FHIR server https://www.hl7.org/fhir/resource.html#Meta _lastUpdated has a 0...1 cardinality.
I know EPIC FHIR interfaces do not support _lastUpdated.

2024-08-13 08:53 UTC, ndegwamartin commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +        }
We use the existing meta tags in our implementation with custom tags, is the idea to revert / enhance this or overwrite is the agreed upon approach?

2024-08-13 09:09 UTC, joiskash reviewed
I am not sure if this is already discussed, but here is use case that will need to be supported. We should discuss if there are any race conditions and potential OOMs -
CHW is offline for 2 weeks
Visits 30 houses per day
Each house has 4 family members
Each registration results in 30 resources per family member
This will create a total of 2*7*30*4*30 = 50,400 resources with references. Let us assume that there are no resources with base64 binary data. Each resource will roughly be 5KB that's roughly 100 MB of data to upload. 3G upload speed is around 0.4 MB/s. So this should take roughly 5 minutes to upload + post sync processing time. We could have some documentation around the performance of using POST vs PUT and the repercussions based on this.

2024-08-13 09:28 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/request/BundleEntryComponentGeneratorImplementations.kt
> +internal class HttpPostForCreateEntryComponentGenerator(useETagForUpload: Boolean) :
ignore this

2024-08-13 09:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +  internal suspend fun updateResourceAndIndexPostSync(
ignore this

2024-08-22 05:31 UTC, santosh-pingle commented
I am looking into the review comments.

2024-08-22 06:02 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +        }
done.

2024-08-22 06:03 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +import java.util.*
done.

2024-08-22 06:06 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +    postSyncResourceID: String,
done.

2024-08-22 06:12 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +                database.deleteUpdates(LocalChangeToken(tokenIds))
done.

2024-08-22 06:28 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    val secondResponseEntry = postSyncResponseBundle.entry[1]
removed secondResponseEntry, not required.

2024-08-22 07:22 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +        }
done.

2024-08-22 08:42 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +      FhirContext.forCached(FhirVersionEnum.R4)
done.

2024-08-22 10:11 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    runBlocking {
done.

2024-08-23 07:35 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * of referring resources, which is just redundant.
done.

2024-08-23 10:34 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * of referring resources, which is just redundant.
done.

2024-08-23 11:00 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +  fun consolidate_allChangesBundleSquashedPost_shouldUpdateResourceId() = runBlocking {
done.

2024-08-26 07:00 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +    preSyncResourceId: String,
done.

2024-08-26 09:27 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * [LocalChangeResourceReference.localChangeId]. [LocalChange] contains UUIDs for every resource.
done.

2024-08-26 09:38 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    postSyncSerializedResource: String,
done.

2024-08-26 10:37 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +    preSyncResourceId: String,
done.

2024-08-26 10:37 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * [LocalChangeResourceReference.localChangeId]. [LocalChange] contains UUIDs for every resource.
done

2024-08-26 10:38 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +    postSyncSerializedResource: String,
removed, not using anymore.

2024-08-27 07:34 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    runBlocking {
If I make this change, the tests start failing. runTest is actually designed for unit tests that run on the JVM, but these are Android tests.

2024-08-28 12:23 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/upload/ResourceConsolidator.kt
> +    if (response.hasEtag() && response.hasLastModified() && response.hasLocation()) {
done.

2024-08-28 12:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +   * be referenced as the reference value in other resources, returning those resource UUIDs.
this would work thanks - but also i wasn't asking you to list the resources in json format - you could just say you have a care plan and an observation both with subject being patient a and then you'd return the uuids of these two resources.

2024-08-28 12:45 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/upload/HttpPostResourceConsolidatorTest.kt
> +    runBlocking {
ok thanks for checking!

2024-09-04 06:24 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +   * be referenced as the reference value in other resources, returning those resource UUIDs.
api is not required anymore.

2024-09-05 10:20 UTC, jingtang10 approved these changes

2024-09-05 10:20 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(exception.message).isEqualTo("Resource not found with type Patient and id patient1!")
this can be broken down to 2 test cases. one to check new one is created. another to check old id is deleted.

2024-09-09 06:33 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(exception.message).isEqualTo("Resource not found with type Patient and id patient1!")
done.

2024-09-09 06:37 UTC, merged