draft (currentSyncJobStatus when the sync state in WorkManager is null)
google/android-fhir pull request #2511
Opened 2024-04-16 13:06 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2472

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-04-19 10:29 UTC, ndegwamartin commented
@santosh-pingle tested out the implementation, it works fine on our app and solves the issue we reported.

2024-05-02 06:16 UTC, joiskash approved these changes
Looks good, just left a small correction in documentation

2024-06-10 16:17 UTC, ndegwamartin commented
@jingtang10 anything left for this PR or can we merge it?

2024-07-04 11:15 UTC, jingtang10 requested changes

2024-07-04 11:15 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
can you remove the function:
```
private fun handleNullWorkManagerStatusForPeriodicSync(
    workInfoState: WorkInfo.State,
  ): CurrentSyncJobStatus
``` 

which is no longer used?

2024-07-04 11:15 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
upon reading this PR i got really confused what `getWorkerInfo` is returning. the doc for that function is actually really really thin. can you add more details and add some examples?

I asked gemini to create an example:

```
/**
 * Retrieves the detailed status and progress information for a specific [FhirSyncWorker] job.
 *
 * This function monitors the [WorkManager] for the specified work name and provides a reactive flow of updates.
 * Each update includes the current work state (e.g., ENQUEUED, RUNNING, SUCCEEDED, etc.) along with the 
 * parsed job-specific status if available.
 *
 * @param context The application context to access the WorkManager.
 * @param workName The unique identifier of the worker job to track.
 * 
 * @return A Flow of [Pair] objects where:
 *   * First element: The current [WorkInfo.State] of the job.
 *   * Second element (optional): A [SyncJobStatus] object deserialized from the worker's progress data.
 *     The specific type of [SyncJobStatus] depends on the "StateType" key in the progress data.
 *     If the progress data is empty, missing the necessary keys, or an error occurs during deserialization,
 *     this element will be null.
 * 
 * @throws JsonParseException If the Gson deserialization of the 'State' data fails.
 * @throws ClassNotFoundException If the class specified in 'StateType' is not found.
 */
```

please use this as an inspiration only

2024-07-04 12:03 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
> +  fun oneTime_worker_nextExecutionAfterSucceeded() {
can you rename this to say what the expectation is for this function? is it to test that the next execution should start with running?

also - can you double check if you revert your change in Sync.kt, this test case would fail?

2024-07-05 03:02 UTC, santosh-pingle commented
Working on review comments.

2024-07-05 06:52 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
> +  fun oneTime_worker_nextExecutionAfterSucceeded() {
actually, test is not failing after reverting the change, it looks like syncJobStatus value in workManager api is not null.

2024-07-05 08:34 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
> +  fun oneTime_worker_nextExecutionAfterSucceeded() {
Not sure how to set up condition WorkManager returns null status for ENQUEUED, RUNNING, and CANCELLED states for this specific change.

2024-07-05 08:36 UTC, santosh-pingle commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
added kotlin doc.

2024-07-05 13:51 UTC, santosh-pingle commented on engine/src/androidTest/java/com/google/android/fhir/sync/SyncInstrumentedTest.kt
> +  fun oneTime_worker_nextExecutionAfterSucceeded() {
acknowledged.

2024-07-05 13:51 UTC, merged