Add condition to not populate string value if it's empty
google/android-fhir pull request #2521
Opened 2024-04-23 02:22 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2520

**Description**
Add condition to not populate string value if it's empty

**Alternative(s) considered**
N/A

**Type**
Bug fix

**Screenshots (if applicable)**

https://github.com/google/android-fhir/assets/62053304/afe018e0-32c7-43a3-9e4f-393f96b7e9aa

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-04-29 08:45 UTC, MJ1998 requested changes

2024-04-29 08:45 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +          if (otherOption.isEmpty()) return@map
I think we should simply skip this case instead of returning from map!

2024-05-31 05:15 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/DialogSelectViewHolderFactory.kt
> +          if (otherOption.isEmpty()) return@map
Yeah filter all non empty text sounds better... 
In case there is more than zero non-empty texts then save them as answers else don't save an empty answer.

2024-07-03 18:23 UTC, jingtang10 reviewed
This is great - thanks very much for the contribution and jajoo for reviewing.

@FikriMilano, is there any way you can add a test to this? can you add a test file for optionselectdialogfragment? if it's easy to do we can also add a test in `QuestionnaireUiEspressoTest`

2024-09-03 09:14 UTC, jingtang10 approved these changes

2024-09-03 09:14 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/OptionSelectDialogFragment.kt
> +              .filter { it.currentText.isNotEmpty() }
can you just add a comment here to say that this is possible when the user inputs nothing for a new open choice option?

2024-09-04 05:28 UTC, MJ1998 approved these changes
LGTM

2024-09-04 05:28 UTC, merged