Improve initial load of calculated expression
google/android-fhir pull request #2522
Opened 2024-04-23 02:32 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2519

**Description**
On initial load of forms:
1. Iterate all items with calculated expression
2. Evaluate the calculated expression
3. Update the QR item answer

**Alternative(s) considered**
N/A

**Type**
Improvement

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-05-01 16:11 UTC, MJ1998 requested changes
What if there is an item (maybe display item) which is dependent on the initial calculated expression ?

2024-05-01 16:11 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              questionnaireResponse.allItems.find { qrItem -> qrItem.linkId == qItem.linkId } ?: QuestionnaireResponseItemComponent(),
What is the reason of adding `?: QuestionnaireResponseItemComponent()` ?

2024-05-01 16:11 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (modifiedQuestionnaireResponseItemSet.contains(questionnaireResponseItem)) return
Should we check this in the beginning of the function ?

2024-07-04 15:41 UTC, jingtang10 requested changes

2024-07-04 15:41 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> -            updateDependentQuestionnaireResponseItems(
so now that you stopped using this function, can you pls add documentation for this function and the new function and especially highlight the differences and when they should be used instead of the other one?

2024-07-09 20:07 UTC, jingtang10 requested changes
This is really great optimization! Thanks @FikriMilano!

This is not your code, but I've just noticed in the file `ExpressionEvaluator.kt` function `evaluateCalculatedExpressions` the use of `updatedQuestionnaireResponseItemComponent` is actually wrong. What should be passed as the %context should be the corresponding questionnaire response item of the questionnaire item with calculated expression that is affected. Can you please fix that in this PR? I think what you can do is to actually just pass a null value there and add a comment to say something like "to properly use %context we will need to find questionnaire item and questionnaire response item pairs etc.. but we won't do that now." You can then just simplify that function signature.

2024-07-09 20:07 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          ?: return@forEach
this can get quite complicated in the world of nested items and nested repeated groups because link ids no longer uniquely identify a questionnaire item or a questionnaire response item...

i've been meaning to write a helper function that traverses the two trees in parallel and match the pairs.. maybe it's time for me to do that..

2024-07-10 11:15 UTC, jingtang10 approved these changes
Thanks for the PR @FikriMilano great job!

2024-07-10 11:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
> +        // questionnaire item that has calculated expression, but we won't do that now
```suggestion
        // TODO: Pass the questionnaire response itemv corresponding to the
        // questionnaire item with the calculated expression for the FHIRPath supplement
        // `%context`
```

2024-07-10 11:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          ?: return@forEach
can you 1) create an issue and 2) add a todo here?

2024-07-10 12:47 UTC, jingtang10 approved these changes

2024-07-10 12:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (indexedValue.index == 0) {
put this if statement back in line 582.

i think it's better to signify that this function is only called to initialize calculated expressions.

2024-07-10 12:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private suspend fun initializeCalculatedExpression(
add some documentation - especially explain that in this funtion we go over all calculated expressions in the questionnaire and evaluate them.

```suggestion
  private suspend fun initializeCalculatedExpressions(
```

2024-07-10 12:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      modificationCount.update { count -> count + 1 }
i think this should be moved outside too

2024-07-10 12:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      evaluateAllCalculatedExpressions()
perhaps this functino can now be inlined?

2024-07-12 03:50 UTC, MJ1998 approved these changes

2024-07-15 13:18 UTC, merged