Ordering of patches with cyclic during upload
google/android-fhir pull request #2524
Opened 2024-04-23 06:56 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2500

**Description**
1. Find subgraphs (weakly connected) of Resources with cycles in them .
2. Pack the subgraphs in  Bundles such that a single subgraph is not split between two Bundles (as it may cause server error).
3. Order the remaining resources and add them to the Bundle (in remaining space of or new Bundles) .

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-05-01 16:11 UTC, MJ1998 commented
Is this ready for review ?

2024-05-17 06:01 UTC, MJ1998 requested changes
What if we use Strongly Connected Components (SCC) ? 
1. Identify the SCCs
2. Consolidate all nodes in each SCC into a supernode.
3. Then apply the same topological sorting

So for following graph:-
1 -> 2, 3
2 -> 4, 5
4 -> 1
5 -> 6
7 -> 8, 9
8 -> 7

SCC = [{1,2,4}, {7, 8}]
We can have the topological sort as - [{3}, {6}, {5}, {1, 2, 4}, {9}, {7, 8}]

Current solution is also right but the above solution has more improvements:-
1. Time complexity is one-fourth (I guess).
2. In current approach the weakly-connected-components will go in one bundle if there is a cycle. Whereas in the above approach only the SCC will go in one bundle -> Reduces the size of the bundle a lot.

2024-05-17 06:04 UTC, MJ1998 commented
It's the Tarjan's Algorithm: https://www.geeksforgeeks.org/tarjan-algorithm-find-strongly-connected-components/

2024-05-31 14:59 UTC, jingtang10 requested changes

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +   * [CombinedMapping] contains weakly connected [PatchMapping]s where one or more [PatchMapping]s
```suggestion
   * [CombinedMapping] contains strongly connected [PatchMapping]s where one or more [PatchMapping]s
```

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +internal sealed interface OrderedMapping {
i think there is no order in this structure itself - so maybe patch mapping group is a better name - or something similar?

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +  private fun stronglyConnectedComponents(diGraph: Graph, nodesCount: Int): List<List<Node>> {
optionally - you can separate all the logic related to scc to a separate class - and try to write it as an internal api.

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +      //      println(it.key)
```suggestion
```

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +    // replace the ssc nodes with super node
reformat this please (capitalise, punctuation etc)

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/request/TransactionBundleGenerator.kt
please udpate the unit tests here

2024-05-31 14:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/request/UrlRequestGenerator.kt
> +   * [PatchMapping].
this is good. but can you also add that we could potentially make this illegal in the future and explicitly introduce configurations for referential integrity on the server side.

and maybe just add a little bit to explain that single resource requests won't be able to handle resources referencing each other if the server is strict about referential integrity.

2024-06-05 09:33 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +   * [CombinedMapping] contains weakly connected [PatchMapping]s where one or more [PatchMapping]s
Done

2024-06-05 09:33 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +      //      println(it.key)
done

2024-06-05 09:33 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/request/TransactionBundleGenerator.kt
Done

2024-06-05 09:33 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/request/UrlRequestGenerator.kt
> +   * [PatchMapping].
Done

2024-06-05 09:33 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +    // replace the ssc nodes with super node
Done

2024-06-05 10:54 UTC, jingtang10 requested changes

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +  private fun transformGraphWithSSCtoGraphWithSuperNodes(
what this function actually does is: generating edges in the graph G' of super nodes from the edges in the original graph G.

so if there's an edge a->b in G, then there is an edge from S(a)->S(b) in G' where S(x) is the super node of x and S(a)!=S(b).

maybe you can add this to the description as at the moment it's not as detailed.

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +      .sscOrdered { createTopologicalOrderedList(it) }
i think you can do

```
.sscOrdered(::createTopologicalOrderedList)
```

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +internal class StronglyConnectedPatches(private val diGraph: Graph, private val nodesCount: Int) {
this needs some tests. especially simple cases e.g. graph of size 1, graph of size 0. graph of size 2 with or without a single link.

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +internal sealed interface PatchMappingGroup {
i wonder if we can define a single structure which is a collection of patch mappings that should be uploaded together. in (possibly most) some cases, they should just be individual patch mappings, but in the case of cycles, they would be bundled together as a result of your SCC calculation.

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +typealias Graph = Map<Node, List<Node>>
think about this alternative definition: 

```
data class Node(private id: String, private out: List<Node>)
typealias Graph = List<Node>
```

and potentially this *may* simplify your code a bit. because you can define things like

```
data class SuperNode(val out: List<SuperNode>, val nodes: List<Nodes>)
data class Node(val id: String, val out: List<Node>, val superNode: SuperNode)
```

and another thing is that - if we use this, we might be able to do away with copying the strings.

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodeToInt = mutableMapOf<String, Int>()
add comments here.

2024-06-05 10:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    fun dfs(at: Int) {
add comment here

2024-06-06 10:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +internal sealed interface OrderedMapping {
Done

2024-06-06 10:54 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +internal class StronglyConnectedPatches(private val diGraph: Graph, private val nodesCount: Int) {
Done. Converted it into object and added docs to the class and public function.

2024-06-06 11:07 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +internal class StronglyConnectedPatches(private val diGraph: Graph, private val nodesCount: Int) {
Done. Removed the [nodeCount] param to remove the changes of wrong value being sent.

2024-06-06 11:07 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +      .sscOrdered { createTopologicalOrderedList(it) }
No need based on the recent refactoring.

2024-06-06 11:08 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +internal class StronglyConnectedPatches(private val diGraph: Graph, private val nodesCount: Int) {
Done. Added tests for various use cases with 1, 2 and multiple nodes.

2024-06-06 11:09 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +internal sealed interface PatchMappingGroup {
Done. PatchMappingGroup is now a simple data class.

2024-06-06 11:11 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +typealias Graph = Map<Node, List<Node>>
Tarjan computes the strongly connected components in topological order. So removed the code for various manipulations including generating super nodes.
I don't think we need this structure change now.

2024-06-06 11:12 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +  private fun transformGraphWithSSCtoGraphWithSuperNodes(
Obsolete code based on recent refactoring. Removed.

2024-06-06 11:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodeToInt = mutableMapOf<String, Int>()
Done

2024-06-06 11:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    fun dfs(at: Int) {
Done

2024-06-10 15:34 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> + * - Multiple values in [patchMappings] signifies the cyclic nature of the nodes among themselves.
can you add a bit about how they are used? - they are used to make sure patches that have to be uploaded in the same request are uploaded in the same request...

2024-06-10 15:41 UTC, jingtang10 approved these changes
thank you @aditya-07 great job!

2024-06-10 15:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +typealias Graph = Map<Node, List<Node>>
internal?

2024-06-10 15:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +typealias Graph = Map<Node, List<Node>>
add examples for nodes and graphs.

2024-06-11 09:30 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +typealias Graph = Map<Node, List<Node>>
Done

2024-06-11 09:31 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +typealias Graph = Map<Node, List<Node>>
Done

2024-06-11 10:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> + * - Multiple values in [patchMappings] signifies the cyclic nature of the nodes among themselves.
Done

2024-06-11 13:26 UTC, MJ1998 requested changes

2024-06-11 13:26 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val assignedLowValueForEachNode = mutableMapOf<Node, Int>()
nit
```suggestion
    val lowLinks = mutableMapOf<Node, Int>()
```

`lowLinks` is the terminology used in tarjan's algorithm

2024-06-11 13:26 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val currentLowValueForEachNode = mutableMapOf<Node, Int>()
nit: 
```suggestion
    val discoveryTimes = mutableMapOf<Node, Int>()
```

Just trying to use the same terminology in Tarjan's algorithm

2024-06-11 13:26 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodesCurrentlyInStack = mutableSetOf<Node>()
This not make the complexity O(nLogn).

If there is a way to map a String of format "<ResourceType>/<Id>" to an integer in O(1) we can reduce the complexity to O(n).

For the least you could use a HashSet ? With number of nodes in thousands the likelihood of collision is very low.
The complexity will almost always will be O(n)

2024-06-11 13:26 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +      PatchMappingGroup(it.mapNotNull { resourceIdToPatchMapping[it] })
Oh this step will anyway take O(nlogn) - See a comment below.
I guess we can associate each resourceTypeAndId to an Int and hence derive the `resourceIdToPatchMapping`
Then we can create an adjacencyList of Ints and the algorithm would run in O(n).
Finally do the reverse mapping.

2024-06-11 14:45 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +internal data class PatchMappingGroup(val patchMappings: List<PatchMapping>)
Also update kdoc to something like:-
```
/**
 * Represents a strongly connected component (SCC) within a directed graph of [PatchMapping] instances.
 *
 * A strongly connected component is a subgraph where every [PatchMapping] node is reachable from every
 * other node within the same subgraph. In the context of patch mappings, this signifies a group of patch
 * mappings that have cyclic dependencies among themselves.
 *
 * This class is used to group related [PatchMapping] instances together for processing, ensuring that
 * resources with dependencies are handled as a unit.
 */
 ```

2024-06-11 14:45 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodesCurrentlyInStack = mutableSetOf<Node>()
Resolving this as mutableSetOf() is a LinkedHashSet indeed.

2024-06-13 07:06 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchGenerator.kt
> +internal data class PatchMappingGroup(val patchMappings: List<PatchMapping>)
Done.

2024-06-13 07:06 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
>    suspend fun List<PatchMapping>.orderByReferences(
Done

2024-06-13 07:08 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +   *   [PatchMapping]s if the mappings are cyclic.
Done. I haven't added the link here, but at the `StronglyConnectedPatches.findSCCWithTarjan`.

2024-06-13 07:08 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val connectedComponents = mutableListOf<List<Node>>()
Done

2024-06-13 07:08 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +        }
Done

2024-06-13 07:08 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val assignedLowValueForEachNode = mutableMapOf<Node, Int>()
Done

2024-06-13 07:09 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val currentLowValueForEachNode = mutableMapOf<Node, Int>()
Done

2024-06-13 07:54 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodesCurrentlyInStack = mutableSetOf<Node>()
To keep separation of the actual algorithm and the generated graph, I think its fine if we keep `nodesCurrentlyInStack` and `resourceIdToPatchMapping` as two separate values in two separate places/ routines.

`visitedNodes` and `nodesCurrentlyInStack` are now boolean arrays.

2024-06-13 07:54 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt
> +      PatchMappingGroup(it.mapNotNull { resourceIdToPatchMapping[it] })
It should be O(n) as we are using a hashmap.

2024-06-13 08:22 UTC, MJ1998 approved these changes
LGTM only. This is a great PR!

2024-06-13 08:22 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodeCount = (diGraph.keys + diGraph.values.flatten().toSet()).size
Should'nt this be?
```suggestion
    val nodeCount = (diGraph.keys + diGraph.values.flatten()).toSet().size
```

Or actually the diGraph.keys will have all the keys already. Look at `createAdjacencyListForCreateReferences` where for each patchMapping we add a List<Node> which could also be empty.

2024-06-13 08:22 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodesCurrentlyInStack = mutableSetOf<Node>()
We can still create another mapping from resourceIdToPatchMapping where we map "resourceTypeAndId" to an Int.
The algorithm is still separate and will work on Node which is an alias of Int instead of String now.

2024-06-13 09:00 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodesCurrentlyInStack = mutableSetOf<Node>()
I am trying to avoid intermediary mappings and this makes code more readable.

2024-06-13 09:01 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodeCount = (diGraph.keys + diGraph.values.flatten().toSet()).size
`diGraph.keys` is already a set. Its just to make sure that if ever the code is called with a graph with just the edge added, it doesn't fail.

2024-06-13 10:12 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/patch/StronglyConnectedPatches.kt
> +    val nodesCurrentlyInStack = mutableSetOf<Node>()
Done

2024-06-13 11:27 UTC, merged