Avoid EditText#setText to mitigate TextWatcher racing condition
google/android-fhir pull request #2537
Opened 2024-05-08 09:29 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1914 

Cause of the issue: The EditText temporarily contains an extra character. The TextWatcher gets removed ([here](https://github.com/google/android-fhir/blob/63151b5f1fdb6c1ad843d1421ea354b84fb51378/datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/EditTextViewHolderFactory.kt#L104)) before it can process this extra character, leaving the saved text state (in QuestionnaireViewItem) inconsistent with the actual EditText content. This inconsistency triggers a UI update using EditText#setText ([here](https://github.com/google/android-fhir/blob/63151b5f1fdb6c1ad843d1421ea354b84fb51378/datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/EditTextStringViewHolderDelegate.kt#L68)), which unintentionally resets the cursor position to the beginning.

EditText#append moves the cursor to the last position.

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-05-08 10:45 UTC, MJ1998 commented
This, however, has a side effect (which existed earlier as well but was overlooked because of cursor resetting) of missing some characters when typing too fast.
Reason: EditText's extra character is skipped when using the above solution.

Solving this will require more effort. I can think of a solution which will involve detecting "user has stopped typing". Something like this - [stackoverflow](https://stackoverflow.com/a/52944488).

Let me know if you want to fix this as well. Will raise a separate issue for this.

Alternative: Use RxBindings or do some backpressure solutioning to handle all character inputs from user. But this will need a more complex handling - like "not updating the EditText until upstream processing (handleInput) is complete".

2024-05-08 12:50 UTC, pld commented
@jingtang10 what are your thoughts on this?

2024-05-08 14:02 UTC, MJ1998 commented
I made an attempt at solving the "side effect" as well. Seems good to me but Idk if this behaviour - "detect user has stopped typing" can have any other side effects. 

Only difficulty is to test this as racing conditions are always a pain to test.
How I tested it - Ran my finger over "QWERTY" tabs on keyboard back and forth really fast. Before the last commit I could see some missed characters. After the last commit, I didn't see any missed character in quite some attempts trying this test.

Can you try testing this PR ?
@pld

2024-05-08 14:54 UTC, AngelaKabari commented
Thanks for all your work on this @MJ1998. @FikriMilano will test the PR tomorrow and we'll get back to you.

2024-05-09 05:42 UTC, MJ1998 commented
Just FYI an elaboration on the how I am testing this:-
I slide my finger and keep it pressed over "QWERTY" keys back and forth. So the input I generate is "qwertytrewqwertytrewq...". 

You can observe some characters being missed before the last commit if you test like this. @FikriMilano 

In actual case the upstream function can take more time to finish (for example, resolving fhir query)  - which makes characters missing clearly visible.

2024-05-09 09:53 UTC, MJ1998 commented
Regarding your question on RxBinding, I think its a much bigger effort as we dont use simple TextView or EditText views, rather its a EditTextInputLayout which offers more features like validation, header views along with it. 

So moving from EditTextInputLayout to RxBinding views will be difficult. 
@FikriMilano

2024-05-09 16:07 UTC, AngelaKabari commented
@MJ1998 this fix you shared is working great. Thank you for prioritising this and getting it resolved so quickly!

2024-05-17 13:21 UTC, AngelaKabari commented
@MJ1998 upon further testing, the issue of the missing characters is significantly affecting the data entry.
https://github.com/google/android-fhir/assets/8417097/b9775530-db3a-4cc6-a9ae-352ccf68e2af

Can we please go back to the drawing board on this?

2024-05-17 14:55 UTC, MJ1998 commented
Is this issue happening on this PR?

2024-05-17 15:33 UTC, AngelaKabari commented
@MJ1998 yes it is.

2024-05-27 05:30 UTC, MJ1998 commented
Can you try increasing the DELAY TIME to 1 second or 2 second and see if this is happening ?
Not the best solution but I am trying to figure out what is causing the delay in the upstream function (that validates the input string and sends it to the QuestionnaireViewModel for updating the RecyclerView) if there is no dependent items also. 
To increase delay time search for this line: `textInputEditText.afterTextChangedDelayed(500)`

2024-05-31 11:50 UTC, MJ1998 commented
Can you try this solution in  @f-odhiambo device and confirm if it works ?
I am not sure because that if condition is what we are anyway doing in updateUI.

2024-06-03 05:14 UTC, MJ1998 commented
Context: User input is sent back to QuestionnaireViewModel for validation, updating dependent items and then building the RecyclerView list -> which then comes back to the EditViewHolderFactory. 
The problem is happening when user input speed exceeds the speed at which this loop finishes.
So here's what we are implementing: 
We will detect new user input and when loop comes back to EditViewHolderFactor we will cut off the loop to prevent updating UI when THERE IS new user input present!
@jingtang10 @FikriMilano

2024-06-11 14:27 UTC, pld commented
yay, awesome, thank you @MJ1998 🎉 !

2024-06-18 08:28 UTC, aditya-07 requested changes
The approach taken to fix the issue looks fine to me and the changes look good as well.
Just a comment to add Unit test to make sure that the code keeps working as expected.

2024-06-18 08:28 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/factories/EditTextViewHolderFactory.kt
> +    }
Can we add unit test for this. You should be able to use `view.requestFocus` and `view.clearFoucs` to simulate the use cases.

2024-06-19 10:37 UTC, jingtang10 approved these changes

2024-06-20 09:10 UTC, aditya-07 approved these changes
LGTM! Thanks @MJ1998 !

2024-06-20 09:10 UTC, merged