Return unique include and revInclude resources per search filter match.
google/android-fhir pull request #2544
Opened 2024-05-14 11:58 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2512 

**Description**
1. Return distinct included and revIncluded resource per searchIndex.
2. When user updates a resource, if the resource has an `meta.lastUpdated`, use that for index value.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 
**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-05-16 09:08 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +          lastUpdatedRemote = resource.meta.lastUpdated?.toInstant() ?: it.lastUpdatedRemote,
Is this something we missed in some previous PR? 
@santosh-pingle FYI.

2024-05-16 15:22 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +          lastUpdatedRemote = resource.meta.lastUpdated?.toInstant() ?: it.lastUpdatedRemote,
We didn't essentially miss it, never took to consideration that the application may change `resource.meta.lastUpdated` since it is a server assigned value.

2024-05-21 08:39 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +          lastUpdatedRemote = resource.meta.lastUpdated?.toInstant() ?: it.lastUpdatedRemote,
Since this is not relevant to the current PR can we do this in some other PR ? and raise an issue for it also ?

2024-05-21 08:46 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +          ?.distinctBy { Pair(it.searchIndex, it.resource.id) }
Should we rather add `SELECT DISTINCT..` to where the query is being created - `Search.getIncludedQuery` and `Search.getRevIncludedQuery` ?

2024-05-21 08:46 UTC, MJ1998 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    // Patient.GIVEN and Encounter.LOCATION_PERIOD should return single copies of the resources.
Can there be a case when duplicate records are returned when only include is used (ie, revInclude is not used) ?

2024-05-27 10:06 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> +          lastUpdatedRemote = resource.meta.lastUpdated?.toInstant() ?: it.lastUpdatedRemote,
This change is one of the ways to fix the [duplicate issue](https://github.com/google/android-fhir/issues/2512). That's why I have added it in this PR itself.

2024-05-27 10:12 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    // Patient.GIVEN and Encounter.LOCATION_PERIOD should return single copies of the resources.
The issue tests for both at the same time, but under the hood, search api treats include and revInclude as separate functions and their individual results don't interfere with each other. 
Nevertheless, I guess its a good idea to separate the tests out so that we can rely on the tests even when search api internal functionality changes in future.

2024-05-27 13:24 UTC, MJ1998 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    // Patient.GIVEN and Encounter.LOCATION_PERIOD should return single copies of the resources.
Tests look good now! thanks.

2024-05-27 13:28 UTC, MJ1998 approved these changes
LGTM. NIT comment.

2024-05-27 13:28 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> -          entity.lastUpdatedRemote?.let { instant ->
But lastUpdatedRemote can still be null right ?

2024-05-30 09:34 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
> -          entity.lastUpdatedRemote?.let { instant ->
Yes and it could be null only during the On Device create or update.

2024-05-31 13:09 UTC, jingtang10 requested changes

2024-05-31 13:09 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          SELECT DISTINCT rie.index_name, rie.resourceUuid, re.serializedResource
discussed with aditya - i'm worried about what it means to be sorting by a field that is repeated.... for example if you have a patient with two given names aaron and charlie, and another one with two given names barry and david, then what order should this query actually produce, if it's deterministic at all?

do we know that the ordering here is perserved somehow (i.e. we take the first value)?

2024-05-31 13:09 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    // Patient.GIVEN should return single copy of of the Patient resource.
can you explain a little bit more that the dupliatees of record are generated by the join sql statement for the sorting. and probably link to the issue as well.

2024-06-18 15:18 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          SELECT DISTINCT rie.index_name, rie.resourceUuid, re.serializedResource
I have added the comments in sort api to describe the nature of repeated fields. 

SQLite finds DISTINCT values first and then ORDERS them (based on explain query plan and my own tests).
So, what I have concluded is that the ordering is done on the first repeating value in each resource ( which translates to first entry in StringIndexEntity table for that resource for that particular index_name) .

2024-06-18 15:18 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    // Patient.GIVEN should return single copy of of the Patient resource.
Done

2024-06-19 11:03 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +     */
```suggestion
    /**
     * This tests that the search query does not return duplicated resources as a result of sorting by a field that has multiple index values. For example, searching a group of patients sorted by
     * Patient.GIVEN should return a single copy of each patient even if some of them might have mulitple given names indexed.
     *
     * Whilst sorting, the resource table and the relevant index table are joined, which could result in multiple rows for a single resource if there are multiple index values for the particular index used in the sorting criteria. This is prevented by adding the `DISTINCT` keyword in the generated SQL query.
     */
```

2024-06-19 11:04 UTC, jingtang10 approved these changes
pls add your findings using the query plan, and performance tests.

2024-06-26 07:31 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  @Test
done

2024-06-26 07:31 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +     */
Done

2024-07-10 10:23 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +     */
need updating again

2024-07-10 10:49 UTC, jingtang10 requested changes

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .contains(SearchResult(group, mapOf(Group.MEMBER.paramName to listOf(p2, p1)), null))
better to split

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt
> +   */
update

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt
> +   */
update

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private const val MAX_VALUE = "9223372036854775808"
add reference to sqlite doc

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        HAVING MIN(IFNULL(b.index_value,0)) >= -9223372036854775808
can you 1) add test cases where not having this would result in included/revincluded resource not showing up, and 2) add comments in the code to explain this behavior - i imagine where you use min / max values to fill null fields

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      HAVING ${if (order == Order.ASCENDING) "MIN($havingColumn) >= $MIN_VALUE" else "MAX($havingColumn) >= $MIN_VALUE"}
explain why using min max values here

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        HAVING MIN(IFNULL(b.index_value,0)) >= -9223372036854775808
can you explain why this comparison needs to happen inside `HAVING`? i can understand the use of `IFNULL` but cannot understand the use of `>= -9223372036854775808`

2024-07-10 10:49 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          HAVING MAX(IFNULL(b.index_from,0) + IFNULL(c.index_from,0)) >= -9223372036854775808
add a comment on why the + is needed

2024-07-24 07:49 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +     */
Done

2024-07-24 07:51 UTC, aditya-07 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .contains(SearchResult(group, mapOf(Group.MEMBER.paramName to listOf(p2, p1)), null))
Done. Have split all the new tests .

2024-07-24 07:52 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt
> +   */
Done

2024-07-24 07:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/BaseSearch.kt
> +   */
Done

2024-07-24 07:53 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private const val MAX_VALUE = "9223372036854775808"
Done.

2024-07-24 07:55 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        HAVING MIN(IFNULL(b.index_value,0)) >= -9223372036854775808
Extracted the code into a function and added notes about the values , null and comparison.

Added a test where result would not include a null value if `HAVING` clause comparison is not done.

2024-07-24 07:56 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        HAVING MIN(IFNULL(b.index_value,0)) >= -9223372036854775808
Done, added the reason in place where the query is generated.

2024-07-24 07:56 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +          HAVING MAX(IFNULL(b.index_from,0) + IFNULL(c.index_from,0)) >= -9223372036854775808
Done, added comment where query is generated.

2024-07-24 07:57 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      HAVING ${if (order == Order.ASCENDING) "MIN($havingColumn) >= $MIN_VALUE" else "MAX($havingColumn) >= $MIN_VALUE"}
Done

2024-07-24 09:59 UTC, jingtang10 approved these changes

2024-07-24 10:11 UTC, merged