Support Custom Search Parameter in x-fhir-query
google/android-fhir pull request #2555
Opened 2024-05-29 07:02 UTC by asad-zaman

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2554

**Description**
Add support to consider custom search parameters during `x-fhir-query` execution.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature)

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-05-30 05:15 UTC, MJ1998 requested changes
Thanks @asad-zaman for raising this bug. 

Instead of exposing FhirEngineConfiguration (which has lot of other things than just customSearchParameters) could you use`SearchParamDefinitionsProviderImpl` instance that is created in the `FhirServices` class ?

2024-05-30 10:20 UTC, asad-zaman commented
Hi @MJ1998,
I have made the changes. Now use `SearchParamDefinitionsProvider` instead of `FhirEngineConfiguration`. Thanks for the suggestion.

2024-05-31 05:10 UTC, MJ1998 approved these changes
LGTM.

2024-05-31 05:10 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  internal fun getSearchParamProvider() = fhirServices?.searchParamProvider
Nit: Place this function after `getOrCreateFhirService` to emphasize that calling this only makes sense once the `FhirServices` class has been created, ie, which is when `FhirEngine` instance has been asked for by the application.
Actually just add a small kdoc in lines of "this will return null unless FhirEngine instance is created"

2024-05-31 07:43 UTC, asad-zaman commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +  internal fun getSearchParamProvider() = fhirServices?.searchParamProvider
I have refactored this and added kdoc. Please check. Thanks :)

2024-06-03 13:51 UTC, asad-zaman commented
@MJ1998, Could you please check now?

2024-06-06 14:52 UTC, asad-zaman commented
Hi @jingtang10, If it is ok, then could you please initiate the merge? Thanks 😊

2024-06-13 11:50 UTC, asad-zaman commented
Hi @MJ1998,
I didn't see any Kokoro Build details. Isn't it finished yet? Also, I didn't see any label about kokoro run. May be I missed something. 
![Screenshot_20240613_174414_Chrome](https://github.com/google/android-fhir/assets/19770825/d42ce14c-d2c1-4018-9240-57529bea005d)

2024-06-20 18:19 UTC, asad-zaman commented
Hi @MJ1998, 
Any update?

2024-06-20 18:27 UTC, MJ1998 commented
The kokoro label can only be added by core team with permissions. 

Currently the kokoro seems to be running. Does it always run? Or does it fail? Can you tag me once the kokoro provides a status?

2024-06-21 06:36 UTC, asad-zaman commented
Hi @jingtang10,
Could you please start the Kokoro build. I didn't see any status about kokoro build. Thanks

2024-06-21 06:42 UTC, asad-zaman commented
> The kokoro label can only be added by core team with permissions.
> 
> Currently the kokoro seems to be running. Does it always run? Or does it fail? Can you tag me once the kokoro provides a status?

@MJ1998,
I didn't see any details about kokoro build. Even I don't know whether kokoro is already run or not. I didn't get any status about success or failure. In my last ticket, I got email when kokoro failed and successed. Hence it seems to me that kokoro isn't started yet.

2024-06-23 08:30 UTC, asad-zaman commented
Hi @MJ1998,
Here is the [Kokoro ](https://btx.cloud.google.com/invocations/52fcf854-07e0-4d37-a0e0-f890bba69130/targets/openhealthstack%2Fandroid-fhir%2Fgcp_ubuntu%2Fpresubmit;config=default/log) detail. In the device test, one case failed, which is unrelated to my changes. Could you please check and guide me so that I can resolve it. Thanks 

```
MediumPhone.arm-33-en_US-portrait com.google.android.fhir.datacapture.test.QuestionnaireUiEspressoTest#clearAllAnswers_shouldClearDraftAnswer 
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: expected to be empty
```

2024-06-24 15:06 UTC, MJ1998 commented
Hey how did you get the failed test case? These seem to pass for me locally and strangely the kokoro is never-ending
@asad-zaman

2024-06-24 17:39 UTC, asad-zaman commented
Hi @MJ1998, 
Thanks for your quick response. [Here](https://console.cloud.google.com/storage/browser/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/4593/20240621-003920/firebase/datacapture;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) is the detail of the kokoro run. Please check.

Go to the above link and navigate to the path according below screenshot and check the file named [test_result_1.xml](https://console.cloud.google.com/storage/browser/_details/android-fhir-build-artifacts/prod/openhealthstack/android-fhir/gcp_ubuntu/presubmit/4593/20240621-003920/firebase/datacapture/matrix_0/MediumPhone.arm-33-en_US-portrait-shard_7/test_result_1.xml?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))). 

<img width="823" alt="tmp_25a47711-9249-40a2-9758-e359d30c5007" src="https://github.com/google/android-fhir/assets/19770825/fa1ebe58-b9f6-4ddc-8374-267d3c07ef57">

FYI, In my local machine, the above mentioned test case also passed.

2024-06-25 07:34 UTC, merged

2024-06-26 05:54 UTC, MJ1998 commented
This is merged @asad-zaman. Thanks for the PR and fixing custom search parameter in x-fhir-query.