Use checkbox for show/hide error state
google/android-fhir pull request #2563
Opened 2024-06-04 20:53 UTC by chungwwei

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1635

**Description**
Remove the button that toggles show/hide error state 
Use checkbox for show/hide error state in modal bottom sheet

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Other

**Screenshots (if applicable)**
![Screenshot_20240604_162536](https://github.com/google/android-fhir/assets/39935368/8ea40b3f-519f-4d8c-8b16-1dba542cad85)

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-06-06 12:37 UTC, jingtang10 requested changes
thanks for this change @chungwwei

looking at https://m3.material.io/components/bottom-sheets/overview i don't think we want to keep the x button at the top left corner of the bottom sheet - it appears superfuluous. can you please removew? thanks!

also - can you screenrecord a short video to show this works?

2024-06-06 12:37 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ModalBottomSheetFragment.kt
> -            R.string.hide_error_state
should this string be deleted?

2024-06-06 12:37 UTC, jingtang10 commented on catalog/src/main/res/drawable/baseline_close_24.xml
remove this file if we're removing the x button.

2024-06-06 12:37 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_modal_bottom_sheet.xml
> +    />
remove

2024-06-06 12:37 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ModalBottomSheetFragment.kt
> +    closeButton.setOnClickListener { NavHostFragment.findNavController(this).navigateUp() }
remove

2024-06-06 15:15 UTC, chungwwei commented on catalog/src/main/java/com/google/android/fhir/catalog/ModalBottomSheetFragment.kt
> -            R.string.hide_error_state
From search, looks like that string is only used in the `ModalBottomSheetFragment.kt` file. It becomes unused after removal, deleting it.

2024-06-06 15:16 UTC, chungwwei commented
[short_demo.webm](https://github.com/google/android-fhir/assets/39935368/cc1975ef-2715-4754-b19a-21118ae4e420)

2024-06-07 12:33 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/ModalBottomSheetFragment.kt
> -            R.string.hide_error_state
great thanks

2024-06-07 12:35 UTC, jingtang10 approved these changes
Thanks very much for this! Great job!

2024-06-07 13:03 UTC, jingtang10 commented on catalog/src/main/res/layout/fragment_modal_bottom_sheet.xml
> +        style="@style/Questionnaire.CheckBoxStyle"
Here we're using style defined in the data capture library for the catalog app itself... I think this is really leaking things a bit since I consider the bottom sheet not to be part of the questionnaire but part of the catalog app which we use to showcase the data capture library which renders the questionniare...

having said that - this is such a small issue and i'm ok for this to be fixed in the future.

2024-06-07 21:25 UTC, merged