Balance SQLite expression tree for logical operators (AND/OR) to lower the depth
google/android-fhir pull request #2565
Opened 2024-06-08 23:46 UTC by LZRS

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2561 

**Description**
Recursively bifurcates the conditional params expressions to prevent occurences of SQLite expression tree exceeding depth of 1000, as suggested in this [comment](https://github.com/google/android-fhir/pull/2565#issuecomment-2243596001)

**Alternative(s) considered**
Chunking large expression list to limit 50 within parantheses to avoid crashing with `Expression tree is too large (maximum depth 1000)`, as described [here](https://stackoverflow.com/a/17032196)

**Type**
Enhancement Feature

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-06-14 13:46 UTC, pld commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    this.chunked(50) { conditionParams ->
@MJ1998 do have thoughts on what the chunk size should be?

2024-06-21 18:18 UTC, pld commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    const val CONDITION_PARAMS_CHUNK_SIZE = 50
another question on this value, don't we want this to be as high as possible? I'd think fewer chunks are easier to process, and fewer checks definitely means fewer iterations. Why not set this to the max of 1000 as a default?

2024-07-22 18:45 UTC, jingtang10 commented
judging purely by the error message, my hypothesis is that the expression tree depth is O(n) for nested OR operators because the expression tree is constructed naively by parsing the OR operators sequentially. For example, if you nest 7 or statements you'd get:

```
  o
 / \
x   o
   / \
  x   o
     / \
    x   o
       / \
      x   o
         / \
        x   o
           / \
          x   x
```

where each `o` stands for one of the 6 OR operators and the 7 `x`s are the 7 values. This has depth 7.

But what you really want is actually this:

```
        o
      /   \
    o       o
   / \     / \
  o   o   o   o
 / \ / \ / \ / \
 x x x x x x x x
```

where the tree is more "balanced" and this has depth 4.

If my hypothesis of what causes the problem is correct, instead of trying to break the OR statements into chunks (and having to come up with a value), all you actually have to do is keep the tree balanced by splitting the top level OR statment at the middle of the list of params.

Does this make sense?

2024-07-23 09:56 UTC, jingtang10 commented
there's no guarantee what i said is true @LZRS - i've done no testing or verification and depending on sqlite's implementation what i said could be complete garbage... so pls test and see if this is true :) (for example you could try to see if you'll hit the depth limit a bit later to bifurcate the tree instead of chunking the parameters)

2024-08-22 01:02 UTC, LZRS commented
> there's no guarantee what i said is true @LZRS - i've done no testing or verification and depending on sqlite's implementation what i said could be complete garbage... so pls test and see if this is true :) (for example you could try to see if you'll hit the depth limit a bit later to bifurcate the tree instead of chunking the parameters)

@jingtang10 I tested this out for 1000, 2000 and upto 5000 parameters, and it worked perfectly. I also went ahead a drafted an implementation in the PR

2024-09-10 09:53 UTC, jingtang10 requested changes

2024-09-10 09:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +      return map {
why use `map` if the size is <= 1 anyway? i think you can just do the lamba inside the `map` function directly since you know there's only one (or zero) item.

2024-09-10 09:53 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    return listOf(left, right)
can you just join left and right with the separator without going through all this? in line 89 you have guarantee that the list has 2 or more items. that means neither left nor right can have size 0.

2024-09-10 09:53 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun `search CarePlan filter with large list of patient reference`() {
i think you do want to also test base cases... for example an empty list, and a list with 1, 2, (maybe add a 3 just to check when the list is not an even number and power of 2), 4 and 8 items.

by that point we can be confident the algorithm works as intended.

we can have a huge one like this - but it's actually not as useful in my view.

2024-09-10 09:55 UTC, aditya-07 requested changes
Can we add a DatabaseImplTest with

2024-09-10 09:55 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun `search CarePlan filter with large list of patient reference`() {
We should add this test in DatabaseImplTest to make sure that it always compiles and runs on the actual database.

2024-09-11 10:43 UTC, LZRS commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun `search CarePlan filter with large list of patient reference`() {
The base case for 1 has been covered in other test cases in the class, I guess I could add for others

2024-09-11 10:44 UTC, LZRS commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  @Test
Not really sure if it's easily possible, but checking it out...

2024-09-11 13:58 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun `search CarePlan filter with large list of patient reference`() {
Well - I know that the base case for 1 is covered via other test cases. BUT it's much better to write unit tests for base cases than complex cases.

I would say that tests cases for 0, 1, 2, 3, 4 together is much better than a single test case for 10.

This is because you really want to isolate any cases and make sure tests are easy to debug, easy to fix. If the test case for 10 starts to fail, you'll spend a long time trying to debug. But if the test case fails for either of 1, 2, 3, or 4, you can almost immediately pin down the cause for failure.

2024-10-03 09:28 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  @Test
I'm not really sure that this is a requirement for our API. This is an implementation detail in the db and our APIs don't really promise to the app how many patients the appp can join... i think maybe we should improve our documentation here but i am ok with not having this as a test. just my opinion.

2024-10-08 10:39 UTC, jingtang10 requested changes

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val patients = (0..5001).map { Patient().apply { id = "task-patient-index-$it" } }
There are 5002 patients and 5001 tasks. Is this test case deliberately checking this? I feel like if you really want to test the filter clause, it's better to query tasks linked to patient 0-4999 so at least you're filtering out 1 patient to know that the filter clause works.

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val patientsSearchIdList =
you can also limit this list to 2000 or 3000.

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +        return "true" // In case empty, return true to match other conditions in the where clause
first of all, we should never get to this point i think.. something is wrong if we are here...

but let's say we are here, i think we should return "true" if the oeprator is and but "false" if the operator is or... for this to be a no-op.

this is because if the operator is or, and you return a true here, then the whole thing will evaluate to true... and that doesn't seem right to me.

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +        println(getQuery().args)
remove

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
> +    assertThat(result1.size).isEqualTo(1)
not sure this block is useful.

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
good test cases in this file that really test what is being done in this pr - thanks lazarus!

2024-10-08 10:39 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +        return "true" // In case empty, return true to match other conditions in the where clause
actually - can you change the code calling this function on line 61 in this file. so that when the list is empty, you don't call this function.

and then you can safely remove this case.

and then, you need to update the test case in searchtest.kt file on line 2807 to remove the `AND true`.

2024-10-15 08:50 UTC, LZRS commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val patientsSearchIdList =
> you can also limit this list to 2000 or 3000.

I couldn't set limit the test to either 3000 or 2000, ran to another sqlite error on android 
```
android.database.sqlite.SQLiteException: too many SQL variables (code 1)
```
It's related to https://issuetracker.google.com/issues/73634057

For now, I just used a limit of 990

2024-10-15 10:11 UTC, jingtang10 approved these changes

2024-10-15 10:11 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val patientsSearchIdList =
but 5000 worked? this is odd...

can you please do some more testing to see what's goign on here?

this is not blocking the pr though.

2024-10-15 10:16 UTC, jingtang10 requested changes

2024-10-15 10:16 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +        .apply { filter(Task.SUBJECT, *patientsSearchIdList.toTypedArray()) }
this filter is checking that tasks are referencing patients 0-990 (inclusive) so that's 991 patients.

but you only have tasks for patients 0-989 (990 in total).

so the filter criteria is not really being tests because the filter criteria is broader than what you have in the database.

if you want to test it, make the filter more strict. for example, create N patients, and in the filter list N-1 IDs. and check that you only get N-1 results.

2024-10-16 09:28 UTC, LZRS commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val patientsSearchIdList =
Initially the way they'd passed for the 5000, I had generated the bifurcated queries and ran them in separate sqlite db browser. That might be the difference

2024-10-29 10:53 UTC, jingtang10 approved these changes

2024-10-29 10:53 UTC, aditya-07 approved these changes

2024-10-31 10:23 UTC, merged