Check if previous/next page is hidden to show previous/next buttons
google/android-fhir pull request #2569
Opened 2024-06-12 14:57 UTC by LZRS

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2568 

**Description**
Change `getQuestionnairePages` to only return questionnaire pages from QuestionnaireItems that have extension 
```
        {
          "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://hl7.org/fhir/questionnaire-item-control",
                "code": "page",
                "display": "Page"
              }
            ]
          }
        }
```

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-06-13 06:38 UTC, MJ1998 requested changes
We need to include contiguous set of items not with page extension into another page.

"If there are items at the same level as a 'page' group that are listed before the 'page' group, they will be treated as a separate page"
Reference - https://build.fhir.org/ig/HL7/fhir-extensions//CodeSystem-questionnaire-item-control.html

So if the questionnaire looks like - 
{
  itemWithNoPageExtension1, 
  itemWithPageExtension1, // have nested items
  itemWithPageExtension2,
  itemWithNoPageExtension2,
  itemWithNoPageExtension3,
  itemWithNoPageExtension4,
  itemWithPageExtension3,
  }
  
The pages would look like following:-
{
  page1: {
  	itemWithNoPageExtension1,
  },
  page2: {
  	itemWithPageExtension1
  },
  page3: {
  	itemWithPageExtension2
  },
  page4: {
  	itemWithNoPageExtension2,
  	itemWithNoPageExtension3,
  	itemWithNoPageExtension4
  },
  page5: {
  	itemWithPageExtension3
  }
}

2024-06-13 06:38 UTC, MJ1998 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          pages!!.last { it.index < currentPageIndexFlow.value!! && it.enabled && !it.hidden }.index
How are these 2 different ?

2024-10-02 05:11 UTC, FikriMilano commented
@LZRS does this change handle the following use case?
```
if the first page is by default, hidden using an extension, while the user is in the second page, the previous button should be hidden
```

2024-10-02 07:03 UTC, LZRS commented
> @LZRS does this change handle the following use case?
> 
> ```
> if the first page is by default, hidden using an extension, while the user is in the second page, the previous button should be hidden
> ```

Yes, so far the changes in this PR handle that but the ongoing discussions were on whether it should be hidden since it's also treated as a 'page' or should we handle by through an exception

2024-10-02 07:17 UTC, FikriMilano commented
@LZRS 
I mean, what if the first page has the page extension? but the page item is hidden using an extension.

In the second page, which also has a page extension, the previous button needs to be hidden.

Can this change handle that?

2024-10-02 07:49 UTC, LZRS commented
> @LZRS I mean, what if the first page has the page extension? but the page item is hidden using an extension.
> 
> In the second page, which also has a page extension, the previous button needs to be hidden.
> 
> Can this change handle that?

Yeah, it handles that

2024-11-07 12:04 UTC, FikriMilano commented
Here's some updates about the issue in dealing with pages, by @MJ1998 
https://chat.fhir.org/#narrow/channel/179255-questionnaire/topic/Rendering.20of.20pages.20when.20page.20extension.20is.20absent.20in.20items/near/481103016

2024-11-28 07:53 UTC, FikriMilano commented
@MJ1998 @jingtang10 have you decided whether we should make the implementation more relaxed?

2024-12-19 10:03 UTC, LZRS commented
@FikriMilano @MJ1998 Reviewing the current existing implementation,  **Sibling** items to a page extension group are treated as page even though they may not be of type`group`. 
```
{
  page1: {
  	itemWithNoPageExtension1
  },
  page2: {
  	itemWithPageExtension2
  },
  page3: {
  	itemWithPageExtension3
  },
  page4: {
  	itemWithNoPageExtension4
},
page5: {
  	itemWithNoPageExtension5
},
page6: {
  	itemWithNoPageExtension6
  },
  page7: {
  	itemWithPageExtension7
  }
}
```
The [spec](https://build.fhir.org/ig/HL7/fhir-extensions//CodeSystem-questionnaire-item-control.html) has also been updated 

> If a group item has this itemControl value, then all sibling items SHALL also be of type group and also have an itemControl value of 'page', 'header', or 'footer'. Form fillers SHOULD raise an error if a Questionnaire fails to adhere to this requirement.

IMO, it feels the current implementation is already relaxed and wouldn't necessarily crash 

In the PR, I have just updated to check that the previous or next button is not hidden, to show the previous/next button

2024-12-20 07:09 UTC, MJ1998 approved these changes
LGTM. Approving with one small NIT.

2024-12-20 07:09 UTC, MJ1998 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +            linkId = "page4-noExtension"
NIT
```suggestion
            linkId = "page4-noExtension-hidden"
```

2024-12-20 15:46 UTC, merged