update readme according to review comments
google/android-fhir pull request #2580
Opened 2024-06-20 16:55 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-06-21 11:05 UTC, jingtang10 approved these changes
thanks jajoo! this is really great!

mostly some formatting nitpicks re capitalisation and punctuation.

2024-06-21 11:05 UTC, jingtang10 commented on docs/use/SDCL/Customize-how-a-Questionnaire-is-displayed.md
> +1. **Create a Layout for the Custom Component:**
```suggestion
1. Create a layout for the Custom Component
```

2024-06-21 11:05 UTC, jingtang10 commented on docs/use/SDCL/Customize-how-a-Questionnaire-is-displayed.md
> +   Design a layout file (XML) to define the visual structure and appearance of your custom widget.
```suggestion
   Design an XML layout file to define the visual structure and appearance of your custom widget.
```

2024-06-21 11:07 UTC, jingtang10 requested changes
jajoo making more changes. pls let me know when ready.

2024-06-24 04:22 UTC, MJ1998 commented on docs/use/SDCL/Customize-how-a-Questionnaire-is-displayed.md
> +2. **Create a `QuestionnaireItemViewHolderFactory` Class:**
Them in bold look better.

2024-06-24 04:22 UTC, MJ1998 commented on docs/use/SDCL/Customize-how-a-Questionnaire-is-displayed.md
> +4. **Create a `QuestionnaireItemViewHolderFactoryMatchersProviderFactory`:**
Them in bold look better.

2024-06-24 04:22 UTC, MJ1998 commented on docs/use/SDCL/Customize-how-a-Questionnaire-is-displayed.md
> +6. **Use the Custom Widget in Your Questionnaire Fragment:**
Them in bold look better.

2024-06-24 04:22 UTC, MJ1998 commented on docs/use/SDCL/Customize-how-a-Questionnaire-is-displayed.md
> +5. **Register the Factory in `DataCaptureConfig`:**
Them in bold look better.

2024-06-25 10:27 UTC, jingtang10 approved these changes

2024-06-25 10:28 UTC, merged