Small changes for more code readability
google/android-fhir pull request #2656
Opened 2024-08-14 12:51 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-08-19 10:08 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +        SELECT DISTINCT localChangeId
Yes and yes!

2024-08-19 11:04 UTC, jingtang10 requested changes
Thanks @MJ1998! The variable names are great! A small comment on the doc change.

2024-08-19 11:04 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +   * [LocalChange]s containing references to the oldResource.
i don't think the resource uuids should be listed in square brackets actually. But also the old sentence is actually clearer about the relationship. It's the UUIDs of resources whose local changes reference the old resource.

```suggestion
   * place. This method returns a list of resource UUIDs for all the
   *  resources whose [LocalChange]s reference to the oldResource
```

2024-08-21 13:42 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
> +   * [LocalChange]s containing references to the oldResource.
Have stuck to the same wordings but updated more of kdocs. PTAL.

2024-08-22 16:41 UTC, jingtang10 approved these changes
Thanks @MJ1998 this is great!

A small suggestion on the use of `@param` - but I'm happy for you to merge this PR based on your judegement after you read the guideline - either way.

2024-08-22 16:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/Database.kt
> +   * @param updatedResource The updated resource with the new ID.
this section discourages use of `@param` https://kotlinlang.org/docs/coding-conventions.html#documentation-comments

given this, can you change the first line of this doc to incorporate the parameters instead of using `@param`? Seems more concise.

same with the rest of this PR.

2024-08-26 09:41 UTC, merged