Add dialog extension
google/android-fhir pull request #2663
Opened 2024-08-26 04:26 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2662

**Description**
- Define dialog extension https://github.com/google/android-fhir/dialog
- Use dialog: if the item control is checkbox or radio button, and has dialog extension

FHIR Chat discussion about adding `dialog` control type to Jira:
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/dialog.20item.20control

**Alternative(s) considered**
N/A

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-08-27 09:37 UTC, jingtang10 requested changes
can you add a test case in `QuestionnaireEditAdapterTest.kt`?

2024-11-01 02:15 UTC, FikriMilano commented
As discussed, we should use dialog extension instead of adding a dialog item control type

2024-11-05 10:35 UTC, jingtang10 reviewed
can you pls add some documentation in the docs folder (this will be automatically published on our doc site)?

2024-11-05 10:35 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapterTest.kt
> +  fun getItemViewType_choiceItemType_itemControlExtensionWithRadioButton_andDialogExtension_shouldReturnDialogSelectViewHolderType() {
use backtick notation for test names:
```
fun `should do something`
```

2024-11-05 10:35 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapterTest.kt
> +  @Suppress("ktlint:standard:max-line-length")
you can remove this if you follow the next comment.

2024-11-05 10:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +  "https://github.com/google/android-fhir/dialog"
keep extension urls in the same "namespace". see the location widget extension.

```suggestion
  "https://github.com/google/android-fhir/StructureDefinition/dialog"
```

2024-11-12 03:45 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/extensions/MoreQuestionnaireItemComponents.kt
> +  "https://github.com/google/android-fhir/dialog"
done

2024-11-12 03:45 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapterTest.kt
> +  @Suppress("ktlint:standard:max-line-length")
done

2024-11-12 03:45 UTC, FikriMilano commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapterTest.kt
> +  fun getItemViewType_choiceItemType_itemControlExtensionWithRadioButton_andDialogExtension_shouldReturnDialogSelectViewHolderType() {
done

2024-11-12 09:46 UTC, jingtang10 approved these changes
thank you!

2024-11-12 09:46 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
> +      questionnaireItem.shouldUseDialog -> QuestionnaireViewHolderType.DIALOG_SELECT
so if the questionnaire item type is not choice or reference, this extension will be no-op.

do you need to add this to any documentation?

2024-11-13 01:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireEditAdapter.kt
> +      questionnaireItem.shouldUseDialog -> QuestionnaireViewHolderType.DIALOG_SELECT
added

2024-11-14 09:41 UTC, merged