Load resources with url and optional version
google/android-fhir pull request #2666
Opened 2024-08-27 16:42 UTC by jingtang10

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-08-27 17:38 UTC, MJ1998 requested changes
Adding version looks find but why is resourceType being removed from apis here?

2024-08-27 17:38 UTC, MJ1998 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +    url: String,
I think we need to have resourceType as parameter. Take a look at this issue: https://github.com/google/android-fhir/issues/2490

2024-08-28 13:08 UTC, santosh-pingle approved these changes
LGTM!

2024-08-28 13:43 UTC, jingtang10 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +    url: String,
canonical resources are universally identified using canonical urls: see https://hl7.org/fhir/resource.html#canonical and https://build.fhir.org/ig/HL7/crmi-ig/artifact-lifecycle.html#artifact-identity

we discussed this in great length with @brynrhodes (on android-fhir@google.com mailing list) and this is the conclusion we arrived at.

2024-08-28 13:49 UTC, MJ1998 commented on knowledge/src/main/java/com/google/android/fhir/knowledge/KnowledgeManager.kt
> +    url: String,
FYI @dubdabasoduba since you had raised the issue #2490

2024-08-28 14:02 UTC, MJ1998 approved these changes
LGTM

2024-08-28 14:02 UTC, merged