Implement Parallelized map and optimize Database search API
google/android-fhir pull request #2669
Opened 2024-09-07 10:43 UTC by ndegwamartin

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2668 

**Description**
Optimizes the DatabaseImpl search APIs FHIR Resource(serialized) to HAPI FHIR Structure mapping block by introducing a parallelized implementation that uses async couroutines within each mapping iteration.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Enhancement

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-09-10 09:58 UTC, jingtang10 reviewed
great work thanks @ndegwamartin!

2024-09-17 16:15 UTC, ndegwamartin commented
**Device:** Physical, Samsung Galaxy Active Tab 2
**Mode :** Benchmarking with Kotlin system Timing's `measureTimeMillis`
**Scope:** [Database search API method search](https://github.com/google/android-fhir/blob/6ad0a6751fea3e53d9e2be327ca205cca1112af8/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L226) 

**Optimization:** None

**Run 1**
| Resource Type | Total Records | Timetaken(seconds)| DB Query(seconds) |
| -------- | ------- | ----------------------------|-----------------|
| Group | ~1K | 8 | ~0.2|
| Task | ~17K | ~24 | ~1.8|
| Patient | ~11K | ~456 | ~1.3|

**Run 2**
| Resource Type | Total Records | Timetaken(seconds)| DB Query(seconds) |
| -------- | ------- | ----------------------------|-----------------|
| Group | ~1K | ~2 | ~0.1 |
| Task | ~17K | ~22| ~1.7|
| Patient | ~11K | ~472 | ~1.2|

----------------------------------------------------------------------------
 
**Optimization:** Using _async_ with parent context (usually `Dispatchers.IO`)

**Run 1**
| Resource Type | Total Records | Timetaken(seconds)| DB Query(seconds) |
| -------- | ------- | ----------------------------|-----------------|
| Group | ~1K | 4.8 | ~0.2 |
| Task | ~17K | ~24 | ~1.7 |
| Patient | ~11K | ~450 | ~1.3 |

**Run 2**
| Resource Type | Total Records | Timetaken(seconds)| DB Query(seconds) |
| -------- | ------- | ----------------------------|-----------------|
| Group | ~1K | ~2 | ~0.1 |
| Task | ~17K | ~24| ~1.7 |
| Patient | ~11K | ~455 | ~1.3|

----------------------------------------------------------------------------

**Optimization:** Using _async_ with `Dispatchers.Default` . 
(_Note - Threads safety of the FHIR JsonParser is achieved through creating a new instance for each loop_) 

**Run 1**
| Resource Type | Total Records | Timetaken(seconds)| DB Query(seconds) |
| -------- | ------- | ----------------------------|-----------------|
| Group | ~1K | ~5 | ~0.2 |
| Task | ~17K | ~5.4 | ~1.8 |
| Patient | ~11K | ~208 | ~1.4 |

**Run 2**
| Resource Type | Total Records | Timetaken(seconds)| DB Query(seconds) |
| -------- | ------- | ----------------------------|-----------------|
| Group | ~1K | ~0.5 | ~0.1 |
| Task | ~17K | ~5 | ~1.7 |
| Patient | ~11K | ~204 | ~1.3|

**Note** - The tests were carried out in a QA test environment. In the real world Patients would be more than Groups (i.e. Patients = ~10 x No. of Groups ) and Tasks would be even more than Patients (i.e Tasks = ~30 x No. of Patients)

2024-09-17 16:24 UTC, ndegwamartin commented
**Full specs of the device:**
- Samsung Galaxy Tab Active2
- Android 9 (28)
- 3GB Memory

2024-09-19 09:38 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +suspend fun <A, B> Iterable<A>.pmap(f: suspend (A) -> B): List<B> = coroutineScope {
can you rename pmap to something which recommends to pass functions doing CPU intensive work.
May be "pmapCPU" ?

2024-09-19 09:40 UTC, ndegwamartin commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +suspend fun <A, B> Iterable<A>.pmap(f: suspend (A) -> B): List<B> = coroutineScope {
Yeah makes total sense because of the Dispatcher constraint

2024-09-19 09:46 UTC, ndegwamartin commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +suspend fun <A, B> Iterable<A>.pmap(f: suspend (A) -> B): List<B> = coroutineScope {
I had restricted it for use in the DB search API class but with the rename I could potentially move it out to the generic Utils class for reuse elsewhere.

2024-09-23 01:00 UTC, FikriMilano approved these changes
Looks good!

2024-09-27 07:11 UTC, MJ1998 requested changes
What happens when you don't parallelize the parsing but just run the parsing in the Default Dispatcher ?

A new function:-
```
fun IParser.parseResourceInCPU(resourceString: String) = 
    withContext(Dispatchers.Default) { parseResource(resourceString) }
```

and replace all parseResource with this function. 

I am surprised that parallelizing (second optimization) did not improve the search api performance. If parallelizing is not improving then do we really need it ?

2024-09-30 12:48 UTC, ndegwamartin commented
**Device:** Physical, Samsung Galaxy Active Tab 2
**Mode :** Benchmarking with Kotlin system Timing's `measureTimeMillis`
**Scope:** [Database search API method search - (Deserialization/mapping)](https://github.com/google/android-fhir/blob/6ad0a6751fea3e53d9e2be327ca205cca1112af8/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L226) 

**Optimization:** Using IParser.parseResourceInCPU() with context (usually `Dispatchers.Default`)

**Run 1**
| Resource Type | Total Records | Timetaken(seconds)|
| -------- | ------- | ----------------------------|
| Group | ~1K | ~5 |
| Task | ~17K | ~29 |
| Patient | ~11K | ~457|

**Run 2**
| Resource Type | Total Records | Timetaken(seconds)|
| -------- | ------- | ----------------------------|
| Group | ~1K | ~2 |
| Task | ~17K | ~28 |
| Patient | ~11K | ~461 |


cc @MJ1998

2024-09-30 12:49 UTC, ndegwamartin commented
**Device:** Physical, Samsung Galaxy Active Tab 2
**Mode :** Benchmarking with Kotlin system Timing's `measureTimeMillis`
**Scope:** [Database search API method search - (Deserialization/mapping)](https://github.com/google/android-fhir/blob/6ad0a6751fea3e53d9e2be327ca205cca1112af8/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L226) 

**Optimization:** Using _IParser.parseResourceInCPU()_ with context `Dispatchers.Default`

**Run 1**
| Resource Type | Total Records | Timetaken(seconds)|
| -------- | ------- | ----------------------------|
| Group | ~1K | ~5 |
| Task | ~17K | ~29 |
| Patient | ~11K | ~457|

**Run 2**
| Resource Type | Total Records | Timetaken(seconds)|
| -------- | ------- | ----------------------------|
| Group | ~1K | ~2 |
| Task | ~17K | ~28 |
| Patient | ~11K | ~461 |


cc @MJ1998

2024-09-30 12:55 UTC, MJ1998 commented
So its only when we do both - parallelize and use Default dispatcher - we see performance improvement, correct ?
@ndegwamartin

2024-09-30 12:55 UTC, ndegwamartin commented
> So its only when we do both - parallelize and use Default dispatcher - we see performance improvement, correct ? @ndegwamartin

Correct.

2024-10-01 06:54 UTC, MJ1998 commented
Okay so I think using Dispatchers.IO for CPU-intensive tasks might be less efficient due to thread type mismatch.

2024-10-01 09:57 UTC, ellykits commented on engine/src/main/java/com/google/android/fhir/Util.kt
> +suspend fun <A, B> Iterable<A>.pmapCPU(f: suspend (A) -> B): List<B> = coroutineScope {
Can we consider renaming this to `pmap` and providing the `Dispatcher` as a function parameter? default to `Dispatchers.Default`

2024-10-01 10:05 UTC, jingtang10 approved these changes
thanks @ndegwamartin for all the work! great results!

2024-10-01 12:11 UTC, ndegwamartin commented on engine/src/main/java/com/google/android/fhir/Util.kt
> +suspend fun <A, B> Iterable<A>.pmapCPU(f: suspend (A) -> B): List<B> = coroutineScope {
I think instead of having a default we should have the user to explicitly specify the _Dispatcher_ so that they are forced to align it with their exact use case. Refactoring as such.

2024-10-01 14:33 UTC, jingtang10 approved these changes

2024-10-01 14:33 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertTrue(timeTaken < 2000)
don't do this. is there a non flakey way to test parallelism? if not i'm happy for you to not include a test.

2024-10-01 15:18 UTC, ndegwamartin commented on engine/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertTrue(timeTaken < 2000)
I'm okay with removing it, however unless the system it runs on is actually unable to multithread then it would never fail?

2024-10-03 14:21 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertTrue(timeTaken < 2000)
please let me know once this is resolved.

2024-10-05 17:45 UTC, ndegwamartin commented on engine/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertTrue(timeTaken < 2000)
Done!

2024-10-07 06:45 UTC, MJ1998 approved these changes
LGTM.

2024-10-07 06:46 UTC, merged