Configuration changes to accept update payload type
google/android-fhir pull request #2687
Opened 2024-10-07 06:53 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2686 

**Description**
Clear and concise code change description.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-10-08 10:48 UTC, jingtang10 approved these changes

2024-10-08 10:48 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
can we just remove some of the strategies that we are not going to implement - especially given that we're using this approach where the verbs are being passed to the strategy.

2024-10-09 04:54 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
Would they be - SingleChange and SingleResource ones ?
Because we could encounter cycles and hence syncing in Bundle is the only choice. 
This would mean removing SingleResourcePost @santosh-pingle completed recently.

2024-10-09 05:20 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
Following would be the valid strategies (assuming bundle is the only way and we are introducing PUT for updates):-

1. AllChangesSquashedPutForCreatePatchForUpdate
2. AllChangesSquashedPutForCreateAndUpdate
3. AllChangesSquashedPostForCreateAndPatchForUpdate
4. AllChangesSquashedPostForCreateAndPutForUpdate
5. AllChangesPutForCreatePatchForUpdate
6. AllChangesPutForCreateAndUpdate
7. AllChangesPostForCreateAndPatchForUpdate
8. AllChangesPostForCreateAndPutForUpdate

And like @aditya-07 said, 
Lets provide a generic data class (UploadStrategy) with 3 variables (each having 2 possibilities) :-
1. squash: [True, False]
2. methodForCreate: [PUT, POST]
3. methodForUpdate: [PATCH, PUT]

This makes it 8 options. 
And additionally we should add bundleSize to this class as bundles are the only way to go.

Is this what you meant, @aditya-07  ?

2024-10-09 06:49 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
Yes, but we would want to know if the upload should be individual or Bundle.
In that case, we could add an additional param or have two distinct `UploadStrategy` one for each packaging style e.g. `IndividualUploadStrategy` and `BundleUploadStrategy` that may take appropriate params.

2024-10-10 06:13 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
From discussion with Aditya offline, we came up with the current solution of having a factory to create UploadStrategy objects. 
Also, we still need to support uploading by single resource or single change as some servers might not support bundle uploading (they would probably turn off referential integrity when syncing single changes or single resources).

2024-10-15 08:25 UTC, aditya-07 requested changes

2024-10-15 10:25 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/data/DemoFhirSyncWorker.kt
> +    UploadStrategy.forBundleRequest(HttpUploadMethod.PUT, HttpUploadMethod.PATCH, true, 500)
use named function params here - hard to understand what these are otherwise.

2024-10-15 10:25 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +        UploadStrategy.forBundleRequest(HttpUploadMethod.PUT, HttpUploadMethod.PATCH, true, 500),
same here

2024-10-15 16:17 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +open class UploadStrategy
Done

2024-10-15 16:17 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      methodForUpdate: HttpUploadMethod,
done.

2024-10-15 16:18 UTC, MJ1998 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +        UploadStrategy.forBundleRequest(HttpUploadMethod.PUT, HttpUploadMethod.PATCH, true, 500),
done.

2024-10-16 05:17 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      methodForUpdate: HttpUploadMethod,
Done.

2024-10-17 06:57 UTC, aditya-07 approved these changes
Nits, otherwise LGTM!

2024-10-17 06:57 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
Since PUT is not supported, is this required.

2024-10-17 06:57 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
Move this to first incase you wanna keep the following block for future.
 ``` 
require(methodForUpdate != HttpUpdateMethod.PUT || squash) {
        "Http method PUT not supported for UPDATE with squash set as false."
      }
```

2024-10-17 07:07 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
When we implement PUT for update I'll simply remove this if block in both the request types. 
The require statements will still be valid, correct ?

2024-10-17 08:03 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
Correct. For now, I would like devs to get `NotImplementedError` first if they use PUT rather than the  `IllegalArgumentException` by `require`.

2024-10-17 08:39 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
Makes sense!

2024-10-17 08:40 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
done.

2024-10-17 08:42 UTC, MJ1998 commented on engine/src/main/java/com/google/android/fhir/sync/upload/UploadStrategy.kt
> +      }
Still kept in code. Just reordered the error checking for dev convenience. Also its ok to keep it. When implementing PUT for updates we can remove the other if check and this would still hold true.

2024-10-17 09:49 UTC, merged