Manual sync as separate screen.
google/android-fhir pull request #2691
Opened 2024-10-08 06:29 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-10-09 10:18 UTC, santosh-pingle commented
Uploading Screen Recording 2024-10-09 at 3.19.27 PM.mov…

2024-10-09 12:51 UTC, jingtang10 requested changes
If there's nothing else in the activity view model, can we refactor and rename it to sync fragment view model?

Thanks @santosh-pingle!

2024-10-09 12:51 UTC, jingtang10 commented on demo/src/main/res/values/strings.xml
> +  <string name="manual_sync">Manual Sync</string>
```suggestion
  <string name="manual_sync">Sync</string>
```

2024-10-09 12:51 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/ManualSyncFragment.kt
rename this file to `SyncFragment.kt`

2024-10-09 12:51 UTC, jingtang10 commented on demo/src/main/res/drawable/sync_24dp.xml
this icon looks smaller than the other three on the landing page of the demo app - can you make this a bit bigger (and possibly bolder just to be consistent)?

2024-10-10 10:13 UTC, santosh-pingle commented on demo/src/main/res/values/strings.xml
> +  <string name="manual_sync">Manual Sync</string>
done.

2024-10-10 10:13 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/ManualSyncFragment.kt
done.

2024-10-10 10:13 UTC, santosh-pingle commented on demo/src/main/res/drawable/sync_24dp.xml
done.

2024-10-11 11:57 UTC, jingtang10 approved these changes
Thanks @santosh-pingle

2024-10-11 11:57 UTC, merged