Periodic sync separate screen.
google/android-fhir pull request #2699
Opened 2024-10-14 07:29 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #

**Description**

- Periodic sync as separate screen.
- 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 
**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-10-14 12:09 UTC, santosh-pingle commented
https://github.com/user-attachments/assets/268e8f07-52f1-42ee-ab35-bb47c03c338b

2024-10-16 12:59 UTC, jingtang10 requested changes
thanks @santosh-pingle!

a few things:

1. in the same pr we can remove sync from patient list and search screen
2. fix the failed sync in the video - is it a transient problem in your testing, or is there something wrong with the sync?
3. i think a progress bar would probably be really useful in the sync screens.

i love the simplicity of the screen - it really is a much clearer demo.

2024-10-16 12:59 UTC, jingtang10 commented on demo/src/main/res/values/strings.xml
> +  <string name="periodic_sync">Periodic Sync</string>
```suggestion
  <string name="periodic_sync">Periodic sync</string>
```

and rename `Sync` on line 70 to `One-time sync` to contrast this.

2024-10-16 12:59 UTC, jingtang10 commented on demo/src/main/res/layout/fragment_home.xml
in the screenshot, the text in different items are not aligned - there's an indentation possibly caused by the size of the icon - pls adjust.

2024-10-16 12:59 UTC, jingtang10 commented on demo/src/main/java/com/google/android/fhir/demo/PeriodicSyncFragment.kt
> +  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
i think the last sync statuses can be shown from the begining.

2024-10-17 07:11 UTC, santosh-pingle commented on demo/src/main/res/values/strings.xml
> +  <string name="periodic_sync">Periodic Sync</string>
done.

2024-10-17 07:11 UTC, santosh-pingle commented on demo/src/main/res/layout/fragment_home.xml
done.

2024-10-18 11:59 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/PeriodicSyncFragment.kt
> +  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Done. Except when the sync is happening for the first time, in which case there won't be a last sync state.

2024-10-18 12:55 UTC, santosh-pingle commented
https://github.com/user-attachments/assets/f8eeaca0-24ba-42d9-8740-b6ac8cabc538

2024-10-24 05:06 UTC, santosh-pingle commented on demo/src/main/java/com/google/android/fhir/demo/PeriodicSyncViewModel.kt
> +  val progressFlow: StateFlow<Int?> = _progressFlow
done.

2024-10-24 06:52 UTC, santosh-pingle commented
https://github.com/user-attachments/assets/03767c6a-39d5-4e17-86c7-ac8bcd42155f

2024-10-28 11:57 UTC, jingtang10 approved these changes
thanks santosh!

2024-10-30 08:17 UTC, merged