Upload strategy doc
google/android-fhir pull request #2703
Opened 2024-10-17 10:06 UTC by MJ1998

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Partially Fixes #2686 

**Description**
Clear and concise code change description.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-10-29 10:56 UTC, jingtang10 requested changes
why are there test changes in this pr? do you need to sync to the latest code?

2024-10-29 10:56 UTC, jingtang10 commented on docs/use/FEL/Sync-data-with-FHIR-server.md
> +* **`getUploadStrategy()`**: This defines how local changes are uploaded to the FHIR server. You can provide either `UploadStrategy.forBundleRequest` or `UploadStrategy.forIndividualRequest`.
can you explain the 4 params for bundle and individual requests?

2024-11-12 08:53 UTC, ellykits commented
> why are there test changes in this pr? do you need to sync to the latest code?

This is a code refactor PR hence the changes. The title is confusing.

2024-11-12 08:53 UTC, ellykits reviewed
LGTM :+1:

2024-11-12 09:52 UTC, jingtang10 commented
@MJ1998 can you pls sync this pr so that the code change is no longer included in the pr.

and pls address the comment in the readme.md file.

thx!

2025-01-29 13:56 UTC, closed without merging