Demo app for activity flow
google/android-fhir pull request #2711
Opened 2024-11-05 08:17 UTC by aditya-07

Fixes #2700 

**Description**

1. Demo app to show case activity flow api.
2. Landing page has a Patient card, a carousel of cards (phase card) related to each phase of activity flow and an overflow menu to select a particular activity to run.
3. Each phase card has a start button to activate the phase . The start button is enable only for the phase that is logically the next phase in the activity flow cycle.
4. On pressing the start button, the request/event for the particular phase are generated either from the CarePlan (Proposal Phase) or the previous phase requests (Plan/Order/Perform phases).
5. All the requests and persisted in the engine.
6. If you want to run the same flow again, click restart flow, which removes all of the resources related to the selected activity flow from the engine and moves the flow back to start proposal phase. 

**Alternative(s) considered**
NO

**Type**
Choose one: Feature

**Screenshots (if applicable)**

https://github.com/user-attachments/assets/83dc1f87-ccc5-468a-9c27-dc867efa8b30

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-11-06 11:27 UTC, jingtang10 requested changes

2024-11-06 11:27 UTC, jingtang10 commented on gradle/libs.versions.toml
> +material = "1.12.0"
remove this from the `Dependencies.kt` file to unify the dependency.

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/build.gradle.kts
> +    minSdk = 26
some of these values are defined in `Release.kt` and `Sdk.kt` files in the `buildsrc` dir.

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/build.gradle.kts
> +dependencies {
order dependencies by block: implementation, testImplementation etc. please check bulid files in other moules - we also order everything lexicographically.

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/androidTest/java/com/google/android/fhir/workflow/demo/ExampleInstrumentedTest.kt
remove this file if it's not needed?

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/test/java/com/google/android/fhir/workflow/demo/ExampleUnitTest.kt
remove.

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/assets/ad/DailyAppleActivity.json
can you create a `README.md` in the new module to explain where these resource files come from.

just so that it's easy for us to keep things up to date in the future.

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/assets/cql/DailyAppleLogic.cql
> +library DailyAppleLogic version '1.0.0'
tell @brynrhodes about this addition pls

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/helper/ResourceLoader.kt
> +class ResourceLoader(
can you use knowledge manager for this?

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/ActivityHandler.kt
> +    //    ActivityFlow returns a copy of the resource it has, so after updating the returned
```suggestion
    // ActivityFlow returns a copy of the resource it has, so after updating the returned
```

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/ActivityHandler.kt
> +    currentPhase.update(currentRequest)
optiona: a bit more clear?:
```
currentPhase.update(
  currentPhase.get().apply{
    ...
  }
)
```

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +      //    generateData(it, ::handleOnClick)
clean up

2024-11-06 11:27 UTC, jingtang10 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +          createProposalPhase2()
clean up the names

2024-11-11 10:11 UTC, aditya-07 commented on gradle/libs.versions.toml
> +material = "1.12.0"
Done

2024-11-11 10:11 UTC, aditya-07 commented on workflow_demo/build.gradle.kts
> +    minSdk = 26
Done

2024-11-11 10:12 UTC, aditya-07 commented on workflow_demo/build.gradle.kts
> +dependencies {
Done

2024-11-11 10:12 UTC, aditya-07 commented on workflow_demo/src/androidTest/java/com/google/android/fhir/workflow/demo/ExampleInstrumentedTest.kt
Done

2024-11-11 10:12 UTC, aditya-07 commented on workflow_demo/src/test/java/com/google/android/fhir/workflow/demo/ExampleUnitTest.kt
Done

2024-11-11 10:15 UTC, aditya-07 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/helper/ResourceLoader.kt
> +class ResourceLoader(
There is no way to get File reference for a assets file. So this class reads the file from assets as an input stream, creates a file in the local directory and then calls the `KnowledgeManager.index` .

2024-11-11 10:15 UTC, aditya-07 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/ActivityHandler.kt
> +    //    ActivityFlow returns a copy of the resource it has, so after updating the returned
Done

2024-11-11 10:21 UTC, aditya-07 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/ActivityHandler.kt
> +    currentPhase.update(currentRequest)
Done

2024-11-11 10:21 UTC, aditya-07 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +          createProposalPhase2()
Done

2024-11-12 10:16 UTC, jingtang10 reviewed
can you pls move the setup of knowledge resources using knowledge manager out of the proposal stage - so that it's part of initialisation.

2024-11-15 19:15 UTC, aditya-07 commented on workflow_demo/src/main/assets/ad/DailyAppleActivity.json
Done

2024-11-15 19:15 UTC, aditya-07 commented
> can you pls move the setup of knowledge resources using knowledge manager out of the proposal stage - so that it's part of initialisation.

Done

2024-11-19 09:25 UTC, jingtang10 commented on workflow_demo/src/main/assets/pd/Bundle-getrecommendations-data.json
remove

2024-11-19 09:25 UTC, jingtang10 commented on workflow_demo/src/main/assets/pd/GetRecommendations.json
remove

2024-11-19 09:38 UTC, nsabale7 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +        filter(MedicationRequest.SUBJECT, { value = "Patient/active_apple_guy" })
```suggestion
        filter(MedicationRequest.SUBJECT, { value = "${ResourceType.Patient.name}/active_apple_guy" })
```

2024-11-19 09:38 UTC, jingtang10 approved these changes
pls also add a simple page in the doc site for this new demo app

2024-11-19 09:38 UTC, nsabale7 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +        filter(MedicationRequest.SUBJECT, { value = "Patient/active_apple_guy" })
```suggestion
        filter(MedicationRequest.SUBJECT, { value = "${ResourceType.Patient.name}/active_apple_guy" })
```

2024-11-21 09:32 UTC, aditya-07 commented on workflow_demo/src/main/assets/pd/Bundle-getrecommendations-data.json
Done

2024-11-21 09:32 UTC, aditya-07 commented on workflow_demo/src/main/assets/pd/GetRecommendations.json
Done

2024-11-21 09:33 UTC, aditya-07 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +        filter(MedicationRequest.SUBJECT, { value = "Patient/active_apple_guy" })
I don't think it makes any difference.

2024-11-21 10:28 UTC, merged