Complete Question is shown now as TextView with Dropdown
google/android-fhir pull request #272
Opened 2021-02-22 13:49 UTC by MuhammadSalman-7214

2021-02-22 14:05 UTC, joiskash requested changes
Good work ! Just a few comments and please fix the Unit tests too.

2021-02-22 14:05 UTC, joiskash commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
> +        android:id="@+id/dropdown_menu"
Change this to dropdown_question_title  or something similar.

2021-02-22 15:20 UTC, jingtang10 commented
Thanks @MuhammadSalman-7214. Please address @joiskash 's comment and I will approve.

Additionallly, I think you'll need to fix this for the edit text layout as well: https://github.com/google/android-fhir/blob/master/datacapture/src/main/res/layout/questionnaire_item_edit_text_view.xml

Can be done in a follow-up PR.

2021-02-22 17:18 UTC, MuhammadSalman-7214 commented
sure, will complete @joiskash comments and then push the PR

2021-02-22 19:15 UTC, jingtang10 commented
> sure, will complete @joiskash comments and then push the PR

thanks! please let the reviewers know once you're done. also just a note, you won't be able to merge the PR until it is 1) approved by one the code owners and 2) all checks are passing.

2021-02-23 06:03 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +            private lateinit var textInputLayout: TextView
Done and Unit tests done too

2021-02-23 06:03 UTC, MuhammadSalman-7214 commented on datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
> +        android:id="@+id/dropdown_menu"
Done

2021-02-23 06:05 UTC, MuhammadSalman-7214 commented
Changes done @jingtang10 and @joiskash. Both of you can review the changes.

2021-02-23 09:44 UTC, jingtang10 requested changes

2021-02-23 09:44 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +                .text
same line

2021-02-23 09:44 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +            InstrumentationRegistry.getInstrumentation().targetContext,
thanks for fixing this -- can you do this for other files too?

2021-02-23 09:45 UTC, jingtang10 commented
Thanks - just a couple of nits

2021-02-23 10:00 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +                .text
okay

2021-02-23 10:00 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +            InstrumentationRegistry.getInstrumentation().targetContext,
okay

2021-02-23 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +                .text
Done

2021-02-23 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +            InstrumentationRegistry.getInstrumentation().targetContext,
Done

2021-02-23 11:01 UTC, MuhammadSalman-7214 commented
@jingtang10 both nits done

2021-02-23 18:05 UTC, jingtang10 approved these changes
Thanks @MuhammadSalman-7214!

🚀

2021-02-24 07:01 UTC, MuhammadSalman-7214 commented
your welcome @jingtang10 :-)

2021-02-24 11:32 UTC, merged