Workflow api upgrade
google/android-fhir pull request #2744
Opened 2024-11-28 07:48 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2736 

**Description**
1. Added a new factory to get all activity flows for a Patient.
2. Opened Request's Intent for app devs to access it.
3. Added a new api to get previous phases of an ActivityFlow.
4. Refactored demo app to use above api.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**

- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-12-20 11:42 UTC, jingtang10 requested changes
Thanks Aditya!

add some test.

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/phase/Phase.kt
> +class ReadOnlyRequestPhase<R : CPGRequestResource<*>>(private val cpgRequestResource: R) {
should phase implement read only phrase?

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/phase/Phase.kt
> +  fun getRequestResource() = cpgRequestResource
can these just be in the base phase class?

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +  fun getPreviousPhase(): PreviousPhaseIterator<R> {
do you think it's better or worse to just return a list?

i can see different arguments, it's only 3 phases at most, but maybe developers typically would want to display the previous phases together (maybe?) and if this is an interator, they actually have to repeated call till all phases are loaded anyway? so I'm not sure if this is better... 

but on the other hand, if they only wan to check a immediately preceding phase, this would be good... i don't really know how often that would be

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +          Communication::class.java,
add a comment here to say we need to add new resource types to this list

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +      val cache: MutableMap<String, CPGRequestResource<*>> =
rename this variable.

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +internal data class RequestChain(
private

2024-12-20 11:42 UTC, jingtang10 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/CPGEventResource.kt
>        return when (request) {
```suggestion
      return when (event) {
```

2024-12-30 14:22 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/phase/Phase.kt
> +class ReadOnlyRequestPhase<R : CPGRequestResource<*>>(private val cpgRequestResource: R) {
Marked `ReadOnlyRequestPhase` as  interface that is implemented by `BaseRequestPhase`

2024-12-30 14:23 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/phase/Phase.kt
> +  fun getRequestResource() = cpgRequestResource
Not needed after refactor.

2024-12-30 14:24 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +  fun getPreviousPhase(): PreviousPhaseIterator<R> {
Done. `getPreviousPhases` now returns a list of `ReadOnlyRequestPhase`

2024-12-30 14:24 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +      val cache: MutableMap<String, CPGRequestResource<*>> =
Done

2024-12-30 14:24 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +internal data class RequestChain(
Done

2024-12-30 14:24 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/resource/event/CPGEventResource.kt
>        return when (request) {
Done

2024-12-31 08:55 UTC, aditya-07 commented on workflow/src/main/java/com/google/android/fhir/workflow/activity/ActivityFlow.kt
> +          Communication::class.java,
done

2024-12-31 15:10 UTC, jingtang10 approved these changes
thanks aditya!

2024-12-31 15:10 UTC, jingtang10 commented on workflow_demo/src/main/java/com/google/android/fhir/workflow/demo/ui/main/MainViewModel.kt
> +          setPhase(it.getPhaseName(), it.getRequestResource().resource)
just `forEach` the list. no need to use `interator()` again

2024-12-31 17:44 UTC, merged