populate initial with initialExpression result collection
google/android-fhir pull request #2751
Opened 2024-12-06 06:31 UTC by parthfloyd

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2750 

**Description**
Updated `populateInitialValue()` function in `ResourceMapper.kt` of the SDC module to populate `questionnaireItem.initial` with values of collection instead of just the first value of the collection.

**Alternative(s) considered**
None | Looking forward to feedback

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**

- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://google.github.io/android-fhir/contrib/) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

2024-12-06 09:08 UTC, LZRS commented
To support multiple initially selected options from the dropdown, not quite sure populating the `Questionnaire.item.initial` would work. 
From this [`Questionnaire.item.initial` invariant](https://build.fhir.org/questionnaire-definitions.html#Questionnaire.item.initial)

> que-11	[Rule](https://build.fhir.org/conformance-rules.html#rule)	If one or more answerOption is present, initial cannot be present. Use answerOption.initialSelected instead	answerOption.empty() or initial.empty()

I would instead suggest using [`Questionnaire.item.answerOption.initialSelected`](https://build.fhir.org/questionnaire-definitions.html#Questionnaire.item.answerOption.initialSelected)

2024-12-07 02:59 UTC, parthfloyd commented
@LZRS Thank you so much for your feedback! 
I've pushed code & now it's conforming with the  [invariant ](https://build.fhir.org/questionnaire-definitions.html#Questionnaire.item.initial)rules. Please feel free if any changes or optimizations are required in the code.

Invariant:
> que-8	Rule	Initial values can't be specified for groups or display items

> que-13	Rule	Can only have multiple initial values for repeating items

> que-11	Rule	If one or more answerOption is present, initial cannot be present. Use answerOption.initialSelected instead

cc: @jingtang10 , @icrc-jofrancisco

2024-12-08 04:23 UTC, parthfloyd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +              evaluatedExpressionResult.any { answerOption.value.equalsDeep(it) }
For questionnaireItems with answerOptions, it is checking using equalsDeep to match answerOptions value with the result of initialExpression. 

Please let me know if this should be updated,
I had to update two test cases as the initialExpression result was not matching exactly with the answerOptions (system was missing in answerOption)

Reference:

> If the expression returns elements of type 'code', when the user selects one or more candidates, the code will be matched against the allowed Codings (from answerValueSet, answerOptions, or answerExpresssion).

- https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-initialExpression-definitions.html

> If two codings have the same system, version and code then they have the same meaning. If the version information is missing, or the system, version or the code elements differ, then how the codes are related can only be determined by consulting the definitions of the system(s) and any mappings available.

- https://hl7.org/fhir/R4/datatypes.html#codesystem

2024-12-11 13:28 UTC, LZRS approved these changes
LGTM

2024-12-12 08:23 UTC, parthfloyd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +              evaluatedExpressionResult.any { answerOption.value.equalsDeep(it) }
As discussed in developer call:
- added test for selecting answerOption with value `Coding` without `Coding.system` (in initialExpression result & answerOption).

To sum it up:
(In cases where result of initialExpression & type of answer is Coding) it will only select answerOption if the Coding matches exactly.

2025-01-07 10:03 UTC, jingtang10 requested changes

2025-01-07 10:03 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          // Handle initial values based on whether the questionnaire item repeats
so in this `else` block, the `anwerOption` is empty in the questionnaire item? why do we have to do anything in this case?

2025-01-07 10:03 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          // Handle initial values based on whether the questionnaire item repeats
pls also reflect these changes with new test cases.

2025-01-08 06:22 UTC, parthfloyd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          // Handle initial values based on whether the questionnaire item repeats
Thanks for the review @jingtang10 Best wishes for 2025!! I'll be adding test cases for it.

Explanation for code:
- So line 277-281 handles the case when questionnaireItem has an answerOption (then selects initialSelected) [que-11]
- line 284-291 handles the case when it doesn't have answerOption but it is a repeating item (only repeating item are allowed multiple initial values. [que-13]
- lastly 292-295 handles the default case when a regular questionnaireItem without answerOption has 1 initial value. 

Reference:

> Invariant:

> que-8 Rule Initial values can't be specified for groups or display items
> 
> que-13 Rule Can only have multiple initial values for repeating items
> 
> que-11 Rule If one or more answerOption is present, initial cannot be present. Use answerOption.initialSelected instead

2025-01-09 09:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        if (questionnaireItem.answerOption.isNotEmpty()) {
add a comment here to say for answer options, the initialSelected extension is used to highlight initial values.

but another thing to add here, is that if the initial expression evaluates to 1,2,3,4,5, but you only have 3 answer options 1,2,3... then 4 and 5 will be ignored here... we don't add them as additional values (nor does it make sense to do so). but it's just worth commenting that.

2025-01-09 10:08 UTC, parthfloyd commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        if (questionnaireItem.answerOption.isNotEmpty()) {
Thanks @jingtang10  I've added the comment & test-cases! Please feel free to let me know if any changes are required!

2025-01-13 15:48 UTC, jingtang10 reviewed
Very good test cases! Thanks @parthfloyd!

A few comments below

2025-01-13 15:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should fail with IllegalStateException when QuestionnaireItem of group or display item has a initial value`():
can you split this into 2 smaller test cases one for group one for display item?

In each questionnaire just include a single questionnaire item.

In general, for tests, it's much better to keep tests small and focused. So when a test fails from the test name you'll immediately figure out what's the problem, instead of having to debug.

2025-01-13 15:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +      assertThat((questionnaireResponse.item[0].answer[0].value as Coding).code)
extract questionnaireResponse.item[0].answer[0].value as a variable. or use kotlin's `with`:

```
with(questionnaireResponse.item[0].answer[0].value) {
  assert(this.code...)
  assert(this.system...)
}
```

2025-01-13 15:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +        }
what's the significance of having 2 observations in this test case? it seems that's not really being tested?

is the point you would collapse the 2 choices? would it be better to give the second observation a different coding and show that the first one is chosen?

2025-01-13 15:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +        .isEqualTo("correct2-display-val")
similarly extract local variables instead of repeating

2025-01-13 15:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should select a single initial answer for non repeating question without answerOption`() =
i think a missing test case here is that if there's no answer option but the expression evaluates to multiple values?

you should test in that case only the first value is used. right?

2025-01-21 04:13 UTC, parthfloyd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +        }
Thanks @jingtang10 This was a ctrl-c/v error! Thanks for finding it! Fixed accordingly!

2025-01-21 04:49 UTC, parthfloyd commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `populate() should select a single initial answer for non repeating question without answerOption`() =
Yes! added test case for it!

2025-01-28 14:47 UTC, MJ1998 approved these changes
LGTM

2025-01-28 14:47 UTC, MJ1998 commented
Please resolve the NIT and update your branch. Thanks for the PR @parthfloyd

2025-01-29 05:04 UTC, parthfloyd commented
@MJ1998 Thanks for the review! I've pushed changes accordingly. Looking forward to the merge & further development on populate!

2025-02-18 13:43 UTC, jingtang10 approved these changes

2025-02-18 13:43 UTC, merged