Slider Question functionality added
google/android-fhir pull request #287
Opened 2021-03-05 11:11 UTC by MuhammadSalman-7214

2021-03-05 13:05 UTC, jingtang10 commented
Thanks @MuhammadSalman-7214! Can you please always make sure to link to the issue this PR is addressing (and close the PR after this is merged).

@joiskash do you have bandwidth to take a look at this? Thanks!

2021-03-05 13:15 UTC, joiskash commented
Sure I'll have a look at this PR

2021-03-05 14:11 UTC, joiskash submitted a review, later dismissed
Add tests in the QuestionnaireItemAdapterTest and address the comments below :)

2021-03-05 14:11 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                val sliderValue = answer?.value?.integer?.value?.toString() ?: "0.0"
This cant be hardcoded.. imagine if the slider is from 5 to 10

2021-03-05 14:11 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
can you make this `questionnaireItemViewItem.singleAnswerOrNull =` for better readability

2021-03-08 05:42 UTC, MuhammadSalman-7214 commented on datacapture/src/main/res/layout/questionnaire_item_slider.xml
> +        android:valueFrom="0.0"
currently these values should remain hard coded as discussed with @jingtang10, and for their values, I am not able to find values.xml currently in the code

2021-03-08 05:43 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +        Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.slider_header).text)
sure

2021-03-08 05:46 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +    fun singleAnswerOrNull_singleAnswer_shouldReturnSingleAnswer() {
okay

2021-03-08 05:47 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                val sliderValue = answer?.value?.integer?.value?.toString() ?: "0.0"
for now, this is hard coded, will create a new issue for this as discussed with @jingtang10 to read values from extensions

2021-03-08 07:06 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
sorry, not understanding this. Can you explain this?

2021-03-08 12:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                val sliderValue = answer?.value?.integer?.value?.toString() ?: "0.0"
yes i think we'll have to do this in a follow up and especially considering the ongoing work in #224

2021-03-08 12:29 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +        Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.slider_header).text)
please comment again once done.

2021-03-08 12:29 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +    fun singleAnswerOrNull_singleAnswer_shouldReturnSingleAnswer() {
please comment again once done.

2021-03-08 12:31 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_slider.xml
> +        android:valueFrom="0.0"
don't hardcode these in the xml file. hardcode these in the kotlin files.

2021-03-08 12:36 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
instead of `questionnaireItemViewItem.singleAnswerOrNull = this` inside the apply block can you refactor such that it is something like this 

`questionnaireItemViewItem.singleAnswerOrNull =
                    QuestionnaireResponse.Item.Answer.newBuilder().apply {
                         value = ....
                        }`

You can refer to the other factories to find this pattern

2021-03-08 12:38 UTC, MuhammadSalman-7214 commented on datacapture/src/main/res/layout/questionnaire_item_slider.xml
> +        android:valueFrom="0.0"
done @jingtang10

2021-03-08 12:38 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +        Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.slider_header).text)
done

2021-03-08 12:39 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +    fun singleAnswerOrNull_singleAnswer_shouldReturnSingleAnswer() {
done @jingtang10

2021-03-08 12:40 UTC, MuhammadSalman-7214 commented
@jingtang10 and @joiskash made the requested changes, please check, thanks.

2021-03-08 12:44 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
@joiskash but this is already doing the same way as QuestionnaireResponse.Item.Answer.newBuilder().apply in the code
![Screenshot from 2021-03-08 17-44-05](https://user-images.githubusercontent.com/64642723/110323086-e6e01800-8035-11eb-8884-cf22c62548f9.png)

2021-03-08 13:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
Yes it is the same thing. Just suggesting to maintain uniformity in the code. Also why is the callback called inside apply?

2021-03-08 17:02 UTC, jingtang10 requested changes

2021-03-08 17:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
do not set `questionnaireItemViewItem.singleAnswerOrNull` inside the `apply`

also  keep `questionnaireItemViewItem.questionnaireResponseItemChangedCallback()` outside of `apply`

2021-03-09 08:26 UTC, MuhammadSalman-7214 commented
https://github.com/google/android-fhir/pull/287#discussion_r589589917
@jingtang10 to take callback out of apply is fine, but how can I take questionnaireItemViewItem.questionnaireResponseItemChangedCallback() outside of apply as it requires assigning within this block?

2021-03-09 09:54 UTC, jingtang10 commented
thanks @MuhammadSalman-7214. I see you have moved the callback call outside of the `apply` function.

Have you read this comment from @joiskash https://github.com/google/android-fhir/pull/287/files#r589390062 ?

so maybe this is where the confusion comes from, have you read about scope functions https://kotlinlang.org/docs/scope-functions.html?

you need to do the assignment outside of the apply function:

`something = something.newBuilder().apply{...}`

2021-03-09 10:58 UTC, MuhammadSalman-7214 commented
> thanks @MuhammadSalman-7214. I see you have moved the callback call outside of the `apply` function.
> 
> Have you read this comment from @joiskash https://github.com/google/android-fhir/pull/287/files#r589390062 ?
> 
> so maybe this is where the confusion comes from, have you read about scope functions https://kotlinlang.org/docs/scope-functions.html?
> 
> you need to do the assignment outside of the apply function:
> 
> `something = something.newBuilder().apply{...}`

@jingtang10 done. All other changes are done as well. Thanks.

2021-03-09 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +    fun singleAnswerOrNull_multipleAnswers_shouldReturnNull() {
Done

2021-03-09 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +    fun singleAnswerOrNull_singleAnswer_shouldReturnSingleAnswer() {
Done

2021-03-09 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
> +                            questionnaireItemViewItem.singleAnswerOrNull = this
Done

2021-03-09 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactoryInstrumentedTest.kt
> +    fun singleAnswerOrNull_singleAnswer_shouldReturnSingleAnswer() {
Done

2021-03-09 12:06 UTC, jingtang10 approved these changes
thanks @MuhammadSalman-7214

2021-03-09 15:03 UTC, MuhammadSalman-7214 commented
> thanks @MuhammadSalman-7214

your welcome @jingtang10 :+1:

2021-03-10 21:22 UTC, jingtang10 commented
https://github.com/google/android-fhir/pull/294 has been merged. So please rebase your branch onto `master` (or merge master into your feature branch if rebase is too difficult) and follow [this section](https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-coding-conventions) in the developer's guide to set up your environment to use the new coding conventions. Thanks!

2021-03-13 07:13 UTC, merged