Replace FQ id with logical id for Resources
google/android-fhir pull request #301
Opened 2021-03-10 08:53 UTC by deepankarb

* `Resource.getId()` returns the fully qualified id if underlying fields are populated.
* We replace `Resource.getId()` with `Resource.getId().getIdPart()` to retrieve the logical id instead.

This fixes #296

2021-03-10 09:23 UTC, jingtang10 requested changes
thanks @deepankarb :)

2021-03-10 09:23 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/Util.kt
> +internal fun Resource.logicalId(): String = this.idElement.idPart
I would change this to be a property rather than a function :)

```
internal val Resource.logicalId: String
  get() = this.idElement.idPart
```

2021-03-10 09:29 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/Util.kt
> +internal fun Resource.logicalId(): String = this.idElement.idPart
I kept thinking about this but was too lazy to look this up. Thanks!

2021-03-10 13:31 UTC, jingtang10 requested changes

2021-03-10 13:31 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/Util.kt
> +internal fun Resource.logicalId(): String = this.idElement.idPart
please comment once updated

2021-03-10 21:24 UTC, jingtang10 commented
https://github.com/google/android-fhir/pull/294 has been merged. So please rebase your branch onto `master` (or merge `master` into your feature branch if rebase is too difficult) and follow [this section](https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-coding-conventions) in the developer's guide to set up your environment to use the new coding conventions. Thanks!

2021-03-23 10:10 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/Util.kt
> +internal fun Resource.logicalId(): String = this.idElement.idPart
Updated to property.

2021-03-23 10:44 UTC, jingtang10 approved these changes
Thanks! 😀👌

2021-03-23 15:54 UTC, merged