wip: #281 rough draft
google/android-fhir pull request #305
Opened 2021-03-10 19:48 UTC by s-ayush2903

Linked to #281 
I searched about what is better, espresso or uiAutomator, it turned out that espresso tests are flaky most of the times([link](https://blog.codecentric.de/en/2018/11/android-testing-part2-kotlin-dsl-for-espresso-and-uiautomator/)) therefore I planned to use UI Automator for experimenting with a click test. And following the robot pattern along with uiAutomator will give us more easy to read tests([link](https://academy.realm.io/posts/kau-jake-wharton-testing-robots/)). To use the automaton, I added a few generic helper classes that help finding UI elements on the screen and also a custom error logging/report for the UI tests when run with automaton. 

Although by doing this much, I wasn't able to get the click test passing for the datepickerViewHolderFactory as to click on the textInputEditText we'll have to create a layout on the device screen, then click it and then verify if the expected outcome occurs, but the UI tests we currently have need the android device but do not create the layout of the screen that needs to be tested. I'll look into this more as this seems difficult to me as of now(clicking the view that isn't on screen), I saw an automated test for radioButtons where the click was being tested the same way(i.e., without inflating the layout on screen), I read it and tried understanding the workflow(i.e., create an item(that needs to be tested), bind it to the viewHolder, find it somehow(mostly using `findViewById` and then observe the expected result)), but I wasn't able to implement this behavior for datePickerViewHolderFactoryTest, I'll study it again and thoroughly and try re-implementing the required test(s). 

Also please present your views on the automated testing architecture, whether the proposed one is acceptable or not, thanks

2021-03-10 21:25 UTC, jingtang10 commented
Please follow [this section](https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-coding-conventions) in the developer's guide to set up your environment to use the new coding conventions. Thanks!

2021-03-11 21:18 UTC, s-ayush2903 commented
@jingtang10 What to do with this PR, should I keep writing tests or first wait for testing pattern to be decided : (

2021-03-11 21:51 UTC, jingtang10 commented
thanks for this PR!

can you please link this PR to an issue you're addressing?

uiautomator sounds like more heavy-handed than we need. i think we should try to use espresso first.

in general not a big fan of adding a bunch of infrastructure without us needing it first. i think we should focus on writing some test cases first.

2021-03-11 22:08 UTC, s-ayush2903 commented
Linked issue to the PR and thanks for input, will work on tests and remove irrelevant stuff

2021-03-25 10:37 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(DatePickerFragment().isVisible)
This is incorrect I believe, as when I make the assertion with `.isTrue()` at line#132, it fails. I feel that to check that pickers are being displayed we'll have to test 'em either in isolation or launch 'em in a scenario in the specific vhf. As of now I don't have much info on how to do the latter but I believe first one I should be able to write.

2021-03-28 14:08 UTC, jingtang10 requested changes
Thanks!

2021-03-28 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
I'm not sure what this is actually testing. I think we need to test when you click the item the right answer is set. But this doens't test that.

2021-03-28 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
@joiskash

2021-03-28 14:40 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
I guess this is only testing that on clicking the drop down, the correct number of options are being displayed (as the name of the test suggests). You could maybe add another test like `selectOptionFromDropDown` which will simulate two clicks, the first to open the drop down and the next to select an answer option. You can then assert if the right answer is selected.

2021-03-28 23:16 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
I actually wanted to do that exactly, but was struggling in finding a specific item from the list of dropdown, so wrote quite _hacky_ test  :sweat: If it were espresso and an activity then would've written it, but this pattern of testing is very new to me, so kinda struggling. Will read about it and push the fix.

2021-03-30 23:32 UTC, jingtang10 commented
is there any update? thanks!

2021-04-04 12:56 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
@joiskash Any suggestions on how to retrieve any item of dropdown to perform click?

2021-04-05 02:55 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
`val tmp = viewHolder
      .itemView
      .findViewById<AutoCompleteTextView>(R.id.auto_complete)
      .adapter
      .getView(0,null,parent)
    `

2021-04-05 02:56 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
@s-ayush2903  try this, it works for me

2021-04-05 12:17 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
The reason for passing convertView as null in the getView is that we don't want to inflate a layout? I was doing the same thing but was just passing `viewHolder.itemView` in convertView and that showing some problem.

2021-04-05 12:21 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
> 2: The adapters are built to reuse Views, when a View is scrolled so that is no longer visible, it can be used for one of the new Views appearing. This reused View is the `convertView`. If this is null it means that there is no recycled View and we have to create a new one, otherwise we should use it to avoid creating a new.

Since this is the first time the view is being created, and there seems to be no recycled view I thought passing null was the right thing to do, to create a new view. Not sure if this is 100% correct.

[Reference](https://stackoverflow.com/questions/10120119/how-does-the-getview-method-work-when-creating-your-own-custom-adapter)

2021-04-05 12:38 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
Thanks, this sounds reasonable. But the concerned test still fails : (

2021-04-05 12:39 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +  fun clickOnCheckboxShouldToggleItsCurrentState() {
6d921e8

2021-04-05 12:58 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
oh did you try debugging to make sure that after `performClick` has been invoked you reach the `autoCompleteTextView.onItemClickListener` block within `QuestionnaireItemDropDownViewHolderFactory`?

2021-04-12 14:31 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +      .isTrue()
> I actually wanted to do that exactly, but was struggling in finding a specific item from the list of dropdown, so wrote quite _hacky_ test 😓 If it were espresso and an activity then would've written it, but this pattern of testing is very new to me, so kinda struggling. Will read about it and push the fix.

@s-ayush2903 would you please add espresso tests for the view holder factories? (probably in a separate issue and PR)

2021-04-12 14:42 UTC, jingtang10 requested changes

2021-04-12 14:42 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetAnswerToFalse() {
```suggestion
  fun click_shouldSetCheckBoxUnchecked() {
```

also rename the previous test case `shouldSetQuestionnaireResponseItemComponentAnswer` to `click_shouldSetAnswerTrue`.

Basically you should have 4 cases:

```
fun click_shouldSetCheckBoxChecked
fun click_shouldSetAnswerTrue
fun click_shouldSetCheckBoxUnchecked
fun click_shouldSetAnswerFalse
```

2021-04-12 14:42 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetAnswerToTrue() {
```suggestion
  fun click_shouldSetCheckBoxchecked() {
```

2021-04-12 14:42 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(DatePickerFragment().isVisible)
yeah we probably need to use scenario. that's also why we created a separate issue for this. can you take this on?

happy for this PR to be merged with the improvements you made to `QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt`

2021-04-12 14:42 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(DatePickerFragment().isVisible)
```suggestion
    assertThat(DatePickerFragment().isVisible).isTrue()
```

2021-04-12 14:42 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(DatePickerFragment().isVisible)
```suggestion
    assertThat(DatePickerFragment().isVisible).isTrue()
```

2021-04-15 15:06 UTC, jingtang10 requested changes

2021-04-15 15:06 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +    with(checkBox) {
i don't see the advantage of using `with` here. just do `checkBox.performClick()`?

2021-04-15 21:08 UTC, s-ayush2903 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +    with(checkBox) {
Ah, I tend to use scoping fns when we use some prop/var/element more than once in sequence

2021-04-19 15:37 UTC, jingtang10 approved these changes
Thanks @s-ayush2903! 👍

2021-04-19 21:14 UTC, merged