SDC: Crash fix for Questionnaire Item type equals to GROUP
google/android-fhir pull request #308
Opened 2021-03-11 13:48 UTC by shoaibmushtaq25

SDC: Crash fix for Questionnaire Item type equals to GROUP
Standard data capture gallery app was crashing when Questionnaire Item type equals to GROUP.
The linked issue is https://github.com/google/android-fhir/issues/271

2021-03-11 14:19 UTC, shoaibmushtaq25 commented
@googlebot I signed it!

2021-03-11 14:27 UTC, shoaibmushtaq25 commented
@googlebot I fixed it.

2021-03-15 18:25 UTC, jingtang10 requested changes
Thanks @shoaibmushtaq25!

2021-03-15 18:25 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +                )
this is not needed i think? same for all the test cases below.

2021-03-17 07:50 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      }
Resolved.

2021-03-17 10:41 UTC, jingtang10 commented
please re-request review once you're done. thanks!

2021-03-17 11:28 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val questionnaireBuilder = Questionnaire.newBuilder()
Resolved

2021-03-17 11:29 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaire.itemList.forEach { questionnaireBuilder.addItem(it) }
Resolved

2021-03-17 11:29 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +      (linkId: String) -> Pair<Questionnaire.Item?, QuestionnaireResponse.Item?>
Resolved, Changed to Result class.

2021-03-17 11:29 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +    questionnaireResponseItemRetriever:
Resolved.

2021-03-17 11:29 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +  val questionnairePair = questionnaireResponseItemRetriever(enableWhen.question.value)
Resolved.

2021-03-17 11:31 UTC, shoaibmushtaq25 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +                )
I Changed the Pair to Result class here to use the power of destructive declarations. Please guide me, what should I pass here in place of QuestionnaireItem?

2021-03-17 16:20 UTC, jingtang10 requested changes

2021-03-17 16:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    //    questionnaire.itemList.forEach { questionnaireBuilder.addItem(it) }
?

2021-03-17 16:20 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +                )
i mean the line 474-486 the `addEnableWhen` function isn't needed. can you try without

2021-03-17 16:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +data class Result(
```suggestion
data class QuestionnaireItemWithResponse(
```

or something similar?

2021-03-17 17:22 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    //    questionnaire.itemList.forEach { questionnaireBuilder.addItem(it) }
Oh my bad, Let me remove it.

2021-03-17 17:51 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluator.kt
> +data class Result(
Name changed to `QuestionnaireItemWithResponse`.

2021-03-17 17:54 UTC, shoaibmushtaq25 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +                )
Yeah, removing `addEnabledWhen` worked here, so I have removed it. Thanks :+1:

2021-03-19 13:05 UTC, shoaibmushtaq25 commented
Please feel free to review this PR again @jingtang10. All comments and conflicts to date has been resolved.

2021-03-19 18:43 UTC, merged

2021-03-20 21:16 UTC, shoaibmushtaq25 commented
> Thanks very much!

Thanks a lot , Really appreciated.