fix: Fixes reference app crash on triggering Evaluation
google/android-fhir pull request #324
Opened 2021-03-13 20:26 UTC by s-ayush2903

Close #319 
* Checked and fixed nullability issues

2021-03-15 17:19 UTC, s-ayush2903 commented
@deepankarb @jingtang10 Would it be Ok to create a factory in this PR and use it to create instances of FhirEngine, as currently  we have different `FhirApplication`s(BaseApplication classes that extend the `CoreApplication`(class which is the abstraction of FhirApplication class)) for `reference` and `cqlreference` modules whose companion object method is accessed to create a `fhirEngine`.

2021-03-16 11:23 UTC, s-ayush2903 commented
Why is spotless check failing, irrespective of the fact that I've same settings as mentioned in [wiki](https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-coding-conventions) : (
See:
|Indents for Kt|Ktfmt settings|
|--|---|
|![001](https://user-images.githubusercontent.com/56556919/111300729-6ba2e580-8677-11eb-86dc-30ef1c0d9e3a.png)|![002](https://user-images.githubusercontent.com/56556919/111300708-65146e00-8677-11eb-98d2-ac4a8bb2f952.png)|

2021-03-17 14:19 UTC, jingtang10 requested changes
@s-ayush2903 Hi thanks for this PR and apologies for the delay in reviewing. Been trying to work out the right approach and architecture here.

I created #330 where I added a little more details. Basically, we want to separate the CQL functionalities from the `core` module. I think this PR should remove rather than add to the `core` module. Things like `CoreApplication.kt` should be in the new `cqlreference` application instead.

I think the new `cqlreference` module should probably also use hardcoded data rather than data read from the db. But that can be in a separate PR.

I understand this is quite an involved PR. Thanks for taking this on. I'm happy if you want to pick other issues to work on first. But please do comment first.

2021-03-18 15:09 UTC, s-ayush2903 commented
>  Things like `CoreApplication.kt` should be in the new `cqlreference` application instead.

As of now, I don't have any plausible reason to move `CoreApplication.kt` to `cqlreference` module, as it is being used by both, the `reference` module and the `cqlreference` module(to instantiate fhirEngine), also the files moved to the core module have the same reason as mentioned for the `CoreApplication.kt`; we can do move 'em to `cqlreference` module but they won't be accessible from `reference` module and we'll have to rewrite 'em there(in `reference` module) as well, thereby increasing the code duplicacy.

2021-03-19 14:50 UTC, jingtang10 requested changes
thanks! i think what i probably haven't made very clear is that we'll need to rewrite the cql reference app (see the linked issue) by depending on a different library (`cql-evaluator` rather than `cql-engine`).

I think the best thing to do is actually just removing the cql activity from the reference app altogether and remove the evaluatecql api. and then create a skeleton app called cqlreference.

I think what's been changed in this PR about the database API is not right -- we don't want to expoose the db to applications.

sorry about this - but I think you're better off just starting afresh with a new PR. i'm happy to do that as well if you just want to take on a new issue?

2021-03-19 14:50 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> -internal class DatabaseImpl(context: Context, private val iParser: IParser, databaseName: String?) :
please revert changes in this file. the database need to be internal and should not be exposed to applications. the sdk's APIs should be exposed by `FhirEngine`.

2021-03-19 14:50 UTC, jingtang10 commented on cqlreference/src/main/java/com/google/android/fhir/cqlreference/cql/CqlEngineUtils.kt
> +    else null
i think the best course of action for now is to remove this code and add an not implemented exception before we rewrite this application.

2021-03-19 14:50 UTC, jingtang10 commented on cqlreference/build.gradle
> +    implementation project(path: ':core')
remove this dependency for now. we haven't defined an API for the cql reference app to use the core lib correctly yet.

2021-03-19 22:02 UTC, s-ayush2903 commented on cqlreference/build.gradle
> +    implementation project(path: ':core')
If we remove this, then we'll have to write the FhirEngine interface and its impl both again in the cqlref module, as there is an option of downloading the fhir res in the cqlLoadActivity and for that we'll have to write a functionality to save the Res(for which the working engine is needed). So there exists some way of achieving the same behavior(as current one's) without adding it as a dependency, that'll be interesting.

2021-03-19 22:02 UTC, s-ayush2903 commented
>  we'll need to rewrite the cql reference app (see the linked issue) by depending on a different library (cql-evaluator rather than cql-engine).

Oh this makes it clear, I was under the impression that we need to separate the engine only. 

> just starting afresh with a new PR


So will I have to create a new PR for this issue then, what's the problem with this one? I can rewrite commit history if that is an issue, rest is on your preference

2021-03-22 10:15 UTC, jingtang10 commented on cqlreference/build.gradle
> +    implementation project(path: ':core')
the direction we'll be taking with the cql ref module is that we will be using hard-code resources for now. so it won't have a dependency on the core module where there's a db. this will be a breaking change and we will need to rewrite the cql ref module (the UI).

2021-03-22 10:18 UTC, s-ayush2903 commented on cqlreference/build.gradle
> +    implementation project(path: ':core')
So it means, I'll have to hardcode it here in this PR. Ok fine :+1:, I was unsure as you mentioned that it could be done in a separate PR

2021-03-22 13:44 UTC, jingtang10 commented on cqlreference/build.gradle
> +    implementation project(path: ':core')
can yo uwork on this issue as a priority instead of grabbing other issues? this is blocking to other things.

i don't mind even if you just leave things in the cql reference module unimplemented. the key thing that needs to happen in the core module is the evaluateCql api needs to be deleted as well as the cql folder.

2021-03-22 17:15 UTC, jingtang10 requested changes

2021-03-22 17:15 UTC, jingtang10 commented on core/build.gradle
> +    implementation deps.retrofit.mock
remove these.

2021-03-22 17:58 UTC, jingtang10 requested changes

2021-03-22 17:58 UTC, jingtang10 commented on settings.gradle
> +include ':cqlreference'
please move this up so that these modules are sorted alphabetically. thx!

2021-03-22 17:58 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +      "${searchResults.count()} search results: " + searchResults.joinToString(" ")
```suggestion
      "${searchResults.count()} search results: ${searchResults.joinToString(" ")}"
```

2021-03-22 17:58 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt
> -import com.google.android.fhir.reference.data.HapiFhirResourceDataSource
keep these intact please.

2021-03-22 19:45 UTC, s-ayush2903 commented on core/build.gradle
> +    implementation deps.retrofit.mock
7d4e820

2021-03-22 19:45 UTC, s-ayush2903 commented on settings.gradle
> +include ':cqlreference'
7a220c7

2021-03-22 19:45 UTC, s-ayush2903 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +      "${searchResults.count()} search results: " + searchResults.joinToString(" ")
7a220c7

2021-03-22 19:45 UTC, s-ayush2903 commented on reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt
> -import com.google.android.fhir.reference.data.HapiFhirResourceDataSource
7a220c7

2021-03-22 21:59 UTC, jingtang10 approved these changes
Thanks @s-ayush2903 for your contribution! Just a couple of small nits.

👍

2021-03-22 21:59 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/api/FhirConverter.kt
> +package com.google.android.fhir.api
revert this change

2021-03-22 21:59 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/data/FhirPeriodicSyncWorker.kt
> +import com.google.android.fhir.reference.FhirApplication.Companion.fhirEngine
revert this change - seems unnecessary.

2021-03-23 07:41 UTC, s-ayush2903 commented on reference/src/main/java/com/google/android/fhir/reference/data/FhirPeriodicSyncWorker.kt
> +import com.google.android.fhir.reference.FhirApplication.Companion.fhirEngine
Is it a poor practice to use static imports? d075369

2021-03-23 07:41 UTC, s-ayush2903 commented on reference/src/main/java/com/google/android/fhir/reference/api/FhirConverter.kt
> +package com.google.android.fhir.api
d075369

2021-03-23 08:13 UTC, merged

2021-03-23 09:06 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/data/FhirPeriodicSyncWorker.kt
> +import com.google.android.fhir.reference.FhirApplication.Companion.fhirEngine
oops missed this i don't think we have a strong view here actually :) i just thought it would provide a bit more context including the classname in the invocation. but i don't feel strongly.

2021-03-23 09:08 UTC, jingtang10 commented
Thanks @s-ayush2903 for preservering - this is a structural change and we had some direction changes. Appreciate it.

👍 👍 👍

2021-03-23 10:54 UTC, s-ayush2903 commented
Thanks to you too for clarifying stuff. With this, maybe an Issue can be created that targets about the todos in the cqlref module. And I would be happy to work on it! Thoughts?