feat:Add navigation for sdc gallery app fix#154
google/android-fhir pull request #325
Opened 2021-03-14 15:15 UTC by epicadk

fix#154

2021-03-15 12:24 UTC, epicadk commented on build.gradle
> +        classpath deps.navigation.safeargs
The docs mention that this needs to be added to the top level build.gradle file. I tried adding it to the module level file however it throws an error. Should I leave it here or should I remove navigation safeargs?

2021-03-15 12:49 UTC, epicadk commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MyQuestionnaireFragment.kt
>  package com.google.android.fhir.datacapture.gallery
Had to rename the fragment to `MyQuestionnaireFragment` because `QuestionnaireFragment` shadows an existsing class.

2021-03-16 12:57 UTC, epicadk commented on build.gradle
> +        classpath deps.navigation.safeargs
@jingtang10 sorry for this I have tried to explain in more detail in the pr description. I'll keep in mind that I should discuss this with the code owners first. 😓

2021-03-17 14:01 UTC, jingtang10 requested changes
Thanks @epicadk !

2021-03-17 14:01 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireResponseDialogFragment.kt
>  class QuestionnaireResponseDialogFragment() : DialogFragment() {
add `onDestroyView`?

2021-03-17 16:17 UTC, epicadk commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MyQuestionnaireFragment.kt
>  package com.google.android.fhir.datacapture.gallery
<img src = https://user-images.githubusercontent.com/56596662/111500603-2f03e680-876a-11eb-990f-02124a9e82e3.png height =400 width =400>

2021-03-17 16:21 UTC, epicadk commented on build.gradle
> +        classpath deps.navigation.safeargs
> I don't quite understand here... what's the purpose of this TODO?

Right now this classpath will be added to the entire project but we would only use it in the sdc gallery module. So I was just trying to figure out a way to add it to the module level build.gradle file however having read up I don't think it's possible.

2021-03-17 16:43 UTC, jingtang10 commented
With #334 merged, please rebase/merge and run `./gradlew sA` to format your XML files. Also see https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-style.

2021-03-17 16:43 UTC, jingtang10 commented on build.gradle
> +        classpath deps.navigation.safeargs
ah ok. thanks for the explanation. yes please leave it here. it's fine.

2021-03-17 16:44 UTC, jingtang10 commented on build.gradle
> +        classpath deps.navigation.safeargs
and remove the todo

2021-03-17 16:46 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MyQuestionnaireFragment.kt
>  package com.google.android.fhir.datacapture.gallery
What happens if you continue? does gradle complain if you try to build?

2021-03-17 17:01 UTC, epicadk commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MyQuestionnaireFragment.kt
>  package com.google.android.fhir.datacapture.gallery
> What happens if you continue? does gradle complain if you try to build?

Nope it does not. It would just be hard to understand which `QuestionnaireFragment` class we are using that's all

2021-03-17 18:43 UTC, jingtang10 requested changes
Thanks - just a couple of small things.

2021-03-17 18:43 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListAdapter.kt
> +    val binding =
just inline this?

2021-03-17 18:43 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MyQuestionnaireFragment.kt
> +class MyQuestionnaireFragment : Fragment() {
Maybe `QuestionnaireContainerFragment`?

2021-03-17 18:43 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MyQuestionnaireFragment.kt
>  package com.google.android.fhir.datacapture.gallery
ah ok so it's just an IDE thing. I thought it's a navigation library bug.

I suggested below maybe `QuestionnaireContainerFragment`?

2021-03-17 19:49 UTC, epicadk commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListAdapter.kt
> +    val binding =
I tried but on running spotless it just reverts it back to this.

2021-03-18 10:31 UTC, jingtang10 requested changes
thanks!

2021-03-18 10:31 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListAdapter.kt
> +    val binding =
I mean
```suggestion
    return ViewHolder(QuestionnaireListItemViewBinding.inflate(LayoutInflater.from(parent.context), parent, false))
```

2021-03-18 10:31 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
> +    val questionnaireResponseJson = JsonFormat.getPrinter().print(questionnaireResponse)
You'll need to use something like this since we just merged #329:

```
FhirContext().forR4().getPrinter().encodeResource...String(questionnaireResponse);
```

2021-03-18 10:31 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
> +import com.google.fhir.r4.core.QuestionnaireResponse
you'll find you'll need to update this after sync to the latest changes.

2021-03-19 12:09 UTC, jingtang10 approved these changes
Thank you very much for this change!

🎉🎉🎉

2021-03-19 16:58 UTC, merged