add ResourceMapperHAPI
google/android-fhir pull request #326
Opened 2021-03-15 12:02 UTC by Andati

2021-03-15 12:08 UTC, Andati commented
@googlebot I signed it!

2021-03-16 09:41 UTC, jingtang10 commented
Thanks @Andati for this. I just created #329 and I think once that's done we can rebase this onto that? So we will have a unified resource mapper and also will have better test coverage.

2021-03-16 12:35 UTC, Andati commented
yes @jingtang10, looks good to me

2021-03-18 09:18 UTC, jingtang10 commented
Hey @Andati can you try to rebase/merge now that #329 is merged

2021-03-24 23:52 UTC, jingtang10 requested changes
Thanks for the PR @Andati!

Can you merge this code with https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt?

2021-03-24 23:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapperHAPI.kt
> +      Class.forName("com.google.android.fhir.datacapture.model.$className").newInstance() as
I don't think this approach is gonna work in general. We should find a more generic way of handing things than havin to create a new class for each type of FHIR resource.

2021-03-25 10:40 UTC, Andati commented
Sure @jingtang10 let me merge the 2 files while I look for a generic way of extending the fhir resources

2021-04-03 18:42 UTC, jingtang10 requested changes
Thanks @Andati for generalizing this class! Great work! I haven't gone through this in detail but some high-level comments first.

2021-04-03 18:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          .getMethod("add${targetFieldName.capitalize()}", innerClass)
this only works with repeated field -- if a field is not repeated it would be `setXXX`.

2021-04-03 18:42 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                },
Quick question: is it guaranteed that sub-fields of the same field would always be grouped together? This isn't obvious to me from reading the sdc standard but I may have missed it. Have you tried to verify this? Thanks!

2021-04-03 18:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun extract(
I haven't gone through this in detail but my general feedback is that this function is fairly long and a little difficult to read. I actually think you could refactor the original code (the `extractFields` and `extractField` methods) and create some high level structure that would make the more readable.

There also seems to be some duplication between the code in `extract` method and `createInnerClassObject`. Can you try to extract a common function? Thanks!

2021-04-07 14:13 UTC, Andati commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          .getMethod("add${targetFieldName.capitalize()}", innerClass)
this method is for ItemType `GROUP` which is a list in the HAPI library. And so the `add` method adds to a list. Example: `AddName`. If you call `setName` then you have to pass a list instead

2021-04-07 14:40 UTC, Andati commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                },
I haven't come across this as well while checking the hl7 sdc standard. If the questions are not grouped together, then there would be more entries in the list for the group. For instance, the patient name is `List<HumanName>` in the HAPI library and so there would be a first entry for the first group and a second entry for the second group. The list size would then be 2

2021-04-07 14:41 UTC, Andati commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun extract(
There is indeed duplication, working on it

2021-04-07 17:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          .getMethod("add${targetFieldName.capitalize()}", innerClass)
I think the fact that the questionnaire item is of type `GROUP` does not guarantee that the field is a repeated field.

Just imagine if the name field is not repeated in patient. You can still have a group of questions for the first name and last name.

2021-04-29 13:35 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Questionnaire.QuestionnaireItemComponent.itemComponentContextNameToExpressionMa:
Does this change intentional or mistaken?

2021-04-29 14:15 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Questionnaire.QuestionnaireItemComponent.itemComponentContextNameToExpressionMa:
That is no longer in use. It should be deleted

2021-04-29 15:22 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapperHAPI.kt
> +      Class.forName("com.google.android.fhir.datacapture.model.$className").newInstance() as
@jingtang10 Could you please explain the above comment more to have more clarity of the change here?

2021-05-05 08:36 UTC, shoaibmushtaq25 commented
> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fandroid-fhir%2Fpull%2F326) for more info**.

@googlebot I consent.

2021-05-05 08:38 UTC, ekigamba commented
> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fandroid-fhir%2Fpull%2F326) for more info**.

@googlebot I consent

2021-05-05 08:42 UTC, ekigamba commented
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fandroid-fhir%2Fpull%2F326) for more info**.

@googlebot I fixed it

2021-05-05 08:44 UTC, ekigamba commented
@googlebot I consent.

2021-05-06 16:21 UTC, jingtang10 commented
I can see that `12672919+shoaibmushtaq25@users.noreply.github.com` has signed the CLA but `shoaib.mushtaq@venturedive.com` hasn't. Can you double check @shoaibmushtaq25?

2021-05-06 16:35 UTC, shoaibmushtaq25 commented
As I remember I already signed the CLA with this email and also submitted and merged a PR earlier. Anyways, I will double check it to make sure. Thanks for pointing out

2021-05-07 10:36 UTC, shoaibmushtaq25 commented
@googlebot I signed it!

2021-05-07 10:38 UTC, shoaibmushtaq25 commented
@googlebot I signed it!

2021-05-07 12:28 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          .getMethod("add${targetFieldName.capitalize()}", innerClass)
Done.

2021-05-07 12:32 UTC, shoaibmushtaq25 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                },
Link to the question asked on FHIR chat.
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/SDC.20Extraction.20examples/near/236809508

2021-05-07 12:33 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun extract(
Done.

2021-05-10 09:44 UTC, jingtang10 commented
Hi Shaoib - I think you need to reply `@googlebot I consent` as well. can you try that please?

2021-05-10 14:24 UTC, shoaibmushtaq25 commented
@googlebot I consent.

2021-05-11 13:58 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun extractQuestionAnswer(
@jingtang10 I believe that this is covered currently

2021-05-11 14:07 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    var questionnaireResponseItemListIterator1 = questionnaireResponseItemListIterator
Fixed

2021-05-11 14:07 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun processItemIterator(
Fixed

2021-05-14 17:16 UTC, jingtang10 requested changes

2021-05-14 17:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      val propertyType = questionnaireItem.inferPropertyResourceClass
move this and line 111 before the if block

2021-05-14 17:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      if (questionnaireItem.item != null && questionnaireResponseItem.item != null) {
remove this condition -- both are guaranteed to be non-null.

2021-05-17 06:49 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +data class FieldType(val mainType: Class<*>, val parameterizedType: Class<*>?, val name: String)
If you mean the `parameterizedType`, then yes, there are a couple of cases where it's not a list. We also use both properties, `mainType` and `parameterizedType` to fetch the method using reflection and sometimes wrap the answer using the correct type before calling the setter method

2021-05-17 06:57 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          !TextUtils.isEmpty(modelAndField[1])
:thinking: Good question. Initially we check both parts since their absence means the `definition` is wrong i.e. If either the Resource or the top-level property is missing

For example `http://hl7.org/fhir/StructureDefinition/Patient#Patient.name` is a valid value for `definition`

2021-05-17 06:58 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      val propertyType = questionnaireItem.inferPropertyResourceClass
Done

2021-05-17 06:59 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +data class FieldType(val mainType: Class<*>, val parameterizedType: Class<*>?, val name: String)
Done

2021-05-17 07:02 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      if (questionnaireItem.item != null && questionnaireResponseItem.item != null) {
Could you explain this? I believe they are not guaranteed to be non-null

2021-05-17 08:52 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +data class FieldType(val mainType: Class<*>, val parameterizedType: Class<*>?, val name: String)
However, I have removed the `name` which doesn't seem required anymore

2021-05-17 09:55 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun extractQuestionAnswer(
Cool, I didn't know that. Done

2021-05-17 13:38 UTC, jingtang10 requested changes

2021-05-17 13:38 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val propertyType = questionnaireItem.inferPropertyResourceClass
```suggestion
    val propertyType = questionnaireItem.inferPropertyResourceClass ?: return
```

and you can remove line 112 and line 133

2021-05-17 14:05 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val propertyType = questionnaireItem.inferPropertyResourceClass
Fixed.

2021-05-17 17:47 UTC, jingtang10 requested changes

2021-05-17 17:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * - Patient#identifer = FieldType(Identifier::javaClass, List::javaClass)
can you give an example of a parameterized type being non-list?

2021-05-17 17:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  get() = parameterizedType?.simpleName.equals(List::class.java.simpleName)
:/ i think comparing `simpleName` might not be enough for this. can we do something more accurate? will `==` work?

2021-05-18 08:19 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return base
Done.

2021-05-18 08:20 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   * Base object target property. This method handles nested fields in the Questionnaire
Done.

2021-05-18 08:22 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   * target property. This method handles nested fields in the Questionnaire
Done.

2021-05-18 08:24 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      extractField(questionnaireItem, questionnaireResponseItem)
Done.

2021-05-18 08:32 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      if (questionnaireItem.item != null && questionnaireResponseItem.item != null) {
Done.

2021-05-18 09:22 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  get() = parameterizedType?.simpleName.equals(List::class.java.simpleName)
It's not as accurate. I had a previous issue comparing the complete class name. I think we can try this again

2021-05-18 09:22 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          !TextUtils.isEmpty(modelAndField[1])
Sounds cool

2021-05-18 09:23 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * - Patient#identifer = FieldType(Identifier::javaClass, List::javaClass)
Enumeration in `Patient.gender`

2021-05-18 09:27 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     */
Yea, this should be implemented

2021-05-18 13:14 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          !TextUtils.isEmpty(modelAndField[1])
Done.
Added a more generic way.

2021-05-18 14:36 UTC, shoaibmushtaq25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  get() = parameterizedType?.simpleName.equals(List::class.java.simpleName)
Done.

2021-05-18 22:08 UTC, jingtang10 requested changes

2021-05-18 22:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun FieldType.getMethodParam(): Class<*> =
add documentation on what this is and why this is needed

2021-05-18 22:08 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     */
i struggle a little to understand what is to do done here. can you try to elaborate a little more here?

also can you reformat using one of these ways: https://google.github.io/styleguide/javaguide.html#s4.8.6-comments to make the comment neater.

2021-05-19 12:34 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        for (declaredField in declaredFields) if (declaredField.name.equals(modelAndField[i])) {
I see this is only used once

2021-05-19 13:01 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * to the type elements in the group questions
I am currently not aware of any other. I expect that we might have some more bugs around this. What do you think?

2021-05-19 13:19 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return codeableConcept
Fixed. Nice catch

2021-05-19 13:19 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * of the setter methods and converting the answer to the expected parameter type
Fixed

2021-05-19 13:19 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val modelAndField = this.targetResourceAndElement
Fixed

2021-05-19 13:22 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + */
Fixed

2021-05-19 13:26 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        this.updateFieldWithEnum(propertyType, targetFieldName, ans)
Fixed

2021-05-19 13:26 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        this.updateFieldWithAnswer(ans, targetFieldName, propertyType)
Fixed

2021-05-19 13:26 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      this.extractFields(questionnaireItem.item, questionnaireResponseItem.item)
Fixed

2021-05-19 13:28 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        val declaredFields = currentClass.declaredFields
Fixed

2021-05-19 13:28 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * - Patient#name = FieldType(String::javaClass, null)
Fixed

2021-05-19 13:30 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +     */
I have removed the comment

2021-05-19 13:33 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * - Patient#identifer = FieldType(Identifier::javaClass, List::javaClass)
Done

2021-05-19 13:33 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // get answer from questionnaireResponse or from initial value in questionnaire
Done

2021-05-19 15:34 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        for (declaredField in declaredFields) if (declaredField.name.equals(modelAndField[i])) {
I've tried to reduce both loops to `forEach` loops with labels to enable `break` and `continue`

2021-05-19 15:34 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        for (declaredField in declaredFields) if (declaredField.name.equals(modelAndField[i])) {
Done

2021-05-19 16:05 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun FieldType.getMethodParam(): Class<*> =
Done

2021-05-19 17:22 UTC, jingtang10 requested changes

2021-05-19 17:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          }
There's still something about this that feels a little unusual... See comment later for the extension functions you can add to `Field`. With those, and with the following:

```
private fun Field.getNestedField(name: String): Field {
  val clazz = if (isParameterized) {
    (genericType as ParameterizedType).actualTypeArguments[0]
  } else {
    type
  }
  return clazz.declaredFields.single { it.name == name }
}
```

and then all you need to do really is to follow the path to the type in a simple loop and in each iteration you just call `getNestedField`.

2021-05-20 07:43 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        else return
Done

2021-05-20 07:48 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Base.updateFieldWithEnum(propertyType: FieldType, targetFieldName: String, ans: Base) {
Done

2021-05-20 08:00 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  if (isParameterized) parameterizedType!! else mainType
:laughing: Yea, I agree

2021-05-20 11:12 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          }
OK, I tried something a bit different due to the initial value which is a Class and not a field. I also ended up using the method `Class#getDeclaredField(String)`

2021-05-20 19:40 UTC, jingtang10 requested changes

2021-05-20 19:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return resourceField
try something like this:

```suggestion
    val path = definitionPath ?: return null
    if (path.size < 2) return null
    var resourceClass: Class<*> = Class.forName("org.hl7.fhir.r4.model.${path[0]}")
    val field: Field = resourceClass.getField(path[1])
    return path.drop(2).fold(field) { field: Field, nestedFieldName: String ->
      field.mainType.getField(nestedFieldName)
    }
```

i think the `fold` function in kotlin is perfect for this.

2021-05-20 19:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Questionnaire.QuestionnaireItemComponent.targetResourceAndElement: List<String>?
```suggestion
private val Questionnaire.QuestionnaireItemComponent.definitionPath: List<String>?
```

2021-05-20 19:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Field.retrieveNonParameterizedType(): Class<*> =
can you inline this function? it's only used in one place.

2021-05-20 19:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Field.mainType: Class<*>
what about a more specific name:

```suggestion
private val Field.nonParameterizedType: Class<*>
```

2021-05-20 19:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * For example a Field of List<String> should give [String] as the [mainType]
```suggestion
 * The non-parameterized type of this field (e.g. `String` for a field of type `List<String>`).
```

2021-05-21 08:55 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  get() = type
I Agree

2021-05-21 09:02 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  val paramAns = generateAnswerWithCorrectType(answer, fieldType)
Fixed

2021-05-21 09:07 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Questionnaire.QuestionnaireItemComponent.inferPropertyResourceClass: Field?
Done

2021-05-21 09:07 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val propertyType = questionnaireItem.inferPropertyResourceClass ?: return
Done

2021-05-21 09:11 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      }
I think we should leave this as-is for now. It will make the `updateFieldWithAnswer` longer, more complex and less readable. However, I agree that the functionality should be almost be similar

2021-05-21 09:17 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      updateFieldWithAnswer(base, targetFieldName, propertyType)
Done

2021-05-21 11:25 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> + * For example a Field of List<String> should give [String] as the [mainType]
Done

2021-05-21 11:35 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Field.mainType: Class<*>
Done

2021-05-21 11:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Field.retrieveNonParameterizedType(): Class<*> =
Done

2021-05-21 11:39 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private val Questionnaire.QuestionnaireItemComponent.targetResourceAndElement: List<String>?
Done

2021-05-21 11:44 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Base.updateFieldWithAnswer(answer: Base, targetFieldName: String, fieldType: Field) {
Done

2021-05-21 12:07 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return resourceField
Tried to re-write it this way. The results

```
	val path = definitionPath ?: return null
    if (path.size < 2) return null
    val resourceClass: Class<*> = Class.forName("org.hl7.fhir.r4.model.${path[0]}")
    val field: Field = resourceClass.getFieldOrNull(path[1]) ?: return null

    return path.drop(2).fold(field) { field: Field?, nestedFieldName: String ->
      field?.nonParameterizedType?.getFieldOrNull(nestedFieldName)
    }
```

2021-05-21 16:53 UTC, jingtang10 approved these changes
Thanks @ekigamba and @shoaibmushtaq25 for the perseverance! Congrats on landing this PR! 🎉🚀

(just a couple of nit picks).

2021-05-21 16:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Base.updateFieldWithEnum(propertyType: Field, targetFieldName: String, answer: Base) {
similar to `updateField` method, the `targetFieldName` can be removed here no?

also rename `propertyType` to `field` and `answer` to `value`.

```suggestion
private fun Base.updateFieldWithEnum(field: Field, value: Base) {
```

2021-05-21 16:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   */
this is a bit of nit picking: can you use https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax or maybe just `//` for multi-line comment? the indentation here looks off to me.

2021-05-21 16:56 UTC, shoaibmushtaq25 commented
Thank you to you as well 👍 for putting time on it for the review and give us feedback to improve the code.

2021-05-24 08:13 UTC, ekigamba commented
@jingtang10 I also agree with Shoaib. Thanks for taking the time to review and patience to point out all the issues and bear with us.

2021-05-24 08:24 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   */
Fixed. I agree

2021-05-24 08:25 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Base.updateFieldWithEnum(propertyType: Field, targetFieldName: String, answer: Base) {
Fixed

2021-05-24 09:40 UTC, merged