Add : index date search params
google/android-fhir pull request #332
Opened 2021-03-16 10:57 UTC by epicadk

Fixes #285

2021-03-22 13:07 UTC, deepankarb requested changes
Thanks for adding this :) I have left some comments, please fix and I'll approve.

2021-03-22 13:07 UTC, deepankarb commented on core/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +            start = Date(1516055094)
Can we add the values in any human readable form? E.g.:
```suggestion
            start = Date(1516055094) // Tue Jan 16 03:54:54 IST 2018
```

2021-03-22 16:46 UTC, epicadk commented on core/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +            (period.hasEnd()) -> period.endElement.precision
I tried this. It should work but I know it probably isn't the best way to do this. Do you have any suggestions?

2021-03-23 16:50 UTC, epicadk commented
@deepankarb made the request changes can you review it again?

2021-03-30 20:24 UTC, epicadk commented
@deepankarb gentle reminder can you please review the pr again? 😅

2021-03-31 09:47 UTC, deepankarb approved these changes
Thanks!

2021-04-07 16:51 UTC, jingtang10 requested changes

2021-04-07 17:38 UTC, epicadk commented on core/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +      "Timing", "Timing.repeat" -> {
Sorry you're right Timing.repeat is the fhirtype for the Timing repeat component. Removing.

2021-04-07 17:40 UTC, epicadk commented on core/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +      "Period" -> {
Made the changes 👍🏼

2021-04-07 17:43 UTC, jingtang10 approved these changes
Thanks again for your contribution! 👍

2021-04-07 18:13 UTC, merged