prefix added to questions
google/android-fhir pull request #333
Opened 2021-03-16 12:55 UTC by MuhammadSalman-7214

2021-03-17 10:41 UTC, jingtang10 commented
please add a description of your approach here in the PR description. thanks!

2021-03-17 11:17 UTC, jingtang10 requested changes
Thank you @MuhammadSalman-7214!

Please add tests.

2021-03-17 11:17 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_check_box_view.xml
> +        android:visibility="gone" />
do you not need a margin between the prefix and the question iteself?

2021-03-17 11:17 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_date_picker_view.xml
> +            android:layout_marginEnd="@dimen/item_margin_horizontal" />
shouldn't these be on the linear layout

2021-03-17 11:24 UTC, MuhammadSalman-7214 commented on datacapture/src/main/res/layout/questionnaire_item_check_box_view.xml
> +        android:visibility="gone" />
yes, otherwise we can't be able to differentiate, and it doesn't look too good either

2021-03-17 11:24 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +        if (questionnaireItemViewItem.questionnaireItem.prefix.toString().isNotEmpty()) {
okay

2021-03-17 11:24 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +      private lateinit var prefix: TextView
okay

2021-03-17 11:25 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +        prefix = itemView.findViewById(R.id.prefix)
okay

2021-03-17 11:25 UTC, MuhammadSalman-7214 commented on datacapture/src/main/res/layout/questionnaire_item_date_picker_view.xml
> +            android:layout_marginEnd="@dimen/item_margin_horizontal" />
they are there as well, but it is there to add some margin between prefix and question

2021-03-17 16:43 UTC, jingtang10 commented
With #334 merged, please rebase/merge and run `./gradlew sA` to format your XML files. Also see https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-style.

2021-03-19 14:54 UTC, jingtang10 requested changes
thanks @MuhammadSalman-7214! can you add a screenshot just so we can see what it looks like now? (i think the my pain questionnaire has some prefixes in it).

you'll need to update the tests (my comments in the first file applies to all test files).

2021-03-19 14:54 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +    assertThat(!viewHolder.itemView.findViewById<TextView>(R.id.prefix).isVisible)
this isn't complete. it's not asserting anything. it should be `assertThat(...).isFalse()`.

2021-03-19 14:54 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +  fun shouldNotSetPrefixText() {
```suggestion
  fun shouldHidePrefixText() {
```

2021-03-19 14:54 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.prefix).text).isEqualTo("Prefix?")
also assert on visibility

2021-03-19 14:54 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetPrefixText() {
```suggestion
  fun shouldShowPrefixText() {
```

2021-03-19 15:22 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +    assertThat(!viewHolder.itemView.findViewById<TextView>(R.id.prefix).isVisible)
okay sure

2021-03-19 15:23 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +    assertThat(viewHolder.itemView.findViewById<TextView>(R.id.prefix).text).isEqualTo("Prefix?")
okay

2021-03-19 15:23 UTC, MuhammadSalman-7214 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactoryInstrumentedTest.kt
> +  fun shouldSetPrefixText() {
okay

2021-03-22 08:15 UTC, MuhammadSalman-7214 commented
![Screenshot_1616400912](https://user-images.githubusercontent.com/64642723/111959753-afcb3580-8b10-11eb-80be-4363ea7de82a.png)
Please find attached @jingtang10

2021-03-22 09:34 UTC, jingtang10 approved these changes
Looks good. Thanks @MuhammadSalman-7214 🎉

2021-03-22 09:49 UTC, merged

2021-03-22 09:50 UTC, MuhammadSalman-7214 commented
> Looks good. Thanks @MuhammadSalman-7214

your welcome @jingtang10 :+1: