capitalize replaced
google/android-fhir pull request #345
Opened 2021-03-19 04:09 UTC by Manikant25

solves #340

2021-03-19 11:51 UTC, jingtang10 commented
please see my comment in the linked issue.

2021-03-19 12:07 UTC, jingtang10 submitted a review, later dismissed

2021-03-19 12:07 UTC, jingtang10 commented
thanks for the pr.

2021-03-19 14:35 UTC, epicadk requested changes

2021-03-19 14:35 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
Lint checks are failing because of the wildcard import.

2021-03-19 14:55 UTC, Manikant25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
@epicadk Thanks for informing me

2021-03-19 14:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
Please see https://github.com/google/android-fhir/wiki/Developer's-Guide

2021-03-19 16:09 UTC, Manikant25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
@jingtang10  @epicadk  I followed this guide as shown in the below screenshot then also import is not resolved.
Can you give any suggestions?
[Setting Screenshot](https://github.com/Manikant25/Keep-Notes/blob/master/Screenshot%20(538).png)

2021-03-19 16:12 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
Just change the line to 
   
    import java.util.Locale

2021-03-19 16:14 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
you need to remove those rules in `packages to use import with *`

2021-03-19 16:21 UTC, Manikant25 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +import java.util.*
@epicadk Thankyou

2021-03-22 17:59 UTC, jingtang10 requested changes
please update once done. thanks!

2021-03-22 19:54 UTC, jingtang10 commented
you'll also need to rebase / merge to pull in the latest change from master.

2021-03-22 20:09 UTC, Manikant25 commented
Apologies for the delay, I just close this  PR as this branch has got messed up. I will send another.
Thanks

2021-03-22 20:09 UTC, closed without merging

2021-03-22 20:20 UTC, s-ayush2903 commented
@Manikant25 Btw, you just needed to pull from master branch of this repo and push it to your fork, it would've reflected here. Also if you anytime find yourself stuck with spotless check then you can run `./gradlew spotlessApply` and then commit the changes to push here. If `./gradlew spotlessApply` gives some violations or reports some problem about your jdk version then you can, use `run anything`(usually triggered via `Double Ctrl`) and type in `gradle spotlessApply` or `gradle sA` and hit enter, then spotless will run and fix everything, you'll just need to add and commit the changes. 

PS: If you're unable to trigger `run anything` via double Ctrl key, then you can press `Shift` two times to open a search pane and then type `run anything`, it'll find it for you and then you'll need to type the cmd mentioned above and wait

2021-03-22 20:29 UTC, Manikant25 commented
Thankyou @s-ayush2903, I will keep this in mind.