chore: Chore issue template added
google/android-fhir pull request #352
Opened 2021-03-19 16:38 UTC by Ana2k

fixes: #350 

Chore.md file has been added inside issue template to show chore option while creating issues.

2021-03-22 08:16 UTC, jingtang10 commented
@Ana2k thanks for your PR! In the future please discuss with admins and code owners in the issue before raising PRs like this that change the processes.

@mberg @fredhersch @pld fyi.

2021-03-22 19:20 UTC, Ana2k commented
> @Ana2k thanks for your PR! In the future please discuss with admins and code owners in the issue before raising PRs like this that change the processes.
> 
> @mberg @fredhersch @pld fyi.

@jingtang10 thanks for the heads up. I will keep this in mind from now on.

2021-03-26 11:00 UTC, Ana2k commented
@jingtang10 I have implemented the changes on this as requested. 
Please review it.

2021-03-26 16:47 UTC, jingtang10 requested changes
While you're at it, can you add the `labels` field to the two existing templates too? They shoould be `bug` and `enhancement`. Thanks!

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/code_health.md
> +about: Issues related to Refactoring, Improving Testing, Infrastructure, Documentation or related.
```suggestion
about: Code refactoring, testing infrastructure, documentation, etc.
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/code_health.md
> +name:  Code-Health
```suggestion
name:  Code health
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/process.md
> +about: Issues related to builds and releases, communications, templates etc.
```suggestion
about: Builds, releases, communications, etc.
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/research.md
> +about: Issues related to creation and managing of research tasks. Includes background, goal, and methodology.
```suggestion
about: Research tasks
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/research.md
> +<!--Please state here specifics of what you want to do.-->
```
**Describe the issue to be researched**
Include any background information and available resources.

**Describe the goal of the research**
What's the desired outcome of this task? What artifacts should be produced?

**Describe the methodology**
What information is available for the research? Where can more information be found? Who should the assignee approach to ask questions?
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/code_health.md
> +<!--Please state if this issue should be assigned to you or who you think could help to solve this issue.-->
```suggestion
**Describe the issue**

**Would you like to work on the issue?**

```

and below for the other two templates.

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/code_health.md
> +
add a row
```
labels: 'code health'
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/process.md
> +
add a row
```
labels: 'process'
```

2021-03-26 16:47 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/research.md
> +
add a row
```
labels: research
```

2021-03-27 09:46 UTC, Ana2k commented
@jingtang10 i have implemented the changes. Please review them. Thanks!

2021-03-27 12:06 UTC, jingtang10 approved these changes
Thanks! 👍 
just one little nit.

2021-03-27 12:06 UTC, jingtang10 commented on .github/ISSUE_TEMPLATE/research.md
> +What information is available for the research? Where can more information be found? Who should the assignee approach to ask questions?
tweak this a little:

```suggestion
Where can more information be found? Who should the assignee approach to ask questions? How can a decision be made?
```

thanks!

2021-03-29 22:23 UTC, merged