remove jcenter
google/android-fhir pull request #357
Opened 2021-03-20 04:48 UTC by epicadk

Thanks to [Coolmind](https://stackoverflow.com/questions/49573157/android-studio-3-1-could-not-find-org-jetbrains-trove4jtrove4j20160824)

2021-03-22 07:55 UTC, epicadk commented
Not exactly sure why the upload is failing. I will look into it.

2021-03-23 21:01 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +    </remote-repository>
do you actually need this?

2021-03-23 21:01 UTC, jingtang10 commented on build.gradle
> +        gradlePluginPortal()
have you tested without this? which artifact do you need this for?

2021-03-23 21:01 UTC, jingtang10 commented on build.gradle
> +        gradlePluginPortal()
and this?

2021-03-23 21:02 UTC, jingtang10 commented
Thanks for the fix! A few comments.

2021-03-23 21:02 UTC, jingtang10 requested changes
please see comments.

2021-03-24 05:13 UTC, epicadk commented on build.gradle
> +        gradlePluginPortal()
It's required for this artifact `org.jetbrains.trove4j:trove4j:20160824`

2021-03-24 05:44 UTC, epicadk commented on .idea/jarRepositories.xml
> +    </remote-repository>
Sorry wasn't sure. Removed it.

2021-03-24 08:01 UTC, s-ayush2903 commented
@epicadk Can you please keep this PR intact for some time, as #364 is almost to finish and if this'll get merged then there'll be a ton of conflicts to resolve as the aforementioned PR has so many changes :pleading_face:

2021-03-24 08:14 UTC, epicadk commented on build.gradle
> +        gradlePluginPortal()
same as above.

2021-03-24 08:53 UTC, jingtang10 approved these changes
Thanks for this fix! 👍

2021-03-24 10:25 UTC, merged