Create index for near,location
google/android-fhir pull request #365
Opened 2021-03-22 08:38 UTC by epicadk

#293

2021-03-24 00:10 UTC, jingtang10 requested changes
Thanks very much for this. Great job figurin this out!

Please update the title of the PR, e.g., Create new index table for location (longitude+latitude pair)

2021-03-24 00:10 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/entities/PositionIndex.kt
> +  val path: String,
i guess you don't need these two actually since they are going to be the same for every record

2021-03-24 00:10 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/entities/PositionIndex.kt
> +  val longitude: BigDecimal
With the knowledge that latitude and longitude are bounded to a small range, can we just use double here?

2021-03-24 23:58 UTC, jingtang10 requested changes

2021-03-24 23:58 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +          // TODO: Handle composite type https://github.com/google/android-fhir/issues/292.
just move this todo to after the next line

2021-03-24 23:58 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/entities/PositionIndex.kt
> + * @property [longitude] the longitude
remove these documentations that are not providing any additional information than the code itself.

2021-03-28 14:17 UTC, epicadk commented
@jingtang10 done with the changes. Can you review it again?

2021-03-28 17:00 UTC, jingtang10 approved these changes
Thanks for this @epicadk! Good job 🎉

2021-03-28 17:32 UTC, merged