Nested items should be tied to the answer of the parent item if the parent item is not of type GROUP
google/android-fhir pull request #378
Opened 2021-03-23 13:11 UTC by joiskash

**Fixes**: 
#274

**Description:**
This pull request makes sure that the questionnaire response being generated follows the FHIR specification . More details can be found in issue #274 

**Type**
- Bug fix

**Screenshots (if applicable)**

2021-03-28 22:05 UTC, jingtang10 requested changes
Thansk @joiskash for this PR!

Are you handling repeated answers in this PR?

I think one big assumption that is no longer true with this approach taken by the standard to nest of quesions in answers is that we cannot uniquely identify a questionnaire item using link ID any more... nested questionnaire items might share the same link ID. So this immediately raises the problem when we're updating answers the callback needs to contain more information.

So if you're handing repeated answers in this PR, maybe the first thing to do would be to make `QuestionnaireItemViewItem` contain a chain of IDs to help identify the questionnaire item.

If you're not handling repeated answers, you can probably reuse `linkIdToQuestionnaireItemMap`.

2021-03-29 09:51 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireItemViewItemProperty.canModifyStructure = true
The idea was to create a class which contains properties of the viewItem. for example: read only, can modify structure etc

2021-03-29 09:58 UTC, joiskash commented
> 
> 
> Thansk @joiskash for this PR!
> 
> Are you handling repeated answers in this PR?
> 
> I think one big assumption that is no longer true with this approach taken by the standard to nest of quesions in answers is that we cannot uniquely identify a questionnaire item using link ID any more... nested questionnaire items might share the same link ID. So this immediately raises the problem when we're updating answers the callback needs to contain more information.
> 
> So if you're handing repeated answers in this PR, maybe the first thing to do would be to make `QuestionnaireItemViewItem` contain a chain of IDs to help identify the questionnaire item.
> 
> If you're not handling repeated answers, you can probably reuse `linkIdToQuestionnaireItemMap`.

I do not completely understand this. Questionnaire item and Questionnaire response item still have unique linkIds that map them to each other. An answer cannot exist without a parent item. Maybe I do not understand what it is that you are trying to say.

I had not planned to handle repeated items in this PR but I can. Considering a lot of these changes assume that there is only one answer.

2021-03-29 10:04 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireItemViewItemProperty.canModifyStructure = true
Remember the conversation we had about read only mode? That there should be a way to add more properties to questionnaire item and not pass it as paramter

2021-03-29 11:24 UTC, jingtang10 commented
> > Thansk @joiskash for this PR!
> > Are you handling repeated answers in this PR?
> > I think one big assumption that is no longer true with this approach taken by the standard to nest of quesions in answers is that we cannot uniquely identify a questionnaire item using link ID any more... nested questionnaire items might share the same link ID. So this immediately raises the problem when we're updating answers the callback needs to contain more information.
> > So if you're handing repeated answers in this PR, maybe the first thing to do would be to make `QuestionnaireItemViewItem` contain a chain of IDs to help identify the questionnaire item.
> > If you're not handling repeated answers, you can probably reuse `linkIdToQuestionnaireItemMap`.
> 
> I do not completely understand this. Questionnaire item and Questionnaire response item still have unique linkIds that map them to each other. An answer cannot exist without a parent item. Maybe I do not understand what it is that you are trying to say.
> 
> I had not planned to handle repeated items in this PR but I can. Considering a lot of these changes assume that there is only one answer.

Suppose we have a question `parent` with a child question `child`. And in the questionnaire response there are two answers to this question `parent`, and within each answer there is one answer to the respective `child`. So while there is only one questionnaire response item component with the link ID `parent`, there would actually be two questionnarie response item components with teh link ID `child`. This is the problem I was trying to describe.

If you're not handling repeated items in this PR it's ok. I can take another look.

2021-03-29 14:37 UTC, joiskash commented
ok yea i understand what you are saying. I am happy to work on repeated answers too in this PR,

2021-03-29 21:49 UTC, jingtang10 commented
> Well according to the standard, answers don't repeat, repeat is the property of an item. So if `parent` has repeat == true then there will be 2 items in the questionnaire response with linkid `parent` each having their item `child` within `parent.answer`. I am happy to work on repeated answers too in this PR,

That's different from my understanding. If you look at the cardinality of `answer` in this page: https://www.hl7.org/fhir/questionnaireresponse.html it's marked `0..*`. In the HAPI structures API the answer is a list as well.

I thought that's the conclusion of the discussion we had on the fhir chat.

But I don't think this changes my overall point that link id in the questionnaire response is no longer unqiue.

I don't mind if you want to work on repeated items in a follow-up. Up to you :)

2021-03-30 06:04 UTC, joiskash commented
> 
> 
> > Well according to the standard, answers don't repeat, repeat is the property of an item. So if `parent` has repeat == true then there will be 2 items in the questionnaire response with linkid `parent` each having their item `child` within `parent.answer`. I am happy to work on repeated answers too in this PR,
> 
> That's different from my understanding. If you look at the cardinality of `answer` in this page: https://www.hl7.org/fhir/questionnaireresponse.html it's marked `0..*`. In the HAPI structures API the answer is a list as well.
> 
> I thought that's the conclusion of the discussion we had on the fhir chat.
> 
> But I don't think this changes my overall point that link id in the questionnaire response is no longer unqiue.
> 
> I don't mind if you want to work on repeated items in a follow-up. Up to you :)

Ok yes you are right. Sorry, it always confuses me cause there is no clear body of text that explains this explicitly. I will handle repeated items in a follow-up. I do not wont to have two big changes in one PR.

2021-03-30 09:59 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireItemViewItemProperty.canModifyStructure = true
@jingtang10 do you still feel this should not be a separate class?

2021-03-31 11:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      validateQuestionniareResponseItems(questionnaire.item, questionnaireResponse.item)
done

2021-03-31 11:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    questionnaireItemViewItemProperty.canModifyStructure = true
done

2021-03-31 11:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private fun validateQuestionniareResponseItems(
done

2021-03-31 11:08 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +  val questionnaireItemViewItemProperty: QuestionnaireItemViewItemProperty
done

2021-03-31 11:09 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItemProperty.kt
> +class QuestionnaireItemViewItemProperty() {
done

2021-04-03 10:30 UTC, jingtang10 requested changes

2021-04-03 10:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +          }
can this just be inside `questionnaireResponseItemChangedCallback`?

2021-04-03 10:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
why not use `linkIdToQuestionnaireItemMap`?

2021-04-03 10:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var questionnaireItemBeingSearched: Questionnaire.QuestionnaireItemComponent? = null
this seems to be an intermediary result during an operation. why not pass the result to the next stage of the operation rather than creating this as a field? doesn't seem to be thread-safe.

2021-04-03 10:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
Seems like you can use `linkIdToQuestionnaireResponseItemMap`?

2021-04-05 05:47 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
yes thanks!

2021-04-05 05:47 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private var questionnaireItemBeingSearched: Questionnaire.QuestionnaireItemComponent? = null
done

2021-04-05 05:47 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
yes thanks!

2021-04-05 05:47 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +          }
done

2021-04-05 05:49 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private val questionnaireResponseItemAnsweredCallback: (String) -> Unit = { linkId ->
Yup i used the existing callback

2021-04-05 05:49 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +   * [Questionnaire.QuestionnaireItemComponent] answered
removed it. was not needed

2021-04-07 19:27 UTC, jingtang10 requested changes

2021-04-07 19:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          )
```suggestion
          questionnaireItemViewItemList.addAll(
            getQuestionnaireItemViewItemList(
              questionnaireItem.item, 
              if (questionnaireResponseItem.answer.isEmpty()) {
                questionnaireResponseItem.item
              } else {
                questionnaireResponseItem.answer.first().item
              }
            )
```

2021-04-07 19:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (this.answer.isNotEmpty()) {
can you reuse `addNestedItemsToAnswer` here?

2021-04-08 13:12 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
ok sure 👍🏼

2021-04-08 13:24 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
thats right 👍🏼 fixed it

2021-04-08 13:26 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          )
done

2021-04-08 13:32 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (this.answer.isNotEmpty()) {
it is a private function that is part of the class. `addNestedItemsToAnswer ` uses `linkIdToQuestionnaireItemMap` which is a member variable of the class. `createQuestionnaireResponseItem` is outside the class . Any suggestion as to what I should do?

2021-04-08 13:52 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (this.answer.isNotEmpty()) {
ok I have done some changes to reuse addNestedItemsToAnswer. You can review it in code review

2021-04-12 17:14 UTC, jingtang10 requested changes

2021-04-13 12:12 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        this@createQuestionnaireResponseItem.item.count() > 0
done

2021-04-13 12:12 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  questionnaireItemComponent: Questionnaire.QuestionnaireItemComponent?
done

2021-04-13 12:19 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private fun Questionnaire.QuestionnaireItemComponent.createListOfItemInAnswer():
Im not sure how to do this

2021-04-13 12:19 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  this.apply {
yes you are right, done

2021-04-13 12:19 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    answer = answer
done

2021-04-13 13:04 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +            questionnaireItemViewItem.questionnaireItem.linkId
done

2021-04-19 16:38 UTC, jingtang10 submitted a review, later dismissed
sorry for the delay... the PR status was still `Changes requested`... I don't know why.

2021-04-19 16:38 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private fun Questionnaire.QuestionnaireItemComponent.createListOfItemInAnswer():
ok i don't see this done? i'm fine if you want to keep this function. i think it's fine.

2021-04-19 16:38 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>      }
What I mean here is this:

```suggestion
    if (answer.isNotEmpty() && hasNestedItemsWithinAnswers) {
        this.addNestedItemsToAnswer(this@createQuestionnaireResponseItem)
    }
    if (hasNestedItemsWithinItems) {
      this@createQuestionnaireResponseItem.item.forEach {
        this.addItem(it.createQuestionnaireResponseItem())
      }
    }
```

and then add 

```
val Questionnaire.QuestionnaireItemComponent.hasNestedItemsWithinItems: Boolean
  get() = item.isNotEmpty() && type == Questionnaire.QuestionnaireItemType.GROUP
```

in `MoreQuestionnaireItemOptions.kt`

I think the conditional block seems more logical. What do you think?

2021-04-20 05:02 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>      }
oh thats weird.. i think you reviewed an older version of the file if you check the [branch](https://github.com/google/android-fhir/tree/kj/sdc-nested-item-in-answer), you will see that this is already done..

2021-04-20 05:03 UTC, joiskash commented
Let me know if you cannot still see the changes.. I just pulled onto my local machine and see that it is updated with all the changes that I had committed last time..not sure why you are seeing an older version of the branch

2021-04-23 05:01 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private fun Questionnaire.QuestionnaireItemComponent.createListOfItemInAnswer():
It is done.. Im not sure why you are not saying the changes. And I have re-requested review but it still says changes requested..

2021-04-23 05:03 UTC, joiskash commented
> 
> 
> sorry for the delay... the PR status was still `Changes requested`... I don't know why.

Yea it still says changes requested.. and for some reason your review was done on an old file

2021-05-04 12:22 UTC, jingtang10 requested changes

2021-05-04 12:22 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private inline val Questionnaire.QuestionnaireItemComponent.listOfItemInAnswer:
i think if you're generating a new list, it probably shouldn't be a property. i would make this a function.

2021-05-04 13:05 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private inline val Questionnaire.QuestionnaireItemComponent.listOfItemInAnswer:
done

2021-05-04 13:16 UTC, jingtang10 approved these changes
Thanks Kashyap! 👍

2021-05-04 13:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
nit: remove new line

2021-05-04 13:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +}
optional:
```suggestion
private inline fun Questionnaire.QuestionnaireItemComponent.listOfItemInAnswer = item.map { it.createQuestionnaireResponseItem() }.toList()
```

2021-05-04 13:21 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +
done :)

2021-05-04 13:52 UTC, merged