separate integration tests and unit tests
google/android-fhir pull request #387
Opened 2021-03-24 09:23 UTC by epicadk

**Fixes**: #282

**Description:**
Clear and concise code change description. 

**Type**
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Builds
- [ ] Releases
- [ ] Other (please specify)

**Screenshots (if applicable)**

2021-04-03 22:11 UTC, jingtang10 commented
is there any update on this one? thanks!

2021-04-03 22:12 UTC, jingtang10 commented
please make sure @deepankarb also has a chance to review once done. thanks!

2021-04-04 03:47 UTC, epicadk commented
> is there any update on this one? thanks!

Sorry for the delay. Will be done within a day.

2021-04-04 18:25 UTC, epicadk commented
Sorry something urgent came up. I've completed adding unit tests. Will finish integration tests soon.

2021-04-05 08:51 UTC, epicadk commented
I need to place the integration tests in a different folder. I was thinking I can create a separate directory for unit tests and integration tests under the test directory. Any suggestions?

2021-04-05 18:26 UTC, epicadk commented
I've also added some tests in #332 for the date types. I've covered all cases except the integer case of the number index. I can't seem to find a resource that uses a search parameter of that type.  Even the example given on the specification website doesn't work.

2021-04-12 18:19 UTC, jingtang10 requested changes
It might be ok to keep everything in the same file, but you should have two classes of test cases

1. cases that test specific code paths e.g. `string_empty_shouldIndexNothing` or `int_shouldCreateIndex` etc etc. We would use minimally constructed resources to test specific types.
2. cases where we use more complex resources and assert that all indecies that should be created are created.

I think these two classes of tests can probably co-exist in the same file if named sensibly.

2021-04-12 18:19 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/ResourceIndexerTest.kt
> +/*
I don't think it's right to create another file in this package. This should be in the same directory as the other file.

2021-04-13 19:50 UTC, epicadk commented on core/src/test/java/com/google/android/fhir/ResourceIndexerTest.kt
> +/*
> I don't think it's right to create another file in this package. This should be in the same directory as the other file.

Reverted this change

2021-04-13 19:52 UTC, epicadk commented
I've kept the order similar as they occur in the resource indexer. I've also included tests for null and empty values wherever possible.

2021-04-19 16:49 UTC, jingtang10 requested changes
A couple of high-level comments. Please address! Thanks!

2021-04-19 16:49 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  /** Integration tests for ResourceIndexer. */
can you move the 'integration' tests after the 'unit' tests?

2021-04-19 16:49 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_Patient_shouldIndexLastUpdatedDate() {
the point of these unit test cases is to cover all code paths so i think they need to be re-organized by index type, and please rename them, e.g.:

```
fun index_string_null
fun index_string
...

fun date_period_someCondition
fun date_period_someOtherCondition
...
```

2021-04-20 07:28 UTC, epicadk commented
Noticed a bug in the date indexer while testing so I made the corresponding change. The value to should be inclusive (makes querying easier using the SQL between operator.)

2021-05-04 12:35 UTC, jingtang10 commented
@epicadk did you remove all the other changes in the test class you made?

2021-05-04 15:26 UTC, epicadk commented
> @epicadk did you remove all the other changes in the test class you made?

Yup all of the tests are in the same file and I've renamed the tests as requested [here](https://github.com/google/android-fhir/pull/387#discussion_r616014331). I've also updated the pr description to explain the changes I have made.

2021-05-06 10:02 UTC, jingtang10 requested changes
@epicadk Really happy with this - this is a very good PR! Thank you so much for this!

Apologies for the delay in reviewing. Please let me know once you're done with the few small comments I made.

2021-05-06 10:02 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
>        .contains(
```suggestion
      .containsExactly(
```

2021-05-06 11:46 UTC, epicadk commented
@jingtang10 divided the tests in 3 parts.

1.  The creation of resources 
2. Actual code for indexing
3. assertions

2021-05-06 15:03 UTC, jingtang10 approved these changes
Great! Thanks!

2021-05-06 15:03 UTC, merged