Initial Values Pre Filled Functionality Added
google/android-fhir pull request #393
Opened 2021-03-26 12:34 UTC by MuhammadSalman-7214

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

**Fixes** #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-03-26 12:37 UTC, MuhammadSalman-7214 commented
![Screenshot_1616762185](https://user-images.githubusercontent.com/64642723/112632339-d1eaed80-8e59-11eb-86a5-9c8cd8c7939d.png)
Attached is a screenshot example of prefilled values.

2021-03-26 16:25 UTC, jingtang10 requested changes
Please fill out the PR template.

2021-03-27 11:15 UTC, MuhammadSalman-7214 commented
> Please fill out the PR template.

Sorry haven't understood you, can you please explain?

2021-03-27 11:18 UTC, s-ayush2903 commented
@MuhammadSalman-7214 You were asked to fill the details required in this PR's description, i.e., here: https://github.com/google/android-fhir/pull/393#issue-601583545

2021-03-27 11:20 UTC, MuhammadSalman-7214 commented
okay thanks @s-ayush2903

2021-03-27 11:22 UTC, MuhammadSalman-7214 commented
Filled the PR template @jingtang10. thanks

2021-03-27 11:26 UTC, s-ayush2903 commented
Nope, it is still incomplete, the main motto of the template is to close the related issue automatically as soon as the PR is merged(if issue isn't linked then it'll need to be closed manually, which isn't desired and consumes time), so to make that(automatic issue closing) we have to link the issue in PR description via writing `Fixes #issue_number`. Also everyone is supposed to fill the template in as much detail as possible to make reviewing process easy, fast and smooth. You may look for reference here: https://github.com/google/android-fhir/pull/395#issue-601958498

2021-03-27 12:59 UTC, MuhammadSalman-7214 commented
@s-ayush2903 is everything okay now?

2021-03-27 17:11 UTC, jingtang10 commented
@MuhammadSalman-7214 please read carefully through the PR template and fill it out.

Thanks.

2021-03-29 06:42 UTC, MuhammadSalman-7214 commented
> @MuhammadSalman-7214 please read carefully through the PR template and fill it out.
> 
> Thanks.

@jingtang10 done, thanks

2021-03-29 11:46 UTC, jingtang10 commented
So here the approach you have taken is to populate the inital values in the UI. The problem is that you haven't actually saved these values in the data mdoel - so if the user save the questionnaire without touching the initial values the generated questionnarie response will not be the same as what's displayed.

You need to either fix this by actually populating the initial values, or generate questionnaire response items using the initial values in the questionnaire view model.

2021-03-29 11:47 UTC, jingtang10 requested changes
please address comment above.

2021-03-29 11:52 UTC, MuhammadSalman-7214 commented
okay

2021-03-29 14:30 UTC, MuhammadSalman-7214 commented
> So here the approach you have taken is to populate the inital values in the UI. The problem is that you haven't actually saved these values in the data mdoel - so if the user save the questionnaire without touching the initial values the generated questionnarie response will not be the same as what's displayed.
> 
> You need to either fix this by actually populating the initial values, or generate questionnaire response items using the initial values in the questionnaire view model.

@jingtang10 the requested comment has been handled, thanks

2021-03-29 18:58 UTC, jingtang10 commented
@joiskash can you take a look please if you have time? Thanks!

2021-03-29 21:53 UTC, jingtang10 commented
@MuhammadSalman-7214 out of the two approaches I outlined, why did you pick the former not the latter? did you consider which one is better?

thanks!

2021-03-30 06:23 UTC, joiskash requested changes
I think you need to add this for the remaining view holder factories too, Date, DateTime, Slider. And then some unit tests. I have put some comments please address them. Thank you!

2021-03-30 06:23 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +        "integer" -> {
Use `QuestionnaireItemType.INTEGER` instead of hard coded value 'integer'. You can refer to QuestionnaireItemAdapter class . Do the same for all the other cases

2021-03-30 06:23 UTC, joiskash commented on datacapturegallery/src/main/assets/iprd-hiv-fhir-questionnaire-initial.json
> +                "initial": [
Initial value is already set here. So revert all changes to this questionnaire. We can check with this value itself to see if the feature is working.

2021-03-30 06:23 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +          QuestionnaireListItem(
Remove this item. As mentioned above we can just use the existing questionnaire iprd-hiv-fhir-questionnaire.json. Items with link id 11.2.* have initial values already

2021-03-30 06:59 UTC, jingtang10 commented
@joiskash do you think it's better to handle initial values in view holders or in the view model?

2021-03-30 07:08 UTC, MuhammadSalman-7214 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +          QuestionnaireListItem(
@joiskash the existing questionnaire iprd-hiv-fhir-questionnaire.json. Items with link id 11.2 have initial value for edit text only, whereas we want to test it for check boxes, radio buttons, drop downs as well, so have to add to test all those changes

2021-03-30 07:11 UTC, MuhammadSalman-7214 commented on datacapturegallery/src/main/assets/iprd-hiv-fhir-questionnaire-initial.json
> +                "initial": [
@joiskash sure I can remove for edit text as it it already present in one file, but I have added it because to test all the changes in one file for initial values. This initial value json file has all the changes for us to test in one place

2021-03-30 07:12 UTC, MuhammadSalman-7214 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +          QuestionnaireListItem(
also @jingtang10 mentioned, I should add a new json file, rather than changing any old json file, so I have added a new json file, and have to add this as well then

2021-03-30 07:14 UTC, MuhammadSalman-7214 commented
> @MuhammadSalman-7214 out of the two approaches I outlined, why did you pick the former not the latter? did you consider which one is better?
> 
> thanks!

@jingtang10 I picked this approach, as the same work was already happening in the factory classes, whereas for Viewmodel, we could have some other changes as well, so I have gone with the same flow that we already are following and tested, everything is working fine

2021-03-30 07:15 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +        "integer" -> {
okay

2021-03-30 07:15 UTC, MuhammadSalman-7214 commented on datacapturegallery/src/main/assets/iprd-hiv-fhir-questionnaire-initial.json
> +                "initial": [
and I don't think there is any problem, if we can test it on two places

2021-03-30 07:58 UTC, jingtang10 commented
> 
> 
> 
> > @MuhammadSalman-7214 out of the two approaches I outlined, why did you pick the former not the latter? did you consider which one is better?
> > 
> > thanks!
> 
> @jingtang10 I picked this approach, as the same work was already happening in the factory classes, whereas for Viewmodel, we could have some other changes as well, so I have gone with the same flow that we already are following and tested, everything is working fine

Wouldn't you ultimately end up doing more work changing every single view holder rather than just the view model?

2021-03-30 09:20 UTC, MuhammadSalman-7214 commented
@jingtang10 what changes would be made in the QuestionnareViewModel Class if we take this approach then rather than each factory class?

2021-03-30 09:48 UTC, joiskash commented
> 
> 
> @jingtang10 what changes would be made in the QuestionnareViewModel Class if we take this approach then rather than each factory class?

Ok so if you see in each view holder factory if the questionnaireResponseItem has an answer, then it will populate the UI with the answer. So @jingtang10 is suggesting that in the view model `Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem()` can be used to set the answer with the initial value from the questionnaireItem. That way you make a change only in one place.

2021-03-30 09:56 UTC, MuhammadSalman-7214 commented
> > @jingtang10 what changes would be made in the QuestionnareViewModel Class if we take this approach then rather than each factory class?
> 
> Ok so if you see in each view holder factory if the questionnaireResponseItem has an answer, then it will populate the UI with the answer. So @jingtang10 is suggesting that in the function `Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem()` you can set the answer with the initial value from the questionnaireItem. That way you make a change only in one place.
> 
> You can go through the view model in detail and see if there is a better place to do this. Put your comments here so we can discuss before you code it.

okay @joiskash. Checking the code of ViewModel

2021-03-30 09:57 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +          QuestionnaireListItem(
ok cool thats sounds good to me

2021-03-30 10:27 UTC, MuhammadSalman-7214 commented
@joiskash I have checked the code of ViewModel and in the class checked the Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem() function. I have some questions regarding this approach
1. We have initial value available here for every question, but how will we set that initial value to each questionaire response  or that specific question response in the ViewModel?
2. We have different kind of answers for every question like, checkbox can be checked or unchecked (Boolean Type), Drop down can have one selection, also radio buttons and edit texts the criteria is different, how will handle all these type of question answers in ViewModel?
Thanks

2021-03-30 12:51 UTC, joiskash commented
> 
> 
> @joiskash I have checked the code of ViewModel and in the class checked the Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem() function. I have some questions regarding this approach
> 
>     1. We have initial value available here for every question, but how will we set that initial value to each questionaire response  or that specific question response in the ViewModel like which paramter will we use for example when we want to set linkId, we are setting it using linkId parameter, but how will we set it to QuestionnaireResponse?
> 
>     2. We have different kind of answers for every question like, checkbox can be checked or unchecked (Boolean Type), Drop down can have one selection, also radio buttons and edit texts the criteria is different, how will handle all these type of question answers in ViewModel?
>        Thanks

1.  The function `createQuestionnaireResponseItem` is being called by each item in the questionnaire item. Look at line number 62. So just like how we set the linkId on line 257 you will have to do something like

`    answer = mutableListOf<QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent>(
        QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
          value = this@createQuestionnaireResponseItem.initial[0].value
        }
      ) `

2021-03-30 14:57 UTC, MuhammadSalman-7214 commented
Thanks @joiskash, the ViewModel approach looks better than changing each factory class, and I think this should be our approach, right @jingtang10 ?

2021-03-30 22:57 UTC, jingtang10 commented
> Thanks @joiskash, the ViewModel approach looks better than changing each factory class, and I think this should be our approach, right @jingtang10 ?

Sure, sounds good.

2021-03-31 04:56 UTC, MuhammadSalman-7214 commented
> > Thanks @joiskash, the ViewModel approach looks better than changing each factory class, and I think this should be our approach, right @jingtang10 ?
> 
> Sure, sounds good.

great. Let me update the PR

2021-03-31 06:00 UTC, joiskash requested changes

2021-03-31 06:27 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
> +        val initialValue = questionnaireItemViewItem.questionnaireItem.initial
yes, you are right, updated the PR again. Thanks

2021-03-31 11:37 UTC, joiskash commented
Yes in the veiw model test class

2021-03-31 12:14 UTC, MuhammadSalman-7214 commented
> Looks good. Add a unit test in the view model to check if for a questionnaire item with initial value, the value is actually set in the UI

@joiskash to check this, should I check the initial value is setting in the Questionnare Response? or should I do something else?

2021-04-01 06:32 UTC, joiskash approved these changes
Just a small nit. Looks good to me :)

2021-04-01 06:34 UTC, joiskash commented
> 
> 
> > Looks good. Add a unit test in the view model to check if for a questionnaire item with initial value, the value is actually set in the UI
> 
> @joiskash to check this, should I check the initial value is setting in the Questionnare Response? or should I do something else?

I have addressed this in the code review. Make sure you make the small change before merging. Thanks!

2021-04-01 06:40 UTC, MuhammadSalman-7214 commented
@joiskash not seeing the nit, can you please tell me about it, thanks.

2021-04-01 06:48 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun hasInitialValue_shouldSetValueInUIAndQuestionResponse() {
Change the name of this test to `questionnaireHasInitialValue_shouldSetAnswerValueInQuestionnaireResponse` . We do not need to check if the value is set in UI because each viewHolder has tests which check if the UI is set to what is present in the QuestionnaireReponse

2021-04-01 06:52 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun hasInitialValue_shouldSetValueInUIAndQuestionResponse() {
okay sure

2021-04-01 06:55 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun hasInitialValue_shouldSetValueInUIAndQuestionResponse() {
Done

2021-04-01 07:25 UTC, merged