[WIP]: Migrating hardcoded-strings
google/android-fhir pull request #398
Opened 2021-03-28 13:00 UTC by Ana2k

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

Fixes #379

**Description**
Migrate user-visible hard-coded string files

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: | Feature | 

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-03-29 12:13 UTC, Manikant25 commented
@Ana2k  Try to run  `./gradlew spotlessApply` and  `./gradlew spotlessCheck`. I think there is a problem in the coding style.

2021-03-30 05:15 UTC, Ana2k commented
> @Ana2k Try to run `./gradlew spotlessApply` and `./gradlew spotlessCheck`. I think there is a problem in the coding style.

@Manikant25 thanks for the advice, its currently WIP(work-in-progress). After I complete making all the changes I will surely. Thanks :)

2021-03-30 09:14 UTC, epicadk commented on reference/src/main/java/com/google/android/fhir/reference/data/SamplePatients.kt
> +      else Resources.getSystem().getString(R.string.no_value_quantity)
You can only access system resources like this not application resources.

2021-03-30 09:16 UTC, epicadk commented
> > @Ana2k Try to run `./gradlew spotlessApply` and `./gradlew spotlessCheck`. I think there is a problem in the coding style.
> 
> @Manikant25 thanks for the advice, its currently WIP(work-in-progress). After I complete making all the changes I will surely. Thanks :)

You can convert it to draft so people will know you are still working on it. No need to add WIP in the title.

2021-03-30 09:58 UTC, Ana2k commented on cqlreference/src/main/java/com/google/android/fhir/cqlreference/CqlLoadActivity.kt
> +            getString(R.string.snackbar_loaded) + resource.resourceType.name + getString(R.string.snackbar_with_Id) + resource.id,
- 

- Please have a look its

> > > @Ana2k Try to run `./gradlew spotlessApply` and `./gradlew spotlessCheck`. I think there is a problem in the coding style.
> > 
> > 
> > @Manikant25 thanks for the advice, its currently WIP(work-in-progress). After I complete making all the changes I will surely. Thanks :)
> 
> You can convert it to draft so people will know you are still working on it. No need to add WIP in the title.

Afaik WIP means Work In Progress, and I feel more comfortable doing this as seen in other open source orgs. Thanks for the suggestion!

2021-03-30 10:01 UTC, Ana2k commented
> > > @Ana2k Try to run `./gradlew spotlessApply` and `./gradlew spotlessCheck`. I think there is a problem in the coding style.
> > 
> > 
> > @Manikant25 thanks for the advice, its currently WIP(work-in-progress). After I complete making all the changes I will surely. Thanks :)
> 
> You can convert it to draft so people will know you are still working on it. No need to add WIP in the title.

Afaik WIP means Work In Progress, and I feel more comfortable doing this as seen in other open source orgs. Thanks for the suggestion!

2021-03-30 10:08 UTC, Ana2k commented
@jingtang10 I have finalised this pr. Please review it.

2021-03-30 10:11 UTC, Ana2k commented on cqlreference/src/main/java/com/google/android/fhir/cqlreference/CqlLoadActivity.kt
> +            getString(R.string.snackbar_loaded) + resource.resourceType.name + getString(R.string.snackbar_with_Id) + resource.id,
Please check now, the pr has been finalised.

2021-03-30 14:36 UTC, epicadk commented
> Afaik WIP means Work In Progress, and I feel more comfortable doing this as seen in other open source orgs. Thanks for the suggestion!

It was suggested by one of the maintainers here. : /  
https://github.com/google/android-fhir/pull/386#issuecomment-805576021

2021-03-31 15:55 UTC, Ana2k commented
> > Afaik WIP means Work In Progress, and I feel more comfortable doing this as seen in other open source orgs. Thanks for the suggestion!
> 
> It was suggested by one of the maintainers here. : /
> [#386 (comment)](https://github.com/google/android-fhir/pull/386#issuecomment-805576021)

Yupp saw it. Thanks! :)

2021-04-03 21:20 UTC, jingtang10 requested changes
1. please don't put exception strings in resource files.
2. please revert all changes in `cqlreference` module since the ui will change.

2021-04-03 21:20 UTC, jingtang10 commented
this is not a feature. this is code health. please update PR type and title.

2021-04-04 11:29 UTC, Ana2k commented
> 2\. all changes in `cqlreference` module since the ui will change.

Snackbar changes?(they are in cqlreference)

2021-04-04 11:39 UTC, Ana2k commented
> 1. please don't put exception strings in resource files.
> 2. please revert all changes in `cqlreference` module since the ui will change.

1. I can turn translatable as false for the exception message.
Then I hope no issue with i10 or i18 translation will be there?
2. Should I revert the Snackbars too?(they are in cqlreference non UI part)

2021-04-13 13:00 UTC, jingtang10 commented
@Ana2k apologies but I'm going to close this because we're going to rewrite the UIs. Thanks again for your contribution!

2021-04-13 13:00 UTC, closed without merging