SpotlessConfig on entire project
google/android-fhir pull request #413
Opened 2021-03-31 12:41 UTC by s-ayush2903

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

Fixes #412 

**Description**
Spotless now runs on entire module irrespective of module depth & surface

**Alternative(s) considered**
Extracted out the common spotless functionality to a file and applied in root gradle file

**Type**
Choose one: (| Code health |)

**Screenshots (if applicable)**
NA

**Checklist**
- [x] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-01 07:32 UTC, s-ayush2903 commented
Set an upper bound on runtime for pipelines so that we don't end up in situations like [this](https://github.com/google/android-fhir/pull/413/checks?check_run_id=2241107660)?

2021-04-03 22:09 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +                name="url"
this seems odd - do you know why the indentation is so big?

2021-04-03 22:09 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
the only effective change that leads to spotless being applied to the whole project is remove the config from `subprojects` block right?

2021-04-03 22:09 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +        "package|import|class|object|sealed|open|interface|abstract "
how come this is needed now?

2021-04-03 22:09 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +      targetExclude("**/generated-sources/**")
why is this change needed?

2021-04-03 22:15 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +        "package|import|class|object|sealed|open|interface|abstract "
Because spotless needs some kind of declaration in the file to find a line before which to apply license-header

https://github.com/diffplug/spotless/issues/135

2021-04-03 22:15 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
Yes

2021-04-03 22:16 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +      targetExclude("**/generated-sources/**")
To not apply spotless on generated build files

2021-04-03 22:20 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
Yes, should it be moved back to gradle file?

2021-04-03 22:32 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +                name="url"
Yeah, that's weird, I didn't pay any attention to it after applying spotless. Let me see

2021-04-03 22:58 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +      targetExclude("**/generated-sources/**")
Ah, its needless 8877df3

2021-04-03 23:16 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +                name="url"
Ah, here comes an interesting fact: when I run spotless after moving this code section to some XML file(that isn't in any "dot directory", like `.idea`), it automatically formats it correctly, but doesn't work when the same patch is in a dot directory. Feels like there's some problem with prettier.

2021-04-06 10:52 UTC, jingtang10 requested changes
Thanks @s-ayush2903 for this. Just a few small comments.

2021-04-06 10:52 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +                name="url"
Can you please file a bug in prettier codebase?

I feel it's probably still better to keep using prettier (as opposed to excluding this file or directory for prettier) -- given that the issue is tracked and prettier will fix this in the future.

2021-04-06 10:52 UTC, jingtang10 commented on buildSrc/build.gradle.kts
> +//  implementation(Plugins.kotlinGradlePlugin)
remove?

2021-04-06 10:52 UTC, jingtang10 commented on buildSrc/build.gradle.kts
> +  implementation("com.diffplug.spotless:spotless-plugin-gradle:5.11.0")
can you use the dependencies?

2021-04-06 10:52 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
no i think this is fine :)

2021-04-06 10:52 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +        "package|import|class|object|sealed|open|interface|abstract "
can you add a comment here to link to that issue?

2021-04-06 12:45 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +                name="url"
https://github.com/prettier/prettier/issues/10657

2021-04-06 13:04 UTC, s-ayush2903 commented on buildSrc/build.gradle.kts
> +  implementation("com.diffplug.spotless:spotless-plugin-gradle:5.11.0")
Turns out we can't do it this simply. When I do it, it tells me an unresolved reference and also tells me to make sure if we are using kotlin-gradle-plugin repo in buildSrc. There should be some fancy workaround for it, but that'll require more effort in comparison to that of putting a simple string(the current case). Should I go ahead for that workaround?

2021-04-06 17:28 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
if you move this back, can you use the dependencies better in the `build.gradle.kts` file rather than using `implementation("com.diffplug.spotless:spotless-plugin-gradle:5.11.0")`? if that's the case please move this back.

2021-04-06 17:28 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +        "package|import|class|object|sealed|open|interface|abstract "
reminder to do this

2021-04-06 17:29 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +                name="url"
hm, so do you think this is a spotless issue? so odd...

2021-04-06 17:32 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +                name="url"
I'm not sure. The scene is:
1. File is exposed (by spotless) to prettier for applying formatting
2.  And prettier ends up formatting it incorrectly.
Quite difficult(to me) to comment where the problem is

2021-04-06 17:34 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +                name="url"
The observation to be made here is that prettier does format it but incorrectly. I manually changed formatting of some section of file and then re-ran spotless, again it ended up formatting file the way it was earlier(i.e., incorrectly).

2021-04-06 17:40 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
Yep, Plugins will be accessible from there. But by doing so, won't we be reducing cohesion?(Just a question out of curiosity, no problem in moving it to gradle file)

2021-04-07 08:35 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
Nope it won't be possible even then : (
I saw junit's project just to see if they've done something this way, they have some workaround, but even then are unable to achieve any dependency via reference in buildSrc level gradle file, I've checked many projects and all of 'em hardcoded deps in buildSrc level gradle file. Maybe it is so difficult to refer deps by `somefile.object.subobject.dep` in buildSrc level gradle file : (

2021-04-07 16:56 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
got it thx.

2021-04-07 17:36 UTC, jingtang10 requested changes
thanks @s-ayush2903 please see comments below

2021-04-07 17:36 UTC, jingtang10 commented on buildSrc/build.gradle.kts
> +  implementation("com.diffplug.spotless:spotless-plugin-gradle:5.11.0")
as i commented above, just move the sptless config back to the top level `build.gradle.kts`

2021-04-07 17:36 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
> Yes, should it be moved back to gradle file?

actually just do this. thx!

2021-04-07 18:31 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
db7dac7 & no offense, does it mean we can sacrifice cohesion over a single string?

2021-04-07 18:37 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +        "package|import|class|object|sealed|open|interface|abstract "
db7dac7

2021-04-07 18:37 UTC, s-ayush2903 commented on buildSrc/build.gradle.kts
> +  implementation("com.diffplug.spotless:spotless-plugin-gradle:5.11.0")
db7dac7

2021-04-07 18:55 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +                name="url"
i've tested locally and i actually got the formatting to work... so i've no idea what's going on here.

2021-04-07 18:58 UTC, jingtang10 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
yeah interesting point. i think it's quite nice to have the dependencies properly referenced. and i don't feel having the format config on the top level gradle being a sacrifice of cohesion -- but do you think the opposite is true?

you can still define a function in the top level gradle file (please do that actually).

2021-04-07 18:59 UTC, jingtang10 commented on build.gradle.kts
> +      targetExclude("**/build/", ".idea/")
can you try remove this and see if you can format the xml file in .idea

2021-04-07 19:02 UTC, s-ayush2903 commented on build.gradle.kts
> +      targetExclude("**/build/", ".idea/")
I was doing the same thing previously, but added it now due to https://github.com/google/android-fhir/runs/2290241853#step:11:49

2021-04-07 19:04 UTC, jingtang10 commented on build.gradle.kts
> +      targetExclude("**/build/", ".idea/")
have you run `./gradlew sA`?

2021-04-07 19:08 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +                name="url"
This astonishes me, as it neither works on my studio nor @_CI

2021-04-07 19:49 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
I think it would've been better to have that functionality separate, as it was just a config spec and gradle file is about applying configs to module(s)(not to define and use there), and over this maybe we could have that specific dep as a raw string with some special comment 

Well, that was my point of view on it, I definitely don't know as much you do, so it may sound stupid to you :sweat_smile:

2021-04-07 19:58 UTC, s-ayush2903 commented
I'm unsure if you're aware of https://github.com/diffplug/spotless/issues/831 or not but you should know that it exists now.

2021-04-07 20:00 UTC, s-ayush2903 commented on build.gradle.kts
> +      targetExclude("**/build/", ".idea/")
Ah no, might've missed it.

2021-04-07 20:01 UTC, s-ayush2903 commented
> if re-including the two directories works that'd be great.

07cf553 & Btw, Any specific reason for exposing the build and (git)ignored files to formatting or we just want to maintain the inertia?

2021-04-07 20:02 UTC, s-ayush2903 commented on buildSrc/src/main/kotlin/SpotlessConfig.kt
> +fun Project.configureSpotless() {
Btw 07cf553

2021-04-07 20:12 UTC, jingtang10 commented
Yeah you're right there's no need to format files nobody edits.

2021-04-07 20:21 UTC, jingtang10 commented
Yeah I think putting the spotless config in the kotlin folder is a reasonable thing :) if you feel that's better please do that and let me know when you're ready for this to be merged.

2021-04-07 21:05 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
What should be the destiny of this file? This entire file is incorrectly formatted, should we just ignore it or reformat it correctly(reformatting to desired spec can be done via [prettier playground](https://prettier.io/playground) easily, if needed) and put it in the shelf. Btw it is now ignored(via spotless) and (hopefully) will never come up again for formatting issues.

2021-04-07 21:22 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
just format it in android studio i think that's enough

2021-04-07 21:23 UTC, jingtang10 commented on .idea/jarRepositories.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
or prettier playground

2021-04-07 23:19 UTC, s-ayush2903 commented on .idea/jarRepositories.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
0ea1030  & [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgJwgKzmGAAgDc5MBnAS2gF4AdEAFgYD46pDDVIBbdaBESgBDHnHogASnB4R40-lRgRMlOOQDC0AGaUA5gFdMwmNSit2nTqkwy5cALS3FlZZgCebDlesR0p6EIRMQlKABMGEmEAGwNxBjBBY2jIgHovH19-MyDReJBguEjiGLiJAFlhUg4NJJjCZwglFXc0jMzUPwCOQokjFJAo2PyACxgYdHIkVNTGgEYAOh4qhAWVPVTl6oAmNssrVFm7eCc4FzdPfetbWRPG5o92n07swN6GcOLS-JwAIybyAteDwDFBXK1Bukrgcujl3gU8l9hhIAFIAIQBhC0PBBYJg7gaZyarhae28z1h0GhmRpuRCDH6DGptJ8JWRDDGEymM3uJI8Cz+ALWmA2UDgAA8DORUpBYIIjucVGppegDL9opQwKkmeSWYQobrDjd7KdFY9oTZjo5eRcnjDXj08qEIoM2WUGGjKLBjO4UbU5ZgyTSXt06flCkj3SBPd7hL7-fBA5C7VlQ-DGa7vhJOZNpqkcIkAwtfl6YD6gRAeNrkxajrdrUSHpdDca7o2+c3g5THfSQJ9M+yQABxCAQPTRIo13WpuFOhgRgdRkdjidBjrdsN9TADIZRnPc1JhaILPSj8dwCtVo+pYRQMLYcKbFZQbbV-V2o1W03E20W1sNs1O3XB1Nw+F1d3ySpqgUCA1wpED4QXCCKmfGC4PtNM5xADNkI5cZcx5IklmfBZhHQYQwBGC91ifHY3wNZ46xNG0Wg-f9vybFMuA3eF+1wkAtgQdCZzeLCkLdfJBPMKcuwdZk9VA7Dtx1BSaQk7N8IPIVyGgEx3HQaiRRlaB4FgBUfyVdRUnIERJhGORyBU1SGIOJi20AtivxY81p24hCsL49SGCHYwjzgLE6miQgAAVYj0L1CBgpthL8zDe3ErNgtCicItjKLYoMeKOCSjsUpDWdexwoKQH3PN0Dir1AT0bLDI2Hhdhk1z2O8oDDl4fgxVgLxDiwXB8BgLwQAAGhAbtyGQUBhEwbAAHdoqWhB5pQGIVrjeaZt+YwwAAazgGAAGVyLAL09GQMs4hmmRfjgMIwhegAZW9DGEPQ4AAMRUZZxhu5AQGEAxlGmmqYB4aIAHURlcdQrrgc7NtcShiHBUGwHIfa+ygcgyBgaLjD0ZZkG0GIiZmnByHFNEjtOi68ner04Ep6m4Fp+nzpuicAEUDHsTnohpkByIoMhQd+YRnuiKGsFLOHwhgEZkAADgABhm0aibh4x0FBrB1DIUgoYAR2F+BSb8LawfIBwxRel6odsK3KFsUmfoppAqbF7mQCJnhKDuzAHqD-m4CFkW-a5maYDllWwjV5BtgT4xKA1KA9GxX2QHUABWKGpTgAAVOWtv98XiDiABJO9BHOsBVH8ABBO9zvxCdRaJgBfPugA)

2021-04-08 07:38 UTC, jingtang10 approved these changes

2021-04-08 07:50 UTC, jingtang10 commented
Many thanks for your perseverance with the number of comments! Great work! 🎉🎉🎉

2021-04-08 08:07 UTC, s-ayush2903 commented
Thanks, more the comments, more I get to learn : )

2021-04-08 10:02 UTC, merged