Ms/feature initial values
google/android-fhir pull request #417
Opened 2021-04-01 11:03 UTC by MuhammadSalman-7214

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

Fixes #[https://github.com/google/android-fhir/issues/372]

**Description**
Show already pre filled initial values, if there are any. 

**Alternative(s) considered**
Yes considered the alternative approach of changing the factories, but the approach of Viewmodel (current) is better as discussed?

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-01 11:05 UTC, MuhammadSalman-7214 commented
@jingtang10 and @joiskash please check the updated checks now. Also updating the test cases

2021-04-01 12:03 UTC, joiskash requested changes

2021-04-01 12:03 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      throw java.lang.IllegalArgumentException("GROUP type can't have initial value")
Change the error statement to  "Questionnaire item ${questionnaireItemListIterator.next().linkId} breaks the rule (type!='group' and type!='display') or initial.empty()". Same below. And also add a condition for type display

2021-04-01 12:37 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      throw java.lang.IllegalArgumentException("GROUP type can't have initial value")
Done

2021-04-01 12:37 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      throw java.lang.IllegalArgumentException("GROUP type can't have initial value")
Done

2021-04-01 12:43 UTC, jingtang10 commented
please update your PR description to link to the issue properly - thanks!

2021-04-01 12:46 UTC, MuhammadSalman-7214 commented
> please update your PR description to link to the issue properly - thanks!

Already done that, thanks

2021-04-01 12:53 UTC, jingtang10 requested changes

2021-04-01 12:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (this@createQuestionnaireResponseItem.type != Questionnaire.QuestionnaireItemType.GROUP &&
I find this entire block to be difficult to read. Can you try to improve it? For example, seems like the whole block should be inside 
```
if (this@createQuestionnaireResponseItem.initial.isNotEmpty()) {
  ...
}
```

You can also use early returns, or create utility functions.

2021-04-01 12:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseItem.linkId} breaks the rule (type!='group' and type!='display') or initial.empty()"
what is "the rule"? is it written in FHIR somewhere? I'm not seeing it in https://www.hl7.org/fhir/questionnaire.html#invs.

if it's our rule, then just use plain language to explain it.

2021-04-01 12:54 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (this@createQuestionnaireResponseItem.type != Questionnaire.QuestionnaireItemType.GROUP &&
okay

2021-04-01 12:56 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseItem.linkId} breaks the rule (type!='group' and type!='display') or initial.empty()"
https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial

@joiskash is saying to write the way I have written it now, previously I tried to wrote in simple words

2021-04-01 13:19 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseItem.linkId} breaks the rule (type!='group' and type!='display') or initial.empty()"
@jingtang10  yes this "rule" is found in the description of the questionnaire.item.initial .It is not our rule, it is a rule from the FHIR spec. You will find it in the link posted by Muhammad

2021-04-01 13:38 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseItem.linkId} breaks the rule (type!='group' and type!='display') or initial.empty()"
so @jingtang10 should the exception be like this or is it need to be changed?

2021-04-01 18:14 UTC, MuhammadSalman-7214 commented
@Test
  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
    val questionnaire =
      Questionnaire().apply {
        id = "a-questionnaire"
        addItem(
          Questionnaire.QuestionnaireItemComponent().apply {
            linkId = "a-link-id"
            text = "Basic question"
            type = Questionnaire.QuestionnaireItemType.BOOLEAN
            initial =
              mutableListOf(
                Questionnaire.QuestionnaireItemInitialComponent().setValue(BooleanType(true)),
                Questionnaire.QuestionnaireItemInitialComponent().setValue(BooleanType(true))
              )
          }
        )
      }
    val serializedQuestionniare = printer.encodeResourceToString(questionnaire)
    state.set(QuestionnaireFragment.BUNDLE_KEY_QUESTIONNAIRE, serializedQuestionniare)
    
    val errorMessage =
      assertFailsWith<IllegalArgumentException> { QuestionnaireViewModel(state) }.localizedMessage

    assertThat(errorMessage)
      .isEqualTo("Questionnaire item a-link-id have more than one initial value which is not allowed")
  }
  
  @joiskash I have written this test case to verify the code is throwing exception when there are more than one initial values, it is throwing right exception, but it is not asserting. Can you please help me out in this? Thanks.

2021-04-01 19:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseItem.linkId} breaks the rule (type!='group' and type!='display') or initial.empty()"
Questionnaire item ${this@createQuestionnaireResponseItem.linkId} has initial value(s) and is a group or display item. See rule que-8 at https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial.

2021-04-02 03:53 UTC, joiskash commented
There are some tests in the view model that say "shouldThrowError" have a look at them and then add similar tests. So basically you are asserting that a proper error message is thrown in the unit test.

2021-04-02 06:16 UTC, MuhammadSalman-7214 commented
@joiskash the tests in the view model are for the case when we pass both Questionnaire and Questionnaire response together, but we are testing for the other case in which we are only passing question. This test is not there in ViewModel Test class as well, so that is why need a bit help in this. Thanks.

2021-04-02 10:32 UTC, MuhammadSalman-7214 commented
@jingtang10 and @joiskash, please review, thanks.

2021-04-02 10:49 UTC, MuhammadSalman-7214 commented
@jingtang10 and @joiskash, please check the PR. Everything has been done. Thanks

2021-04-05 02:36 UTC, joiskash submitted a review, later dismissed

2021-04-05 02:36 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      } else if (initial.size > 1 &&
Please refer to rule 13 mentioned [here ](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial)

2021-04-05 02:36 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
same as above refer to rule 13 [here](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial) you need to check  if item.repeats is true or false. 
not item type.

2021-04-05 05:15 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      } else if (initial.size > 1 &&
@joiskash currently we are handling only one initial value, not more than one. That is the reason of the check.

2021-04-05 05:16 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
@joiskash currently we are handling only one initial value, not more than one. That is the reason for this test.

2021-04-05 05:35 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
I think we should test the rule 13. If there is more than one initial item and repeats == false then we should throw and error. If there is more than one initial item and repeats == true we should not throw an error and should just use the first initial value. Later on when #216

2021-04-05 05:37 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
We do not want to reject a valid questionnaire just because we are unable to handle repeats. That is it what I feel. @jingtang10 please comment.

2021-04-05 05:43 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      } else if (initial.size > 1 &&
@joiskash check updated as per the rule, thanks

2021-04-05 05:43 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
@joiskash test case updated as per the rule, thanks.

2021-04-05 06:03 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
yes @joiskash, updated the PR as per the rules and as you are suggesting.

2021-04-05 10:34 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
Can you re-request review? also one small suggestion. Do you think you can move the if-else logic into a function? basically 3 if else statements will be there

1. rule 8 i.e. item (type!='group' and type!='display') or initial.empty()
2. rule 13 i.e. item repeats=true or initial.count() <= 1
3. happy scenario else for all other conditions . 

This way the code will be very readable and will be directly related to the rules defined in the spec. You can directly use these logical statements as defined.

2021-04-05 19:10 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
@joiskash Sure, I can re request review and move all the if else logic to a seprate function, but I don't think we shouldn't change the format of checks as every check has been verified with unit tests. Also all the checks are as per the rules, though the format of check can be different so I don't think we should change the rules again.

2021-04-06 08:52 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
![Screenshot from 2021-04-06 13-49-29](https://user-images.githubusercontent.com/64642723/113684941-2a827c00-96df-11eb-9285-73f6669013cb.png)
@joiskash, when creating a function, it is not picking answer or setAnswe. Can you tell me the reason why is it not picking it this way?

2021-04-06 09:53 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
```
private fun Questionnaire.QuestionnaireItemComponent.createAnswerForItemWithInitialValue():  
MutableList<QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent>? {
  if (valid condition) {
  ....
 return  mutableListOf(
   ...
  ) }
 else error:
  return null
}
```

try this syntax and call the function and set answer with the returned value

2021-04-06 09:54 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
create an extension function for Questionnaire.QuestionnaireItemComponent

2021-04-06 11:22 UTC, MuhammadSalman-7214 commented
@joiskash, I have updated the PR, please check, thanks.

2021-04-06 15:07 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnareHasMoreThanOneInitialValues_shouldThrowError() {
@joiskash, please check the PR, thanks.

2021-04-07 06:54 UTC, joiskash reviewed
Look fine to me except for my comment about restructuring the if-else to match the rules in the spec exactly with rule 8 and rule 13. Currently you only refer to rule 8 in the error message. @jingtang10 can take a decision on this

2021-04-07 07:04 UTC, MuhammadSalman-7214 commented
> Look fine to me except for my comment about restructuring the if-else to match the rules in the spec exactly with rule 8 and rule 13. Currently you only refer to rule 8 in the error message. @jingtang10 can take a decision on this

@joiskash rule 13 is covering as well in case for repeat true, we are setting the value in that case

2021-04-07 07:08 UTC, joiskash commented
Yes I am just talking about the error message. Check both error message, both refer to rule 8. You don't refer to rule 13 anywhere even though you are checking for it.

2021-04-07 07:20 UTC, MuhammadSalman-7214 commented
Well I can add another check in case for throwing exception for rule 13

2021-04-07 07:47 UTC, MuhammadSalman-7214 commented
@joiskash, I have checked all the rules and found out the exception of rule 13 is covering as well. It's just that the exception wording can be changed only to "Item have more than one Initial Values and is not Repeating Item", something like that. What do you suggest about the text of the exception? as every check is covering already

2021-04-07 10:07 UTC, joiskash commented
I think "Questionnaire item ${this@createQuestionnaireResponseWithInitialItem.linkId} Can only have multiple initial values for repeating items See rule que-13 at https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial."

2021-04-07 10:47 UTC, MuhammadSalman-7214 commented
> I think "Questionnaire item ${[this@createQuestionnaireResponseWithInitialItem.linkId](mailto:this@createQuestionnaireResponseWithInitialItem.linkId)} Can only have multiple initial values for repeating items See rule que-13 at https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial."

yes that rule and the exception has already been handled

2021-04-07 10:52 UTC, jingtang10 requested changes
thanks @MuhammadSalman-7214

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseWithInitialItem.linkId} has initial value(s) and is a group or display item. See rule que-8 at https://www.hl7.org/fhir/questionnaire-def
move this to the beginning of this function and throw exception.

i.e.

```
if (is group or is display and has initial value) {
  throw exception
}
```

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  if (this@createQuestionnaireResponseWithInitialItem.initial.isNotEmpty()) {
this is too long -- think of ways to make this block more readable. right now it's very difficult to figure out what this if block is doing.

use a combination of 1) creating utility functions 2) early return / throw 3) reorganising branches logically

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
same here. do an early return.

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  if (this@createQuestionnaireResponseWithInitialItem.initial.isNotEmpty()) {
do you need this at all? 
```suggestion
  if (initial.isNotEmpty()) {
```

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (this@createQuestionnaireResponseWithInitialItem.type !=
```suggestion
    if (type !=
```

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseWithInitialItem():
this function name is a bit of a misnomer. it's creating a list of answers rather than the questionnaire response item.

```suggestion
private fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItemAnswers():
```

and add documentation to this function to say you are using inital items.

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      throw IllegalArgumentException(
your error msg is wrong here. this is breaking que-13

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      )
this seems wrong? if there're multiple intial values why do you only copy one?

2021-04-07 10:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  return null
Again, this can be made into an early return.

```
if (no initial value) {
  return null
}
```

this should probably be the very first thing in this function

2021-04-07 10:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      throw IllegalArgumentException(
it seems like @joiskash had pointed this out. can you change this please?

2021-04-07 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      )
because at the moment, we are only catering the first initial value for repeat true case

2021-04-07 10:59 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  return null
sure

2021-04-07 11:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      )
thanks for the explanation. please create a follow up issue and add a comment here in that case.

2021-04-07 12:33 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        "Questionnaire item ${this@createQuestionnaireResponseWithInitialItem.linkId} has initial value(s) and is a group or display item. See rule que-8 at https://www.hl7.org/fhir/questionnaire-def
Done

2021-04-07 12:33 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  if (this@createQuestionnaireResponseWithInitialItem.initial.isNotEmpty()) {
Done

2021-04-07 12:33 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    }
Done

2021-04-07 12:34 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  if (this@createQuestionnaireResponseWithInitialItem.initial.isNotEmpty()) {
Yes and done

2021-04-07 12:34 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    if (this@createQuestionnaireResponseWithInitialItem.type !=
Done

2021-04-07 12:34 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +private fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseWithInitialItem():
Done

2021-04-07 12:34 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      throw IllegalArgumentException(
Updated

2021-04-07 12:34 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  return null
Done

2021-04-07 12:45 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      )
okay, will create an issue for this

2021-04-07 16:20 UTC, jingtang10 requested changes

2021-04-07 17:00 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  return null
Thanks @jingtang10 for the article. It helped in understanding the concept.

2021-04-07 22:28 UTC, jingtang10 requested changes
please update the PR title to something readable.

also please add in PR description what's the added functionality from https://github.com/google/android-fhir/pull/393.

2021-04-08 07:16 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +/** Here we are setting initial value as an Answer to a Question */
Done

2021-04-08 07:16 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
Done

2021-04-08 07:21 UTC, MuhammadSalman-7214 commented
> please update the PR title to something readable.
> 
> also please add in PR description what's the added functionality from #393.

Done

2021-04-08 07:36 UTC, jingtang10 approved these changes

2021-04-08 08:47 UTC, merged