Add date to search
google/android-fhir pull request #419
Opened 2021-04-02 11:08 UTC by epicadk

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-03 18:48 UTC, jingtang10 commented
Well done in figuring out how the index tables work.

2021-04-03 20:51 UTC, epicadk commented
> Well done in figuring out how the index tables work.

Thankyou 😄. I'm not sure how I should handle the case when the Prefix is null should we throw an error or have a default value?

2021-04-12 18:36 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      null -> "" // Possibly throw an error or provide a default value?
have you tested these?

2021-04-12 18:36 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    AND ? BETWEEN index_tsLow AND index_tsHigh
does this even work?

2021-04-12 18:58 UTC, epicadk commented on core/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    AND ? BETWEEN index_tsLow AND index_tsHigh
Ahh I see I have misspelled `from`. I 'll correct it. Apart from that is does work. I tested it using FhirEngineImpl but I am not sure that is where I should add the tests.

2021-04-12 19:12 UTC, epicadk commented
@jingtang10 I've added tests for the SQL query. But I think we should resolve #433 before we merge this.

2021-04-19 03:56 UTC, epicadk commented
> @jingtang10 I've added a test for the SQL query. But I think we should resolve #433 before we merge this. Converting to draft will add tests for all the cases. I just wanted to know whether I should continue adding the tests in `FhirEngineImplTest` or should I add them to `DatabaseImplTest` ?

Hi, can I have some help here?

2021-04-19 14:43 UTC, jingtang10 commented
Hi @epicadk sorry for the delay. I approved and merged #433. Can you mark this draft as ready for review? thanks

2021-04-19 14:49 UTC, epicadk commented
> Hi @epicadk sorry for the delay. I approved and merged #433. Can you mark this draft as ready for review? thanks

Marked as ready to review. But I haven't really added tests. I'm having trouble in figuring out where I should test if the query works as intended in the `FHIRengineImpl` test or the `DatabaseImpl` test?

2021-04-23 16:46 UTC, epicadk commented
Added an empty commit because build test was failing here but seemed to be working fine locally.

2021-05-10 16:53 UTC, epicadk commented
PR ready for review

2021-06-03 11:21 UTC, jingtang10 reviewed
some comments - sorry for the delay!

2021-06-03 11:21 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +fun DateFilter.query(type: ResourceType): SearchQuery {
to make this PR simpler, i think we could restrict the precision field a little bit. For example, I would think having precision year, month, or day are rare for date time data type (see comment below).

So you can do something like `check(precision == MINUTE || ... SECOND || ... MILLISECOND)`

2021-06-03 11:21 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +  var useHigh = false
I would much rather just create a var that is null and assign the right value to it instead of using this boolean flag.

2021-06-03 11:21 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        )
I think the meaning of equal and not equal can be interpreted in many ways -- and the standard doesn't really help here because it's kinda vague. but i'm happy for us to take a simple approach and use a very strict definition of equal and not equal for date time: literally requiring the start and end timestamps to be both equal. what do you think?

2021-06-03 17:47 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +fun DateFilter.query(type: ResourceType): SearchQuery {
It says in the docs that `YYYY`, `YYYY-MM`, `YYYY-MM-DD` but yeah I think that a user would use Date rather than DateTime for these cases. Should I still add these constrains?

2021-06-04 13:55 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        )
I think this implementation makes sense to have this implementation. 

For example if I wanted to search for an event that occurred on `2001-01-01` I would expect an event that occurred at `2001-01-01T13:10` to be included in the results as well.

2021-06-07 16:55 UTC, jingtang10 requested changes

2021-06-07 16:55 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +  )
I find the structure here a bit difficult to read, especially given the early returns you have in some (but not all) of the branches in the `when` block. can you create another helper function that returns a condition string as well as a list of params which you will concat to the end of the param list?

2021-06-10 06:59 UTC, Tarun-Bhardwaj commented
Hi @epicadk, could you please provide an ETA for completion of changes mentioned in the PR?

2021-06-10 08:23 UTC, epicadk commented
> Hi @epicadk, could you please provide an ETA for completion of changes mentioned in the PR?

I think this and #436 are pretty similar. Once that is approved and ready to merge I'll make similar changes to this pr. I'd say we can get this done in the next 4-5 days

2021-06-15 13:57 UTC, Tarun-Bhardwaj commented
@aditya-07 , could you please review the changes?

2021-06-16 16:43 UTC, jingtang10 requested changes

2021-06-16 16:43 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.LESSTHAN -> "? >= index_to" to listOf(value.value.time)
```suggestion
    ParamPrefixEnum.LESSTHAN -> "? >= index_from" to listOf(value.value.time)
```

because: `[parameter]=lt2013-01-14T10:00 | 2013-01-14 matches, because it includes the part of 14-Jan 2013 before 10am`

what this says to me is that if any part of the range is less than the given value, the range is considered less than the given value.

same for le

2021-06-16 16:43 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      "? <= index_from" to listOf(value.precision.add(value.value, 1).time)
```suggestion
      "? <= index_to" to listOf(value.precision.add(value.value, 1).time)
```

see this: `[parameter]=gt2013-01-14T10:00 | 2013-01-14 matches, because it includes the part of 14-Jan 2013 after 10am`

what this says to me is that if any part of the range is greater than the given value, the range is considered greater than the given value.

same for ge

2021-06-16 16:43 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      "? <= index_from" to listOf(value.precision.add(value.value, 1).time)
can you change the order of things a little bit I find this hard to read...

`index_from >= ?` is easier to read for me than `? <= index_from` because it follows the prefix names such as start after, greater than etc.

same for the rest

2021-06-16 17:48 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.LESSTHAN -> "? >= index_to" to listOf(value.value.time)
Ahh yes that's how this and ends before are different.

2021-06-17 09:05 UTC, jingtang10 requested changes

2021-06-17 09:05 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private data class ConditionParam<T>(val condition: String, val params: List<T>)
is it possible to do something like this: https://kotlinlang.org/docs/functions.html#variable-number-of-arguments-varargs

or create a new function? so that you don't need to use `listOf` repeatedly above?

2021-06-17 09:17 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private data class ConditionParam<T>(val condition: String, val params: List<T>)
I think data classes can only have var/val in their primary constructor, I'll define another one.

2021-06-21 12:32 UTC, jingtang10 approved these changes
Awesome! 😎

Thanks for the PR!

2021-06-21 12:32 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    )
add 4 spaces to align slightly better - same below

2021-06-21 15:55 UTC, deepankarb approved these changes
Thanks @epicadk this is cool!
I've left a few non-blocking comments. LGTM, approved :rocket:

2021-06-21 15:55 UTC, deepankarb commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +              value = DateTimeType("2013-03-14")
The `DateTimeType` supplied above to `patient` has time zone but not here. Will running the query in different time zones produce consistent results?

Can we add tests for that case or create an issue to add them later?

2021-06-21 15:55 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.APPROXIMATE -> TODO("Not Implemented")
Can we add more details here about `ParamPrefixEnum.APPROXIMATE` e.g. link to spec and reason for not implementing.

2021-06-21 15:55 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.APPROXIMATE -> TODO("Not Implemented")
Also, an issue to track it :)

2021-06-21 15:55 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private data class ConditionParam<T>(val condition: String, val params: List<T>) {
Can we use [`varargs`](https://kotlinlang.org/docs/functions.html#variable-number-of-arguments-varargs) for params?

2021-06-21 17:31 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +private data class ConditionParam<T>(val condition: String, val params: List<T>) {
We can't use varargs in the primary constructor of a data class. I've created a secondary constructor for that reason. I realize I was still using listOf in the dateTime code, I've updated that now.

2021-06-21 17:41 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +              value = DateTimeType("2013-03-14")
Sorry I just did that to show to it is compatible with different timezones. By default the timezone will always be UTC unless specified. I think we can leave it up to the consumer whether they would like to search in the devices timezone of any other timezone?

2021-06-21 18:05 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +              value = DateTimeType("2013-03-14")
Oh, Hapi will use the local timezone for DateTimeTypes where the timezone isn't specified. I think this could cause issues. We would also have to change the way we index dates and datetimes in order to have more consistent results across timezones.

Even for date types `DateType("2001-01-01").value.time` will return `978287400000` (for me in india) which is actually `December 31, 2000 6:30:00 PM` GMT

2021-06-21 19:02 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +              value = DateTimeType("2013-03-14")
Thanks, I have opened #567

2021-06-22 04:19 UTC, merged