Utils test
google/android-fhir pull request #420
Opened 2021-04-02 14:50 UTC by Ana2k

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

Fixes #380 

**Description**
Added UtilTest.kt file as unit test for Util.kt 

**Alternative(s) considered**
N/A

**Type**
Choose one:  Testing 

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-02 14:51 UTC, Ana2k commented
@jingtang10 @deepankarb i have implemented this testing file. Please review this pr.

2021-04-03 08:20 UTC, epicadk commented on core/src/test/java/com/google/android/fhir/UtilTest.kt
> +import java.util.*
Spotless check is failing most likely because of this.

2021-04-03 11:56 UTC, Ana2k commented on core/src/test/java/com/google/android/fhir/UtilTest.kt
> +import java.util.*
Thanks so much for the review @epicadk ! I have updated the changes, hope the build runs now. :)

2021-04-04 04:15 UTC, epicadk commented on core/src/test/java/com/google/android/fhir/UtilTest.kt
> - * Copyright 2021 Google LLC
Why this change?

2021-04-13 20:08 UTC, jingtang10 requested changes
thanks!

2021-04-13 20:08 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertEquals(currentDate.toTimeZoneString(), expectedResult)
We use `Truth`: https://truth.dev/

2021-04-13 20:08 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/UtilTest.kt
> +  fun checkTimeZoneFormat() {
```suggestion
  fun shouldFormatDate() {
```

2021-04-13 20:08 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/UtilTest.kt
> +    val currentDate = Date()
I'd rather use a fixed value in test to avoid flakiness.

2021-05-06 15:59 UTC, jingtang10 commented
Is this still being worked on?

2021-05-08 19:43 UTC, Ana2k commented
> Is this still being worked on?

Hi @jingtang10 I apologise for the delay. Sadly I had COVID for quite a while. I have just fully recovered. 
Really excited to start contributing again.
Will get this done ASAP.

2021-05-14 18:24 UTC, jingtang10 commented
> > Is this still being worked on?
> 
> Hi @jingtang10 I apologise for the delay. Sadly I had COVID for quite a while. I have just fully recovered.
> Really excited to start contributing again.
> Will get this done ASAP.

Hi @Ana2k - sorry to hear that you had covid but really pleased to hear that you're fully recovered. Please take it easy! Kind regards and best wishes to you!

2021-06-02 12:46 UTC, Ana2k commented
@jingtang10 theres some updates in the Util.kt file and its test file in the master branch
Proceeding with updating test and date tests to pre existing UtilTest.kt
Please let me know if further changes are required in that file.

2021-06-05 06:50 UTC, Ana2k commented
> @jingtang10 theres some updates in the Util.kt file and its test file in the master branch.
> The tests wrt Time and date were absent in pre existing UtilTest.kt.
> So, I am proceeding with updating time and date tests to it.
> Please let me know if further changes are required in that file.

@jingtang10 I have updated the shouldFormatDate function in utilTest.kt Kindly please review. Thanks!

2021-06-24 16:01 UTC, jingtang10 requested changes

2021-07-03 08:45 UTC, Ana2k commented on engine/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertThat(parsedDate.toString()).isEqualTo(expectedResult)
Yes these are the changes for the same. The tests passed on my end. I hope no issues on this code snippet?

2021-07-07 13:11 UTC, jingtang10 requested changes

2021-07-07 13:11 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/UtilTest.kt
> +    assertThat(parsedDate.toString()).isEqualTo(expectedResult)
I'm not see the `Date.toTimeZoneString` method being called here. How is it being tested?

2021-07-13 12:45 UTC, Tarun-Bhardwaj commented
Hi @Ana2k , is there an ETA you can provide for completing the changes as per the review comments in order to close this PR?

2021-08-05 03:17 UTC, Ana2k commented
> Hi @Ana2k , is there an ETA you can provide for completing the changes as per the review comments in order to close this PR?

Hi @Tarun-Bhardwaj I am have almost completed working on this, ETA is around 11th August

2021-11-10 21:06 UTC, jingtang10 commented
Closing this since it's not been open worked on.

2021-11-10 21:06 UTC, closed without merging