localChangeUtilsTest mplemented
google/android-fhir pull request #424
Opened 2021-04-04 10:41 UTC by Ana2k

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-04 10:48 UTC, Ana2k commented
@deepankarb @jingtang10 I have implemented the tests. Please review this pr.
Thanks!

2021-05-06 17:07 UTC, jingtang10 requested changes
Thanks @Ana2k!

2021-05-06 17:07 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +                    |"path": "/name/0/use",
Do you mind removing the `|`s? do they affect your result at all?

2021-05-06 17:07 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +           ]}"""
I would probably do the indentation this way:

```suggestion
      """
      {
        "resourceType": "Patient",
        "id": "human",
        "name": [
          {
            "use": "usual",
            "given": [
              "Kenzi"
            ]
          }
        ]
      }
      """
```

2021-05-06 17:07 UTC, jingtang10 commented on core/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    assertEquals(mergeLocalChanges(fifth, fourth), res54)
Please separate these into 4 different test cases each with a descriptive name

```
@Test
mergeInsertAndInsert

@Test
mergeInsertAndDelete

...
...

```


The reason to do things this way is that each test will be independent. So if a test is failing you can tell by looking at the test case name to figure out what is happening. If your test case fails now you will have to check the stack trace or even debug to figure out which case is actually failing.

2021-05-08 19:47 UTC, Ana2k commented on core/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    assertEquals(mergeLocalChanges(fifth, fourth), res54)
> Please separate these into 4 different test cases each with a descriptive name
> 
> ```
> @Test
> mergeInsertAndInsert
> 
> @Test
> mergeInsertAndDelete
> 
> ...
> ...
> ```
> 
> The reason to do things this way is that each test will be independent. So if a test is failing you can tell by looking at the test case name to figure out what is happening. If your test case fails now you will have to check the stack trace or even debug to figure out which case is actually failing.

Thanks for the clear explanation. Will get these done in a couple of days :)

2021-05-14 08:51 UTC, jingtang10 commented
please re-request review when this is done thanks

2021-05-20 18:57 UTC, Ana2k commented
@jingtang10 I have implemented the required changes please review. Thanks!

2021-05-26 21:59 UTC, Ana2k commented
@jingtang10 @vincent-karuri please review this pr. Thanks.

2021-05-27 07:25 UTC, vincent-karuri commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    // Expected output when third and first are mixed( DELETE AND INSERT)
I think we can move the comments to form part of the test name i.e. make the test name more descriptive to specify the SUT, condition, and expected behavior. e.g. https://github.com/google/android-fhir/blob/4892adbddf78f4fdef40d3f95bd5e2bb19424fdf/engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt#L119

reference: https://source.android.com/setup/contribute/code-style#javatests-style-rules

2021-05-27 07:29 UTC, vincent-karuri commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    // Expected output when third and first are mixed( DELETE AND INSERT)
we can also rename the resources to describe they're content better. atm, it's not too clear what the numbers mean i.e. why `res31, res54 etc.`. Unless it's not important to distinguish between them.

2021-05-27 15:27 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    // Expected output when third and first are mixed( DELETE AND INSERT)
hi vincent - do you mind adding this reference: https://source.android.com/setup/contribute/code-style#javatests-style-rules to the developer's guide? https://github.com/google/android-fhir/wiki/Developer's-Guide in the naming convention section. thanks!

2021-05-27 16:45 UTC, Ana2k commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    // Expected output when third and first are mixed( DELETE AND INSERT)
> we can also rename the resources to describe their content better. atm, it's not too clear what the numbers mean i.e. why `res31, res54 etc.`. Unless it's not important to distinguish between them.

@vincent-karuri @jingtang10 
I have made the required changes I as well as I could. 
Please review this pr for further changes. Thanks!

2021-05-27 18:00 UTC, jingtang10 requested changes

2021-05-27 18:00 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    )
Please inline all these variables - I would much rather have some duplication in each test cases but do not need to scroll up and down to figure out what the behaviour needs to be.

2021-05-27 18:00 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun response_test_insert_payload1_insert_payload2() {
```suggestion
  fun mergeLocalChanges_insertTwice() {
```

same with the other names

2021-06-01 15:48 UTC, Ana2k commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun response_test_insert_payload1_insert_payload2() {
@jingtang10  @vincent-karuri I have implemented all the required changes. Kindly review this pr. Thanks!

2021-06-01 15:49 UTC, Ana2k commented
@jingtang10 @vincent-karuri I have implemented all the required changes. Kindly review this pr. Thanks!

2021-06-04 13:42 UTC, jingtang10 requested changes
Thanks @Ana2k !

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    // (INSERT AND INSERT)
remove this comment which is not adding anything

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun mergeLocalChnages_insertTwice() {
```suggestion
  fun mergeLocalChanges_insert_insert() {
```

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun mergeLocalChanges_delete_and_insert() {
```suggestion
  fun mergeLocalChanges_delete_insert() {
```

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +/*
Can you modify `LocalChangeUtils.mergeLocalChanges` and make sure the rresource type and resource ids match?
```
    check(first.resourceType == second.resourceType) {
      "Resource types ${first.resourceType} and ${second.resourceType} do not match"
    }
    check(first.resourceId == second.resourceId) {
      "Resource IDs ${first.resourceId} and ${second.resourceId} do not match"
    }
```

And then add 2 test cases: 1 with different resource types and 1 with different resource ids and assert that exceptions are thrown.

look for the use of `assertThrows` in the codebase

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +      )
inline these variables?

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  val payload_json_node: JsonNode = objectMapper.readTree(payload1)
no need to be class variables if only used in the last test case?

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +class LocalChangeUtilsTest {
overall you need to have 3^2 = 9 test cases:

insert insert
insert update
insert delete
update insert
update update
update delete
delete insert
delete update
delete delete

here you've got 5 so 4 are still missing

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun mergeLocalChanges_insertPayloadJNode_and_UpdateJpatch() {
```suggestion
  fun mergeLocalChanges_insert_update() {
```

2021-06-04 13:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +    // (INSERT-PayloadJNODE AND UPDATE-JSON-PATCH)
remove this comment - it's not adding anything or explaining anything more than the test case name

2021-06-07 11:48 UTC, Ana2k commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +      )
I have inlined these for now, but its too clumpsy and non readable, according to me.
I saw the format at https://github.com/google/android-fhir/blob/1c3d04de5ba90d209c539be514a571ec371ca9ed/engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt#L65
that's why stuck to the same.

2021-06-10 16:16 UTC, Ana2k commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +/*
@jingtang, as per my understanding of the codebase, LocalChangeUtils.mergeLocalChanges support merging of  different resourceType ,as shown in the if else statements given

Bu defenintely I can add check for matching of IDs. So implementing that as of now. Please tell your views

2021-06-10 19:10 UTC, Ana2k commented
@jingtang10 I have implemented all the required changes.
Except the resourceType spec 
Reason in :https://github.com/google/android-fhir/pull/424#discussion_r649335620

Kindly please review this pr. Thanks!

2021-06-11 11:55 UTC, vincent-karuri commented
@jingtang10 I think we have the same integration test issue here as well

2021-06-11 12:01 UTC, vincent-karuri commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun mergeLocalChanges_delete_delete() { // delete delete
hi @Ana2k were you able to take a look at the format on the other tests https://github.com/google/android-fhir/pull/424#discussion_r640355991?

2021-06-11 12:08 UTC, vincent-karuri commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun mergeLocalChanges_delete_delete() { // delete delete
It follows the format recommended here https://github.com/google/android-fhir/pull/424#discussion_r640355991 with a slight modification.

Basically, this test method should read something like `mergeLocalChanges_deletion_shouldMergeDeletePayloads`.  This allows one to quickly understand all the "variables" at play in the test by simply looking at the test name. 

Also, it removes the need for comments in the test as the name is self-explanatory.

2021-06-17 14:59 UTC, Ana2k commented on engine/src/test/java/com/google/android/fhir/db/impl/dao/LocalChangeUtilsTest.kt
> +  fun mergeLocalChanges_delete_delete() { // delete delete
> hi @Ana2k were you able to take a look at the format on the other tests [#424 (comment)](https://github.com/google/android-fhir/pull/424#discussion_r640355991)?

@vincent-karuri  Thanks for the specifics.Theye were really helpful.I have made relevant changes to the best of my understanding.
Can @jingtang10 and you review this pr and mention if more changes are required?
Thanks!

2021-07-03 08:50 UTC, Ana2k commented
@jingtang10 reminder for reviewing this pr. 
@maimoonak tagging you to update about previous PRs.
Thanks!

2021-07-13 12:46 UTC, Tarun-Bhardwaj commented
Hi @Ana2k , is there an ETA you can provide for completing the changes as per the review comments in order to close this PR?

2021-08-05 03:25 UTC, Ana2k commented
> Hi @Ana2k , is there an ETA you can provide for completing the changes as per the review comments in order to close this PR?

Hi @Tarun-Bhardwaj , almost all of the required changes have been implemented for this. ETA is 10th August for this.

2021-11-10 21:07 UTC, jingtang10 commented
Closing this since it's not been open worked on.

2021-11-10 21:07 UTC, closed without merging