Support Contains for string search
google/android-fhir pull request #426
Opened 2021-04-05 09:59 UTC by epicadk

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #376 
**Description**
Clear and concise code change description. 

Support contains for string search.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
Explained in the comment on linked issue. 

**Type**
Choose one: Feature

**Screenshots (if applicable)** 

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-12 17:25 UTC, jingtang10 requested changes
Thanks @epicadk for this change! Just a comment on the syntax for the search API.

2021-05-12 17:25 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var modifier: StringParam? = null,
I'm not certain this is the right way to represent this. Looking at the API, you have something like this: 

```
filter(Patient.GIVEN) {
  value = "eve"
  modifier = StringParam().setContains(true)
}
```

I would say it looks a little clumsy. can we just create a new enum? Similar to `Order` here. And just have `MATCHES, MATCHES_EXACTLY, CONTAINS`.

2021-05-12 18:13 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var modifier: StringParam? = null,
Yes will do.

2021-05-13 17:05 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_HumanName() {
@jingtang10 I changed the indexing pattern. This test would have failed with the previous way but now it passes.

2021-05-14 11:26 UTC, jingtang10 commented
Thanks @epicadk - I would really love to focus on the contains issue and handle the change of indexing in a separate PR. Is it ok?

2021-05-14 11:40 UTC, epicadk commented
> Thanks @epicadk - I would really love to focus on the contains issue and handle the change of indexing in a separate PR. Is it ok?

Yep sorry. Reverting the change.

2021-05-14 13:59 UTC, epicadk commented
@jingtang10 done.

2021-05-14 15:41 UTC, jingtang10 requested changes
thanks!

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/params/StringSearchModifier.kt
> +/*
does it make sense for this to be in `SearchDsl.kt`? `Order` is already there.

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/params/StringSearchModifier.kt
> +enum class StringSearchModifier {
prefer for this to be exhaustive - add STARTS_WITH and set it as default in the DSL? Feel like that's much more explicit. so you'll have

```
STARTS_WITH,
MATCHES_EXACTLY,
CONTAINS
```

for a developer looking at these three options it's immediately clear what the behavior is. not having a default makes it a little harder to understand the behavior.

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/params/StringSearchModifier.kt
> +enum class StringSearchModifier {
nit: `StringFilterModifier`?

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    )
does spotless give you problems here?

if not, can you make the indentation look better by adding 4 spaces so this block is in line with the `"""`.

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    )
same here

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(res[0].nameFirstRep.given.any { it.toString() == "Eve" }).isTrue()
this line seems to be superfulous if you have asserted that `patient1` is returned?

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      }
i think i would prefer to break this into 2 different test cases.

```
fun search_string_exact // for matching Eve
fun search_string_exact_differentCase // for not matching EVE 
```

`EVE` and `eve` are frankly the same test case since it's about not matching the case.

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      }
hm i think you could just have one most generic case, which is that you can match a substring in a case-insensitive way.

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_Exact() {
```suggestion
  fun search_string_exact() {
```

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_Contains() {
```suggestion
  fun search_string_contains() {
```

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_Default() {
```suggestion
  fun search_string_default() {
```

2021-05-14 15:41 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      }
same thing here - let's split the cases.

i think you can have a matching case and a non-matching case. 2 should be enough.

2021-05-14 17:30 UTC, epicadk commented
@jingtang10 done

2021-05-14 18:21 UTC, jingtang10 approved these changes
Great! Thanks so much for this. Please feel free to merge after addressing the final few (nit) comments.

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_default() {
```suggestion
  fun search_string_default() {
```

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_default_no_match() {
```suggestion
  fun search_string_default_no_match() {
```

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_exact() {
```suggestion
  fun search_string_exact() {
```

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_exact_no_match() {
```suggestion
  fun search_string_exact_no_match() {
```

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_contains() {
```suggestion
  fun search_string_contains() {
```

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_String_contains_no_match() {
```suggestion
  fun search_string_contains_no_match() {
```

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(res).hasSize(1)
nit: add black line before assertions - and same for other test cases.

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .isTrue()
kinda feel like you just need to assert that the right patient (with id `test_1`) is returned. no need to actually assert the name indeed starts with `Eve`. actually the name might start with `EVE` or `eve`. so this assertion doesn't need to be here.

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(res[0].nameFirstRep.given.any { it.toString() == "Eve" }).isTrue()
i think just checking the patient id is right is enough?

2021-05-14 18:21 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .isTrue()
same here

2021-05-14 19:41 UTC, merged

2021-05-17 11:13 UTC, jingtang10 commented
Thanks again @epicadk for this PR and merging!