Merge kp/support min max value float datetime into master for adding
google/android-fhir pull request #432
Opened 2021-04-07 14:41 UTC by kunjan8794

Closes #415

**Description**
Added support for decimal, date & dateTime data types for MinValue & MaxValue extensions

**Type**
Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-07 17:02 UTC, kunjan8794 commented
@jingtang10 Just wanted your inputs regarding the unit tests. How should I do it here for different data types? I have added couple of them for the decimal data types. If you think thats apt, I will go ahead and write them for date and dateTime as well.

2021-04-13 11:31 UTC, jingtang10 requested changes
you can define a comparison method on  the type `Type`:

```
operator fun Type.compareTo(value: Type?): Int {
  ...
}
```

and then in your validators you can just do this:

```
{ extension: Extension, answer: QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent
      ->
      extension.value > answer.value  // or extension.value < answer.value
    }
```

2021-04-19 20:00 UTC, jingtang10 requested changes

2021-04-19 20:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MoreTypes.kt
> +        if (value.primitiveValue().toInt() == this.primitiveValue().toInt()) return 0
```
value.primitiveValue().toInt().compareTo(primitiveValue().toInt())
```

Same with the other types

2021-04-19 20:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MoreTypes.kt
> +/*
please add tests for this class

2021-04-20 18:33 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MoreTypes.kt
> +private fun clearTimeFromDateValue(dateValue: Date): Date {
@jingtang10 I have added this utility funciton here, but I am not sure if thats the correct place for this function. Can you please share your insights on this?

2021-05-04 11:09 UTC, jingtang10 requested changes

2021-05-04 11:09 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
> +  fun shouldReturnInvalidResultForDecimal() {
```suggestion
  fun shouldReturnInvalidResult() {
```

so in terms of responsibilities, the `MinValueConstraintValidator` only checkes if something is less than the min value. It doesn't really care what type the value is. So in the tests, what we are testing is that it invokes the comparison correctly.

On the other hand, the `MoreTypeTest` needs to verify the comparison works with different types of value.

So here I think it makes more sense to remove the `ForDecimal` in the name of the test case.

2021-05-06 09:32 UTC, jingtang10 commented
Hey @kunjan8794 any update here? Let me know if anything isn't clear in my review. Thanks!

2021-05-06 09:34 UTC, jingtang10 commented
let's try to close this off soon since the pr was opend a while ago. :)

2021-05-06 17:12 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MoreTypes.kt
> +  val calendarValue = Calendar.getInstance()
@jingtang10 the Date(year, month, day) function has been deprecated. Should we still use it?

2021-05-11 11:31 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MoreTypes.kt
> +  val calendarValue = Calendar.getInstance()
I see - in that case it's fine.

2021-05-11 21:07 UTC, jingtang10 approved these changes
Thanks @kunjan8794 - just 3 final comments.

2021-05-12 08:56 UTC, jingtang10 commented
you may need to run `./gradlew spotlessApply`.

2021-05-12 13:13 UTC, merged