Feat: Number Search
google/android-fhir pull request #436
Opened 2021-04-10 09:08 UTC by epicadk

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #435 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR? 
NA

**Type**
Choose one: Feature

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-12 13:05 UTC, epicadk commented
What should we set as the threshold for the Approximate search prefix?

2021-04-12 19:17 UTC, epicadk commented
Will add tests to show that the SQL query works

2021-05-06 09:36 UTC, epicadk commented
Will finish this by today.

2021-05-12 13:30 UTC, epicadk commented
Pr ready for review

2021-05-14 20:28 UTC, epicadk commented
I'll make changes to the tests so that they are similar to the string search ones.

2021-06-02 12:11 UTC, jingtang10 commented
@kevinmost can you please leave a review because this is related to your work on indexing numbers. Thanks!

2021-06-04 19:56 UTC, kevinmost approved these changes

2021-06-04 19:56 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      value!!.scale() >= 0 ->
There are a lot of `value!!` throughout this method. Can we just null-assert once, at the top of the file, and capture it in a local val?

```kt
val value = value!!
val precision = 
  when {
    value.scale() >= 0 -> 
  // and so on
```

2021-06-04 19:56 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +          throw IllegalArgumentException("Prefix not allowed for Integer type")
You can use `require` here. I would also put the prefix into the error message.

```
require(value.scale() > 0) { "Prefix $prefix not allowed for Integer type" }
```

2021-06-04 19:56 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +          throw IllegalArgumentException("Prefix not allowed for Integer type")
Ditto

2021-06-04 19:58 UTC, kevinmost commented
@jingtang10 LGTM, not sure if you wanted to approve before this lands.

2021-06-05 05:29 UTC, epicadk commented
Ran the integration tests they pass locally, can't figure out why they fail in the CI

2021-06-05 12:10 UTC, kevinmost commented
I think something may be wrong with CI (again). I'm seeing CI fail on one of my PRs even though I don't think it should.

2021-06-05 12:43 UTC, epicadk commented
I checked the test results in the artifacts and the test in the reference app seems to be failing.

2021-06-07 16:58 UTC, jingtang10 requested changes

2021-06-07 16:58 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +fun NumberFilter.query(type: ResourceType): SearchQuery {
similar to the comment i left in the date time PR. i find the structure a bit difficult to read because of the early returns in some of the branches in `when`. can you create a utility function to make the logic a bit more readable (and unify the code paths). thanks!

2021-06-08 12:19 UTC, jingtang10 requested changes

2021-06-08 12:19 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +fun getConditionParamPair(
private

2021-06-08 12:19 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    }
I feel this is a little too lenient. 0.49 would be within the margin to be equal to 0.5 (scale would be 1, 10^(-1) = 0.1, so the precision is 0.05). I feel like we need to increase the scale by at least one or two decimal points. So that maybe 0.499 can be deemed equivalent to 0.5, but not 0.49.

Also, can you create a utility function with a little bit of explanation in the documentation (with examples) to explain what's happening here?

Thanks!

2021-06-08 12:19 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.GREATERTHAN -> "index_value > ?" to listOf(value.toDouble())
```suggestion
    ParamPrefixEnum.GREATERTHAN -> "index_value > ?" to listOf((value - precision).toDouble())
```

same should be applied to everything below

2021-06-08 13:00 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.GREATERTHAN -> "index_value > ?" to listOf(value.toDouble())
according to the [standard](https://www.hl7.org/fhir/search.html#number)

> When a comparison prefix in the set lgt, lt, ge, le, sa & eb is provided, the implicit precision of the number is ignored, and they are treated as if they have arbitrarily high precision

2021-06-08 13:32 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    }
Actually 0.5 would simply anything in the range of [0.45,0.55). I think this mainly has to do with [Significant figures](https://en.wikipedia.org/wiki/Significant_figures#Rounding_to_significant_figures)

2021-06-08 16:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    ParamPrefixEnum.GREATERTHAN -> "index_value > ?" to listOf(value.toDouble())
oh i didn't realise this is described in the standard. can you maybe add a comment in the code to link to https://www.hl7.org/fhir/search.html#number?

2021-06-08 16:45 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    }
oh i see this is mandated in the standard as well https://www.hl7.org/fhir/search.html#number.

2021-06-08 17:05 UTC, jingtang10 requested changes
thanks very much! a few more comments.

2021-06-08 17:05 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    // Ends_Before and Starts_After are not used with integer values.
where in the standard says this?

2021-06-08 18:43 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    // Ends_Before and Starts_After are not used with integer values.
[This section](https://www.hl7.org/fhir/search.html#prefix) the small paragraph immediately after the table

2021-06-09 11:52 UTC, jingtang10 requested changes
Apologies really should have sent these in the previous rounds... but I think this might be the last review :)

2021-06-09 11:52 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +  val conditionParamPair = getConditionParamPair(prefix, value, precision)
```suggestion
  val conditionAndParams = getConditionParamPair(prefix, value!!)
```

and call `value.getRange()` inside `getConditionParamPair`

2021-06-09 11:52 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> + * https://www.hl7.org/fhir/search.html#number
```suggestion
 * Returns the condition and list of params required in NumberFilter.query see
 * https://www.hl7.org/fhir/search.html#number.
```

2021-06-09 11:52 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  @Test(expected = java.lang.IllegalArgumentException::class)
use this: https://github.com/google/android-fhir/search?q=assertthrows

2021-06-09 11:52 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  @Test(expected = java.lang.IllegalArgumentException::class)
use this: https://github.com/google/android-fhir/search?q=assertthrows

2021-06-09 11:52 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    // Approximate to a 10% range
add a link to the standard where this is explained.

2021-06-09 13:34 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> + * Note 100 is considered to have 2 significant digits
Sorry matches upto 2. Yep, I'll remove it. I mainly included it to highlight the difference between 1e2 and 100

2021-06-09 13:34 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    else -> BigDecimal(5)
Sure

2021-06-09 14:48 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    else -> BigDecimal(5)
100 has a scale of 0 but 1e2 will have a scale of -2

2021-06-10 06:35 UTC, Tarun-Bhardwaj commented
@epicadk , it seems there are some changes requested on this PR. Is there an ETA by when you think this can be closed?

2021-06-10 06:37 UTC, epicadk commented
> @epicadk , it seems there are some changes requested on this PR. Is there an ETA by when you think this can be closed?

Yup working on it. Will be done by the end of the day.

2021-06-11 15:42 UTC, jingtang10 approved these changes
thanks @epicadk! great work!

👍

2021-06-11 15:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    for (x in
actually slightly prefer to split this into 3 different test cases.

i think `1e2` and `1e3` can be merged into one test case.

2021-06-11 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      require(value.scale() > 0) { "Prefix $prefix not allowed for Integer type" }
maybe move this to the front of the function

`require(value.scale() <= 0 || (prefix != STARTS_AFTER && prefix != ENDS_BEFORE))`

2021-06-11 15:43 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    for (x in
or use proper parameterized tests? may be an overkill though.

2021-06-11 15:55 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    for (x in
I removed the 1e2 test case for now, maybe we can discuss parametrized tests in a different issue?

2021-06-11 16:08 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      require(value.scale() > 0) { "Prefix $prefix not allowed for Integer type" }
I think the condition would remain value.scale() > 0 right?

2021-06-11 16:27 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      require(value.scale() > 0) { "Prefix $prefix not allowed for Integer type" }
oh yeah that's right

2021-06-11 16:29 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    for (x in
i mean you could even just have 3 different test cases so test failures are more explicit.

eg. `search_number_equals_int`, `search_number_equals_decimal` etc

2021-06-11 19:14 UTC, epicadk commented
Keeping only the relevant commit messages in the commit body. I hope that's okay?

2021-06-11 19:16 UTC, epicadk commented
@Tarun-Bhardwaj done with this, can focus on adding Date Search now

2021-06-12 03:41 UTC, epicadk commented
> I checked the test results in the artifacts and the test in the reference app seems to be failing. Temporarily deleted the test to check if that is indeed the issue. cc @jingtang10

This is still failing removing it for now, we can add it back later. (It's just an example anyways.)

2021-06-12 04:16 UTC, merged