Add API and implementation for upload sync
google/android-fhir pull request #437
Opened 2021-04-12 07:31 UTC by deepankarb

Fixes #366

**Description**

Added basic upload sync API and implementation in `FhirEngine`.

* Sync resources by squashed change type
* Rudimentary check for upload success

**Alternative(s) considered**
Basic feature implemented but needs augmentation to support periodic sync using work manager ala download sync.

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-12 21:50 UTC, jingtang10 requested changes

2021-04-12 21:50 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/Util.kt
> +    return if (this.hasIdElement() && this.idElement.hasIdPart()) this.idElement.idPart else ""
```suggestion
    return this.idElement?.idPart ?: ""
```

2021-04-12 21:50 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +    return outcome.hasIssue() &&
should this be

```suggestion
    return !outcome.hasIssue() ||
```

?

2021-04-13 08:35 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +    return outcome.hasIssue() &&
I am using `Resource.hasXX()` to guard against empty/null properties. Maybe `outcome.issue?.all... ?: false` is better?

2021-04-13 11:36 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +    return outcome.hasIssue() &&
so if `outcome` has no `issue`, would you return `true` or `false`? I kinda feel it should be `true`? But you would return `false` here?

2021-04-13 13:19 UTC, deepankarb commented on core/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +    return outcome.hasIssue() &&
I was going with `false` because it does not imply success or failure. And I think better to fail fast. That being said we need to have robust signals for operation success. I have created #440 to track it.

2021-04-13 14:49 UTC, jingtang10 approved these changes

2021-04-13 15:24 UTC, merged