Bug : Fix date indexing
google/android-fhir pull request #439
Opened 2021-04-12 17:27 UTC by epicadk

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #433 

**Description**
Clear and concise code change description.  
Added precision to ts_high in the date index to comply with the standard. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR? 

We could index precision however I don't really see a usecase. 

**Type**
Choose one: Bug fix 

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-04-12 18:55 UTC, jingtang10 requested changes

2021-04-12 18:55 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/entities/DateIndex.kt
> +  val tsLow: Long
while we're at it, can we change the order of these two fields and rename them `from` and `to`?

2021-04-12 18:55 UTC, jingtang10 commented
thanks for the draft! @epicadk

2021-04-12 22:05 UTC, jingtang10 requested changes
Thanks!

2021-04-12 22:05 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/db/impl/entities/DateIndexEntity.kt
> +      Index(value = ["resourceType", "index_name", "index_to", "index_from"]),
can you change the order here too?

2021-04-12 22:05 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/entities/DateIndex.kt
> +  val from: Long
change the order of these two fields here and everywhere in other files

add descriptive documentation and espeically describe whether these values are exclusive or inclusive.

2021-04-12 22:05 UTC, jingtang10 commented on core/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +          from = lastUpdatedElement.precision.add(lastUpdatedElement.value, 1).time - 1
change order

2021-04-14 04:20 UTC, epicadk commented
Done @jingtang10

2021-04-19 10:37 UTC, jingtang10 approved these changes

2021-04-19 10:38 UTC, jingtang10 commented
Thanks @epicadk for the contribution! 🎉

2021-04-19 11:15 UTC, merged