chore : Skip CI if changes are only to `*.md` file
google/android-fhir pull request #457
Opened 2021-04-28 07:45 UTC by epicadk

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

trivial

**Description**
Clear and concise code change description. 

Skip the workflow if changes are made only to .md files ( like `readme.md`

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
 
We could add the `license.txt` file as well but spotless check might fail if changes are made to the file so I've decided to include it. 

**Type**
Choose one: (Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-04 12:39 UTC, jingtang10 requested changes
Thanks for this! Great idea using `paths-ignore`.

Please do modify the paths though to use `**` so that it covers subdirectories.

2021-05-04 12:39 UTC, jingtang10 commented on .github/workflows/ci.yml
> +      - '*.md'
```suggestion
      - '**.md'
```

2021-05-04 12:39 UTC, jingtang10 commented on .github/workflows/ci.yml
> +      - '*.md'
```suggestion
      - '**.md'
```

2021-05-04 15:29 UTC, epicadk commented
> Thanks for this! Great idea using `paths-ignore`.
> 
> Please do modify the paths though to use `**` so that it covers subdirectories.

Yup sorry I wasn't aware of the difference between `*` and `**`. I've made the changes.

2021-05-04 15:41 UTC, epicadk commented
I also added `CODEOWNERS` and `LICENSE` because they wouldn't really affect the outcome of the CI

2021-05-05 09:52 UTC, jingtang10 commented
Great! Thanks for this!

2021-05-05 09:52 UTC, jingtang10 approved these changes

2021-05-05 09:52 UTC, merged

2021-08-19 18:14 UTC, jingtang10 commented
This PR is causing some issues. If a PR is raised with changes only to the ignored files, no CI workflow will be triggered. But because we have a branch rule for `master` to ensure only PRs with passing tests can be merged, the PR cannot actually be merged.

I'm not sure this PR is still the right thing to do given this. Either we revert this PR, or if we can find a way for GitHub to not enforce the testing rule for PRs with only documentation change.

2021-08-19 18:15 UTC, jingtang10 commented
@deepankarb had this problem for #720

2021-08-20 03:38 UTC, epicadk commented
I had a look at some of the actions repos and even they have removed the path filter due to a similar issue. (lastest commit on https://github.com/actions/upload-artifact). So I think removing the filter is the way to go.

The logic behind this change was to avoid running the tests because the code wouldn't have changed. So if we do find a way to implement this properly we could revisit this later.

2021-08-20 04:29 UTC, deepankarb commented
Thanks @epicadk @jingtang10 The worst case scenario is when there are lots of small changes in documentation in multiple PRs (single PR updation will cancel any subsequent runs AFAIK so not an issue). Such a scenario is IMO rare. I think it's better to remove the `paths-ignore`.