Adds patient count API
google/android-fhir pull request #460
Opened 2021-05-03 08:38 UTC by rkodev

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes https://github.com/google/android-fhir/issues/458

**Description**
Adds a count a part of the search API

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-03 08:40 UTC, rkodev commented
@googlebot I signed it!

2021-05-03 13:02 UTC, rkodev commented
@jingtang10 @deepankarb @kevinmost @pankajkatoch @yigit This PR is ready for Review

2021-06-03 08:31 UTC, jingtang10 requested changes

2021-06-03 08:31 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   */
incorrect doc.

2021-06-03 08:31 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +    SELECT ${ if (isCount) "count(*)" else "a.serializedResource" }
```suggestion
    SELECT ${ if (isCount) "COUNT(*)" else "a.serializedResource" }
```

2021-06-03 08:31 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +      { findViewById<TextView>(R.id.patient_count).text = it.toString() + " Patients" }
```suggestion
      { findViewById<TextView>(R.id.patient_count).text = it.toString() + " Patient(s)" }
```

2021-06-03 08:31 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +    )
```suggestion
    return fhirEngine.count<Patient>(
      filter(Patient.ADDRESS_CITY) {
        prefix = ParamPrefixEnum.EQUAL
        value = "NAIROBI"
      }
    )
```

2021-06-07 07:50 UTC, maimoonak commented
@googlebot I signed it!

2021-06-07 09:08 UTC, maimoonak commented
@googlebot I signed it.

2021-06-07 10:25 UTC, maimoonak commented
@googlebot I consent.

2021-06-07 10:27 UTC, jingtang10 approved these changes
Thanks! @maimoonak and @rkodev! 👍

2021-06-07 10:27 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +   * Total count of entities available for given search
available is misleading. this is the count of resources returned for a given search.

```suggestion
   * Total count of resources for given search
```

2021-06-07 10:44 UTC, merged