Adds token search
google/android-fhir pull request #461
Opened 2021-05-03 15:15 UTC by rkodev

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #431

**Description**
Adds filter by token

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-03 15:44 UTC, epicadk commented
Can you also add modifiers as mentioned here https://www.hl7.org/fhir/search.html#token

2021-05-04 10:06 UTC, rkodev commented
@epicadk Can we add this modifier in a separate PR, I think how we choose to implement the modifiers will affect how they are implemented for the other data types.

2021-05-12 18:01 UTC, jingtang10 requested changes
Thanks @rkodev!

2021-05-21 07:47 UTC, rkodev commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var value: Any? = null,
Updated to accept variables, I've left out [CodeableConcept](https://www.hl7.org/fhir/datatypes.html#CodeableConcept) because match on any would rely on an OR search

2021-05-21 07:48 UTC, rkodev commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var system: String? = null
Resolved. Renamed `value` to  `code` and swapped the order

2021-05-24 15:42 UTC, jingtang10 requested changes

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
>    internal val referenceFilter = mutableListOf<ReferenceFilter>()
```suggestion
  internal val referenceFilters = mutableListOf<ReferenceFilter>()
```

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  internal val tokenFilter = mutableListOf<TokenFilter>()
```suggestion
  internal val tokenFilters = mutableListOf<TokenFilter>()
```

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun search_token_filter() {
I think you need to have test cases for:

- coding
- identifier
- contact point
- boolean
- uri
- string

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var code: String?
what about
```suggestion
  var code: String
```

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +    tokenFilter.add(TokenFilter(parameter = filter, code = contactPoint.value))
according to https://www.hl7.org/fhir/STU3/search.html#token the `system` field should be `use`.

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +
missing one for `CodeType`?

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var system: String? = null,
Use `uri` to match the definition here https://www.hl7.org/fhir/STU3/search.html#token?

```suggestion
  var uri: String? = null,
```

2021-05-24 15:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +    tokenFilter.add(TokenFilter(parameter = filter, code = coding.code, system = coding.system))
i suggest swaping the order of `system` and `code` parameters to be more consistent with the order of definition.

2021-05-25 12:59 UTC, rkodev commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun search_token_filter() {
Added tests for all the data types

2021-05-25 13:21 UTC, rkodev commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  var system: String? = null,
Renamed variable to uri

2021-05-26 13:29 UTC, jingtang10 requested changes

2021-05-26 13:29 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun search_token_filter_by_coding_type() {
```suggestion
  fun search_filter_token_coding() {
```

same for all the test cases below

2021-05-26 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +
sorry that i missed this - but isn't there also `CodeableConcept`?

2021-05-26 13:29 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun search_token_filter_by_contact_point() {
add a case where there is no `use` in contact poiont.

```
fun search_filter_token_contactPoint_missingUse() {
```

2021-05-26 18:34 UTC, rkodev commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +
https://github.com/google/android-fhir/pull/461#discussion_r636709721

2021-05-27 09:44 UTC, jingtang10 approved these changes
Thanks @rkodev 👍

2021-05-27 09:54 UTC, merged