Added extenstions for Address and HumanName models to express them as string value #450
google/android-fhir pull request #464
Opened 2021-05-06 20:57 UTC by aditya-07

… a string value #450

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[450]

**Description**
The issue was related to the default toString() implementation of Address and HumanName model classes in hl7.fhir library.
The approach I have used is to provide asString() extension function for the classes and generate a default comma-separated  string as output.

**Alternative(s) considered**
N.A

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-07 05:50 UTC, aditya-07 commented
@googlebot I signed it!

2021-05-07 06:05 UTC, aditya-07 commented
@googlebot I fixed it.

2021-05-10 09:41 UTC, aditya-07 commented
@googlebot I consent

2021-05-10 09:57 UTC, jingtang10 requested changes
can you also rename the json test files? e.g `index_test_patient.json`. At the moment I think their names are still carrying thd old field names e.g. `date_test_patient.json` when it was used to test the Date type only.

2021-05-10 09:57 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +        else -> StringIndex(searchParam.name, searchParam.path, value.toString())
The `StringIndex(...)` is repeated 3 times. So I think it's better to extract a string field and call `StringIndex` constructor once.

2021-05-10 09:57 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/Util.kt
> +}
I would actually just keep these as private extension functions in `ResourceIndexer.kt` for now? Can't think of anything else beyond the indexing code that will use these things.

Also add tests!

2021-05-10 09:57 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +        StringIndex("address", "Patient.address", testPatient.addressFirstRep.asString()),
for these tests, do you think it'll make sense to use the actual strings? e.g.

```
StringIndex("address", "Patient.address", "the actual address")
```

2021-05-10 14:07 UTC, jingtang10 commented
please link issue 450 properly in the PR description

2021-05-12 09:09 UTC, jingtang10 approved these changes
Thanks @aditya-07! Approved 🎉  but with some caveats, please address the comments before merging.

Well done on your first PR!

2021-05-12 09:09 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_given() {
Actually just thinking... do we need all these `nullGiven`, `nullFamily` etc etc... Aren't they all covered in `nullValues`?

I think I'd be ok if you just remove these individual ones... What do you think?

2021-05-12 09:09 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +              listOf(null, StringType(null), StringType(""), StringType(" "), StringType("Mr."))
to make it more interesting, add another non-blank value in the prefix, given, and suffix lists.

2021-05-12 09:09 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_address_null_shouldNotIndexAddress() {
```suggestion
  fun index_string_address_nullValues_shouldNotIndexAddress() {
```

2021-05-12 09:09 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_address_empty_shouldNotIndexAddress() {
```suggestion
  fun index_string_address_emptyValues_shouldNotIndexAddress() {
```

2021-05-12 11:19 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +    return (line.filterNotNull().map { it.value } +
According to the search param definition 

> A server defined search that may match any of the string fields in the Address, including line, city, district, state, country, postalCode, and/or text

So I think we'll also have to make changes in the string search api, because this would only match the complete address.

2021-05-12 11:28 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +    return (line.filterNotNull().map { it.value } +
the string search api can match partial string: #376

2021-05-12 11:46 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +    return (line.filterNotNull().map { it.value } +
Yes but that is only with the contains modifier. 

I tested this out on the hapi fhir server here

http://hapi.fhir.org/baseR4/Patient?name=eve 
http://hapi.fhir.org/baseR4/Patient?name=adam

And adam everman is matched in both the cases without using the contains modifier. I don't think this would be the case here.

2021-05-12 13:04 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +    return (line.filterNotNull().map { it.value } +
thanks @epicadk let's continue the discussion in the issue.

2021-05-12 18:18 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  }
Yes, removing it.

2021-05-12 18:19 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_shouldNotIndexHumanName() {
Yes, it makes more sense.

2021-05-12 18:19 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_prefix() {
Unnecessary test, removing it instead.

2021-05-12 18:20 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_given() {
Unnecessary test, removing it instead.

2021-05-12 18:20 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_family() {
Unnecessary test, removing it instead.

2021-05-12 18:20 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_suffix() {
Unnecessary test, removing it instead.

2021-05-12 18:21 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +              listOf(null, StringType(null), StringType(""), StringType(" "), StringType("Mr."))
Added a non-blank prefix and suffix each and updated the expected text.

2021-05-12 18:21 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_address_null_shouldNotIndexAddress() {
Updated

2021-05-12 18:22 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_address_empty_shouldNotIndexAddress() {
Updated

2021-05-12 18:23 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_string_humanName_null_given() {
Yes, I think that would be Ok since they are all covered in a single test.

2021-05-12 19:33 UTC, merged