Add support for custom questionnaire item views
google/android-fhir pull request #467
Opened 2021-05-11 12:20 UTC by vincent-karuri

Closes #447 

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-11 15:47 UTC, jingtang10 requested changes
Thanks for taking this on @vincent-karuri! Some initial comments below.

2021-05-12 07:40 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +class QuestionnaireFragment() : Fragment() {
hmm, never knew this. I think we can keep the ViewPicker interface and have the `QuestionnaireFragment` implement it?

2021-05-12 07:40 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +import com.google.android.fhir.datacapture.views.*
sure

2021-05-12 10:35 UTC, vincent-karuri commented
@googlebot I signed it!

2021-05-12 10:50 UTC, vincent-karuri commented
While this doesn't break the datacapture gallery reference app, the date picker is modified (looks weird now).

2021-05-12 14:37 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +class QuestionnaireFragment() : Fragment() {
Fixed

2021-05-12 16:20 UTC, jingtang10 requested changes

2021-05-13 06:50 UTC, vincent-karuri commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    val questionnaireItemAdapter = QuestionnaireItemAdapter(null)
you mean remove the tests?

2021-05-13 06:51 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +open class QuestionnaireItemViewHolder(
this was required to mock the class

2021-05-13 08:33 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ViewPicker.kt
> +    fun pick(viewType: Int): QuestionnaireItemViewHolderFactory?
done

2021-05-13 08:33 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ViewPicker.kt
> +interface ViewPicker {
done

2021-05-13 18:20 UTC, kevinmost commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val mockK = "org.mockito.kotlin:mockito-kotlin:${Versions.mockK}"
Super-nit: MockK is a different mocking framework. Can we rename this to `const val mockitoKotlin`? I was about to ask if we could go with mockito-kotlin instead, but then noticed that's what this refers to. :)

2021-05-14 08:48 UTC, jingtang10 requested changes

2021-05-14 08:48 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ViewPicker.kt
> +interface ViewPicker {
Add a note on how this interface should be used.

e.g.

```
Developers wishing to define a custom view for `QuestionnaireItem`s should make sure
1. `getQuestionnaireItemViewHolderType` returns a unique type value for the `QuestionnaireItem`s, and that 
2. `getQuestionnaireItemViewHolderFactory` returns the class to generate the view holder.
```

Actually having thought about this, I think this is kinda weird for the developer to have to define the actual integer value... shouldn't we just ask for something like

```
Map<QuestionnaireItem, QuestionnaireItemViewHolderFactory>
```

And then we can work out how many new types to register depending on how many entries are in this map.

And rather than defining `ViewPicker`, the view model can just take this map?

2021-05-14 08:48 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    val questionnaireItemAdapter = QuestionnaireItemAdapter(null)
I mean if there's a default null value of the new param in the constructor of the view model, you don't need to change all the instantiation code in this test file.

2021-05-17 09:04 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ViewPicker.kt
> +interface ViewPicker {
Don't have enough context on why the current approach was used. Was mainly trying not to deviate too much from https://github.com/google/android-fhir/pull/127. The approach you mention on using a map is what we use for OpenSRP.

2021-05-17 09:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/ViewPicker.kt
> +interface ViewPicker {
Thanks for the comment! I think when I wrote the draft #127 I thought we should have exposed the type number so to give developers more control - but that seems to be a false assumption.

Glad this is aligned with OpenSRP's approach. The main trick here I think is just that as a library we will need to work out the type numbers to assign for these custom view types beyond https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt.

2021-05-26 09:37 UTC, vincent-karuri commented
> Discussed offline with @vincent-karuri. We decided we can expose a new function in the `QuestionnaireFragment` that returns a list of "matchers":
> 
> ```
> data class FactoryMatcher(
>   val factory: QuestionnaireItemViewHolderFactory,
>   val matcher: (QuestionnaireItemViewItem) -> Boolean
> )
> ```
> 
> and that in the adapter we can work out what is the view type value to use for the recycler view from this list.

@jingtang10 thinking about this, could we instead define an interface:

```
interface FactoryMatcher{
  val factory: QuestionnaireItemViewHolderFactory
  fun isMatch(QuestionnaireItemViewItem) : Boolean
}
```

so we can maintain `FactoryMatcher`s separately and simply instantiate a `FactoryMatcher` when adding it to the list of `FactoryMatcher`s. I think this might be cleaner and more maintainable than instantiating the data classes inline (especially if the matching logic is more involved)?

2021-05-26 13:55 UTC, jingtang10 commented
> > Discussed offline with @vincent-karuri. We decided we can expose a new function in the `QuestionnaireFragment` that returns a list of "matchers":
> > ```
> > data class FactoryMatcher(
> >   val factory: QuestionnaireItemViewHolderFactory,
> >   val matcher: (QuestionnaireItemViewItem) -> Boolean
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and that in the adapter we can work out what is the view type value to use for the recycler view from this list.
> 
> @jingtang10 thinking about this, could we instead define an interface:
> 
> ```
> interface FactoryMatcher{
>   val factory: QuestionnaireItemViewHolderFactory
>   fun isMatch(QuestionnaireItemViewItem) : Boolean
> }
> ```
> 
> so we can maintain `FactoryMatcher`s separately and simply instantiate a `FactoryMatcher` when adding it to the list of `FactoryMatcher`s. I think this might be cleaner and more maintainable than instantiating the data classes inline (especially if the matching logic is more involved)?

Must admit I don't really understand why it's clearner and more maintainable? In kotlin functions are first-class citizens so these two methods are kind of equivalent? The only different I can think of is that you can't inherit from the data class, which I guess is desired? because we want the list here to be a simple list of "view holder factories and when they should be used".

Not saying I'm oppoosed to using interfaces. Just don't think it's necessarily better than data class.

2021-05-26 13:56 UTC, jingtang10 commented
@kevinmost @yigit might know more as kotlin gurus.

2021-05-26 14:18 UTC, vincent-karuri commented
> > > Discussed offline with @vincent-karuri. We decided we can expose a new function in the `QuestionnaireFragment` that returns a list of "matchers":
> > > ```
> > > data class FactoryMatcher(
> > >   val factory: QuestionnaireItemViewHolderFactory,
> > >   val matcher: (QuestionnaireItemViewItem) -> Boolean
> > > )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and that in the adapter we can work out what is the view type value to use for the recycler view from this list.
> > 
> > 
> > @jingtang10 thinking about this, could we instead define an interface:
> > ```
> > interface FactoryMatcher{
> >   val factory: QuestionnaireItemViewHolderFactory
> >   fun isMatch(QuestionnaireItemViewItem) : Boolean
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so we can maintain `FactoryMatcher`s separately and simply instantiate a `FactoryMatcher` when adding it to the list of `FactoryMatcher`s. I think this might be cleaner and more maintainable than instantiating the data classes inline (especially if the matching logic is more involved)?
> 
> Must admit I don't really understand why it's clearner and more maintainable? In kotlin functions are first-class citizens so these two approaches are kind of equivalent? The only different I can think of is that you can't inherit from the data class, which I guess is desired? because we want the list here to be a simple list of "view holder factories and when they should be used".
> 
> Not saying I'm oppoosed to using interfaces. Just don't think it's necessarily better than data class.

Ok, I guess I was mainly talking about how interface implementations can be broken out into a package of `FactoryMatcher`s. Is there a way to do the same for the data classes or do they have to be defined inline?

Also not a kotlin expert but are data classes meant to hold complex logic that could be part of the lambdas?

2021-05-26 15:13 UTC, jingtang10 commented
> Ok, I guess I was mainly talking about how interface implementations can be broken out into a package of `FactoryMatcher`s. Is there a way to do the same for the data classes or do they have to be defined inline?

Yeah you can just declare `object`s in different files.

> Also not a kotlin expert but are data classes meant to hold complex logic that could be part of the lambdas?

The matcher can't be that complex? Normally just checking if the item is a certain type? I think we're good here.

2021-06-02 11:32 UTC, jingtang10 requested changes

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +   */
```suggestion
  /**
   * Returns a list of [QuestionnaireItemViewHolderFactoryMatcher]s that provide custom views for rendering items in the questionnaire. User-provided custom views will take precedence over canonical views provided by the library. If multiple [QuestionnaireItemViewHolderFactoryMatcher] are applicable for the same item, the behavior is undefined (any of them may be selected).
   */
```

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
```suggestion
    if (viewType >= numOfCanonicalWidgets)
```

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
add:

```
check(viewType < numOfCanonicalWidgets + questionnaireItemViewHolderMatchers.size)
```

or something similar

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
nit: remove this line

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
nit: remove this line

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    // canonical FHIR widgets
```suggestion
    // For custom widgets, generate an int value that's greater than any int assigned to the
    // canonical FHIR widgets
```

2021-06-02 11:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    // map custom widget viewTypes to their corresponding widget factories
```suggestion
    // Map custom widget viewTypes to their corresponding widget factories
```

2021-06-02 11:32 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/CustomDatePickerFactory.kt
> +object CustomDatePickerFactory : QuestionnaireItemViewHolderFactory(R.layout.custom_layout) {
```suggestion
object CustomNumberPickerFactory : QuestionnaireItemViewHolderFactory(R.layout.custom_layout) {
```

2021-06-02 11:32 UTC, jingtang10 commented on datacapturegallery/src/main/res/layout/custom_layout.xml
> +<?xml version="1.0" encoding="utf-8" ?>
rename file to `custom_number_picker_layout.xml`

2021-06-02 13:46 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
Not sure I understand. What should happen if this check fails?

2021-06-02 13:49 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
done

2021-06-02 13:49 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
done

2021-06-02 13:49 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
done

2021-06-02 13:49 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  }
done

2021-06-02 13:50 UTC, vincent-karuri commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/CustomDatePickerFactory.kt
> +object CustomDatePickerFactory : QuestionnaireItemViewHolderFactory(R.layout.custom_layout) {
done

2021-06-02 13:50 UTC, vincent-karuri commented on datacapturegallery/src/main/res/layout/custom_layout.xml
> +<?xml version="1.0" encoding="utf-8" ?>
done

2021-06-03 10:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
this should never happen. and if it does happen an exception will be thrown by `check` function.

2021-06-03 10:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  }
more succinct:
```
open fun getQuestionnaireItemViewHolderFactoryMatchers() =
    emptyList<QuestionnaireItemViewHolderFactoryMatcher>()
```

2021-06-03 10:45 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
cool, would this ever happen though? the method is never invoked directly so we're certain the https://github.com/google/android-fhir/pull/467#discussion_r643867705 is always true?

2021-06-03 11:08 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItemViewHolderMatchers != null && viewType >= numOfCanonicalWidgets)
added a check

2021-06-07 08:39 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  }
done

2021-06-07 12:18 UTC, jingtang10 requested changes

2021-06-07 12:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    whenever(customQuestionnaireItemViewHolderFactory.create(any())).thenReturn(mock())
can you try this:

```suggestion
    val customQuestionnaireItemViewHolderFactory: QuestionnaireItemViewHolderFactory = mock().apply{
      whenever(create(any())).thenReturn(mock())
    }
```
?

and this may even allow you to inline this variable?

2021-06-07 12:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +      QuestionnaireItemViewHolderType.values().size + 1
this fails because of the size of getQuestionnaireItemViewHolderFactoryMatchers() right? so i think you should extract an variable and do this:

```suggestion
      QuestionnaireItemViewHolderType.values().size + customFactoryMatchers.sizes
```

2021-06-09 06:30 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +      throw InvalidQuestionnaireWidgetTypeException()
done

2021-06-09 06:30 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    }
done

2021-06-09 06:30 UTC, vincent-karuri commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +
done

2021-06-09 06:38 UTC, vincent-karuri commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    assertEquals(viewFactoryMatchers[0].factory.create(mock()), actualQuestionnaireItemViewHolder)
done

2021-06-09 06:38 UTC, vincent-karuri commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +  @Test(expected = QuestionnaireItemAdapter.InvalidQuestionnaireWidgetTypeException::class)
done

2021-06-09 06:46 UTC, vincent-karuri commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    assertEquals(expectedItemViewType, actualItemViewType)
done

2021-06-09 07:53 UTC, vincent-karuri commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +    whenever(customQuestionnaireItemViewHolderFactory.create(any())).thenReturn(mock())
done

2021-06-09 07:57 UTC, vincent-karuri commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +      QuestionnaireItemViewHolderType.values().size + 1
done

2021-06-09 09:25 UTC, vincent-karuri commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/CustomQuestionnaireFragment.kt
> +class CustomQuestionnaireFragment : QuestionnaireFragment() {
I've added a questionnaire item with a dummy extension instead

2021-06-24 16:32 UTC, jingtang10 approved these changes

2021-06-24 16:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  open fun getQuestionnaireItemViewHolderFactoryMatchers() =
```suggestion
  open fun getCustomQuestionnaireItemViewHolderFactoryMatchers() =
```

maybe just add the word custom to make it clear to the app developer this is something custom and they can define?

2021-06-24 16:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +      .isEqualTo(actualQuestionnaireItemViewHolder)
```suggestion
    assertThat(
      questionnaireItemAdapter.onCreateViewHolder(
        mock(),
        QuestionnaireItemViewHolderType.values().size
      )
    ).isEqualTo(viewFactoryMatchers[0].factory.create(mock()))
```

2021-06-24 16:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +      .isEqualTo(actualQuestionnaireItemViewHolder)
also are you relying on the fact that `mock()` returns the same instance here and below in `getQuestionnaireItemViewHolderFactoryMatchers`? If so, can we just make this more explicit but creating a certain instance and checking it's the same instance?

2021-06-25 09:28 UTC, rkodev commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  open fun getQuestionnaireItemViewHolderFactoryMatchers() =
done

2021-06-25 09:29 UTC, rkodev commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +      .isEqualTo(actualQuestionnaireItemViewHolder)
done

2021-06-25 10:39 UTC, rkodev commented
@googlebot I consent.

2021-06-25 18:26 UTC, jingtang10 approved these changes

2021-06-25 18:27 UTC, jingtang10 commented
excellent - i left another nit comment. but please feel free to merge. @vincent-karuri thanks! 🎉

2021-06-30 09:20 UTC, merged