Render questionnaire in different language using translation extension
google/android-fhir pull request #478
Opened 2021-05-17 19:38 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #465

**Description**
Added extension functions to `QuestionnaireItemComponent` to provide localized prefix and text incase there is a translation available based on the users language setting. 
Translation logic tries to find the text for the current language code. If not found, it fallbacks on the language code without country code and then on the default value.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-18 09:43 UTC, jingtang10 requested changes

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +internal fun getLocalizedText(
```suggestion
private fun getLocalizedText(
```

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +/*
can you unify this file with `MoreQuestionnaireItemExtensions.kt` and `MoreQuestionnaireItemOptions.kt` and call the new file `MoreQuestionnaireItemComponents.kt`?

think it is more aligned with kotlin file conventions this way.

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +internal fun getLocalizedText(
can you make this an extension function/property on `StringType`?

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +}
can these two be properties instead of functions? what's the pros/cons?

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +class QuestionnaireItemTranslationExtensionTest {
please separate the tests for text and prefix. so you'll double the number of test cases.

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +  fun localizedValues_vietnameseTranslationAndDefaultLocale_shouldGetDefault() {
```suggestion
  fun localizedValues_vietnameseTranslation_usLocale_shouldGetUs() {
```

2021-05-18 09:43 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +  fun localizedValues_vietnameseTranslationAndDefaultLocale_shouldGetDefault() {
I suggest setting the default local to a fixed value (for example US). The reason being we don't have control of the testing environment, so leaving something to can potentially cause flakiness in tests.

2021-05-18 10:36 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +}
Yes, I can make these properties instead since we taking the default language and not passing a specific language as parameter.

2021-05-18 10:58 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +  fun localizedValues_vietnameseTranslationAndDefaultLocale_shouldGetDefault() {
@jingtang10 We can change it to `localizedText_vietnameseTranslation_usLocale_shouldGetDefault` as `shouldGetUs` would be misleading because the returned value is the default value and not tied to any language translation extension. 
What do you think?

2021-05-18 11:10 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +  fun localizedValues_vietnameseTranslationAndDefaultLocale_shouldGetDefault() {
sounds good

2021-05-18 11:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +}
sure.

2021-05-18 11:46 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +internal fun getLocalizedText(
Done

2021-05-18 11:49 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +class QuestionnaireItemTranslationExtensionTest {
I updated tests as you suggested and combined them into single MoreQuestionnaireItemComponentsTest.kt

2021-05-18 11:52 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtension.kt
> +/*
Done

2021-05-18 11:52 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemTranslationExtensionTest.kt
> +  fun localizedValues_vietnameseTranslationAndDefaultLocale_shouldGetDefault() {
Makes sense. Done!

2021-05-18 18:34 UTC, jingtang10 approved these changes
Thanks @aditya-07!

2021-05-18 18:34 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +
Remove extra line

2021-05-18 18:34 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +
Ditto

2021-05-18 18:34 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +
Ditto

2021-05-19 06:36 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +val Questionnaire.QuestionnaireItemComponent.hasNestedItemsWithinAnswers: Boolean
Done

2021-05-19 06:37 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +
Done

2021-05-19 06:37 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +
Done

2021-05-19 08:15 UTC, merged