WIP rework sync API
google/android-fhir pull request #482
Opened 2021-05-18 13:33 UTC by jingtang10

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-19 08:33 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/FhirEngine.kt
> +  suspend fun syncUpload(upload: (suspend (List<SquashedLocalChange>) -> List<LocalChangeToken>))
I think we're leaking DB abstraction here. We'll have to think of a way to do decouple keeping the abstractions.

2021-05-20 23:12 UTC, yigit requested changes

2021-05-20 23:12 UTC, yigit commented on build.gradle.kts
> +  val kotlin_version by extra("1.4.31")
for future reference, gradle 7.0 adds a much nicer way to define dependencies:

https://docs.gradle.org/7.0/release-notes.html#dependency-management-improvements

2021-05-20 23:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/SyncedResourceDao.kt
> +  }
```suggestion
  @Insert(onConflict = OnConflictStrategy.REPLACE)
  suspend fun insertAll(resources: List<SyncedResourceEntity>)
```

you don't need to do it manually, room can receive a list to insert.

2021-05-20 23:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        SyncedResourceEntity(it.key, it.value.last().meta.lastUpdated.toTimeZoneString())
are these guaranteed to be ordered?

2021-05-20 23:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    upload(database.getAllLocalChanges()).forEach { database.deleteUpdates(it) }
you probably want this in a transaction ?

2021-05-20 23:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    upload(database.getAllLocalChanges()).forEach { database.deleteUpdates(it) }
also, you may want to check again for local changes and call it back again if there are new local changes after the sync call? (e.g. while(localHcanges.isNotEmpty() { .. }

2021-05-20 23:12 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +      } catch (e: IOException) {}
we need to figure and and document what the expectation is here.
if they need to catch exceptions, lets document it in syncDownload

2021-05-20 23:12 UTC, yigit commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +    lifecycleScope.launch {
you don't want lifecycle scope here (as it will be cancelled if activity disappears).

I know this is just tesst code but you usually want an application level scope here to run the work and observe the reesult. if UI disappears, sync still happens just no notification in the UI.

2021-05-20 23:12 UTC, yigit commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +    lifecycleScope.launch {
keeep in mind, if you change this to be an application level scope, then the code shouldn't be here as it would leak the activity.

2021-05-24 11:35 UTC, jingtang10 commented on build.gradle.kts
> +  val kotlin_version by extra("1.4.31")
reverting this change. added a new issue #492

2021-05-24 12:19 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/dao/SyncedResourceDao.kt
> +  }
done

2021-05-25 09:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +        SyncedResourceEntity(it.key, it.value.last().meta.lastUpdated.toTimeZoneString())
fixed.

2021-05-25 10:38 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +    upload(database.getAllLocalChanges()).forEach { database.deleteUpdates(it) }
pushed this into the db class for transaction.

2021-05-25 11:59 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +      } catch (e: IOException) {}
ack. i made note - @deepankarb is working on this.

2021-05-26 05:16 UTC, yigit requested changes
sorry i miseed it in the first CL but can you add more tests here. this part is fairly tricky so would be good to test well.

2021-05-26 05:16 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      }
Lets not call user code in a transaction, if they try to access back into the database, bad things might happen.

```suggestion
    var localChanges = getAllLocalChanges()
      while (localChanges.isNotEmpty()) {
         val uploaded = upload(localChanges)
         deleteUpdates(uploaded)
         localChanges = getAllLocalChanges()
      }
```

now that suggestion hits into a race condition hence we need to have a mutex around this to avoid concurrent access.

2021-05-26 05:16 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +    db.withTransaction {
same here. basically, during this method we are holding a database lock and because they are doing network, it might lock for a very long time.

2021-05-26 05:16 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +  val retry: Boolean = false
where is this used?

2021-05-26 05:16 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> -        exceptions.add(ResourceSyncException(syncData.resourceType, exception))
you should avoid catching CancelationException here. it would be also good to have a test that we handle cancelation properly (coroutine cancelation happens via CancelationExceptions)

2021-05-27 16:08 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +    db.withTransaction {
done

2021-05-27 16:08 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      }
done

2021-05-27 16:10 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +  val retry: Boolean = false
https://github.com/google/android-fhir/issues/506

2021-05-27 16:11 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> -        exceptions.add(ResourceSyncException(syncData.resourceType, exception))
https://github.com/google/android-fhir/issues/507

2021-05-27 20:14 UTC, yigit approved these changes

2021-06-02 08:15 UTC, merged