Kj/repeating answers
google/android-fhir pull request #490
Opened 2021-05-21 17:03 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #216  partially

**Description**
Adding functionality to handle multiple answer for choice type question

**Type**
Feature

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-24 10:55 UTC, jingtang10 reviewed
Thanks @joiskash!

For every type of widget, adding the question value to the questionnaire item is going to be very similar anyway. the variability is in the UI class. so I feel like maybe we can do without the new abstract methods. What do you think? Don't feel like they're adding anything...

2021-05-24 11:52 UTC, joiskash commented
> 
> 
> Thanks @joiskash!
> 
> For every type of widget, adding the question value to the questionnaire item is going to be very similar anyway. the variability is in the UI class. so I feel like maybe we can do without the new abstract methods. What do you think? Don't feel like they're adding anything...

Yes I agree, instead of having these abstract method, each UI class can implement its own method to add and remove views for new answers. In the case of checkbox it is trivial because you can just tick as many as you wish.

2021-05-26 08:07 UTC, aditya-07 requested changes
Added a few comments. Please take a look.

2021-05-26 08:07 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +          }
Can we extract the view creation logic into a separate function for better readability?

2021-05-26 09:16 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        val answer = questionnaireResponseItem.answer
done

2021-05-26 09:16 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        var index = 0
done

2021-05-26 09:17 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +          }
done

2021-05-26 09:25 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +          }
done

2021-05-26 09:26 UTC, joiskash commented
> 
> 
> Added a few comments. Please take a look.

Thanks for the review, I have pushed the changes. Please have a look

2021-05-26 09:40 UTC, aditya-07 approved these changes

2021-05-26 13:35 UTC, jingtang10 requested changes

2021-05-26 13:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +      }
just remove these two?

2021-05-26 13:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        val linearLayout = LinearLayout(checkboxGroup.context)
at this point i think i would just define a layout file for this?

2021-05-26 17:24 UTC, joiskash commented on datacapture/src/main/res/layout/questionnaire_item_checkbox_group_view.xml
> +
done

2021-05-26 17:25 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        val linearLayout = LinearLayout(checkboxGroup.context)
done

2021-05-27 09:40 UTC, jingtang10 requested changes

2021-05-27 09:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    }
```suggestion
   check(questionnaireItem.repeats) { "Questionnaire item with linkId ${questionnaireItem.linkId} does not allow repeated answers" }
```

2021-05-27 09:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    }
```suggestion
    check(questionnaireItem.repeats) { "Questionnaire item with linkId ${questionnaireItem.linkId} does not allow repeated answers" }
```

2021-05-27 09:40 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryInstrumentedTest.kt
> +        },
just remove this it's covered by the previous test case

2021-05-27 09:40 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryInstrumentedTest.kt
> +}
I thin the test here should be 1) add answer and 2) remove answer.

single or more answers don't really matter and is not what we need to test in my opinion.

2021-05-27 10:11 UTC, jingtang10 commented
can you also change the PR title to something more readable please? thanks

2021-05-27 10:59 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        val displayText = singleCheckBox.findViewById<TextView>(R.id.single_check_box_text)
done

2021-05-27 11:03 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    }
done

2021-05-27 11:04 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
> +    }
done

2021-05-27 11:20 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryInstrumentedTest.kt
> +        },
done

2021-05-27 11:27 UTC, joiskash commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryInstrumentedTest.kt
> +}
done

2021-05-27 14:14 UTC, jingtang10 approved these changes
Thanks @joiskash 👍

2021-05-27 14:56 UTC, merged