Basic pagination support in Questionnaires
google/android-fhir pull request #497
Opened 2021-05-25 15:30 UTC by kevinmost

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #186 

**Description**
Adds basic pagination support to Questionnaires.

Does not validate Questionnaire format when loading questionnaire, or validate responses when switching pages.

Only supports pagination if top-level items are of type `GROUP` and all have attached `code: "page"` extensions.

**Type**
Choose one: Feature

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/3058312/119525327-64b9e280-bd4c-11eb-86f7-3dc103230224.png)
![image](https://user-images.githubusercontent.com/3058312/119525459-84e9a180-bd4c-11eb-91c2-8b457d2b31fa.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-05-26 15:20 UTC, jingtang10 requested changes
Thanks @kevinmost!

2021-05-26 15:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                .items
this feels slightly odd to me. kinda feels like you can split this `getQuestionnaireState` into one where you only deal with items and another where you deal with pagination? might make the code look neater?

2021-05-27 16:47 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +        println("kmost: state ${state.items.size} items. Pagination: ${state.pagination}")
Oops, will remove this :)

2021-05-27 20:11 UTC, yigit submitted a review, later dismissed

2021-05-27 20:11 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      viewModel.pageFlow.value = viewModel.pageFlow.value!!.previousPage()
it is better to keeep the visible flow readonly and have methods in view model to change its state instead of exposing mutable state flow

2021-05-27 20:11 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    modificationCount.combine(pageFlow) { _, _ -> questionnaireState }
i was initially confused by this `questionnaireState` field.
more specifically i don't think this is a field.

The test (which seems like the only place we access) can use `questionaireStateFlow.first()`. For the ViewModel, i think it is better as a method then a property. (or just inlined to the flow)

2021-05-27 20:11 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    modificationCount.combine(pageFlow) { _, _ -> questionnaireState }
also, you may want to cache this in the view model (shareIn(viewModelScope) or stateIn) that would also make it a shared flow.

2021-05-31 13:28 UTC, fredhersch commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +          ),
Absolutely. Thanks

2021-06-02 12:15 UTC, kevinmost commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +          ),
Removed patient-registration.json

2021-06-02 12:20 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun QuestionnairePagination.previousPage(): QuestionnairePagination {
It isn't an action, though. They return a new page object, which we use to set the value of our `Flow<QuestionnairePagination?>`.

Eg, we use it as `viewModel.pageFlow.value = viewModel.pageFlow.value!!.nextPage()`.

`viewModel.pageFlow.value = viewModel.pageFlow.value!!.goToNextPage()` feels wrong, as it implies that the function has a side-effect, which it doesn't.

2021-06-02 12:20 UTC, kevinmost commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +
Agreed, I was actually only using these tests to probe at the HAPI structures and see what they output for a given JSON input. Removing.

2021-06-02 12:20 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +        if (state.pagination != null) {
I considered that, but didn't think it was worth the performance penalty of an unnecessary nested view. The visibility is still only changed in one place here, and we get to keep a flat view hierarchy.

2021-06-02 12:24 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      viewModel.pageFlow.value = viewModel.pageFlow.value!!.previousPage()
Turned the MutableStateFlow into a backing property `_pageFlow`, and exposed immutable Flow `pageFlow` and a `goToPage` method.

2021-06-02 12:25 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      viewModel.pageFlow.value = viewModel.pageFlow.value!!.previousPage()
Changed to these 3 members

```
  private val _pageFlow =
    MutableStateFlow<QuestionnairePagination?>(questionnaire.getInitialPagination())

  internal val pageFlow: StateFlow<QuestionnairePagination?>
    get() = _pageFlow

  internal fun goToPage(page: QuestionnairePagination) {
    _pageFlow.value = page
  }
```

2021-06-02 12:33 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +    modificationCount.combine(pageFlow) { _, _ -> questionnaireState }
Agreed. Only exposing `questionnaireStateFlow` now.

Any preference for `shareIn` vs `stateIn`? I used the former.

2021-06-02 12:40 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun QuestionnairePagination.previousPage(): QuestionnairePagination {
Yigit suggested not exposing the `pageFlow` outside of the ViewModel, which also led to exposing `goToNextPage` and `goToPreviousPage` methods on the actual ViewModel, and not on the pagination objects.

2021-06-02 12:41 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>     * items and the list of items in the questionnaire response answer list and populate
done

2021-06-02 12:42 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +      viewModel.pageFlow.value = viewModel.pageFlow.value!!.previousPage()
Actually, no need to expose that `StateFlow` either. Just doing this:

```kt
  private val pageFlow =
    MutableStateFlow<QuestionnairePagination?>(questionnaire.getInitialPagination())

  internal fun goToPreviousPage() {
    pageFlow.value = pageFlow.value!!.previousPage()
  }

  internal fun goToNextPage() {
    pageFlow.value = pageFlow.value!!.nextPage()
  }
```

2021-06-02 12:47 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +                .items
I tried to separate this out, but the items themselves rely on knowing the pagination. See this line:

```kt
if (pagination != null && pagination.currentPageIndex != index) {
```

So I don't think we can make a function that returns the `List<QuestionnaireItemViewItem>` without passing in a `QuestionnairePagination?`.

2021-06-03 17:05 UTC, jingtang10 approved these changes

2021-06-22 15:55 UTC, merged