Added onFocusChangeListner and RequiredConstraintValidator.kt
google/android-fhir pull request #511
Opened 2021-05-28 10:40 UTC by kunjan8794

Fixes #470 

**Description**
Handle the required field in the questionnaires - add validator

**Type**
Feature

**Checklist**
- [X] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [X] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [X] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [X] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [X] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [X] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [X] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [X] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-02 12:09 UTC, jingtang10 requested changes

2021-06-02 12:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +          RequiredConstraintValidator.validate(
i don't think it's right to call the RequiredConstraintValidator individually. it should be added to the list of validators used to validate any question item and answer.

2021-06-02 12:09 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RequiredConstraintValidatorTest.kt
> +    Truth.assertThat(validationResult.isValid).isTrue()
import Truth

2021-06-07 15:03 UTC, jingtang10 approved these changes
Thanks! Just a comment on enablement evaluation as well.

2021-06-07 15:03 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
>        questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
do you think we can move line 53-54 to the on focus change listener too?

2021-06-08 06:47 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
>        questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
@jingtang10 
We could do that, but possibly, can there be a scenario where a user is filling up the form, and then doesn't really lose focus on the last element and then clicks on the submit button?

2021-06-08 12:00 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
>        questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
yes and the same argument can be made for the required field validator. should we move the required field validation back as well?

i think we were leaning towards only validate when the user is moving away from the widget. but having thought about this a little more, on mobile we don't really have the signal for moving away from a widget... the user could scroll down but the 'focus' is not lost on the widget. so maybe we should just keep everything in the change listener?

2021-06-09 07:52 UTC, kunjan8794 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
>        questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
So again in that case, if we think about the RequiredConstraintValidator, if someone does not ever touch a required component, then the text change listener might never get called and the warning might never be displayed.

2021-06-09 09:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
>        questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
discussed this with @fredhersch.. he raised the point that if the user starts to type we don't want to show an error message before they finish typing (it would seem quite annoying).

i'm happy for us to leave it as is in this PR and maybe come back to refine where exactly the validation is called (and potentially adding an option for the developer to specify a mode)

2021-06-09 09:16 UTC, jingtang10 approved these changes

2021-06-09 09:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> -        )
slightly odd this is removed by the same isn't removed in the date picker file?

2021-06-15 14:16 UTC, Tarun-Bhardwaj commented
Hi @kunjan8794 , did you get a chance to resolve this issue?

2021-06-22 09:16 UTC, jingtang10 approved these changes

2021-06-22 09:16 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    <string name="max_value_validation_prefix">Maximum value allowed is:</string>
use this: https://developer.android.com/guide/topics/resources/localization#mark-message-parts

```suggestion
    <string name="min_value_validation_error_msg">Minimum value allowed is: <xliff:g id="min_value">%1$f</xliff></string>
    <string name="max_value_validation_error_msg">Maximum value allowed is: <xliff:g id="max_value">%1$f</xliff></string>
```

2021-06-22 09:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
> +      context.getString(R.string.min_value_validation_prefix) + extension.value.primitiveValue()
```suggestion
      context.getString(R.string.min_value_validation_error_msg, extension.value.primitiveValue())
```

2021-06-28 14:11 UTC, jingtang10 approved these changes

2021-06-29 08:58 UTC, jingtang10 approved these changes

2021-06-29 09:28 UTC, merged