Added Patient search in reference app.
google/android-fhir pull request #518
Opened 2021-05-31 20:23 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #385

**Description**
Provides a way to search Patient by name property.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**
![Screenshot_1622492453](https://user-images.githubusercontent.com/18224849/120239483-fdd08800-c27b-11eb-94f0-65e18b12f30d.png)
![Screenshot_1622492498](https://user-images.githubusercontent.com/18224849/120239485-0032e200-c27c-11eb-8cbd-365ad23fefb5.png)
![Screenshot_1622492508](https://user-images.githubusercontent.com/18224849/120239486-00cb7880-c27c-11eb-9012-12156444c2d6.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-01 06:13 UTC, FikriMilano reviewed
Nice pr @aditya-07 , some comments below.

2021-06-01 06:13 UTC, FikriMilano commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +          return true
return false if the newText has not been handled by the listener
`newText != null`

https://developer.android.com/reference/android/widget/SearchView.OnQueryTextListener.html#onQueryTextChange(java.lang.String)

2021-06-01 06:13 UTC, FikriMilano commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +          return true
Same, return false if the query has not been handled by the listener
`query != null`

https://developer.android.com/reference/android/widget/SearchView.OnQueryTextListener.html#onQueryTextSubmit(java.lang.String)

2021-06-01 16:52 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +          patientListViewModel.searchPatientsByName(newText!!)
`newText` is never going to be null. Updated the signature.

2021-06-01 16:52 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +          patientListViewModel.searchPatientsByName(query!!)
`query ` is never going to be null. Updated the signature.

2021-06-01 16:54 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +          return true
`newText` is never going to be null. Updated the signature.

2021-06-01 16:54 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
> +          return true
Update signature, change not needed.

2021-06-02 15:38 UTC, jingtang10 requested changes

2021-06-02 15:38 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +    fetchAndPost { if (nameQuery.isEmpty()) getSearchResults() else getSearchResults(nameQuery) }
can you unify these two functions? maybe remove the old search function as it's no longer correct to filter by address city.

2021-06-02 16:03 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemRecyclerViewAdapter.kt
> +    ): Boolean = oldItem.name == newItem.name
`PatientListViewModel.PatientItem.id` is not the unique `Patient.id` but just the index of PatientListViewModel.PatientItem in the adapter. This causes issues when adapter's data is updated as two completely different `PatientListViewModel.PatientItem` objects but at the same index get labeled same.

Instead of reverting the change, I will add the unique `Patient.id` to  the PatientListViewModel.PatientItem and do the comparison using it.

2021-06-03 08:36 UTC, jingtang10 approved these changes

2021-06-03 09:38 UTC, merged