Add max/min length validators for questionnaire
google/android-fhir pull request #526
Opened 2021-06-01 17:38 UTC by stevenckngaa

The max/min length validators are only enforced on answers that
are in the the following FHIR primitive types:
1. BooleanType
2. DecimalType
3. IntegerType
4. DateType
5. TimeType
6. StringType
7. UriType

This list is an intersection of the FHIR primitive types & the FHIR
questionnaire response supported types.

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-03 10:26 UTC, jingtang10 requested changes

2021-06-03 12:17 UTC, joiskash reviewed
Thanks @stevenckngaa , great work. I just pointed out a few nits which probably got missed out when the validation package was added. Do have a look

2021-06-03 12:17 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +            this.setValue(IntegerType(20))
Can we use `value = IntegertType(20)` instead of `this.setValue`?

2021-06-03 12:17 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/PrimitiveTypeAnswerMaxLengthValidator.kt
> +    questionnaireItem: Questionnaire.QuestionnaireItemComponent,
Why are we not passing the questionnaireItemViewItem but instead passing the questionnaireItem and questionnaireResponseItem separately? Seems like that is the current design in the ConstraintValidator.. just wanted to know the thought behind this.

2021-06-03 12:32 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +            this.setValue(IntegerType(20))
agree with this. i think this is more idiomatic.

2021-06-08 18:03 UTC, stevenckngaa commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +            this.setValue(IntegerType(20))
For some reason value is a val. I can't use the assignment operator. This is really strange. :(

2021-06-09 11:43 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/PrimitiveTypeAnswerMaxLengthValidator.kt
> +    questionnaireItem: Questionnaire.QuestionnaireItemComponent,
I see `questionnaireItemViewItem` as a UI thing. Its purpose is to encapsulate information required for the recycler view to display an item in the questionnaire item list. It does contain both the question item and the response item. But it may also contain other things that are used for the UI (for example call back to refresh the visibility of other questions depending on the answer to the current question).

The validation API here should not depend on UI classes. It can be used separately (in fact @joiskash is building a separate API for validation) so I think it would be wrong to use the questionnaireItemViewItem.

Open for discussion of course - but this is my thought process.

2021-06-09 17:08 UTC, jingtang10 approved these changes
Thanks @stevenckngaa!

2021-06-10 07:56 UTC, jingtang10 commented
please run `./gradlew spotlessApply` or simply `./gradlew sA`

2021-06-10 13:42 UTC, merged