Added Navigation library to Reference app.
google/android-fhir pull request #533
Opened 2021-06-03 12:27 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #505

**Description**
1. Added Navigation library to Reference app. 
2. Made it Single Activity app.
3. Fixed the patient details page.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-08 16:41 UTC, jingtang10 requested changes

2021-06-08 16:41 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientsActivity.kt
> +    val toolbar = findViewById<Toolbar>(R.id.toolbar)
opt: add a new line before this line

2021-06-08 16:41 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/data/SamplePatients.kt
> +  fun getObservationItems(
can you keep this in `PatientDetailsViewModel.kt`? I would like to get rid of this class at some point.

2021-06-08 16:41 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/data/SamplePatients.kt
> +    fhirPatients: List<Observation>
```suggestion
    observations: List<Observation>
```

2021-06-08 16:41 UTC, jingtang10 commented on reference/src/main/res/layout/fragment_patient_list.xml
> +        app:queryHint="Find by Patient Name"
put this in the resources: `strings.xml`

2021-06-08 16:41 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    if (modelClass.isAssignableFrom(PatientDetailsViewModel::class.java)) {
maybe use `require` https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html ?

2021-06-08 16:41 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    return samplePatients.getPatientItems(listOf(patient))?.first()
i really think this should be in this class rather than in the `SamplePatients.kt`

can you move this to this class and try to get rid of `SamplePatients.kt`?

2021-06-14 09:28 UTC, aditya-07 commented on reference/src/main/AndroidManifest.xml
> +            android:name="com.google.android.fhir.reference.PatientsActivity"
Done

2021-06-14 09:29 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
> +      }
Done

2021-06-14 09:29 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/data/SamplePatients.kt
> +  fun getObservationItems(
Done

2021-06-14 09:29 UTC, aditya-07 commented on reference/src/main/res/layout/fragment_patient_list.xml
> +        app:queryHint="Find by Patient Name"
Done

2021-06-14 09:29 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    if (modelClass.isAssignableFrom(PatientDetailsViewModel::class.java)) {
Done

2021-06-14 09:32 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    return samplePatients.getPatientItems(listOf(patient))?.first()
Refactored some code. Moved the main code to PatientListViewModel.

2021-06-14 09:37 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientsActivity.kt
> +    val toolbar = findViewById<Toolbar>(R.id.toolbar)
done

2021-06-14 09:40 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
>  class PatientDetailFragment : Fragment() {
Done

2021-06-14 11:04 UTC, jingtang10 approved these changes

2021-06-14 11:59 UTC, merged