Edit Patient Functionality Added
google/android-fhir pull request #536
Opened 2021-06-04 13:31 UTC by MuhammadSalman-7214

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[https://github.com/google/android-fhir/issues/273]

**Description**
To get all the information about the patient and then generate a Questionnaire Response based on the patient details fetched using fhirpathengine

**Alternative(s) considered**
Not considered any alternatives, as this approach was already finalized for this issue
**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-04 16:18 UTC, jingtang10 reviewed
Thanks @MuhammadSalman-7214! Can you add some tests for this?

2021-06-07 09:50 UTC, MuhammadSalman-7214 commented
sure @jingtang10

2021-06-10 16:59 UTC, jingtang10 requested changes
can you revert the changes to delete the issue templates?

2021-06-10 17:02 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    return patientResource
```suggestion
    return Patient().apply {
      active = true
      birthDate = Date(1996, 8, 17)
      gender = Enumerations.AdministrativeGender.MALE
      address = Address().apply {
        ...
      }
    }
```

2021-06-11 05:03 UTC, MuhammadSalman-7214 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
I have added this dependency because to test fhirpathengine.evaluate function in unit test, it requires fhir engine dependency to be added in the gradle to have it available in the data capture module, otherwise the test doesn't pass.

2021-06-11 05:05 UTC, MuhammadSalman-7214 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val fhirEngine = "com.google.android.fhir:engine:${Versions.fhirEngine}"
if I'll revert it here, then where can I add the fhir engine dependency?

2021-06-11 05:05 UTC, MuhammadSalman-7214 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val fhirEngine = "0.1.0-alpha02"
if I'll revert it here, then where can I add the fhir engine dependency?

2021-06-11 05:09 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    return patientResource
Okay

2021-06-11 10:55 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
can you check fhir path engine's namespace? it's not in our fhir engine lib. it comes from hapi structures lib.

2021-06-11 10:55 UTC, jingtang10 commented
please address the comments from the last review in the code. thanks!

2021-06-11 10:56 UTC, jingtang10 commented
especially revert the deletion of the issue template files.

2021-06-11 13:35 UTC, MuhammadSalman-7214 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
@jingtang10 can you please elaborate? I understand that fhirpathengine is not in our local fhir engine lib, but what should we do to make test run successfully?

2021-06-11 13:41 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
you need to add dependency to hapi. you can find it in fhir engine's dependencies.

2021-06-14 09:46 UTC, MuhammadSalman-7214 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
@jingtang10 facing the following error, if I don't include the dependency in sdc build.gradle file explicitly

java.lang.NoClassDefFoundError: org/fhir/ucum/UcumException

	at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractAnswersFromExpression(ResourceMapper.kt:110)
	at com.google.android.fhir.datacapture.mapping.ResourceMapper.populate(ResourceMapper.kt:92)
	at com.google.android.fhir.datacapture.mapping.ResourceMapperTest.populateResourceAnswers(ResourceMapperTest.kt:968)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.fhir.ucum.UcumException
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:164)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:119)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:112)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:111)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
	
	whereas api(Dependencies.hapiFhirStructuresR4) is already present in sdc build.gradle file

2021-06-15 10:46 UTC, jingtang10 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
ok that's odd -- it maybe because of this file that is missing https://github.com/google/android-fhir/blob/master/engine/src/main/java/org/fhir/ucum/UcumException.kt

Can you try to upgrade our hapi dependency to 5.4.0 which was released end of may?

If that doesn't fix it can you update this bug https://github.com/hapifhir/hapi-fhir/issues/2443 and also send an email to the hapi fhir discussion group? https://groups.google.com/g/hapi-fhir?pli=1

also try to include the ucum exeption file to the sdc lib maybe the only other local fix we can do (and any client using both engine and sdc migth need to exclude the dupilcated file which might be a bit nasty...)

2021-06-16 08:26 UTC, MuhammadSalman-7214 commented on datacapture/build.gradle.kts
> +  implementation(Dependencies.fhirEngine)
Thanks @jingtang10. After adding UcumException to sdc and also adding caffeine dependency, it is now working and I have removed the explicitly added dependency of fhir engine from sdc build.gradle as well. I have pushed the PR as well. You can review. Thanks.

2021-06-16 14:40 UTC, jingtang10 requested changes
thanks @MuhammadSalman-7214 - some high-level comments first.

can you ask @ekigamba and/or @shoaibmushtaq25 to leave a review since they worked on the extraction process? thanks!

2021-06-16 14:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
why only care about the first item?

2021-06-16 14:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  ) {
two things about this function signature

1. i dislike the idea that you are using an implicit out param... why not just return a map?
2. i think this should be an extension function on `QuestionnaireItemComponent`

2021-06-16 14:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      val questionType = answerExtracted[0]
shouldn't all the extracte values be used if the question has repeated answers?

2021-06-16 14:40 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        }
always extract this type of operation into a utility function. this is making the logic of this function very hard to read.

2021-06-16 17:48 UTC, MuhammadSalman-7214 commented on datacapture/build.gradle.kts
> +  }
if I don't add this, then files duplication error comes

2021-06-16 17:55 UTC, MuhammadSalman-7214 commented on .idea/jarRepositories.xml
> -<?xml version="1.0" encoding="UTF-8" ?>
was facing some problems in code, delete the build, ideas folder, because of which this file got removed

2021-06-16 17:55 UTC, MuhammadSalman-7214 commented
> thanks @MuhammadSalman-7214 - some high-level comments first.
> 
> can you ask @ekigamba and/or @shoaibmushtaq25 to leave a review since they worked on the extraction process? thanks!

Sure @jingtang10

2021-06-16 17:57 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      val questionType = answerExtracted[0]
currently I am only handling it for a single answer, not including multiple answers

2021-06-16 17:59 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
because all questionnaires currently have questions inside first item, so that is why just taking the first item, and then catering all the questions within it

2021-06-16 18:01 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun populate(questionnaire: Questionnaire, resource: Resource): HashMap<String, Any> {
The reason not generating QuestionnaireResponse is that QuestionnaireResponse wants answers against each and every link Id, whereas we don't have answer for every link Id that is present in the Questionnaire, so I am returning Hashmap, and setting the values as initial values to Questionnaire.

2021-06-16 18:02 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        }
okay

2021-06-16 18:03 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  ) {
okay

2021-06-17 06:35 UTC, shoaibmushtaq25 commented
I have reviewed this PR and it looks good to me. Let's wait for @ekigamba to also review it as he did the major work on ResourceMapper in parallel to me. cc: @MuhammadSalman-7214 @jingtang10

2021-06-17 16:56 UTC, MuhammadSalman-7214 commented
@jingtang10 update the PR as per your comments, kindly review, thanks.

2021-06-21 06:37 UTC, ekigamba requested changes

2021-06-21 06:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
I also think that you should care about all the items

2021-06-21 06:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun populate(questionnaire: Questionnaire, resource: Resource): QuestionnaireResponse {
1. Change the PR title to `Implement Expression-based population`
2. Is this supposed to support population from multiple resources eg. edit patient functionality will require populating using both the Patient and RelatedPerson. I think this is clearly stated https://github.com/opensrp/fhircore/issues/184 and https://github.com/opensrp/fhircore/issues/185

2021-06-21 06:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
I think that Expression-based population should only be activated if there is a `questionnaire-launchContext`. I still think that this should be OK since the application knows the Resource used in population

cc @Rkareko

2021-06-21 06:50 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun populate(questionnaire: Questionnaire, resource: Resource): QuestionnaireResponse {
@ekigamba I have done that for editing of Related Person as well, will be pushing it shortly

2021-06-21 06:51 UTC, ekigamba requested changes

2021-06-21 06:51 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        singleQuestion.item.forEach { question ->
I think we have a case where we might have multiple levels eg. `Patient.Contact.HumanName` where HumanName group has it's own questions i.e. given and family. The example can be found in the `ResourceMapperTest#extract()`

2021-06-21 06:51 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      if (singleQuestion.type == Questionnaire.QuestionnaireItemType.GROUP) {
If we decide to support population from multiple resources, we might need to support the extension `questionnaire-itemPopulationContext`. I think @Rkareko and @jingtang10 can provided better direction on this. One of it's purpose would be switching the resource population context

2021-06-21 06:53 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        singleQuestion.item.forEach { question ->
but that already has been cared of in this extension function fetchExpression() which will find expression in every item in a group

2021-06-21 06:55 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      if (singleQuestion.type == Questionnaire.QuestionnaireItemType.GROUP) {
I don't think so we need that, as fetchexpression() is already fetching extensions for GROUP as well as single items base on the loop, but still we can discuss

2021-06-21 06:56 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        singleQuestion.item.forEach { question ->
as we have to define initial expression extension for all the questions that we want an answer or that we want to edit

2021-06-21 06:58 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
this should be okay then as we are checking for the ITEM_CONTEXT_EXTENSION_URL for the same way as above

2021-06-21 07:30 UTC, ekigamba requested changes

2021-06-21 07:30 UTC, ekigamba commented on datacapture/build.gradle.kts
> +  }
Does this still happen even with the removed fhir engine dependency?

2021-06-21 07:30 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          StringType(this.family)
I see that we are returning a `StringType`. If the type is `HumanName` is the type returned supposed to be a `StringType` or a `HumanName`?

2021-06-21 07:30 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return if (questionLinkId.contains("family")) {
This should not be dependent on the linkId. Kindly change this to something more generic

2021-06-21 07:30 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return if (questionLinkId.contains("country")) {
This should not be dependent on the linkId. Kindly change this to something more generic

2021-06-21 07:30 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return StringType(this.value)
It is also not clear why this is returning a `StringType` if the expected type is `ContactPoint`. I see that we return the correct types here https://github.com/google/android-fhir/blob/feature/add-edit-patient-functionality/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt#L163

2021-06-21 07:30 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +              "definition": "http://hl7.org/fhir/StructureDefinition/Patient#Patient.address.country",
Add a question for `Patient.contact` with `Patient.contact.HumanName`

2021-06-21 08:10 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          StringType(this.family)
it's supposed to be a String type here as I'll set the String type value based on Question linkId

2021-06-21 08:11 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return if (questionLinkId.contains("family")) {
yeah can you suggest what should it be?

2021-06-21 08:11 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return if (questionLinkId.contains("country")) {
yeah can you suggest what should it be?

2021-06-21 08:12 UTC, ekigamba requested changes

2021-06-21 08:12 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.telecom",
I believe this should be something like `Patient.telecom.value`

2021-06-21 08:12 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return StringType(this.value)
because I'll set all these values as per their link Id's. Will elaborate you on call

2021-06-21 08:13 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.name",
we cannot say, it is wrong, though we can use it directly as Patient.name.given as well

2021-06-21 08:23 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.telecom",
no it does not work with this as the value is for contact point not for telecome

2021-06-21 08:28 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.address",
private fun Base.getType(questionLinkId: String): Type? {
    when {
      this.isDateTime -> {
        return (this as DateType)
      }
      this.isBooleanPrimitive -> {
        return (this as BooleanType)
      }
      this.isPrimitive -> {
        return StringType((this as Enumeration<*>).code)
      }
      this is HumanName -> {
        return if (questionLinkId.contains("family") && questionLinkId.contains("related")) {
          StringType(this.family)
        } else if (questionLinkId.contains("name") && questionLinkId.contains("related")) {
          this.given[0]
        } else if (questionLinkId.contains("family")) {
          StringType(this.family)
        } else {
          this.given[0]
        }
      }
      this is Address -> {
        return if (questionLinkId.contains("country")) {
          StringType(this.country)
        } else {
          StringType(this.city)
        }
      }
      this is ContactPoint -> {
        return StringType(this.value)
      }
    }
    return null
  }
  this function is already calling from populate function, so I don't think there is a separate need for this

2021-06-21 08:30 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.address",
for all your above comments

2021-06-21 08:31 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.address",
only thing to change is to make linkId thing more generic

2021-06-21 08:58 UTC, ekigamba requested changes

2021-06-21 08:58 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +              "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemContext",
Kindly remove these extensions that specify the Base type. This is no longer supported and the extraction should work without this

2021-06-21 08:58 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.address",
Is there an official example that can lead on how the population of compound/composite questions is supposed to be authored?

2021-06-21 09:02 UTC, Rkareko commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.name",
We should look into creating a FHIRPath expression that fetches the family name

2021-06-21 10:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  fun populate(questionnaire: Questionnaire, resource: Resource): QuestionnaireResponse {
I support doing multiple resources in a following PR (trying to separate things)

2021-06-21 10:06 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
thanks @MuhammadSalman-7214 I think in your reply you just stated _what it is now_ rather than responding to the suggest of _what it should/can/ought to be_.

2021-06-21 10:07 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
could potentially add a check and throw an exception @ekigamba what do you think?

e.g. `check(questionnaire.hasLaunchContextEtc(), "Does not have launch context etc etc")`

2021-06-21 10:13 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.telecom",
@ekigamba can this be `Patient.telecom.where(system='phone')` or something similar?

2021-06-21 10:38 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.name",
@jingtang10 I mean to say we can extract the value of name in both ways as Patient.name.given from expression as well as from Patient.name expression as well, are you clear on it now?

2021-06-22 15:22 UTC, MuhammadSalman-7214 commented
@ekigamba and @jingtang10 all changes are done as per your comments, please review, thanks.

2021-06-23 11:31 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val questionnaireItemList = questionnaire.item[0].item
I agree @jingtang10, I guess we can probably have helper functions on the SDK. It seems that the extension is not referenced on this function since this happens outside this function?

2021-06-23 11:34 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +                    "expression": "Patient.telecom",
@jingtang10 Yea, I think that's a better expression since `Patient.telecom` is a list

2021-06-23 12:02 UTC, ekigamba requested changes

2021-06-23 12:02 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun setInitialValue(
I also think this function name should be `setInitialValueForItemList`

2021-06-23 12:04 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      setInitialValue(question.item, answersHashMap)
thanks

2021-06-23 12:05 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun fetchExpressionsFromQuestionnaire(
okay

2021-06-23 12:05 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun fetchExpressions(
okay

2021-06-23 12:05 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    if (question.type == Questionnaire.QuestionnaireItemType.GROUP) {
thanks :-)

2021-06-23 12:05 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun setInitialValueToAllItems(
okay

2021-06-23 12:06 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun setInitialValue(
okay

2021-06-23 12:54 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private val expressionMap: HashMap<String, String> = hashMapOf()
okay, that is fine

2021-06-23 15:06 UTC, ekigamba approved these changes

2021-06-24 13:54 UTC, jingtang10 requested changes
Thanks @MuhammadSalman-7214!

2021-06-24 13:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
no need to use iterator.

```
questions.forEach {
  setInitialValueForItem(it, answersHashMap)
}
```

2021-06-24 13:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
Actually as per my previoius comment, I really think you should avoid using output parameter (i.e. `answerHashMap`). Can you please make that a return value?

2021-06-24 13:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return createQuestionnaireResponse(questionnaire, answersHashMap)
a suggestion: you are basically going through all the questions in the questionnaire and creating an expression map, and then you're going through it to create the answer map, and then you're going through the questions in the questionnaire again to create the response. why not just do this in one traverse?

2021-06-24 14:31 UTC, MuhammadSalman-7214 commented
https://github.com/google/android-fhir/pull/536#discussion_r657893734
@jingtang10 for this, I am using questionnaire, if I rename the variable to questionnaire then there is a problem with actual questionnaire variable as this line:
QuestionnaireResponse().apply { questionnaire = questions.id }

2021-06-24 14:32 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem():
okay sure

2021-06-24 16:57 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
okay

2021-06-24 16:59 UTC, MuhammadSalman-7214 commented
@jingtang10 I have updated the PR as per your comments except the suggestion comment. If that is necessary then I'll do that as well otherwise you can approve the PR or please tell me to implement that comment as well, thank you very much.

2021-06-24 17:05 UTC, MuhammadSalman-7214 commented
https://github.com/google/android-fhir/pull/536#discussion_r657893564
For this, I have added this file as well, but it is added in gitignore, so that is why not pushing

2021-06-25 08:47 UTC, jingtang10 commented
> [#536 (comment)](https://github.com/google/android-fhir/pull/536#discussion_r657893734)
> @jingtang10 for this, I am using questionnaire, if I rename the variable to questionnaire then there is a problem with actual questionnaire variable at this line:
> QuestionnaireResponse().apply { questionnaire = questions.id }

what's the error? i think the error might be type mismatch rather than variable naming issue. Even if it is a naming conflict, you can typically apply scope to clarify (use `@`)?

2021-06-25 08:47 UTC, jingtang10 commented
> @jingtang10 I have updated the PR as per your comments except the suggestion comment. If that is necessary then I'll do that as well otherwise you can approve the PR or please tell me to implement that comment as well, thank you very much.

yes please implement it

2021-06-25 15:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return createQuestionnaireResponse(questionnaire, answersHashMap)
> a suggestion: you are basically going through all the questions in the questionnaire and creating an expression map, and then you're going through it to create the answer map, and then you're going through the questions in the questionnaire again to create the response. why not just do this in one traverse?

@jingtang10 I have pushed the code as per your suggestion, please review, thanks

2021-06-25 15:21 UTC, MuhammadSalman-7214 commented
@jingtang10 code is pushed, you can check the PR, thanks

2021-06-25 18:26 UTC, jingtang10 requested changes
thanks! i think the code structure is much better this way.

we discussed the issue with the removed file offline - if you can resolved that that'd be great. thanks!

2021-06-25 18:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun evaluatePopulateExpressionOnQuestionnaireItem(
```suggestion
  private fun populateInitialValue(
```

2021-06-25 18:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun evaluatePopulateExpressionsInItemList(
```suggestion
  private fun populateIntialValue(
```

2021-06-25 18:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    questionsList: List<Questionnaire.QuestionnaireItemComponent>,
```suggestion
    questionnaireItems: List<Questionnaire.QuestionnaireItemComponent>,
```

2021-06-25 18:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
```suggestion
    questionnaireItems.forEach {
      populateInitialValue(it, resource)
    }
```

2021-06-25 18:26 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem():
this is where the function belongs - great!

can i ask you for a favour @MuhammadSalman-7214? is it possible for you to add some unit tests for this? thanks!

2021-06-28 09:19 UTC, MuhammadSalman-7214 commented
@jingtang10 PR updated as per your comments, and jarRepositories.xml file added as well, though it is showing some changes, but that is of format only as I have applied spotlessApply. you can check the changes, thank you very much.

2021-06-28 09:19 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem():
can you tell me in which feature, I can write unit test for this function? thanks

2021-06-28 09:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    }
Done

2021-06-28 09:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    questionsList: List<Questionnaire.QuestionnaireItemComponent>,
Done

2021-06-28 09:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun evaluatePopulateExpressionsInItemList(
Done

2021-06-28 09:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun evaluatePopulateExpressionOnQuestionnaireItem(
Done

2021-06-28 09:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> + * [Questionnaire.QuestionnaireItemComponent].
Done

2021-06-28 09:20 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +private inline fun Questionnaire.QuestionnaireItemComponent.listOfItemInAnswer() =
Done

2021-06-28 09:21 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +  item.map { it.createQuestionnaireResponseItem() }.toList()
Done

2021-06-28 09:21 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return questionnaireResponse
Done

2021-06-28 09:21 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return null
Done

2021-06-28 09:21 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private fun Questionnaire.QuestionnaireItemComponent.fetchExpression(): Expression? {
Done

2021-06-28 16:16 UTC, jingtang10 requested changes

2021-06-28 16:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   * populate to Questionnaire
You don't need to re-describe what the function signature is. Rather explain what it does:

```
Returns a `QuestionnaireResponse` to the [questionnaire] that is pre-filled from the [resource].

See http://build.fhir.org/ig/HL7/sdc/populate.html#expression-based-population.
```

2021-06-28 16:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val expressionMap: HashMap<String, String> = hashMapOf()
is this map still used?

2021-06-28 16:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        }
why do you need to use `apply`?

2021-06-29 06:58 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        }
To set the initial value to the questionnaire

2021-06-29 07:41 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   * populate to Questionnaire
Done

2021-06-29 07:42 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val expressionMap: HashMap<String, String> = hashMapOf()
No, and I have removed it as well

2021-06-29 07:42 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem():
Done

2021-06-29 07:43 UTC, MuhammadSalman-7214 commented
https://github.com/google/android-fhir/pull/536#discussion_r659876257
@jingtang10 done

2021-06-29 09:04 UTC, jingtang10 requested changes

2021-06-29 09:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   * . See http://build.fhir.org/ig/HL7/sdc/populate.html#expression-based-population.
nit: don't put the period on the new line.

2021-06-29 09:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        }
why not

`question.inital = ...`

rather than using `.apply{ ... }`?

is that not simpler and more straightforward? is using `apply` adding anything?

2021-06-29 09:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem():
where are the unit tests?

2021-06-29 10:08 UTC, MuhammadSalman-7214 commented
https://github.com/google/android-fhir/pull/536#discussion_r660424257
@jingtang10 the unit test for createQuestionnaireResponse() is in the ResoueceMapperTest class, should I create a new file for unit test of this function?

2021-06-29 10:09 UTC, MuhammadSalman-7214 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +fun Questionnaire.QuestionnaireItemComponent.createQuestionnaireResponseItem():
@jingtang10 the unit test for createQuestionnaireResponse() is in the ResoueceMapperTest class, should I create a new file for unit test of this function?

2021-06-29 10:37 UTC, jingtang10 commented
> [#536 (comment)](https://github.com/google/android-fhir/pull/536#discussion_r660424257)
> @jingtang10 the unit test for createQuestionnaireResponse() is in the ResoueceMapperTest class, should I create a new file for unit test of this function?

not that i can see. can you send a link?

2021-06-30 13:58 UTC, jingtang10 approved these changes

2021-06-30 13:58 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    assertThat(((response.item[0].item[0].item[0].answer[0]).value as StringType).valueAsString)
`response.item[0]` is repeated so many times - extract a local variable

2021-06-30 14:08 UTC, MuhammadSalman-7214 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    assertThat(((response.item[0].item[0].item[0].answer[0]).value as StringType).valueAsString)
sure

2021-06-30 14:40 UTC, merged