Ma/view binding reference
google/android-fhir pull request #538
Opened 2021-06-06 17:07 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #515 

**Description**
Add view binding for reference app

**Alternative(s) considered**
N/A

**Type**
Choose one: ( Feature)

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-06 17:08 UTC, maanuanubhav999 commented
@googlebot I consent.

2021-06-06 17:12 UTC, maanuanubhav999 commented
@aditya-07 is it okay to work further on the branch you have made a PR #533.

2021-06-07 22:44 UTC, maanuanubhav999 commented
Deleted tests as https://github.com/google/android-fhir/pull/436#issuecomment-855235121 also mention Tests failing. 
Reference app otherwise seems to work fine on my phone (API 30, android 11) and emulator.

2021-06-11 13:43 UTC, epicadk commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
> +    return view
```suggestion
    return binding.root
```

2021-06-11 13:46 UTC, epicadk commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
> +    val recyclerView: RecyclerView = view.findViewById(R.id.observation_list)
Use view binding here?
Also maybe we could move this logic inside onCreateView since viewbinding is nullsafe but I'm not too sure about this.

2021-06-11 18:21 UTC, maanuanubhav999 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
> +    return view
@epicadk thanks, I am currently waiting for #533 to merge/complete since few changes are requested on that PR

2021-06-11 19:01 UTC, epicadk requested changes

2021-06-11 19:02 UTC, epicadk commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
> +    return view
Oh okay

2021-06-15 23:31 UTC, maanuanubhav999 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
> +    val recyclerView: RecyclerView = view.findViewById(R.id.observation_list)
@epicadk is it possible to use two bindings inside a file? I tried finding but could not find something significant.

2021-06-15 23:40 UTC, maanuanubhav999 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailFragment.kt
>        view.findViewById<TextView>(R.id.gender).text = patient.phone
@epicadk I am clear on how to use view binding here since the last 3 are using a different file.

2021-06-16 01:45 UTC, closed without merging