Fix: hide nested elements after parent item deselected / parent answer removed
google/android-fhir pull request #546
Opened 2021-06-12 23:01 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[530]

**Description**
Removes nested / child items when parent item deselected/ answer removed

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
No

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-14 05:09 UTC, joiskash requested changes
This does not seem like the right fix. In the case of nested questionnaire items, if the parent items answer is empty, null, or false you need to remove all the nested items that are within the parent item,answers.items. The right place to do this is probably in the `questionnaireResponseItemChangedCallback`

2021-06-14 11:03 UTC, maanuanubhav999 commented
okay sure @joiskash. I will work on that.

2021-06-15 21:50 UTC, maanuanubhav999 commented
@joiskash PR is failing tests where the parent is false but still, we have child Items. will we actually have a case like this?? Is there any other approach that I could follow or should I change tests?.

2021-06-16 05:36 UTC, joiskash commented
> 
> 
> @joiskash PR is failing tests where the parent is false but still, we have child Items. will we actually have a case like this?? Is there any other approach that I could follow or should I change tests?.

You can change any test which does not seem logical with the new change.

2021-06-16 06:40 UTC, joiskash requested changes
Please check my review comments and please Re-Request once you have made changes, thanks!

2021-06-16 06:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              questionnaireResponseItem
Revert this change, you can get the `questionnaireResponseItem` by using the linkId and  `linkIdToQuestionnaireResponseItemMap`

2021-06-16 06:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      { linkId, questionnaireResponseItem ->
Same as below, use the `linkIdToQuestionnaireResponseItemMap`

2021-06-16 06:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (questionnaireResponseItem.answer.first().hasValueBooleanType() &&
We also need to check another condition here.. OR `questionnaireResponseItem.answer.first().value.isEmpty`

2021-06-16 06:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          linkIdToQuestionnaireResponseItemMap[linkId]!!.addNestedItemsToAnswer(it)
this should be in the else branch.. so if there is no answer value then there should be no nested items in the answer. Makes sense?

2021-06-16 19:35 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              questionnaireResponseItem
Thanks, I totally missed that.

2021-06-16 21:29 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          linkIdToQuestionnaireResponseItemMap[linkId]!!.addNestedItemsToAnswer(it)
Thanks, @joiskash but not quite sure about this or maybe I have misinterpreted. We want to **add Nested Items To Answer** when the condition **value is not empty** and **value is booleanType and its value is true** ?? If this is the case it will not add any nested values when it is not of BooleanType.

2021-06-17 05:40 UTC, joiskash requested changes
Please add a test case to check the new condition that you have written

2021-06-17 05:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (linkIdToQuestionnaireResponseItemMap[linkId]!!.answer.first().value.isEmpty ||
i think this should be `condition_1 || (condition2 && condition3)`

2021-06-17 13:20 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (linkIdToQuestionnaireResponseItemMap[linkId]!!.answer.first().value.isEmpty ||
Okay. Sure

2021-06-17 22:40 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        if (linkIdToQuestionnaireResponseItemMap[linkId]!!.answer.first().value.isEmpty ||
I have to push multiple PR as my local `./gradlew check`  is failing all tests. I think there is already an issue related to it. I will later squash them.

2021-06-21 14:22 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    viewModel.questionnaireItemViewItemList[0].questionnaireResponseItem.answer.clear()
I would suggest removing this line and instead putting `viewModel.questionnaireItemViewItemList[0].questionnaireResponseItem.answer[0].value = false` so that the nested item is removed and you can test it.. Over here it looks like you are just clearing the answer and then setting the value to false. Do let me know if my understanding is wrong.

2021-06-21 14:23 UTC, joiskash requested changes
Put another test case for type string. But otherwise I think this PR is almost ready! Thanks!

2021-06-21 14:29 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          linkIdToQuestionnaireResponseItemMap[linkId]!!.addNestedItemsToAnswer(it)
Sorry missed this, so when the questionnaireItem has a nested item then the corresponding questionnaireResponseItem will not have a nested item, the questionnaireResponseItem.answer will have the nested item. It is the structure that the FHIR spec has defined. It is to make sure that if the parent questionnaireItem allows repeated answers, then all the answers will contain the nested items.

2021-06-21 14:31 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          linkIdToQuestionnaireResponseItemMap[linkId]!!.addNestedItemsToAnswer(it)
Please have a look at this [discussion](https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Questionnaire.20Response.20example)

2021-06-21 23:03 UTC, maanuanubhav999 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    viewModel.questionnaireItemViewItemList[0].questionnaireResponseItem.answer.clear()
sure thanks. I totally forgot that clear will erase the nested items also.

2021-06-22 00:43 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          linkIdToQuestionnaireResponseItemMap[linkId]!!.addNestedItemsToAnswer(it)
@joiskash thanks, do we need this(moving to else branch) even now?

2021-06-23 14:06 UTC, joiskash reviewed
Look good to me :) , @jingtang10 please have a look if you feel any changes are needed. After that @maanuanubhav999 you can merge this to master. Thanks!

2021-06-23 14:07 UTC, joiskash approved these changes

2021-06-23 14:13 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          linkIdToQuestionnaireResponseItemMap[linkId]!!.addNestedItemsToAnswer(it)
yes it looks fine now. Just a small comment i missed in the review, `linkIdToQuestionnaireResponseItemMap[linkId]!!.answer.first()` could probably be a local variable to make the if-else more readable.

2021-06-24 12:16 UTC, jingtang10 reviewed
We don't normally prefix PRs with things like `Fix:`. IMHO they actually make the PRs harder to read. We can use labels instead if needed.

Just do `Hide nested ...`

Also I'm not so sure that the fix is in this file... look at this block https://github.com/google/android-fhir/blob/f5116ed7aef1f93bedd840e8fde1046f65252350/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt#L40: 

when the check box is unticked, the answer is still there but with a false value. I think in this case having a nested item is kind of legitimate. I think if we want to fix this issue, we could make sure that `false` answers are simply clearing the answers (see below example) -- but is that what we want?

```
questionnaireItemViewItem.singleAnswerOrNull =
  if (checkBox.isChecked) {
    QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
      value = BooleanType(checkBox.isChecked)
    }
  } else {
    null
}
```

@joiskash - do you think we can ask on fhir chat about this?

2021-06-24 13:07 UTC, joiskash commented
> 
> 
> We don't normally prefix PRs with things like `Fix:`. IMHO they actually make the PRs harder to read. We can use labels instead if needed.
> 
> Just do `Hide nested ...`
> 
> Also I'm not so sure that the fix is in this file... look at this block
> 
> https://github.com/google/android-fhir/blob/f5116ed7aef1f93bedd840e8fde1046f65252350/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt#L40
> :
> 
> when the check box is unticked, the answer is still there but with a false value. I think in this case having a nested item is kind of legitimate. I think if we want to fix this issue, we could make sure that `false` answers are simply clearing the answers (see below example) -- but is that what we want?
> 
> ```
> questionnaireItemViewItem.singleAnswerOrNull =
>   if (checkBox.isChecked) {
>     QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
>       value = BooleanType(checkBox.isChecked)
>     }
>   } else {
>     null
> }
> ```
> 
> @joiskash - do you think we can ask on fhir chat about this?

Makes sense..I was actually looking at this only from the point of UI. There can be a question which if the answer is false, the nested items still make sense. I did not think this through. 

Current scenario is nested items remain hidden until the parent item has been answered.

Once the parent item is answered the nested items appear.

What should happen now when the parent answer is cleared (in case of edit text or integer) or set to false in case of a boolean.

@f-odhiambo please put your thoughts here.

2021-06-24 13:44 UTC, jingtang10 commented
One thing we _could_ do is just to say, if it's a single checkbox, then we will clear the answer if it's unticked. If you want the answer to be set to false but present, maybe use a radio button group (with yes and no radio buttons).

2021-06-25 21:18 UTC, maanuanubhav999 commented
> One thing we _could_ do is just to say, if it's a single checkbox, then we will clear the answer if it's unticked. If you want the answer to be set to false but remain present, maybe use a radio button group (with yes and no radio buttons).

sorry I messed up earlier. Summarizing from the points mentioned above 

We surely don't want to remove the nested element **every time** the parent is `false`. it will be required in many cases ( i.e. question:  did you take your medicine, if not why?). So when to remove it ??

But we may still require to clear nested elements when `(case of edit text or integer)`

Maybe we can have a **clear option** that would clear all the filled QuestionnaireResponse??  there may be other cases when one requires to clear the form.

2021-06-30 10:42 UTC, joiskash commented
> One thing we _could_ do is just to say, if it's a single checkbox, then we will clear the answer if it's unticked. If you want the answer to be set to false but remain present, maybe use a radio button group (with yes and no radio buttons).

This seems like a implementation detail that can be missed out.. @f-odhiambo  please comment. This issue was raised by you, what is the ideal behavior according to you?

2021-06-30 11:13 UTC, f-odhiambo commented
HI @joiskash. Sorry I may have missed this. 

So the ideal scenario for this would be

1. if the parent items answer is empty, null, or false you need to remove all the nested items that are within the parent item
2.  if the parent items answer is answered, checked, or true you need to show/make visible  all the nested items that are within the parent item

Thus 
1. Go to datacapturegallery app.
2. Click on Neonate record from New South Wales, Australia
3. Scroll down to Hep B give y/n
4. Press the checkbox - date field should be made visible 
5. Uncheck the check box - date field should be hidden

2021-06-30 11:28 UTC, joiskash commented
> 
> 
> HI @joiskash. Sorry I may have missed this.
> 
> So the ideal scenario for this would be
> 
>     1. if the parent items answer is empty, null, or false you need to remove all the nested items that are within the parent item
> 
>     2. if the parent items answer is answered, checked, or true you need to show/make visible  all the nested items that are within the parent item
> 
> 
> Thus
> 
>     1. Go to datacapturegallery app.
> 
>     2. Click on Neonate record from New South Wales, Australia
> 
>     3. Scroll down to Hep B give y/n
> 
>     4. Press the checkbox - date field should be made visible
> 
>     5. Uncheck the check box - date field should be hidden

So the main issue is with false, there may be a parent question which can have the answer as false and have valid nested items.. So in the current build if the parent answer is by default unchecked then the nested items will not be visible. And after you check and uncheck if we clear nested items then for a false answer we can never have the nested items..

Jing did suggest asking this to the fhir chat group, but I have not done it yet.

2021-06-30 12:33 UTC, jingtang10 commented
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/EnableWhen.20behavior.20with.20operator.20.60exists.60

let's see the response.

2021-07-01 08:36 UTC, jingtang10 commented
please see the chat link above. one solution suggested by people on the fhir chat is that we need to be able to clear boolean questions (i.e. adding another option to the radio button group or use a different widget type) and indeed coding questions.

2021-07-02 05:20 UTC, joiskash commented
As per my understanding, from the FHIR chat we can conclude that 

1.  Boolean questions should be rendered as 3 options. The 3rd one being "not answered" or something similar
2. Choice questions should have a clear answer option.

2021-07-05 08:16 UTC, maanuanubhav999 commented
> As per my understanding, from the FHIR chat we can conclude that
> 
> 1. Boolean questions should be rendered as 3 options. The 3rd one being "not answered" or something similar
> 2. Choice questions should have a clear answer option.
> 
> @jingtang10 please correct me if I am wrong

@joiskash So should I move forward with this?

2021-07-05 16:39 UTC, jingtang10 commented
> > As per my understanding, from the FHIR chat we can conclude that
> > 
> > 1. Boolean questions should be rendered as 3 options. The 3rd one being "not answered" or something similar
> > 2. Choice questions should have a clear answer option.
> > 
> > @jingtang10 please correct me if I am wrong
> 
> @joiskash So should I move forward with this?

That's be great thanks!

2021-07-09 10:33 UTC, jingtang10 commented
@maanuanubhav999 is there more to do here? if not can you close this?

2021-07-09 12:19 UTC, closed without merging