Validation API for SDC
google/android-fhir pull request #548
Opened 2021-06-14 11:23 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #374 

**Description**
Expose external api for developers to validate the questionnaire response using the SDC library

**Type**
Feature

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-15 17:28 UTC, jingtang10 requested changes

2021-06-15 17:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  fun validateQuestionnaireResponse(): MutableList<ValidationResult> {
i feel you need to create a new API in the validation package rather than putting it here. i don't feel this needs to be linked with the fragment API.

what about something like 
```
object QuestionnaireValidator {
  fun validate(questionnaire: Questionnaire, questionnarieResponse: QuestionnaireResponse): ValidationResult
}
```
and it will use the existing validators in that package.

2021-06-15 17:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ConstraintValidator.kt
> +    val linkId: String?,
can this be mandatory?

```suggestion
    val linkId: String,
```

2021-06-15 17:28 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  val validationLinkIdAndMessages: List<Pair<String, String>>
this feels kinda odd - can we maybe have something like `Map<String, ConstraintValidationResult>` to map from link id to the result? or something similar.

at the very least, if the `Pair<String, String>` represents the validation result of a single question, it makes sense to create a data class for it.

2021-06-16 06:42 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  fun validateQuestionnaireResponse(): MutableList<ValidationResult> {
ok makes sense , Ill change this

2021-06-16 06:48 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  val validationLinkIdAndMessages: List<Pair<String, String>>
ok sure

2021-06-16 11:17 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  fun validateQuestionnaireResponse(): MutableList<ValidationResult> {
done

2021-06-16 11:18 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
> +  val validationLinkIdAndMessages: List<Pair<String, String>>
done used `Map<String,ValidationResult>`

2021-06-18 05:33 UTC, Tarun-Bhardwaj commented
Hi @joiskash, it seems changes are pending for this PR. Is there an ETA by when these can be ready for review?

2021-06-18 07:17 UTC, joiskash commented
> Hi @joiskash, it seems changes are pending for this PR. Is there an ETA by when these can be ready for review?

I have actually requested a review after the last round of review. Not sure if its not showing up properly

2021-06-18 13:51 UTC, jingtang10 commented
> > Hi @joiskash, it seems changes are pending for this PR. Is there an ETA by when these can be ready for review?
> 
> I have actually requested a review after the last round of review. Not sure if its not showing up properly

Thanks @joiskash

Not sure if you need to dismiss or approve the previous review etc. Odd.

2021-06-18 13:52 UTC, joiskash commented
> 
> 
> > > Hi @joiskash, it seems changes are pending for this PR. Is there an ETA by when these can be ready for review?
> > 
> > 
> > I have actually requested a review after the last round of review. Not sure if its not showing up properly
> 
> Thanks @joiskash
> 
> Not sure if you need to dismiss or approve the previous review etc. Odd.

Yea.. i maybe doing something wrong. Ill pay more attention next time. Sorry for the inconvenience

2021-06-21 10:29 UTC, jingtang10 submitted a review, later dismissed

2021-06-21 10:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  fun getQuestionnaire() = viewModel.getQuestionnaire()
feel this can be a property ie

`val questionnaire = viewModel.questionnaire`

2021-06-21 10:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun getQuestionnaire(): Questionnaire = questionnaire
just change the property to internal?

2021-06-21 10:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireValidator.kt
> +        // TODO(https://github.com/google/android-fhir/issues/487): Validates all answers.
this doesn't seem very difficult to do in this PR? can you just do it?

2021-06-21 10:29 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    assertThat(validationResult.message?.equals("Maximum value allowed is:200000")).isTrue()
```suggestion
    assertThat(validationResult.message!!).isEqualTo("Maximum value allowed is:200000")
```

2021-06-21 10:29 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireValidatorTest.kt
> +    assertEquals(
use truth:

`assertThat(...).isEqualTo()`

2021-06-21 13:16 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireValidator.kt
> +        // TODO(https://github.com/google/android-fhir/issues/487): Validates all answers.
Well the issue is that I am reusing the validators which are used in `QuestionnaireResponseItemValidator` which all handle only single answer. I can make those changes in this PR if you want.

eg: Have a look at `ValueConstraintExtensionValidator`

2021-06-21 15:16 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireValidator.kt
> +        // TODO(https://github.com/google/android-fhir/issues/487): Validates all answers.
oh yeah that's right -- sure this makes sense.

2021-06-21 17:39 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireValidator.kt
> +object QuestionnaireValidator {
done

2021-06-21 17:42 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +  fun getQuestionnaire() = viewModel.getQuestionnaire()
done

2021-06-21 17:43 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  fun getQuestionnaire(): Questionnaire = questionnaire
done

2021-06-21 17:58 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
> +    assertThat(validationResult.message?.equals("Maximum value allowed is:200000")).isTrue()
done

2021-06-21 18:03 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireValidatorTest.kt
> +    assertEquals(
done

2021-06-22 09:01 UTC, jingtang10 approved these changes
Thanks @joiskash! 🎉

2021-06-22 09:01 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +  }
don't have to do this in this PR - but you can probably create an iterator for questionnaire item + questionnaire response item. this logic is repeated in the questionnaire view model as well.

2021-06-22 09:32 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +  }
sure ill put a comment so that it is done while handling repeated answers

2021-06-22 10:07 UTC, jingtang10 requested changes

2021-06-22 10:07 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
> +  }
```suggestion
    assertThat(result.get("a-question"))
      .containsExactly(
        ValidationResult(
          false,
          listOf("The maximum number of characters that are permitted in the answer is: 3")
        )
      )
  }
```

2021-06-22 10:07 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidatorTest.kt
> +      )
```suggestion
    assertThat(result.get("a-question"))
      .containsExactly(
        ValidationResult(
          false,
          listOf("The maximum number of characters that are permitted in the answer is: 3")
        )
      )
    assertThat(result.get("a-nested-question"))
      .containsExactly(
        ValidationResult(
          false,
          listOf("The maximum number of characters that are permitted in the answer is: 3")
        )
      )
```

2021-06-22 10:46 UTC, jingtang10 approved these changes

2021-06-22 10:52 UTC, merged