feat: Add view binding for Reference app
google/android-fhir pull request #550
Opened 2021-06-16 01:46 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #515 

**Description**
N/A

**Alternative(s) considered**
N/A

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-16 01:48 UTC, maanuanubhav999 commented
@epicadk I have made the changes you have asked for. Since there was a lot of merging and permission issues I decided to open a new PR.

2021-06-16 16:49 UTC, jingtang10 approved these changes
Thanks @maanuanubhav999 for this change!

Just an optional suggestion. Please feel free to merge after you address (or let me know if you decide not to)

2021-06-16 16:49 UTC, jingtang10 commented on reference/src/main/res/layout/fragment_patient_list.xml
> +        layout="@layout/patient_list"
this naming seems odd to me, what about keep the id `patient_list`, and change the layout file to be `patient_list_view` or something like that.

```suggestion
        android:id="@+id/patient_list"
        layout="@layout/patient_list_view"
```

same for the two more changes below

2021-06-16 19:42 UTC, maanuanubhav999 commented
@jingtang10 Thanks, please merge it. I don't have write access.

2021-06-17 08:50 UTC, jingtang10 requested changes

2021-06-17 08:50 UTC, jingtang10 commented on reference/src/main/res/layout/patient_list_view.xml
> +        android:id="@+id/patient_list_recyclerView"
can this not be `patient_list`?

if we have to include recycler view i'd prefer `patient_list_recycler_view`

2021-06-17 11:19 UTC, maanuanubhav999 commented on reference/src/main/res/layout/patient_list_view.xml
> +        android:id="@+id/patient_list_recyclerView"
The Id when including the patient_list_view(In fragment_patient_list.xml) is set to `patient_list` I could probably change that to something like `patient_list_view` then this could be set to `patient_list` or should I stick with `patient_list_recycler_view`

2021-06-17 16:20 UTC, jingtang10 approved these changes

2021-06-17 16:20 UTC, jingtang10 commented on reference/src/main/res/layout/patient_list_view.xml
> +        android:id="@+id/patient_list_recyclerView"
how about change the id in `fragment_patient_list.xml` to `patient_list_container` and make this one `patient_list`

2021-06-21 11:11 UTC, merged