Add a regex validator for questionnaire
google/android-fhir pull request #555
Opened 2021-06-16 23:12 UTC by stevenckngaa

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #466

**Description**
Add a Regex validator for questionnaire.

Regex is a string value that is supplied to questionnaire extension: http://hl7.org/fhir/StructureDefinition/regex

Only questionnaire supported primitive types are subjected to this regex validation.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
N/A

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)
Feature

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-17 16:18 UTC, jingtang10 requested changes

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RegexValidator.kt
> +          !pattern.matcher((answer.value as PrimitiveType<*>).asStringValue()).matches()
i wonder if it makes sense to extract a small utility function for conversion to string since it happened twice here?

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RegexValidator.kt
> +      }
can you turn this into an early return?

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidatorTest.kt
> +    assertThat(validateAggregationFromChildValidators.validationMessages.size).isEqualTo(1)
also assert on the actual message?

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RegexValidatorTest.kt
> +  fun dateType_notMatchRegex_shouldReturnInvalidResult() {
```suggestion
  fun date_notMatchRegex_shouldReturnInvalidResult() {
```

to be consistent with the next test case name

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RegexValidatorTest.kt
> +    fun checkAnswerMatchRegex(regex: String, value: PrimitiveType<*>) {
super nit and optional: 
```suggestion
    fun checkAnswerMatchingRegex(regex: String, value: PrimitiveType<*>) {
```

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RegexValidatorTest.kt
> +    fun checkAnswerNotMatchRegex(regex: String, value: PrimitiveType<*>) {
```suggestion
    fun checkAnswerNotMatchingRegex(regex: String, value: PrimitiveType<*>) {
```

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RegexValidatorTest.kt
> +  fun uri_answerOverMinLength_shouldReturnValidResult() {
```suggestion
  fun uri_matchRegex_shouldReturnValidResult() {
```

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/RegexValidatorTest.kt
> +  fun boolean_notMatchRegex_shouldReturnInvalidResult() {
super nit and optional:

```suggestion
  fun boolean_notMatchingRegex_shouldReturnInvalidResult() {
```

and please do the same for the rest of test cases if you decide to do this

2021-06-17 16:18 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RegexValidator.kt
> + * 7. UriType
there seem to be more primitive types: https://www.hl7.org/fhir/datatypes.html#primitive

what made you choose these 7?

2021-06-21 22:40 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/RegexValidator.kt
> + * 7. UriType
This is because there are only a subset of primitive types that are allowed in QuestionnaireResponse. I've updated the documentation to link against the documentation instead of listing them here.

2021-06-22 09:59 UTC, jingtang10 approved these changes
Thanks @stevenckngaa! 👍🎉

2021-06-22 09:59 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/Types.kt
> +/*
nit: don't we normally do `MoreTypes.kt` in this case?

2021-06-22 14:37 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/common/datatype/Types.kt
> +/*
I found there is no consistent convention for naming an extension class, some use MoreTypes, some use Types, some use TypeExtensions. Anyway, I am going to rename it to MoreTypes to keep this consistent with the rest of the code base.

2021-06-22 16:42 UTC, merged