Language switcher for the Data Capture Gallery
google/android-fhir pull request #558
Opened 2021-06-17 17:32 UTC by ndegwamartin

Fixes #503

**Description**
-   Adds a language switcher to the data capture gallery useful to demo internationalization in the sdc lib
-  Localized some widget text to Vietnamese
-  Updated to the latest translated questionnaire [Questionnaire-case-reporting-questionnaire-vn.zip](https://github.com/google/android-fhir/issues/161#issuecomment-842540918)

**Type**
Feature

**Screenshots**

![Screenshot_1623950930](https://user-images.githubusercontent.com/10017086/122446001-d6332c80-cfaa-11eb-8cbd-3923177726c5.png)

![Screenshot_1623950934](https://user-images.githubusercontent.com/10017086/122445975-ce738800-cfaa-11eb-9bbb-ed5b9a1e7d90.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-18 06:27 UTC, ndegwamartin commented
@googlebot I signed it!

2021-06-24 14:00 UTC, jingtang10 commented
Thanks @ndegwamartin :) This is really cool 😎

A note on UI: I'm not sure @fredhersch has any comment - but I would love to keep things simple to begin with. Do we have to have a navigation drawer on the left? Can we simply make this an action item on the top bar: number 4 in https://material.io/components/app-bars-top#anatomy?

2021-06-25 01:32 UTC, fredhersch commented
Thanks @jingtang10 I had requested the drawer. I think it's the most logical way to show this for implementers and will be useful for other features (like syncing). If you have concerns about maintainability of the demo app using this approach let's revisit. Otherwise, I'd propose we go ahead with this. Looks great @ndegwamartin

2021-06-30 12:48 UTC, jingtang10 commented
spoke with @fredhersch and we think the drawer layout is probably more useful for the reference app rather than the sdc gallery app here. if it's possible to refactor please do so - thanks @ndegwamartin!

2021-07-07 09:08 UTC, ndegwamartin commented
The **Language selection** dialog now pops up when you touch the action item on the right of the top app bar.

![Screenshot_1625648654](https://user-images.githubusercontent.com/10017086/124732132-9a411680-df1b-11eb-80e9-be0edc90590e.png)

![Screenshot_1625648677](https://user-images.githubusercontent.com/10017086/124732587-00c63480-df1c-11eb-9cbb-59a17018cf73.png)

2021-07-07 09:11 UTC, ndegwamartin commented
@fredhersch @jingtang10 might be worth having the first page localised in Vietnamese so that it is apparent every time one switches the language, even before getting to the questionnaires

2021-07-07 13:50 UTC, jingtang10 requested changes
Thanks @ndegwamartin!

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +  data class Language(val tag: String, val displayName: String) {
nit: add new line before this class

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +
nit: remove new line :)

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +    builder.setAdapter(adapter, listener).create().show()
```suggestion
    AlertDialog.Builder(context).apply {
      title = ...
      icon = ...
      adapter = ArrayAdapter(context, android.R.layout.simple_list_item_1, languageList)
    }.create().show()
```

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +        Locale.getDefault().toLanguageTag()
if the shared pref locale override is null, do you still have to override the default locale? shouldn't you just do an early return at this point?

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +
remove new line

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +  fun renderSelectLanguageDialog(
```suggestion
  fun showLocaleSelectionDialog(
```

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +object LanguageSwitcherUtils {
```suggestion
object LocaleUtils {
```

prefer the name locale because it is more than languages - you could have the same language but due to where you are is displayed differently. also slightly more in line with the rest of the code.

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +  fun refreshActivity(activity: Activity) {
I don't think this belongs in this class. It's nothing to do with language or locale.

can you just put this in the class where it's used. also - you can make this an extension function of activity:

```
private fun Activity.refresh/reload/someothername() {
  ...
}
```

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +    val res: Resources = context.resources
```suggestion
    val resources: Resources = context.resources
```

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    applyOverrideConfiguration(newConfiguration)
this is slightly confusing to me. does line 81 actually set the locale for the context? it seems to me if line 83 is needed it should be part of the util function on line 81. can you try without it? does it work?

2021-07-07 13:50 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +      }
i'm sure i've seen simpler examples on stack overflow :) are you sure the code can't be made simpler? line 42 to 46 seem like it can be simplified? https://stackoverflow.com/questions/4985805/set-locale-programmatically

also - have you tested this? does it work for N and below?

2021-07-08 09:23 UTC, ndegwamartin commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    applyOverrideConfiguration(newConfiguration)
you are right, a bit of a misnomer there, renaming this to `LocaleUtils.updateContextResourceConfiguration(...`

2021-07-08 09:25 UTC, ndegwamartin commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    applyOverrideConfiguration(newConfiguration)
alternatively we could keep the name as it is but then pass `super` as a parameter. we'd also need to pass `this` so that we can invoke `applyOverrideConfiguration` as well from within the helper function

2021-07-08 11:26 UTC, ndegwamartin commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +      }
Yeah, tested this on Android N and it works fine. However I will refactor this code to make it more concise and clear

2021-07-08 11:27 UTC, ndegwamartin commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LanguageSwitcherUtils.kt
> +      }
Also the recommended answer on S/O above is actually quite similar to this implementation. This should be more apparent once I refactor the code.

2021-07-14 06:04 UTC, Tarun-Bhardwaj commented
Hi @ndegwamartin  , is there an ETA you can provide for completing the changes as per the review comments in order to close this PR?

2021-07-14 10:17 UTC, ndegwamartin commented
> Hi @ndegwamartin , is there an ETA you can provide for completing the changes as per the review comments in order to close this PR?

@Tarun-Bhardwaj all changes requested are complete

2021-07-15 11:11 UTC, deepankarb commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/utils/LocaleUtils.kt
> +  @Suppress("DEPRECATION")
Please add more details on which call is deprecated and create an issue for fixing it.

2021-07-16 13:38 UTC, deepankarb commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +  private fun refreshToSelectedLanguage(language: LocaleUtils.Language, context: Activity) {
Parameter name and type are not consistent. Is a `Context` or and `Activity` needed in the method?

2021-07-16 13:44 UTC, deepankarb commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    activity.startActivity(intent)
We're starting a new activity every time this method is called, which will get added to the backstack. Are there better ways to load the configuration within the same activity?

2021-07-16 13:52 UTC, deepankarb commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    activity.startActivity(intent)
Maybe [`activity.recreate()`](https://developer.android.com/reference/android/app/Activity.html#recreate%28%29)?

2021-07-16 13:54 UTC, deepankarb commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    this reload context
Is `infix` syntax helpful here?

2021-07-16 14:03 UTC, deepankarb requested changes
Left some comments please fix and send again. Thanks!

2021-07-20 05:25 UTC, ndegwamartin commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    this reload context
maybe not, refactoring

2021-07-20 05:53 UTC, ndegwamartin commented
@deepankarb please check out the updates

2021-08-07 14:28 UTC, Tarun-Bhardwaj commented
@deepankarb , it seems Martin has completed all changes as per review comments. Could you please re-review the same?

2021-11-23 12:42 UTC, jingtang10 approved these changes

2021-11-23 14:57 UTC, jingtang10 approved these changes

2021-11-23 16:15 UTC, ndegwamartin commented
> Auto-merge enabled

@deepankarb a reminder to check the updates

2021-11-24 16:00 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +
this isn't done

2021-11-24 16:29 UTC, jingtang10 requested changes

2021-11-24 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +
remove new line

2021-11-24 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +
remove new line

2021-11-24 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/MainActivity.kt
> +    languageList = LocaleUtils.getLanguageList(this)
can this line be on line 31?

2021-11-26 10:38 UTC, jingtang10 commented
Following our discussion yesterday @ndegwamartin I closed this issue https://github.com/google/android-fhir/issues/503#issuecomment-979866812. Will you please close this PR if this sounds good to you? Thanks for the good work and I hope the learnings here has been useful in fhir core!

2021-11-26 11:12 UTC, ndegwamartin commented
> Following our discussion yesterday @ndegwamartin I closed this issue [#503 (comment)](https://github.com/google/android-fhir/issues/503#issuecomment-979866812). Will you please close this PR if this sounds good to you? Thanks for the good work and I hope the learnings here have been useful in fhir core!

Yeah I've learnt a alot. Closing this now

2021-11-26 11:12 UTC, closed without merging