Implement StructureMap-based extraction
google/android-fhir pull request #566
Opened 2021-06-21 16:20 UTC by ekigamba

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #543

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-22 12:58 UTC, ekigamba commented
I'm not sure whether to suspend the whole extraction function or just the `StructureMapProvider#getStructureMap`

2021-06-23 14:00 UTC, jingtang10 requested changes

2021-06-23 14:00 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    // https://simplifier.net/packages?Text=hl7.fhir.core&fhirVersion=All+FHIR+Versions
duplicates

2021-06-23 14:00 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val map: StructureMap =
did this map come from somewhere? or did you author this?

if it's an example from somewhere can you add a link? thanks!

2021-06-29 21:29 UTC, ekigamba commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val hapiFhirValidations = "5.3.0"
Yea, I'll change that

2021-06-29 21:39 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  }
Sorry, forgot about the Kotlin default param

2021-06-29 21:49 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val pcm = FilesystemPackageCacheManager(true, ToolsVersion.TOOLS_VERSION)
Fixed

2021-06-29 21:49 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val scu = StructureMapUtilities(contextR4)
Fixed

2021-06-29 21:52 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val structureMapUrl = questionnaire.targetStructureMap ?: return Bundle()
Fixed

2021-06-29 21:59 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should allow extract correct Patient resource using definition-based extraction`() {
Done

2021-06-29 22:00 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should allow extracting correct Patient resource with unanswered questions using definition-based extraction`() {
Done

2021-06-29 22:01 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should allow StructureMap-based extraction and return correct Patient resource`() {
Done

2021-06-29 22:01 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val pcm = FilesystemPackageCacheManager(true, ToolsVersion.TOOLS_VERSION)
Done

2021-06-29 22:02 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    // https://simplifier.net/packages?Text=hl7.fhir.core&fhirVersion=All+FHIR+Versions
Done

2021-06-29 22:02 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val map: StructureMap =
I authored this

2021-06-30 13:52 UTC, jingtang10 requested changes

2021-06-30 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +
can you create a new file called `MoreQuestionnaires.kt` in the `datacapture` package?

2021-06-30 13:52 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should allow perform definition-based extraction`() {
```suggestion
  fun `extract() should perform definition-based extraction`() {
```

2021-06-30 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    // Load the npm package
this comment doesn't add much -- partly because the function has got a good name.

if you want to explain why this is needed, or how this is done, etc, please update this comment. otherwise, remove this comment if it's simply repeating the function name.

2021-06-30 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    structureMapProvider: StructureMapProvider?,
```suggestion
    structureMapProvider: (String) -> StructureMap,
```

2021-06-30 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +}
remove

2021-06-30 13:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    context: Context?
can you move all the logic related to do with the npm package to a separate file, and here take a SimpleWorkerContext instead? that way you may also be able to get rid of the shadow class used in your test?

2021-06-30 18:49 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +
Done

2021-06-30 18:50 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +  fun `extract() should allow perform definition-based extraction`() {
Done

2021-06-30 18:51 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    // Load the npm package
Removed

2021-06-30 18:53 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    structureMapProvider: StructureMapProvider?,
Done

2021-06-30 18:55 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +}
Done

2021-06-30 19:03 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    context: Context?
I think that we can try to keep the API simple to use by performing all the operations required implicitly. A couple of operations need to happen so that we can provide the `SimpleWorkerContext` i.e. 
- Copy the npm archive to private app storage
- Extract the NPM package containing all the StructureDefinitions
- Load the package from this extracted files

I think is going to be difficult to use if we separate the required functionalities required for this to work. Furthermore, it's going to be more difficult if we leave it unimplemented.

However, I think we can move the login related to the npm package to separate file. What do you think?

2021-07-07 15:27 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    context: Context?
i'm not exactly sure that you should have `lateinit var npmPackage: NpmPackage` in this class. it makes the object mapper stateful. my point was that the loading of the npm package should be in a separate file to separate the logic. it might be used elsewhere by another module.

you could still call out to that file from here. and maybe we don't yet need to add another param to the extract API.

2021-07-07 15:42 UTC, jingtang10 requested changes

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      extractByStructureMapBased(
```suggestion
      extractByStructureMap(
```

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      extractByDefinitionBased(questionnaire, questionnaireResponse)
```suggestion
      extractByDefinitions(questionnaire, questionnaireResponse)
```

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val structureMap = structureMapProvider(structureMapUrl)
```suggestion
    val structureMap = structureMapProvider(questionnaire.targetStructureMap!!)
```

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +object NpmPackageProvider {
internal

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  fun loadSimpleWorkerContextWithPackage(context: Context): SimpleWorkerContext {
```suggestion
  fun loadSimpleWorkerContext(context: Context): SimpleWorkerContext {
```

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    context: Context?
actually i see you have moved the npm stuff in a separate file.

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesKtTest.kt
> +class MoreQuestionnairesKtTest {
```suggestion
class MoreQuestionnairesTest {
```

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.contextR4).isNotNull()
these are two test cases.

2021-07-07 15:42 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.npmPackage).isNotNull()
again two test cases -- same below.

2021-07-09 08:16 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +object NpmPackageProvider {
Can we leave this as public?

The whole initial setup process takes around 3 minutes on a good device and I plan to have this happening after installation and application start so that extraction is fast having done this previously.

The target application would have to setup the module after installation and load the modules at application start

2021-07-09 08:55 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesKtTest.kt
> +class MoreQuestionnairesKtTest {
Done, sorry about this

2021-07-09 09:05 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.contextR4).isNotNull()
Kinda but logically it's one. The aim of the test is make sure that the method `loadSimpleWorkerContext` can initialize `contextR4` when not previously initialized. 

We need to confirm that `contextR4` is not initialized before starting the test. Is this what you meant?

2021-07-09 09:08 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.npmPackage).isNotNull()
Kinda but logically it's one. The aim of the test is make sure that the method `loadSimpleWorkerContext` can initialize `npmPackage` when not previously initialized. 

We need to confirm that `npmPackage` is not initialized before starting the test. Is this what you meant?

-----------------

The same applies for the test below in `loadSimpleWorkerContext() should cache SimpleWorkerContext`

2021-07-09 09:09 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  fun loadSimpleWorkerContextWithPackage(context: Context): SimpleWorkerContext {
Done

2021-07-09 09:09 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val structureMap = structureMapProvider(structureMapUrl)
Done

2021-07-09 09:10 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      extractByDefinitionBased(questionnaire, questionnaireResponse)
Sounds better

2021-07-09 09:10 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      extractByStructureMapBased(
Sounds better. Done

2021-07-09 16:05 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +object NpmPackageProvider {
3 minutes! that's mad... can you add a documentation here to say this process is very time consuming

2021-07-09 16:16 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.contextR4).isNotNull()
i think you can have a test case for the exception if you don't call the load function. and another test case for if you call the function.

these are fundamentally 2 different cases -- i think for unit tests we try to keep each test case really really simple and follows the 3 steps -> arrange act and assert.

here's some more background: https://livebook.manning.com/book/effective-unit-testing/chapter-4/112

2021-07-09 16:16 UTC, jingtang10 requested changes
still prefer to split the tests -- see comments in file

2021-07-09 16:16 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.contextR4).isNotNull()
also import `assertThat`

2021-07-12 10:44 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +object NpmPackageProvider {
I see this is is already documented [here](https://github.com/google/android-fhir/blob/ek/sdc-structure-map-extraction-implementation/datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt#L64). 

I'll add extra documentation on the specific methods and some guiding documentation on the class itself

2021-07-12 11:00 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +    Truth.assertThat(NpmPackageProvider.contextR4).isNotNull()
Cool, I'll remove the exception asserts in all the test cases and import `assertThat`

2021-07-13 10:36 UTC, jingtang10 requested changes

2021-07-13 10:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +object NpmPackageProvider {
general comment: the file IO functions should be `suspend` functions

2021-07-13 10:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  fun loadSimpleWorkerContext(context: Context): SimpleWorkerContext {
if you call this function, you'll end up calling `setupNpmPackage` without checking if it's been loaded before?

2021-07-13 15:36 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/NpmPackageInitializationError.kt
> +class NpmPackageInitializationError : RuntimeException {
Changed

2021-07-13 15:36 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +
Cool

2021-07-13 15:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +      Log.e(ResourceMapper::class.java.name, e.stackTraceToString())
Removed

2021-07-13 15:39 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TarGzipUtility.kt
> + * libraries
Changed

2021-07-13 16:40 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  }
Cool

2021-07-13 17:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +        packageDirectory.delete()
We just have a `SecurityException` in a case where access would be denied. Since this is private app storage, this will not be an issue.

2021-07-13 17:40 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +    val filename = "packages.fhir.org-hl7.fhir.r4.core-4.0.1.tgz"
Done

2021-07-13 17:44 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +      IOUtils.closeQuietly(outputStream)
Done

2021-07-13 17:46 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return targetResource
Done

2021-07-13 17:48 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  fun loadSimpleWorkerContext(context: Context): SimpleWorkerContext {
Good question, `setupNpmPackage` does the check itself and only proceeds if not previously loaded

2021-07-13 17:52 UTC, ekigamba commented
https://github.com/google/android-fhir/pull/566#discussion_r668639055

@jingtang10 
> general comment: the file IO functions should be suspend functions

Correct, we will generally want to change the ResourceMapper extraction functions to suspend functions

2021-07-13 20:43 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TarGzipUtility.kt
> +    TarArchiveInputStream(GzipCompressorInputStream(FileInputStream(compressedFilePath))).use { fin
Done

2021-07-15 11:03 UTC, jingtang10 requested changes

2021-07-15 11:03 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +/**
looking at this file i'm still slightly confused by the apis.

it still feels like it's doing too much. can we maybe have 2 classes

- `NpmPackageProvider`
- `SimpleWorkerContextProvider`

so in the former you have `getNpmPackage(context: Context)` and in the latter you have `getSimpleWorkerContext(context: Context)`. The latter depends on the former. And both caches what needs to be cached within themselves.

2021-07-15 16:12 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TarGzipUtility.kt
> +    }
Changed

2021-07-15 16:15 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +        packageDirectory.delete()
Done

2021-07-15 16:17 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +    return outDir
Done

2021-07-15 16:17 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  /** Generate the path to the local npm packages directory */
Done

2021-07-15 16:19 UTC, ekigamba commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val commonsIo = "commons-io:commons-io:${Versions.commonsIo}"
Done

2021-07-15 16:20 UTC, ekigamba commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val commonsIo = "2.10.0"
Done

2021-07-15 16:21 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +   * @return [Bundle] containing the extracted [Resource]s
Cool, updated

2021-07-15 16:26 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          structureMapProvider(questionnaire.targetStructureMap!!),
I agree. This has been changed

2021-07-15 16:28 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    contextR4.setExpansionProfile(Parameters())
Extraction crashes for some instances when this is not provided

2021-07-15 16:29 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    val contextR4 = NpmPackageProvider.loadSimpleWorkerContext(context)
Done

2021-07-15 16:31 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          this
I just tried this and I get the error `Named arguments are not allowed for non-Kotlin functions`

2021-07-15 16:34 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  lateinit var contextR4: SimpleWorkerContext
Done

2021-07-15 16:37 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TarGzipUtility.kt
> +        }
Yea,nice catch

2021-07-19 09:29 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +/**
I have split the functionalities into separate files

2021-07-20 08:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          this
in that case add comments:

```
/* appInfo= */ simpleWorkerContext,
/* source= */ questionnaireResponse,
...
```

2021-07-20 09:15 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProvider.kt
> +  fun loadSimpleWorkerContext(npmPackage: NpmPackage): SimpleWorkerContext {
really feels like one of these two apis can go.

2021-07-20 09:15 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +@RunWith(RobolectricTestRunner::class)
what is this class testing? is it not just testing your shadow?

2021-07-21 07:26 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProvider.kt
> +  fun loadSimpleWorkerContext(npmPackage: NpmPackage): SimpleWorkerContext {
Done

2021-07-21 07:26 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProvider.kt
> +  fun loadSimpleWorkerContext(context: Context): SimpleWorkerContext {
Yes

2021-07-21 07:29 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProvider.kt
> +  lateinit var simpleWorkerContext: SimpleWorkerContext
Done

2021-07-21 07:32 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/SimpleWorkerContextProviderTest.kt
> +      .isEqualTo(SimpleWorkerContextProvider.simpleWorkerContext)
Done

2021-07-21 07:38 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/NpmPackageProviderTest.kt
> +@RunWith(RobolectricTestRunner::class)
Yea, at this point that's correct. I'm going to remove this and in case there any extra changes then you can point them out when you review again

2021-07-21 08:58 UTC, jingtang10 approved these changes
Great work! 👌

2021-07-21 08:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  lateinit var npmPackage: NpmPackage
this needs to be private also

2021-07-21 11:14 UTC, merged

2021-07-21 11:16 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  lateinit var npmPackage: NpmPackage
Done

2021-07-22 07:05 UTC, ekigamba commented
> Great work!

Thanks :pray: