Added AutoComplete support to questionnaire items
google/android-fhir pull request #575
Opened 2021-06-22 22:20 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #520 

**Description**
Added a new ViewHolderFactory for autocomplete. It creates a Chip for a selected answer and allows multiple answers/Chips if Questionnaire.repeats is true

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
No

**Type**
Choose one: Feature 

**Screenshots (if applicable)**
![device-2021-06-23-034620](https://user-images.githubusercontent.com/18224849/123006996-1d1f8880-d3d6-11eb-8588-ca66a48bac82.png)
![device-2021-06-23-034843](https://user-images.githubusercontent.com/18224849/123007006-214ba600-d3d6-11eb-92b5-ec1544ea78c5.png)

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-23 14:04 UTC, joiskash reviewed
Just put a few comments, please have a look , thanks!

2021-06-23 14:04 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal const val ITEM_CONTROL_AUTO_COMPLETE = "autocomplete"
Should we maintain these constants in alphabetical order?

2021-06-23 14:04 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +      ITEM_CONTROL_DROP_DOWN,
same as above

2021-06-24 08:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItem.itemControl == ITEM_CONTROL_AUTO_COMPLETE) {
Autocomplete does not have a drop down, so questionnaire authors must make sure that autocomplete widget type is used for questions which have answers that are general. eg: Which country do you reside in?

The above comment will be addressed in multi-select dropdown with checkbox

2021-06-25 10:17 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +    if (questionnaireItem.itemControl == ITEM_CONTROL_AUTO_COMPLETE) {
Done

2021-06-25 10:18 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal const val ITEM_CONTROL_AUTO_COMPLETE = "autocomplete"
done

2021-06-25 10:18 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +      ITEM_CONTROL_DROP_DOWN,
done

2021-06-28 10:20 UTC, jingtang10 requested changes

2021-06-28 10:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        } != null
```suggestion
        return chipContainer.children.any { view ->
          view is Chip && (view as Chip).text == selection
        }
```

2021-06-28 10:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          questionnaireItemViewItem.takeIf { addNewChipIfNotPresent(answer) }?.addAnswer(answer)
not sure about this logic - i kind feel like we should use the answers as the "source of truth" rather than the display text in chips.

so i think we should check that the answer isn't there already, and if not, add a new chip.

2021-06-28 10:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        }
```suggestion
        questionnaireItemViewItem.questionnaireResponseItem.answer?.let {
          if (canHaveMultipleAnswers) {
            it.map{ addNewChipIfNotPresent(it) }
          } else {
            replaceChip(it.last())
          }
        }
```

2021-06-28 10:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +              val chip = chipContainer.getChildAt(chipContainer.childCount - 2) as Chip
I think you need to document somewhere that the last element of the layout is the edittext, otherwise this code is going to be very hard to understand.

2021-06-28 10:20 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +/*
i feel like there are test cases for inputing options. are they difficult to test in here? if so do we need to use ui automater etc?

2021-06-28 16:24 UTC, aditya-07 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +    Truth.assertThat(viewHolder.itemView.findViewById<TextView>(R.id.prefix).isVisible).isTrue()
Done

2021-06-28 16:29 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        get() = questionnaireItemViewItem.questionnaireItem.repeats
The value of canHaveMultipleAnswers is dynamic and changes with the current questionnaireItemViewItem set by bind(). So keeping it.

2021-06-28 16:30 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +
Done

2021-06-28 16:30 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +      private fun addNewChipIfNotPresent(
Done

2021-06-28 16:30 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        // in the recyclerview
Done

2021-06-28 17:32 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        } != null
In line with your comment below, refactored the code to check if Answer is present instead of checking the text.

2021-06-28 17:34 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          questionnaireItemViewItem.takeIf { addNewChipIfNotPresent(answer) }?.addAnswer(answer)
Done

2021-06-28 17:34 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        }
Done

2021-06-28 17:35 UTC, aditya-07 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +/*
As discussed, I will create a separate PR for this.

2021-06-28 17:36 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +              val chip = chipContainer.getChildAt(chipContainer.childCount - 2) as Chip
Done.

2021-06-29 09:06 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
> +/*
can you create an issue as well?

2021-06-29 09:06 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +        get() = questionnaireItemViewItem.questionnaireItem.repeats
got it thanks!

2021-06-29 09:08 UTC, jingtang10 approved these changes

2021-06-29 10:06 UTC, merged