Deduplicate patients record.
google/android-fhir pull request #583
Opened 2021-06-23 14:51 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #563 

**Description**
Deduplicate resource record by resource id after search query execution.

**Alternative(s) considered**
No

**Type**
Choose one: (Bug fix)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-24 07:28 UTC, jingtang10 requested changes
please add tests

2021-06-25 12:01 UTC, santosh-pingle commented
@jingtang10 please review once!

2021-06-28 11:12 UTC, jingtang10 requested changes

2021-06-28 11:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
>          when (SearchParamType.fromCode(pair.first.type)) {
```suggestion
        when (SearchParamType.fromCode(searchParam.type)) {
```

2021-06-28 11:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +    return n?.let { Triple(n.name, n.path, n.value) }
never use single letter param names.

2021-06-28 11:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +  private fun indexValues(pair: Pair<SearchParamDefinition, Base>): Serializable? {
so for every index record, you'll be calculating the index twice - this seems like a waste?

can you generate these indices first, and then find a way to deduplicate?

maybe you'll need to redefine a `equals` function for the index classes?

2021-06-28 11:12 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
> +      .distinctBy { pair -> indexValues(pair) }
why isn't this step after the index has been calculated below?

2021-06-28 14:08 UTC, santosh-pingle commented
@jingtang10 thanks!

Updated changes, please review once.

2021-06-29 09:31 UTC, jingtang10 approved these changes
Thanks @santosh-pingle! This way is much better! 🎉

2021-06-29 09:31 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    assertThat(result.filter { it.id.contains("1401518") }).hasSize(1)
can you do `it.id = something` rather than using `contains` (maybe you need to add `Patient/` or something?

unlikely to create flakey test in this example, but I'd really rather the logic in tests is always precise.

2021-06-29 09:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
> +  fun index_duplicateString_deDuplicatesStringIndices() {
supernit: deduplicate is one word. same below

```suggestion
  fun index_duplicateString_deduplicatesStringIndices() {
```

2021-06-29 11:16 UTC, merged