implement date sort and test
google/android-fhir pull request #584
Opened 2021-06-24 00:00 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #547 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-24 04:42 UTC, maanuanubhav999 commented
Will add few more tests as discussed with @epicadk

2021-06-24 04:58 UTC, epicadk commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +        ORDER BY b.index_value ASC
there is no `index_value` column for `dateIndexEntity` so you'll probably have to use `index_to` or `index_from` here

2021-08-30 04:47 UTC, Tarun-Bhardwaj commented
@maanuanubhav999 , could you please assign this PR to your mentor for the first level review?

2021-08-30 15:12 UTC, maanuanubhav999 commented
@Tarun-Bhardwaj hi, it is not related to GSoC.  Do you still want me to get a review from my mentor. thanks.

2021-08-30 17:36 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val ids = results.map { it.id }
Does this preserve order? Maybe you can use mapIndexed just to be sure.

2021-08-30 17:37 UTC, maanuanubhav999 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val ids = results.map { it.id }
okay, I will try.

2021-08-30 17:43 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val ids = results.map { it.id }
Another approach would be to use Guava to check if the list is sorted.

2021-08-31 07:51 UTC, Tarun-Bhardwaj commented
> @Tarun-Bhardwaj hi, it is not related to GSoC. Do you still want me to get a review from my mentor. thanks.

Yes, that would help. Thanks!

2021-09-03 12:12 UTC, epicadk commented
> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fandroid-fhir%2Fpull%2F584) for more info**.

@googlebot I consent

2021-09-03 12:13 UTC, epicadk commented
@googlebot I consent.

2021-09-03 12:15 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .containsExactly("Patient/test_patient_1", "Patient/$earlyDateId", "Patient/$laterDateId")
This contains `"Patient/test_patient_1"` even though the value is null. Is this how we want to handle null values or is this is bug? cc @jingtang10

2021-09-03 12:19 UTC, epicadk commented
@maanuanubhav999 as discussed on slack this should solve it :). Can you please solve the merge conflicts?

2021-09-03 12:20 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .containsExactly("Patient/test_patient_1", "Patient/$earlyDateId", "Patient/$laterDateId")
FYI the same thing would happen for numbers and strings as well.

2021-09-04 03:43 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .containsExactly("Patient/$laterDateId", "Patient/$earlyDateId", "Patient/test_patient_1")
I really think that we should use something link guava to check is the list is sorted because we probably want to add parameterized tests in the future. But maybe we can do that in a different pr.

2021-09-04 03:43 UTC, epicadk approved these changes

2021-11-10 22:31 UTC, jingtang10 requested changes
Thanks for this! @maanuanubhav999 👍

2021-11-10 22:31 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        is DateClientParam -> "DateIndexEntity"
i think we should create an enum to encapsulate sort table name + sort column name, so that later in line 67-72 you don't need to write the if statement

something like this:

```
private enum class SortTableInfo(val tableName: String, val columnName: String) {
  STRING_SORT_TABLE_INFO("StringIndexEntity", "index_value"),
  NUMBER_SORT_TABLE_INFO("NumberIndexEntity", "index_value"),
  DATE_SORT_TABLE_INFO("DateIndexEntity", "index_from")
}
```

2021-11-10 22:31 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .containsExactly("Patient/$laterDateId", "Patient/$earlyDateId", "Patient/test_patient_1")
doesn't `inOrder` in the next line do that?

2021-11-10 22:31 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val laterDate = DateType("2020-12-15")
these can all be inlined... no need to do this in tests. in unit tests repitition is less a problem. rather we just want the test case to be short and easy to read.

2021-11-10 22:31 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    database.insert(patient2)
```suggestion
    database.insert(
      Patient().apply {
        id = "older-patient"
        birthDateElement = DateType("2020-12-12")
      }
    )

    database.insert(
      Patient().apply {
        id = "younger-patient"
        birthDateElement = DateType("2020-12-13")
      }
   )
```

2021-11-10 22:31 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +  fun search_date_sort_appointmentDate() {
how is this test case different from the first one? do we really need this?

2021-11-11 04:54 UTC, epicadk commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .containsExactly("Patient/$laterDateId", "Patient/$earlyDateId", "Patient/test_patient_1")
> doesn't `inOrder` in the next line do that?

In this case I think it does, but what I meant was maybe instead of providing input and expected data for each test we could just check if the resultant list is sorted based on a given criteria.

2021-11-27 12:48 UTC, maanuanubhav999 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        is DateClientParam -> "DateIndexEntity"
sure, undetstood

2021-11-28 18:23 UTC, maanuanubhav999 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +      .containsExactly("Patient/$laterDateId", "Patient/$earlyDateId", "Patient/test_patient_1")
hey @jingtang10 any final thoughts about this, also we may need to discuss this [comment](https://github.com/google/android-fhir/pull/584#discussion_r701843016)

2021-11-29 10:02 UTC, jingtang10 approved these changes
Thanks @maanuanubhav999

2021-11-29 10:02 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val ids = results.map { it.id }
yes this does preserve order

2021-11-29 10:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    .getMethod("set${field.name.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.ROOT) else it.toString() }}", field.nonParameterizedType)
what's wrong with capitalize?

2021-11-29 17:32 UTC, maanuanubhav999 commented on buildSrc/src/main/kotlin/JacocoConfig.kt
> +  fun JacocoOptions.() {
Sorry, this was by mistake

2021-11-29 17:44 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    .getMethod("set${field.name.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.ROOT) else it.toString() }}", field.nonParameterizedType)
really sorry I don't understand how I messed up this during the merge. There was a suggestion to use replaceFirstChar since capitalize is deprecated. I will revert it.

2021-11-30 10:30 UTC, jingtang10 approved these changes

2021-11-30 10:30 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val ids = results.map { it.id }
this variable can be inlined

2021-11-30 10:30 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val results =
this variable can be inlined

2021-11-30 10:30 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val results =
this variable can be inlined

2021-11-30 10:30 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +    val ids = results.map { it.id }
this variable can be inlined

2021-11-30 12:41 UTC, merged