Horizontal layout support for RadioButton and CheckBox
google/android-fhir pull request #586
Opened 2021-06-24 04:13 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #542

**Description**
Add horizontal layout support for RadioButton and CheckBox using `choiceOrientation` ItemComponent

**Alternative(s) considered**
Also add HorizontalScrollView because there are limited space when rendering horizontally

**Type**
Choose one: Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-06-30 13:00 UTC, jingtang10 commented
Thanks @FikriMilano for this change!

I don't think we spoke about the design here. But I have some high level questions: 

1. have you considered using the same widget (radio button group) but placing the logic to change orientation in the widget's initialization code? this way you could hide the logic to decide orientation would live in the widget rather than the adapter.
2. if the width is too narrow for the options, i would very much like for the options to naturally flow like text. i think creating a scroll bar is not going to be great for usability. it's somewhat important in my view that the user can see all the options. for this @aditya-07 tried https://github.com/google/flexbox-layout. but you might have other solutions.

2021-07-01 03:40 UTC, FikriMilano commented
> 
> 
> Thanks @FikriMilano for this change!
> 
> I don't think we spoke about the design here. But I have some high level questions:
> 
>     1. have you considered using the same widget (radio button group) but placing the logic to change orientation in the widget's initialization code? this way you could hide the logic to decide orientation would live in the widget rather than the adapter.
> 
>     2. if the width is too narrow for the options, i would very much like for the options to naturally flow like text. i think creating a scroll bar is not going to be great for usability. it's somewhat important in my view that the user can see all the options. for this @aditya-07 tried https://github.com/google/flexbox-layout. but you might have other solutions.

Happy to help @jingtang10 

1. I did actually and at first it won't work. But now you mention this, I just tried this again and turns out it's possible. 
There are: 
   - less code
   - the adapter is much cleaner
   - the widget works fine

2. Thanks, this is the behavior I was looking for. I just tried the flexbox and it works great.
Is this what you have in mind? Here's a screenshot:
<img src="https://user-images.githubusercontent.com/62053304/124060199-bbef5900-da56-11eb-8a4b-b00a3e6f484f.png" width="256"> 

Note:
My thumb made a slip, accidentally closed the PR yesterday haha

2021-07-09 14:09 UTC, Tarun-Bhardwaj commented
@jingtang10 , could you please review this PR?

2021-07-23 14:16 UTC, FikriMilano commented
**Update**
@jingtang10 we can create a custom layout called FlexRadioGroup that extends to FlexboxLayout.
Let me know if this is the right approach for this.

Here is the result:

<img src="https://user-images.githubusercontent.com/62053304/126794519-ca4c9ff1-8b69-40cf-a584-dbd588d12fa8.png" width="256">

2021-08-07 00:43 UTC, fredhersch commented
@Tarun-Bhardwaj is this pending a PR review? cc: @aditya-07 @jingtang10

2021-08-07 14:35 UTC, Tarun-Bhardwaj commented
> @Tarun-Bhardwaj is this pending a PR review? cc: @aditya-07 @jingtang10

Yes @fredhersch , the PR is pending review.

2021-08-30 04:49 UTC, Tarun-Bhardwaj commented
@FikriMilano , could you please assign this PR to your mentor for an initial review?

2021-08-30 12:21 UTC, FikriMilano commented
> @FikriMilano , could you please assign this PR to your mentor for an initial review?

Sure.
@qiarie

2021-08-31 07:46 UTC, Tarun-Bhardwaj commented
> > @FikriMilano , could you please assign this PR to your mentor for an initial review?
> 
> Sure.
> @qiarie

@qiarie , assigned the PR to you for an initial review. Adita/Jing/Steven/Kevin would review it once you are done before the changes are merged. CC: @jingtang10

2021-11-11 00:29 UTC, jingtang10 requested changes
Hi @FikriMilano! Thanks so much for this change!

I just came across the new constraint layout's support for flow and I tried it: https://github.com/google/android-fhir/compare/jt/flow-layout?expand=1

![Screenshot (11 Nov 2021 00_28_56)](https://user-images.githubusercontent.com/28757340/141215212-1819d97a-03b4-4fbf-9da9-416f669fe7ae.png)


Do you think constraint layout is better or worse than flexbox?

@aditya-07 did you know about constraint layout's support?

2021-11-12 06:28 UTC, FikriMilano commented
> I just came across the new constraint layout's support for flow and I tried it: https://github.com/google/android-fhir/compare/jt/flow-layout?expand=1
> 
> Do you think constraint layout is better or worse than flexbox?

I'm not sure, need to try that out first

2021-11-23 12:54 UTC, jingtang10 commented
> 

pl

2021-11-23 12:55 UTC, jingtang10 commented
> > I just came across the new constraint layout's support for flow and I tried it: https://github.com/google/android-fhir/compare/jt/flow-layout?expand=1
> > Do you think constraint layout is better or worse than flexbox?
> 
> I'm not sure, need to try that out first

Can you do that please? I'm keen to not to have to introduce a lot of code if there's simpler support :)

2021-11-24 00:48 UTC, FikriMilano commented
sure, that makes sense

2021-12-28 11:56 UTC, FikriMilano commented
Some updates on this, need to develop function that handles RadioButton selection since it's not supported by Flow

2021-12-30 11:30 UTC, jingtang10 commented
thanks - let me know when this is ready for review

2022-01-13 08:51 UTC, Tarun-Bhardwaj commented
++ @anita-vadverao , could you please run some tests on this?

2022-01-26 17:45 UTC, jingtang10 commented
@juanchazo can you please leave a review? thanks

2022-01-30 05:18 UTC, FikriMilano commented
Added Flow in CheckBoxGroup as well, since we plan to remove FlexBoxLayout soon. #1082

2022-02-01 11:37 UTC, jingtang10 requested changes
@FikriMilano thanks for the updates!

I'm not seeing in this PR how the default behavior (vertical layout) is maintained. Have you tested it?

2022-02-02 08:39 UTC, FikriMilano commented
@jingtang10 yeah, I tested it.
Here are the newest screenshots:

Vertical
<img src="https://user-images.githubusercontent.com/62053304/152118231-d0149841-d646-4192-9dfc-707c117d99ef.png" width="256">

Horizontal
<img src="https://user-images.githubusercontent.com/62053304/152118325-bfdd0461-5755-43d6-885e-0c65161fc066.png" width="256">

2022-02-07 12:33 UTC, jingtang10 requested changes

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          }
can you use `forEachIndexed`?

doing `++` inside `forEach` seems very procedural - i think we should use the provided api `forEachIndexed` if we can.

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        for (i in 1 until checkboxGroup.childCount) {
add a comment to say why it now starts from 1

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
instead of using `index`, this is actually related to the overall size of the answers. so just use the answerOption.size

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +              if (isChecked) {
use `when`

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          val radioButton =
i think what you did with the other file is really nice - having a separate function for this part. can you do the same?

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +                if (isChecked) {
use `when` instead of `if`?

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
```suggestion
        val refIds = IntArray(questionnaireItemViewItem.answerOption.size) { it }
```

or `{ it + 1}`

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          questionnaireItemViewItem.answerOption.forEach { answerOption ->
can you add a comment to describe the id values of each of the checkbox created?

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        if (choiceOrientation == CHOICE_ORIENTATION_HORIZONTAL) {
use `when`

2022-02-07 12:33 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +                  if (previousId != -1) {
this is using a function closure - which is fine. but maybe another way of doing this is to just looka the siblings and clear anything that's checked?

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryInstrumentedTest.kt
> +    assertThat(answerOptionText2.text).isEqualTo("Coding 2")
okay, that's possible

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal const val CHOICE_ORIENTATION_VERTICAL = "vertical"
sure

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +internal val Questionnaire.QuestionnaireItemComponent.choiceOrientation: String?
okay

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          }
i think that's possible, let me try

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        for (i in 1 until checkboxGroup.childCount) {
okay

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
okay

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +              if (isChecked) {
okay

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          val radioButton =
sure

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +                if (isChecked) {
okay

2022-02-08 00:28 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
okay, that's better

2022-02-08 00:30 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          questionnaireItemViewItem.answerOption.forEach { answerOption ->
okay, but could you elaborate more on what to describe?

2022-02-08 00:30 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        if (choiceOrientation == CHOICE_ORIENTATION_HORIZONTAL) {
okay

2022-02-08 00:31 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +                  if (previousId != -1) {
okay - that's possible, but wouldn't that be slower? by going through each item

2022-02-09 09:24 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          questionnaireItemViewItem.answerOption.forEach { answerOption ->
i think we need to say, the checkbox ids will start from 1? for example, if there are two checkboxes, they will have ids "1" and "2". something like this.

2022-02-09 09:27 UTC, jingtang10 requested changes

2022-02-09 14:06 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          questionnaireItemViewItem.answerOption.forEach { answerOption ->
okay, thanks

2022-02-09 23:01 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +                  if (previousId != -1) {
Yeah

2022-02-09 23:02 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
I mean the previousId variable. I worry its value will get lost.

2022-02-10 03:03 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +                  if (previousId != -1) {
okay

2022-02-10 03:08 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
yeah - that would be bad, it would cause two selection on the radio buttons.
i haven't encounter that bug on this, but perhaps let @anita-vadverao test this widget?

2022-02-10 17:34 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
i think if it is a UI state it definitely should be saved properly. i would much prefer to just clear the siblings.

@kevinmost do you agree with this?

2022-02-10 17:39 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
sorry i realised the third comment in this thread should be for this comment above: https://github.com/google/android-fhir/pull/586/files/bd4334cae92ab0f62834501386bae63a951581d3#r800609951

i was using mobile not sure how things got tangled.

2022-02-10 17:58 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
I think it would improve code readability and cut down on potential lifecycle errors, as Jing mentioned, to just iterate through all of the buttons and clear the ones that don't match the clicked ID when any button is clicked.

Something like:

```kotlin
val buttons = // however you get all the radio button IDs

buttons.forEach { button ->
  button.setOnCheckedChangeListener { checked -> 
    if (checked) uncheckIfNotButtonId(button.id)
  }
}

private fun uncheckIfNotButtonId(id: Int) {
  buttons.forEach { button -> if (button.id != id) button.isChecked = false }
}
```

Any state we can remove from the system is an improvement to readability, IMO.

2022-02-11 07:00 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        val refIds = IntArray(index - refId) { refId++ }
okay then, thanks for the suggestions @kevinmost @jingtang10

2022-02-18 16:47 UTC, jingtang10 requested changes

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        // By default, checkbox starts from index 1
```suggestion
        // The Flow layout has index 0. The checkbox indices start from 1.
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          val singleCheckBox =
```suggestion
        val checkBoxLayout =
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +                if (choiceOrientation == ChoiceOrientationTypes.HORIZONTAL)
use `when`

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        flow.referencedIds = IntArray(0)
similarly, do you really need this line? if you do, add a comment to explain why

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        radioGroup.removeViews(1, radioGroup.childCount - 1)
```suggestion
        // Keep the Flow layout which is the first child
        radioGroup.removeViews(1, radioGroup.childCount - 1)
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        flow.referencedIds = refIds
I suggest we use the API `View.generateViewId()` to generate view id rather than doing the book keeping ourselves. this way we don't have to keep doing the +1 business which is probably bug-prone.

In the following code, for each answer option, we are generating a view id -> answer option pair, we pass that to the function, and then at the end we collect the view ids to give them to the flow layout as reference ids.

```suggestion
        questionnaireItemViewItem
          .answerOption
          .map { answerOption -> View.generateViewId() to answerOption }
          .onEach { populateViewWithAnswerOption(it.first, it.second, choiceOrientation) }
          .map { it.first }
          .let { flow.referencedIds = it.toIntArray() }
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        flow.referencedIds = refIds
same here:

I suggest we use the API `View.generateViewId()` to generate view id rather than doing the book keeping ourselves. this way we don't have to keep doing the +1 business which is probably bug-prone.

In the following code, for each answer option, we are generating a view id -> answer option pair, we pass that to the function, and then at the end we collect the view ids to give them to the flow layout as reference ids.

```suggestion
        questionnaireItemViewItem
          .answerOption
          .map { answerOption -> View.generateViewId() to answerOption }
          .onEach { populateViewWithAnswerOption(it.first, it.second, choiceOrientation) }
          .map { it.first }
          .let { flow.referencedIds = it.toIntArray() }
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +      private fun populateViewWithAnswerOption(
add new line

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        index: Int
```suggestion
        viewId: Int
        answerOption: Questionnaire.QuestionnaireItemAnswerOptionComponent,
        choiceOrientation: ChoiceOrientationTypes
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +            id = index + 1
```suggestion
            id = viewId
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        index: Int
```suggestion
        viewId: Int,
        answerOption: Questionnaire.QuestionnaireItemAnswerOptionComponent,
        choiceOrientation: ChoiceOrientationTypes
```

2022-02-18 16:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +            id = index + 1
```suggestion
            id = viewId
```

2022-02-21 03:21 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        flow.referencedIds = IntArray(0)
sure, at first I thought this was supposed to prevent ref ids duplication, but turns out its not, so it should be fine to remove this now

2022-02-21 03:25 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
>          val singleCheckBox =
okay

2022-02-21 03:29 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +                if (choiceOrientation == ChoiceOrientationTypes.HORIZONTAL)
okay

2022-02-21 03:29 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        flow.referencedIds = IntArray(0)
we can remove this

2022-02-21 03:30 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +      private fun populateViewWithAnswerOption(
okay

2022-02-21 03:41 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        flow.referencedIds = refIds
Wow, yeah that is definitely better

2022-02-21 03:44 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        index: Int
okay

2022-02-21 03:46 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        checkboxGroup.removeViews(1, checkboxGroup.childCount - 1)
okay

2022-02-21 03:46 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        // By default, checkbox starts from index 1
okay

2022-02-21 03:47 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        radioGroup.removeViews(1, radioGroup.childCount - 1)
okay

2022-02-21 03:47 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +            id = index + 1
okay

2022-02-21 03:48 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        flow.referencedIds = refIds
okay

2022-02-21 03:48 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +        index: Int
okay

2022-02-21 03:48 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +            id = index + 1
okay

2022-02-21 08:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +        flow.referencedIds = refIds
glad you liked it

2022-02-21 08:53 UTC, jingtang10 approved these changes
Great job! Thanks @FikriMilano! 👍

2022-02-21 12:08 UTC, merged