Added Retry logic to syncing resources.
google/android-fhir pull request #603
Opened 2021-06-29 07:19 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #535

**Description**
Clients would call appropriate functions of `Sync.kt` to initiate/setup sync for the resources with `RetryConfiguration`.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-07-02 15:06 UTC, jingtang10 approved these changes

2021-07-02 15:06 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    retryConfiguration: RetryConfiguration? = DefaultRetryConfiguration
can you make retryConfig part of the periodicSyncConfig?

2021-07-02 15:29 UTC, yigit requested changes

2021-07-02 15:29 UTC, yigit commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val mockk = "io.mockk:mockk:${Versions.mockk}"
if you can write the tests w/o mockk, that would be great.
mocking helps write the teest easy but is pain in the neck when debugging. we usually discourage mocking unless it is the last resort.

2021-07-02 15:29 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +      Result.failure()
```suggestion
    return when {
      result is Success -> Result.success()
      retries -> runAttemptCount -> Result.retry()
      else -> Result.failure()
```

would make it easier to read. (feel free to ignore).

2021-07-02 15:29 UTC, yigit commented on engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
> +    @MockK lateinit var engine: FhirEngine
referring back to my earlier comment on mockK, these are our own classes so you can create fake implementations (or even use the real one with an in memory database).

2021-07-05 05:50 UTC, deepankarb reviewed
Structurally LGTM. I have left some feedback. Thanks for adding comments to the code.

2021-07-05 05:50 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  val DefaultRetryConfiguration =
```suggestion
  val defaultRetryConfiguration =
```

2021-07-05 05:50 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  inline fun <reified W : FhirSyncWorker> oneTimeSync(
Suggest using a different name since this is significantly different in behaviour (i.e. retries) than a strictly "one time" sync as declared above.

2021-07-05 05:50 UTC, deepankarb commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +      Result.failure()
I'd prefer `when` over `if-else if` since it's easier to read and maintain.

2021-07-06 15:35 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +  /** Maximum retries for a failing [FhirSyncWorker] */
Done

2021-07-06 15:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Config.kt
> +data class BackOffCriteria(
Done

2021-07-06 15:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +      )
Done

2021-07-06 15:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +    retryConfiguration: RetryConfiguration? = DefaultRetryConfiguration
Done

2021-07-06 15:38 UTC, aditya-07 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val mockk = "io.mockk:mockk:${Versions.mockk}"
The reason I prefer mocking here is because `FhirSynchronizer` internally has a lot of moving parts that we will have to take care of if we don't use a mocking framework. And for our tests, we only need the end result/state of the whole `FhirSynchronizer#synchronize() `process which is pretty easy to get using mockk framework's constructor mocking without having to run the whole process. 
Additionally the objects we have mocked are just to satisfy the dependency and aren't actually run against.

2021-07-06 15:38 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +      Result.failure()
Done

2021-07-06 15:39 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
> +    @MockK lateinit var engine: FhirEngine
The objects we have mocked are just to satisfy the dependency and aren't actually run against.

2021-07-06 15:41 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  val DefaultRetryConfiguration =
Done and with the Jing's [comment](https://github.com/google/android-fhir/pull/603#discussion_r663079545) , moved this to `Config.kt`

2021-07-06 15:41 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  inline fun <reified W : FhirSyncWorker> oneTimeSync(
Function name is inline with the OneTimeWorkRequest of WorkManager framework which handles retries. If you still feel the name is misleading, I can change it.

2021-07-07 15:15 UTC, jingtang10 approved these changes

2021-07-08 16:19 UTC, aditya-07 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val mockk = "io.mockk:mockk:${Versions.mockk}"
I had a discussion with @jingtang10 as well and concluded we are better off without mockk. So removing the dependency.

2021-07-08 16:20 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
> +    @MockK lateinit var engine: FhirEngine
mockk removed

2021-07-09 09:56 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/sync/Sync.kt
> +  inline fun <reified W : FhirSyncWorker> oneTimeSync(
i think `oneTimeSync` is ok and consistent with work manager so can keep for now

2021-07-09 10:03 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +      object : FhirEngine {
Optional - can put this in a separate file for reuse.

2021-07-09 10:04 UTC, jingtang10 approved these changes

2021-07-09 10:05 UTC, merged

2021-07-09 23:59 UTC, yigit commented on engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
> +      object : FhirEngine {
+1, it is better to call them Fake, create a fakes package and re-use them