Add tests for API 30, cache AVD
google/android-fhir pull request #619
Opened 2021-07-01 17:35 UTC by yigit

This PR adds testing for API 30 devices.

* Cleaned up the CI build a bit to explicitly have a matrix parameter for full build.
* Added cache for AVD

Fixes #617
Test: CI

2021-07-01 17:55 UTC, yigit commented
btw this is not ready to be reviwed, still trying to figure out why the filter are not working .

2021-07-02 15:48 UTC, epicadk commented on .github/workflows/ci.yml
> +        emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
The emulator seems to be working fine because we are using `macos-11` (private preview). If we want this change maybe we could also downgrade the runner to `macos-latest`? But then why not use the latest version?

2021-08-04 12:21 UTC, stevenckngaa reviewed
Hey Yigit, this PR is marked as **Code owner review required**. However, from the comments and build logs, API 30 is still not passing. Do you have a chance to look into the cause?

2021-08-10 11:38 UTC, Tarun-Bhardwaj commented
> Hey Yigit, this PR is marked as **Code owner review required**. However, from the comments and build logs, API 30 is still not passing. Do you have a chance to look into the cause?

Hi @yigit , did you get a chance to look into this query?

2021-11-29 14:54 UTC, jingtang10 requested changes
@yigit do you still want to work on this or should we close this?

2022-01-29 11:05 UTC, Tarun-Bhardwaj commented
> @yigit do you still want to work on this or should we close this?

@yigit , @jingtang10 , are there changes still pending or can this be closed?

2022-02-08 18:12 UTC, jingtang10 commented
chatted with @yigit. agreed to close this since a lot has changed and we'll probably use gradle build actions.

2022-02-08 18:12 UTC, closed without merging