View patient card.
google/android-fhir pull request #631
Opened 2021-07-05 13:38 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #622 

**Description**
Just show the patient registration information that was captured in the Add patient issue. These can be displayed as name/value pairs in rows

**Alternative(s) considered**
No

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-07-06 10:44 UTC, Tarun-Bhardwaj commented
@aditya-07 , assigning it to you for reviewing the changes.

2021-07-07 07:04 UTC, aditya-07 requested changes

2021-07-07 07:04 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> -  val html: String = if (hasText()) text.div.valueAsString else ""
Can you double check if `hasText()` is just checking for `null` or other values as well.

2021-07-09 07:00 UTC, aditya-07 approved these changes
Just do this change. Looks good otherwise.

2021-07-09 07:00 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +    patientItem?.let {
Instead of using `it` in the apply sections, can you use explicit name because of the  nested scopes

```
patientItem?.let { patient ->
        binding.patientDetail.apply {
          text = HtmlCompat.fromHtml(patient.html, HtmlCompat.FROM_HTML_MODE_LEGACY)
        }
..
..
..
```

2021-07-09 09:06 UTC, merged