WIP | DONOT Merge | 554 Flow API for one-time and periodic tasks
google/android-fhir pull request #648
Opened 2021-07-14 20:49 UTC by maimoonak

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #554 

**Description**
Implementation of FlowAPI for managing sync states and last sync date for one-time and periodic sync

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR? WIP

**Type**
Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-07-20 16:58 UTC, maimoonak commented
@f-odhiambo Here is the PR for feedback on last sync date issue

2021-07-22 11:31 UTC, kevinmost requested changes

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/SharedPreferencesUtil.kt
> +      commit()
`commit` blocks this thread. If you use `apply`, it wouldn't block, but then you have to deal with possibly-stale values.

Maybe we can make this a `suspend fun write` and keep `commit`, so that it's essentially asynchronous? @yigit any opinions?

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/SharedPreferencesUtil.kt
> +      commit()
Same question here for @yigit

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
> +internal class FhirEngineImpl constructor(private val database: Database, context: Context) :
Nit: The `constructor` keyword is unnecessary here, remove it.

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +  data class Glitch(val exceptions: List<ResourceSyncException>) : State()
What is the difference between `Glitch` and `Error`?

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/SyncJob.kt
> +  ): Flow<MutableList<WorkInfo>>
Change this to `Flow<List<WorkInfo>>`. We shouldn't pass around mutable collections.

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/SyncJob.kt
> +  fun stateFlowFor(uniqueWorkerName: String, context: Context): Flow<State>
Let's change `uniqueWorkerName: String` to `worker: SyncWorkType`, and let the implementation call `worker.workerName` internally.

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +class SyncJobImpl(
All of the public-facing functions on this class need a `Context`. Could you add `private val context: Context` to the constructor, and remove the Context parameter from the functions in the interface?

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +      .mapNotNull { if (it.isEmpty()) null else it[0] } // todo its always 0 ... would it be??
This can be

```kt
.mapNotNull { it.getOrNull(0) }
```

2021-07-22 11:31 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +    return null
This can be made functional:

```kt
return workInfos
  .asSequence()
  .filter { it.state != ENQUEUED && it.progress.keyValueMap.isNotEmpty() }
  .map { workInfo ->
    val state = workInfo.progress.getString("StateType")!!
    val stateData = workInfo.progress.getString("State")!!
    Gson().fromJson(stateData, Class.forName(state)) as State
  }
  .firstOrNull()
```

2021-07-22 11:31 UTC, kevinmost commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
> +  object testDataSourceImpl : DataSource {
Nit: `object` names should start with an uppercase letter

2021-07-22 11:31 UTC, kevinmost commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
> +  object testFhirEngineImpl : FhirEngine {
Same

2021-07-22 11:31 UTC, kevinmost commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
> +  object testCorruptDatasource : DataSource {
Same

2021-07-22 11:31 UTC, kevinmost commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +  @Mock private lateinit var dataSource: DataSource
In Kotlin, prefer using the mockito-kotlin helpers

```kt
private val database = mock<Database>()
private val dataSource = mock<DataSource>()
```

I think you can also remove `MockitoAnnotations.openMocks(this)` on line 78

2021-07-22 11:31 UTC, kevinmost commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    assertTrue(workInfoList.size == 7)
Please replace `org.junit.Assert.*` usages with `com.google.common.truth.Truth.assertThat` throughout this file.

Eg:

```kt
assertThat(workInfoList).hasSize(7)

assertThat(workInfoList[0].state).isEqualTo(WorkInfo.State.ENQUEUED)

assertThat(stateList[0]).isInstanceOf(State.Nothing::class.java)
```

2021-07-22 21:16 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/SharedPreferencesUtil.kt
> +      commit()
We should use jetpack data store instead of shared preferences. 
Even though Shared Prefs have an async write API, it might still block the UI thread if a write is pending while context is being destroyed.

2021-07-22 21:19 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/SharedPreferencesUtil.kt
> +      commit()
Sorry I didn't read the whole CL (ooo) but unless I'm missing something, we should use data store,not shred preferences.
Data store also provides first class coroutines API, which is what we want for internals

2021-07-27 11:00 UTC, maimoonak commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +  data class Glitch(val exceptions: List<ResourceSyncException>) : State()
Error or Success is final state emitted when Synchronizer finishes and sends final result. The Glitch is the intermediate error it faces and still continues. A Glitch may lead to Success or Error at the end, but we are enabling consumer to read intermediates states and progress for all resource types

2021-07-27 20:08 UTC, maimoonak commented
@kevinmost @yigit Thanks alot for the detailed and through feedback. It helped and made the code much more readable and precise. I have resolved all of the comments and this PR is ready for review. Aside from code and general design approach please review the approach being used in FhirSyncWorker and WorkManager usage in SyncJobImpl.

2021-07-29 13:25 UTC, kevinmost approved these changes
Once these comments are addressed, LGTM for merging.

2021-07-29 13:25 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/DatastoreUtil.kt
> +    millis = runBlocking { context.dataStore.data.first()[lastSyncTimestampKey] } ?: return null
This can be combined, and turned into a val

```kt
val millis = runBlocking { ... } ?: return null
```

2021-07-29 13:25 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +              "State" to Gson().toJson(it)
Creating `Gson` instances can be expensive. Please move this up to a property on the class:

```kt
private val gson: Gson = Gson()
```

and then use that property here

```kt
"State" to gson.toJson(it)
```

2021-07-29 13:25 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
> +    kotlin.runCatching { job.join() }.onFailure { Log.w(javaClass.name, it) }
Please pull out the tag for this log as well, so that it's not computed every time we log.

2021-07-29 13:25 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
> +  data class Glitch(val exceptions: List<ResourceSyncException>) : State()
Makes sense. Please add docs on each of these state classes explaining the difference.

2021-07-29 13:25 UTC, kevinmost commented on engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
> +        Gson().fromJson(stateData, Class.forName(state)) as State
Similarly, please make a val for this `Gson` instance within this class so that it's only instantiated once for this class, instead of every time we call `convertToState`

2021-07-29 13:25 UTC, kevinmost commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    Thread.sleep(5000) // how to avoid it ???
Not sure, but what if you call

```kt
job1.join()
job2.join()
```

2021-07-29 13:25 UTC, kevinmost commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    assertThat(res[4]).isInstanceOf(State.Failed::class.java)
You can also do

```kt
    assertThat(res.map { it::class.java })
      .containsExactly(
        State.Nothing::class.java,
        State.Started::class.java,
        State.InProgress::class.java,
        State.Glitch::class.java,
        State.Failed::class.java,
      ).inOrder()
```

Then you won't need the `assertThat(res).hasSize(5)` assertion below, either.

2021-08-02 14:37 UTC, Tarun-Bhardwaj commented
@maimoonak , could you please advise a date by when the changes suggested by Kevin in his last review get incorporated?

2021-08-04 01:26 UTC, maimoonak commented on engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
> +    Thread.sleep(5000) // how to avoid it ???
@kevinmost I tried but it does not work

2021-08-04 06:54 UTC, maimoonak commented
@kevinmost Please review. I have updated it and also added the Sync status to UI where for now it sends the updated state. 

<img src="https://user-images.githubusercontent.com/4829880/128135197-1e0fd882-2ab6-477a-a716-3533a032208f.jpg" data-canonical-src="https://user-images.githubusercontent.com/4829880/128135197-1e0fd882-2ab6-477a-a716-3533a032208f.jpg" width="200" height="400" />

2021-08-09 13:01 UTC, kevinmost approved these changes
Suggested some minor changes, but looks good once those are resolved.

2021-08-11 14:09 UTC, merged