Add missing nested answers to the questionnaire response item map
google/android-fhir pull request #662
Opened 2021-07-21 17:22 UTC by jingtang10

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #652 

**Description**

- In the questionnaire response item map, we were missing answers to questions nested under other non-group questions. This causes issues for enable when evaluation because no answer can be retrieved to evaluate if another question should be enabled or not
- The assumption that the response item map is immutable needs to be removed. This is because as the user answers questions, more nested items might be created (questions nested under other questions are nested in the response under the answers).

**Alternative(s) considered**
NA

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-07-21 17:40 UTC, joiskash requested changes
Please look at the comments.

2021-07-21 17:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        }
Optional: Better readability if we specify "it" .. for the outer let `questionnaireItemComponent ->` and inside the forEach `questionnaireResponseItemComponent`

2021-07-21 17:40 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        createLinkIdToQuestionnaireResponseItemMap(it.item)
We need the putAll or else the map will not have them
```
item.answer.forEach {
        linkIdToQuestionnaireResponseItemMap.putAll(
          createLinkIdToQuestionnaireResponseItemMap(it.item)
        )
      }
```

2021-07-21 17:50 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        linkIdToQuestionnaireResponseItemMap[linkId]?.addNestedItemsToAnswer(it)
Could linkIdToQuestionnaireResponseItemMap[linkId] be null? Wouldn't line 81 guarantee that linkIdToQuestionnaireResponseItemMap[linkId] isn't null unless there is a potential race condition somewhere?

2021-07-22 00:07 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        }
done.

2021-07-22 00:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        createLinkIdToQuestionnaireResponseItemMap(it.item)
done

2021-07-22 00:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        linkIdToQuestionnaireResponseItemMap[linkId]?.addNestedItemsToAnswer(it)
Not really - the questionnaire response might not have been created for certain nested items yet. I've simplified the code to address this.

2021-07-22 00:56 UTC, jingtang10 commented
thanks @joiskash @stevenckngaa please take anther look!

2021-07-22 07:09 UTC, joiskash approved these changes
Awesome! thanks

2021-07-22 09:15 UTC, merged