Fixed add patient crash after resource extraction
google/android-fhir pull request #664
Opened 2021-07-21 17:54 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #663 

**Description**
Fixed issue by extracting `Patient` from the `Bundle` returned by `ResourceMapper.extract()` 

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-07-21 18:08 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt
> +        ResourceMapper.extract(questionnaireResource, questionnaireResponse).entry[0].resource as
Could entry be an empty list? If it's possible, should you fail the save operation gracefully with error message rather than crashing the reference app?

2021-07-21 18:27 UTC, jingtang10 requested changes

2021-07-21 18:27 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt
> +        ResourceMapper.extract(questionnaireResource, questionnaireResponse).entry[0].resource as
try something like this?

```suggestion
        val something = ResourceMapper.extract(questionnaireResource, questionnaireResponse).singleOrNull() ?: return
        val patient = something.resource as Patient
```

2021-07-21 19:03 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/AddPatientViewModel.kt
> +        ResourceMapper.extract(questionnaireResource, questionnaireResponse).entry[0].resource as
Using `entryFirstRep` property of `Bundle` that promises to returns first entry. If entry list is empty, it will add an entry and then return the first. I am now checking for the type of the `entry.resource` and returning gracefully if its not Patient.

2021-07-22 02:24 UTC, jingtang10 approved these changes

2021-07-22 10:08 UTC, merged