Convert ResourceMapper extract and populate functions to suspend funcs
google/android-fhir pull request #667
Opened 2021-07-22 09:05 UTC by ekigamba

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #666 

**Description**
Convert ResourceMapper, SimpleWorkerContextProvider and NpmPackageProvider functions to suspend functions

**Alternative(s) considered**
None

**Type**
Feature

**Screenshots (if applicable)**
None

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-07-27 08:24 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        )
nit: Are the named arguments required here. Can they be removed?

2021-07-27 10:16 UTC, aditya-07 requested changes

2021-07-27 10:16 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private suspend fun extractByDefinitions(
All the heavy duty private functions in the file called by `extractByDefinitions ` should also be marked `suspend` e.g. `extractFields`, `extractField`

2021-07-27 10:16 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  suspend fun populate(questionnaire: Questionnaire, resource: Resource): QuestionnaireResponse {
`populateInitialValues`, `populateInitialValue` should also be suspending functions.

2021-07-27 10:16 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  suspend fun loadNpmPackage(context: Context): NpmPackage {
`setupNpmPackage` should be a marked suspend.

2021-07-28 13:55 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        )
Cool

2021-07-28 13:58 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private suspend fun extractByDefinitions(
Done

2021-07-28 13:59 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  suspend fun populate(questionnaire: Questionnaire, resource: Resource): QuestionnaireResponse {
Done

2021-07-28 13:59 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/NpmPackageProvider.kt
> +  suspend fun loadNpmPackage(context: Context): NpmPackage {
Done

2021-08-03 08:51 UTC, aditya-07 approved these changes
LGTM

2021-08-03 08:52 UTC, merged