Update answers to the choice of data type field.
google/android-fhir pull request #676
Opened 2021-07-28 11:38 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #674 

**Description**
Choice data type is added value[X] (e.g valueQuantity ...)
Answer is updated to the nested field of choice data type  (e.g Quantity.value, Quantity.code ...)

**Alternative(s) considered**
No

**Type**
Choose one: (Bug fix)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-03 08:17 UTC, aditya-07 requested changes

2021-08-04 08:12 UTC, aditya-07 approved these changes

2021-08-04 08:15 UTC, aditya-07 commented
LGTM. Please merge the changes once builds pass.

2021-08-04 09:00 UTC, merged

2021-09-22 11:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      }
i think this needs a bit of cleanup. line 233 and line 260 both check if the item is a group. can this logic be unified rather than scatted around in different places?