VitalSigns questionnaire
google/android-fhir pull request #685
Opened 2021-08-04 16:05 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #625 

**Description**
Update vitalsigns questionnaire with code.

**Alternative(s) considered**
no

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-05 08:19 UTC, aditya-07 requested changes

2021-08-05 08:19 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        return UriType(answer.value)
What do you think of having extension functions like `StringType.toUriType()`, `StringType.to CodeType()`  etc. for all the conversions done here, in a separate file that can be used by others as well?

2021-08-05 08:31 UTC, santosh-pingle commented on reference/src/main/java/com/google/android/fhir/reference/ScreenerViewModel.kt
> +          if (resource.hasValueQuantity() && !resource.valueQuantity.hasValueElement()) {
This check is for valueQuantity only. 
As of now we only have temp, pulse, heart rate observation which belongs to ValueQuantity.

For other values there will be separate check respective of their value type.

2021-08-05 14:16 UTC, aditya-07 requested changes

2021-08-05 14:16 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/utilities/TypeConversionUtil.kt
> +fun StringType.toUriType(): UriType {
These look good. Can we mark these internal so that they are available to the library only?

2021-08-05 14:16 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/utilities/TypeConversionUtilTest.kt
> +  fun stringType_toUriType() {
The tests look good. Please check the assertion with the expected object instead of the value similar to `assertThat(uri.equalsDeep(UriType("fakeCode"))).isTrue()`

2021-08-06 06:08 UTC, aditya-07 approved these changes
LGTM.

2021-08-06 06:54 UTC, merged