Reference app UI updates
google/android-fhir pull request #691
Opened 2021-08-09 15:40 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #654

**Description**
1. Update reference app design
2. Display observations and conditions in the Patient details page.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-12 07:38 UTC, jingtang10 commented
Update the type in the description.

2021-08-12 16:02 UTC, jingtang10 requested changes

2021-08-12 16:02 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +  private fun renderCard(header: CharSequence, observations: List<Model>) {
```suggestion
  private fun renderCard(header: CharSequence, models: List<Model>) {
```

this is not limited to observation so use generic names for variables.

2021-08-13 06:36 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    Thread.sleep(TimeUnit.MILLISECONDS.toMillis(100))
I have removed this. It was to delay loading of observations before the patient resource got loaded.

2021-08-13 06:36 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerView.kt
> +data class Model(
Done

2021-08-13 06:37 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerView.kt
> +abstract class ItemViewHolder(view: View) : RecyclerView.ViewHolder(view) {
Removed in cleanup.

2021-08-13 06:37 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerView.kt
> +class HeaderItemViewHolder(val binding: PatientDetailsHeaderBinding) :
Removed in cleanup.

2021-08-13 06:38 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +                Model("Gender", patient.gender.capitalize(Locale.ROOT)),
It's easier to add more values this way. In a layout, it would just be repeating rows.

2021-08-13 06:39 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    Thread.sleep(TimeUnit.MILLISECONDS.toMillis(200))
Done

2021-08-13 06:39 UTC, aditya-07 commented on reference/src/main/res/layout/patient_details_layout.xml
> +<!--      android:layout_height="wrap_content"/>-->
done

2021-08-13 06:39 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +  //  val patientCount = liveData { emit(count()) }
done

2021-08-13 06:39 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +      ).years.let { return@let if (it > 0) it else 1 }} years old"
done

2021-08-13 06:41 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +      "Id: #---${patientItem.resourceId.substring(patientItem.resourceId.length - 3)}"
Done. Also, substring is here because that's how the ID was shown the UI deck.

2021-08-13 06:41 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +      else "No effective DateTime"
done

2021-08-13 06:41 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    // val observation: Observation = getObservationDetails(position)
done

2021-08-13 06:41 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    val dateTimeStr =
done

2021-08-13 06:41 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
>    private fun createObservationItem(
done

2021-08-13 06:42 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +    if (observations.isNotEmpty()) {
done

2021-08-13 06:43 UTC, aditya-07 commented on reference/src/main/res/layout/patient_details_header.xml
> +        android:text="Mary Odhiambo"
Supposed to be tools:text

2021-08-13 06:44 UTC, aditya-07 commented on reference/src/main/res/layout/patient_details_header.xml
> +        android:text="Last Contacted: none"
done

2021-08-13 06:45 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +      val observations = it.map { observation -> Model(observation.code, observation.value) }
done

2021-08-13 06:45 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +  private fun renderCard(header: CharSequence, observations: List<Model>) {
done

2021-08-13 06:45 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +        MaterialCardView(ContextThemeWrapper(container.context, R.style.CardView)).apply {
Moved to a layout file

2021-08-13 06:45 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +        MaterialTextView(container.context).apply {
Moved to a layout file

2021-08-13 06:46 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +  }
done

2021-08-13 06:46 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +    //    this.idView.text = patientItem.id
done

2021-08-13 06:46 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerView.kt
> +class ChildItemViewHolder(binding: PatientListItemViewBinding) : ItemViewHolder(binding.root) {
removed in cleanup

2021-08-13 08:34 UTC, jingtang10 requested changes

2021-08-13 08:34 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +        if (observations.isEmpty()) View.GONE else View.VISIBLE
for consistency can we have two methods analogous to `setupPatientData`? e.g. `setUpObservation` and `setUpCondition`?

2021-08-13 08:34 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +        addView(lineView(this))
this whole block is repeated later on - can you reuse the code somehow? extension function? private helper function etc?

2021-08-13 11:00 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +        if (observations.isEmpty()) View.GONE else View.VISIBLE
Done

2021-08-13 11:00 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +        addView(lineView(this))
Done

2021-08-13 13:34 UTC, jingtang10 commented
@aditya-07 can you also include before/after screenshots? thanks!

2021-08-13 14:51 UTC, stevenckngaa commented on reference/src/main/res/layout/patient_list_item_view.xml
> +    <ImageView
Could you please point me to the mock? The one I saw has the status image aligned to the start of parent not at the center.

2021-08-13 14:51 UTC, stevenckngaa commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:layout_alignStart="@id/name"
In the mock I had, this is aligned to the end of status and below parent name.

2021-08-13 14:51 UTC, stevenckngaa commented on reference/src/main/res/layout/patient_details_header.xml
> +    android:background="#10156125"
From the mock this is #F1F3F4

2021-08-13 14:51 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
>      super.onViewCreated(view, savedInstanceState)
Can we use a single RecyclerView for rendering patient details,  observation and conditions? Using 3 LinearLayouts in a NestedScrolledView isn't very scalable. Views won't be recycled and you may end up using a lot of memory.

You could have an adapter called PatientDetailsAdapter which takes a list of objects that are PatientItem, ObservationItem & ConditionItem. Each Item should have a view binder to bind the UI and data.

2021-08-13 14:51 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +          PatientProperty("Mobile Number", patient.phone),
Could this be reference by String resource instead?

2021-08-16 11:06 UTC, aditya-07 commented on reference/src/main/res/values/strings.xml
> +  <string name="html_text">Current status: <font
This is spotless's output.

2021-08-16 12:45 UTC, jingtang10 approved these changes

2021-08-16 13:59 UTC, aditya-07 commented on reference/src/main/res/values/colors.xml
> +    <color name="colorPrimaryDark">#175adf</color>
Was using **colorPrimaryDark** to update the status bar. So added **```android:statusBarColor```** to the theme instead.

2021-08-16 14:07 UTC, aditya-07 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:contentDescription="Status"
Done

2021-08-16 14:09 UTC, aditya-07 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +    <ImageView
Changed the status alignment.

![image](https://user-images.githubusercontent.com/18224849/129576960-c06d1a80-cdf5-4731-b539-15232637026d.png)

2021-08-16 14:10 UTC, aditya-07 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:layout_alignStart="@id/name"
This would do the same. Name is aligned to end of status and this is aligned to the start of name. See the image in above comment.

2021-08-16 14:15 UTC, aditya-07 commented on reference/src/main/res/layout/patient_details_header.xml
> +    android:background="#10156125"
The color is dynamic and dependent on the RiskAssessment of the Patient. There is another ticket that takes care of updating the color here & the traffic colors in the patient list page properly based on the RiskAssessment.

2021-08-16 14:21 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
>      super.onViewCreated(view, savedInstanceState)
The rationale with not using RecyclerView here is that each group : Patient detail, observation & condition is shown as an independent card and then each row would have to have a background either with top rounder corners, regular rectangle or bottom rounded corners to give you an illusion of being in a single card. Otherwise, if each row/viewholder is a card, then while binding you would endup dynamically adding those values anyways.

2021-08-16 14:24 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +          PatientProperty("Mobile Number", patient.phone),
Done

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    val observations: MutableList<PatientListViewModel.ConditionItem> = mutableListOf()
s/observations/conditions

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +        createObservationItem(index + 1, fhirPatient, getApplication<Application>().resources)
Please explain the reason of + 1 here. Same for line 68.

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    private fun createObservationItem(
Annotate with @JvmStatic

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +      val dateTimeStr =
Again, don't omit braces if if-else-if-else expression doesn't fit one line.

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    private fun createConditionItem(
Please annotate with @JvmStatic

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
>      super.onViewCreated(view, savedInstanceState)
Do they need to be cards?

From the mocks, I would split the UI in a common of ViewHolders
1. Patient status (Name, status, last contacts + a button)
2. A common item for showing an icon on the start, tile, subtile and a button on the right
3. A common item for showing at most 2 buttons
4. A section header (for patient log, symptoms & vitals)
5. Some other UI

Each item appearance depends on its corresponding ViewBinder implementation. You can reuse existing Android state or create new state and then use [StateListDrawable](https://developer.android.com/reference/android/graphics/drawable/StateListDrawable) to swap out the background.

The main issue here is patient log can be a very long list. If you use a LinearLayout, you will end up consuming a lot of memory and eventually out of memory. In addition, the mock indicates that each patient mode can be expanded / collapsed. Using RecycleView will give you the expand / collapse animation for free.

If this is a production app, I will not let this go. However, since this is a reference app, I will defer the decision to to @jingtang10

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/res/layout/patient_detail.xml
> +    android:orientation="vertical"
From the mock, there is a 16dp horizontal padding. And there is also a 16dp in the children.

2021-08-16 17:55 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +    // The new ui just shows shortened id with just last 3 characters.
Put this as the kdoc for getTruncatedId

2021-08-16 20:08 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +  data class PatientProperty(
Done

2021-08-16 20:08 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
> +      if (observations.isEmpty()) View.GONE else View.VISIBLE
Done

2021-08-16 20:10 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +        createObservationItem(index + 1, fhirPatient, getApplication<Application>().resources)
The index is not used anymore so changed the code. In `createObservationItem`, passing `Observation.id` where index was being passed. Currently `id` is not being used, but can be used later.

2021-08-16 20:10 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +      val dateTimeStr =
done

2021-08-16 20:11 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    private fun createConditionItem(
Since the function is a private one and not being called from java code, don't think the annotation is required.

2021-08-16 20:12 UTC, aditya-07 commented on reference/src/main/res/layout/patient_detail.xml
> +    android:orientation="vertical"
done.

2021-08-16 20:12 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +    // The new ui just shows shortened id with just last 3 characters.
done

2021-08-16 20:12 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    private fun createObservationItem(
Since the function is a private one and not being called from java code, don't think the annotation is required.

2021-08-16 20:12 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    val observations: MutableList<PatientListViewModel.ConditionItem> = mutableListOf()
done

2021-08-18 16:25 UTC, aditya-07 commented
@stevenckngaa @jingtang10 Please check the updates. The new UI in patients page with recyclerview:

![device-2021-08-18-214715](https://user-images.githubusercontent.com/18224849/129935544-8e586acb-6fc5-489a-a1d2-fc065a1b132a.png)

2021-08-18 17:28 UTC, stevenckngaa reviewed
Thank you. This is a lot better.

2021-08-18 17:28 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +data class PatientDetailDataModel(
Can we break this into multi data classes? This is error prone because

1. All data fields (except firstInGroup, lastInGroup) can be null.
2. Multiple data fields can be non-nullable.

In both cases, we don't know which view binder to pick.

```
interface PatientDetailData {
  val firstInGroup: Boolean = false,
  val lastInGroup: Boolean = false
}

data class PatientDetailHeader(
  val header: String,
   override val firstInGroup: Boolean 
   override val firstInGroup: Boolean 
): PatientDetailData

data class PatientDetailProperty(
  val patientProperty: PatientProperty,
   override val firstInGroup: Boolean 
   override val firstInGroup: Boolean 
): PatientDetailData

...
```

2021-08-18 17:28 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +    holder.itemView.background =
No action: If you replace the background drawable here, you will end up interrupting with any ripple effect when adding an item. An improvement is to replace this with [StateListDrawable](https://developer.android.com/reference/android/graphics/drawable/StateListDrawable) which already have attributes for first, middle & last.

Since each row isn't clickable, there is no ripple effect. No need to do anything.

2021-08-18 17:28 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +          header = getApplication<Application>().getString(R.string.header_observation)
Use the `getString` function in this class rather than from Application class. Same applies for line 136.

2021-08-18 19:26 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +          header = getApplication<Application>().getString(R.string.header_observation)
done

2021-08-18 19:26 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +data class PatientDetailDataModel(
done

2021-08-20 09:28 UTC, stevenckngaa reviewed
Thanks. Looking good.

2021-08-20 09:28 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +      o is PatientDetailHeader && n is PatientDetailHeader && n.header == o.header ||
If you implement equal in each of these classes, you don't need line 221 - 231.

e.g.
```
data class PatientDetailHeader(
  val header: String,
  override val firstInGroup: Boolean = false,
  override val lastInGroup: Boolean = false
) : PatientDetailData {
    override fun equals(other: Any?): Boolean {
    	if (this === other) return true
    	if (other !is PatientDetailHeader) return false
        return this.header == other.header
    }
}
```

2021-08-20 09:28 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
>      return (o == n ||
Note that `===` compares memory address, `==` uses equals(..) to compare. Once you adopt the next comment, you can keep this.

2021-08-23 14:02 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +class PatientOverviewItemVH(
nit: ViewHolder rather than VH :)

2021-08-23 14:04 UTC, jingtang10 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:id="@+id/age"
```suggestion
        android:id="@+id/key"
```

2021-08-23 14:05 UTC, jingtang10 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:layout_below="@id/age"
```suggestion
        android:layout_below="@id/value"
```

2021-08-23 14:13 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +      return@let if (it > 0) it else 1
you can just omit the `return@let` i think?

just `if ... else ...`

2021-08-23 14:15 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +      return@let if (it > 0) it else 1
Why this logic anyway? I don't think we normally say 1yo for children less than 1yo.

2021-08-23 18:30 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +      o is PatientDetailHeader && n is PatientDetailHeader && n.header == o.header ||
Done

2021-08-23 18:31 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
>      return (o == n ||
Done

2021-08-23 18:31 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +class PatientOverviewItemVH(
Done

2021-08-23 18:31 UTC, aditya-07 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:id="@+id/age"
Done

2021-08-23 18:31 UTC, aditya-07 commented on reference/src/main/res/layout/patient_list_item_view.xml
> +        android:layout_below="@id/age"
Done

2021-08-23 18:33 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +      return@let if (it > 0) it else 1
I have changed the code to use plural resources.

2021-08-23 20:39 UTC, stevenckngaa approved these changes

2021-08-23 20:39 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +  override fun equals(other: Any?): Boolean {
Sorry, it's been a while since I wrote Kotlin. I just remember data class has auto generated equals & hashcode. See https://kotlinlang.org/docs/data-classes.html

Given all your data classes have final primitive / nested data class, you can rely on the auto generated equals & hashcode.

2021-08-23 20:39 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +  private val ageView: TextView = binding.fieldName
fieldNameView. The text may not be age any more.

2021-08-24 06:09 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
> +  private val ageView: TextView = binding.fieldName
In this ViewHolder, `ageView` is still used to display age. The backing xml field however is generic and so named  fieldName.

2021-08-24 06:46 UTC, merged

2021-08-24 09:13 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +  override fun equals(other: Any?): Boolean {
I still find the custom equals & hashcode, do you really need them?

2021-08-24 10:53 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +  override fun equals(other: Any?): Boolean {
I merged the PR before removing the changes. Will create a separate PR to remove these.