Support Date Approximate
google/android-fhir pull request #692
Opened 2021-08-09 17:38 UTC by epicadk

- Support date approximate
- add some comments

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #586

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-09 18:03 UTC, Tarun-Bhardwaj commented
@epicadk , are you sure this PR fixes #586 (as mentioned in the description above)? Should it not be #568 ?

2021-08-09 18:21 UTC, epicadk commented
My bad, I was using the CLI and messed up the numbering.

2021-08-11 06:03 UTC, epicadk commented
@Tarun-Bhardwaj done with the changes. awating review

2021-08-19 05:48 UTC, jingtang10 requested changes

2021-08-19 05:48 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +  const val mockkAndroid = "io.mockk:mockk-android:${Versions.mockk}"
the reason that mocking is needed here is that the `getCurrentDate` function is written as a global function. Can you add something like a "date provider" that the engine/search class depends on so you can easily use a custom implementation of that provider in tests?

@stevenckngaa @yigit  @kevinmost do you agree with this approach?

2021-08-19 05:48 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_dateTime_Approximate() = runBlocking {
```suggestion
  fun search_dateTime_approximate() = runBlocking {
```

2021-08-19 05:48 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +
can you add two negative cases (where no result is returned) as well?

2021-08-19 05:48 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        (value.rangeEpochDays.first -
`value.rangeEpochDays.first` is already defined as `start`
and `value.rangeEpochDays.last` as `end`

same with below

2021-08-19 05:48 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +            0.1 * (value.rangeEpochDays.first - currentDateTime.rangeEpochDays.first).absoluteValue)
define a APPROXIMATION_COEFFICIENT as 0.1 and add a comment that explains what it is and links to the spec.

same with below

2021-08-20 06:57 UTC, epicadk commented
Sort of busy with the presentation will work on this after.

2021-08-23 13:51 UTC, jingtang10 requested changes

2021-08-23 13:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/MoreDates.kt
> +internal fun getCurrentDate() = Date.from(Instant.now())
remove? this is not used any more i think

2021-08-23 13:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> + * multiplier required to Approximate to a 10% range see https://www.hl7.org/fhir/search.html#prefix
```suggestion
 * The multiplier used to determine the range for the `ap` search prefix. See https://www.hl7.org/fhir/search.html#prefix for more details.
```

2021-08-23 13:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +              (start - currentDateTime.rangeEpochDays.first).absoluteValue)
make this a private util function

2021-08-23 13:51 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  val dateProvider: Clock = Clock.systemDefaultZone()
@stevenckngaa @kevinmost @yigit do you think this should be part of the fhir engine rather than the search interface?

2021-08-24 07:44 UTC, epicadk commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  val dateProvider: Clock = Clock.systemDefaultZone()
I've added it to the fhir engine for now. I'll rebase if just having it in the search api is fine.

2021-11-17 12:23 UTC, jingtang10 approved these changes

2021-11-17 14:01 UTC, merged