Added support to search using multiple resource types
google/android-fhir pull request #697
Opened 2021-08-10 15:00 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #611

**Description**
Added a nested search to the current Search class so that the user can do a search reverse chained search like
 `Return all Patients who have a Condition - Diabetes referenced by Condition.subject property`

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-19 07:06 UTC, jingtang10 reviewed
Great job!!!

2021-08-19 07:06 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +   */
```suggestion
  /**
   * Provides limited support for the reverse chaining on [Search]
   * [https://www.hl7.org/fhir/search.html#has]. For example: search all Patient that
   * have Condition - Diabetes. This search uses the subject field in the Condition resource. Code snippet:
   * ```
   *     FhirEngine.search<Patient> {
   *        has<Condition>(Condition.SUBJECT) {
   *          filter(Condition.CODE, Coding("http://snomed.info/sct", "44054006", "Diabetes"))
   *        }
   *     }
   * ```
   */
```

2021-08-19 07:06 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      AND $outerTableAlias.resourceId IN (
have you considered using a join? is it feasible at all?

2021-08-19 08:59 UTC, jingtang10 requested changes
QQ: what happens when you try to have mulit-level nesting? Have you tested? Can you add a test case?

2021-08-19 09:05 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +  val outerTableAlias = if (nestedContext == null) "a" else "c"
why `a` and `c`? i know normally people don't care about aliasis in the sql query... but let's just make them a little more readable here :)

2021-08-19 09:44 UTC, jingtang10 requested changes
QQ: what happens when you try to have mulit-level nesting? Have you tested? Can you add a test case?

2021-08-19 09:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  @PublishedApi internal var nestedSearch: NestedQuery? = null
this should be a list. by default the top level logical operator is and (similar to the filters) so if a query has multiple `has`es we need to put them all in a query and join them using `AND`.

also this needs to be separate test case

2021-08-19 09:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +  inline fun <reified R : Resource> has(
is it possible at all to group the nested query stuff into a separate file?

2021-08-19 09:44 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    print(query.query)
remove.

2021-08-19 09:44 UTC, jingtang10 commented on engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
> +    print(query.args)
remove.

2021-08-19 09:44 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      }
i think this logic is slightly hard to read here. to understand what a nested query looks like, the reader needs to figure out what `select`, `from`, and `where` clauses look like and mentally put them together.

is it better to have a master switch somewhere for nested queries and then put the logic together? and then that logic can probably be moved to a separate file.

2021-08-31 11:05 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      AND $outerTableAlias.resourceId IN (
agreed. would be a problem with joins.

2021-09-01 12:22 UTC, jingtang10 approved these changes

2021-09-01 12:22 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        $sortOrderStatement
please refactor so that count queries don't include sort order statement and limit statement? throw exception and add a test case as well please.

happy for you to do that in a follow-up immediately after this pr.

2021-09-01 12:22 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        SELECT COUNT(*)
fix the indentation for here and for below

```suggestion
        """ 
        SELECT COUNT(*)
```

2021-09-01 12:22 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      """
```suggestion
        """
```

2021-09-01 12:22 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  fun search_patient_return_single_patient_who_has_diabetic_careplan() = runBlocking {
```suggestion
  fun search_patient_returnSinglePatientWhoHasDiabeticCareplan() = runBlocking {
```

same with the other test cases

2021-09-01 20:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      """
Done

2021-09-01 20:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +        SELECT COUNT(*)
Done

2021-09-02 02:52 UTC, merged