Hotfix sync exceptions for failing server
google/android-fhir pull request #708
Opened 2021-08-12 13:35 UTC by maimoonak

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-13 06:27 UTC, aditya-07 requested changes

2021-08-13 06:27 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/Util.kt
> +class StateExclusionStrategy : ExclusionStrategy {
Mark it internal.

2021-08-13 06:27 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/Util.kt
> +class StateExclusionStrategy : ExclusionStrategy {
Also, please write a kdoc explaining its need.

2021-08-13 06:27 UTC, aditya-07 commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
> +      val hugeStackTraceMessage = (1..10242).map { allowedChars.random() }.joinToString("")
Please mention the reason for this size. You can link `Data.MAX_DATA_BYTES` here.

2021-08-13 06:27 UTC, aditya-07 commented on engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
>    object TestCorruptDatasource : DataSource {
Do you think FailingDataSource would be a better suited name? IMHO corrupt data source can still return bad data.

2021-08-13 06:27 UTC, aditya-07 commented on engine/src/test/java/com/google/android/fhir/sync/TestCorruptSyncWorker.kt
> +class TestCorruptSyncWorker(appContext: Context, workerParams: WorkerParameters) :
Same name change here?

2021-08-13 16:54 UTC, jingtang10 approved these changes

2021-08-13 16:54 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/Util.kt
> + * FhirSynchronizer. It should skip serializing the exceptions to avoid WorkManager WorkData limit
```suggestion
 * Exclusion strategy for [Gson] that handles field exclusions for [State] returned by
 * FhirSynchronizer. It should skip serializing the exceptions to avoid exceeding WorkManager WorkData limit.
```

add link to issue. e.g.

`See https://github.com/google/android-fhir/issues/707.`

2021-08-17 07:09 UTC, aditya-07 approved these changes

2021-08-17 07:20 UTC, merged