Hotfix: Allow using a custom TransformSupportServices for StructureMap
google/android-fhir pull request #712
Opened 2021-08-16 07:54 UTC by ekigamba

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Allow using a custom TransformSupportServices for StructureMap. When using StructureMap-based extraction, we use the command `create('ResourceType')` to generate new instances of resources. The current implementation lacks support for internal model type eg `RiskAssessment.Prediction`, `Immunization.Reaction`. 

**Description**
Add an optional `TransformSupportServices` param to the ResourceMapper#extract method and 

**Alternative(s) considered**
Yes, adding support for the internal models inside the datacapture model. This would take longer to implement because it's not clear how many models are not supported. Adding support for an internal model would require making changes to android-fhir.

**Type**
Choose one: Feature

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-17 08:16 UTC, ekigamba commented
@jingtang10 Kindly review. This is a small PR that fixes an issue with ResourceMapper extraction using StructureMap-based extraction. The issue came up while trying to implement a StructureMap for patient registration

2022-01-12 10:50 UTC, aditya-07 requested changes

2022-01-12 10:50 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    transformSupportServices: StructureMapUtilities.ITransformerServices? = null
Since the function parameters keeps increasing, maybe we should think about wrapping up these in a structure like `StructureMapExtractionContext`.

2022-01-12 10:50 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      else StructureMapUtilities(simpleWorkerContext, transformSupportServices)
```suggestion
  StructureMapUtilities(simpleWorkerContext, transformSupportServices)
  .transform(simpleWorkerContext, questionnaireResponse, structureMap, this)
```
Since passing null transformSupportServices is fine in the constructor.

2022-01-14 06:56 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    transformSupportServices: StructureMapUtilities.ITransformerServices? = null
Change this also

2022-01-14 06:56 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      else StructureMapUtilities(simpleWorkerContext, transformSupportServices)
Agree! I have updated this

2022-01-29 11:04 UTC, Tarun-Bhardwaj commented
@ekigamba , is there an ETA by when the changes can be committed to make the PR ready for review?

2022-01-31 14:36 UTC, aditya-07 reviewed
A few comments, otherwise the PR looks good.

2022-01-31 14:36 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        context,
Since `context` is also just used for structure map based extraction, maybe it should also be encapsulated inside `StructureMapExtractionContext`.

2022-01-31 14:36 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val transformSupportServices: StructureMapUtilities.ITransformerServices? = null
I think reversing these would be better for creating StructureMapExtractionContext objects with lambda.

2022-02-02 05:40 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val outputs: MutableList<Base> = mutableListOf()
Since `outputs` is not being used anywhere, can it be avoided altogether?

2022-02-07 17:47 UTC, jingtang10 reviewed
Please address aditya's comments.

@ekigamba - thanks for this pr and the good work in creating the tests. i think the knowledge and experience to create structure map from a mapping is pretty lacking in general (i have no idea how to do this). can you please write a little bit of documentation somewhere and we can put it on the wiki?

thanks!

2022-02-07 17:47 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          structureMapExtractionContext.transformSupportServices
i went into hapi's code for a quick look, can't really figure out what they do in the case of this being null. just to be safe, shouldn't we call different contructors if this is null or not?

2022-02-17 08:34 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +          structureMapExtractionContext.transformSupportServices
I confirmed that that both constructors have the same logic with one having the setting for the TransformSupportServices
- https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/StructureMapUtilities.java#L253..L259
- https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/StructureMapUtilities.java#L261..L266

2022-02-17 08:35 UTC, ekigamba commented
@jingtang10 I will add some documentation on the conversion

2022-02-17 08:40 UTC, ekigamba commented on datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt
> +    val outputs: MutableList<Base> = mutableListOf()
Yes

2022-02-17 09:38 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +        context,
Agreed

2022-02-17 09:38 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val transformSupportServices: StructureMapUtilities.ITransformerServices? = null
Agreed

2022-02-28 08:41 UTC, aditya-07 approved these changes
Please check the comment. Apart from that LGTM

2022-02-28 08:41 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val context: Context,
nit: Can you please swap these? Context is usually the first param.

2022-02-28 11:52 UTC, Kigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val context: Context,
Cool, what about this https://github.com/google/android-fhir/pull/712#discussion_r795726506?

2022-02-28 11:55 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val context: Context,
Cool, what about this https://github.com/google/android-fhir/pull/712#discussion_r795726506?

2022-02-28 12:05 UTC, ekigamba commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
> +  val context: Context,
Definitely

2022-02-28 15:33 UTC, merged