Risk assessment display.
google/android-fhir pull request #721
Opened 2021-08-16 11:43 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #626 

**Description**
Show patient risk assessment display.
Low : Green
Moderate : Amber
High : Red

**Alternative(s) considered**
No.

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-31 05:48 UTC, santosh-pingle commented
There are changes in parent PR #691, therefore it is required to revise/update current PR changes.
I will be working on it.

2021-09-02 13:07 UTC, santosh-pingle commented
@googlebot I consent.

2021-09-02 13:09 UTC, santosh-pingle commented
We can review the changes.

2021-09-08 09:25 UTC, aditya-07 commented
@googlebot I consent

2021-09-09 12:57 UTC, aditya-07 requested changes

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/res/layout/patient_details_header.xml
>          android:background="#10156125"
Please replace it with unknown_risk_background.

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +        .reversed()
Can this be simplified by ```.filter { it.hasOccurrence() }.sortedByDescending { it.occurrenceDateTimeType.millis }``` ?

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    return getApplication<FhirApplication>().getString(R.string.unknown)
Use `getString(resId: Int)` class function  instead.

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
> +    return getApplication<FhirApplication>().getString(R.string.none)
Same `getString(resId: Int)`.

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +    }
Since we would want to show the status based on the latest RiskAssessment of the Patient, below code might be better suited.
```suggestion
      patients.forEach {patient->
      risks.filter { it?.subject?.reference == "Patient/${patient.resourceId}" }.firstOrNull()?.let {
        patient.risk = it?.prediction?.first()?.qualitativeRisk?.coding?.first()?.code
      }
    }
```

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +          .reversed()
Same as above, should be able to simplify with `.filter { it.hasOccurrence() }.sortedByDescending { it.occurrenceDateTimeType.millis }`

2021-09-09 12:57 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +    }
On the other hand, I feel `getRiskAssessments()` should return a `Map` instead of the `Collection`. Then, the above `risks.filter` can be replaced with a simple `Map.get`.

2021-09-13 07:31 UTC, santosh-pingle commented
Working on review comments.

2021-09-14 11:47 UTC, aditya-07 approved these changes
LGTM

2021-09-15 05:09 UTC, merged