Set values to date and time widget if answer already present
google/android-fhir pull request #728
Opened 2021-08-18 09:29 UTC by joiskash

Set values to date and time widget if answer already present.This pevents the date/ time widget to always open with the default date/time

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #649 

**Description**
If the questionnaire.item has an initial answer or the questionnaireResponse.item has an answer for the date time question, then on opening the widget, the highlighted date/ selected time is always set to today/now respectively. This is confusing to the user, since the expected behavior is that if an answer is already present, then that should be the date/time highlighted/selected in the widget.

**Alternative(s) considered**
Nope

**Type**
Bug fix

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-18 11:52 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt
> +    }
will this not work?

```suggestion
    val today =  (this.arguments?.get("date") as? LocalDate) ?: LocalDate.now()
```

2021-08-18 11:53 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt
> +    var now = LocalTime.now()
same as above

2021-08-18 13:04 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt
> +    }
yup it should work, and looks much neater too! thanks ill make the change

2021-08-19 08:59 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt
> +    }
Sorry, you probably won't need the brackets either.

2021-09-01 17:36 UTC, jingtang10 requested changes

2021-09-01 17:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt
> +    val today = this.arguments?.get("date") as? LocalDate ?: LocalDate.now()
`"date"` needs to be extracted as a string constant to be used consistently

2021-09-01 17:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          dateFragment.arguments = bundleOf("date" to selectedDate)
here you need to reference the string const instead of hardcoding the value `"date"`

2021-09-01 17:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            }
i think this can be improved. this 3 nested levels of seems a little redundant... what about

```
val selectedDate =
            questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.let {
              LocalDate.of(
                it.year,
                it.month + 1,
                it.day,
              )
            }
```

2021-09-01 17:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +                questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.second?.let {
same here

2021-09-01 17:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt
> +    val now = this.arguments?.get("time") as? LocalTime ?: LocalTime.now()
same thing with the string

2021-09-01 17:36 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          val selectedDate =
see below comment in the date time picker

2021-09-02 11:05 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/DatePickerDialogFragment.kt
> +    val today = this.arguments?.get("date") as? LocalDate ?: LocalDate.now()
done

2021-09-02 11:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          dateFragment.arguments = bundleOf("date" to selectedDate)
done

2021-09-02 11:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +            }
done

2021-09-02 11:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +                questionnaireItemViewItem.singleAnswerOrNull?.valueDateTimeType?.second?.let {
done

2021-09-02 11:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/TimePickerDialogFragment.kt
> +    val now = this.arguments?.get("time") as? LocalTime ?: LocalTime.now()
done

2021-09-02 11:06 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          val selectedDate =
done

2021-09-08 15:49 UTC, jingtang10 requested changes

2021-09-08 15:49 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +              )
add a private extension function:

```
private val DateType.localDate = ...
```

and do the same for the DateTime picker below

2021-09-08 15:49 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +              )
```
private val DateTimeType.localDate = ...
```

2021-09-08 15:49 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +              )
```
private val DateTimeType.localTime = ...
```

or maybe do 

```
   ... =
  get() {
  }
```

2021-09-10 08:41 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +              )
done

2021-09-10 08:41 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +              )
done

2021-09-28 11:05 UTC, jingtang10 approved these changes
just a few cosmetic comments.

feel free to merge once addressed. thanks!

2021-09-28 11:05 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          dateFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
this feels more kotlin-y:

```suggestion
          DatePickerFragment().apply {
            arguments = bundleOf(REQUEST_BUNDLE_KEY_DATE to selectedDate)
          }.show(context.supportFragmentManager, DatePickerFragment.TAG)
```

?

2021-09-28 11:05 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          dateFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
```suggestion
          DatePickerFragment().apply {
            arguments = bundleOf(REQUEST_BUNDLE_KEY_DATE to selectedDate)
          }.show(context.supportFragmentManager, DatePickerFragment.TAG)
```

2021-09-28 11:05 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          timeFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
```suggestion
          TimePickerFragment().apply {
            arguments = bundleOf(REQUEST_BUNDLE_KEY_TIME to selectedTime)
          }.show(context.supportFragmentManager, DatePickerFragment.TAG)
```

2021-09-28 11:31 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          timeFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
done

2021-09-28 11:32 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
> +          dateFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
done

2021-09-28 11:32 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
> +          dateFragment.show(context.supportFragmentManager, DatePickerFragment.TAG)
yup makes sense, done

2021-09-29 06:17 UTC, merged