Applying validation on bind to keep validation message relavant to current questionnaireItemViewItem
google/android-fhir pull request #730
Opened 2021-08-18 10:12 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #673 

**Description**
I am calling the `applyValidationResult` in the `QuestionnaireItemEditTextViewHolderFactory` onBind function. So that everytime we switch the page, the validation result relevant to the current questionnaireItemViewItem is displayed

**Alternative(s) considered**
Nope

**Type**
Bug fix

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-19 10:10 UTC, jingtang10 requested changes
Thanks @joiskash!

Thinking in the context of #374 and #577, I wonder if you can make `applyValidationResult` a method in the interface `QuestionnaireItemViewHolderDelegate`.

And then in `QuestionnaireItemViewHolder` you can make sure that the validation code is called upon bind for all widgets:

```
  open fun bind(questionnaireItemViewItem: QuestionnaireItemViewItem) {
    delegate.bind(questionnaireItemViewItem)
    delegate.validate(
      QuestionnaireResponseItemValidator.validate(
        questionnaireItemViewItem.questionnaireItem,
        questionnaireItemViewItem.questionnaireResponseItem,
        delegate.getContext()
      )
    )
  }
```

2021-08-24 04:10 UTC, joiskash commented
Sure ! Im sorry i completely missed this. Will get on it today.

2021-08-24 09:01 UTC, joiskash commented
@jingtang10 I have made the changes as requested by you. I also tried to pull in the setItemFocus change into the QuestionnaireItemViewHolderDelegate so that when the focus is lost, the validation is checked again.
This does not work for some widgets though, because the TextView on focus does not get triggered. For eg: In the Checkbox group

2021-09-02 11:07 UTC, joiskash commented
@aditya-07 Can you please review this?

2021-09-03 18:10 UTC, jingtang10 requested changes
thanks @joiskash!

2021-09-03 18:10 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          )
this code is repeated in every widget. can you create a new function in the delegate that returns this?

if you do that, perhaps the delegate needs to be an abstract class rather than an interface.

additionally, maybe `questionnaireItemViewItem` needs to moved to the delegate as well (and potentially assigned in the bind function?)

2021-09-03 18:17 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +  fun validate(questionnaireItemViewItem: QuestionnaireItemViewItem, context: Context)
```suggestion
  fun displayValidationResult(validationResult: ValidationResult)
```

2021-09-03 18:27 UTC, jingtang10 commented
you may also want to create a new function that is like a callback `onAnswerChanged` which calls the validation code and displays the result...

also i don't know if you can refactor the delegate... not sure if we can get rid of it

2021-09-07 14:28 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          )
done , I have changed it as per your feedback. Please have a look

2021-09-07 14:28 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +  fun validate(questionnaireItemViewItem: QuestionnaireItemViewItem, context: Context)
done

2021-09-07 14:47 UTC, joiskash commented
> 
> 
> you may also want to create a new function that is like a callback `onAnswerChanged` which calls the validation code and displays the result...
> 
> also i don't know if you can refactor the delegate... not sure if we can get rid of it

done.. I did refactor the delegate a bit. Please have a look.

2021-09-08 15:55 UTC, jingtang10 approved these changes
this is great. thanks @joiskash!

@kevinmost can you also take a look at this and see if the interface makes sense to you? thanks!

2021-09-08 15:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +          validationResult.validationMessages.joinToString {
can you creat an extension function to validation result to get the single string validation message?

2021-09-08 18:24 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +abstract class QuestionnaireItemViewHolderDelegate {
Is it possible to keep this as an interface?

The two functions with bodies look like they could be extension functions.

```kotlin
fun QuestionnaireItemViewHolderDelegate.onAnswerChanged(context: Context) { ... }
fun QuestionnaireItemViewHolderDelegate.getValidationResult(context: Context): ValidationResult { ... }
```

2021-09-08 18:24 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          validationResult.validationMessages.joinToString {
Same comment for all of these, but could this be:

```
validationResult.validationMessages.joinToString(separator = "\n")
```

2021-09-09 07:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +abstract class QuestionnaireItemViewHolderDelegate {
if we do this we wil also need `getQuestionnaireItemViewItem()` as a new API because we have a new member in this abstract class.

i'm happy with keeping this as interface. but what's the thinking behind this suggestion @kevinmost?

i also kinda want to merge the delegate with the view holder itself... but i've managed to do it myself. someone might have a clever way of simplifying this :)

2021-09-09 13:37 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +abstract class QuestionnaireItemViewHolderDelegate {
If we change this to an interface, wouldn't we just drop the word `abstract` from

```kotlin
abstract var questionnaireItemViewItem: QuestionnaireItemViewItem
```

? Am I missing something else we need to do?

I don't feel strongly about this; interfaces are just more flexible than abstract classes and it would be nice to keep things as flexible as possible.

2021-09-13 08:13 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          validationResult.validationMessages.joinToString {
done

2021-09-13 08:13 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +abstract class QuestionnaireItemViewHolderDelegate {
done, you are right, I did not have to do any changes. I just removed abstract class and put interface instead.

2021-09-13 08:13 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
> +          validationResult.validationMessages.joinToString {
done

2021-09-13 08:14 UTC, joiskash commented
@kevinmost Can you please take another look, I will merge once you are fine with the changes.

2021-09-28 10:34 UTC, jingtang10 approved these changes
👍🎉 great work! thanks!

2021-09-28 10:44 UTC, merged