Hidden extension to hide question item.
google/android-fhir pull request #742
Opened 2021-08-20 11:12 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #683 

**Description**
Add hidden extension implementation.

**Alternative(s) considered**
no

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-23 11:11 UTC, jingtang10 reviewed
Thanks @santosh-pingle!

Have you considered the alternative -- in the view model figure out if a questionnaire item is hidden and avoid adding it to the list for the recycler view?

2021-08-30 07:05 UTC, santosh-pingle commented
I will try to push review changes by end of today which will have addressed review comments and updated unit tests.

2021-09-01 08:20 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>            }
Can be simplified to: 
```suggestion
            if (enabled && !questionnaireItem.isHidden) {
              listOf(
                QuestionnaireItemViewItem(questionnaireItem, questionnaireResponseItem) {
                  questionnaireResponseItemChangedCallback(questionnaireItem.linkId)
                }
              ) +
                getQuestionnaireState(
                    questionnaireItemList = questionnaireItem.item,
                    questionnaireResponseItemList =
                      if (questionnaireResponseItem.answer.isEmpty()) {
                        questionnaireResponseItem.item
                      } else {
                        questionnaireResponseItem.answer.first().item
                      },
                    // we're now dealing with nested items, so pagination is no longer a concern
                    pagination = null,
                  )
                  .items
            }
          } else {
            emptyList()
          }
```

2021-09-01 08:20 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertResourceEquals(viewModel.getQuestionnaireResponse(), questionnaireResponse)
Are these assertions necessary for the test case?

2021-09-01 09:54 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>            }
Actually, below edge case is also required.
If hidden extension is true and question item is enabled, then initial answers (if present) will be part of questionnaire response.
(Line no. 201 change is required if it is enabled and hidden.)

2021-09-01 10:04 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertResourceEquals(viewModel.getQuestionnaireResponse(), questionnaireResponse)
(Line. no 877 assertion) Actually, it is required, to make sure, if question item is hidden and enabled and it has initial value, then those answers should be part of questionnaire response.

(Line no. 871 assertion) it is good to have to just check questionnaireItemView has correct indexed responseItem if previous questionnaireItemView is hidden.

2021-09-01 11:09 UTC, jingtang10 requested changes

2021-09-01 11:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +    val value = this.extension.firstOrNull { it.url == EXTENSION_HIDDEN_URL }?.value as BooleanType?
this cast could cause a crash.

do this instead:

```
    val extension = this.extension.singleOrNull { it.url == EXTENSION_HIDDEN_URL } ?: return false
    val value = extension.value
    if (value is BooleanType){
      return value.booleanValue()
    }
    return false
```

2021-09-01 11:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              emptyList()
early return.

2021-09-08 13:02 UTC, jingtang10 approved these changes

2021-09-08 13:06 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +    assertResourceEquals(viewModel.getQuestionnaireResponse(), questionnaireResponse)
this is fine - but to simplify a little more you could just check the link id rather than comparing the whole response item

2021-09-08 13:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
> +/** Hidden extension value as boolean. */
```suggestion
/** Whether the QuestionnaireItem should be hidden according to the hidden extension or lack thereof. */
```

2021-09-09 04:25 UTC, merged