Prototype: Debug OOM
google/android-fhir pull request #745
Opened 2021-08-20 15:57 UTC by stevenckngaa

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-20 16:29 UTC, jingtang10 requested changes
thanks for the fix @stevenckngaa

2021-08-20 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
> +      GlobalScope.launch(Dispatchers.Main) {
```suggestion
      viewLifecycleOwner.lifecycleScope.launch {
```

?

2021-08-20 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
remove line

2021-08-20 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
remove empty line

2021-08-20 16:29 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val BUNDLE_KEY_QUESTIONNAIRE_URI = "questionnaire_URI"
```suggestion
    const val BUNDLE_KEY_QUESTIONNAIRE_URI = "questionnaire-uri"
```

2021-08-20 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +            "HL7 example Large questionnaire",
@joiskash is it ok if we put this questionnaire you authored in the gallery app? if so can you suggest name and description? thanks!

2021-08-20 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +  private val backgroundContext = CoroutineScope(Dispatchers.IO).coroutineContext
viewModelScope?

2021-08-20 16:29 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +    questionnaireJson = questionnaireJson?.let { it }
does `.let{ it }` do anything? is it just no-op?

2021-08-21 17:10 UTC, joiskash commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +            "HL7 example Large questionnaire",
Sure you can. We can call it Malaria Net Card Distribution - Door to Door survey

2021-11-08 12:15 UTC, Tarun-Bhardwaj commented
@stevenckngaa , just curious to know if there's any progress on this PR?

2021-11-09 18:33 UTC, stevenckngaa commented
@jingtang10 @yigit could you please take a look?

2021-11-09 18:33 UTC, stevenckngaa commented
@jingtang10, @yigit could you please take a look?

2021-11-10 08:19 UTC, yigit requested changes
feel free to submit after the small nits are fixed.

we can implement accepting answers as URI as nother PR.

2021-11-10 08:19 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_QUESTIONNAIRE_RESPONSE = "questionnaire-response"
should this also have a URI for consistency ?

2021-11-10 08:19 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        FhirContext.forR4().newJsonParser().parseResource(questionnaireJson) as Questionnaire
we probably want to throw in another else case.
like update this else to check for EXTRA_JSON_ENCODED_QUESTIONNAIRE and another else branch to have `error("one of these parameters must be supplied")`

2021-11-10 08:19 UTC, yigit commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_JSON_ENCODED_QUESTIONNAIRE = "questionnaire"
need to document which one wins if both are provided.

2021-11-10 11:27 UTC, stevenckngaa commented
Filed https://github.com/google/android-fhir/issues/916 to track questionnaire response URI.

2021-11-10 11:28 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_JSON_ENCODED_QUESTIONNAIRE = "questionnaire"
Done. I log a warning in case both EXTRA_JSON_ENCODED_QUESTIONNAIRE & EXTRA_QUESTIONNAIRE_URI are provided.

2021-11-10 11:28 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_QUESTIONNAIRE_RESPONSE = "questionnaire-response"
Sure. Tracked in https://github.com/google/android-fhir/issues/916

2021-11-10 11:28 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +        FhirContext.forR4().newJsonParser().parseResource(questionnaireJson) as Questionnaire
Done. Also added a test case.

2021-11-10 15:00 UTC, stevenckngaa commented
@jingtang10 @yigit could you please take another look? I can't submit this change because both of you have requested changes.

2021-11-10 16:16 UTC, yigit approved these changes

2021-11-11 16:31 UTC, jingtang10 requested changes
As discussed, please load the small questionnaires in the gallery app without using a file.

2021-11-11 16:31 UTC, jingtang10 commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +            questionnaireResponseJson?.let { cachedResponse } ?: readFileFromAssets(path)
i find this line kinda hard to read. can we just do `if (questionnaireResponseJson == null) { ... }`?

2021-11-12 17:58 UTC, stevenckngaa commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +            "A very large HL7 questionnaire for Malaria Net card distribution",
Done

2021-11-12 17:58 UTC, stevenckngaa commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
> +    const val EXTRA_QUESTIONNAIRE_URI = "questionnaire-uri"
Done

2021-11-12 17:59 UTC, stevenckngaa commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
> +            "A very large HL7 questionnaire for Malaria Net card distribution",
Done.

2021-11-12 17:59 UTC, stevenckngaa commented on datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
> +            questionnaireResponseJson?.let { cachedResponse } ?: readFileFromAssets(path)
Done.

2021-11-12 18:02 UTC, stevenckngaa commented
@jingtang10 I have changed the data capture gallery app to only load large questionnaires via URI. PTAL.

2021-11-17 11:31 UTC, jingtang10 approved these changes
👍👍👍🎉🎉🎉

2021-11-17 11:31 UTC, merged