support max decimal extension
google/android-fhir pull request #748
Opened 2021-08-21 13:12 UTC by epicadk

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #710

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?
We could add this to the Primitive max length validator. 

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-30 12:15 UTC, epicadk commented
This is my first pr on the data capture module. Could someone review it and tell me if something is missing?

2021-08-31 14:17 UTC, Tarun-Bhardwaj commented
> This is my first pr on the data capture module. Could someone review it and tell me if something is missing?

@aditya-07 , could you please take a look at it?

2021-11-24 12:24 UTC, jingtang10 requested changes

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  fun setupTest() {
conventionally we call this `setUp`

```suggestion
  fun setUp() {
```

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +      .isEqualTo("The maximum number of decimal places that are permitted in the answer is:2")
hey i liked the space after the `:` :) can we add it back? thanks

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/main/res/values/strings.xml
> +    >The maximum number of decimal places that are permitted in the answer is:<xliff:g
add a space after `:`

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidator.kt
> +      val maxDecimalValue = (extension.value as? IntegerType)?.value
```suggestion
      val maxDecimalPlaces = (extension.value as? IntegerType)?.value
```

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  fun setupTest() {
hm i realised this is the case for the other validator tests.... if you don't mind renaming all of them to `setUp` it'd be good. thanks!

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  fun validAnswer_shouldReturnValidResult() {
```suggestion
  fun validate_validAnswer_shouldReturnValidResult() {
```

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  @Test
add blank line

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  fun noExtension_shouldReturnValidResult() {
```suggestion
  fun validate_noExtension_shouldReturnValidResult() {
```

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  fun invalidAnswer_shouldReturnInvalidResult() {
```suggestion
  fun validate_tooManyDecimalPlaces_shouldReturnInvalidResult() {
```

2021-11-24 12:24 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidatorTest.kt
> +  fun noExtension_shouldReturnValidResult() {
i would also move this test case up to the top (because it's kinda like a zero case)

2021-12-06 09:53 UTC, jingtang10 approved these changes

2021-12-06 09:53 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidator.kt
> +
this wasn't done?

2021-12-06 14:18 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/DecimalTypeMaxDecimalValidator.kt
> +
I rewrote the object by extending `ValueConstraintExtensionValidator` this seems to be before that

2021-12-07 15:42 UTC, merged