Add response item initial value to questionnaire response only if enablewhen is true.
google/android-fhir pull request #756
Opened 2021-08-26 12:23 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #755 

**Description**
Add response item initial value to questionnaire response only if enablewhen is true.
Remove response item initial value from questionnaire response if enablewhen is false.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-08-31 08:12 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            questionnaireResponseItem?.removeAnswers()
`questionnaireResponseItem` is not nullable. So we can get rid of the safe `?.` call.

2021-08-31 08:44 UTC, aditya-07 requested changes

2021-08-31 08:44 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            questionnaireResponseItem?.removeAnswers()
`questionnaireResponseItem` is not nullable. So we can get rid of the safe `?.` call.

2021-08-31 08:44 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +      }
Instead of generating the `questionnaireResponse` here, can you add the static `questionnaireResponseJson` here so that exact expected value is know before hand. Later for `assertion`, you can either serialize `viewModel.getQuestionnaireResponse()` to a json to perform string comparison or convert `questionnaireResponseJson` to `questionnaireResponse` object.

2021-08-31 08:44 UTC, aditya-07 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +      }
Same as above.

2021-08-31 08:44 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
Is this required here?It should have the value from init code 
```
questionnaire.item.forEach {
        questionnaireResponse.addItem(it.createQuestionnaireResponseItem())
      }
```

2021-08-31 11:05 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
It's issue.
If question item is not enabled then it can not have answer, though it has initial value.
If question item is enabled then it can have answer, if it has initial value then just add those as initial answer.

We need it because of 
if not enabled then those answers are removed ( questionnaireResponseItem.removeAnswers()), 
and if enabled then just add those initial value as initial answers.

2021-09-01 07:56 UTC, aditya-07 approved these changes
LGTM.

2021-09-01 10:56 UTC, jingtang10 requested changes
@santosh-pingle i'm not sure this fix is correct - can you please address the comments? thanks!

2021-09-01 10:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  }
```suggestion
  answer.removeAll { true }
  item.forEach { it.removeAnswers() }
```

2021-09-01 10:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +internal fun QuestionnaireResponse.QuestionnaireResponseItemComponent.removeAnswers() {
this should be called `removeAllAnswers` or `removeAllNestedAnswers`.

also add kdoc.

2021-09-01 10:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>            if (enabled) {
Early return to make the code more readable:

```suggestion
          if (!enabled) {
            questionnaireResponseItem.removeAnswers()
            emptyList()
          }
```

2021-09-01 10:56 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
wait - i'm not sure i understand why this is done this way.

the problem raised in the issue is that answers to disabled questions are being extracted.

this function `getQuestionnaireState` is called to render the questionnaire. according to the logic here, if the user answers a question, you will override their answer with the intial value? this seems incorrect to me.

it seems to me the fix should actually be in the extraction code. rather than in the view model.

2021-09-01 12:39 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>            if (enabled) {
Please check, this is what you meant.

2021-09-01 12:44 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
Ok.
(this was a discussion which we had offline.)

Let’s assume that, question item is not enabled (enablewhen clause is false) and it has answers (either initial value or user input answer.)
Now, at the time of data extraction, there is no way that QuestionnaireResponse will tell whether a given questionnaire item is enabled or not.
Therefore, if the questionnaire item is not enabled then the answer should not be present in the questionnaire response.

Whether answers get overridden?

- If the question item is not enabled, then it will not have answers in questionnaireResponseItem, answers are removed.
- Now, let's assume the question item is enabled, so just update the questionnaire item response with initial values. 
- If it has already answered it will not override the answer, it checks hasenablewhen and does not have an answer.

2021-09-01 13:57 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
you're correct in saying that from the `QuestionnaireResponse` alone you can't tell if a question is enabled, but you can tell that from inspecting the `Questionnaire` itself no? so one solution is to do this in the resource mapper.

even if you do decide to do this in view model (which is an alternative solution), it should not be in this function, i think it probably should be when the answer changes (so that the enable when evaluation would change) so it probably should be in the `questionnaireResponseItemChangedCallback`?

overriding answer: i still don't think this is right. the user may decide to remove an initial answer. in your case you would then immediately add the intial answer back.

2021-09-01 17:59 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
We can handle it in ```questionnaireResponseItemChangedCallback```, but still we need to update initial values in response items once it enabled, as answers were already removed when question item was disabled (as per fix).
Consider below case ->
There are question items which are enabled but not displayed to the user. Initial values are only answers and users can not input it. If these questionnaire items get disabled then their answers also get removed (as per fix). Now, if they get enabled again then we need to add those initial values back to response items as those are the only answers.

2021-09-02 07:19 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
Can you try to not remove the intial answer when disabling the question?

2021-09-03 05:39 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Questionnaire.20item.20response.20and.20disabled.20questionnaire.20item/near/251752110

2021-09-03 05:47 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
As you suggested in developers sdk call and reference to above link, we will retain answers of disabled questions in questionnaire response, and from ``` getQuestionnaireResponse ``` we will return separate copy of questionnaire response which will have answers of enabled questions only.

2021-09-03 05:47 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
Working on change.

2021-09-06 13:44 UTC, santosh-pingle commented
Can we please review it.

2021-09-08 12:58 UTC, jingtang10 requested changes

2021-09-08 12:58 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>  }
when do you actually remove the item from the list? i'm struggling to find the line that actually does it. all this does is that if something it's not enabled you early return... in that case the item is still in the list though?

what about turn this around and use the `filter` function and generate an enabled list like below:

```suggestion
  private fun getEnableResponseItems(
    questionnaireItemList: List<Questionnaire.QuestionnaireItemComponent>,
    questionnaireResponseItemList: List<QuestionnaireResponse.QuestionnaireResponseItemComponent>,
  ): List<QuestionnaireResponse.QuestionnaireResponseItemComponent> {
    return questionnaireItemList
      .asSequence()
      .zip(questionnaireResponseItemList.asSequence())
      .filter { (questionnaireItem, questionnaireResponseItem) ->
        EnablementEvaluator.evaluate(questionnaireItem) { linkId ->
          val questionnaireItemComponent = linkIdToQuestionnaireItemMap[linkId]
          val questionnaireResponseItemComponent = linkIdToQuestionnaireResponseItemMap[linkId]
          if (questionnaireItemComponent == null || questionnaireResponseItemComponent == null) {
            return@evaluate QuestionnaireItemWithResponse(null, null)
          }
          QuestionnaireItemWithResponse(
            questionnaireItem = questionnaireItemComponent,
            questionnaireResponseItem = questionnaireResponseItemComponent
          )
        }
      }
      .map { (questionnaireItem, questionnaireResponseItem) ->
        // Nested group items
        questionnaireResponseItem.item =
          getEnableResponseItems(questionnaireItem.item, questionnaireResponseItem.item)

        // Nested question items
        questionnaireResponseItem.answer.forEach {
          it.item = getEnableResponseItems(questionnaireItem.item, it.item)
        }

        questionnaireResponseItem
      }
      .toList()
  }
```

2021-09-08 12:58 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun removeAnswers_questionnaireResponseItemHasAnswers_removeAnswers() {
up to you but i don't think you need to test this private function

2021-09-09 05:01 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            }
Please refer further discussion in below comments.

2021-09-09 05:07 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>  }
Answers for disabled question was getting removed with below change.
return@forEach questionnaireResponseItem.removeAllNestedAnswers()

But as you suggested not to include questionnaireResponse item to questionnaire response for disabled question, this change is updated.

2021-09-10 17:09 UTC, jingtang10 approved these changes
a few small comments.. once addressed please feel free to merge!

nice work thanks @santosh-pingle!

2021-09-10 17:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +  private fun getEnableResponseItems(
```suggestion
  private fun getEnabledResponseItems(
```

2021-09-10 17:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +          val questionnaireResponseItemComponent = linkIdToQuestionnaireResponseItemMap[linkId]
```suggestion
          val questionnaireItem = linkIdToQuestionnaireItemMap[linkId]
          val questionnaireResponseItem = linkIdToQuestionnaireResponseItemMap[linkId]
```

2021-09-10 17:09 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +            questionnaireResponseItem = questionnaireResponseItemComponent
```suggestion
            questionnaireItem,
            questionnaireResponseItem
```

2021-09-13 07:24 UTC, merged