dark ui issue fixed in add patient
google/android-fhir pull request #762
Opened 2021-08-28 11:54 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #684 

**Description**
fixes add patient UI in dark mode.

**Alternative(s) considered**
Not sure but the library should support dark UI in general. 

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-25 15:59 UTC, jingtang10 requested changes

2021-11-25 15:59 UTC, jingtang10 commented on reference/src/main/res/values/styles.xml
> +        >@style/Theme.MaterialComponents.Light.DarkActionBar</item>
This is not the right fix. The problem, as you can see from the screenshot, is that dark theme is not correctly respected by the reference app (therefore the light background) but respected by the data capture library generating the widget UI (therefore the light color widgets).

What should change is line 20 in this file where you should use a DayNight theme.

2021-12-07 14:13 UTC, jingtang10 approved these changes

2021-12-07 14:13 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +      binding.statusValue.setTextColor(Color.BLACK)
this seems unnecessary?

2021-12-07 14:26 UTC, maanuanubhav999 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +      binding.statusValue.setTextColor(Color.BLACK)
Since the status is currently set to unknown, we have a white background, maybe in the future, we might have to set this to the opposite of what the background color is.

2021-12-07 23:12 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +      binding.statusValue.setTextColor(Color.BLACK)
oh ok got it. so i guess the patient card color concept needs to be adaptable in light/dark themes. we can do that in a follow up

2021-12-08 00:39 UTC, merged

2021-12-09 09:11 UTC, maanuanubhav999 commented on reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
> +      binding.statusValue.setTextColor(Color.BLACK)
sure, should I make a new Issue @jingtang10