Reference app crash when country is null.
google/android-fhir pull request #776
Opened 2021-09-08 06:20 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #774 

**Description**
Country element value was null.

**Alternative(s) considered**
no

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-09-08 08:31 UTC, aditya-07 requested changes

2021-09-08 08:31 UTC, aditya-07 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +  val country = if (hasAddress() && address[0].hasCountry()) address[0].country else ""
Other fields can be null, so should check them as well. 
We could do this while constructing PatientListViewModel.PatientItem
```
   return PatientListViewModel.PatientItem(
    id = position.toString(),
    resourceId = patientId,
    name = name,
    gender = gender ?: "",
    dob = dob ?: "",
    phone = phone ?: "",
    city = city ?: "",
    country = country ?: "",
    isActive = isActive,
    html = html
  )
```

Don't forget to modify `PatientItemViewHolder` to handle null/empty values.

2021-09-08 13:31 UTC, jingtang10 approved these changes

2021-09-08 13:31 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
>      return patientItem.resourceId.substring(patientItem.resourceId.length - 3)
```suggestion
    return patientItem.resourceId.takeLast(3)
```

2021-09-08 13:31 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +    dob = dob ?: "",
i'm not sure this should be a string... date format varies hugely in different locales and system settings probably should be respected...

please create a separate ticket.

2021-09-09 04:43 UTC, santosh-pingle commented on reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
> +    dob = dob ?: "",
Actually, this data class is for item view only to show the patient attributes on the screen, thats why we are seeing all fields as string also  same was updated in doc in existing code.

2021-09-09 06:58 UTC, aditya-07 approved these changes
LGTM. Thanks Santosh!

2021-09-09 06:58 UTC, merged