Ma/add not answered or clear
google/android-fhir pull request #781
Opened 2021-09-11 08:24 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #530

**Description**
1. Boolean questions should be rendered as 3 options. The 3rd one being "not answered" or something similar
2. Choice questions should have a clear answer option.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-09-26 19:38 UTC, maanuanubhav999 commented
Do we have to add "Not answered" even in the check box type?

 I have not yet added it. Since users can unselect the check box and remove answers unlike radio groups or dropdown.
 But we may add it if we want uniformity in all the choice types.

2021-09-30 15:46 UTC, jingtang10 requested changes
Thanks @maanuanubhav999! 👍 A couple of high-level comments:

1. Can you please remove `QuestionnaireItemCheckBoxViewHolderFactory` and all references to it?
2. Can you reuse `QuestionnaireItemRadioGroupviewHolderFactory` instead of creating a new widget type (`QuestionnaireItemBooleanTypePickerViewHolderFactory`)? The new widget factory you created does pretty much what the radio group does. I think the only difference is that if the question is boolean type it needs to generate two answer options true/false, and you have to translate them to the correct answers when the user answers the questions.

2021-09-30 15:49 UTC, jingtang10 commented
> Do we have to add "Not answered" even in the check box type?
> 
> I have not yet added it. Since users can unselect the check box and remove answers unlike radio groups or dropdown. But we may add it if we want uniformity in all the choice types.

If you're talking about checkox group - you're right we don't need not answered option, because the user can just untick everything. If you're talking about a single checkbox - I think we should just get rid of it since there won't be any use for it (I commented in my review already).

2021-10-12 11:27 UTC, maanuanubhav999 commented
Hey, @jingtang10 I will try to complete it in 2-3 days.

2021-10-12 12:25 UTC, jingtang10 commented
@shelaghm and I are discussing some alternative solutions - will update and hopefully will provide some mocks to guide implementation

2021-10-31 12:25 UTC, maanuanubhav999 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +  //  }
No, I will remove it

2021-11-06 12:14 UTC, jingtang10 requested changes

2021-11-06 13:49 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
> +          QuestionnaireItemBooleanTypePickerViewHolderFactory
sure

2021-11-06 14:04 UTC, maanuanubhav999 commented on datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
> +<?xml version="1.0" encoding="utf-8" ?>
we still have `QuestionnaireItemCheckBoxGroupViewHolderFactory.kt` which has a dependency on `questionnaire_item_check_box_view.xml` so keeping it.

2021-11-06 14:04 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +      private lateinit var boolTypeNo: RadioButton
sure, thanks for your patience @jingtang10

2021-11-10 19:25 UTC, jingtang10 requested changes
Thanks very much for perseverance - this should be the last round of comments.

Following the same design pattern of the yes/no radio button, I don't believe we want to add another radio button for the radio button group. I would suggest revert the changes for the radio button group and drop down and create two separate issues (and raise 2 separate PRs if you wish) for them.

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +          questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
remove this line

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +          questionnaireItemViewItem.questionnaireResponseItemChangedCallback()
remove this line (it's being called in the next line in `onAnswerChanged`)

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun bind_shouldSetHeaderText() {
```suggestion
  fun bind_shouldSetQuestionText() {
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
> +            android:id="@+id/boolean_type_yes"
make the names more descriptive please

```suggestion
            android:id="@+id/yes_radio_button"
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
> +            android:id="@+id/boolean_type_no"
```suggestion
            android:id="@+id/no_radio_button"
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
> +        android:id="@+id/bool_header"
```suggestion
        android:id="@+id/question_text_view"
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun bind_shouldCreateRadioButtonsForBooleanType() {
not sure you need a test just to check that the radio buttons are created. i think it's obvious from the xml layout file.

but you do need to verify that if the answer is missing or true or false, the widget is initialized with the correct radio button selected.

so it's wrong to remove the existing test cases, please add them back and change them from using checkboxes to radio buttons.

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
>      assertThat(answer[0].valueBooleanType.value).isTrue()
```suggestion
    assertThat(answer.single().valueBooleanType.value).isTrue()
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
>      assertThat(answer[0].valueBooleanType.value).isFalse()
```suggestion
    assertThat(answer.single().valueBooleanType.value).isFalse()
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun doubleClickYes_shouldClearAnswer() {
```suggestion
  fun yesSelected_clickYes_shouldClearAnswer() {
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun doubleClickNo_shouldClearAnswer() {
```suggestion
  fun noSelected_clickNo_shouldClearAnswer() {
```

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun doubleClickYes_shouldClearAnswer() {
i would change this test case so that the initial answer is yes, so you don't have to click twice

2021-11-10 19:25 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun doubleClickNo_shouldClearAnswer() {
i would change this test case so that the initial answer is no, so you don't have to click twice.

2021-11-11 15:13 UTC, anita-vadverao approved these changes

2021-11-16 14:47 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        boolTypeHeader.text = questionnaireItem.localizedText
Hey, didn't get this, why would we need to shift this? @jingtang10

2021-11-16 18:39 UTC, maanuanubhav999 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun bind_shouldCreateRadioButtonsForBooleanType() {
sure, makes sense.

2021-11-17 11:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        autoCompleteTextView.error =
this change needs to be reverted

2021-11-17 11:42 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> -      private lateinit var textInputLayout: TextInputLayout
why remove this

2021-11-17 11:52 UTC, jingtang10 requested changes
did you push the changes addressing the comments from the previous review? i can't seem to see any.

thanks!

2021-11-17 11:52 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> -  @Test
why are you removing these test cases?

2021-11-17 11:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> -      private lateinit var textInputLayout: TextInputLayout
I don't think you should remove this

2021-11-17 11:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        autoCompleteTextView.error =
i think this might be a sync issue -> you should not change this.

2021-11-17 11:52 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        boolTypeHeader.text = questionnaireItem.localizedText
can you move this line to the top:

`val (questionnaireItem, questionnaireResponseItem) = questionnaireItemViewItem`

so that the if else block can use `questionnaireItem` rather than `questionnaireItemViewItem.questionnaireItem`

also, move `boolTypeHeader` setup before the `answer` setup because that's consistent with the order of the widgets.

2021-11-19 14:03 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactory.kt
> +        boolTypeHeader.text = questionnaireItem.localizedText
sure, also removed `answer` since it was not needed anywhere.

2021-11-19 14:08 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        autoCompleteTextView.error =
yeah sorry for this, it was indeed a sync issue.

2021-11-22 14:08 UTC, jingtang10 requested changes

2021-11-22 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun noAnswer_shouldSetAnswerEmpty() {
For this case `noAnswer` I think you also should add tests to check that the radio buttons are not checked. The same for the later test cases, basically you should have 1 test case for checking that the answer is correctly set in the questionnaire response item, and another test case for checking that the UI radio buttons are correctly ticked.

2021-11-22 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun noAnswer_shouldSetAnswerEmpty() {
```
  @Test
  @UiThreadTest
  fun noAnswer_shouldNotCheckYesOrNoRadioButton() {
    viewHolder.bind(
      QuestionnaireItemViewItem(
        Questionnaire.QuestionnaireItemComponent().apply { text = "Question?" },
        QuestionnaireResponse.QuestionnaireResponseItemComponent()
      ) {}
    )

    assertThat(viewHolder.itemView.findViewById<RadioButton>(R.id.yes_radio_button).isChecked)
      .isFalse()
    assertThat(viewHolder.itemView.findViewById<RadioButton>(R.id.no_radio_button).isChecked)
      .isFalse()
  }
```

2021-11-22 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun answerTrue_shouldSetBooleanTypeTrue() {
For answerTrue, have the following two test cases:

```
answerTrue_shouldSetAnswerTrue
answerTrue_shouldCheckYesRadioButton
```

2021-11-22 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun answerFalse_shouldSetBooleanTypeFalse() {
Have the two cases:

```
answerFalse_shouldSetAnswerFalse
answerFalse_shouldCheckNoRadioButton
```

2021-11-22 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun yesSelected_clickYes_shouldClearAnswer() {
add another test case just to check that the radio buttons are selected correctly (both should not be selected because the answer should be cleared)

`yesSelected_clickYes_shouldClearRadioButtons`

2021-11-22 14:08 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +  fun noSelected_clickNo_shouldClearAnswer() {
add another test case just to check that the radio buttons are selected correctly (both should not be selected because the answer should be cleared)

`noSelected_clickNo_shouldClearRadioButtons`

2021-11-24 15:50 UTC, jingtang10 approved these changes
Great work! Thanks @maanuanubhav999! 👍 🎉

2021-11-24 15:50 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(answer.isEmpty())
nit: this is up to you, but i'm happy to inline the `answer` variable - kinda feel like not that useful to declare it:

```
    assertThat(questionnaireItemViewItem.questionnaireResponseItem.answer.isEmpty())
```

is enough.

same with the test cases below.

2021-11-24 17:00 UTC, maanuanubhav999 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemBooleanTypePickerViewHolderFactoryInstrumentedTest.kt
> +    assertThat(answer.isEmpty())
sure, thanks a lot @jingtang10

2021-11-24 18:12 UTC, merged