[WIP] Introduce a SQLCipher encryption to FHIR engine database
google/android-fhir pull request #787
Opened 2021-09-15 22:27 UTC by stevenckngaa

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #392

**Description**
Here are the changes:
1. Introduce new dependencies: a) SQLCipher for database encryption, b) Android security library for `EncryptedSharedPreferences`
2. Generates a 16 bytes database encryption passphrase for FHIR engine database
3. Store the generated database passphrase in `EncryptedSharedPreferences`

TODO:
1. Check with Jing to see if we can increase the minSdk to 23. If not, we need to provide an alternative way to store the database encryption passphrase in a file encrypted by a private key from Android keystore.
2. Write unit tests

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-09-20 23:11 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/FhirServices.kt
> +    internal fun enableEncryption() = apply { enableEncryption = true }
Should we check if Android API >= M here?

2021-11-04 13:29 UTC, jingtang10 requested changes

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  @JvmField @Parameterized.Parameter(0) var encrypted: Boolean = false
add a little bit of explanation on what this does to the test please thanks!

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirServices.kt
> +    internal fun enableEncryption() = apply {
is there any value in using the `apply` function here?

same with the function above `inMemory()`

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +   * configuration or vice versa.
can you add what would happen in those cases?

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/FhirEngineProvider.kt
> +          }
the more i look at this block the more i feel FhirServices should just be inlined in this class.. not sure how you feel about that? no need to do that in this PR but i think this can be a follow-up.

@yigit

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/DatabaseEncryptionException.kt
> +object KeyStoreExceptionErrorCode {
is there some code we can point to in our open source repo that is the origin of these errors? that we might need to keep these things up to date :/

2021-11-04 13:29 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt
> +    FhirEngineProvider.init(FhirEngineConfiguration(enableEncryption = true, RECREATE_AT_OPEN))
i don't know if we should be more lenient here. if this code is called accidentally by developers with FhirEngineProvider still alive, there will be exceptions. is this what we want to happen?

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/SQLCipherSupportHelper.kt
> +          standardHelper.getWritableDatabase(passphraseFetcher())
is it possible at all for this to throw for some other reason? or is it guaranteed to succeed?

2021-11-04 13:29 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      databaseConfig.inMemory -> Room.inMemoryDatabaseBuilder(context, ResourceDatabase::class.java)
can we make it not possible to set the db config with `inMemory` and `enableEncryption` both true?

2021-11-04 18:09 UTC, jmarkoff commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +suspend fun <R> RoomDatabase.withWrappedTransaction(
You can test with an emulator as well, but I'm not sure of a good way to test the keystore without an emulator or real device unfortunately. You would need to build out some stubs. For Jetpack Security, we just require that you test on a device (real or virtual).

2021-11-04 18:11 UTC, jmarkoff commented on engine/src/main/java/com/google/android/fhir/db/DatabaseEncryptionException.kt
> +object KeyStoreExceptionErrorCode {
They are only defined in the platform code sadly. Generally they shouldn't change to often though.

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/security/keymaster/KeymasterDefs.java

2021-11-04 18:11 UTC, jmarkoff commented on engine/src/main/java/com/google/android/fhir/db/DatabaseEncryptionException.kt
> +class DatabaseEncryptionException(
It's something that I had to write, the error codes are defined in the platform code only.
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/security/keymaster/KeymasterDefs.java

The code that I shared with you wraps all keystore actions with this type of exception wrapper.

2021-11-04 18:22 UTC, stevenckngaa commented on reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt
> +    FhirEngineProvider.init(FhirEngineConfiguration(enableEncryption = true, RECREATE_AT_OPEN))
I don't think app developers should call the initialization anywhere apart from `Application#onCreate`. [`WorkManager#initialize`](https://developer.android.com/reference/kotlin/androidx/work/WorkManager#initialize) throw an exception if it is called more than once in the same process. I think we may also want to throw an exception if the app developer access database at direct boot, which is out of this PR scope.

@yigit FYI

2021-11-05 00:09 UTC, yigit requested changes

2021-11-05 00:09 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +      databaseConfig.inMemory -> Room.inMemoryDatabaseBuilder(context, ResourceDatabase::class.java)
do we care about that? I mean, it is not great that it wont work but also it has no negative impact on the actual use case (testing)

2021-11-05 00:09 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +suspend fun <R> RoomDatabase.withWrappedTransaction(
this is going to be easy to get wrong. as in you are not really convering all of the access to room database.

Any reason why we cannot do this when reading the key in open helper callback instead of here? I mean, do the retry in the open helper callback (and literally block by blocking the thread so that the rest of the database access do not get complicated?)

2021-11-05 00:09 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
> +  return withContext(CoroutineScope(Dispatchers.IO).coroutineContext) {
unrelated nit, you can just do withContext(Dispatchers.IO). but as mentioned above, we should try to avoid leaking this complexity to here and instead handle it when we need to read the key from keystore.

2021-11-05 00:09 UTC, yigit commented on engine/src/main/java/com/google/android/fhir/db/impl/SQLCipherSupportHelper.kt
> +  private val passphraseFetcher: () -> ByteArray,
so this code could literally retry itself.
I know it will need to block a thread (not as great as doing a delay in coroutines) but the advantage is that you isolate it to the lower layer database and guaranteed that all access in room handles it.

2021-11-05 00:09 UTC, yigit commented on reference/src/main/java/com/google/android/fhir/reference/FhirApplication.kt
> +    FhirEngineProvider.init(FhirEngineConfiguration(enableEncryption = true, RECREATE_AT_OPEN))
yea i think following up what WM does is the right way to go for consistency

2021-11-05 12:12 UTC, stevenckngaa commented on engine/src/main/java/com/google/android/fhir/db/impl/SQLCipherSupportHelper.kt
> +  private val passphraseFetcher: () -> ByteArray,
Right, the only reason that I didn't do it here was the thread blocking problem you mentioned. Sounds like we are okay with it. I am happy to move it back to this class.

2021-11-05 17:15 UTC, stevenckngaa commented on engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
> +  @JvmField @Parameterized.Parameter(0) var encrypted: Boolean = false
Whether it is var or val, the compiler forces me to add a default value. I prefer `var` because `val`with default value false gives an impression that this value is always false.

I can't use `lateinit` because this is a JvmField. Also checked other implementations in our internal codebase. Everyone is using var with a default value.

2021-11-25 14:08 UTC, jingtang10 approved these changes
I ❤️ this. This is #lit.

Thanks @stevenckngaa for this exemplary work!

Left some comments but mostly cosmetic.

2021-11-26 15:44 UTC, jingtang10 approved these changes

2021-11-29 15:59 UTC, yigit approved these changes

2021-11-29 15:59 UTC, yigit commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val datastorePref = "1.0.0-rc02"
FYi this has 1.0.0 now.

2021-11-29 22:06 UTC, stevenckngaa commented on buildSrc/src/main/kotlin/Dependencies.kt
> +      const val datastorePref = "1.0.0-rc02"
This change doesn't introduce the datastorePref. Jing asked me to sort dependencies in the lexicographic order. I'll make a change in a separate PR. Cheers!

2021-11-29 22:08 UTC, merged