Kj/pagination overlapping buttons
google/android-fhir pull request #790
Opened 2021-09-17 08:13 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #602 

**Description**
Added a constraint layout to contain the RecyclerView and Page navigation buttons.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**
![floating_buttons](https://user-images.githubusercontent.com/48797364/133748619-201368e6-afde-4753-8c12-4c7daf48cc25.png)
![not_floating](https://user-images.githubusercontent.com/48797364/133748635-7f1ed6da-dda2-410e-84da-89da7ab792f0.png)

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-09-28 11:13 UTC, jingtang10 requested changes

2021-09-28 11:13 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> -        android:layout_height="wrap_content"
have you tried if setting this to `0dp` will fix the issue without more changes to the layout?

2021-09-28 11:13 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +  <androidx.constraintlayout.widget.ConstraintLayout
if you're adding a `ConstraintLayout`, you can probably drop the parent `RelativeLayout`?

2021-09-28 11:17 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> -        android:layout_height="wrap_content"
https://developer.android.com/guide/topics/ui/layout/relative relative layout should really work with this case.

2021-09-28 12:00 UTC, joiskash commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> -        android:layout_height="wrap_content"
Yes I have tried this.. It makes the RecyclerView disappear

2021-09-28 12:01 UTC, joiskash commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +  <androidx.constraintlayout.widget.ConstraintLayout
That is true.. I was just not sure.

2021-09-30 14:12 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +  <androidx.constraintlayout.widget.ConstraintLayout
lmk when this is done

2021-09-30 15:27 UTC, joiskash commented on datacapture/src/main/res/layout/questionnaire_fragment.xml
> +  <androidx.constraintlayout.widget.ConstraintLayout
done

2021-10-01 10:02 UTC, jingtang10 approved these changes
Thanks!

2021-10-01 10:07 UTC, merged