Refactoring : Unify group type check in ResourceMapper extractField
google/android-fhir pull request #798
Opened 2021-09-24 12:23 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #797

**Description**
Refactoring : Unify group type check in ResourceMapper extractField

**Alternative(s) considered**
no

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-09-29 09:21 UTC, jingtang10 requested changes

2021-09-29 09:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    bundle.apply { addEntry().apply { this.resource = resource } }
no need to use `apply` here

could just be `resource.extractFields` and `bundle.addEntry`...

2021-09-29 09:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +private fun Questionnaire.QuestionnaireItemComponent.createBase(): Base =
add documentation

2021-09-29 09:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private suspend fun extractResource(
add documentation

2021-09-30 12:10 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    updateFieldWithEnum(definitionField, questionnaireResponseItem.answer.first().value)
Not sure about low level and high level types which were present as inline comment in existing code.
Not sure about FHIR standard which has mention of it.

It seems comment `// this is a high level type e.g. AdministrativeGender` try to say about these are value set and represented by enum. [valuesets](https://www.hl7.org/fhir/terminologies-valuesets.html)
Is it okay to mention comment below?
_Value set defined as part of the FHIR specification, which include codes, https://www.hl7.org/fhir/terminologies-valuesets.html_

And inline comment `// this is a low level type e.g. StringType` may be suggests primitive type in FHIR.
[link] (https://www.hl7.org/fhir/datatypes.html#primitive)
Is it okay to mention comment below?
_Primitive types are those with only a value, and no additional elements as children, https://www.hl7.org/fhir/datatypes.html#primitive_

2021-09-30 15:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // this is a high level type e.g. AdministrativeGender
just remove this comment

2021-09-30 15:35 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +      // this is a low level type e.g. StringType
and remove this comment too

2021-09-30 15:35 UTC, jingtang10 approved these changes

2021-10-01 06:59 UTC, merged