Support readOnly element.
google/android-fhir pull request #833
Opened 2021-10-13 10:59 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #763  

**Description**
If questionnaire item has readOnly element true, then make relevant view/widget disable.

**Alternative(s) considered**
No

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-10 05:48 UTC, santosh-pingle commented
> In the RecyclerView, a read-only viewholder may be later reused for a read/write view. In that case `setViewReadOnly` should be called every time to set appropriate `view.isEnabled` value based on q`uestionnaireItemViewItem.questionnaireItem.readOnly` flag.

Done.

2021-11-10 05:49 UTC, santosh-pingle commented
Resolving conflicts.

2021-11-10 11:34 UTC, jingtang10 requested changes
In the `bind` function in `QuestionnaireItemViewHolder`, you call `setReadOnly` which is defined in `QuestionnaireItemViewHolderDelegate`.

2021-11-10 11:34 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
> +
add a function that should be implemented by each widget:
```
fun setReadOnly(isReadOnly: Boolean)
```

2021-11-15 06:58 UTC, santosh-pingle commented
readOnly  is true
<img width="421" alt="Screen Shot 2021-11-15 at 12 19 39 PM" src="https://user-images.githubusercontent.com/86107848/141735539-7b6bb474-76c3-4436-829a-6f6dbb6990f7.png">

gneder is read only
is active read only
<img width="427" alt="Screen Shot 2021-11-15 at 12 19 07 PM" src="https://user-images.githubusercontent.com/86107848/141735766-58159048-eff7-413d-84c3-b3874d0c976f.png">

Q4 is read only
<img width="425" alt="Screen Shot 2021-11-15 at 12 25 50 PM" src="https://user-images.githubusercontent.com/86107848/141736129-2a30a675-abf3-4c55-93d8-1dee6be932a5.png">

2021-11-18 11:30 UTC, jingtang10 approved these changes
Great work thanks!

2021-11-18 11:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
> +          var view = chipContainer.getFlexItemAt(i)
```suggestion
          val view = chipContainer.getFlexItemAt(i)
```

2021-11-18 11:30 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
> +          var view = radioGroup.getChildAt(i)
```suggestion
          val view = radioGroup.getChildAt(i)
```

2021-11-19 09:02 UTC, santosh-pingle commented
@jingtang10 
It looks like we need to handle below use case as well.
-> If questionnaire item has `readOnly` property set to true and it also has nested items, then those all nested item views need to be readonly. And it is required to set `readOnly` property of all those nested item in `QuestionnaireViewModel` if parent item is read only. 
correct?

2021-11-22 09:38 UTC, jingtang10 commented
> If questionnaire item has `readOnly` property set to true and it also has nested items, then those all nested item views need to be set readonly. To make this change, it is required to set `readOnly` property for all those nested item in `QuestionnaireViewModel`

Where is this from? I couldn't find it either on the questionnaire resource documentation or the sdc ig.

Personally I'd like to understand why this is the case -- it's not inconceivable that you have a top-level answer that cannot be changed with nested answer that can be changed.

I'm happy for you to add a TODO (and create an issue) with a link to the source of this.

2021-11-22 10:38 UTC, santosh-pingle commented
> > If questionnaire item has `readOnly` property set to true and it also has nested items, then those all nested item views need to be set readonly. To make this change, it is required to set `readOnly` property for all those nested item in `QuestionnaireViewModel`
> 
> Where is this from? I couldn't find it either on the questionnaire resource documentation or the sdc ig.
> 
> Personally I'd like to understand why this is the case -- it's not inconceivable that you have a top-level answer that cannot be changed with nested answer that can be changed.
> 
> I'm happy for you to add a TODO (and create an issue) with a link to the source of this.

Just for reference,
Discussed offline.
Its not required to handle, there is no such reference, just query which I had.

2021-11-22 12:08 UTC, merged