Add phone number widget to contrib package
google/android-fhir pull request #838
Opened 2021-10-13 14:37 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Addresses #650 #868

**Description**
Added a simple phone number widget that sets the raw input type of the textInputEditText to TYPE_CLASS_PHONE

**Alternative(s) considered**
No

**Type**
Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-11 12:58 UTC, joiskash commented
Simplified QuestionnaireItemPhoneNumberViewHolderFactory by extending QuestionnaireItemEditTextSingleLineViewHolderFactory and setting the input type to [TYPE_CLASS_PHONE](https://developer.android.com/reference/android/text/InputType#TYPE_CLASS_PHONE)

2022-01-25 15:34 UTC, jingtang10 requested changes

2022-01-25 15:34 UTC, jingtang10 commented on catalog/src/main/assets/patient-registration-paginated.json
>                "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-instruction",
and can you add this to the data capture lib wiki once this is merged? e.g. https://github.com/google/android-fhir/wiki/Structured-Data-Capture-Library#predefined-custom-widgets

2022-01-25 15:34 UTC, jingtang10 commented on catalog/src/main/java/com/google/android/fhir/catalog/CustomQuestionnaireFragment.kt
> +            else it.value.toString() == QuestionnaireItemPhoneNumberViewHolderFactory.WIDGET_TYPE
i don't know if we should just move this into the data capture library?

if we define a specific extension url already, then it seems to actually make sense for this decision to be inside the library. so you don't need to change this custom fragment.

2022-01-27 10:29 UTC, joiskash commented on catalog/src/main/assets/patient-registration-paginated.json
>                "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-instruction",
Another idea that came to my mind is to just use item-control. Since the binding is extensible http://hl7.org/fhir/R4/extension-questionnaire-itemcontrol.html . That way we can use MoreQuestionnaireItemComponents

2022-01-27 11:07 UTC, joiskash commented on catalog/src/main/assets/patient-registration-paginated.json
>                "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-instruction",
Ok got it. I will go ahead and use extension.url = https://github.com/google/android-fhir/questionnaire-itemControl and extension.valueCoding = phone-number. For now I will not use MoreQuestionnaireItemComponents and will handle the selection logic in the adapter itself. By checking the extension and value.toString()

2022-01-27 12:05 UTC, joiskash commented on catalog/src/main/assets/patient-registration-paginated.json
>                "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-instruction",
Ok so I will go with the same approach as being used for Item controls, but ill just set the URL for the extension and the coding system to be https://github.com/google/android-fhir/StructureDefiniton/questionnaire-itemControl and https://github.com/google/android-fhir/questionnaire-item-control respectively .

2022-01-29 11:04 UTC, Tarun-Bhardwaj commented
@joiskash , though you have committed changes 2 days back, the status still shows 'Changes requested'. Is there an ETA by when the remaining changes can be committed?

2022-01-31 04:23 UTC, joiskash commented
> @joiskash , though you have committed changes 2 days back, the status still shows 'Changes requested'. Is there an ETA by when the remaining changes can be committed?

It is ready for review, I will re-request :)

2022-02-09 09:47 UTC, jingtang10 approved these changes
just a few small comments

2022-02-09 09:47 UTC, jingtang10 commented on catalog/src/main/assets/patient-registration-paginated.json
> +                    "display": "Phone Number"
do you need this?

2022-02-09 09:47 UTC, jingtang10 commented on catalog/src/main/assets/patient-registration-paginated.json
> +                "text": "Phone Number"
do you need this?

2022-02-09 09:47 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +                .setDisplay("Phone Number")
not needed?

2022-02-09 09:47 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                .setDisplay("Phone Number")
not needed?

2022-02-09 09:47 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +  private fun getViewGroup(): ViewGroup {
can remove?

2022-02-09 10:12 UTC, joiskash commented on catalog/src/main/assets/patient-registration-paginated.json
> +                    "display": "Phone Number"
Removed

2022-02-09 10:12 UTC, joiskash commented on catalog/src/main/assets/patient-registration-paginated.json
> +                "text": "Phone Number"
removed

2022-02-09 10:12 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
> +                .setDisplay("Phone Number")
removed

2022-02-09 10:13 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +                .setDisplay("Phone Number")
removed

2022-02-09 10:13 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
> +  private fun getViewGroup(): ViewGroup {
removed

2022-02-10 09:14 UTC, merged