Implement inequality operators (<, >, <=, >=) in the enable when statement
google/android-fhir pull request #848
Opened 2021-10-21 14:38 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #818 

**Description**
Implement inequality operators (<, >, <=, >=) in the enable when statement

**Alternative(s) considered**
no

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-01 18:13 UTC, jingtang10 commented
please update this PR now that #847 is merged

2021-11-04 11:55 UTC, jingtang10 requested changes
please udpate

2021-11-09 08:46 UTC, santosh-pingle commented
Updating PR.

2021-11-10 05:37 UTC, santosh-pingle commented
@jingtang10 
Can you please review it?
I will check whether I can add more tests to increase code coverage.

2021-11-10 11:09 UTC, jingtang10 requested changes
as discussed, merge the `MoreTypes.kt` files and move it to the `common` module and use the `Type.compareTo` rather than defining the extension functions on the `QuestionnaireItemEnableWhenComponent`.

2021-11-15 05:25 UTC, santosh-pingle commented
Working on review comments.

2021-11-16 05:18 UTC, santosh-pingle commented
#923

2021-11-19 08:49 UTC, santosh-pingle commented
> as discussed, merge the `MoreTypes.kt` files and move it to the `common` module and use the `Type.compareTo` rather than defining the extension functions on the `QuestionnaireItemEnableWhenComponent`.

done.

2021-11-22 14:15 UTC, jingtang10 requested changes
In general we shouldn't be making any code change without unit test change.

If `MoreTypes.kt` file is changed please add unit tests as well.

I don't believe the quantity type needs to be singled out in the unit test for the enablement evaluator -- that's an irrelevant detail in the code of enablement evaluator. but that's a relevant detail in the `MoreTypes.kt` file, so the tests should reside there.

2021-11-23 05:58 UTC, santosh-pingle commented
yes, quantity tests need to be moved to ```MoreTypes.kt```, thanks!

2021-11-23 12:41 UTC, jingtang10 requested changes

2021-11-23 12:41 UTC, jingtang10 commented on common/src/main/java/com/google/android/fhir/MoreTypes.kt
> +      this.fhirType().equals("Quantity") -> {
can you try to change the function signature to this:

`operator fun Type.compareTo(value: Type): Int {`

i.e. remove the `?` in the parameter type.

and then remove line 46 as a check? thanks

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_greaterOrEqual_answersGreaterOrEqualEnableWhenAnswer_shouldReturnTrue() {
```suggestion
  fun evaluate_expectAnswerGreaterThanOrEqualToValue_answerGreaterThanOrEqualToValue_shouldReturnTrue() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_lessOrEqual_answerLessOrEqualEnableWhenAnswer_shouldReturnTrue() {
```suggestion
  fun evaluate_expectAnswerLessThanOrEqualToValue_someAnswerLessThanOrEqualToValue_shouldReturnTrue() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_lessOrEqual_noAnswerLessOrEqualEnableWhenAnswer_shouldReturnFalse() {
```suggestion
  fun evaluate_expectAnswerLessThanOrEqualToValue_noAnswerLessThanOrEqualToValue_shouldReturnFalse() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_greaterOrEqual_noAnswersGreaterOrEqualEnableWhenAnswer_shouldReturnFalse() {
```suggestion
  fun evaluate_expectAnswerGreaterThanOrEqualToValue_noAnswerGreaterThanOrEqualToValue_shouldReturnFalse() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_greaterThan_answersGreaterThanEnableWhenAnswer_shouldReturnTrue() {
```suggestion
  fun evaluate_expectAnswerGreaterThanValue_someAnswerGreaterThanValue_shouldReturnTrue() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_greaterThan_noAnswersGreaterThanEnableWhenAnswer_shouldReturnFalse() {
```suggestion
  fun evaluate_expectAnswerGreaterThanValue_noAnswerGreaterThanValue_shouldReturnFalse() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_lessThan_answersLessThanEnableWhenAnswer_shouldReturnTrue() {
```suggestion
  fun evaluate_expectAnswerLessThanValue_someAnswerLessThanValue_shouldReturnTrue() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  fun evaluate_lessThan_noAnswersLessThanEnableWhenAnswer_shouldReturnFalse() {
```suggestion
  fun evaluate_expectAnswerLessThanValue_noAnswerLessThanValue_shouldReturnFalse() {
```

2021-11-23 12:41 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/enablement/EnablementEvaluatorTest.kt
> +  @Test
all these new tests should be moved to line 183.

2021-11-25 06:34 UTC, santosh-pingle commented
Updating code as per review comments.

2021-11-25 12:44 UTC, jingtang10 approved these changes
Thanks @santosh-pingle!

2021-11-25 12:44 UTC, merged