Do not show soft keyboard on details patient card if it is opened on previous screen.
google/android-fhir pull request #906
Opened 2021-11-01 09:33 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #861 

**Description**
If soft keyboard opened on Add, Edit, Screener and Search screen and user navigate to Patient details card, then 
keyboard stays opened on details screen.

Therefore once action is complete on Add, Edit, Search patient and screener screen, just hide/close the soft keyboard so that it will not be shown on details screen.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-01 18:26 UTC, jingtang10 requested changes
What if you click the back button on the questionnaire screen without submitting the questionnaire? have you tested this case?

2021-11-01 18:26 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/util/Util.kt
> +inline fun hideSoftKeyboard(activity: Activity?) {
can you change this into an extension function?

`inline fun Activity.hideSoftKeyboard`

2021-11-01 18:26 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/util/Util.kt
> +    view.clearFocus()
```suggestion
    // Clear focus to avoid showing soft keyboard again if activity is launched again 
    view.clearFocus()
```

2021-11-01 18:26 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/util/Util.kt
> +    imm.hideSoftInputFromWindow(view.windowToken, 0)
```suggestion
    (activity.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager).hideSoftInputFromWindow(view.windowToken, 0)
```

2021-11-01 18:30 UTC, jingtang10 commented
> What if you click the back button on the questionnaire screen without submitting the questionnaire? have you tested this case?

maybe try to do this in `onPause`?

2021-11-09 06:38 UTC, santosh-pingle commented
looking into the review comments.

2021-11-09 07:38 UTC, santosh-pingle commented
> > What if you click the back button on the questionnaire screen without submitting the questionnaire? have you tested this case?
> 
> maybe try to do this in `onPause`?

Done.

2021-11-10 11:14 UTC, jingtang10 reviewed
https://stackoverflow.com/questions/10627137/how-can-i-know-when-an-edittext-loses-focus

can you please try putting this logic in the data capture library (in the `views` package in the specific widgets), e.g.:

```
    textInputEditText.setOnFocusChangeListener {view, focused ->
      if (!focused) {
        // hide soft keyboard
        view.context.applicationContext.getSystemService()...
      }
    }
```

2021-11-10 19:28 UTC, jingtang10 requested changes

2021-11-10 19:28 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +          activity?.hideSoftKeyboard()
do you stil need this change?

2021-11-10 19:28 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +    activity?.hideSoftKeyboard()
do you stil need this change?

2021-11-10 19:28 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +    activity?.hideSoftKeyboard()
do you stil need this change?

2021-11-10 19:28 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/util/Util.kt
> +/*
i don't think it's appropriate to still place this file in the `reference` module

2021-11-11 06:05 UTC, santosh-pingle commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +          activity?.hideSoftKeyboard()
Instead of this change below code snippet is added
```
searchView.setOnQueryTextFocusChangeListener { view, focused ->
      if (!focused) { ...
```

It is required here, as patient list fragment has searchview view which is part of reference app only.
If we do not add above code snippet then soft keyboard get shown on next page if it is already open on patient list screen.

2021-11-11 06:07 UTC, santosh-pingle commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +    activity?.hideSoftKeyboard()
same here.

2021-11-11 06:07 UTC, santosh-pingle commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +    activity?.hideSoftKeyboard()
same here

2021-11-11 12:01 UTC, jingtang10 approved these changes
Well done!

2021-11-11 12:02 UTC, jingtang10 commented on reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
> +        (activity?.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
```suggestion
        (requireActivity().getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
```

2021-11-12 09:21 UTC, merged