Changes to use logical operator instead of Set operators while generating Search SQL query
google/android-fhir pull request #920
Opened 2021-11-11 07:12 UTC by aditya-07

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #908

**Description**
Use AND/OR operators exclusively instead a mix of AND/OR & UNION/INTERSECT while generating Search SQL query.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-12-06 12:30 UTC, jingtang10 requested changes
thanks @aditya-07 - some intial comments

2021-12-06 12:30 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +internal enum class PrePost {
add documentation to explain this

2021-12-06 12:30 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    fun <T> Collection<T>.joinToQueryString(
I kinda feel this utility function can do so much more:

```
fun List<ConditionParam>.join(separator: String): ConditionParam
```

basically it needs to combine subqueries together by joining the strings and concatenating the param lists.

If you look at the different types of filter criteria classes, this logic is basically duplicated in each class.

2021-12-06 12:30 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +enum class Operation(val logicOperator: String) {
nit:
```suggestion
enum class Operation(val logicalOperator: String) {
```

2021-12-06 12:30 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    fun <T> Collection<T>.joinToQueryString(
also i don't think this should be in a companion object -- it can just be a ext function.

2021-12-06 12:30 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    fun <T> Collection<T>.joinToQueryString(
also does this mean that the different `***Criteria` classes can actually be one class allowing the different filter criterions within the same criteria to be different types (since you'll probably have to get rid of the type anyway)?

2022-01-04 19:26 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
> +      .map { it.query(type) }
Done

2022-01-04 19:27 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +internal enum class PrePost {
Removed it during refactoring.

2022-01-04 19:29 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    fun <T> Collection<T>.joinToQueryString(
Done. All `**Criteria` classes except for `DateClientParamFilterCriteria` now are just thin data classes and the query generation is taken care by `FilterCriteria` .

2022-01-04 19:29 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
> +enum class Operation(val logicOperator: String) {
Done

2022-01-04 23:15 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +    TODO(
should this be implemented?

2022-01-04 23:15 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    fun <T> Collection<T>.joinToQueryString(
great! why isn't date handled in this pr?

2022-01-04 23:40 UTC, jingtang10 requested changes

2022-01-04 23:40 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +  private fun List<ConditionParam<*>>.toQueryString(
this function is repeated in the date class, can the code be shared?

2022-01-05 08:40 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +  private fun List<ConditionParam<*>>.toQueryString(
This function `toQueryString` tries to generate a Condition string to be used in the query by looking at the provided ConditionParams. 
Date class function `joinToQueryString` on the other hand tries to create a unified Query from two distinct queries (DateIndexEntity and DateTimeIndexEntity if they are present). 

There might be a way to unify them, but I feel. the two are doing quite different work and having separate functions increases the code readability.

2022-01-05 08:43 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +    TODO(
TODO does throw `NotImplementedError`. But, replacing it with an explicit `UnsupportedOperationException` for better readability.

2022-01-05 10:06 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +    TODO(
Never mind, refactored the code to implement `getConditionalParams`

2022-01-05 20:10 UTC, jingtang10 requested changes

2022-01-05 20:10 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +    buffer: Appendable = StringBuilder(),
do we need this optional param if it's not used anywhere?

2022-01-05 20:10 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +  private fun <T> Collection<T>.joinToQueryString(
is it really worth having this as a generic function or can we just use the actual type here?

2022-01-07 08:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    val buffer: Appendable = StringBuilder()
Removed as the function toQueryString now internally calls `Iterable<T>.joinToString` to construct the string.

2022-01-07 08:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    operation: Operation,
Done

2022-01-07 08:20 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    val separator = " ${operation.logicalOperator} "
Removed as the function toQueryString now internally calls `Iterable<T>.joinToString` to construct the string.

2022-01-07 08:21 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
> +    }
Done.

2022-01-07 08:22 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +  private fun <T> Collection<T>.joinToQueryString(
Don't need this function anymore. Directly using `Iterable<T>.joinToString` to construct the query.

2022-01-07 08:22 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +    buffer: Appendable = StringBuilder(),
Nope.

2022-01-07 08:24 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +      listOf(getConditionParamPair(prefix, value!!.dateTime!!))
Done. But I think we should fail early in the filter apis itself if the user doesn't provide value for a particular Criterion.

2022-01-07 12:42 UTC, jingtang10 approved these changes
just a couple of small comments. otherwise good to merge!

thanks @aditya-07 ! 👍

2022-01-07 12:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
>  internal fun List<NestedSearch>.nestedQuery(
optional:

i'm slightly unhappy with this function. the function is returning the new query statement while mutating the list of arguments... is there a way to make it cleaner?

this is optional and can be done (or not done) in a follow-up.

2022-01-07 12:42 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +        throw IllegalArgumentException("DateClientParamFilter.value can't be null.")
use `check`: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html at the beginning of this function

2022-01-07 13:51 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
> +        throw IllegalArgumentException("DateClientParamFilter.value can't be null.")
Done

2022-01-07 13:54 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
>  internal fun List<NestedSearch>.nestedQuery(
Yes, I agree. I can clean it up in a subsequent PR.

2022-01-07 15:42 UTC, merged