Change validateQuestionnaireResponseItems to allow questionnaire repsponse with missing items
google/android-fhir pull request #926
Opened 2021-11-17 10:03 UTC by joiskash

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #912 #836

**Description**
Re-wrote validateQuestionnaireResponseItems to take the input questionnaire response and validate it against the questionnaire response that is created by using the questionnaire.

**Alternative(s) considered**
Yes the alternative was to use the input questionnaire response as the main questionnaire response and add items if and when enable was activated. This seemed to be a more complicated solution

**Type**
Bug fix

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-17 10:03 UTC, joiskash commented
@jingtang10 please take a look at this. There are two questions:

2021-11-17 10:11 UTC, joiskash commented
@jingtang10 please take a look at this. These two questions are dealt as follows:

1. How do we deal with a questionnaire response that has more items than the questionnaire? Currently throwing an error No matching questionnaire item for questionnaire response item
2. How do we deal with a questionnaire response that has less items than the questionnaire? Not throwing any error because questionnaire response may not have disabled items.

2021-11-23 15:17 UTC, joiskash commented
> Should the validation code live in QuestionnaireResponseValidator.kt instead?
That class is responsible for validating answers that are typed in via UI. I dont think we should mix them up. Maybe we change the name of this function to checkQuestionnaireResponseAgainstQuestionnaire

This function is independent of creating the questionnaire response item . What I have done is to use the questionnaire response item that is created with the questionnaire and only fill up answers from the input questionnaire response after verifying that 

1. linkIDs match and order of questions is maintained
2. type matches for the primitive types
3. only questionnaire items which allow repeats allow multiple answers
4. There are no extra questionnaire response items

Since we are not using the input questionnaire response as the main questionnaire response to build view items, we will not be generating view items without response in the tuple. This is to make sure that irrespective of the items present in the input questionnaire response, the SDK will allow the user to answer the questionnaire completely.

PS: input questionnaire response is the one that is passed to the fragment via the bundle. The main questionnaire response is what we create by going through the questionnaire hierarchy.

2021-12-01 10:03 UTC, joiskash commented
I have made two changes as per @jingtang10 suggestion

1. Moved the validation function to QuestionnaireResponseValidator.kt 
2. Made some change in the getQuestionnaireState function to add missing questionnaireResponseItems.

I felt that instead of allowing for empty questionnaireResponseItems in the QuestionnaireItemViewItem, we could just use existing code to create them while fetching the list for the state flow. This change also helps us in the futures by avoiding zipping questionnaires and questionnaireResponse together because of the details in #910

2021-12-08 20:26 UTC, jingtang10 commented
@kevinmost can you please also take a look at this? thanks!

2021-12-09 16:58 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              questionnaireItem.linkId.equals(questionnaireResponseItem.linkId)
Nit: Prefer `==` in Kotlin

2021-12-09 16:58 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          .withIndex()
Nit: Would be a bit more performant to use

```
.flatMapIndexed { index, questionnaireItem ->
```

2021-12-09 16:58 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +    val questionnaireResponseInputItemListIterator = questionnaireResponseInputItemList.iterator()
If these two need to have the same length (which it looks like they do, as we throw an error if they don't on line 137), I would recommend using `zip` and doing something like this:

```kotlin
require(questionnaireItemList.size == questionnaireResponseInputItemList.size) {
  "Unequal item amounts: ${questionnaireItemList.size} items and ${questionnaireResponseInputItemList.size} responses"
}
questionnaireItemList.zip(questionnaireResponseInputItemList)
  .forEach { (questionnaireItem, questionnaireResponseInputItem) -> ... }
```

2021-12-09 16:58 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +        if (!questionnaireItem.linkId.equals(questionnaireResponseInputItem.linkId)) {
Nit: I'd also do this via `require`, and use `==`.

```kotlin
require(questionnaireItem.linkId == questionnaireResponseInputItem.linkId) { "Mismatching..." }
```

2021-12-09 16:58 UTC, kevinmost commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +              mutableListOf(
Does this need to be mutable?

2021-12-09 17:17 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +    val questionnaireResponseInputItemListIterator = questionnaireResponseInputItemList.iterator()
They don't have to be of the same length.. The questionnaire response may not have some items . This can happen if the item was disabled / not answered. That's why i removed the zip from the previous implementation.

2021-12-10 08:19 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +    val questionnaireResponseInputItemListIterator = questionnaireResponseInputItemList.iterator()
The error we throw on line 137 is to make sure the questionnaire response does not have more items than the questionnaire. But the questionnaire response can have less number of items. Thats why I am iterating over questionnaireResponseList and using the index to fetch the corresponding questionnaire item. You will find more details regarding this in #836 . Please let me know if it does not make sense.

2021-12-10 08:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +              questionnaireItem.linkId.equals(questionnaireResponseItem.linkId)
done

2021-12-10 08:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
>          .withIndex()
done

2021-12-10 08:34 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +        if (!questionnaireItem.linkId.equals(questionnaireResponseInputItem.linkId)) {
done

2021-12-10 08:34 UTC, joiskash commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +              mutableListOf(
nope , i made changed it to `listOf` :)

2021-12-10 13:32 UTC, jingtang10 requested changes

2021-12-14 13:39 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +  fun validateQuestionnaireResponseItems(
done, I have made this function a private helper and changed the names of the validate functions.

2021-12-15 15:11 UTC, kevinmost approved these changes

2021-12-15 15:11 UTC, kevinmost commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +            index,
Nit: Looks like the index is not needed, could this become `forEach` instead?

2021-12-15 15:19 UTC, jingtang10 approved these changes
Thanks @joiskash!

I think with this change, we should move a lot of the test cases from view model to the validation package. But that can be done in a follow-up.

2021-12-15 15:27 UTC, joiskash commented on datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt
> +            index,
Will take care of it in my next PR. Thanks!

2021-12-15 15:28 UTC, joiskash commented
> Thanks @joiskash!
> 
> I think with this change, we should move a lot of the test cases from view model to the validation package. But that can be done in a follow-up.
> 
> 

Yes absolutely! That shouldn't be too hard to do.

2021-12-15 17:42 UTC, merged