Internationalization for Questionnaire AnswerOptions
google/android-fhir pull request #927
Opened 2021-11-17 17:04 UTC by ndegwamartin

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #929

**Description**
  Add Multi language translations support for Questionnaire Answer Options via FHIR Extensions
. 

**Alternative(s) considered**
Alternatives for Multi language support are CodeSystems and ValueSets via Designations

**Type**
Choose one: (Feature)

**Screenshots (if applicable)** 

```
                    "answerOption": [
                        {
                            "valueCoding": {
                                "system": "http://hl7.org/fhir/administrative-gender",
                                "code": "female",
                                "display": "Female",
                                "_display": {
                                    "extension": [
                                        {
                                            "url": "http://hl7.org/fhir/StructureDefinition/translation",
                                            "extension": [
                                                {
                                                    "url": "lang",
                                                    "valueCode": "sw-KE"
                                                },
                                                {
                                                    "url": "content",
                                                    "valueString": "Mwanamke"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            }
                        },
```

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-19 20:03 UTC, santosh-pingle reviewed
left some comments.

2021-11-19 20:03 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
> +  fun getDisplayString_choiceItemType_answerOptionShouldReturnDisplayValueForMalformedLanguageExtension() {
is it ok to rename it as
```
getDisplayString_invalidExtension_shouldReturnDisplayValue

```

2021-11-19 20:03 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
> +
can we remove extra blank line?

2021-11-19 20:03 UTC, santosh-pingle commented on datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
> +
can we remove extra blank line?

2021-11-23 06:16 UTC, ndegwamartin commented
@santosh-pingle made the updates based on your feedback, please have a look

2021-12-06 20:54 UTC, jingtang10 requested changes
Please see the comment I made in the linked issue https://github.com/google/android-fhir/issues/929#issuecomment-987197522

According to the example I found here: https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Coding-uv-ips.html it seems the translation extension is on the `display` (which is a string) rather than the `Coding`.

If that's the case, then all we need to do is to reuse the extension function

```
fun StringType.getLocalizedText
```

I would suggest moving that function to the `common` module if that's the path we decide to go down.

2022-01-29 11:01 UTC, Tarun-Bhardwaj commented
@ndegwamartin , though you have committed changes 3 days back, the status still shows 'Changes requested'. Is there an ETA by when the remaining changes can be committed?

2022-02-07 17:51 UTC, jingtang10 requested changes
https://github.com/google/android-fhir/pull/1037 has been released today.

looks good. just have to update the dependency.

2022-02-07 17:51 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> -  const val androidFhirCommon = "com.google.android.fhir:common:${Versions.androidFhirCommon}"
revert

2022-02-07 17:51 UTC, jingtang10 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val androidFhirCommon = "0.1.0-alpha01-preview3-SNAPSHOT"
```suggestion
    const val androidFhirCommon = "0.1.0-alpha02"
```

2022-02-09 06:36 UTC, ndegwamartin commented
> 

@Tarun-Bhardwaj The PR was awaiting the Alpha 02 Release of the FHIR Common Library which is now ready. I've updated the PR

2022-02-09 09:22 UTC, jingtang10 approved these changes

2022-02-09 09:27 UTC, merged