Add safe call in validateQuestionnaireResponseItems
google/android-fhir pull request #937
Opened 2021-11-23 12:03 UTC by FikriMilano

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #936

**Description**
Add safe call in validateQuestionnaireResponseItems

**Alternative(s) considered**
N/A

**Type**
Feature

**Screenshots (if applicable)**
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-23 13:04 UTC, jingtang10 requested changes

2021-11-23 13:04 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
I think the call that we should add is to check that each questionnaire item has type -- can you do that instead please?

```
val type = checkNotNull(questionnaireItem.type) { "Questionnaire item must have type" }
```

on line 346

and then use `type` later in the if/else block

2021-11-23 13:23 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
sure, thanks

2021-11-23 14:39 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
wait that doesn't fix the current issue.

but when I flipped that, it works.
`if (Questionnaire.QuestionnaireItemType.GROUP.equals(questionnaireItem.type)) {`

is this fine?

2021-11-23 14:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
what's the current issue? i think to fix the current issue the questionnaire needs to be fixed.

but in the code i think we should have the `checkNotNull`.

2021-11-24 01:18 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
the issue is when calling `questionnaireItem.type` will crash the app because of NPE.
it can be prevented by flipping the checks like the sample above.

I'm not sure it was the questionnaire though, because for custom widget I was following this example from datacapture gallery.
https://github.com/google/android-fhir/blob/master/datacapturegallery/src/main/assets/hl7-questionnaire-example-f201-lifelines.json#L52..L60

2021-11-24 11:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
yeah that example needs to be fixed.

see documentation here: https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.type

cardinality is 1..1 -- meaning it's mandatory.

2021-11-24 23:52 UTC, FikriMilano commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (questionnaireItem.type?.equals(Questionnaire.QuestionnaireItemType.GROUP) == true) {
I see, okay then. I think that's resolved.
Will only add the `checkNotNull`

2021-11-29 14:48 UTC, jingtang10 requested changes
1. please add a test in the questionnaire view model test (look at something like `questionnareHasInitialValueAndGroupType_shouldThrowError` and adapt it) and make sure a questionnaire item with missing type will throw an exception
2. please fix the broken questionnarie in our gallary app -- so it won't crash

2021-11-30 00:16 UTC, FikriMilano commented
sure, thanks for the feedback

2021-12-01 09:20 UTC, jingtang10 approved these changes

2021-12-01 09:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
> +      if (type.equals(Questionnaire.QuestionnaireItemType.GROUP)) {
```suggestion
      if (type == Questionnaire.QuestionnaireItemType.GROUP) {
```

2021-12-01 09:20 UTC, jingtang10 commented on datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
> +  fun questionnaireHasNullType_shouldThrowError() {
```suggestion
  fun questionnaireItemMissingType_shouldThrowError() {
```

2021-12-05 23:38 UTC, merged