Readonly edittext view.
google/android-fhir pull request #939
Opened 2021-11-24 09:58 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
 Readonly edittext view.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one:  Feature 

**Screenshots (if applicable)**

 Before implementation 
 _Edit text with Mark value_
<img width="430" alt="Screen Shot 2021-11-24 at 3 21 36 PM" src="https://user-images.githubusercontent.com/86107848/143215491-baf4f485-0e83-40ea-b305-2fa2bd1275c0.png">

 After implementation 
 _Edit text with Mark value_
<img width="433" alt="Screen Shot 2021-11-24 at 3 24 29 PM" src="https://user-images.githubusercontent.com/86107848/143215907-25b47e8d-0214-45e1-9560-8e967503a79f.png">

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-11-24 10:29 UTC, santosh-pingle commented
@jing could you please confirm proposed implementation?

2021-11-24 19:35 UTC, jingtang10 requested changes

2021-11-24 19:35 UTC, jingtang10 commented on datacapture/src/main/res/color/box_stroke_color.xml
> +</selector>
assuming you modified this from the android source? can you link to the original file and comment on the diff?

2021-11-24 19:35 UTC, jingtang10 commented on datacapture/src/main/res/color/text_color.xml
> +</selector>
assuming you modified this from the android source? can you link to the original file and comment on the diff?

2021-11-24 19:35 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/text_color</item>
Add comment:

`Override default theme text color to improve contrast of disabled text.`

2021-11-24 19:35 UTC, jingtang10 commented on datacapture/src/main/res/values/styles.xml
> +        <item name="boxStrokeColor">@color/box_stroke_color</item>
Add comment:

`Override default theme box stroke color to improve contrast of disabled widget.`

2021-11-24 20:54 UTC, jingtang10 commented
please also update the PR name and description

2021-11-25 09:44 UTC, santosh-pingle commented
Updating code changes as per review comments.

2021-11-25 10:39 UTC, santosh-pingle commented on datacapture/src/main/res/color/text_color.xml
> +</selector>
it is newly created color state list resource.

2021-11-25 12:34 UTC, jingtang10 commented
please mark as ready to review if ready. thanks!

2021-11-25 12:49 UTC, santosh-pingle commented on datacapture/src/main/res/color/box_stroke_color.xml
> +</selector>
I have update comment with file name, please check once.

2021-11-25 13:01 UTC, santosh-pingle commented
@jingtang10 
Implemented contrast change is only visible to questionnaire edit text view (`QuestionnaireItemEditTextViewHolderFactory`) and not for others. Do we also need to apply it to other questionnaire views?

2021-11-25 14:40 UTC, jingtang10 commented
> @jingtang10 Implemented contrast change is only visible to questionnaire edit text view (`QuestionnaireItemEditTextViewHolderFactory`) and not for others. Do we need to apply it to other questionnaire views?

yeah you do. anything with the edit text you'll need to apply the stroke color, anything with text you'll probably need to apply the text color.

2021-11-25 14:42 UTC, jingtang10 commented
have you also tested this with dark theme? please attach some screenshots. thanks!

2021-11-25 14:42 UTC, jingtang10 commented
also please attach before/after screenshots with other widgets if you do them in the same PR.

2021-11-26 06:37 UTC, santosh-pingle commented
> have you also tested this with dark theme? please attach some screenshots. thanks!

looking into it.

2021-11-26 10:52 UTC, santosh-pingle commented
> > have you also tested this with dark theme? please attach some screenshots. thanks!
> 
> looking into it.

@shelaghm 
when `#9E9E9E` get applied to the disabled text and container it works as expected in light theme (please refer earlier screenshots) but when it switch to the dark theme then contrast/opacity is too high. 
To fix this issue, it is required to use alpha value and theme attribute to create color state list resource. 
As you mentioned **38% opacity** in earlier comments I assumed **alpha value is .38** as range is 0 to 1, now it works  in both themes, but if you think alpha value can be greater than .38 please let me know.

Light theme : read only view with alpha .38

<img width="425" alt="light theme alpha  38" src="https://user-images.githubusercontent.com/86107848/143567542-f09e1c5c-086c-4aee-a4a0-e46dd7389fb9.png">

Dark theme : readonly view with alpha .38
<img width="432" alt="dark theme with alpha  38" src="https://user-images.githubusercontent.com/86107848/143567587-166badad-96ac-4868-a3a9-850e0568e497.png">

2021-11-29 08:05 UTC, santosh-pingle commented
autocomplete textview, light theme, alpha .38
<img width="428" alt="light theme autocomplete  38" src="https://user-images.githubusercontent.com/86107848/143829740-010f48a3-71ca-4de6-bc85-ca4d8788f18a.png">

autocomplete textview, dark theme, alpha .38

<img width="430" alt="dark theme autocomplete  38" src="https://user-images.githubusercontent.com/86107848/143829849-e1fa78fb-054b-4ba0-932c-8a2c9d875363.png">

2021-11-29 12:52 UTC, santosh-pingle commented
Q Hep B y / n readonly view `QuestionnaireItemBooleanTypePickerViewHolderFactory`, alpha .38, light theme
<img width="426" alt="light boolean  38" src="https://user-images.githubusercontent.com/86107848/143870640-4be10104-577d-4f92-b1ac-2037e72b41f0.png">

Q Hep B y / n readonly view `QuestionnaireItemBooleanTypePickerViewHolderFactory`, alpha .38, dark theme
<img width="431" alt="dark boolean  38" src="https://user-images.githubusercontent.com/86107848/143870774-de220d79-3dfe-4637-82ce-328197be38e6.png">

2021-11-29 14:37 UTC, santosh-pingle commented
Q. 1st dose 2nd dose readonly view `QuestionnaireItemDateTimePickerViewHolderFactory`, light theme, alpha .38
 
<img width="429" alt="datetime picker light alpha  38" src="https://user-images.githubusercontent.com/86107848/143886917-75f8e5c5-2b0e-42e1-b2a9-5abfa9e8f7e0.png">


Q. 1st dose 2nd dose readonly view `QuestionnaireItemDateTimePickerViewHolderFactory`, dark theme, alpha .38

<img width="429" alt="datetimepicker dark alpha  38" src="https://user-images.githubusercontent.com/86107848/143886981-8d16c5a9-89a2-45b6-a454-f7b8d7ea528f.png">

2021-11-30 08:40 UTC, santosh-pingle commented
Q.1 & Q.3 readonly view `QuestionnaireItemDialogSelectViewHolderFactory`, light theme, alpha .38
<img width="433" alt="light drop down dialog select alpha  38" src="https://user-images.githubusercontent.com/86107848/144013322-cb3d9489-5bb1-4cd6-99d3-538890882027.png">


Q.1 & Q.3 readonly view `QuestionnaireItemDialogSelectViewHolderFactory`, dark theme, alpha .38
<img width="431" alt="dark drop down dialog select alpha  38" src="https://user-images.githubusercontent.com/86107848/144013342-ff9cedf2-1e22-42f7-9979-b5a33b6590b0.png">

2021-12-01 05:17 UTC, santosh-pingle commented
@jingtang10
Can you please it? Thanks!

2021-12-03 11:22 UTC, santosh-pingle commented
readonly view `QuestionnaireItemDropDownViewHolderFactory` alpha .38

<img width="419" alt="Screen Shot 2021-12-03 at 4 47 41 PM" src="https://user-images.githubusercontent.com/86107848/144594212-48cc280d-c2ca-4a9c-9608-838c3724c5b4.png">


<img width="420" alt="Screen Shot 2021-12-03 at 4 48 26 PM" src="https://user-images.githubusercontent.com/86107848/144594266-73dd1931-2854-4d41-8604-194348e98ea4.png">

2021-12-03 11:24 UTC, santosh-pingle commented
readonly view `QuestionnaireItemCheckBoxGroupViewHolderFactory` alpha .38
<img width="419" alt="Screen Shot 2021-12-03 at 4 47 20 PM" src="https://user-images.githubusercontent.com/86107848/144594559-76e8fa56-6e80-41c6-b96d-aafce37e1b9b.png">


<img width="418" alt="Screen Shot 2021-12-03 at 4 46 44 PM" src="https://user-images.githubusercontent.com/86107848/144594630-13ae6b5d-089e-4261-9406-7d72ca243b31.png">

2021-12-03 12:10 UTC, jingtang10 approved these changes

2021-12-03 17:19 UTC, merged

2021-12-08 07:56 UTC, anita-vadverao commented
Retested "Readonly" changes by adding "readOnly" :  true" attribute in Questionnaire JSON and it is properly visible after adding contrast to text. Working as expected.