Super class field mapping Resource Extraction
google/android-fhir pull request #954
Opened 2021-12-06 11:35 UTC by maimoonak

Fixes #943 

**Description**
Resource Extraction by Field allows mapping for parent class fields like DomainResource field extension for Patient class

**Alternative(s) considered**
The class just needed additional handling to traverse super class when Field not found in current class mapped

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-12-14 12:18 UTC, Tarun-Bhardwaj commented
@aditya-07 , could you please review this PR?

2021-12-17 13:10 UTC, maimoonak commented
@Tarun-Bhardwaj @aditya-07 I have fixed the failing CI issue

2021-12-21 10:02 UTC, aditya-07 requested changes

2021-12-21 10:02 UTC, aditya-07 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return superclass.getFieldOrNull(name)
superclass is nullable and may cause `NullPointerException` incase the field is not found throughout the class hierarchy.
```suggestion
    return superclass?.getFieldOrNull(name)
```

2021-12-22 11:41 UTC, maimoonak commented
@aditya-07 feedback resolved.

2021-12-22 12:45 UTC, epicadk commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +    return superclass?.getFieldOrNull(name)
```suggestion
    superclass?.getFieldOrNull(name)
```

2021-12-27 08:34 UTC, aditya-07 approved these changes
Great PR @maimoonak! LGTM!

2021-12-28 07:25 UTC, merged

2021-12-30 15:30 UTC, jingtang10 commented
@maimoonak @aditya-07: Looking through this code, I understand that the change you made is making sure a latter value is not overriding an earlier value if you're setting the same field (which is a list).

So I'm not sure the title of this PR is accurate - can you confirm? and if so can you update the title and description?

thanks

2021-12-30 15:56 UTC, maimoonak commented
@jingtang10 The main aim of PR as to allow mapping fields into superclass. For example with 
`Patient->DomainResource->Resource`
code did not allow to map tag OR extension fields into superlcass to be mapped into SDC-extraction. This PR fixes it by [line](https://github.com/google/android-fhir/pull/954/files#diff-4d2985aba5e8203b97cc5dc2eac7dbbd0c7832be34a27036d1ecfb8e4a3a3e50R622). 
Other issue which was noticed when mapping extension was that incase of multiple mapping it was always overriding first value of extension hence only last mapped extension persisted. 

The issue that was fixed into PR was 'Allow super class field mapping for SDC Resource Extraction'

2021-12-30 23:52 UTC, jingtang10 commented
thanks @maimoonak - as long as this is documented in this issue it's fine. if you can just list the two things this PR does in the description that'd be great. thanks!

2021-12-30 23:54 UTC, jingtang10 commented
But perhaps a good follow-up PR to write is to provide minimal test cases. I think your new test case is too big and testing both of the things this PR is doing.

2021-12-31 09:36 UTC, maimoonak commented
Ok. Sure would break it down into two separate cases for each functionality separately