Handle InputeditText request focus.
google/android-fhir pull request #957
Opened 2021-12-07 14:53 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #863 

**Description**
Focus was given to the next inputEditText which is not visible as soft keyboard was shown.

Now, search the focusable inputEditText in down direction and request the focus only if it found. If focusable item is not visible then focus will not be given. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-12-10 10:27 UTC, joiskash reviewed
This is a good fix! Another issue I have noticed is with the Date and time widget. Please have a look at the video that I have attached. I think you can add some similar check which will prevent this from happening. It happens with the drop down too. 

https://user-images.githubusercontent.com/48797364/145559102-660a992a-36d7-49f2-9ced-de6b570f59ad.mp4

.

2021-12-13 09:07 UTC, santosh-pingle commented
@joiskash 
Actually, this change is to fix the force close exception as mentioned in the issue #863. 
But I do not see any application crash in the attached video.

Just wanted to know whether you are talking about the application crash or something else?

2021-12-13 09:16 UTC, joiskash commented
There is no crash, but the date widget pops up every time the cursor is on the first widget and the page is changed. Its a bug. The date widget should not pop-up unless clicked on.

2021-12-13 09:22 UTC, santosh-pingle commented
Can you please create separate issue/bug for this, thanks!

2021-12-15 15:54 UTC, jingtang10 requested changes

2021-12-15 15:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +
```suggestion

    // Override `setOnEditorActionListener` to avoid crash with `IllegalStateException` if it's not possible to move focus forward.
    // See https://stackoverflow.com/questions/13614101/fatal-crash-focus-search-returned-a-view-that-wasnt-able-to-take-focus/47991577
```

2021-12-15 15:54 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
why are they different?

```suggestion
      view.focusSearch(FOCUS_FORWARD)?.requestFocus(FOCUS_FORWARD) ?: false
```

2021-12-16 07:17 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
1. With change `view.focusSearch(FOCUS_FORWARD)?.requestFocus(FOCUS_FORWARD) ?: false`
- it shows warning, please see attached image.
<img width="974" alt="warning" src="https://user-images.githubusercontent.com/86107848/146323869-ccf9c9cd-cf96-4ee0-8bb0-3cb2af766acf.png">
- Yes, focus was given to the focusable item.
   (https://user-images.githubusercontent.com/86107848/146324243-302c3cbe-e68c-4cd3-9c53-37dc23350cb1.mov).


2. With change `view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false`
-  There is no warning.
-  It scrolls page down.
   (https://user-images.githubusercontent.com/86107848/146324407-33e48607-04cf-44c8-859c-33e21f45c1d3.mov)

2021-12-16 07:32 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
Updated suggested change.

2021-12-16 08:22 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
Build fails
/Users/runner/work/android-fhir/android-fhir/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt:89: Error: Must be one of: View.FOCUS_LEFT, View.FOCUS_UP, View.FOCUS_RIGHT, View.FOCUS_DOWN [WrongConstant]

2021-12-16 09:20 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
Interesting, so I guess they: 

- https://newbedev.com/fatal-crash-focus-search-returned-a-view-that-wasn-t-able-to-take-focus
- https://stackoverflow.com/questions/13614101/fatal-crash-focus-search-returned-a-view-that-wasnt-able-to-take-focus/47991577

are probably using deprecated apis/constants.

have you tried using FOCUS_DOWN in both?

2021-12-16 09:49 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
> +      view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_FORWARD) ?: false
Updated change `view.focusSearch(FOCUS_DOWN)?.requestFocus(FOCUS_DOWN) ?: false`

2021-12-16 09:52 UTC, jingtang10 approved these changes

2021-12-16 11:06 UTC, merged