Refactor definition-based extraction for multiple resource
google/android-fhir pull request #961
Opened 2021-12-10 12:05 UTC by santosh-pingle

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #670 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Code health

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-12-10 12:33 UTC, santosh-pingle commented
@jingtang10 

- I have removed base extension type of the functions.
- I tried to create extension context data class which have current resource, bundle, questionnaire and response item
`data class ExtractionContext(
  var currentResource: Base,
  val bundle: Bundle,
  var questionnaireItem: Questionnaire.QuestionnaireItemComponent,
  var questionnaireResponseItem: QuestionnaireResponse.QuestionnaireResponseItemComponent
)`
- But not sure how to use `Map<ResourceType, List<Resource>>` which was mentioned in the issue, as bundle is passed in the extraction context to collect the extracted resource.

Created first draft, can you please review once and provide your input on it.

2021-12-17 01:32 UTC, jingtang10 requested changes
Thanks @santosh-pingle and sorry for the delay.

Please read through http://build.fhir.org/ig/HL7/sdc/extraction.html#definition-based-extraction if you haven't. I think the details in this section will inform the design decisions in this PR.

2021-12-17 01:32 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  val questionnaireResponseItem: QuestionnaireResponse.QuestionnaireResponseItemComponent
I think the extraction context should include a list of resources to be extracted, and a list of resources that have been extracted.

so every time you come across a new extraction context extension, you add the new resource to the list of resources to be extracted, and then you recursively visit the child questions, and then you move that resource to the list of resources that have been extracted.

At the end of your traversal of the questionnaire, you'll end up with the first list being empty, and the second list containing all the resources that have been extracted.

2021-12-29 10:52 UTC, santosh-pingle commented
Working on review comments

2021-12-30 14:01 UTC, santosh-pingle commented
It's still in progress.
I am trying to make changes as per review comments.
thanks!

2021-12-31 07:53 UTC, santosh-pingle commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  val questionnaireResponseItem: QuestionnaireResponse.QuestionnaireResponseItemComponent
Code is refactored as mush as possible as per review comments.

2022-01-04 09:55 UTC, jingtang10 requested changes

2022-01-04 09:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  var questionnaireResponseItemList: List<QuestionnaireResponse.QuestionnaireResponseItemComponent>
i don't think these should be in the context.

2022-01-04 09:55 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
> +  private suspend fun extractFields(extractionContext: ExtractionContext) {
i think the questionnaire items and questionnaire response items still should be what you use in the recursion. this function (and the other functions) are basically doing a tree-traversal. and the extraction context is what is passed down in the traversal to carry the extraction progress and result.

so please add those back to the param list in this function.

2022-01-06 05:33 UTC, santosh-pingle commented
looking into the review comments.

2022-01-10 14:18 UTC, closed without merging

2022-01-10 15:23 UTC, jingtang10 commented
I took the liberty of rewriting some part of the resource mapper in #1014, which is merged after speaking with @santosh-pingle and @aditya-07. It covers a little more refactoring than in this PR - notably changing the code structure for definition based extraction.

Thanks again @santosh-pingle for this work.