Throw ConverterException properly for missing numerical value
google/android-fhir pull request #986
Opened 2021-12-20 21:44 UTC by jingtang10

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #869 
Fixes #974 

**Description**

- Throw ConverterException properly for missing numerical value
- Also closes #974 which handles the follow-up comments in #952 

**Alternative(s) considered**
NA

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-12-21 13:51 UTC, epicadk commented on common/src/main/java/com/google/android/fhir/UnitConverter.kt
> +      throw ConverterException("Missing numerical value in the canonical UCUM value", e)
Should we add the link to the issue here?

2021-12-30 08:36 UTC, aditya-07 requested changes

2021-12-30 08:36 UTC, aditya-07 commented on engine/src/main/java/com/google/android/fhir/search/filter/TokenParamFilterCriterion.kt
> +data class TokenParamFilterCriterion constructor(var parameter: TokenClientParam) :
```suggestion
data class TokenParamFilterCriterion(var parameter: TokenClientParam) :
```

2021-12-30 21:55 UTC, jingtang10 reviewed
thanks both!

2021-12-30 21:55 UTC, jingtang10 commented on common/src/main/java/com/google/android/fhir/UnitConverter.kt
> +      throw ConverterException("Missing numerical value in the canonical UCUM value", e)
done

2021-12-30 21:55 UTC, jingtang10 commented on engine/src/main/java/com/google/android/fhir/search/filter/TokenParamFilterCriterion.kt
> +data class TokenParamFilterCriterion constructor(var parameter: TokenClientParam) :
done

2021-12-31 07:49 UTC, aditya-07 approved these changes
LGTM

2021-12-31 12:03 UTC, merged