Parse HTML tag in questionnair text
google/android-fhir pull request #989
Opened 2021-12-23 23:22 UTC by wantingzhang77

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]
#968
**Description**
Clear and concise code change description. 
1. Parse the html tag in questionnaire text 
2. Add a small 5dp padding between questionnaire prefix text and item text. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)
Bug fix
**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [ ] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [ ] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2021-12-26 21:08 UTC, wantingzhang77 commented
@jingtang10 I am not sure about how does codecov report error. And it reports the DatabaseImpl.kt file which I haven't touched. Could you give me some instruction on this?

2021-12-31 00:51 UTC, jingtang10 requested changes
Thanks @wantingzhang77! Great job!

Can you try to define a kotlin extension function https://kotlinlang.org/docs/extensions.html?

Something like:

```
fun String.toSpanned(): Spanned
```

So this can be reused by all widgets?

I think you may need to add some unit tests for that.

2021-12-31 00:51 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_display_view.xml
> +        android:paddingRight="@dimen/prefix_padding_horizontal"
instead of `paddingRight`, use `paddingEnd` to accommodate RTL.

or, actually, just add another view of width between these two text views

2021-12-31 00:51 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_display_view.xml
> +        android:paddingRight="@dimen/prefix_padding_horizontal"
i think this needs to be added to all widget types right?

2021-12-31 00:51 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
> +      .isEqualTo("Group header".let { HtmlCompat.fromHtml(it, HtmlCompat.FROM_HTML_MODE_LEGACY) })
Any particular reason to pick `FROM_HTML_MODE_LEGACY`?

2021-12-31 00:52 UTC, jingtang10 commented
> @jingtang10 I am not sure about how does codecov report error. And it reports the DatabaseImpl.kt file which I haven't touched. Could you give me some instruction on this?

I think the coverage report of DatabaseImpl.kt has always been a bit flakey...

2022-01-04 19:50 UTC, wantingzhang77 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactoryInstrumentedTest.kt
> +      .isEqualTo("Group header".let { HtmlCompat.fromHtml(it, HtmlCompat.FROM_HTML_MODE_LEGACY) })
https://developer.android.com/reference/androidx/core/text/HtmlCompat#summary
Different Flag format the text differently by adding new lines on different conditions. After exam it, I changed it to FROM_HTML_MODE_COMPACT, which is the most compact one. I think this fits the use of the text of questionnaire items.

2022-01-04 19:57 UTC, wantingzhang77 commented on datacapture/src/main/res/layout/questionnaire_item_display_view.xml
> +        android:paddingRight="@dimen/prefix_padding_horizontal"
I think `paddingEnd` maybe better than a perment view between these two. We only want this blank area to be there whenever a prefix presents.

2022-01-04 20:13 UTC, wantingzhang77 commented on datacapture/src/main/res/layout/questionnaire_item_display_view.xml
> +        android:paddingRight="@dimen/prefix_padding_horizontal"
Done.

2022-01-05 19:05 UTC, jingtang10 requested changes
In `MoreQuestionnaireItemComponents.kt`, there are two extension properties on `QuestionnaireItemComponent`: `localizedText` and `localizedPrefix`.

My question is, if every questionnaire item's prefix and text should be localized and also converted to `Spanned`, should you just change those properties to `localizedTextSpanned` and `localizedPrefixSpanned`?

Alternative, we could also just add an extention function that converts a `StringType` to a localized `Spanned` object. But that means when we use this we need to do

```
questionnaireItem.textElement.toLocalizedSpanned()
```

and

```
questionnaireItem.prefixElement.toLocalizedSpanned()
```

2022-01-05 19:06 UTC, jingtang10 commented on datacapture/src/main/res/layout/questionnaire_item_display_view.xml
> +        android:paddingRight="@dimen/prefix_padding_horizontal"
agreed - that's a good thought

2022-01-06 02:11 UTC, wantingzhang77 commented
@jingtang10 
I think the two ways you suggested don't differs much.
I changed those properties to `localizedTextSpanned` and `localizedPrefixSpanned`.

2022-01-06 15:56 UTC, jingtang10 approved these changes
Thanks @wantingzhang77! 👍

2022-01-08 14:42 UTC, merged