add empty option
google/android-fhir pull request #995
Opened 2022-01-02 20:08 UTC by maanuanubhav999

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #940 

**Description**
add an empty option for the dropdown widget.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

2022-01-02 20:40 UTC, maanuanubhav999 commented
Hey @jingtang10, can you give me some insights on how can I write tests cases for this condition since I tried many methods but they were not working?

## Goal
I have to click on the dropdown and select the option for the test case but I couldn't find any method to do the same.

## Thing I tried
* using setListSelection even when the pop-up is visible and the list is not empty.
* using setText but it will not invoke the click listener.
* Also looked into the source code but nothing that could help.

Something like this could easily be handled with espresso but should I use it? thanks.

2022-01-29 11:15 UTC, Tarun-Bhardwaj commented
@maanuanubhav999 , did you get a clarity on the approach or you need help on this?
CC: @jingtang10

2022-01-29 14:46 UTC, maanuanubhav999 commented
Hey, @Tarun-Bhardwaj  I would like some help with the writing test.  I am not able to find some direct method to do so.

2022-01-31 10:32 UTC, Tarun-Bhardwaj commented
> Hey, @Tarun-Bhardwaj I would like some help with the writing test. I am not able to find some direct method to do so.

@anita-vadverao , is this something you could help Anubhav with?

CC: @jingtang10

2022-01-31 18:21 UTC, jingtang10 requested changes

2022-01-31 18:21 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        answerOptionString.add(0, "-Select-")
Can you please add an empty string?

If we add something like "-Select-" we'd have to translate it to different langauges

2022-01-31 18:36 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        answerOptionString.add(0, "-Select-")
sure

2022-01-31 18:48 UTC, jingtang10 commented
Have you tried using `performClick`? search for it in our codebase.

2022-02-01 04:59 UTC, anita-vadverao commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        answerOptionString.add(0, "-Select-")
> > Hey, @Tarun-Bhardwaj I would like some help with the writing test. I am not able to find some direct method to do so.
> 
> @anita-vadverao , is this something you could help Anubhav with?
> 
> CC: @jingtang10

@maanuanubhav999 Did you try with `performClick` with `getChildAt()` to select item from drop-down?

2022-02-02 04:52 UTC, maanuanubhav999 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        answerOptionString.add(0, "-Select-")
@jingtang10 @anita-vadverao thanks for the response.

 I did try `performClick` with `getChildAt()` with AutoCompleteTextView but was unable to simulate a click on the dropdown.
 
 with AutoCompleteTextView the `getChildAt()` method does not exists.

2022-02-03 09:34 UTC, jingtang10 requested changes

2022-02-03 09:34 UTC, jingtang10 commented on datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
> +        answerOptionString.add(0, "-Select-")
does this help: https://www.examplefiles.net/cs/821426

2022-02-08 18:05 UTC, jingtang10 commented
Any update @maanuanubhav999 ?

2022-02-08 18:46 UTC, maanuanubhav999 commented
sorry @jingtang10 didn't get much time this week, will update by tomorrow for sure.

2022-02-23 20:04 UTC, jingtang10 commented
any update on this?

2022-02-23 21:43 UTC, maanuanubhav999 commented
@jingtang10 Thanks for your patience.

I did try running the espresso test but the test seems to be running forever, 
When I tried debugging it, finding the view could be archived but after performing click on it the weird running forever scenario would happen again.

So I am still working on it.

2022-02-23 21:48 UTC, jingtang10 commented
> @jingtang10 Thanks for your patience.
> 
> I did try running the espresso test but the test seems to be running forever, 
> When I tried debugging it, finding the view could be archived but after performing click on it the weird running forever scenario would happen again.
> 
> So I am still working on it. 

Thanks for the update. If you want others to be able to help you need to push your commits so others can see.

2022-02-24 12:36 UTC, jingtang10 commented
@vvikramraj is starting to work on some UI tests so maybe he will be able to help (or this will help him).

@anita-vadverao fyi also

2022-02-24 12:39 UTC, maanuanubhav999 commented
thanks @jingtang10

2022-04-12 09:19 UTC, jingtang10 commented
@epicadk @PallaviGanorkar are you able to take a look and help with this? thanks

2022-04-16 12:53 UTC, jingtang10 commented
please see #1298 from @PallaviGanorkar

2022-04-16 13:21 UTC, jingtang10 approved these changes
thanks @maanuanubhav999 for this change. approving since @PallaviGanorkar is addressing the tests in her PR #1298

2022-04-16 13:21 UTC, jingtang10 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +          .getItem(1)
you need another test case to check that the empty option is populated in the ui

2022-04-17 04:29 UTC, maanuanubhav999 commented on datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
> +          .getItem(1)
Hey @jingtang10, thanks for being patience with me, got to learn a lot.

2022-04-17 10:45 UTC, merged